### ISSUE TITLE
Electron needs to be based on node >= v10.7.0 (can get away with v10.6.0)

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#1]
Just creating an issue here so we can follow up progress. See https://github.com/electron/electron/issues/14247

So, we need node `v10.7.0` to support both:

* [`napi_create_threadsafe_function()`](https://nodejs.org/dist/latest-v10.x/docs/api/all.html#n_api_napi_create_threadsafe_function)
* [`napi_create_bigint_int64()`](https://nodejs.org/dist/latest-v10.x/docs/api/all.html#n_api_napi_create_bigint_int64).

We can tweak the c-code to temporarily get rid of `napi_create_bigint_int64()`, but we need the threads. If we do this we can use `v10.6.0`.

I checked the `electron` repo (with help of @mafintosh) and current master is pinning node on `v10.2.0` which doesn't help us right now. _But_ in the `electron/node` fork there's a branch named `electron-node-v10.6.0`.

cc @karissa @r10s @Jikstra 

_If_ we can check out that branch and build `electron` ourselves based on that branch we should be good to at least develop, which will buy us some time.

**Comment by ralphtheninja** [comment]
Another alternative is to temporarily get rid of both `napi_create_*` functions and implement a polling mechanism, since we won't be able to callback into js land via the event handler.

**Comment by ralphtheninja** [comment]
Using temporary solution for now. Basically just commented out code in `deltachat-node` to make it compile, so some stuff is broken for now. More precisely:

* we can't do events since the event handler function is never called
* we can't get a big int file size

**Comment by ralphtheninja** [comment]
We had to poll configured state for now https://github.com/deltachat/deltachat-node/commit/9a7c1a8fc5162c4d7e8a0e8610af0ed53e106da1

**Comment by Jikstra** [comment]
> If we can check out that branch and build electron ourselves based on that branch we should be good to at least develop, which will buy us some time.

I think this should be fine for the moment, don't know about the electron release cycle, but i guess they will update their node version soon? Does anybody know more about it? If they upgrade to a compatible node version in the next 2 months, i think it should be fine to rely on a development branch until then.

**Comment by ralphtheninja** [comment]
We're aware of the problem and a polling mechanism is in place until `electron` has matured. Closing.
