### ISSUE TITLE
.desktop file missing

### ISSUE THREAD

**Issue by muelli** [deltachat/deltachat-desktop#100]
For proper integration to GNU/Linux desktop systems, a `.desktop` file would be nice. https://standards.freedesktop.org/desktop-entry-spec/latest/

Likewise, appstream data would be appreciated. https://www.freedesktop.org/software/appstream/docs/

cf. https://github.com/deltachat/deltachat-desktop/issues/58

**Comment by ralphtheninja** [comment]
You could try the `.AppImage`. It contains a `deltachat-desktop.desktop` file.

**Comment by muelli** [comment]
Would it be possible to have this file generated through the build process somehow?  Like `make deltachat-desktop.desktop`

**Comment by karissa** [comment]
If the `.desktop` file contained in the `AppImage` isn't enough, let us know. Probably won't be able to spend much more time on this

**Comment by muelli** [comment]
yeah, the desktop file could do with some tags that you want the app to be found with from a shell.
Also, the appstream file needs to have the releases and some OARS rating.
