### ISSUE TITLE
Media View some html files are not "downloaded"

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1004]
instead the 'fullscreen' media view is opened and completely empty/black with only the download button shown.

**Comment by Simon-Laux** [comment]
And I forgot to add en example :man_facepalming:

**Comment by pabzm** [comment]
@Simon-Laux Can you add the example you mentioned? Or maybe explain which kind of HTML files this happens with?

**Comment by Simon-Laux** [comment]
some html files and some markdown files, I suggest just don't open render media for any document file.

**Comment by pabzm** [comment]
> I suggest just don't open render media for any document file.

sounds reasonable.

Do I understand correctly that the functionality is not broken, because one still can "download" the file, but that it is "only" ugly and inconvenient?

**Comment by Simon-Laux** [comment]
exactly its `"only" ugly and inconvenient`

**Comment by pabzm** [comment]
I fail to reproduce this. Can you please provide a file that triggers this behaviour?

**Comment by Simon-Laux** [comment]
there isn't an exact file that triggers it, for me it happens on older autocrypt html files right now, but instead of opening the fullscreen view I now get an react error:
```
Uncaught Error: Component with name RenderMedia does not exist
```

**Comment by Simon-Laux** [comment]
https://github.com/deltachat/deltachat-desktop/blob/031a67a52ee980da1b5208fc9c344c586609e6a4/src/renderer/components/Media.js#L59-L71

The 'RenderMedia' dialog doesn't exist anymore so it makes no sense to call it here anyway.
