### ISSUE TITLE
Deltachat 0.104 on Debian Buster: glibc 2.29 error. Solved

### ISSUE THREAD

**Issue by 19hundreds** [deltachat/deltachat-desktop#1006]
- Platform (linux/mac/windows): debian buster (10)
- Delta Chat Desktop Version: 0.104.0
- Expected behavior: should run after successful dpkg -i
- Actual behavior: doesn't run
- Steps to reproduce the problem: dpkg -i DeltaChat-ubuntu-19_10-0.140.0.deb
- Screenshots:
- Logs: 
```
/opt/DeltaChat/deltachat-desktop-electron: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/DeltaChat/libdeltachat/lib/x86_64-linux-gnu/libdeltachat.so)
/opt/DeltaChat/deltachat-desktop-electron: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/DeltaChat/rpgp/lib/librpgp.so)
```

If you are trying to install DeltaChat on Debian Buster (10) use only the DeltaChat-ubuntu-19* packages. All the others require an older version of libssl.

I installed with:

`sudo dpkg -i DeltaChat-ubuntu-19_10-0.104.0.deb`

The installation is successful and there are no issue with apt dependencies but then when running `deltachat-desktop` produces the error mentioned in the logs.

**SOLUTION**
Use pinning to install the package `libc6` from testing.

Create /etc/apt/preferences and add:
```
Package: *
Pin: release a=stable
Pin-Priority: 900

Package: *
Pin: release a=testing
Pin-Priority: 650
```

Update /etc/apt/sources.list and add a new entry for the testing repo

```
deb https://deb.debian.org/debian buster main contrib
deb https://deb.debian.org/debian testing main contrib
```

Then upgrade package with:

`sudo apt install -t testing libc6`

Run:

`deltachat-desktop`

It will work

**Comment by Jikstra** [comment]
Can you try again with 0.201.0? https://github.com/deltachat/deltachat-desktop/releases/tag/v0.201.0 It's very likely that your issue vanished by switching to the new rust core. Closing for now, feel free to reopen in case it still happens :)
