### ISSUE TITLE
Code for converting to signal format should be moved to model/state side

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#101]
The view should only render and not reformat data, which should be up the controller/model/state/whatever side

- [ ] `convertContentType()`
- [ ] `convertMessageStatus()`

**Comment by karissa** [comment]
i disagree because the signal format is UI/frontend dependent. So if we want to use a different UI in the future, the pieces that are monkey patching that data on to those signal components will also need to change

**Comment by ralphtheninja** [comment]
I stand corrected :smile:
