### ISSUE TITLE
Crash  immediately after start

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-desktop#1015]
The desktop client crashes immediately after start.

If I switch off wifi there is no crash.

Edit: I use mailbox.org as mailprovider.

- Platform (linux/mac/windows): Linux Ubuntu
- Delta Chat Desktop Version: v0.201.0
- Expected behavior: no crash
- Actual behavior: crash
- Steps to reproduce the problem:

1. start Delta Chat Desktop
2. Crash
- Logs: It's impossible to attache a *.toml file.
so I renamed it to *.txt. I hope this is OK.

[report-dcb72648-cc46-4f4a-95a3-adcbbc8ecc65.txt](https://github.com/deltachat/deltachat-desktop/files/3663913/report-dcb72648-cc46-4f4a-95a3-adcbbc8ecc65.txt)

**Comment by Jikstra** [comment]
This seems like a rust core problem. We should start building node bindings with debug symbols so we have correct stack traces with lines in them.

**Comment by Jikstra** [comment]
Closing as it's a core-rust issue
