### ISSUE TITLE
Impossible to set a background image (Windows)

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-desktop#1018]
- Platform (linux/mac/windows): Windows 10
- Delta Chat Desktop Version: v0.201.0
- Expected behavior: set Background image or custom color
- Actual behavior: I can set "default background" and "default color" but no "custom color" and no image. Not even the predefined images.

For my linux PC it works.

- Steps to reproduce the problem:
1. open settings
2. select a custom image or a predefined image
3. no preview beside the buttons will shown and also no background image in the chatview
- Screenshots:
- Logs:

**Comment by Simon-Laux** [comment]
I fixed it in #1016,
But we'll wait for more bugfixes to make a new release.
If you want you can download the automatic build of that version: 
https://github.com/deltachat/deltachat-desktop/runs/239534322 under artifacts (is in the top right corner)
https://github.com/deltachat/deltachat-desktop/suites/242514529/artifacts/62256
