### ISSUE TITLE
Have to use SSL/TLS or STARTTLS for IMAP. My IMAP server doesn't have both.

### ISSUE THREAD

**Issue by Niels1985** [deltachat/deltachat-desktop#1019]
When I add an account I have to use SSL/TLS of STARTTLS.
Mij IMAP server doensn't have both, now I can's run Delta Anymore.

Greetz, Niels.

**Comment by hpk42** [comment]
thanks. already fixed through https://github.com/deltachat/deltachat-core-rust/pull/628, but not yet released in desktop ...

**Comment by Jikstra** [comment]
If it's about a connection without transport encryption, you should be able to disable that in the advanced settings:
![Screenshot_20190929_024341](https://user-images.githubusercontent.com/34889164/65824105-febd4500-e262-11e9-9085-379a6eef066d.png)
