### ISSUE TITLE
Advanced Settings Ignored

### ISSUE THREAD

**Issue by Jamie96ITS** [deltachat/deltachat-desktop#1025]
- Platform (linux/mac/windows): windows
- Delta Chat Desktop Version: DeltaChat-0.201.0-win64
- Expected behavior: Login to personal mail server sans SSL
- Actual behavior: SSL Failure
- Steps to reproduce the problem: 
- Screenshots:
- Logs: https://pastebin.com/XFNVtCRA

Good day. 

I am trying to use my local mail server with Delta-Chat, my family uses it for internal communications and a few IoT uses...

It does not have a proper SSL chain, nor does it need one as it's most often accessed only on LAN. I figured like most other apps I could tell this program to use no security, and I saw that option here but when using it I fail to login with this error:

Could not connect to IMAP-server 192.168.2.21:143. (A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider. (os error -2146762487))

Other applications connect just fine without SSL, so I'm wondering if this is an issue with Deltachat trying for SSL even though I set security off?

**Comment by hpk42** [comment]
Thanks for reporting ... There is related work going on in the core: 
https://github.com/deltachat/deltachat-core-rust/pull/647

However, I would think that the currently released core with desktop
already would accept an invalid cert ... cc @link2xt

**Comment by link2xt** [comment]
@Jamie96ITS Thanks for reporting! It appears that plain IMAP was not properly tested before.

Try PR #1028 if you know have a development environment installed or try to patch your installation in-place for a quick fix. In any case, I am pretty sure setting IMAP security to "plain" configured SMTP instead.

**Comment by Jikstra** [comment]
@Jamie96ITS you can try the fixed version of @link2xt by using on of the install files of this pr:
https://github.com/deltachat/deltachat-desktop/pull/1028/checks?check_run_id=242872813

As you use windows, this should work for you: https://github.com/deltachat/deltachat-desktop/suites/245977487/artifacts/71703

Can you please try and tell us if this fixed it?

**Comment by Jamie96ITS** [comment]
No dice.

**Comment by Jikstra** [comment]
@r10s is it possible that this is the same problem as with the e2ee setting?

**Comment by link2xt** [comment]
`Client::secure` is not accepting invalid certs still, going to fix it

**Comment by Jikstra** [comment]
@r10s @link2xt any news? We probably need to update the rust core in the node bindings?

**Comment by link2xt** [comment]
I have not tested if it works since https://github.com/deltachat/deltachat-core-rust/pull/647 got merged.

Updating core is good in any case.

**Comment by link2xt** [comment]
While attempting to make #1076 work, I found that settings still don't work. Even more, they are not saved into the database properly.

Command
```
sqlite3 ~/.config/DeltaChat/*/db.sqlite 'select * from config where not keyname like "%_pw"'
```
shows
```
13|server_flags|undefined
```

Preparing a PR now. Basically the problem seems to be that `serverFlags` is passed to node bindings instead of `server_flags`.

**Comment by nicodh** [comment]
Advanced settings are persisted now but only on initial setup, not when updating in settings dialog

**Comment by nicodh** [comment]
It's also not possible to change the IMAP login name for example

**Comment by nicodh** [comment]
Can you please try again with current master?
It should be possible to create an account configured with PLAIN (at least it worked in my tests)
We still have a bug though: updating the server security in an existing account does not work yet...

**Comment by Jamie96ITS** [comment]
Works now, thanks!

I was able to login using my local, plain mail server and play around with it, finding another bug/design flaw with it but that's another matter.
