### ISSUE TITLE
Trying to load emoji resources via insert-css

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#104]
![screenshot from 2018-10-01 10-56-37](https://user-images.githubusercontent.com/308049/46279257-e4299080-c568-11e8-9aa3-91fd551dfa44.png)

**Comment by karissa** [comment]
this is very minor, missing html requests don't do much bad

**Comment by ralphtheninja** [comment]
> this is very minor, missing requests don't do much bad

Agreed!

**Comment by karissa** [comment]
fixed in https://github.com/deltachat/deltachat-desktop/commit/901edc16711074b300b88255b9638606d1b43bba
