### ISSUE TITLE
Linter / Codefromatter for SCSS?

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1040]
would be useful IMO, I currently use the vscode plugin `michelemelluso.code-beautifier` for it, but that isn't a solution for @Jikstra because he uses a different editor.
I would like something like standardjs in terms of auto fixing capabilities and vscode integration availability (but the latter one isn't a huge deal breaker because I can add npm tasks to vscode.)

**Comment by Jikstra** [comment]
https://stylelint.io/ seems one solution which is still maintained, didn't look further into it, but i like the idea.
