### ISSUE TITLE
remove group icon from chatlist

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1042]
during some ui session, @Jikstra and me came to the conclusion, that a a group icon is superfluous; on desktion it is ugly anyway and would need some maintainance. better get rid of  it.

some reasons from https://github.com/deltachat/deltachat-android/pull/1052 :

- it is pretty clear to the user, what is a group and what not
- less noise on the screen
- also, many users use an emoticon as the fist character in a group name, this now looks better
- one thing less to explain
- the other icons stand out more, eg. the verification-icon
- it is some work to maintain a group icon for all situations, this can be better spent for other things
- also, neither telegram, nor signal, nor whatsapp use a group icon

**Comment by Simon-Laux** [comment]
It looks like it's already gone...

**Comment by r10s** [comment]
great!

**Comment by Jikstra** [comment]
@r10s i removed it right after we talked about it ^^

**Comment by r10s** [comment]
this desktop team is incredible fast!
