### ISSUE TITLE
Unread bagde doesn't update

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1043]
When you are in an chat it just counts up and is only updated after you switch to another chat and re-enter the previous chat again.

@nicodh and/or @Jikstra might know what is causing it.

**Comment by Jikstra** [comment]
We're only calling mark_msg_as_read when selecting a chat. So we don't do that on an incoming msg.

**Comment by hpk42** [comment]
k but you consider it a a bug, right? 

basicaly while i am in the chat view and chatting, notifications gather
in the chatlist for that chat sometimes, and also the messages i am interacting
with in the chat view are not marked as read.

**Comment by Simon-Laux** [comment]
@Jikstra https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API might be a solution for detection

**Comment by Simon-Laux** [comment]
My current ideas:
## with intersection observer:

on window focused || on scroll || on new message in focused chat:

    loop through intersections
        is message unread?
           -> mark as read

## cheap, bad but quick solution:

on new message:

    is in selected chat?
        is window focused?
            -> mark message as read
        
on window focused:

    mark chat as noticed (and all messages in it, too?)
