### ISSUE TITLE
file sending is broken

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1053]
it doesn't sent them, but all text messages after send the image/file.

**Comment by MIntrovrt** [comment]
When trying to reproduce, it did send the file and message (unencrypted) and it seems to have gotten to the target mail server, since I got a mail from the target server telling me the file-type is forbidden (which was on purpose).

**Comment by Simon-Laux** [comment]
strange stuff, anyways this needs investigation

**Comment by Simon-Laux** [comment]
seems to be fixed already in current master
