### ISSUE TITLE
Import secret key? 

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#1057]
On rust-master and released .deb one apparently can't select a secret key for import in the settings. cc @toberndo  what is the exact pattern there that filters the selection -- is there a bug?

**Comment by toberndo** [comment]
macOS 10.15, DeltaChat-0.201.0. -> in the file selection dialog there is no match pattern displayed, all files are not selectable.

**Comment by Simon-Laux** [comment]
there is also another bug where somehow 4 files are created instead of 1 or 2 when exporting
