### ISSUE TITLE
option to quit the app is missing

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#107]
on mac, closing the main window does not quit the app.
so, after closing the main window, the menu bar stays there without real functionality.

i would suggest to quit the whole app of the main window is closed.
if possible, also a "quit" option should be added to the "Delta.Chat" menu as this seems to be standard on mac.

**Comment by ralphtheninja** [comment]
Also see https://github.com/deltachat/deltachat-desktop/issues/95

**Comment by r10s** [comment]
ahh, i see. sorry, did not notics that. fell free to close this as a duplicate if appropriate.

**Comment by karissa** [comment]
this is duplicate, let's close it
