### ISSUE TITLE
Wrong positioning for messages with status failed

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-desktop#1079]
If a message could not be sent for some reason (status: failed) a red exclamation mark is shown and the context menu is shown outside of the message bubble.
![message-send-failed](https://user-images.githubusercontent.com/1428457/67601443-ac454a80-f774-11e9-9825-085375419b20.png)

(for reproducing the message status can be set to 24 in database)

**Comment by Simon-Laux** [comment]
was fixed in  #1074
