### ISSUE TITLE
the app name forces the extension .app to be visible on mac

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#108]
typically, the mac does not show the extension for apps on mac.
however, for the names including a dot, the extension seems to be show, which looks weird and unusual to the user.

if there is no other solution, i would suggest to use just `Delta Chat` (without the dot) instead of `Delta.Chat`.
this is also the name used for the android app.

**Comment by r10s** [comment]
@ralphtheninja here is a screenshot: Delta.Chat is the only app with a visibe extension. if i rename the app to "Delta Chat" manually, the .app extension is hidden as for all the other apps.

it't probably not the most important issue, however.

<img width="1054" alt="bildschirmfoto 2018-10-01 um 16 06 07" src="https://user-images.githubusercontent.com/9800740/46293572-36cc7200-c594-11e8-8025-715c85ab78f2.png">

**Comment by Simon-Laux** [comment]
Is this still happening/relevant?

**Comment by r10s** [comment]
> Is this still happening/relevant?

have not tried this recently, however, I assume if the internal name is still `Delta.Chat`, it's still shown as `Delta.Chat.app`.

**Comment by Simon-Laux** [comment]
In the newer versions the name in CamelCase so the name is displayed as `DeltaChat` without the `.app` so I'll close this issue.
