### ISSUE TITLE
Delete Message should have a confirm dialog

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1083]
Because It's easy to click on it on accident. happened to me two times recently while using the touch-pad.

**Comment by violoncelloCH** [comment]
How about an option to easily undo a deletion instead of an annoying confirmation dialog?
Just an undo option which is there for e.g. 20s before the message is completely removed...

**Comment by Simon-Laux** [comment]
I agree that this would be better, but it is much more coding effort.
What about a shift click to skip the conformation dialog instead?

**Comment by Simon-Laux** [comment]
telegram has a conformation dialog, too. I don't think it is too annoying.

**Comment by r10s** [comment]
i agree with @Simon-Laux, i would just add a normal deletion dialog, no shift-workarounds or so.

@violoncelloCH we're currently in release-mode, we do not want to add much code and/or complexity, we just want to get things stable :) if you like, however, you can suggest an "undo" or so in the [forum](https://support.delta.chat).

**Comment by hansal7014** [comment]
Hi,
Please can I work on this issue?
Thanks.

**Comment by Simon-Laux** [comment]
@hansal7014 yeah of course go for it. If you have questions feel free to post them here in this issue.

**Comment by Simon-Laux** [comment]
https://github.com/deltachat/deltachat-desktop/blob/master/src/renderer/components/helpers/ChatMethods.js
here are a few confirm dialogs for reference.
