### ISSUE TITLE
0.201.0-pre: doesnt pull messages after standby

### ISSUE THREAD

**Issue by g6094199** [deltachat/deltachat-desktop#1097]
- Platform (linux/mac/windows): ubuntu 19.04/19.10
- Delta Chat Desktop Version: 0.201.0-pre
- Expected behavior: pull messages after system standby
- Actual behavior: nothing happens until restart of DS
- Steps to reproduce the problem: I see this behavior on 2 Ubuntu systems (Lenovo T450s and 2012's MacBook)
- Screenshots:
- Logs:

**Comment by Jikstra** [comment]
@hpk42 fixed some related bugs in core, and it should be already a lot better with latest desktop master. Hpk, what's the state of the fixes? Are they all merged?
