### ISSUE TITLE
libsasl2 not found

### ISSUE THREAD

**Issue by gerroon** [deltachat/deltachat-desktop#11]
Hi

I am trying to install tthis on Debian testing x64

meson.build:12:0: ERROR:  Native dependency 'libsasl2' not found

npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN deltachat-desktop@1.0.0 license should be a valid SPDX license expression
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deltachat-node@0.9.0 install: `./scripts/rebuild-all`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deltachat-node@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by ralphtheninja** [comment]
@gerroon Hi. See requirements for `deltachat-core` https://github.com/deltachat/deltachat-core

**Comment by gerroon** [comment]
Ok , I think I got it. I removed the folder cloned it build it again. It seems to wokr now, at least I got the ui up and running
