### ISSUE TITLE
package-lock.json out of date

### ISSUE THREAD

**Issue by muelli** [deltachat/deltachat-desktop#1111]
@Jikstra changed package.json in d18411166beab6f14f5d1def0de85064317b1269 without updating package-lock.json

The released version (v0.804.0) does not contain that package and building thus fails.

Can you roll a .1 release with an updated package-lock.json?

**Comment by Jikstra** [comment]
Can we have a script which checks this? This happens again and again, not sure why, probably npm being not as picky as it should.

**Comment by okdistribute** [comment]
@Jikstra you have to run npm install --update

**Comment by Simon-Laux** [comment]
@Jikstra probably just forgot to stage the change. We could save a hash of the package-lock and compare it with the new hash after running `npm i` maybe @lefherz could throw a quick github action together that does it.
I updated the package-lock file in #1117 so @Jikstra could do a release for @muelli  and then we can close this issue.

**Comment by lefherz** [comment]
Something like this? Not sure what exactly you want

**Comment by lefherz** [comment]
Do you want this check at every PR or at release only?

**Comment by Simon-Laux** [comment]
every pr should be fine
