### ISSUE TITLE
0.804.0 AppImage installation doesn't create .desktop file if .deb was installed before

### ISSUE THREAD

**Issue by lefherz** [deltachat/deltachat-desktop#1112]
- Platform (linux/mac/windows): linux xubuntu 18.04
- Delta Chat Desktop Version: 0.201.0 deb -> 0.804.0 AppImage

## Expected behavior: 

When I install a new version through the AppImage, and I click "yes", when I am asked to integrate it into the system, the AppImage overwrites the old version, even if it was installed with a .deb file.

## Actual behavior:

1) If I close the open DeltaChat window, and open the Delta Chat AppImage with a double click on the file, it asks me integrate it into the system. If I click either yes or no, it opens the 0.804.0 window. I am logged into my accounts as expected, but all conversations are missing.

2) If I now close the open DeltaChat window, and open DeltaChat from the application finder, it just starts the 0.201.0 version. I am logged in, and all conversations are there.

3) If I have the 0.201.0 version open, and I double-click the AppImage file, it asks me to integrate Delta Chat 0.804.0 into the system. If I click either yes or no, just brings the 0.201.0 window to the foreground. I am logged in, and all conversations are there.

Each of these 3 paths is reproducible, and it doesn't seem to make a difference when I choose to integrate the AppImage into the system.

## Steps to reproduce the problem:

1. Install Delta Chat 0.201.0 via https://github.com/deltachat/deltachat-desktop/releases/download/v0.201.0/DeltaChat-0.201.0-amd64.deb
2. Login with a user account, start a chat
3. Close Delta Chat 0.201.0
4. Download https://github.com/deltachat/deltachat-desktop/releases/download/v0.840.0/DeltaChat.0.840.0.AppImage
5. `chmod +x DeltaChat.0.840.0.AppImage`
6. `./DeltaChat.0.840.0.AppImage`
7. When it asks you whether to integrate it into the system, click "Yes" (clicking "No" doesn't make a visible difference)
8. see that you are logged in, but can't see the conversation
9. close the Delta Chat 0.804.0 window
10. open Delta Chat from the application finder
11. see that it opens the 0.201.0 version, you are logged in, you can see the conversation
12. `./DeltaChat.0.840.0.AppImage`
13. When it asks you whether to integrate it into the system, click "Yes" (clicking "No" doesn't make a visible difference)
14. see that it opens the 0.201.0 version, you are logged in, you can see the conversation

**Comment by Jikstra** [comment]
> If I close the open DeltaChat window, and open the Delta Chat AppImage with a double click on the file, it asks me integrate it into the system. If I click either yes or no, it opens the 0.804.0 window. I am logged into my accounts as expected, but all conversations are missing.

The builds i uploaded tonight were broken. I silently reuploaded them this morning. Please try them again.

**Comment by lefherz** [comment]
Okay, I tried again, it helped somewhat - now the conversations aren't missing anymore when I open the AppImage via doubleclick.

But otherwise it still opens the 0.201.0 when I open Delta Chat via the appfinder. And if Delta Chat 0.201.0 is still open when I double click the AppImage, it also just brings 0.201.0 to the front.

**Comment by Jikstra** [comment]
If a desktop instance is currently running, it will just get focused, no matter the version that is currently running. I think the problem is that you have 2 versions installed, one is a 'proper system installed one via a .deb package' and the other one is this more 'hacky appimage install'. Also it's possible that for an appimage to be fully integrated into the system, you need the appimaged installed. https://docs.appimage.org/user-guide/faq.html#question-how-can-i-integrate-appimages-with-the-system

@Simon-Laux knows more about appimages i think

**Comment by Simon-Laux** [comment]
AppImages are portable packages, how well they integrate with your desktop env depends on your configuration. Normaly when you click integrate a .desktop file is created, on manjaro there is a program called app image launcher that replaces this dialog with its own one, when you click there on integreate it moves the appimage to an application folder that is read by the start menu.

It should not replace anything installed. it should just add a new entry to the start menu.

**Comment by lefherz** [comment]
Okay, I uninstalled the .deb with `apt remove deltachat-desktop`, and started the AppImage again, clicked on "Yes" for integration into the system, but no .desktop file was created... 

Usually it works for me, I have several other programs installed with an AppImage. But even after deltachat-desktop.deb is uninstalled, the .desktop file doesn't get created, says `$ find ~ -name *.desktop`

**Comment by Simon-Laux** [comment]
https://www.electron.build/configuration/appimage
> Since electron-builder 21 desktop integration is not a part of produced AppImage file. AppImageLauncher is the recommended way to integrate AppImages.

https://github.com/TheAssassin/AppImageLauncher

seems like its an electron-builder thing, I'll upgrade it. hopefully that removes the non working dialog.
