### ISSUE TITLE
show encryption info for groups

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1118]

**Comment by pabzm** [comment]
@Simon-Laux Could you please describe more detailedly what you mean? As far as I know there is no "encryption info" for groups like there is for 1-on-1-chats.

**Comment by Simon-Laux** [comment]
Its more about whether we should add it. It would be a list of members an their fingerprints.

**Comment by pabzm** [comment]
Ok, thanks for the info!

So this is a feature idea, no other client does this yet, right?

I'm moving it to Project Resurrection until we (or "the forum") has decided if it's actually worthwhile and until there's time for implementing it.

**Comment by Simon-Laux** [comment]
I believe it was implemented but removed, and I would like to know why it was removed or If we should add it again? Project Resurection seems reasonable

**Comment by Jikstra** [comment]
There's no group encryption status as far as i know, it's always per contact. My idea would be to implement this in the profile view and if clicking on a profile in group edit/info allow to get there?

**Comment by Simon-Laux** [comment]
I believe to remember we had a for loop in that dialog that dumped all fingerprints of group participants.
Yeah profile view is good, maybe we could then also remove the menu point to don't have too many options in that menu.

**Comment by Jikstra** [comment]
Yup we had a for loop but not sure if this was any helpful.

**Comment by pabzm** [comment]
👍 for using the profile view for profile-related actions and information, and to remove those links from the main menu

**Comment by r10s** [comment]
ftr, since https://github.com/deltachat/deltachat-core-rust/pull/2186 there is [`dc_chat_get_encrinfo()`](https://c.delta.chat/classdc__context__t.html#afdda9fd371e9179cd2bf94278e61a35f) which is also available in desktop on right-clicking groups.
