### ISSUE TITLE
Failed to load video message

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#112]
Platform: Linux

I sent a video message from my phone to desktop with an empty text message as a result.

**Comment by karissa** [comment]
Is there a video screenshot @r10s ?

**Comment by karissa** [comment]
@ralphtheninja can you be a bit more specific? What was displayed on the screen?

**Comment by ralphtheninja** [comment]
> @ralphtheninja can you be a bit more specific? What was displayed on the screen?

An empty text message.

**Comment by ralphtheninja** [comment]
Just to clarify. This is what I see on desktop when sending video from mobile:

![screenshot from 2018-10-31 21-47-28](https://user-images.githubusercontent.com/308049/47817697-a336be80-dd56-11e8-949b-f5f6af126655.png)

**Comment by ralphtheninja** [comment]
It seems `conversations` needs `screenshot.url` to be set and we somehow need to get/generate a thumbnail for the video:

![screenshot from 2018-10-31 22-10-48](https://user-images.githubusercontent.com/308049/47819189-142ba580-dd5a-11e8-83d9-1b26e166cd18.png)
