### ISSUE TITLE
Prefill advanced settings with unprefixed, not "configured_" values

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop#1121]
See https://github.com/deltachat/deltachat-android/issues/1106#issuecomment-550467772

Maybe also show `configured_` value as a placeholder, because it may be useful to know which port is currently used.

**Comment by r10s** [comment]
+1 for placeholder.

if i find some time i'd like to refactor android and ios to using placeholders "Automatic" and "See above" (for the SMTP password).

once configured, i would show "Automatic (imap.server.bla)" and so on.
