### ISSUE TITLE
First mesage to new contact is not shown properly and vanishes

### ISSUE THREAD

**Issue by duckdalbe** [deltachat/deltachat-desktop#1122]
- Platform (linux/mac/windows): Linux
- Delta Chat Desktop Version: 0.840.0-PREVIEW
- Expected behavior: Show initial message to a new contact in message window
- Actual behavior: An initial message sent to a new contact from a third device is only shown in the list of contacts, but not in the message window. Following messages make the initial message disappear from the list of contacts, while it still doesn't show up in the message window — it is lost from DCD.
- Steps to reproduce the problem: 1. Send an initial message to a new contact with another client (I used deltachat-android 0.950.0, then look at deltachat-desktop (doesn't matter if deltachat-desktop was open already or not): message is not shown in message window. 2. Send a reply or another message from another client: first message vanishes from DCD.
- Screenshots: 
![deltachat-desktop-missing-message](https://user-images.githubusercontent.com/557240/68374069-6a3ce100-0144-11ea-9d5a-11f6832b1346.png)

- log: [2019-10-04-10-04-51.log.txt](https://github.com/deltachat/deltachat-desktop/files/3818730/2019-10-04-10-04-51.log.txt) (stripped by private messages)

**Comment by nicodh** [comment]
Just tried to reproduce this with master and everything worked as expected. Can you please test with next release?

**Comment by pabzm** [comment]
I will as soon as my DC-desktop stops crashing on startup, please wait a little.
