### ISSUE TITLE
Add icon on message that has location

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1126]
like on android

**Comment by hansal7014** [comment]
Hi @Simon-Laux,
I don't think there is a location streaming feature on the desktop version. So does this enhancement only add the location icon to the messages with location sent from the android or ios apps?

**Comment by Simon-Laux** [comment]
Its an experimental feature, that's hidden by default. It needs to be enabled in the settings first.

**Comment by Simon-Laux** [comment]
First we would need that icon, maybe we can get it from the android repo, or we can try to quickly throw together our own in inkscape.
After that it would be included like the encryption lock. (css class + conditional including a `<div>` or `<span>` with this class of the icon. The scss class would then includes the svg file with the `@include color-svg` macro)

**Comment by hansal7014** [comment]
Got it. Thanks for the explanation.
