### ISSUE TITLE
tweak support for device-chat

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1129]
the latest core has support for so called "device chats".

in general, these chats are normal chats and will already be displayed on desktop.

however, there should be the correct subtitle displayed ("device_talk_subtitle", stockstring DC_STR_DEVICE_MESSAGES (68) should be added and the device chat should hide send-controls.

for reference, these are the corresponding changes on ios: https://github.com/deltachat/deltachat-ios/pull/379

**Comment by Simon-Laux** [comment]
What do I need to do that the device chat is shown?

**Comment by r10s** [comment]
the ui chat will become visible automatically _as needed_. as any other chat, it will just be returned by dc_get_chatlist(). this issue is only about tweaking the subtitle and the input control. even now, without explicit changes, the device-chat will already work.

for testing, however, you can force the device-chat to become visible by calling [dc_add_device_msg()](https://c.delta.chat/classdc__context__t.html#a18dd64c26e363260463b3c466dda29a7). at some point, dc_add_device_msg() will be called from the core.

**Comment by Simon-Laux** [comment]
Ok, then this needs first support in the node bindings
