### ISSUE TITLE
Automate packaging Process for releases

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1136]
- [x] Mac OS with signing
 -> https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/ looks like good guide
- [x] windows setup
- [x] windows portable (see https://support.delta.chat/t/please-make-deltachat-for-windows-a-truly-portable-standalone-program/675/6)
- [x] Linux AppImage
- [ ] Linux AppImage deltas to last versions for updates?
- [x] Linux .Deb
- [ ] windows .appx for windows store

**Comment by Jikstra** [comment]
@missytake

**Comment by missytake** [comment]
> Linux AppImage deltas to last versions for updates

@Simon-Laux does the build process produce this already?

**Comment by missytake** [comment]
>  Mac OS with signing -> https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/ looks like good guide

Can we add such a certificate to our GitHub secrets? Or do we want to do this on a separate machine?

**Comment by Simon-Laux** [comment]
Seperate machine of course

Am 8. Dezember 2019 14:55:26 MEZ schrieb missytake <notifications@github.com>:
>>  Mac OS with signing ->
>https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/
>looks like good guide
>
>Can we add such a certificate to our GitHub secrets? Or do we want to
>do this on a separate machine?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/deltachat/deltachat-desktop/issues/1136#issuecomment-562951016

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by missytake** [comment]
Okay, maybe we should merge #1186. There are still 3 checkboxes not included in that PR, but they may not be that important for now:

- macOS build with signing and notarizing can not be done with a github action alone
- AppimageUpgrade would be nice, but no merge-blocker for now
- Windows Appstore build: what's the status here?

**Comment by Simon-Laux** [comment]
you must build the appx on a windows runner.
please apply this diff for the appx to work [diff-get-on-msstore.txt](https://github.com/deltachat/deltachat-desktop/files/3940533/diff-get-on-msstore.txt)

**Comment by missytake** [comment]
hm, can you please reupload the file without colors? I constantly get this error:

```
$ git apply diff-get-on-msstore.txt
error: unrecognized input
```

Can you export it with `git diff --no-color`? See https://stackoverflow.com/a/53191568

**Comment by Simon-Laux** [comment]
just do it manually its not that much

**Comment by missytake** [comment]
Okay :)

btw, @Jikstra @Simon-Laux are you okay with it, if the Windows GitHub action:
- gets executed when someone pushes a tag with `v*` to master
- creates a release draft automatically 
- and uploads the .appx there?
- the other deliverables would be available on get.delta.chat as usual. Pushing them to the release draft might be possible as well.

Then we could download the .appx from there, use this release draft for the final github release?

**Comment by missytake** [comment]
I closed #1186 for now, treefit wrote a script for the mac in bb33 which does the same.

**Comment by Jikstra** [comment]
@missytake i'm currently not using tags starting with a `v`, just have the plain version number. deltachat-core-rust does the same. If this makes things easier for any script i can do it again of course.

**Comment by missytake** [comment]
don't worry - treefit's script doesn't look for a `v`.

**Comment by Simon-Laux** [comment]
ah you did omit the `v` purposefully? I did a new tag with it because I assumed you forgot it :smile:

**Comment by Simon-Laux** [comment]
apple rejected a current build(1.1.1):
 ITMS-90296: App sandbox not enabled - The following executables must include the "com.apple.security.app-sandbox" entitlement with a Boolean value of true in the entitlements property list: [( "chat.delta.desktop.electron.pkg/Payload/DeltaChat.app/Contents/Frameworks/DeltaChat Helper (GPU).app/Contents/MacOS/DeltaChat Helper (GPU)", "chat.delta.desktop.electron.pkg/Payload/DeltaChat.app/Contents/Frameworks/DeltaChat Helper (Plugin).app/Contents/MacOS/DeltaChat Helper (Plugin)", "chat.delta.desktop.electron.pkg/Payload/DeltaChat.app/Contents/Frameworks/DeltaChat Helper (Renderer).app/Contents/MacOS/DeltaChat Helper (Renderer)", "chat.delta.desktop.electron.pkg/Payload/DeltaChat.app/Contents/Frameworks/DeltaChat Helper.app/Contents/MacOS/DeltaChat Helper", "chat.delta.desktop.electron.pkg/Payload/DeltaChat.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/crashpad_handler", "chat.delta.desktop.electron.pkg/Payload/DeltaChat.app/Contents/Frameworks/Squirrel.framework/Versions/A/Resources/ShipIt", "chat.delta.desktop.electron.pkg/Payload/DeltaChat.app/Contents/MacOS/DeltaChat" )] Refer to App Sandbox page at https://developer.apple.com/devcenter/mac/app-sandbox/ for more information on sandboxing your app.

ITMS-90237: The product archive package's signature is invalid. Ensure that it is signed with your "3rd Party Mac Developer Installer" certificate.

ITMS-90236: Missing required icon - The application bundle does not contain an icon in ICNS format, containing both a 512x512 and a 512x512@2x image. For further assistance, see the Apple Human Interface Guidelines at https://developer.apple.com/macos/human-interface-guidelines/icons-and-images/app-icon

**Comment by Jikstra** [comment]
@Simon-Laux i think we can close this, your script does most of this, everything else i would say is mac os appstore related or windows appstore related
