### ISSUE TITLE
Advanced 

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#114]
see https://github.com/deltachat/deltachat-desktop/issues/110#issuecomment-426696494

**Comment by gerroon** [comment]
Any word on when one can add manual server settings?

**Comment by ralphtheninja** [comment]
> Any word on when one can add manual server settings?

At the moment it's just me doing stuff more or less randomly. Currently we have no big roadmap, but we will get there. There are tonnes of stuff to use and we're not even sure about what we want the final app to look like. But in a couple of weeks, the delta team will meet and flesh out future plans in greater detail. Just sit tight and we'll get to this issue :smile:

**Comment by ralphtheninja** [comment]
I think we should implement this asap. Several people have been asking for it and can't use the application at all right now.

**Comment by Jikstra** [comment]
Fixed with https://github.com/deltachat/deltachat-desktop/commit/0c3ce52319cd37b39dcbf6fd1c348972b13fdf16, closing this issue for now

**Comment by ralphtheninja** [comment]
Uh, I changed the title by mistake. Changing back.
