### ISSUE TITLE
Hidden location messages are shown in message list

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-desktop#1143]
If a location message is received for the current chat, it is displayed in the list although the hidden flag is set to true.
If you reload the chat the messages are hidden as expected but if the chat is open on receiving time they are shown...

**Comment by nicodh** [comment]
Resolved

**Comment by pabzm** [comment]
Has this bug re-appeared? Or why did you re-open?

**Comment by nicodh** [comment]
Yes it reappeared but not only if the messages arrive in an open chat but anytime...

**Comment by Simon-Laux** [comment]
I can confirm that it reappeared, but could be actually a core thing. (I still use the 0.901' core most of the time)

**Comment by nicodh** [comment]
Is fixed and not reproducable any more...
