### ISSUE TITLE
0.840.0-pre: still doesnt pull messages after standby 

### ISSUE THREAD

**Issue by g6094199** [deltachat/deltachat-desktop#1149]
In relation to https://github.com/deltachat/deltachat-desktop/issues/1097 nothing has changed

    Platform (linux/mac/windows): ubuntu 19.04/19.10
    Delta Chat Desktop Version: 0.840.0-pre
    Expected behavior: pull messages after system standby
    Actual behavior: nothing happens until restart of DS
    Steps to reproduce the problem: I see this behavior on 2 Ubuntu systems (Lenovo T450s and 2012's MacBook)
    Screenshots:
    Logs:

**Comment by Jikstra** [comment]
Thanks for reporting again, there's currently a lot going on on the whole imap/smtp connection thing, so it currently is a moving target as we're implementing imap/smtp on the new rust async feature. We're going to release a new version the next days if possible and will check it out myself and see if I can reproduce it (it was definetly a bug @hpk42 put quite some effort in to fix it, but probably there are still some code paths which produce this bug).

**Comment by g6094199** [comment]
Seems to be fixed with 0.901.0....at least on Linux boxes.

THX!
