### ISSUE TITLE
macOS-version doesn't move emails from INBOX

### ISSUE THREAD

**Issue by v84** [deltachat/deltachat-desktop#1150]
Hi,
I couldn't find this mentioned anywhere but on two installations of the macOS version, the app does not move the emails from the INBOX to the DeltaChat folder. The behaviour is weirdly strange. Sometimes it moves all the emails received to the DeltaChat folder but leaves the sent emails in the INBOX and sometimes it moves nothing at all.

There is only one DeltaChat-App connected to the accounts we tested with.

- Platform (linux/mac/windows): macOS 10.14.6
- Delta Chat Desktop Version: 0.840.0-PREVIEW
- Expected behavior: Delta Chat moves all Delta Chat related messages and status notifications to the Delta Chat folder
- Actual behavior: The app only moves certain emails of differing kinds to the folder
- Steps to reproduce the problem: Install Delta Chat, connect to account and start chatting.

**Comment by Simon-Laux** [comment]
is this desktop specific or does this occur on iOS and android too?

**Comment by Jikstra** [comment]
I guess this is the core bug: https://github.com/deltachat/deltachat-core-rust/issues/896

Could be already fixed, let's release a new -node release :)

**Comment by Simon-Laux** [comment]
please reopen when this issue still exists on the new version (0.900.0)
