### ISSUE TITLE
Messages appear in wrong chat (on scrolling up)

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1158]
On repeated scrolling up and switching the chat the messages get mixed up so that I see messages from different chats in the chatview

**Comment by adbenitez** [comment]
same issue for me, beside the messages appearing in wrong chats, the scrolling simply doesn't work, I get the same messages when scrolling up in an endless loop, also then trying to delete a message or see the message info doesn't work
