### ISSUE TITLE
Be clear with public and private methods in DeltaChatController

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#116]
All methods called from the outside (e.g. from `src/main/ipc.js`) should be public, the rest of the methods should be private (or at least pseudo private, starting with `_`). This makes it a lot clearer which code is internal to the controller and what's exposed. Best thing would be for private methods to actually be private.

**Comment by karissa** [comment]
Using _ is fine node.js practice and I'm fine with that.

**Comment by ralphtheninja** [comment]
https://github.com/deltachat/deltachat-desktop/commit/3f88e8408f18b8b95e813b4ffdbf6786ca710193
