### ISSUE TITLE
Select last chat on start + some smaller adjustments

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-desktop#1164]
On initial (empty) start select device chat

**Comment by nicodh** [comment]
Select last chat on start

**Comment by nicodh** [comment]
Tabs in Media view

**Comment by nicodh** [comment]
When changing to another chat start in message view (even if media view was selected before)

**Comment by nicodh** [comment]
Show green instead of grey check marks in chat list

**Comment by Simon-Laux** [comment]
I think all of these points are solved meanwhile.
