### ISSUE TITLE
ask the user before a dropped file is actually sent

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1169]
i just discussed with @Simon-Laux that an advanced attachment-staging-area as on android is planned.

however, as a quick fix for _now_ it would be great if a simple `confirm()` or sth. like that would be added.

this way the user has a chance to avoid an accidentally picked up file being sent by an thoughtless mouse movement :)

**Comment by adbenitez** [comment]
+1 for the advanced attachment-staging-area as on android

**Comment by Simon-Laux** [comment]
This is only for the quick confirmation dialog, the progress of the real thing is tracked in #739
