### ISSUE TITLE
Editing a group results in a blank screen

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#1170]
Go to a group chat, press the "three dots" button, press the "edit group" button, the DeltaChat windows goes blank and you have to restart the app

- Platform (linux/mac/windows): GNU/Linux
- Delta Chat Desktop Version: master (less than a week ago)

**Comment by nicodh** [comment]
Can't reproduce this. Do you see anything in the logs?

**Comment by nicodh** [comment]
Or try current master maybe?

**Comment by Simon-Laux** [comment]
what is in the electron devTools? maybe it's an react error?

**Comment by Simon-Laux** [comment]
@adbenitez's internet connection is really slow so he uses me as a proxy

I can't update right now, I will be offline and don't know when I will be able to do big downloads, compiling/updating desktop is an expensive task for me ;) 
the error is in `EditGroup.js:127` 
```
Uncaught TypeError: Cannot read property 'filter' of null
at EditGroupInner (EditGroup.js:127)
at renderWithHooks (react-dom.development.js:16241)
at updateFunctionComponent (react-dom.development.js:18328)
at beginWork$1 (react-dom.development.js:20151)
at HTMLUnknownElement.callCallback (react-dom.development.js:336)
at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
at invokeGuardedCallback (react-dom.development.js:440)
at beginWork$$1 (react-dom.development.js:25738)
at performUnitOfWork (react-dom.development.js:24662)
at workLoopSync (react-dom.development.js:24638)
```

(when I tried to save the log, I was asked to save this 3 files) 

[-1575257743126.log](https://github.com/deltachat/deltachat-desktop/files/3909316/-1575257743126.log)
[-1575257743127.log](https://github.com/deltachat/deltachat-desktop/files/3909317/-1575257743127.log)
[-1575257743128.log](https://github.com/deltachat/deltachat-desktop/files/3909318/-1575257743128.log)

**Comment by adbenitez** [comment]
the issue was a dummy contact without `addr` attribute, that while getting that contact using the python bindings returned the dummy contact, the `getContact` function of the node bindings was returning `null` which caused the error and blank screen.
