### ISSUE TITLE
Messages not marked as forwarded

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#1176]
messages users forward to me, or messages I forward, don't have the label "forwarded message" at the top like in DC-Android

- Platform (linux/mac/windows): GNU/Linux
- Delta Chat Desktop Version: current master (hours ago)
- Steps to reproduce the problem: forward a message or ask someone to forward a message to you

**Comment by adbenitez** [comment]
(please note this reports are due I am testing Delta Chat Desktop, I'm NOT requesting to tackle ASAP)

**Comment by adbenitez** [comment]
in the case of forwarded images, the label "forwarded message" is half covered by the image, need some margin at the bottom

**Comment by jezzielee420337** [comment]
src/renderer/components/message/Message.js
