### ISSUE TITLE
Emoji sorted inmediately in "Frequently Used" category

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#1177]
When user click an emoji in the "Frequently Used" category it is re-sorted immediately, which causes some troubles when user clicks several times an emoji and then it change position with another emoji and a wrong emoji is inserted by accident, list should be updated when opening the emoji popup menu again, once open keep current emojis in current position (as done in DC-Android currently)

- Platform (linux/mac/windows): GNU/Linux
- Delta Chat Desktop Version: current master (some hours ago)

**Comment by adbenitez** [comment]
(please note this reports are due I am testing Delta Chat Desktop, I'm NOT requesting to tackle ASAP)

**Comment by Simon-Laux** [comment]
I don't know how easy it is to solve, because we use a library for the emoji picker.
So we need to ask https://github.com/missive/emoji-mart for a solve I assume.

**Comment by Jikstra** [comment]
Or hack around the library ^^

**Comment by Simon-Laux** [comment]
> Or hack around the library ^^

Not in this case, its too deep in it.. maybe to solve #1181, but not for this one.

**Comment by Simon-Laux** [comment]
looks this isue was already fixed in emoji mart so we just need to update the dependency https://github.com/missive/emoji-mart/issues/366
https://github.com/missive/emoji-mart/pull/417

**Comment by Simon-Laux** [comment]
but the version we need isn't released yet

**Comment by Jikstra** [comment]
Can we depend on the git of emoji mart and pin to a specific commit?

**Comment by Simon-Laux** [comment]
Looks like there were already a few new versions, but they are not documented in the release section only as tags and in the changelog. So we can probably upgrade to version 3, but it has some breaking changes so we need to keep an eye on https://github.com/missive/emoji-mart/blob/master/CHANGELOG.md
