### ISSUE TITLE
Disable horizontal scrolling in messages area (chat area)

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#1178]
it is possible to scroll horizontally in the chat area (the area where the messages bubbles live) this is sometime more noticeable producing an horizontal scrolling while you are vertically scrolling using a touch-pad

**Comment by adbenitez** [comment]
(please note this reports are due I am testing Delta Chat Desktop, I'm NOT requesting to tackle ASAP)

**Comment by Simon-Laux** [comment]
In which chat do you experience this? are Stickers present?

**Comment by Simon-Laux** [comment]
This reappeared: this time the media queries in `scss/message/_message.scss` are responsible.

**Comment by Jikstra** [comment]
I only experienced this if we have a image that overflow the MessageList. Or does this happen in other situations too?
