### ISSUE TITLE
Documents view tab shows elements missplaced

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#1179]
Documents files in the "Documents" tab of a chat, aren't shown in a grid layout, apparently (see the screenshot)

- Platform (linux/mac/windows): GNU/Linux
- Delta Chat Desktop Version: current master
- Screenshots:
![files](https://user-images.githubusercontent.com/24558636/70201533-e8a98600-16e4-11ea-84b8-b63d0c53c351.png)

**Comment by adbenitez** [comment]
(please note this reports are due I am testing Delta Chat Desktop, I'm NOT requesting to tackle ASAP)

**Comment by Simon-Laux** [comment]
This is normal for the time being, we will transform this tab into a dialog eventually anyway and then we'll make it look nice.

**Comment by Simon-Laux** [comment]
as I said we will redo this when moving the gallery to a dialog
