### ISSUE TITLE
Chat isn't opened at the end if there are an image near the bottom

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#1180]
Every time I start Delta Chat, and open a chat where there are an image in the visible frame, the chat isn't at the end, I can't see the latest messages, the current position is some messages before. After I open the chat, then going to other chat and back to this chat, the chat is at the end even if I didn't scrolled it, so it is probably something related to the image loading process that affect layout calculation or so.

- Platform (linux/mac/windows): GNU/Linux
- Delta Chat Desktop Version: current master (some hours ago)

**Comment by adbenitez** [comment]
(please note this reports are due I am testing Delta Chat Desktop, I'm NOT requesting to tackle ASAP)

**Comment by Simon-Laux** [comment]
this might be a duplicate issue of #477

**Comment by Jikstra** [comment]
https://github.com/deltachat/deltachat-desktop/pull/1161 will fix this
