### ISSUE TITLE
Duplicated emojis

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#1181]
DC-Desktop and DC-Android have this issue, in the emoji menu, there are duplicated emojis, several of them are repeated in the "Smileys & People" category, this happens with emojis that have gender

- Platform (linux/mac/windows): GNU/Linux
- Delta Chat Desktop Version: current master (some hours ago)
- Screenshots:
![dup-emoji](https://user-images.githubusercontent.com/24558636/70202720-83579400-16e8-11ea-8608-6c44248d5d12.png)

**Comment by adbenitez** [comment]
(please note this reports are due I am testing Delta Chat Desktop, I'm NOT requesting to tackle ASAP)

**Comment by Simon-Laux** [comment]
So the emoji have the gender-less variant before the gendered variants.
This is the normal behavior of emoji-mart https://missive.github.io/emoji-mart/ (ca. 4 mb when visiting the example site).
So this is also rather an issue for the library https://github.com/missive/emoji-mart/issues. (if its important enough)

**Comment by Simon-Laux** [comment]
I'll close this as this is the expected behavior and most of the male and neutral emojis are a bit different if one looks closely.
