### ISSUE TITLE
AppImage panics and crashes after startup at fetching messages

### ISSUE THREAD

**Issue by missytake** [deltachat/deltachat-desktop#1182]
I had this problem before, I think a mail of death is causing this. When I was first fetching the mail, it took a few seconds to get it and crash, at the second try it always crashes after a few seconds (apparently it tries to do the same thing again).

Throwing away the db fixed this problem once, I'll try to find out which mail causes this.

- Platform (linux/mac/windows): linux
- Delta Chat Desktop Version: 0.804.0
- Expected behavior: The client is able to fetch messages and work.
- Actual behavior: When it fetches messages, it crashes. Probably because of one particular mail.
- Steps to reproduce the problem: Receive a malicious mail and start the client.
- Logs:

<details><summary>Direct console output</summary>
<pre><code>
Logfile: /home/user/.config/DeltaChatDev/logs/2019-12-05-11-27-31.log.tsv
init: 2039.728ms
Well, this is embarrassing.

deltachat_ffi had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "/tmp/report-ecd77225-1df8-467e-95b4-1889a5f2a173.toml". Submit an issue or email with the subject of "deltachat_ffi Crash Report" and include the report as an attachment.

- Authors: Delta Chat Developers (ML) <delta@codespeak.net>

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
</pre></code>
</details>

<details><summary>report file: /tmp/report-ecd77225-1df8-467e-95b4-1889a5f2a173.toml</summary>
<pre><code>
name = 'deltachat_ffi'
operating_system = 'unix:Ubuntu'
crate_version = '1.0.0-beta.6'
explanation = '''
Panic occurred in file 'src/libcore/option.rs' at line 378
'''
method = 'Panic'
backtrace = '''
stack backtrace:
   0:     0x7fdecc04b6c7 - <unknown>
   1:     0x7fdecc049b23 - backtrace::capture::Backtrace::new::hb0dd4020032a535d
   2:     0x7fdecc20f147 - <unknown>
   3:     0x7fdecbf88c77 - human_panic::handle_dump::hb460e44955385d54
   4:     0x7fdecb71f1f9 - <unknown>
   5:     0x7fdecc06eaf6 - std::panicking::rust_panic_with_hook::hf385e0a05e771036
   6:     0x7fdecc06e592 - <unknown>
   7:     0x7fdecc06e476 - rust_begin_unwind
   8:     0x7fdecc0971dd - core::panicking::panic_fmt::h581f7a1e5499d350
   9:     0x7fdecc09711c - core::panicking::panic::hf6893ada3b8c575b
  10:     0x7fdecb7a58ec - <unknown>
  11:     0x7fdecb79f54e - deltachat::imap::Imap::fetch::ha95b2dda1cbd8510
  12:     0x7fdecb7c6cf3 - deltachat::job_thread::JobThread::fetch::ha1411ac8dcab71b0
  13:     0x7fdecb8a1943 - deltachat::job::perform_mvbox_fetch::h8e6ebceb34606dd7
  14:     0x7fdecb7216dd - dc_perform_mvbox_fetch
  15:     0x7fdecb713718 - <unknown>
  16:     0x7fdee27c46db - start_thread
  17:     0x7fdedc88788f - __clone
  18:                0x0 - <unknown>
'''
</pre></code>
</details>

<details><summary>log file: /home/user/.config/DeltaChatDev/logs/2019-12-05-11-27-31.log.tsv</summary>
<code><pre>
"2019-12-05T10:27:32.122Z"	"main/index"	"INFO"		"cwd /home/user/.config/DeltaChatDev"
"2019-12-05T10:27:32.124Z"	"main/deltachat/login"	"INFO"		"Using deltachat instance /home/user/.config/DeltaChatDev/636f6d706c347878407465737472756e2e6f7267"
"2019-12-05T10:27:32.221Z"	"main/menu"	"INFO"		"rebuilding menu with locale en"
"2019-12-05T10:27:32.304Z"	"main/deltachat/login"	"INFO"		"Ready"
"2019-12-05T10:27:32.308Z"	"main/deltachat/login"	"INFO"		"dc_get_info"	{"mdns_enabled":"1","public_key_count":"38","is_configured":"1","sentbox_watch":"1","entered_account_settings":"xxx@testrun.org imap:unset:***:unset:0:cert_automatic smtp:unset:0:unset:0:cert_automatic 0","configured_sentbox_folder":"Sent","number_of_contacts":"40","level":"awesome","sqlite_version":"3.29.0","database_version":"55","sqlite_thread_safe":"1","e2ee_enabled":"1","fingerprint":"1E65B7AC6813A378D86C7EABA58CD9998E77DC12","mvbox_watch":"1","arch":"64","inbox_watch":"1","private_key_count":"2","display_name":"xxx","folders_configured":"3","configured_mvbox_folder":"DeltaChat","messages_in_contact_requests":"2","database_dir":"/home/user/.config/DeltaChatDev/636f6d706c347878407465737472756e2e6f7267/db.sqlite","bcc_self":"1","deltachat_core_version":"v1.0.0-beta.6","mvbox_move":"1","number_of_chats":"39","blobdir":"/home/user/.config/DeltaChatDev/636f6d706c347878407465737472756e2e6f7267/db.sqlite-blobs","used_account_settings":"xxx@testrun.org imap:xxx@testrun.org:***:testrun.org:993:cert_automatic smtp:xxx@testrun.org:***:testrun.org:587:cert_automatic AUTH_NORMAL IMAP_SSL SMTP_STARTTLS ","number_of_chat_messages":"366"}
"2019-12-05T10:27:34.261Z"	"main/state"	"INFO"		"Saving state to /home/user/.config/DeltaChatDev/config.json"
"2019-12-05T10:27:34.580Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.dc.on (/tmp/.mount_deltacIExFdy/resources/app.asar/src/main/deltachat/controller.js:243:11),\nDeltaChat.emit (events.js:182:13),\nhandleEvent (/tmp/.mount_deltacIExFdy/resources/app.asar/node_modules/deltachat-node/lib/deltachat.js:747:12),\nDeltaChat.binding.dcn_set_event_handler (/tmp/.mount_deltacIExFdy/resources/app.asar/node_modules/deltachat-node/lib/deltachat.js:35:7)"	"\"Message already in DB\""
</pre></code>
</details>

**Comment by Simon-Laux** [comment]
I encountered the same error with with current deltachat git aur package. Its a core crash that seems to be resolved in a current core.
<details>
<summary>Crash-log</summary>

name = 'deltachat_ffi'
operating_system = 'unix:Manjaro'
crate_version = '1.0.0-beta.6'
explanation = '''
Panic occurred in file 'src/libcore/option.rs' at line 378
```
method = 'Panic'
backtrace = '''
stack backtrace:
   0:     0x7f661c43b6c7 - <unknown>
   1:     0x7f661c439b23 - backtrace::capture::Backtrace::new::hb0dd4020032a535d
   2:     0x7f661c5ff147 - <unknown>
   3:     0x7f661c378c77 - human_panic::handle_dump::hb460e44955385d54
   4:     0x7f661bb0f1f9 - <unknown>
   5:     0x7f661c45eaf6 - std::panicking::rust_panic_with_hook::hf385e0a05e771036
   6:     0x7f661c45e592 - <unknown>
   7:     0x7f661c45e476 - rust_begin_unwind
   8:     0x7f661c4871dd - core::panicking::panic_fmt::h581f7a1e5499d350
   9:     0x7f661c48711c - core::panicking::panic::hf6893ada3b8c575b
  10:     0x7f661bb958ec - <unknown>
  11:     0x7f661bb8f54e - deltachat::imap::Imap::fetch::ha95b2dda1cbd8510
  12:     0x7f661bbb6cf3 - deltachat::job_thread::JobThread::fetch::ha1411ac8dcab71b0
  13:     0x7f661bc91943 - deltachat::job::perform_mvbox_fetch::h8e6ebceb34606dd7
  14:     0x7f661bb116dd - dc_perform_mvbox_fetch
  15:     0x7f661bb03718 - <unknown>
  16:     0x7f66273e04cf - start_thread
  17:     0x7f6625cde2d3 - clone
  18:                0x0 - <unknown>
```

</details>

**Comment by hpk42** [comment]
On Thu, Dec 05, 2019 at 02:35 -0800, Simon Laux wrote:

> I encountered the same error with with current deltachat git aur package. Its a core crash that seems to be resolved in a current core.
> <details>
> <summary>Crash-log</summary>
> 
> name = 'deltachat_ffi'
> operating_system = 'unix:Manjaro'
> crate_version = '1.0.0-beta.6'

beta.6 is four weeks old.  needs to be rechecked with a current desktop master.

**Comment by Simon-Laux** [comment]
Yeah, thats the point, it uses the old node version.

Am 5. Dezember 2019 14:58:52 MEZ schrieb holger krekel <notifications@github.com>:
>On Thu, Dec 05, 2019 at 02:35 -0800, Simon Laux wrote:
>
>> I encountered the same error with with current deltachat git aur
>package. Its a core crash that seems to be resolved in a current core.
>> <details>
>> <summary>Crash-log</summary>
>> 
>> name = 'deltachat_ffi'
>> operating_system = 'unix:Manjaro'
>> crate_version = '1.0.0-beta.6'
>
>beta.6 is four weeks old.  needs to be rechecked with a current desktop
>master.
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/deltachat/deltachat-desktop/issues/1182#issuecomment-562139911

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by missytake** [comment]
Fixed - tested with desktop master, core beta.15.
