### ISSUE TITLE
if main process is blocked, frontend process is blocked too. always.

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#1185]
Bad news guys, seems like whenever the main process is blocked, the renderer process is blocked too. Which is likely the reason why the ui feels unresponsive every now and then.

https://medium.com/actualbudget/the-horror-of-blocking-electrons-main-process-351bf11a763c

https://twitter.com/NumaanAshraf/status/968496732278374400

The in problem more details is, on a callDcMethodAsync what actually happens is, that we send an ipc event to the main process. But if the main process is busy, sending the event will block until the main process is idling again.
I would suggest pushing the websocket server. Probably do it in nodejs for the first moment.

**Comment by Simon-Laux** [comment]
> Probably do it in nodejs for the first moment.
That would only solve the problem when said web socket server doesn't run in the main process

**Comment by Jikstra** [comment]
> That would only solve the problem when said web socket server doesn't run in the main process

Yes.

**Comment by r10s** [comment]
wrt backup #1215 - i think dc_imex() works in the same way as dc_configure() - and we do not have issues on configure, so maybe there is an easier fix somewhere.

**Comment by Jikstra** [comment]
Yup probably something else.

**Comment by Simon-Laux** [comment]
Let's fix the current bugs first and release before experimenting with new technologies

**Comment by Jikstra** [comment]
Thinking about this a bit, I think it makes more sense to make the expensive api calls async in the node bindings. Everything else will lead to other problems if we stay in the js eco system.

**Comment by r10s** [comment]
i totally agree with that :)
