### ISSUE TITLE
First message in Chat is not visible

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-desktop#1189]
- Platform (linux/mac/windows): Linux
- Delta Chat Desktop Version: 0.840.0-PREVIEW
- Expected behavior: See all messages
- Actual behavior: the first message in a chat is not visible
- Steps to reproduce the problem:

1. receive a message for a not yet existing chat (you also can delete a existing chat and then receive a first message.)
2. The chat window show nothing. 
3. receive a second message. This will be shown.

This also happens if you send a autocrypt message. The first one is not visible.

**Comment by Simon-Laux** [comment]
duplicate of #1122
