### ISSUE TITLE
Crash if a "could not delivered" error-message is in the inbox

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-desktop#1190]
- Platform (linux/mac/windows): Linux
- Delta Chat Desktop Version: 0.840.0-PREVIEW
- Expected behavior: no crash
- Actual behavior: crash
- Steps to reproduce the problem:
1. send a message to a not existing mail address
2. wait until the error message reach the inbox.
3. Crash.
4. not able to start DC until you deleted the error-message.

**This is a example of the error message:**
```
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of
its recipients. This is a permanent error. The following address(es)
failed:

not-existing-mailaddress@gmx.de:
SMTP error from remote server for RCPT TO command, host: mx01.emig.gmx.net (212.227.17.5) reason: 550 Requested action not taken: mailbox unavailable



--- The header of the original message is following. ---
```

**Comment by nicodh** [comment]
I just tried to reproduce this. I also sent a mail to an non existing gmx address. I had no crash. I see the "could not deliver" message in the inbox, but DC Desktop does not crash. I also sent a message to a non existing domain and it didn't crash ...?

**Comment by webratte** [comment]
Later I will try to create a log file and publish it here.

**Comment by webratte** [comment]
OK, in the current Version 0.900.0-PREVIEW it seems to fixed on a magical way ;-)

So we can close this issue. :+1:

**Comment by r10s** [comment]
@webratte thanks for re-checking and for coming back to this issue!
