### ISSUE TITLE
Invalid Markdown parsing

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#1191]
when I receive a message like this in delta chat:
"write to me_19@example.com or follow @me_@mastodon.social in the fediverse"

it is displayed like:
"write to me`19@example.com or follow @me`@mastodon.social in the fediverse"

where the marked text is in italics. Testing that text here, Github parses it correctly. I think in the case of @ the preceding  underscore shouldn't be parsed as italics.

**Comment by Simon-Laux** [comment]
I think its hard to fix with the current library we use.

**Comment by adbenitez** [comment]
add option to disable markdown then???
context:
getting this constantly in a conversation with Mastodon users with "_" in their username.

**Comment by Simon-Laux** [comment]
you can wrap the email in back ticks (`) to make the inline code, that would be a workaround.
