### ISSUE TITLE
Custom Imap server?

### ISSUE THREAD

**Issue by gerroon** [deltachat/deltachat-desktop#12]
Hi

Is it possible to use a custom imap server with the desktop likew e can on Android? My server's imap is not imap.myserver.com

thanks

**Comment by ralphtheninja** [comment]
@gerroon No, it's currently not possible. Only possible with automatic configuration.

You are aware of that the desktop app is under heavy development, right?

**Comment by ralphtheninja** [comment]
@gerroon Please also see our support forum for similar questions. https://support.delta.chat/

**Comment by gerroon** [comment]
@ralphtheninja yes I realize it is not a finished project, that is why I was asking for custom server, maybe an FR?

**Comment by ralphtheninja** [comment]
> @ralphtheninja yes I realize it is not a finished project, that is why I was asking for custom server, maybe an FR?

This will most likely be implemented given some time. But feel free to discuss feature requests on the forum!
