### ISSUE TITLE
Create and add icons for windows

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1212]
This is a requirement for uploading to the Microsoft store, MS Visual studio (not code, the normal one) has a generator for it, but you'll need to have a windows os + login with a ms account after 30days.
- https://www.electron.build/configuration/appx#appx-assets
- https://docs.microsoft.com/en-us/windows/uwp/design/style/app-icons-and-logos

the icon can be found at https://github.com/deltachat/interface/blob/master/icons/delta-v7-pathed.svg

**Comment by Simon-Laux** [comment]
@NeoRon82 generated the required icons for windows.
see https://github.com/deltachat/interface/pull/32
now we only need to add them to the desktop repo

**Comment by Jikstra** [comment]
For electron itself we need to add the icon as .ico or .png in at least 256x256px: https://www.electron.build/icons
