### ISSUE TITLE
Backup of larger DB freezes desktop for a minute

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#1215]
Importing a large DB (1.5GB) freezes Elektron/the desktop while core is starting the backup.  The backup is, however, happening in the imap-thread, and not i think with a sync-call to core.  So the blocking on Desktop is probably for other reasons -- is it maybe blocking on waiting for the first CONFIGURATION_PROGRESS event?  

Versions: On core 1.0.0-beta.15  current node and desktop/master 82108558f978109b6cc5b71203208a6e39f8b8d3

**Comment by Simon-Laux** [comment]
might be related to #1185

**Comment by Jikstra** [comment]
Not fixable before #1185

**Comment by Simon-Laux** [comment]
`freezes the app` like `ubuntu window doesn't react` or the progressbar stands still?

**Comment by hpk42** [comment]
DC desktop window becomes grey and unreactive, and yes, stands still.

**Comment by Jikstra** [comment]
This is an indication that the backend process is busy waiting for deltachat-node/core-rust to complete something. Probably we aren't starting the export process in an own thread?

**Comment by hpk42** [comment]
If you trigger an export via dc_imex, this returns immediately. 
progress is then indicated through events. 

the export process is already running independently in the imap-thread.
