### ISSUE TITLE
Current master does not update MessageView on Message-Sent/Received  

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#1220]
Pretty sure that two days before this worked fine ... now if i select a chat, and scroll down (or simply stay down, do not scroll) i don't see the message update.  the Chatlist shows the new message already.  It basically means you can't do a to-and-fro active chat.

**Comment by nicodh** [comment]
Can't reproduce this with current master. The only issue I have is that the message list does not scroll down to show the new mesage (although it should...)

**Comment by r10s** [comment]
i can reproduce this with the 0.900.0-PREVIEW (dmb downloaded from github) on mac, in fact, this prevents chatting.

tried this with a fresh chat, but also happens for existing ones. cannot scroll to the new messages, they are not shown.

**Comment by nicodh** [comment]
Ok- after updating dc node & dc core I have the same issue...

**Comment by nicodh** [comment]
But since the chat list shows the new message I don't think it's an issue of core or node bindings...
very strange...

**Comment by r10s** [comment]
ios and android work seems to work with the most recent core, so this is probably fine this time :)

**Comment by adbenitez** [comment]
probably the same issue as https://github.com/deltachat/deltachat-desktop/issues/1222 ??
see also: https://github.com/deltachat/deltachat-desktop/pull/1229

**Comment by nicodh** [comment]
Should be fixed in current master. Can you confirm please?

**Comment by hpk42** [comment]
yes, works for me, thanks!
