### ISSUE TITLE
Group changes not updated inmediately

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#1221]
(**NOTE:** I am constantly pulling the repo and testing master so all my reports are for current code)

when I remove a memeber from a group, the group still shows the same number of members until I select another chat and then select the previous chat again

**Comment by hpk42** [comment]
Yes, had the same issue, discussed it today with @jikstra -- 
wasn't immediately clear if it's easy to fix or not, unfortunately.

**Comment by Simon-Laux** [comment]
Reminds me of #916

Am 12. Dezember 2019 00:16:31 MEZ schrieb holger krekel <notifications@github.com>:
>Yes, had the same issue, discussed it today with @jikstra -- >
>wasn't immediately clear if it's easy to fix or not, unfortunately. >
>>
>On Wed, Dec 11, 2019 at 10:46 -0800, Asiel Díaz Benítez wrote:>
>> (**NOTE:** I am constantly pulling the repo and testing master so all
>my reports are for current code)>
>> >
>> when I remove a memeber from a group, the group still shows the same
>number of members until I select another chat and then select the
>previous chat again>
>> >
>> -- >
>> You are receiving this because you are subscribed to this thread.>
>> Reply to this email directly or view it on GitHub:>
>> https://github.com/deltachat/deltachat-desktop/issues/1221>
>>
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/deltachat/deltachat-desktop/issues/1221#issuecomment-564776391

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by adbenitez** [comment]
also, maybe related to the regression #1222 ???

**Comment by Simon-Laux** [comment]
somehow the issue got closed before it was fixed.

**Comment by Simon-Laux** [comment]
> maybe related to the regression #1222 ???

No it's still #916 that was closed before being properly fixed.
