### ISSUE TITLE
Receiving message in chat but message not added to the chat area

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#1222]
I opened a chat with another test email, send 3 consecutive messages from the other side, in my delta chat the messages are received and shown in the chat list in the last message preview of the chat, but in the opened chat the message doesn't appear until I start typing something (and the scroll isn't moved to the end) or when changing to other chat and going back to the chat, probably related to my previous issue

**Comment by Jikstra** [comment]
Do you use the latest master? Can you provide us the logs from your developer console? This would show us what events you received from core.

**Comment by Jikstra** [comment]
Ah can reproduce it.

**Comment by adbenitez** [comment]
this issue seems to be a duplicate of https://github.com/deltachat/deltachat-desktop/issues/1220 ???
