### ISSUE TITLE
order of yes/no buttons

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1223]
the current order of yes/no buttons eg. in the "delete" dialog is a bit unexpected. showing "cancel" on the right is contrary to what the user has learnt from most uis.

![Screen Shot 2019-12-11 at 23 08 49](https://user-images.githubusercontent.com/9800740/70664888-a1367300-1c6b-11ea-8c7f-cd7979876090.png)

as a simple fix, i would swap the buttons. it would also be nice to use "cancel" and "delete" as labels (we already have strings for that) instead of "yes" and "no". finally, it is great that the destructive option is shown in red :)

moreover, when touching this, is it probably a good idea to have a look at similar dialogs. EDIT: just noticed that for the "delete account" and "leave group" dialogs, but there are probably more.

**Comment by Simon-Laux** [comment]
I agree with having the option to rename the buttons.
The switching of the buttons is an attempt to catch users that instantly click away dialogs and then think after they clicked it away.

**Comment by r10s** [comment]
> The switching of the buttons is an attempt to catch users that instantly click away dialogs and then think after they clicked it away.

esp. then, we should follow common standards - where cancel is on the left (and buttons are usually standing much closer together btw). have a look at other delete-dialogs - eg. here on github, try to delete a message.

also, the delete confirmation dialog does not appear without reasons - the user did something before and the dialog is the result from that. that is different from a dialog appearing without any user actions.

**Comment by Simon-Laux** [comment]
Ok you convinced me. Lets switch them and add the possibility for custom button labels.

**Comment by Simon-Laux** [comment]
![2019-12-14_11-42](https://user-images.githubusercontent.com/18725968/70847633-d0fd9a80-1e66-11ea-987a-7c9b3bed7666.png)

something like this?
