### ISSUE TITLE
remove markdown from chatlist

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1227]
the current desktop-only device-message uses markdown (tbh, i do not like that as we cannot really use markdown in the device-messages coming from core currently; so we have two types of styles. of messages).

however, this issue is not about markdown as such, but that the markdown is also displayed in the chatlist. i think the chatlist should be clean in this regard, so no bold, italic or whatever. bold eg. is also used for showing an unread chat. having some markup here would make the whole list too noisy. also telegram and others do not show markdown in the chatlist btw.

**Comment by Simon-Laux** [comment]
_Can you please open 2 issues instead of reporting both in the same issue..._

> however, this issue is not about markdown as such, but that the markdown is also displayed in the chatlist. i think the chatlist should be clean in this regard, so no bold, italic or whatever. bold eg. is also used for showing an unread chat. having some markup here would make the whole list too noisy. also telegram and others do not show markdown in the chatlist btw.

we could strip the markdown from the text.

> the current desktop-only device-message uses markdown (tbh, i do not like that as we cannot really use markdown in the device-messages coming from core currently; so we have two types of styles. of messages).

In my opinion its ok, I plan work on markdown in the core soon anyway.

**Comment by adbenitez** [comment]
> In my opinion its ok, I plan work on markdown in the core soon anyway.


I hope the issue of "some_email@ex.com someother_@email.com" wrongly parsed to italics, get fixed then, because it causes information lost

**Comment by r10s** [comment]
> Can you please open 2 issues instead of reporting both in the same issue...

it is basically only one issue, the first paragraph are just some thoughts :) but yes, you're right.

**Comment by r10s** [comment]
> In my opinion its ok, I plan work on markdown in the core soon anyway.

it is not only the core. there are android and ios as well. and it is some work - with probably lots of cornercases, to handle as @adbenitez pointed out. it is not that i do not like markdown, but i would not go for that soon on android or ios - and therefore i tend to avoid it for now.
