### ISSUE TITLE
Contacts display name changes are not updated

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#1228]
The display_name/chat-title of contacts are always the same as the first time you get a contact request from a contact. This means that if you are in a group, a contact can be "the cat" for you and "the dog" for other members, and you name the contact in the group using his old nick, or see others naming "the dog" and you don't understand who is "the dog", etc. Also this cause that if an user did a typo in his display name or something like that, he/she can't "fix" the error for already contacted users.

in the database, in the table "contacts", column "authname", the new display name is stored correctly by core, don't seems to exists a core event for this kind of changes.

- Delta Chat Desktop Version: master

**Comment by Simon-Laux** [comment]
I suspect that this bug comes from core, does it only happen on desktop? how is the name in the database?

**Comment by adbenitez** [comment]
> I suspect that this bug comes from core, does it only happen on desktop? how is the name in the database?


IIRC DC-Android also has the same problem for me, but the new display name is correct in the database, but in the column `authname`, the `name` column keeps the old value, maybe dc clients expect the `name` column to have the real/actual display name, it is not clear to me what is the purpose of the authname, maybe @r10s can give some light here?

**Comment by r10s** [comment]
the core has `name` and `authname` fields. the ui only use `name` directly.

- `authname` is the name spread by the sender together with mails send out; moreover, this name is "authorized" to be sent out to 3rd persons. what you enter into "Your profile / Name" becomes the `authname` for others.  `authname` cannot be modified by api functions.
so if Alice and Bob have a group and Bob invited Claire, Claire gets the authname "Alice" from Bob.

- `name` is a string a person can give to any contact, this can be sth. as "mama" then. this name is not sent to others. the `name` can be modified by the api.

so, this is about the database fields.

to get a name to show on the screen, there are different functions, see https://c.delta.chat/classdc__contact__t.html

wrt issue: yes, might be that the core does sth. wrong here, maybe file an additional issue there.

**Comment by adbenitez** [comment]
will open an issue in core, and discuss about this issue there, since this affects all clients

**Comment by adbenitez** [comment]
see: https://github.com/deltachat/deltachat-core-rust/issues/1014

**Comment by adbenitez** [comment]
on the other hand, `dc_contact_get_display_name()` seems to do things correctly:
```
Get display name.

This is the name as defined by the contact himself, modified by the user or, if both are unset, the email address.

This name is typically used in lists. To get the name editable in a formular, use dc_contact_get_name().
```

maybe it is that dc-desktop is using `dc_contact_get_name()` instead???

**Comment by Simon-Laux** [comment]
> maybe it is that dc-desktop(and dc-android) is using dc_contact_get_name() instead???

Nope its using displayName, just looked at the code.

What about the chat name?

**Comment by Simon-Laux** [comment]
@adbenitez is it fixed? The core issue is closed so I assume it is fixed, but I haven't tested it yet.

**Comment by Simon-Laux** [comment]
@adbenitez told me that It was solved.
