### ISSUE TITLE
Increase default autogenerated keysize to 4096RSA.

### ISSUE THREAD

**Issue by GintokiHub** [deltachat/deltachat-desktop#1230]
RSA 2048Keys as default auto-generated keys for encryption are an edge case.
While they might be secure now, I highly doubt for how long. 
For private conversations I don't trust a 2048RSA standard. I imagine others will feel the same way.

Would it be possible to increase the size to 4096bits RSA?
As for keysize itself 3kb extra doesn't seem like it would produce overhead data wise, as for computational time / overhead, almost every phone and desktop will be able to handle the uptick to 4096RSA, I would assume?

**Comment by r10s** [comment]
we will probably switch to ecc keys in one of the next releases; these keys are much smaller than rsa keys at the same security.

we are not using larger rsa keys as they have some significant drawbacks:

- speed is an issue, eg. key generation easily changes from a few seconds to minutes, see eg. https://github.com/deltachat/deltachat-android/issues/511 and https://github.com/deltachat/deltachat-core/issues/376 - but also encryption and signing is much slower with larger keys

- also size is an issue, eg. we gossip keys to allow encryption of whole keys (gossiping means to add keys of other group members to the encrypted part of the message), this would easily double the size if many messages.

also, doubling the bits does not double the security, in fact the win is much lower than one would suspect, eg. the effective key strenght from 2048 to 3072 changes from 112 to 128 bits only.

for these reasons we decided to use rsa 2048 for now and to switch to ecc soon™

**Comment by r10s** [comment]
closing this issue, we use this issue tracker mainly for actionable items on the desktop ui. feel free, for disussions, please use the forum, https://support.delta.chat

**Comment by adbenitez** [comment]
right now, I would like message size were 3KB less, if this is done, I hope you provide a way to definitely disable encription at all, I don't need it full time, and it is expensive for me

**Comment by adbenitez** [comment]
nevermind, ignore my previous comment, I am reading from email and overlooked the other replies and that the issue was closed
