### ISSUE TITLE
Clicking the play button of a video doesn't actually play it

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#1234]
when you click the play button of a video in the chat area, it is expanded to the full window, but isn't actually played, user has to click the play button again 

- Platform (linux/mac/windows): GNU/Linux
- Delta Chat Desktop Version: master

**Comment by Simon-Laux** [comment]
This is because the 'autoplay' attribute wasn't in camelCase like react wanted it to be.
That will be fixed with merging #1378, which also plays videos in the chatlist without full screening them, though you can fullscreen them manually if you want.
