### ISSUE TITLE
Do the T-Dance

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1235]
Its about time to update/pull translations and push untranslated strings to transifex

**Comment by OzancanKaratas** [comment]
If you let me, I want to import desktop translations into source. Then @r10s pushes it into Transifex.

**Comment by Simon-Laux** [comment]
@OzancanKaratas sorry for answering that late I pulled the translations in.
If you still want to import the untranslated strings feel free to do that and make a pr to my pr, then I can push them to transifex.
