### ISSUE TITLE
Application crashed

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#1253]
I tried to change group image while a message was sending(but doesn't seems to be related to the crash), core crashed, last shell output:

```
621.5s [D]main/ipc: EVENT_DC_DISPATCH_CB (261) : messageList.getMessageIds 40
621.5s [D]main/ipc: EVENT_DC_DISPATCH_CB (262) : chatList.getChatListItemsByIds 40
621.6s [D]main/ipc: EVENT_DC_DISPATCH_CB (263) : messageList.getMessages 
621.7s [D]main/ipc: EVENT_DC_DISPATCH_CB (264) : chatList.getChatListIds 0,,
622.1s [D]main/ipc: EVENT_DC_DISPATCH:  messageList.setDraft [ 40, '' ]
623.5s [D]main/ipc: EVENT_DC_DISPATCH_CB (266) : getContacts2 2,
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Receive Error: Os {
    code: 104,
    kind: ConnectionReset,
    message: "Connection reset by peer",
}
Well, this is embarrassing.

deltachat_ffi had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "/tmp/report-f08c4e72-90c4-4754-b25f-d766557dcb2e.toml". Submit an issue or email with the subject of "deltachat_ffi Crash Report" and include the report as an attachment.

- Authors: Delta Chat Developers (ML) <delta@codespeak.net>

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!
```

- Platform (linux/mac/windows): GNU/Linux
- Delta Chat Desktop Version: master
- Logs:
[report-f08c4e72-90c4-4754-b25f-d766557dcb2e.toml.txt](https://github.com/deltachat/deltachat-desktop/files/3965253/report-f08c4e72-90c4-4754-b25f-d766557dcb2e.toml.txt)

**Comment by adbenitez** [comment]
I got the same crash again at application start up, when the same message was still trying to be sent, then started the app again and it worked, so it isn't a permanent crash

**Comment by hpk42** [comment]
hum -- could you see to compile with debug symbols?  You can set the env var "RUSTFLAGS=-g" when building the node bindings.  Would be very useful to get a full trace.

**Comment by adbenitez** [comment]
I don't know how to compile the node bindings :D I just do:

```
git pull
npm i  # if needed
npm run dev
```

**Comment by adbenitez** [comment]
also, it isn't happening again, just happened two times with a message that was sent already

**Comment by hpk42** [comment]
that's fine -- just do "export RUSTFLAGS=-g" or so before you invoke npm commands.

**Comment by adbenitez** [comment]
will close this for now, how get better logs if this happens again

**Comment by Jikstra** [comment]
> that's fine -- just do "export RUSTFLAGS=-g" or so before you invoke npm commands.

@hpk42  @adbenitez  This doesn't work when it pulls in the node prebuilts. An easy fix is to change the `"deltachat-node"` line in the package.json to pull in the node module from the repo:
`"deltachat-node": "git+https://github.com/deltachat/deltachat-node",`. Then the `RUSTFLAGS=-g npm i` dance should work.
