### ISSUE TITLE
most avatars in groups not visible

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#1256]
version is desktop/node/core master from today. 

![avatar-weg2](https://user-images.githubusercontent.com/73579/70936922-af0d3f00-2043-11ea-8373-e7ffb1498f22.png)

**Comment by nicodh** [comment]
Can't reproduce this. Just updated all repos but all avatars are displayed...

**Comment by r10s** [comment]
probably, you already notices that, however:  
looking closely: there are avatars from Emil and Massick on the screenshot - but moved out of the screen.
the avatars from Emil and Massik seems to be even different. so maybe there is just a wrong offset depending on dc_contact_get_profile_image() returning sth. or nothing?

**Comment by adbenitez** [comment]
I sent a picture to the Testing group reporting this, the issues is with the new avatars, I mean with users that had sent us their avatars, users without avatar (the default letter avatars) works fine
