### ISSUE TITLE
Message with too many spaces makes Desktop busy-hang

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#1263]
current master.  If you try to send a message like the one attached (a line, lots of spaces, \n, then a bit of text in the second line) you can hang desktop  with the CPU spinning on 100% elektron.  

[fail-message.txt](https://github.com/deltachat/deltachat-desktop/files/3977717/fail-message.txt)

**Comment by Simon-Laux** [comment]
Seems like I either use the markdown parser lib in a wrong way or it is broken.
I'm sure I can do a quick fix.
