### ISSUE TITLE
Changing Password does not work

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#1270]
currently trying to get a gmx account going, and after first setup i had to change the password. I already had setup desktop and it basically worked.  Then i went to "password and account" and changed my password and hit "update".  the login failed ... and looking at the password (hitting the eye) sign i saw that the password had revert4ed to the old value.  Something is borked -- password changes do not seem to actually happen.

**Comment by r10s** [comment]
the uis should not _overwrite_ the input fields having user-entered-data with data read from the core, however, maybe desktop does that accidentally. of couse _initializing_ the data on dialog-opening is needed and required.

cmp https://github.com/deltachat/deltachat-core-rust/pull/810 - core resets the parameter set to the working ones on configure failures, to avoid data being displayed to the user that are not actually used.

however, of couse, the but may also be unrelated to that :)
