### ISSUE TITLE
"not now" in contact request should remove the contact request

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1273]
choosing "not now" in a chatlist-contact-request should discard the contact request - otherwise there is no option to get away of the contact-request without blocking or accepting.

![Screen Shot 2019-12-23 at 14 40 30](https://user-images.githubusercontent.com/9800740/71361232-a6ac8b00-2592-11ea-9bf4-37aaf96e6296.png)

currently, the behaviour is equal to clicking _outside_ the dialog - which should stay, same as hitting the escape key. so, in total we have 4 options:

1. "block contact" aka "never" -> remove contact request -> block contact
2. "not now" -> remove contact request, request can be handled later
3. "start chat" -> remove contact requests -> start chat
4. escape, click outside dialog -> do nothing

currently, "not now" is the same as as 4.

**Comment by Jikstra** [comment]
How can I delete a contact request on the api level?

**Comment by r10s** [comment]
> How can I delete a contact request on the api level? Marking the message as read probably?

typically, the "not now" button will removing a contact request from the main chatlist means it is still available in the contact-request-chat-view and subsequent requests will pop up as well.

on the api-level, call [dc_marknoticed_contact()](https://c.delta.chat/classdc__context__t.html#a7cc233792a13ec0f893f6299c12ca061) to achieve this.
