### ISSUE TITLE
No contact request shown when name of sender includes a comma character

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#1280]
**- Platform (linux/mac/windows):**
Windows 8.1 Pro (x64).

**- Delta Chat Desktop Version:**
0.901.0.

**- Expected behavior:**
New incoming mail from sender "Sirname, Firstname" appears as contact request.

**- Actual behavior:**
New incoming mail from sender "Sirname, Firstname" does not appear at all, as if it was never received. Checking the Inbox with another mailer clarifies that the mail has been delivered properly.

**- Logs:**
No log available.

**- Comments:**
Mails sent from "Firstname Sirname" show up properly as contact requests, only those from senders who have a comma character in their name do not appear at all.

**Comment by gerryfrancis** [comment]
BTW, the Android app has the same issue, I hope it finds its way to be solved in both/all branches.

**Comment by Jikstra** [comment]
Very likely are core issue: https://github.com/deltachat/deltachat-core-rust/issues/1120

Once it's fixed there it should be fixed on all platforms (as soon as they pull in the fixed core version).
Thanks for reporting! :)

**Comment by gerryfrancis** [comment]
Thanks for forwarding the issue to the right place, so I may close here. :+1:
