### ISSUE TITLE
"Fullscreen" view of media files is too full screen

### ISSUE THREAD

**Issue by pabzm** [deltachat/deltachat-desktop#1286]
The new fullscreen view of media files (merged via https://github.com/deltachat/deltachat-desktop/pull/1278) instantly uses the full screen estate, beyond the application window. It hides status bars of desktop environments etc, which I find very unexpected for a desktop application.

Is this really intended behaviour?

**Comment by Simon-Laux** [comment]
I believe so, in theory we could also open a semi transparent full screen window like telegram does, but that's a bit more work than this solution, because we need another window for it.

**Comment by pabzm** [comment]
Transparency would not fix the issue, in my opinion.

I would expect a desktop application to always stay inside the bounds of its window, unless I explicitly tell it to do otherwise. All other messaging desktop applications I'm aware of (notably excluding Telegram) show media files as "full screen inside the window" ("full window"?), which feels correct to me.

**Comment by Simon-Laux** [comment]
I can agree with both opinions : full fullscreen and contained fullscreen so I am neutral in this discussion.
@Jikstra please provide your perspective on this.

**Comment by gerryfrancis** [comment]
> I would expect a desktop application to always stay inside the bounds of its window, unless I explicitly tell it to do otherwise.

Fullscreen mode in web browsers occupies the whole screen. Feel free to check by pressing the "F11" key.

**Comment by pabzm** [comment]
gerryfrancis wrote:
> Fullscreen mode in web browsers occupies the whole screen. Feel free to check by pressing the "F11" key.

Indeed, that's the situation in which I tell the browser to go fullscreen. This case is about what happens when I click on an image to see it bigger.

**Comment by r10s** [comment]
i have not tested the fullscreen option, but i think it is fine if the enlarged image is larger than the chat-window, which might be pretty small.

i do not think that is unexpected being larger than the opening window.

**Comment by pabzm** [comment]
Please test it. Having an image opened full screen is really awkward, too, the more the bigger your monitor is.

**Comment by Jikstra** [comment]
It's the same behavior on telegram, i like it how it is, only thing which annoys me a bit is that we don't spawn a new fullscreen window.

**Comment by Simon-Laux** [comment]
Lets move this discussion to the forum if it keeps being inactive.

**Comment by r10s** [comment]
thinking it over and after some discussion with @pabzm this afternoon, maybe telegram is just wrong here.

might really be better to stay inside the window, esp. on larger screens. this also seems to make things easier programming wise - and if the user wants the image to be larger, he can enlarge/fullscreen the window. 

but i like the black background much more than the white one before, just had a look: signal uses sth. as 90% opaque, so close to black as well (not saying signal does everything right, eg.  the buttons in fullscreen-view are weird)

but i would also be fine with giving the current full-screen-solution a try and closing this issue for now.

**Comment by Simon-Laux** [comment]
so then let's close this for now.
