### ISSUE TITLE
Incoming messages (mails) are not marked as read when main window not focused

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#1293]
**- Platform (linux/mac/windows):**
Windows 8.1 Pro (x64).

**- Delta Chat Desktop Version:**
0.901.0.

**- Expected behavior:**
Incoming messages (mails) are always marked as read by Delta Chat after they are read by the user.

**- Actual behavior:**
Incoming messages (mails) are not marked as read by Delta Chat after they are read by the user. Further investigation showed that it depends on whether Delta Chat's main window was focused or not while the message had been received.

**- Logs:**
No log available.

**- Steps to reproduce:**

- Initiate a chat session with another person by sending a message from Delta Chat.
- Set focus to another window than Delta Chat's, and wait for the person's reply.
- As soon as the reply is received, focus Delta Chat's main window to read the message.
- Check with a different mailer than Delta Chat if the incoming message has been read.

Result: The message (mail) is still unread.

Perform the following steps to verify the opposite:

- Initiate a chat session with another person by sending a message from Delta Chat.
- Do not set focus to another window than Delta Chat's, and wait for the persons's reply.
- As soon as the reply is received, check with a different mailer than Delta Chat's if the incoming message has been read.

Result: The message (mail) has been read.

**- Remark(s):**

- The other chat member has used a different mailer than Delta Chat, and the member has always replied to the latest chat message.

**Comment by Simon-Laux** [comment]
Looks like something is wrong in https://github.com/deltachat/deltachat-desktop/blob/master/src/main/markseenFix.js.
We want to rewrite that system anyway to check if the message was actually in the view-port.

**Comment by gerryfrancis** [comment]
@Simon-Laux Thanks for confirming this issue.

**Comment by link2xt** [comment]
Also when read receipt arrives, message is not marked with double-tick immediately. I have to switch to another chat and back to see it.

**Comment by Simon-Laux** [comment]
@link2xt thats a seperate thing. I will move it to an new issue.

**Comment by pabzm** [comment]
The code runs [`.on('focus')`](https://github.com/deltachat/deltachat-desktop/blob/master/src/main/markseenFix.js#L21), so I guess the described behaviour is intended?

We can still debate is this behaviour is sensible but this doesn't look like a bug to me. Can anyone confirm, please?

**Comment by Simon-Laux** [comment]
The markseenfix file is a hack to make read-recipients works somehow more or less until we implement them right (messages should get marked as read when they are in the viewport).

We can discuss whether it should be enabled/disabled when the windows is or isn't focused.

**Comment by gerryfrancis** [comment]
Still an issue in version 0.999.1.

**Comment by gerryfrancis** [comment]
Version 1.0.0 is affected, too.

**Comment by gerryfrancis** [comment]
Version 1.1.0 is affected, too.

**Comment by gerryfrancis** [comment]
Version 1.3.0 is affected, too.

**Comment by r10s** [comment]
current version (1.15.5) marks messages as noticed when the window is not focused, i just tested that on mac.

however - unfortunately, that even happens when the window is completely invisible and the screen is off or even locked - this is not really the idea of "messags are displayed to the user" - however, that is another issue, so this one can probably be closed.

**Comment by gerryfrancis** [comment]
@r10s Thanks for the information, closing here...
