### ISSUE TITLE
Integration test is broken

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-desktop#1299]
It seems since 51112a7 the integration test loading settings from existing config file is broken
@Jikstra @Simon-Laux can you please have a look?

**Comment by Simon-Laux** [comment]
It throws "Previous account not found!" and crashes...

**Comment by pabzm** [comment]
I can't run the app at all, `npm run start` throws the mentioned error:

```
"2020-01-06T16:24:14.761Z"      "main/ipc"      "ERROR" "\nObject.init (/home/user/dev/deltachat-desktop/src/main/ipc.js:281:11),\nonReady (/home/user/dev/deltachat-desktop/src/main/index.js:79:7)"     "Previous account not found!"
"2020-01-06T16:24:14.762Z"      "main/index"    "CRITICAL"      "\nPromise.all.then.catch.error (/home/user/dev/deltachat-desktop/src/main/index.js:52:9)"       "Fatal Error during init"
```

How about reverting 51112a7? Multi-account is of low priority anyway.

**Comment by Simon-Laux** [comment]
that is strange looks like there is another bug...
can you send me a `tree` of your deltachat data folder?

`How about reverting 51112a7?` No if there is a bug I'll find it and fix it.

**Comment by Simon-Laux** [comment]
@pabzm can you try the branch of #1300?

**Comment by pabzm** [comment]
Branch 'fix_integration_config' catches the known exception, so the window is opened, but I'm shown the login page, with a blank rectangle under "Known accounts". When I click on that rectangle (should show my email address I have an account with in the config), I see the error message "Bad email address." (see screenshot).
No additional error message occurs in the output. The console shows:

```
EventEmitter.ipcBackend.on.args (file:///home/user/dev/deltachat-desktop/static/bundle.js:117881:46),
EventEmitter.emit (events.js:187:15) Bad email address.
```

![2020-01-07-141947_1340x1055_scrot](https://user-images.githubusercontent.com/57864086/71898309-494f3700-3159-11ea-968a-269e785c0088.png)

Am I the only one experiencing this?

**Comment by Simon-Laux** [comment]
Your the only one next to the integration test, but I need to get some more data from you to be able to debug this.

**Comment by pabzm** [comment]
Here's the content of my `config.json`:
```
{
  "enterKeySends": true,
  "notifications": true,
  "showNotificationContent": true,
  "locale": "en",
  "credentials": null,
  "enableOnDemandLocationStreaming": false,
  "bounds": {
    "x": 2,
    "y": 23,
    "width": 1340,
    "height": 1055
  }
}
```

Here's a `tree` of my config folder:  [deltachat-broken-account-tree.txt](https://github.com/deltachat/deltachat-desktop/files/4034748/deltachat-broken-account-tree.txt)

**Comment by pabzm** [comment]
"credentials" being `null` doesn't look good to me.

**Comment by Simon-Laux** [comment]
and whats the new error message? (I added some debug info to it in the branch of #1300)

**Comment by pabzm** [comment]
There is no additional error message occurs in the, just the "Bad email address" in the window and the browser console I mentioned.

**Comment by Simon-Laux** [comment]
can you log state.logins in index html then?

**Comment by Simon-Laux** [comment]
> "credentials" being null doesn't look good to me.
that isn't a problem

**Comment by pabzm** [comment]
state.logins:

```javascript
[ { path:
     '/home/user/.config/DeltaChat/63686174407a696d6461686c2e6f7267',
    addr: '' } ]
```

That same `path` is also shown when hovering over the blank button.

**Comment by pabzm** [comment]
Setting a value for keyname `addr` in the database of my account fixed my problem.
Shouldn't we rather use the information from `configured_addr`? That one was set all the time. Or was `addr` maybe set and has been cleared by some code? To avoid this problem impacting other people it would be helpful to know the cause.

@Simon-Laux Could you dig around for the culprit?

For the future I'd like to suggest to start writing more tests, in order to help to avoid such problems.

**Comment by Jikstra** [comment]
> For the future I'd like to suggest to start writing more tests, in order to help to avoid such problems.

Writing tests is not so easy as at least selenium (used for electron integration tests) is quite shitty. Probably we can test the backend alone. But for sure more testing makes sense, especially as some things tend to break again and again.

**Comment by Simon-Laux** [comment]
ah somehow it doesn't find your address in the database.

the dependency on the `addr` var was there before I touched that code. not sure how that value was missing for you.. Did you import an android backup?
_ also that code was really ugly before I refactored it._

> @Simon-Laux Could you dig around for the culprit?

you already figured it out by yourself, but yeah that was the thing I suspected and planned to test as soon as I got the missing info.

> Test

of course - if they work good.

So the steps on this are now:
 - add debug log of found accounts to logins.js
 - fix the integration test.
 - find out how `addr` can be/get empty

**Comment by pabzm** [comment]
On the topic of testing let's discuss in #1328 and #1329.

@Simon-Laux I'm not looking for someone to blame, I'm looking for ways to improve the stability of the code. Please don't take this personally, I don't mean it that way.

How about writing some tests for the code that reads and migrates the logins? Often that helps to figure out what might be wrong.

**Comment by pabzm** [comment]
I did import an android-backup into Desktop, but that was in November. Until last week the App worked fine with it.

**Comment by Simon-Laux** [comment]
> @Simon-Laux I'm not looking for someone to blame, I'm looking for ways to improve the stability of the code. Please don't take this personally, I don't mean it that way.

I don't do that, I just want to provide the reason why I'm so strongly against just-reversing-it. :smiley: 

> How about writing some tests for the code that reads and migrates the logins? Often that helps to figure out what might be wrong.

The migration code is currently disabled, the code is mainly forward compatible so we just flip the switch in some future version and the account folder will then be moved. 
https://github.com/deltachat/deltachat-desktop/blob/master/src/main/logins.js#L11

> can you check whether the `addr` value is present in your android db?

**Comment by Simon-Laux** [comment]
Maybe we could also go the extra mile and avoid [getNewAccountPath](https://github.com/deltachat/deltachat-desktop/blob/master/src/main/logins.js#L93-L99) and use the account path directly when loading an account.

**Comment by pabzm** [comment]
Thank you for looking into it! Even if we still don't have a real answer I suggest to stop here. Apparently my case is still the only one, no one else reported it. Maybe it was just a glitch in the matrix? If anyone else reports the problem we can restart the bug hunt.

I'm sorry for having highjacked this issue! Is the original topic still open?

**Comment by Simon-Laux** [comment]
yes its still open, atleast 2 of the todo points still are:  #1300
(the two logging statements and the don't crash on "previous account not fount" still need to come into master somehow even if we merge the mocha thing)

**Comment by pabzm** [comment]
@Simon-Laux Could you please prioritize this and fix running the integration tests?

**Comment by nicodh** [comment]
I'm just working on a PR with new tests and dynamic account creation via testrun.org

**Comment by Simon-Laux** [comment]
as nico said that test will be replaced by him anyway so it makes no sense to fix the old one.
