### ISSUE TITLE
"Choose language... >” wording

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1301]
in the main menu, there is the menu entry "View / Choose Language ... >" that opens a submenu.

these three dots must not be shown here, not sure where the string comes from, i did not found it in the string resources, maybe it is an electron ui glitch.

if we have control over the string, please just use the existing string `pref_language` here, the verb "choose" is also superfluous.

**Comment by Simon-Laux** [comment]
That sub menu is also super slow on first time opening...
