### ISSUE TITLE
New desktop releases in download page? 

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#1307]
both privately and on public channels there is a stream of crash reports because people go to the download page and use the quite old 0.840 version.  What is missing to publish new desktop builds on get.delta.chat?  Seems like at least the .deb package is missing.

**Comment by pabzm** [comment]
.dmg-files for macOS are missing, too.

**Comment by Simon-Laux** [comment]
missing? https://download.delta.chat/desktop/0.901.0/
just the links on the website. @missytake is already on it.

**Comment by r10s** [comment]
i think this is done now. tbh, i also missed the new version completely ;)
