### ISSUE TITLE
in language list, combine "Dutch" and "Nederlands (Nederland)" to just Nederlands

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1308]
we do not have two different languages for that and the local name is "Nederlands", the iso-code  in transifex is nl_NL.

**Comment by gerryfrancis** [comment]
When offering languages to select, "Dutch" is the correct English expression for the Netherlands (compared to "German" for Austria).

**Comment by r10s** [comment]
we do not want to show the english name for a language but the locale name, eg. for android: https://github.com/deltachat/deltachat-android/blob/master/res/values/arrays.xml#L7
