### ISSUE TITLE
After start select last selected chat (or device chat as default)

### ISSUE THREAD

**Issue by pabzm** [deltachat/deltachat-desktop#1311]
select the last chat that was selected on startup, with default being the device chat. 
The goal is to get rid of the welcome screen.

**Comment by pabzm** [comment]
@Simon-Laux You wrote this into a card. Let's please use issues, so we can comment etc. on it.

Please explain what your note means and why it is critical for v1.0.

**Comment by Simon-Laux** [comment]
It comes out of a release discussion i had at 36c3 with @r10s about things that need to be tackled for 1.0

**Comment by Simon-Laux** [comment]
possible a question for multi-account so we need a way to store the last chat of an account somewhere without being overwritten when switching the account. or we just show the select chat screen otherwise

**Comment by r10s** [comment]
is there no option to save some values beside the database? where is the background image saved? i would use this place for the "last chat" as well.

the whole issue is about remembering and restoring the last selected chat. on first start, the device chat should be selected, at least this was the idea iirc.

**Comment by Simon-Laux** [comment]
background image is the same for all accounts. we can use local storage or an extra array/object in config.json, where only the latter is portable.

**Comment by Jikstra** [comment]
@Simon-Laux I know you would like to give local storage a try but especially for running deltachat on a raspberry pi and having multiple clients we should avoid this and read it out of a account specific config.json.

**Comment by Simon-Laux** [comment]
so a config db next to the account db in the account folder?
what about resurrecting the client preferences in the account db idea?
Also do you plan for multiple simultaneous accounts of dc desktop electron edition? that's a bit far a away IMO to consider.

**Comment by r10s** [comment]
> background image is the same for all accounts. we can use local storage or an extra array/object in config.json, where only the latter is portable.

k, maybe use sth. as `last-chat-<dbname> = <chat-id>` - might be a bit hackish, however, it can be changed pretty easy later - the only thing the user will lose is the last selected chat on an update.

**Comment by pabzm** [comment]
Let's solve this pragmatically with a focus on the current app. We still can change things later, in case we meet problems with the chosen solution and future features (e.g. non-electron-setups, multi-account, etc.)
