### ISSUE TITLE
Remove image and welcome text from no-chat-selected screen

### ISSUE THREAD

**Issue by pabzm** [deltachat/deltachat-desktop#1312]
remove the welcome image and welcome text from the no-chat-selected screen.
After implementing #1311 on delete chat || block contact are the only occurrences of this screen

**Comment by pabzm** [comment]
@Simon-Laux You wrote this into a card. Let's please use issues, so we can comment etc. on it.

Please explain what your note means and why it is critical for v1.0.

**Comment by Simon-Laux** [comment]
It comes out of a release discussion i had at 36c3 with @r10s about things that need to be tackled for 1.0

**Comment by r10s** [comment]
not totally sure, what we figured out on this. i think, on chat deletion, it is fine to leave the right window empty, however, we do not want to have the handdrawn graphic in this case - just a "Select a chat to start messaging" would be fine.

the welcome graphic can be removed at all as that app starts with the last selected chat and defaults to the device chat, so there is no much use in it any longer.

**Comment by Simon-Laux** [comment]
> not totally sure, what we figured out on this. i think, on chat deletion, it is fine to leave the right window empty, however, we do not want to have the handdrawn graphic in this case - just a "Select a chat to start messaging" would be fine.

After removing welcome text & image this is exactly what stays on that screen :wink:
