### ISSUE TITLE
Portable windows shouldn't use home/config folder but the folder where the .exe lays in

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#1315]
Seems like some environment variables are getting set if the portable deltachat.exe is getting executed.

https://www.electron.build/configuration/nsis#portable

**Comment by Simon-Laux** [comment]
@NeoRon82 gave me this error dialog that appeared when opening the logfolder:
```
[Window Title]
C:\Users\User\AppData\Local\Temp\1VIeVtxfsTNNxT9fVPlY3GzfPPr\DeltaChatData\logs

[Content]
"C:\Users\User\AppData\Local\Temp\1VIeVtxfsTNNxT9fVPlY3GzfPPr\DeltaChatData\logs" konnte nicht gefunden werden. Stellen Sie sicher, dass Sie den Namen richtig eingegeben haben und wiederholen Sie den Vorgang.

[OK]
```
So our code to make a portable version -> config folder in cwd, next to the executable
 doesn't work on windows. It looks like it worked before, so maybe it is a behaviour that changed with an electron builder upgrade.
