### ISSUE TITLE
always select the chat-view on clicking in the chatlist

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1317]
currently, you can select the image+document view, which is great.

however, when it is selected, and you click the chatlist after that, chat is not shown but the document view - which is empty for many chats.

i found this several times confusing me and also other users.

i think a click in the chatlist should reliably open the chatview.

**Comment by Simon-Laux** [comment]
already done in master

**Comment by r10s** [comment]
cool! one thing less :)
