### ISSUE TITLE
Extend unit- and integration-test-suite

### ISSUE THREAD

**Issue by pabzm** [deltachat/deltachat-desktop#1328]
We should massively extend the test suite to help improve the stability of DC-Desktop, and to avoid bugs and regressions in further development.

We currently have two layers with a few tests each:
1. Unit tests. Testing small, isolated pieces of code. 
2. "Integration" tests. The existing ones are rather functional tests, which start the App and use use its GUI to check if its behaviour is correct. I'll call them "GUI-using" to avoid misunderstandings.

We're lacking a layer of actual integration tests, which test if several units are working together correctly, without using the GUI.

I've heard reseverd voices about testing because the setup for the GUI-using tests is based on selenium, doesn't work well and is unpleasent to use. No one likes to work with unpleasent setups, so should fix that. But that shouldn't stop us from writing other tests, either.

I suggest to start writing many unit- and integration-tests (without GUI) now, on every piece of code that they can properly test.

And split off a task to research possible changes to the setup for GUI-using tests, in order to enable us to write more of those tests, too. 

Any opinions?

**Comment by Simon-Laux** [comment]
I don't see unit tests because we don't have many components that actually work standalone, because they call the core, so we need to have a mock core-call-interface first.

Also I like mocha more than tape.

**Comment by nicodh** [comment]
The main problem with the tests is the unreliable rendering - we see too many false positives. Especially on MacOS the tests fails often with errors like "element not found" or "element not clickable" although it is always the same Chrome browser running in electron...
Nevertheless the tests would help if run locally before pushing stuff. At least for me they were always reliable on a real machine instead of the virtual display in the CI routine

**Comment by Simon-Laux** [comment]
ah can we use 'rc' instead of the env vars for the integration test credentials? that way I could have them in a file in my home directory and don't need to prepend them every time I do the test.  (this is a blocker for me why I don't run it regularly)

**Comment by nicodh** [comment]
Maybe we should give https://github.com/cypress-io/cypress-electron-plugin a test, but it is highly experimental alpha preview... :-(
It's the only tool so far that is not just a wrapper around Selenium like all the other tools that claim to be a replacement for Selenium...
