### ISSUE TITLE
Research how to improve setup for GUI-using tests

### ISSUE THREAD

**Issue by pabzm** [deltachat/deltachat-desktop#1329]
We should extend our test-suite (see #1328). The setup for GUI-using tests (usually called "functional", in our repo currently called "integration") is considered unpleasent by some.

To improve the situation and make the test-suite help us, instead of being a millstone around the neck, we should consider changing the setup.

To enable us to make an informed decision we need some input. I suggest that someone researches this topic for some hours and presents a few options with Pros and Cons. This article about Javascript testing in 2019 could be a starting point to check out possible better options: https://medium.com/welldone-software/an-overview-of-javascript-testing-in-2019-264e19514d0a

Also anyone who already has an opinion is of course also very welcome to state it here.

Based on the gained input we then could decide collectively how to continue.

**Comment by pabzm** [comment]
Another possible starting point: https://smartbear.de/blog/test-and-monitor/how-to-test-electron-apps/

**Comment by Simon-Laux** [comment]
Is this issue still active/relevant?
