### ISSUE TITLE
Clicking on huge chats with unread messages is very slow

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#1330]
I guess it's the markSeenLogic in the backend causing this

**Comment by Simon-Laux** [comment]
the mark seen workaround fix? yes that could be it, but how do we make it less block-y?

**Comment by Jikstra** [comment]
I think a way to handle it in the frontend would be:
Register an event listener for the onScroll event/intersection api if we an unread message. If we scroll into view, mark the message as seen and unregister the listener. This should be a performant way to solve this issue + having correct on actual reading markseen messages.

**Comment by Simon-Laux** [comment]
I thought there was another quick fix. but if that is already reachable feel free to do it.

**Comment by Jikstra** [comment]
Actually this got fixed at some point. Currently we only mark messages as seen if we get them with getMessages()
