### ISSUE TITLE
A Zipped Portable Version?

### ISSUE THREAD

**Issue by mva1985** [deltachat/deltachat-desktop#1334]
I love DeltaChat...  it's such a fantastic idea

just wondering if there could be a portable version I could put on a thumb drive?

thanks for the consideration

**Comment by Simon-Laux** [comment]
At the moment there is a bug in the portable version, thats why we took it offline. Its an exe that you can run that creates the data directory next to it. (nonetheless electron will create a folder for saving localstorage and browser cache in `%appdata%` we don't know how to prevent this yet.)
https://github.com/deltachat/deltachat-desktop/issues/1315

And the thread about the feature on our forum: https://support.delta.chat/t/please-make-deltachat-for-windows-a-truly-portable-standalone-program/675/17

What do you mean exactly by ziped portable version? you can't really run an exe from a zip without extracting it first...

**Comment by mva1985** [comment]
sorry for the confusion.  a lot of portable software comes zipped...  so yes I would have to extract it first before running

thanks for answering the question though
