### ISSUE TITLE
Sent messages are duplicated in the UI

### ISSUE THREAD

**Issue by Thyphex** [deltachat/deltachat-desktop#1339]
- Platform (linux/mac/windows): windows
- Delta Chat Desktop Version: 0.901
- Actual behavior: sent messages are duplicated in the UI, received messages works fine.
- Screenshots:
![duplicate](https://user-images.githubusercontent.com/44654330/72275506-d1778580-360c-11ea-93c2-89544095ae53.png)

**Comment by Jikstra** [comment]
I think this bug got fixed on master. Can you give this portable build a try and check if still happens for you?

https://transfer.sh/b8FRj/deltachat-desktop-1349.exe

The portable build will not find your existing configuration so you need to setup again.

**Comment by Thyphex** [comment]
I uninstalled and then downloaded the version that you linked but it is still happening.
Maybe it's because I'm using an outlook account? I know there are still issues with outlook.

**Comment by Jikstra** [comment]
The first message showed up twice? All following where only there once?

**Comment by hpk42** [comment]
Outlook is known to cause duplicate messages and prevent encryption. 

There are some plans to work around Outlook.com limitations
https://github.com/deltachat/deltachat-core-rust/issues/1006
but it's quite a bit of work and not happening right now.

**Comment by pabzm** [comment]
As Holger explained this is a bug due to outlook/hotmail.com manipulating headers, which we won't have the time to implement a workaround for currently. So I'm closing this issue.
