### ISSUE TITLE
Regression: client freezes when opening the media view

### ISSUE THREAD

**Issue by missytake** [deltachat/deltachat-desktop#1353]
- Platform (linux/mac/windows): linux
- Delta Chat Desktop Version: [current master](https://github.com/deltachat/deltachat-desktop/tree/f87e263037d5165144a97125e652b753ccd05c48)
- Expected behavior: When I open the media view, it shows all images ever sent in that conversation.
- Actual behavior: both the chat view and the media view buttons look clicked. It stays in the chat view. The client freezes and doesn't react to input anymore.
- Steps to reproduce the problem: 
  - build the client with `npm i`
  - start the client with `npm run start`
  - open a chat
  - click on the media view button in the top right
- Screenshots:

![the client freezes](https://oc2.links-tech.org/s/HVEjEzIgRky36Ya/download)

- Logs: no output in the console window

**Comment by Jikstra** [comment]
Does it happen no matter on which chat you click on the media gallery?

**Comment by missytake** [comment]
It happens in 

* groups with media
* groups without media
* 1-to-1 chats with media
* 1-to-1 chats without media.

Pretty much regardless which chat I try to access...

**Comment by Jikstra** [comment]
Did you run `npm run build` after pulling?

**Comment by missytake** [comment]
No I didn't. :woman_facepalming:
