### ISSUE TITLE
Big view of profile image

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1356]
see https://support.delta.chat/t/big-profile-picture/749/3

**Comment by arghac14** [comment]
@Simon-Laux Can I work on this?

**Comment by Simon-Laux** [comment]
Sure, make sure to write all questions you have regarding the implentation here in this issue, so that we can help you with them.
The current media view expects an attachment object so you can't use that media view, unless you modify it so that it can also take a single file-url to a picture. Or you make a new dialog for showing the profile picture in bigger. If you go for the second option I recommend looking at the existing dialogs to get to know the dialog system.

Am 18. Januar 2020 18:04:29 MEZ schrieb Arghadip Chakraborty <notifications@github.com>:
>@Simon-Laux Can I work on this?
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/deltachat/deltachat-desktop/issues/1356#issuecomment-575918648

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by arghac14** [comment]
Yes I'm going for the second option. Can you clarify what do you mean by the existing dialog system? Is it something in this project?

Also, please assign this to me.

**Comment by Jikstra** [comment]
The existing dialog system lays in `src/renderer/components/dialogs`. Especially the `dialogs/index.js` is interesting to understand how it works, but not complicated.

**Comment by nicodh** [comment]
Maybe take qrInviteCode Dialog as example:
https://github.com/deltachat/deltachat-desktop/blob/master/src/renderer/components/dialogs/QrInviteCode.js

**Comment by Simon-Laux** [comment]
@arghac14 Did you already start? I plan to work on the profile view too, so I want to know how whether I can convert it to typescript now or if I should keep it in js and just change the lines I need to change and do the switch to ts after your pr is merged.

**Comment by Simon-Laux** [comment]
As this is stale I'll clear the assignment.
