### ISSUE TITLE
No copy-to-self IMAP option in macOS Desktop client (to sync with other devices)

### ISSUE THREAD

**Issue by zoelx** [deltachat/deltachat-desktop#1358]
- Platform (linux/mac/windows): mac
- Delta Chat Desktop Version: Version 0.901.0-PREVIEW
- Expected behavior: copy-to-self IMAP option
- Actual behavior: no option
- Steps to reproduce the problem:
- Screenshots:
- Logs:

**Comment by r10s** [comment]
ho @zoelx , thanks for your post :)

the copy-to-self-option was just added, https://github.com/deltachat/deltachat-desktop/pull/1350 and merged to master. it will be available in the next release then.
