### ISSUE TITLE
Failed message gets wrongly displayed.

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1361]
![2020-01-17_19-55](https://user-images.githubusercontent.com/18725968/72638251-5cd17d80-3963-11ea-9100-bf6b3443c771.png)
After leaving this chat and reentering it the message gets displayed as expected

And when clicking on the wrongly displayed one I get a white screen (react error):
![2020-01-17_19-53](https://user-images.githubusercontent.com/18725968/72638245-580cc980-3963-11ea-992d-069ec60ec097.png)

**Comment by Jikstra** [comment]
@Simon-Laux is this still happening?

**Comment by Simon-Laux** [comment]
probably yes, but I don't know a quick way to trigger a failed message rightnow

**Comment by Jikstra** [comment]
This can get reproduced by sending a file > 18mb. The problem is that dc_send_msg returns 0 for such messages instead of the messageId and therefore we also fail retrieving the message object for this (and can also not properly add it into the chat store).
