### ISSUE TITLE
Delete message: delete message completely (also on the server)

### ISSUE THREAD

**Issue by g6094199** [deltachat/deltachat-desktop#1362]
- Platform (linux/mac/windows): Ubuntu 19.10
- Delta Chat Desktop Version: 0.901.0
- Expected behavior: delete a message in DS the message gets deleted completly, not only on the client. This becomes important on hosters that have limited space, eg. Web.de (1GB), else you have to  log into Web.de an delete big messages (with attachments) manually when the box gets filled to  its limits.
- Actual behavior: the deleted message still resides on the server
- Steps to reproduce the problem: delete a message

somehow related  [to](https://github.com/deltachat/deltachat-android/issues/321)

**Comment by Simon-Laux** [comment]
If that's the case this would be a core bug.

Am 18. Januar 2020 14:25:38 MEZ schrieb g6094199 <notifications@github.com>:
>- Platform (linux/mac/windows): Ubuntu 19.10
>- Delta Chat Desktop Version: 0.901.0
>- Expected behavior: delete a message in DS the message gets deleted
>completly, not only on the client. This becomes important on hosters
>that have limited space, eg. Web.de (1GB), else you have to  log into
>Web.de an delete big messages (with attachments) manually when the box
>gets filled to  its limits.
>- Actual behavior: the deleted message still resits on the server
>- Steps to reproduce the problem: delete a message
>
>somehow related 
>[to](https://github.com/deltachat/deltachat-android/issues/321)
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/deltachat/deltachat-desktop/issues/1362

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by gerryfrancis** [comment]
Related issue here: https://github.com/deltachat/deltachat-android/issues/1199

**Comment by g6094199** [comment]
> Related issue here: [deltachat/deltachat-android#1199](https://github.com/deltachat/deltachat-android/issues/1199)

Yes, but on the desktop version there is no seletction dialog on where to delete the message, atm.

**Comment by Simon-Laux** [comment]
Then please create a feature proposal for selectiong multiple messages on the forum (support.delta.chat). On desktop you can only delete messages on by one, we did not implement a selection of multiple messages, yet.

Am 19. Januar 2020 11:25:08 MEZ schrieb g6094199 <notifications@github.com>:
>> Related issue here:
>[deltachat/deltachat-android#1199](https://github.com/deltachat/deltachat-android/issues/1199)
>
>Yes, but on the desktop version there is no seletction dialog on where
>to delete the message, atm.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/deltachat/deltachat-desktop/issues/1362#issuecomment-575989547

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by gerryfrancis** [comment]
> Then please create a feature proposal for selectiong multiple messages on the forum (support.delta.chat). On desktop you can only delete messages on by one, we did not implement a selection of multiple messages, yet.

I guess this one is about deleting (one) message(s) on the server _and_ the client.

> Actual behavior: the deleted message still resides on the server

**Comment by pabzm** [comment]
@g6094199 Thank you for the suggestion!

The behaviour you describe is actually intended, deletion is only local, on your device. Deleting a message from the server has not been implemented yet in the desktop app.

So your post is actually a feature request. We'd like to collect and discuss those in [the forum](https://support.delta.chat/c/features/6). Would you mind to post your wish there a second time?

**Comment by Simon-Laux** [comment]
Really? I believe deletion of **single messages**(not chats) is also server side. The core should do it.
It was the final reason we got allowed for oauth2 for imap on gmail.

Further I believe this is a core bug and as such it should be filed in the core repo instead.

> I guess this one is about deleting (one) message(s) on the server and the client.

@gerryfrancis first I thought that too, but after this 

> Yes, but on the desktop version there is no seletction dialog on where to delete the message, atm.

I interpreted it differently.
So @g6094199 If it is about select and delete multiple messages, it belongs in a feature proposal in the forum. If this is about a bug in the core it belongs in the core issue tracker.

You can delete messages on desktop:
![2020-01-20_09-55](https://user-images.githubusercontent.com/18725968/72712284-00d94580-3b6b-11ea-9ce8-7e5fa19441e0.png)
(it is very likely a core bug if the message isn't deleted then on the imap server too.)

**Comment by r10s** [comment]
> The behaviour you describe is actually intended, deletion is only local, on your device. Deleting a message from the server has not been implemented yet in the desktop app.

this is wrong, the normal "delete message" function _should_ delete the explicitly selected messages locally and on the server - and it worked this way at some point.

i agree with @Simon-Laux , this seems to be a core bug. [dc_delete_msgs()](https://c.delta.chat/classdc__context__t.html#ad6bdf2f72adcd382d849f2c3e25c5908) should delete the given messages locally and on the server - this is also what android asks the user. but i have just tested it, it does not work, in my tests, messages are not deleted from the server.

i'll file a core issue.

**Comment by pabzm** [comment]
Sorry for the wrong information. I learned it this way and hadn't checked the code myself.
