### ISSUE TITLE
video ui drawing errors

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1364]
tested with 0.901.0 on mac:

- the "play button" seems to be draw twice, but not at the same position which looks weird, see first image

- when a video in portrait-format is started, there is a reproducible hole in the overlay, see second image. maybe  the whole layout is different from the landscape-mode, eg. the huge shadow at the bottom is not present at all in landscape mode. wondering if this is desired.

<img width="939" alt="Screen Shot 2020-01-20 at 12 59 12" src="https://user-images.githubusercontent.com/9800740/72724982-1196b500-3b85-11ea-98b6-63d88559569d.png">

<img width="1228" alt="Screen Shot 2020-01-20 at 13 00 23" src="https://user-images.githubusercontent.com/9800740/72725019-325f0a80-3b85-11ea-9fe6-6243e11ca35b.png">

**Comment by Simon-Laux** [comment]
I can't reproduce the hole

**Comment by r10s** [comment]
> I can't reproduce the hole, does it still appear with the current master?

is there a download somewhere? i am always failing to find them, so i only have the "official" build.

however, as the fullscreen view is reworked completely - might be the problem is just gone. i will retry on the next update, feel free to close this issue when you merged the #1378
