### ISSUE TITLE
"archived" tag is missing for archived chats

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1365]
archived chats should show a small tag "archived" at the place where normally the delivery-checkmarks are shown (they are not needed for archived chats).

this is how it looks like on android:

<img width="339" alt="Screen Shot 2020-01-21 at 09 39 59" src="https://user-images.githubusercontent.com/9800740/72788391-23826180-3c32-11ea-81b1-444a89455dea.png">

this is especially useful for the global search that also searched over the archive, also on desktop. this is how a search result on android may look like:

<img width="337" alt="Screen Shot 2020-01-21 at 09 41 39" src="https://user-images.githubusercontent.com/9800740/72788609-79efa000-3c32-11ea-9947-f3a570932bd3.png">

**Comment by Simon-Laux** [comment]
Only needs to pass a variable around and a bit (maybe halfway tricky) css. So I'm marking it as easy issue.

**Comment by r10s** [comment]
:) if the chat object is available, [dc_chat_get_archived()](https://c.delta.chat/classdc__chat__t.html#af8b59ed08edfa2a5c4b7a3787613230d) should do the job.

**Comment by Simon-Laux** [comment]
not even so complicated... but as @Jikstra does the chatlist json he should include an is_chat_archived in it.
