### ISSUE TITLE
Archiving a chat sometimes results in list of chats missing first "page"

### ISSUE THREAD

**Issue by pabzm** [deltachat/deltachat-desktop#1376]
After archiving a chat, sometimes my list of chats is missing all chats that should be displayed without scrolling ("first page").

This is fixed once one of those chats receives a message, or by restarting. 

Unfortunately I can't reproduce it reliably (therefore I hesitated to post this issue, but it keeps happening once in a while). This behaviour should still be public information.

I'll add a log whenever I stumble upon the behaviour and have the presence of mind to copy the relevant parts.

**Comment by pabzm** [comment]
Maybe related to #1283?

**Comment by Jikstra** [comment]
I think it's the same issue

**Comment by pabzm** [comment]
I'll be optimistic and close this issue. If it re-appears I'll re-open it.
