### ISSUE TITLE
forbiddenPathRegEx is broken on linux

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1380]
When dragging out a file and dropping it again in the same chat we now get asked to confirm to send it. The `forbiddenPathRegEx` should prevent anything from happening in this case.

https://github.com/deltachat/deltachat-desktop/blob/master/src/renderer/components/message/MessageListAndComposer.js#L31

Should we remove that logic? We now have an confirmation window for dragging in files so its not a big deal anymore.

**Comment by Simon-Laux** [comment]
https://github.com/deltachat/deltachat-desktop/blob/master/src/renderer/components/message/MessageListAndComposer.js#L31
Should we remove that logic? We now have an confirmation window for dragging in files so its not a big deal anymore.

**Comment by pabzm** [comment]
I think we should fix the check. Dragging a file out and back in is a no-op and should not trigger sending, in my opinion.

**Comment by Simon-Laux** [comment]
Looks like a thing I forgot to consider while making the move to new account folders. So you probably can't reproduce it.
