### ISSUE TITLE
Login is broken

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-desktop#1383]
In current master I get
Login.js:89 Uncaught TypeError: update is not a function
when trying to type something into the input fields on Login form...

At  cd7cc3cae it still works so seems to be related top the typescript changes...

**Comment by Simon-Laux** [comment]
I pushed it as an hotfix to master as it was an wrong import that worked with webpack imports but not with typescripts es6 imports.
Converting every file step by step to ts will prevent this from happening in the future.

**Comment by pabzm** [comment]
@Simon-Laux Thanks for quickly fixing this! 👍

**Comment by hpk42** [comment]
On Thu, Jan 23, 2020 at 15:17 -0800, Nico de Haen wrote:
> In current master I get
> Login.js:89 Uncaught TypeError: update is not a function
> when trying to type something into the input fields on Login form...
> 
> At  cd7cc3cae it still works so seems to be related top the typescript changes...

i thought typescript is making things safer? 
/me hides

**Comment by Simon-Laux** [comment]
@hpk42 only if you use it. (that file in question is still javascript)
