### ISSUE TITLE
no "sending copy to self" setting on Linux desctop client

### ISSUE THREAD

**Issue by dasdirksche** [deltachat/deltachat-desktop#1386]
- Platform (linux/mac/windows): Linux MInt
- Delta Chat Desktop Version: 0.901.0-Preview
Using multiple clients. First on LineageOS second on Linux Mint. After sending autocrypt message I can activate "sending copy to self" on LineageOs but I can't find this setting on Linux desctop client.

**Comment by gerryfrancis** [comment]
See https://github.com/deltachat/deltachat-desktop/issues/1358 .

**Comment by Jikstra** [comment]
In case you need it immediatly, i triggered some "nightly" builds.
You can download the AppImage here:
https://download.delta.chat/desktop/preview/deltachat-desktop-1387.AppImage

https://github.com/deltachat/deltachat-desktop/pull/1387
