### ISSUE TITLE
SVGs are shown inside of documents..

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1394]
.. inside of the gallery/media-view.

Either we fix that (possibly involves stuff in the core) or we remove svg again from the list of mime types of supported images

**Comment by pabzm** [comment]
Where they shown in the media-view before?

Then I'd revert the mime-type change.

**Comment by Simon-Laux** [comment]
The thing is that the core orders the attachments in the gallery tabs, but the deltachat-desktop chooses from the mimetype how to render it.
![2020-01-29_17-06](https://user-images.githubusercontent.com/18725968/73374208-1f051b00-42ba-11ea-9ab0-1ffc33de48dc.png)

So yes the quickfix is to comment out svg again, the right fix is to add it to the image formats inside of the core

**Comment by pabzm** [comment]
So there are two tasks:

1. remove it from Desktop
2. add it to core

We can do 1. before 2. has happend, right? I assume not many people send each other svg-files and even less of those will see this as a serious bug.

**Comment by Simon-Laux** [comment]
two options, if we add it to core we need it displayed as image.

**Comment by pabzm** [comment]
I don't understand what "two options" means, can you explain your thoughts, please?

**Comment by Simon-Laux** [comment]
You unterstood it as todo point while those are options, either removing it from desktop or adding it to the core.

**Comment by pabzm** [comment]
Ok, thanks!

Then I would prefer to use the old behavior in Desktop until the situation in dc-core has been cleared and maybe changed. I guess the latter will take some time.

**Comment by kingemir** [comment]
.ogg files are shown under Documents instead of Audio
.mov files are shown under Documents instead of Video

.mp3 -> Audio ok
.mp4 -> Video ok

**Comment by link2xt** [comment]
I have added SVG into https://github.com/deltachat/deltachat-core-rust/pull/1818

**Comment by Simon-Laux** [comment]
Works for the new ones, the old ones are still displayed as images along the files, so I think we need to force displaying every attachment in the document tab as files and not dynamically upon their mimetype.

**Comment by r10s** [comment]
> so I think we need to force displaying every attachment in the document tab as files and not dynamically upon their mimetype.

yip, that would be great and fix the issue.

showing things in the Image-tab needs to make sure _all supported targets_ can handle the type - the message-type is not only about displaying things in the gallery on the own devicke - it matches how things are sent out - and received.

in case of svg - there are just several targets that cannot display svg. therefore, svg is has the file-type and not the image-type - see https://developer.android.com/guide/topics/media/media-formats
