### ISSUE TITLE
Improve Choose Language

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#140]
The list of languages only contains abbreviations. It should contain names of languages (which should also be translated to current language) ~~and maybe also attach a flag?~~

**Comment by r10s** [comment]
i would not use a flag as language != country

**Comment by karissa** [comment]
yeah no flags!

**Comment by karissa** [comment]
This would probably require a dictionary of abbreviation -> full name of language.

**Comment by ralphtheninja** [comment]
Agree on flags. My first thought was that it was cute, but flags means a lot of other stuff (politics etc) and not necessarily the same as a language. What was I thinking? :)
