### ISSUE TITLE
Message status not updated on last message..

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1406]
..in chat view.
Steps to reproduce: 
send a message to a contact with read notification enabled and wait for the double check-mark to appear.
Actual: it updates to the double check-mark inside of the chat list, but the status on the message is still the single check-mark, when I re-enter the chat the double check mar is there.
Expected:
double check mark on the message in the chat view.

**Comment by pabzm** [comment]
This sounds like a duplicate of #1306 to me — is it?

**Comment by Simon-Laux** [comment]
It is, sorry for not looking before opening this :smile:
