### ISSUE TITLE
When you click to see all files in a chat then go back to chat, it doesn't scroll to the bottom

### ISSUE THREAD

**Issue by Thyphex** [deltachat/deltachat-desktop#1407]
The chat doesn't scroll to the bottom thus loading old messages and basically it's a bad UX

**Comment by pabzm** [comment]
Thanks for reporting!

**Comment by Simon-Laux** [comment]
whats the wanted UX here @Jikstra @r10s?
I can confirm this behavior, but I don't know what behavior is the expected one

**Comment by r10s** [comment]
for me, when opening the gallery and then going back to the chat, it brings me to a more or less random position.

tbh, i am not sure if "scrolling down" is a good way here, i would expect more that the scrolling position is just unchanged.

**Comment by Simon-Laux** [comment]
the behavior is now to scroll to the bottom again, if you want it change, pls open a new issue
