### ISSUE TITLE
Unable to find "Send copy to self" setting

### ISSUE THREAD

**Issue by coreagile** [deltachat/deltachat-desktop#1411]
- Platform (linux/mac/windows): linux
- Delta Chat Desktop Version: 0.901.0-PREVIEW
- Expected behavior: Somewhere in settings there is a "Send copy to self" option
- Actual behavior: Can't find it
- Steps to reproduce the problem: Click the 3 dots on the right, click Settings, look

**Comment by gerryfrancis** [comment]
Version 0.901.0 does not include this feature, yet. Please wait for the next official release, or use one of the latest nightlies. Thanks.

**Comment by Jikstra** [comment]
We just released v0.999.1 which includes this setting. You can find it here:
https://download.delta.chat/desktop/v0.999.1/
