### ISSUE TITLE
Dekstop App does not require password for known accounts.

### ISSUE THREAD

**Issue by grondinm** [deltachat/deltachat-desktop#1419]
Platform (linux/mac/windows): Arch Linux
Delta Chat Desktop Version: 0.999.1-PREVIEW
Expected behavior: When going to switch account screen or opening app it should ask for password before letting you into a known account. Other option would be to have a configurable PIN or something.

Anyone that has access to my PC  can open delta.chat and get into my account.

I understand that if someone has physical access to my computer there are bigger things to worry about but this is still something that should be addressed I feel.

Thank you for this application/tech.

**Comment by Simon-Laux** [comment]
Please post feature requests into our forum: https://support.delta.chat/.
https://support.delta.chat/t/password-protect-dc-desktop-app/416

> Anyone that has access to my PC can open delta.chat and get into my account.

Can't you make different users on your computer? So that your family/friends can use your computer, without getting access to your account?

**Comment by gerryfrancis** [comment]
Speaking for Windows, it is possible to lock the Windows user. Other persons who do not know my username and password have no access to my data, and I lock my user everytime I physically leave the system. I would prefer the approach of @Simon-Laux to create different users if that is possible for Linux, too. (It makes sense for a lot of other issues, too, when the system is used by more than one person.)

**Comment by pabzm** [comment]
Different local user-accounts may be helpful, but they are not the answer to this feature request.

Nonetheless it's a feature request, which we want to discuss in the forum (as Simon-Laux said). Thus I'm closing this.
