### ISSUE TITLE
Mailtext of Outlook Web Access (OWA) mails is not displayed 

### ISSUE THREAD

**Issue by deepee2** [deltachat/deltachat-desktop#1429]
- Platform (linux/mac/windows): Windows 10 
- Delta Chat Desktop Version: 0.901.0-Preview
- other mail client: Outlook Web Access (OWA) of MS Exchange 2019
- Expected behavior: Mailtext of Outlook Web Access (OWA) mails is displayed 
- Actual behavior: Mailtext of Outlook Web Access (OWA) mails is **not** displayed, just the subject of the mail
- Steps to reproduce the problem:
  - send mail from DeltaChat client to mailbox with OWA-client
  - reply mail with OWA-client
- Screenshots:
![DeltaChat_win](https://user-images.githubusercontent.com/11028366/74013567-146b1580-498d-11ea-95ca-f67c41483c16.png)
![OWA_Antwort](https://user-images.githubusercontent.com/11028366/74013566-13d27f00-498d-11ea-948d-7884f1d0478f.png)

**Comment by gerryfrancis** [comment]
Version 0.901.0 of Delta Chat Desktop is old, please retest with version 0.999.1 and report back. Thanks.

**Comment by deepee2** [comment]
I tried Deltachat 0.999.1-PREVIEW. 

Same result with normal OWA settings, means just the subject is shown, not the mailtext, see attachment.

I tried another OWA setting called "Outlook light" which is useful for older browsers -> the mailtext is shown as expected. I can not export the raw message to see which is the difference of the content of the mails.

![deltechat_2](https://user-images.githubusercontent.com/11028366/74643524-27dc6480-5175-11ea-9246-b4424d520a5f.png)

**Comment by gerryfrancis** [comment]
Could be related to https://github.com/deltachat/deltachat-android/issues/1248 .

**Comment by Simon-Laux** [comment]
Looks like an core issue

**Comment by Simon-Laux** [comment]
Please reopen this issue if it is still there in the current version.
