### ISSUE TITLE
Mac “system” shortcuts

### ISSUE THREAD

**Issue by ghoffart** [deltachat/deltachat-desktop#1451]
- Platform (linux/mac/windows): macOS 10.15.3
- Delta Chat Desktop Version: 0.999.1
- Expected behavior: Deltachat accepts common system keyboard shortcuts
- Actual behavior: Deltachat ignores these shortcuts
- Steps to reproduce the problem: 
- Screenshots: –
- Logs:

New message: Cmd-N
Hide the application: Cmd-H (see ticket #634 )
Hide other applications: Cmd-Alt-H
Open settings: Cmd-, (Command comma)
Search field: Either Cmd-F (if it is really search) or Cmd-L ("browser style")

**Comment by Simon-Laux** [comment]
the search field is currently accessible through `CMD + K`
