### ISSUE TITLE
Language menu entries are a mix of 

### ISSUE THREAD

**Issue by ghoffart** [deltachat/deltachat-desktop#1453]
- Platform (linux/mac/windows): macOS 10.15.3
- Delta Chat Desktop Version: 0.999.1

The language menu has entries that are a mix of self-designation entries (e.g. "Deutsch") and terms imposed by others (e.g. "Chinese" or "Swedish").

So either all of these entries are self-designation ("Deutsch", "Swensk", "Français" …) or imposed by others ("German", "Swedish", "French").

<img width="197" alt="Bildschirmfoto 2020-02-12 um 23 17 31" src="https://user-images.githubusercontent.com/128098/74382908-80ff6d80-4dee-11ea-92c5-7f443d9b4b0b.png">

**Comment by r10s** [comment]
all strings should be in the langauge of the languae itself, here are all strings a used on android https://github.com/deltachat/deltachat-android/blob/master/res/values/arrays.xml#L7

**Comment by gerryfrancis** [comment]
> strings a used on android

@r10s This issue is about Desktop version 0.999.1.

**Comment by r10s** [comment]
sure, the link is about for helping to fix the issue on desktop :)

**Comment by gerryfrancis** [comment]
@r10s Ah, thanks for clarifying! :)
