### ISSUE TITLE
Pinned Chats

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1456]
Use the core api to pin chats.

- [x] core part (basically done, but not merged yet https://github.com/deltachat/deltachat-core-rust/pull/1248)
- [x] dc-node part
- [x] Desktop part

What is needed?

- Button/Context menu option to pin/unpin a chat
- Icon on pinned chats

related to #1365

**Comment by r10s** [comment]
this is how it looks like on android: https://github.com/deltachat/deltachat-android/pull/1252

ui-wise, i would not add a button for that, just use the context-menu in the chatlist, this should be sufficient. i would also not add this to the main menu, this is already full enough.

**Comment by r10s** [comment]
wrt node: the dc_archive_chat()/dc_chat_get_archived() are deprectated they still can be used for archiving, but won't work for pinning.

new functions are dc_set_chat_visibility()/dc_chat_get_visibility(), however, as the function signature is not changed, this should not much more than a simple replace.

**Comment by Simon-Laux** [comment]
do we still need the archive chat button in the main menu?

**Comment by r10s** [comment]
> do we still need the archive chat button in the main menu?

good question.  if in doubt, i would add pin also above archive in the main menu. in either way, archive and pin menu entries should appear in combination.
