### ISSUE TITLE
Help doesn't open 

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#1460]
Clicking on the Help menu item doesn't open a browser with the help html for me. Shouldn't the part be something like `/home/kerle/.config/DeltaChat/foobar/help`?

Error:
```
Object.<anonymous> (/opt/DeltaChat/electron_app/tsc-dist/main/ipc.js:247:17),
rejected (/opt/DeltaChat/electron_app/tsc-dist/main/ipc.js:5:65)
14.2s [E]main/ipc: Can not load help file [Error: ENOENT: no such file or directory, stat '/opt/DeltaChat/electron_app/static/help/'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/opt/DeltaChat/electron_app/static/help/'
} 
```

**Comment by hpk42** [comment]
Oh, did i miss that this was changed? 
Help was (is still) working fine but opening inside the app ... 
but i haven't updated desktop for a few days now or so.

**Comment by Simon-Laux** [comment]
the thing should be referenced from `html-dist` not from `static` not sure how this error slipped in here...
