### ISSUE TITLE
Help doesnt open on Mac

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#1477]
```
36.8s [E]main/ipc: Can not load help file [Error: EACCES: permission denied, stat '/Users/bb/Library/Application Support/DeltaChat/help-cache/help/en/help.html'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'stat',
  path: '/Users/bb/Library/Application ' +
    'Support/DeltaChat/help-cache/help/en/help.html'
}
```

**Comment by Simon-Laux** [comment]
wooot? but background images work? that's a bit strange... maybe we should use a temp directory instead?

**Comment by r10s** [comment]
i can confirm that. 1.0.0 on mac does not open the help, not even the browser is opened (did not totally follow the last conversations on that, but my last info was that it should open in a browser:)

**Comment by r10s** [comment]
still not working on 1.2
