### ISSUE TITLE
Disable "Reply to Message"

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#148]
The message context menu has functionality for replying to messages. Afaik it's nothing we do in delta?

Also see https://github.com/deltachat/deltachat-desktop/issues/143

**Comment by r10s** [comment]
yes, currently this should be disabled.
for the mid-future or so, this may come as a feature to the core, however. seems to be a hard requirement for [mailing lists](https://github.com/deltachat/deltachat-core/issues/125) but, of course, also useful for normal chats.

**Comment by ralphtheninja** [comment]
Lets keep it not functional for now. We _can_ disable it, but involves changing `conversations` module just to be able do disable something, which would only be a temporary thing and removed later.

**Comment by hpk42** [comment]
On Wed, Oct 10, 2018 at 16:35 -0700, björn petersen wrote:
> yes, currently this should be disabled.
> for the mid-future or so, this may come as a feature to the core, however. seems to be a hard requirement for [mailing lists](https://github.com/deltachat/deltachat-core/issues/125) but, of course, also useful for normal chats.

yes -- was also eg wondering if a bot-reply could rather make a certain icon
appear within a message that contains a links like "cached" or "pdf" or so. 
but that's a separate issue ;) 

also, on desktop there is more space to render a "reply-to" message next
to the message-being-replied to.  then again, i don't know about good practises,
examples how threading in a chat app is shown (except for the way how Matrix does 
it when gatewaying into IRC ...)

**Comment by r10s** [comment]
> i don't know about good practises, examples how threading in a chat app is shown

all chat app i know only show a short quote over the message on replies. i do not know of a chat app that does real threading.

**Comment by hpk42** [comment]
On Thu, Oct 11, 2018 at 14:44 -0700, björn petersen wrote:
> > i don't know about good practises, examples how threading in a chat app is shown
> 
> all chat app i know only show a short quote over the message on replies. i do not know of a chat app that does real threading.

chat/threading is maybe a question we can refer to the otf usability lab (CC @xeniax)

**Comment by ralphtheninja** [comment]
It seems it's disabled now but not sure how that happened. @Jikstra Did you change anything?

**Comment by ralphtheninja** [comment]
Seems `display: none` is set:

![screenshot from 2018-10-19 15-48-02](https://user-images.githubusercontent.com/308049/47222226-75489600-d3b6-11e8-89e6-adeb53cdcf5d.png)

**Comment by ralphtheninja** [comment]
Seems this was moved to (see big arrow below):

![screenshot from 2018-10-20 18-47-35](https://user-images.githubusercontent.com/308049/47258233-a8fbec80-d498-11e8-90c8-40a1e8773690.png)
