### ISSUE TITLE
"Changes in …" local message focus

### ISSUE THREAD

**Issue by ghoffart** [deltachat/deltachat-desktop#1483]
- Platform (linux/mac/windows): macOS 10.14.6
- Delta Chat Desktop Version: 1.0.0
- Expected behavior: "Changes in v1.0.0" local message is shown in a way that the user can start reading straight away.
- Actual behavior: Local message scrolls by default to the bottom, so that the user can’t read the message from start, and has to scroll back first.
- Steps to reproduce the problem: Open new version first time.
- Screenshots: 
<img width="975" alt="grafik" src="https://user-images.githubusercontent.com/128098/75386306-be312880-58e1-11ea-9b4c-95a9ea7de949.png">

- Logs:

**Comment by Simon-Laux** [comment]
this should be fixed by the new open at last unread message, please reopen if it still occurs
