### ISSUE TITLE
Enable copy & paste of QR codes

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-desktop#1488]
Desktop should be able to process the data encrypted in qr codes as string transferred via copy & paste

**Comment by r10s** [comment]
to bring this forward, i think the currently mostly needed part os allow pasting a qr-code of the type DC_QR_ACCOUNT that is passes to [dc_set_config_from_qr()](https://c.delta.chat/classdc__context__t.html#ac95d7275f01862fba70169b8cbb937c0) then

**Comment by Jikstra** [comment]
@nicodh i think this is done or did you mean something more specific?
