### ISSUE TITLE
Error: Account has no address defined

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#1493]
Just broke on mac...

And why do we still have those ugly hashes in the folder name?

**Comment by Simon-Laux** [comment]
did you mess with the configuration of that account, or what did you do before? we should really identify this "account = null" issue quickly.

> And why do we still have those ugly hashes in the folder name?

Because this variable is not set to true yet: https://github.com/deltachat/deltachat-desktop/blob/master/src/main/logins.js#L11
