### ISSUE TITLE
avatars with emoji are partly broken

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1498]
if the name of a user starts with an emoji, this is displayed wrong in the chat-window - in the profile, it is displayed correctly. the following screenshot should show all the same avatars, however, the right ones show a "?" instead of the laughing-smiley:

![Screen Shot 2020-03-07 at 17 41 01](https://user-images.githubusercontent.com/9800740/76147319-62159380-609b-11ea-8a3e-396fbe479162.png)

tested in delta 1.0 on mac.

**Comment by Simon-Laux** [comment]
seems to be the font family...

**Comment by Simon-Laux** [comment]
my last guess was wrong, It was a code bug.
