### ISSUE TITLE
Move conversations into desktop?

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#150]
I foresee quite a lot of changes going into the `conversations` module. What do people think about moving it into desktop instead of keeping it as a separate module? It would simplify development a lot.

**Comment by ralphtheninja** [comment]
Nevermin, it's probably just as painful to move it.

**Comment by hpk42** [comment]
what is currently done in "conversations" as opposed to "desktop" proper? 
(i can imagine something but would rather like to hear things first-hand :)

**Comment by ralphtheninja** [comment]
> what is currently done in "conversations" as opposed to "desktop" proper?

I don't understand the question. Are you wondering what that module does?

**Comment by hpk42** [comment]
On Thu, Oct 11, 2018 at 11:34 -0700, Lars-Magnus Skog wrote:
> > what is currently done in "conversations" as opposed to "desktop" proper?
> 
> I don't understand the question. Are you wondering what that module does?

yes, wondering what "conversations"'s role is in the scheme of desktop things.

**Comment by ralphtheninja** [comment]
> yes, wondering what "conversations"'s role is in the scheme of desktop things.

Cool. Lets take an example.

In the `ChatView` we have messages, which are components we pull in here https://github.com/deltachat/deltachat-desktop/blob/master/src/renderer/components/ChatView.js#L223 , which uses the `Message` component from `conversations`. It's written in TypeScript and can be found here https://github.com/karissa/conversations/blob/master/ts/components/conversation/Message.tsx#L162

**Comment by hpk42** [comment]
On Thu, Oct 11, 2018 at 12:28 -0700, Lars-Magnus Skog wrote:
> > yes, wondering what "conversations"'s role is in the scheme of desktop things.
> 
> Cool. Lets take an example.
> 
> In the `ChatView` we have messages, which are components we pull in here https://github.com/deltachat/deltachat-desktop/blob/master/src/renderer/components/ChatView.js#L223 , which uses the `Message` component from `conversations`. It's written in TypeScript and can be found here https://github.com/karissa/conversations/blob/master/ts/components/conversation/Message.tsx#L162

and "conversations" is a rip-off signal code but not forked, right? 

FWIW i understand that with JS/node it's common practise to have many little
small repositories.  i appreciate the modularity that arises out of that
but there also is a complexity in making changes.  So if a component
is not *actually* used by someone else, it also makes pervasive changes/PRs
more difficult. This can be a good thing -- eg the language-barrier of delta-core
with UI code means that it's less easy to "blur" the lines. But it can also 
make code more complex than it needs to be ... </abstract-sidenote>

**Comment by ralphtheninja** [comment]
> FWIW i understand that with JS/node it's common practise to have many little small repositories. i appreciate the modularity that arises out of that but there also is a complexity in making changes. So if a component is not *actually* used by someone else, it also makes pervasive changes/PRs more difficult. This can be a good thing -- eg the language-barrier of delta-core with UI code means that it's less easy to "blur" the lines. But it can also make code more complex than it needs to be ... </abstract-sidenote>

You summed up my thoughts :)

**Comment by karissa** [comment]
yeah that's all true. 

The problem mostly is that the signal code is in typescript, so we'd have to have two different built processes in the desktop app (or write/port the desktop app to typescript)

**Comment by hpk42** [comment]
On Fri, Oct 12, 2018 at 12:17 -0700, Karissa McKelvey wrote:
> yeah that's all true. 
> 
> The problem mostly is that the signal code is in typescript, so we'd have to have two different built processes in the desktop app (or write/port the desktop app to typescript)

oh ok -- that appears to make sense then to keep it separate for the time being. 
It's not that we we don't have a lack of build-issues :)
