### ISSUE TITLE
v1.1.x seems to use old core

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1509]
version 1.1.x should fix the encrypt-to-ecc-keys-issue and use the most recent core (1.27), however, the about dialog reports 1.26.

**Comment by Simon-Laux** [comment]
https://github.com/deltachat/deltachat-core-rust/blob/master/CHANGELOG.md#1270
we don't provide a Desktop build that runs on arm so it should be fine.

**Comment by r10s** [comment]
it should work, tbh, i though i did not hit "Submit new issue" after commenting on that at https://github.com/deltachat/deltachat-desktop/issues/1508#issuecomment-597761846 :)
