### ISSUE TITLE
not working "copy link" in message-context-menu

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1512]
there is a "copy link" menu entry in the context menu (the three dots) of each message, independently if there is a link in the message or not.

clicking that item seems to to nothing, even if there is a link in the message.

right clicking directly on a link also shows the "copy link" option and works as expected.

otoh, the "copy to clipboard" that shall copy the whole message content is missing.

so, i would suggest to remove the "copy link" option from the context menu and replace it by the "copy to clipboard" function that will copy the whole message to clipboard then.

if that gets too complicated, i would also be fine with removing these copy functions from the context menu completely for now - as long as selecting and right-clicking works as now.

**Comment by Simon-Laux** [comment]
https://github.com/deltachat/deltachat-desktop/pull/1506 fixes the copy link part.

> otoh, the "copy to clipboard" that shall copy the whole message content is missing.
- feature requests in the forum or at-least in a separate issue, please.
