### ISSUE TITLE
decryption of messages fails randomly, update core

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1515]
decryption of messages fails randomly, the same messages can be decrypted by ios/android and also by thunderbird/autocrypt.

i have also seen that in my private family group with only 3 members, stable keys, no ecc, no changes. never had problems there before.

might be that the bug is already fixed implicitly by the core27 - because this is the "huge" difference between android/ios and desktop - android/ios use core27 while desktop still uses core26.

**Comment by link2xt** [comment]
core26 used pgp 0.4.1: https://github.com/deltachat/deltachat-core-rust/blob/1.26.0/Cargo.lock

core27 uses pgp 0.5.1: https://github.com/deltachat/deltachat-core-rust/blob/1.27.0/Cargo.lock

At least, it includes this bugfix: https://github.com/rpgp/rpgp/commit/e23fa4ef0ff3e4fb6e415764cb0c4adeae435a91

**Comment by Jikstra** [comment]
Should be fixed by https://github.com/deltachat/deltachat-desktop/commit/7f19a9b68679d06c94e2d149adeab875e63358c7

**Comment by r10s** [comment]
great :) really looking forward to the download :)

**Comment by Jikstra** [comment]
https://download.delta.chat/desktop/v1.1.1/
