### ISSUE TITLE
Settings are shared between different accounts

### ISSUE THREAD

**Issue by haeckser** [deltachat/deltachat-desktop#1519]
- Platform (linux/mac/windows): linux
- Delta Chat Desktop Version: 1.1.1
- Expected behavior:When switching between different accounts, the settings should be individual (e.g. background to mark the different accounts in a very simple way
- Actual behavior: settings are active for all accounts
- Steps to reproduce the problem: configure different accounts, open settings and switch background. switch account - background is the same
- Screenshots:
- Logs:

**Comment by r10s** [comment]
afaik, this really only affects the background image, in general, the settings are shared :)

**Comment by Simon-Laux** [comment]
this affects all local settings:
- last window size and position
- language
- experimental features enabled (enableOnDemandLocationStreaming)
- zoomFactor
- background image
- enterKeySends
- notifications & showNotificationContent
they are global. Also this is a feature request technically..
Anyway which of those global settings should be account specific?
Also this bring up the question whether we should separate global from account settings somehow visually?

**Comment by r10s** [comment]
i'd say for most of these settings, it is not that bad to keep them global.

i would not target this issue now, there are more important things to do, eg. going to the stores.

**Comment by gerryfrancis** [comment]
I wonder if this is true under Windows as well, because the database of Delta Chat is stored in the respective user profile.

**Comment by Jikstra** [comment]
Moving to project resurrection as this is currently out of scope
