### ISSUE TITLE
error on importing key files

### ISSUE THREAD

**Issue by haeckser** [deltachat/deltachat-desktop#1520]
- Platform (linux/mac/windows): linux
- Delta Chat Desktop Version: 1.1.1
- Expected behavior: I exported the key with account A, switch account to B and try to import the keys (to use it for all my accounts). Keys should be imported and used for account B
- Actual behavior: On importing, the message 'set_self_key:"Not a valid private key" ' raises. I expect the keys are not imported and so I cannot sync them
- Steps to reproduce the problem:as described in Expected behavior
- Screenshots:
- Logs:
"2020-03-21T15:48:41.381Z"	"main/index"	"INFO"		"cwd /home/haeckser/.var/app/chat.delta.desktop/config/DeltaChat"
"2020-03-21T15:48:41.384Z"	"main/deltachat/login"	"INFO"		"Using deltachat instance /home/haeckser/.var/app/chat.delta.desktop/config/DeltaChat/686165636b73657240756e73326875732e6465"
"2020-03-21T15:48:41.460Z"	"main/menu"	"INFO"		"rebuilding menu with locale de"
"2020-03-21T15:48:41.480Z"	"logger/log-cleanup"	"INFO"		"Successfuly deleted 1 old logfiles"
"2020-03-21T15:48:41.492Z"	"main/deltachat/login"	"INFO"		"Ready"
"2020-03-21T15:48:41.503Z"	"main/deltachat/login"	"INFO"		....

"2020-03-21T15:48:41.820Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.<anonymous> (/app/delta/resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:628:18),\n/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13"	"ThreadId(25) src/job_thread.rs:90: connect+fetch failed: Watch folder not found \"not-set\", reconnect & retry"
"2020-03-21T15:48:41.893Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.<anonymous> (/app/delta/resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:628:18),\n/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13"	"ThreadId(25) src/imap/mod.rs:341: failed to close connection: Bad(\"code: None, info: Some(\\\"Please select a mailbox first\\\")\")"
"2020-03-21T15:48:42.195Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.<anonymous> (/app/delta/resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:628:18),\n/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13"	"ThreadId(25) src/job_thread.rs:93: connect+fetch failed: Watch folder not found \"not-set\""
"2020-03-21T15:48:42.494Z"	"main/state"	"INFO"		"Saving state to /home/haeckser/.var/app/chat.delta.desktop/config/DeltaChat/config.json"
"2020-03-21T15:48:44.475Z"	"main/state"	"INFO"		"Saving state to /home/haeckser/.var/app/chat.delta.desktop/config/DeltaChat/config.json"
"2020-03-21T15:48:52.842Z"	"main/deltachat/login"	"INFO"		"Logged out"
"2020-03-21T15:48:53.843Z"	"main/state"	"INFO"		"Saving state to /home/haeckser/.var/app/chat.delta.desktop/config/DeltaChat/config.json"
"2020-03-21T15:48:54.465Z"	"main/deltachat/login"	"INFO"		"Using deltachat instance /home/haeckser/.var/app/chat.delta.desktop/config/DeltaChat/7075626c696340756e73326875732e6465"
"2020-03-21T15:48:54.469Z"	"main/deltachat/login"	"INFO"		"Ready"
"2020-03-21T15:48:54.489Z"	"main/deltachat/login"	"INFO"		"......

"2020-03-21T15:48:54.901Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.<anonymous> (/app/delta/resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:628:18),\n/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13"	"ThreadId(35) src/job_thread.rs:90: connect+fetch failed: Watch folder not found \"not-set\", reconnect & retry"
"2020-03-21T15:48:54.901Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.<anonymous> (/app/delta/resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:628:18),\n/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13"	"ThreadId(35) src/imap/mod.rs:341: failed to close connection: Bad(\"code: None, info: Some(\\\"Please select a mailbox first\\\")\")"
"2020-03-21T15:48:55.167Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.<anonymous> (/app/delta/resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:628:18),\n/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13"	"ThreadId(35) src/job_thread.rs:93: connect+fetch failed: Watch folder not found \"not-set\""
"2020-03-21T15:48:55.471Z"	"main/state"	"INFO"		"Saving state to /home/haeckser/.var/app/chat.delta.desktop/config/DeltaChat/config.json"
"2020-03-21T15:49:23.629Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.<anonymous> (/app/delta/resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:628:18),\n/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13"	"ThreadId(35) src/job_thread.rs:90: connect+fetch failed: Watch folder not found \"not-set\", reconnect & retry"
"2020-03-21T15:49:23.707Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.<anonymous> (/app/delta/resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:628:18),\n/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13"	"ThreadId(35) src/imap/mod.rs:341: failed to close connection: Bad(\"code: None, info: Some(\\\"Please select a mailbox first\\\")\")"
"2020-03-21T15:49:24.010Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.<anonymous> (/app/delta/resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:628:18),\n/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13"	"ThreadId(35) src/job_thread.rs:93: connect+fetch failed: Watch folder not found \"not-set\""
"2020-03-21T15:49:30.913Z"	"main/deltachat/login"	"INFO"		"Logged out"
"2020-03-21T15:49:31.913Z"	"main/state"	"INFO"		"Saving state to /home/haeckser/.var/app/chat.delta.desktop/config/DeltaChat/config.json"
"2020-03-21T15:49:32.519Z"	"main/deltachat/login"	"INFO"		"Using deltachat instance /home/haeckser/.var/app/chat.delta.desktop/config/DeltaChat/6d696b6b656c40756e73326875732e6465"
"2020-03-21T15:49:32.524Z"	"main/deltachat/login"	"INFO"		"Ready"
"2020-03-21T15:49:32.528Z"	"main/deltachat/login"	"INFO"		"
....
"2020-03-21T15:49:32.800Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.<anonymous> (/app/delta/resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:628:18),\n/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13"	"ThreadId(49) src/job_thread.rs:90: connect+fetch failed: Watch folder not found \"not-set\", reconnect & retry"
"2020-03-21T15:49:32.877Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.<anonymous> (/app/delta/resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:628:18),\n/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13"	"ThreadId(49) src/imap/mod.rs:341: failed to close connection: Bad(\"code: None, info: Some(\\\"Please select a mailbox first\\\")\")"
"2020-03-21T15:49:33.193Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.<anonymous> (/app/delta/resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:628:18),\n/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13"	"ThreadId(49) src/job_thread.rs:93: connect+fetch failed: Watch folder not found \"not-set\""
"2020-03-21T15:49:33.524Z"	"main/state"	"INFO"		"Saving state to /home/haeckser/.var/app/chat.delta.desktop/config/DeltaChat/config.json"
"2020-03-21T15:49:55.809Z"	"main/deltachat"	"ERROR"	"\nonError (/app/delta/resources/app.asar/tsc-dist/main/deltachat/controller.js:228:17),\nDeltaChat.<anonymous> (/app/delta/resources/app.asar/tsc-dist/main/deltachat/controller.js:231:13),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:631:18),\n/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13"	"set_self_key: \"Not a valid private key\""
"2020-03-21T15:49:55.810Z"	"main/deltachat"	"ERROR"	"\nonError (/app/delta/resources/app.asar/tsc-dist/main/deltachat/controller.js:228:17),\nDeltaChat.<anonymous> (/app/delta/resources/app.asar/tsc-dist/main/deltachat/controller.js:231:13),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:631:18),\n/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13"	"set_self_key: \"Not a valid private key\""
"2020-03-21T15:49:55.811Z"	"renderer/ipc"	"ERROR"	"\nEventEmitter.<anonymous> (file:///app/delta/resources/app.asar/html-dist/bundle.js:40215:46),\nEventEmitter.emit (events.js:205:15),\nObject.onMessage (/app/delta/resources/electron.asar/renderer/init.js:42:16)"	"set_self_key: \"Not a valid private key\""
"2020-03-21T15:49:55.838Z"	"renderer/ipc"	"ERROR"	"\nEventEmitter.<anonymous> (file:///app/delta/resources/app.asar/html-dist/bundle.js:40215:46),\nEventEmitter.emit (events.js:205:15),\nObject.onMessage (/app/delta/resources/electron.asar/renderer/init.js:42:16)"	"set_self_key: \"Not a valid private key\""
"2020-03-21T15:49:55.858Z"	"main/deltachat"	"ERROR"	"\nonError (/app/delta/resources/app.asar/tsc-dist/main/deltachat/controller.js:228:17),\nDeltaChat.<anonymous> (/app/delta/resources/app.asar/tsc-dist/main/deltachat/controller.js:231:13),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:631:18),\n/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13"	"set_self_key: \"Not a valid private key\""
"2020-03-21T15:49:55.867Z"	"renderer/ipc"	"ERROR"	"\nEventEmitter.<anonymous> (file:///app/delta/resources/app.asar/html-dist/bundle.js:40215:46),\nEventEmitter.emit (events.js:205:15),\nObject.onMessage (/app/delta/resources/electron.asar/renderer/init.js:42:16)"	"set_self_key: \"Not a valid private key\""
"2020-03-21T15:49:55.895Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.<anonymous> (/app/delta/resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:628:18),\n/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13"	"ThreadId(49) src/job_thread.rs:90: connect+fetch failed: Watch folder not found \"not-set\", reconnect & retry"
"2020-03-21T15:49:55.983Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.<anonymous> (/app/delta/resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:628:18),\n/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13"	"ThreadId(49) src/imap/mod.rs:341: failed to close connection: Bad(\"code: None, info: Some(\\\"Please select a mailbox first\\\")\")"
"2020-03-21T15:49:56.292Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.<anonymous> (/app/delta/resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:628:18),\n/app/delta/resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13"	"ThreadId(49) src/job_thread.rs:93: connect+fetch failed: Watch folder not found \"not-set\""
"2020-03-21T15:55:26.787Z"	"main/state"	"INFO"		"Saving state to /home/haeckser/.var/app/chat.delta.desktop/config/DeltaChat/config.json"
"2020-03-21T15:55:26.790Z"	"main/index"	"INFO"		"Quitting now. Bye."

**Comment by gerryfrancis** [comment]
@haeckser It is reported here, too: https://github.com/deltachat/deltachat-core-rust/issues/1104

**Comment by Jikstra** [comment]
Closing as it's a duplicate as @gerryfrancis pointed out :)
