### ISSUE TITLE
message reported as sent but has no trace on both sides

### ISSUE THREAD

**Issue by searoso** [deltachat/deltachat-desktop#1521]
- Platform (linux/mac/windows):linux
- Delta Chat Desktop Version:0.102.0-PREVIEW
- Expected behavior:message received by another party and saved in sender's mailbox
- Actual behavior:message is marked as "

sent | Sunday, March 22, 2020 2:11 PM (1584875504000)
-- | --
received | Sunday, March 22, 2020 2:11 PM (1584875507000)

" but reported as missing by another party and can't be find in sender's mailbox
- Steps to reproduce the problem:
- Screenshots:
![Screenshot from 2020-03-22 14-16-32](https://user-images.githubusercontent.com/110407/77248107-0e34ae00-6c48-11ea-8759-d9381a8fbf0f.png)

- Logs:need instruction to attach

**Comment by gerryfrancis** [comment]
@searoso You have been using a plain old version of Delta Chat Desktop. Please download and review the latest version from here https://download.delta.chat/desktop/v1.1.1/ and close this issue. Thank you.

**Comment by Simon-Laux** [comment]
right this version is really old, please update and if it reappears you can reopen this issue.
