### ISSUE TITLE
Message could not decrypted

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-desktop#1522]
- Platform (linux/mac/windows): Linux
- Delta Chat Desktop Version: Version 1.1.0
- Expected behavior: decrypt all messages
- Actual behavior: one message is not decrypted

I got a picture message in a current existing encrypted chat. All messages are encrypted and can be decrypted. 
Only this one picture can not decrypted on Desktop Client. On the phone it works as expected.

I have no idea how to reproduce. 
And also I have no log for the time where the message was received.

**Comment by r10s** [comment]
i think this is fixed with 1.1.1, see https://github.com/deltachat/deltachat-desktop/issues/1515

**Comment by webratte** [comment]
Yes, it sounds like it's the same issue.
Thank you for the hint.

So I think you can close this.

**Comment by r10s** [comment]
thanks for re-checking :)
