### ISSUE TITLE
go to next/previous image in enlarged-image-view

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1539]
when enlarging an image, it should be possible to go to the next or to the previous image using the arrow keys. 

also, there should be some buttons for that. the easiest might be to add them to the toolbar that already has the download icon (lower right corner)

if needed, the core has a helper for that, see [dc_get_next_media()](https://c.delta.chat/classdc__context__t.html#a9bb2762236dc193c7e5fd155d66c80d5)

**Comment by Simon-Laux** [comment]
solved by #2396 and #2403

**Comment by r10s** [comment]
\o/
