### ISSUE TITLE
add searching for messages and contacts

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1542]
the current search for chats should be extended to search for contacts and messages as well.

the search should work the same as for android and ios, search results may be chats, contacts or messages, displayed in this order.

- for the first group, chats, this is already done
- contacts can be searched using [dc_get_contacts()](https://c.delta.chat/classdc__context__t.html#a12e37e12b183a124af1c6a1d5304d074)
- messages can be searched using [dc_search_msgs()](https://c.delta.chat/classdc__context__t.html#a777bb1e11d7ea0288984ad23c2d8663b)

esp. the last group may easily result in some thousands results. while the search-function is typically "fast enough", it is probably not doable to prefill all items, only the contacts/messages really in view should be displayed (when typing only one characters, these are typically none until on scrolls as there are already several chat results)

**Comment by Jikstra** [comment]
This is fixed i think. @Simon-Laux reopen if not :)
