### ISSUE TITLE
Create chat with an email not in the contacts list

### ISSUE THREAD

**Issue by sbadux** [deltachat/deltachat-desktop#155]
Hello,
I think that we should be able to create a new chat by typing the email of the receiver. Now we must create a new contact before be able to create a conversation with him.

**Comment by hpk42** [comment]
i'd also often wanted to "chat with <e-mail>" and am all for
simplifying this work flow.  Even the android one did not feel
totally intuitive to me IIRC.

**Comment by r10s** [comment]
> Even the android one did not feel totally intuitive to me IIRC.

android-telegram required to click an "add contact" button which brings you to an activity to create a contact. this created contact can then be selected (resp. is selected implicitly)

android-dev has a search-field where you can also "just" input an email address and create a new contact this way, feels at least a bit simpler to me.

**Comment by sbadux** [comment]
> @sbadux How do you see this workflow? Would a simple input field be enough to fill in email + an OK button?
The android-style is pretty good IMHO.
Anyway, in the Android app you ALWAYS create a new contact for each email address and this is not the best choice for me.

I would make it work in this way:
- Click on Create Chat
- Put a bar on the top where you can input an email address (like the Android search bar)
- If the email address exists, show the contact
- If the email address doesn't exist show two options: 1) Create contact & chat 2) Chat. The second option won't create a contact but just create the chat.

This would me my best workflow, but you are the one who knows if it's difficult to develop and/or it worth the additional work.

**Comment by hpk42** [comment]
On Tue, Oct 16, 2018 at 09:32 -0700, sbadux wrote:
> > @sbadux How do you see this workflow? Would a simple input field be enough to fill in email + an OK button?
> The android-style is pretty good IMHO.
> Anyway, in the Android app you ALWAYS create a new contact for each email address and this is not the best choice for me.
> 
> I would make it work in this way:
> - Click on Create Chat
> - Put a bar on the top where you can input an email address (like the Android search bar)
> - If the email address exists, show the contact
> - If the email address doesn't exist show two options: 1) Create contact & chat 2) Chat. The second option won't create a contact but just create the chat.

Is 2) because you want to not have this e-mail in your contact list but only
start an "once-off" chat?

**Comment by sbadux** [comment]
> On Tue, Oct 16, 2018 at 09:32 -0700, sbadux wrote: > @sbadux How do you see this workflow? Would a simple input field be enough to fill in email + an OK button? The android-style is pretty good IMHO. Anyway, in the Android app you ALWAYS create a new contact for each email address and this is not the best choice for me. I would make it work in this way: - Click on Create Chat - Put a bar on the top where you can input an email address (like the Android search bar) - If the email address exists, show the contact - If the email address doesn't exist show two options: 1) Create contact & chat 2) Chat. The second option won't create a contact but just create the chat.
> Is 2) because you want to not have this e-mail in your contact list but only start an "once-off" chat?

Yes :-) It's not fundamental but would be appreciated. It's like for the emails: you don't need to save the address in the contacts to write an email.

**Comment by ralphtheninja** [comment]
> Yes :-) It's not fundamental but would be appreciated. It's like for the emails: you don't need to save the address in the contacts to write an email.

Aaah, I was wondering why you wouldn't always want to create a contact. Didn't think of this use case. Makes sense.

**Comment by karissa** [comment]
is this possible in core? @r10s

**Comment by nicodh** [comment]
At the moment we have these steps:
1. new chat
2. add contact (other options are: new group or new verified group)
3. enter mail & name
4. add => which saves the contact and immediately creates a chat with the new contact.
I don't see which of these steps could be reduced. We could rename the labels: instead of add contact it could just say "new contact" and instead of "add contact" in the save button just "create chat"

**Comment by Jikstra** [comment]
Fixed by https://github.com/deltachat/deltachat-desktop/pull/997
