### ISSUE TITLE
drag'n'dropping multiple files does not send/ask for all files

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1552]
seems as if only the last is sent.

was just wondering why the recipient dies not get the 3 mp3's i've just sent :)

**Comment by Jikstra** [comment]
Ouh when reading this issue i have a snippet of code in my mind where we just pull out element number zero of some electron api.. I guess this could be the cause of this.

**Comment by Simon-Laux** [comment]
Nope turns out it is our dialog system that can only handle one dialog of the same type at a time and overwrites existing dialogs with the new one, so no wonder it asks only for the last file.

**Comment by Simon-Laux** [comment]
A workaround could be to show only one dialog that lists the files and asks if you are sure to send them all.
