### ISSUE TITLE
app window closes a few secs after start without any note

### ISSUE THREAD

**Issue by TheOtherDoctor** [deltachat/deltachat-desktop#1554]
- Platform (linux/mac/windows): Windows 10 Home v1909
- Delta Chat Desktop Version: 1.1.0
- Expected behavior: stay open and tell if there is a problem.
- Actual behavior: app closes a few seconds after start.
- Steps to reproduce the problem: for me currently, always happens. :-(
- Screenshots: -
- Logs: (see snip below)

After starting DeltaChat desktop client for first time after not opening for some days, and with a few messages having been transferred on that same account via other devices, the app has to download the skipped messages. This mostly works fine (only a few of those "cannot decrypt" blocks remain), but finally the app just closes down, without any note why.

Looking into the logs reveals always:
`"2020-04-14T21:20:02.458Z"	"main/index"	"INFO"		"cwd C:\\Users\\xxxxxx\\AppData\\Local\\DeltaChat"`
`[...]`
`"2020-04-14T21:20:07.094Z"	"main/state"	"INFO"		"Saving state to C:\\Users\\xxxxxx\\AppData\\Local\\DeltaChat\\config.json"`
`"2020-04-14T21:20:33.464Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.<anonymous> (C:\\Users\\xxxxxx\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\deltachat\\controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (C:\\Users\\xxxxxx\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\dist\\deltachat.js:628:18),\nC:\\Users\\xxxxxx\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\dist\\deltachat.js:50:13"	"ThreadId(16) src\\job.rs:195: SMTP failed to send: future timed out"`

So, it wants to tell me - that the future timed out... ?! :-)
Looks like there is some hard 30sec deadline for something?
Probably something is stuck on the IMAP server side, but I cannot see what. 
Same account perfectly simultaneously running on other (Android/Lineage) devices.

It is alive long enough for me to type a message and hit send, but that never gets sent.

**Comment by TheOtherDoctor** [comment]
Just installed v1.1.1 - same effect, same log. :-(

**Comment by Jikstra** [comment]
Hmm weird. Could be the core library dying because you have a weird email in your inbox. Do you also run the android or ios app? If so is that one dying too or not?

**Comment by gerryfrancis** [comment]
FYI, version 1.1.1 of Delta Chat desktop does not include core version 1.28, yet. It would be interesting to see whether Desktop version 1.2.0 has the same behavior or not. @TheOtherDoctor Could you check this out, please?

**Comment by TheOtherDoctor** [comment]
The latest install pack I find on https://github.com/deltachat/deltachat-desktop/releases is the 1.1.1, that's why I used that. 
I downloaded the 1.2 source zip now, but as far as I understood, this needs compilation or the like - this is beyond my skills (on Windows machines). :-(

**Comment by gerryfrancis** [comment]
@TheOtherDoctor Please download Desktop 1.2.0 from here: https://download.delta.chat/desktop/v1.2.0/DeltaChat%20Setup%201.2.0.exe . This is the regular installer.

**Comment by TheOtherDoctor** [comment]
Oops, so I failed to get the wrong download path, sorry. I think I should have learned this already a previous time... :-) 
Might help to mention the generic base dir URL on top of the releases page. If the new is there listed on top, at least I did not get to looking at the bottom for an idea to get to a newer one. ;-)

**Comment by TheOtherDoctor** [comment]
So now I installed 1.2.0, same problem as before.

Just some more observations and trials:

I stated in the original post that the same account is ok from Android(s); that was wrong, the "me" on Win is a different account than the one on Android - it's the same chat anyway, as I'm chatting with myself there, so to say.
I had enough time before crash to do "switch account" on the desktop client, to go to the one which is working on Android client... that seems stable. So it is not the desktop client broken in general, it just fails to handle the server error situation with the email provider (gmx.net in this case); needless to say that accessing that mail account from a mail client works fine, as far as I can see.

I also tried to delete all messages which were marked undecryptable in the desktop, did not change anything. Also tricky to get them all, as I have only those weird 30secs until the app crashes. On two Android devices, I never got these decryption issues, both devices see them as properly sent messages.

Looks like I'd have to take another Android device, install the app there and try the broken account. I am anyway unsure how to create a comparable setup there, as I do not yet have one yet - the backup on the desktop client fails when the bad account is active.
Thus, for an Android cross check, I'd lack the encryption key, as the "send autocrypt message to self" also fails on the crashing desktop client. 
Thus I'd could only do a fresh install on Android, with new key creation, and cross check the behaviour on Android. 
Unless there is some smarter proposal, I'd go for that...

**Comment by TheOtherDoctor** [comment]
I've now tried first just deleting all accounts on the desktop client, and re-added the problematic one. The client is stable with this state, but obviously a setup via "send autocrypt message" does not really work out to have actually the same key setup - a message I write from the desktop app to a receiver already contacted on the Android does not show up in the Android app. 
So I'd try if a backup exported from the Android 1.3.0 can be imported into 1.2.0? 

Overall, I'd extract as learned lesson that there might be room for improvement in error handling when the account setting somehow got inconsistent - I think I somehow managed to have different key setups resulting from simultaneous use with the various clients, resulting in those seemingly random "undecryptable message" issues. 

As I have now re-created the setups, and had no chance to create a backup before, I worry this will be rather impossible to reproduce. :-(

Anyway, thanks a lot for your hints + support!

**Comment by gerryfrancis** [comment]
I wonder if this could be related to https://github.com/deltachat/deltachat-core-rust/issues/1350 ...

**Comment by Simon-Laux** [comment]
please retry with https://support.delta.chat/t/test-upcomming-desktop-1-10-x-release/1080
