### ISSUE TITLE
Provide at least "INFO" logging by default

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#1555]
very often desktop users get back with useless logs because the default is to only provide WARN/ERROR level logs when the ".tsv" is created.  Please provide at least INFO-level messages or maybe even DEBUG simply.  The main reason is helping devs to help users.

**Comment by Simon-Laux** [comment]
The default is to show anything that is not at the DEBUG level.
I can upgrade DC_EVENT_INFO to be logged as INFO. (currently all core events are logged as debug.)
Enable `--log-debug` to enable logging of debug messages.

**Comment by hpk42** [comment]
thanks!
