### ISSUE TITLE
Build the preview builds on the right platforms

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1559]
#### Problems:
- At the moment all preview builds fail because wine fails to install - this would be solved by building on windows.
- We can not build/pack DMG files on the current linux ci - using a mac runner would solve that.

**Comment by Jikstra** [comment]
I'm currently implementing almost this for the -node repo, still having some troubles with the package script (i think the && syntax is not compatible with windows). Once this is done we can almost copy those ci scripts for the desktop.

https://github.com/deltachat/deltachat-node/pull/438

**Comment by Simon-Laux** [comment]
> (i think the && syntax is not compatible with windows)

that is already fixed in a newer powershell version, but unfortunately windows doesn't ship with that new version yet AFAIK.

Anyways only a windows preview build is left to do now as it seems.
