### ISSUE TITLE
Error in messages order when synchronising

### ISSUE THREAD

**Issue by frankiezafe** [deltachat/deltachat-desktop#1562]
- Platform (linux/mac/windows): mx linux, Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
- Delta Chat Desktop Version: 1.2.0
- Expected behavior: when i open delta.chat, i expect to find the messages in the chronological order after the synchronisation
- Actual behavior: latest received message is mixed up in previous messages
- Steps to reproduce the problem: you need 2 desktop applications; open deltachat on the first computer; send messages with a copy to yourself to friends; close deltachat on this machine and ask your friend to send you messages while offline; open deltachat on second computer and start talking; the synching process will run in background and fails to reorganise the messages
- Screenshots:
- Logs: none
![Screenshot](https://user-images.githubusercontent.com/3447074/79559436-02e96c80-80a6-11ea-860a-6efe617e5e73.png)

**Comment by Simon-Laux** [comment]
This problem is the current expected behavior, see https://support.delta.chat/t/order-of-messages/698 for the ongoing discussion. I invite you to take part in the discussion over there.
Also it's rather a core issue so I'll close this here.
