### ISSUE TITLE
Regression: Switching chats with arrow-keys broke recently

### ISSUE THREAD

**Issue by pabzm** [deltachat/deltachat-desktop#1565]
Somewhere between 2bc75ce4 and 0b9d620d the desktop app lost the possibility to switch from each chat to the next and the previous chat by pressing `alt-ArrowDown` and `alt-ArrowUp`, respenctively.

Instead now in both cases the first chat in the list is selected.

**Comment by gerryfrancis** [comment]
Works for me in Delta Chat Desktop version 1.2.0.

**Comment by Jikstra** [comment]
Can reproduce it on latest master

**Comment by Jikstra** [comment]
I guess it's related to this: https://github.com/deltachat/deltachat-desktop/pull/1560
