### ISSUE TITLE
Backups should require password both on export and especially on import

### ISSUE THREAD

**Issue by LeeteqXV** [deltachat/deltachat-desktop#1568]
- Platform (linux/mac/windows): Linux + Android
- Delta Chat Desktop Version: 1.1.1/1.1.2
- Expected behavior: Prompt for password
- Actual behavior: Backups are totally unprotected!(?)
- Steps to reproduce the problem: Any export/import backup.
- Screenshots: n/a
- Logs: n/a

**Comment by gerryfrancis** [comment]
@LeeteqXV Do you probably mean the encryption of backups?

**Comment by Jikstra** [comment]
This is a feature we need for sure, but mainly a core issue. Not too much we can do here in the desktop repo about this.

As this is a feature request, i think the support forum would be the proper place to talk about this, we try to keep the github issues a place for mainly bug reports and features we're currently working on. 

I would close this for now & hope to see this feature land in core soon :)
