### ISSUE TITLE
titlebar is gone on 1.3

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1583]
at least on mac, the title bar is completely gone, there is no longer an option to move the window at all, the close/maximize/minimize buttons are placed over the search field

![Screen Shot 2020-04-30 at 18 06 22](https://user-images.githubusercontent.com/9800740/80733200-ae1a0d00-8b0d-11ea-9859-0b87291b3a8a.png)

**Comment by r10s** [comment]
same for the help-window

**Comment by Jikstra** [comment]
Neat :D Looks like an electron bug to me...

**Comment by r10s** [comment]
hm, wasn't also the menu bar updated (minimize etc.) maybe this is related.

**Comment by Jikstra** [comment]
Bisected it down to this commit: https://github.com/deltachat/deltachat-desktop/pull/1524/commits/cb0e933063e7ffc8fa8e277296cd17e797f4fd78

**Comment by r10s** [comment]
great! good find!

**Comment by r10s** [comment]
and it worked before because of a typo in the attribute-name the hiding was ignored https://github.com/deltachat/deltachat-desktop/commit/cb0e933063e7ffc8fa8e277296cd17e797f4fd78#diff-7a5c146b7b97407c69f9fc8faec491faL45 :)
