### ISSUE TITLE
help lacks navigation options

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1584]
if you click on an item in the contents, the help scrolls done, however, there is no easy way to navigate back.

we have the same issue on ios, we added "back to top" links after each chapter there, this should be a good and quick fix for desktop as well. 

you just have to add the corresponding flag on generation, https://github.com/deltachat/deltachat-pages/blob/master/tools/create-local-help.py#L95

**Comment by Simon-Laux** [comment]
There is a floating button to go to the top.
Is it missing on Mac? Or is it too hidden (the button color is probably too similar to the background) to spot?
![2020-05-01_08-19](https://user-images.githubusercontent.com/18725968/80786593-608cb700-8b84-11ea-802f-2538f3e7dcae.png)

**Comment by r10s** [comment]
ahh, okay, i've overseen that. yip, it is there on mac :)

**Comment by Simon-Laux** [comment]
Maybe it needs to get another color to draw attention to it?

**Comment by r10s** [comment]
i think it is fine for now, i've just overseen it. maybe i was a bit confused by the missing title bar on mac.

i'd say if there are more complains, we can think it over.
