### ISSUE TITLE
scan qr-code does not work on mac

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1586]
scanning qr-code does not work on mac, also, there is no error displayed or so.

**Comment by Simon-Laux** [comment]
no error? something about it in the devconsole or in the logfile?
The issue could be a permission error? is the camera part not working or is the scanning not working?

**Comment by r10s** [comment]
the camera is not shown, no image is displayed. i do not get an error or so.

this is how it looks like:

<img width="866" alt="Screen Shot 2020-05-01 at 11 59 21" src="https://user-images.githubusercontent.com/9800740/80797947-647c0180-8ba3-11ea-859f-788a1253371b.png">

wrt log - this entry is either gone or moved so that i cannot find it, i file a separate issue for that.

**Comment by r10s** [comment]
this seems to be fixed by #1589
