### ISSUE TITLE
feedback missing on hovering attached files, hard to open files

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1587]
while, you can "open" an attachment by one click, it is not obvious how this can be done:

- there is no visual feedback that you can click the attachment-icon to open it, i would expect the "pointing hand" as used in most other similar situations

- also, at least the title should be clickable, not only the icon. maybe it is the best to make the whole div with icon/title/size clickable and showing the pointing cursor

**Comment by Simon-Laux** [comment]
> also, at least the title should be clickable, not only the icon. maybe it is the best to make the whole div with icon/title/size clickable and showing the pointing cursor

This could conflict with the message buttons (download/show menu) - because they overlap in the current design.

**Comment by Simon-Laux** [comment]
so now only the second part is left todo.
