### ISSUE TITLE
"open log" on mac missing

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1588]
maybe it is gone, not sure. the menu on 1.2 ...

<img width="500" alt="Screen Shot 2020-05-01 at 11 35 34" src="https://user-images.githubusercontent.com/9800740/80798035-aad16080-8ba3-11ea-8b26-ecd2350018f0.png">

... and on 1.3:

<img width="500" alt="Screen Shot 2020-05-01 at 11 55 45" src="https://user-images.githubusercontent.com/9800740/80798020-a016cb80-8ba3-11ea-9e94-86f3688e5c82.png">

**Comment by Jikstra** [comment]
Seems like something with the electron version and the mac menu is weird. Bit hard to reproduce without having a mac... Time for a trip to brombi?

**Comment by r10s** [comment]
> Time for a trip to brombi?

;) 

also, the menu is no longer localized (the rest of the app belonging to the second screenshot is german), and there is a "File" menu containing the item "Close window" that was not there before - is that on-purpose?  maybe the menu is completely the default?

**Comment by Simon-Laux** [comment]
> maybe the menu is completely the default?

That's exactly what happened here.

**Comment by Simon-Laux** [comment]
was fixed by  #1605
