### ISSUE TITLE
Create src/renderer/ipc.js to hide ipcRenderer

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#159]
In a similar fashion like `src/main/ipc.js` wraps `electron.ipcMain`.

Pros:

* the code will be a lot cleaner, e.g. instead of doing `ipcRenderer.send('login', { email: login, password: true })` you would do something like `ipc.login({ email: login, password: true })`
* it's more symmetric and checking */ipc.js will make it easier to see what kind of ipc api there is

Cons:

* more boilerplate and more explicit code whenever you want to add a new method

**Comment by karissa** [comment]
It would be nice to abstract this out also for the purpose of making it easier to create a server or mobile implementation
