### ISSUE TITLE
Missing dependencies. I wish they were described somewhere

### ISSUE THREAD

**Issue by hesoyamimi** [deltachat/deltachat-desktop#1590]
Here's the list of posible dependencies that I was needed to launch an AppImage
`sudo apt-get install -y libgdk-pixbuf2.0-dev libnss3 libgtk-3-dev libasound2-dev build-essential`

It may be just because of a server build, but I find it convinient to have such list.

- Platform (linux/mac/windows): linux ubuntu 18 server
- Delta Chat Desktop Version: DeltaChat-1.2.0.AppImage
- Expected behavior: Just start assembling
- Actual behavior: Missing dependencies

**Comment by Simon-Laux** [comment]
So we should describe it in the Readme or on the website?
Or should we try to include those dependencies in the AppImage (aka. open an issue for it on electron builder, but unless somebody takes the initiative it will not be fixed anytime soon)
