### ISSUE TITLE
Build a snapcraft.io package

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop#1593]
electron-builder seems to be able to build snap packages: https://snapcraft.io/docs/electron-apps

**Comment by flub** [comment]
This builds by adding a `"dist": "electron-builder build --linux snap"` line to the `scripts` in `package.json`.  The result ends up in `dists/deltachat-desktop_*.snap` and can be installed with `sudo snap install dists/deltachat-desktop*.snap --dangerous --devmode`.   However when running it does not seem to be able to access an existing `$XDG_CONFIG_DIR/DeltaChat` directory.  And even worse after configuring an account the chatview is entirely broken.

**Comment by Jikstra** [comment]
We're already having problems with the AppImage and windows builds. It feels like it's just adding an option to electron builder but in reality it's nothing that easy. The AppImage is lacking dependencies and whatnot. Also i'm neither using snap or flatpak and don't really want to maintain another platform.

**Comment by link2xt** [comment]
Resulting snap package does not work for me:
```
Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /snap/deltachat-desktop/x1/resources/app.asar.unpacked/node_modules/deltachat-node/build/Release/deltachat.node)
```

**Comment by flub** [comment]
Best would be to find someone who is interested in properly maintaining
this, and preferably out of the main repo like flatpak is imho.  I was
only playing with it a bit to see if I could gets something to work
easily, turns out not.

**Comment by link2xt** [comment]
Looks like electron-builder is doing it wrong. It is better to build it on Ubuntu 20.04 with snapcraft and https://multipass.run/ and then hand it over to CI, rather than building on dev machines.

**Comment by Simon-Laux** [comment]
if the tray icon stuff is still an issue, then please file and track it under the community snap issue tracker (https://github.com/nbuechner/deltachat-snap/) unless there is sth. to do in this repo.
