### ISSUE TITLE
Delta Chat Desktop on Windows Server 2008 R2

### ISSUE THREAD

**Issue by konsta-n-tin** [deltachat/deltachat-desktop#1597]
- Platform (linux/mac/windows): Windows Server 2008 R2
- Delta Chat Desktop Version: 1.2.0
- Expected behavior: Start program when click on icon on desktop
- Actual behavior: Nothing happens
- Steps to reproduce the problem: Install Delta Chat Desktop Version 1.2.0 on Windows Server 2008 R2 and try to run
- Screenshots:
- Logs: Zero size logs in c:\Users\\%username%\AppData\Local\DeltaChat\logs\

**Comment by konsta-n-tin** [comment]
Hmm... The same problem on Windows Server 2012 R2

**Comment by Jikstra** [comment]
Can you check out if you have the visual c++ runtime installed? Seems like this is sometimes the problem on windows:
https://github.com/deltachat/deltachat-desktop/issues/1323

**Comment by konsta-n-tin** [comment]
> Can you check out if you have the visual c++ runtime installed? Seems like this is sometimes the problem on windows:
It was helped me!
Thank you!

**Comment by Simon-Laux** [comment]
https://stackoverflow.com/questions/35097193/can-i-bundle-the-visual-studio-2015-c-redistributable-dlls-with-my-applicatio

looks like its ok for ms when we bundle the files, now I only need to find a good way to get them and to bundle them... time to spin up a windows vm

**Comment by Simon-Laux** [comment]
another option would be to modify the building of the core for the node bindings: https://www.reddit.com/r/rust/comments/7mif9i/how_to_compile_binaries_without_dependencies_on/

**Comment by Simon-Laux** [comment]
Copying all the dll files of the redist to the deltachat instalation folder solved the issue, now I only need to change the build process to do that.

**Comment by Simon-Laux** [comment]
Hey folks, I have a portable version for you to test https://testrun.org/DeltaChat%201.4.0.testing.exe
It works for me on my windows vm, but I want to know if it works for you too.

**Comment by the-Arioch** [comment]
> Copying all the dll files of the redist to the deltachat instalation

....comparing DeltaChat footprint with VisualIRC footprint, "well, d'oh..."

As for test, my win box is not tainted with VC++ runtime, but will i have a clean windows box i will try

**Comment by Simon-Laux** [comment]
@the-Arioch yeah electron is heavy, though the msvc thing is actually required to run the deltachat core on windows.
There were two options left (unless there are more that I missed):
- Bundle the vcredist installer with our installer, but that doesn't solve the problem for the portable version.
- bundle the relevant files (aka. local deployment)

1,7mb more are not that much considering the electron footprint and we can still save some space by excluding more useless unused files from the final package.

**Comment by hpk42** [comment]
The apk is also >50MB so 70MB is not that bad. 
Really excited to get a "just installs" DC Desktop
version for windows -- a major milestone ;)
