### ISSUE TITLE
Missing word from Italian version of read receipt

### ISSUE THREAD

**Issue by EclecticSoftwareEngineer** [deltachat/deltachat-desktop#1598]
- Platform (linux/mac/windows): Linux, Android (probably all)
- Delta Chat Desktop Version: 1.2.0
- Expected behavior: include word 'non'
- Actual behavior: missing word 'non'
- Steps to reproduce the problem: Arrange for read receipt to be sent
- Screenshots:
- Logs:

The Italian read receipt reads (in part):

Ciò significa che il messaggio è stato mostrato nel dispositivo del destinatario, ma necessariamente che il contenuto è stato letto.

It should read:

Ciò significa che il messaggio è stato mostrato nel dispositivo del destinatario, ma non necessariamente che il contenuto è stato letto.

with the word 'non' added ("ma non necessariamente").

i.e., it should read, in English: "but not necessarily that the content has been read" instead of "but necessarily that the content has been read."

**Comment by Simon-Laux** [comment]
Thanks for reporting this issue,
I assume this should be fixed in transifex https://www.transifex.com/delta-chat/delta-chat-app/.
PS: if you find a normal bug that appears on all platforms please file it on https://github.com/deltachat/deltachat-core-rust

**Comment by r10s** [comment]
@EclecticSoftwareEngineer thanks a lot for the detailed report, i  directly fixed that on transifex :)
