### ISSUE TITLE
thin separators lines in chatlist

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1599]
i suggest to add  a thin line below each chat cell

- this improves readability, chats are better separated
- if you have more than one pinned chat, this "grey area" does not look good
- there is a subtile difference between the chatlist and other lists as contacts (these should not get the lines)
- looking around, these lines are used on android/ios - as well as eg. by telegram, also on desktop

btw. we removed the lines also when switching the android-ui that time - and got several report of users, that this minor element is pretty important :)

i just played around, a `.chat-list-item { border-bottom: 1px solid #ddd; }` already improves things significantly imho.

<img width="1232" alt="Screen Shot 2020-05-04 at 11 58 17" src="https://user-images.githubusercontent.com/9800740/80954937-9c32b580-8dfe-11ea-8809-93fe47e3fe81.png">

**Comment by Simon-Laux** [comment]
> if you have more than one pinned chat, this "grey area" does not look good

:heart: 
> as well as eg. by telegram, also on desktop

only on mac, no lines on linux telegram.

**Comment by r10s** [comment]
i think, there are differnt telegram apps around

**Comment by Simon-Laux** [comment]
Lets ommit the line of the archived chat button, otherwise the archive button stands too much out in  my opinion:
![2020-05-04_19-32](https://user-images.githubusercontent.com/18725968/80995088-fbfc8100-8e3d-11ea-92b7-1f037b97ac77.png)

**Comment by r10s** [comment]
> Lets ommit the line of the archived chat button

good idea!

**Comment by Jikstra** [comment]
Closing as core developer doesn't reply :P Please reopen if it still annoys you with an exact idea of the color in hex ^^ Küsse <3
