### ISSUE TITLE
cannot enlarge group-image

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1601]
the new enlarging-option of the contact-profile-image (the avatar) is great!

however, for groups, that have the same ui-control at the same place, this enlarging does not work - instead clicking on the image allows selection another image.

this is pretty irritating, for good ux, similar things should work similar :)

to solve this ux-glitch, maybe we could show the "enlarged image" for groups as well and then have two buttons "Edit group image" and "Delete group image" on the enlarged image. this way we could also get rid of the weird "red x" shown beside the group image.

or, maybe easier, ux-wise and programming-wise, just have a button "Edit group image" below the editable group-name (the button can have the same style as "Send message" in 1:1 profiles), clicking on the button, a menu pops up, allowing selection+deletion. also here, i would not have this "delete image" as a primary option)

**Comment by Simon-Laux** [comment]
why are you naming this ux-glitch?

**Comment by r10s** [comment]
naming things is hard :) how would you call it?

**Comment by Jikstra** [comment]
I agree that this is not an ui glitch, a ui glitch makes me think of something like this: https://www.hisour.com/de/glitch-art-21221/

No matter what, this is a very valid missing ui feature.
