### ISSUE TITLE
mouse pointer glitches

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1602]
in general, i dislike the flicking between the arrow-pointer and the _pointing-hand_, it is always a bit unclear, when which one is shown.

eg. in the settings-dialog, there is lots of switching every few pixels, EDIT: but also if a message spans more than one line

1. i suggest to use the arrow-pointer for _everything but links in messages_ - we are an application, not a website :)

2. in the title above the chat (the one with "groupname" and "3 members"), the lower few pixels of the subtitle show the arrow-pointer, if you go up a few pixels, the pointing-hand is shown.  
however, when targeting 1. , this should already be fixed.

3. the right area in the title above the chat is sometimes not clickable, a second click usually works

4. when opening the group-profile and closing the dialog with escape - the pointer is gone

**Comment by Simon-Laux** [comment]
I can't reproduce 3 and 4.

**Comment by r10s** [comment]
3. and 4. might be mac-specific then. might also be that they got fixed by 1. and 2. implicitly, so i would target them first.

**Comment by r10s** [comment]
to clarify 4: the pointer reappears on movement - but before, it is hidden, what is unexpected (and what does not appear in other dialogs using escape key, eg. "blocked contacts"

**Comment by Simon-Laux** [comment]
1 conflicts with https://github.com/deltachat/deltachat-desktop/issues/1587, anyways lets discuss such a big change/decision in an desktop av.

**Comment by Simon-Laux** [comment]
Just decided with @r10s that we ignore 4. for now, maybe we refile it as a separate issue in the future.
