### ISSUE TITLE
Mac builds are not notarized

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#1607]
![Screen Shot 2020-05-05 at 22 31 14](https://user-images.githubusercontent.com/34889164/81113218-29216000-8f20-11ea-864f-6cb0fcf288bd.png)

https://medium.com/@TwitterArchiveEraser/notarize-electron-apps-7a5f988406db

**Comment by Simon-Laux** [comment]
https://github.com/deltachat/deltachat-desktop/pull/1546 does this.
