### ISSUE TITLE
Login stalling at 60%

### ISSUE THREAD

**Issue by amkisko** [deltachat/deltachat-desktop#1612]
**Platform (linux/mac/windows):**
MacOS Catalina, LiLu firewall

**Delta Chat Desktop Version:**
1.2.0

**Expected behaviour:**
Successful login, chat list view shown OR error shown/reported

**Actual behavior:**
No errors, "Log in" button disabled, login view still shown.

**Steps to reproduce the problem:**
Install DeltaChat, start it, set valid credentials, press "Log in", allow internet access for DeltaChat app

**Screenshots:**
https://i.postimg.cc/jC61BPgJ/Screenshot-2020-05-07-at-11-27-14.png
https://i.postimg.cc/hfSYnv6Z/Screenshot-2020-05-07-at-11-27-41.png

<details>
<summary>- Logs:</summary>
<pre>
"2020-05-07T08:38:53.703Z"      "main/deltachat"        "WARNING"       "\nDeltaChat.<anonymous> (/Applications/DeltaChat.app/Contents/Resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:629:18),\n/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13" "ThreadId(19) src/job_thread.rs:90: connect+fetch failed: \"IMAP Connect without configured params\", reconnect & retry"
"2020-05-07T08:38:53.703Z"      "main/deltachat"        "WARNING"       "\nDeltaChat.<anonymous> (/Applications/DeltaChat.app/Contents/Resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:629:18),\n/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13" "ThreadId(19) src/job_thread.rs:93: connect+fetch failed: \"IMAP Connect without configured params\""
"2020-05-07T08:38:53.704Z"      "main/deltachat"        "WARNING"       "\nDeltaChat.<anonymous> (/Applications/DeltaChat.app/Contents/Resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:629:18),\n/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13" "ThreadId(17) src/job_thread.rs:90: connect+fetch failed: \"IMAP Connect without configured params\", reconnect & retry"
"2020-05-07T08:38:53.704Z"      "main/deltachat"        "WARNING"       "\nDeltaChat.<anonymous> (/Applications/DeltaChat.app/Contents/Resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:629:18),\n/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13" "ThreadId(21) src/job_thread.rs:90: connect+fetch failed: \"IMAP Connect without configured params\", reconnect & retry"
"2020-05-07T08:38:53.705Z"      "main/deltachat"        "WARNING"       "\nDeltaChat.<anonymous> (/Applications/DeltaChat.app/Contents/Resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:629:18),\n/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13" "ThreadId(17) src/job_thread.rs:93: connect+fetch failed: \"IMAP Connect without configured params\""
"2020-05-07T08:38:53.706Z"      "main/deltachat"        "WARNING"       "\nDeltaChat.<anonymous> (/Applications/DeltaChat.app/Contents/Resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:629:18),\n/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13" "ThreadId(21) src/job_thread.rs:93: connect+fetch failed: \"IMAP Connect without configured params\""
"2020-05-07T08:39:25.608Z"      "main/deltachat"        "WARNING"       "\nDeltaChat.<anonymous> (/Applications/DeltaChat.app/Contents/Resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:629:18),\n/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13" "ThreadId(17) src/configure/mod.rs:647: could not connect: SMTP failed to connect: Io(Custom { kind: TimedOut, error: \"future timed out\" })"
"2020-05-07T08:39:25.778Z"      "main/deltachat"        "WARNING"       "\nDeltaChat.<anonymous> (/Applications/DeltaChat.app/Contents/Resources/app.asar/tsc-dist/main/deltachat/controller.js:224:17),\nDeltaChat.emit (events.js:200:13),\nhandleEvent (/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:629:18),\n/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/deltachat-node/dist/deltachat.js:50:13" "ThreadId(17) src/imap/mod.rs:339: failed to close connection: Bad(\"code: None, info: Some(\\\"CLOSE not allowed now.\\\")\")"
"2020-05-07T08:39:25.794Z"      "main/deltachat/login"  "INFO"          "Logged out"
</pre>
</details>

**Comment by Jikstra** [comment]
Something is very weird with the login. We fixed a bug where for errors only the event name got shown, but this looks like something different.

**Comment by Jikstra** [comment]
@amkisko can you try out 1.3.4? It seemed to be a buggy core. https://download.delta.chat/desktop/v1.3.4/

If it doesn't appear on 1.3.4, please close this issue :)

**Comment by amkisko** [comment]
@Jikstra it works, thanks!
