### ISSUE TITLE
Pass in translate function in props to components instead of using global

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#162]
There's some code here and there doing e.g. `const tx = window.translate`, which relies on `.translate` being set properly before usage. If we pass in the translate function to components as a property we can ensure it's always valid.

**Comment by karissa** [comment]
this would mean that each component would have a bunch of objects in the dom -- every prop is actaully transferred to the dom. not sure how this would affect performance and it then makes it hard to debug your code when looking into the HTML inspector. 
`window.translate` should always be set, have you encountered a case in which it isnt?

**Comment by ralphtheninja** [comment]
> this would mean that each component would have a bunch of objects in the dom -- every prop is actaully transferred to the dom. not sure how this would affect performance and it then makes it hard to debug your code when looking into the HTML inspector.

Oh, I didn't know this.



> `window.translate` should always be set, have you encountered a case in which it isnt?

Yes. But don't remember where I had the problem.
