### ISSUE TITLE
Some description labels do not change to selected language unless Delta Chat closed and executed again

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#1637]
- Platform (linux/mac/windows):
Windows 8.1 Pro.

- Delta Chat Desktop Version:
1.3.3-1.10.0.

- Expected behavior:
Delta Chat translates all English description labels to the previously selected language.

- Actual behavior:
Delta Chat does not translate all English description labels to the previously selected language.

- Step to reproduce the problem:
-- Select a different language than English (e.g. "Deutsch" for German).

- Screenshot:
-- This is the result when "Deutsch" (German) is selected:
![grafik](https://user-images.githubusercontent.com/51095533/81869159-d70db980-9573-11ea-8bb6-befd73aba723.png)

- Remark:
-- After Delta Chat is closed and executed again, the description labels show the texts in the previously selected language.

**Comment by Simon-Laux** [comment]
At first glance I can't reproduce this on linux, maybe its an issue that appear only on windows?

**Comment by gerryfrancis** [comment]
@Simon-Laux That is strange. Unfortunately I cannot test on Linux. As you can see at the screenshot, the only description label that is translated in German is "Suchen".

**Comment by Simon-Laux** [comment]
Did you find anything interesting in the logfile?

**Comment by gerryfrancis** [comment]
@Simon-Laux No, unfortunately not, just this:

```
"2020-05-14T11:06:20.410Z"	"main/menu"	"INFO"		"rebuilding menu with locale de"
"2020-05-14T11:06:21.373Z"	"main/state"	"INFO"		"Saving state to C:\\Users\\PC_USER\\AppData\\Local\\DeltaChat\\config.json"
```

**Comment by Simon-Laux** [comment]
> After Delta Chat is closed and executed again, the description labels show the texts in the previously selected language.

So german just doesn't work for you at all or is it fixed after a restart?

**Comment by gerryfrancis** [comment]
@Simon-Laux It is fixed after a restart.

**Comment by Simon-Laux** [comment]
Okey, lets debug this then.
1. start deltachat from the commandline (powershell or conhost/cmd.exe) with the argument `-- debug`
2. This should open deltachat and the developer console and log all debug messages.
3. Change the language and look for `extras.getLocaleData` in the dev console.
4. Save the message varible to the global scope:
![Peek 2020-05-14 13-22](https://user-images.githubusercontent.com/18725968/81928952-65bb1e80-95e6-11ea-9056-a5bb4e91484d.gif)
5. after the message variable is copied to temp0 run
```js
Object.keys(temp1).length
```
in the dev-console. This counts how many language strings were sent to the fronted.
What does this number say?

**Comment by gerryfrancis** [comment]
@Simon-Laux Maybe I am stupid, but I cannot get the console by running `DeltaChat.exe -- debug` . :( (I am testing with the final version 1.3.3, has the console been withdrawn from it?)

**Comment by Jikstra** [comment]
It's:
1. `cd C:\Program Files\DeltaChat` (not sure about the exact path)
2. `.\DeltaChat.exe -- --debug` or `.\DeltaChat.exe --debug` currently dont have a windows system around but one of them should work

**Comment by gerryfrancis** [comment]
> cd C:\Program Files\DeltaChat (not sure about the exact path)

@Jikstra Quite strange, on my Windows machine Delta Chat is installed in `C:\Users\PC_USER\AppData\Local\Programs\deltachat-desktop` . So this app is limited to the current user who installed it. (However, I do not know if this is intended, but that is a different story.)

> `.\DeltaChat.exe -- --debug`

@Jikstra Hooray, you have nailed it! :)

> What does this number say?

@Simon-Laux The number says `595` .

**Comment by Simon-Laux** [comment]
that's the right number so the problem must be somewhere else...

**Comment by gerryfrancis** [comment]
I have found out that the texts in the global three-dot menu (on the right) are not affected and changed to the previously selected language. This would limit the issue to the texts beyond the top menu bar.

**Comment by Simon-Laux** [comment]
The the top menu bar is controlled by the main process, which also sends the language data to the front-end process. The thing you checked was whether the front-end process received this data. So we can say the problem most likely lies in applying the new data.

**Comment by gerryfrancis** [comment]
@Simon-Laux To me it looks like the process of refreshing the text labels is stopped after the first one, which is "Suchen". Maybe that helps.

**Comment by gerryfrancis** [comment]
Thanks, I will test the fix in the upcoming release! :+1:

**Comment by gerryfrancis** [comment]
@Simon-Laux I am reopening this, because it seems that not all labels have been caught:

![grafik](https://user-images.githubusercontent.com/51095533/87660752-dce46e80-c75f-11ea-9ed5-6c12aca78c03.png)

![grafik](https://user-images.githubusercontent.com/51095533/87661039-43698c80-c760-11ea-973c-c440469ef258.png)

(Started in English and switched to German.)

**Comment by Jikstra** [comment]
@gerryfrancis you need to reselect a chat, then they should go away. Those are the strings we need to put into the core and the core gives back to us. We would need to refetch & rerender everything so that they get replaced with the translated strings. I think it's okay for now.

**Comment by gerryfrancis** [comment]
> you need to reselect a chat, then they should go away.

@Jikstra After changing the language from English to German, I reselected "Device messages" and "Saved messages", but they stay as they are in the chatlist. Do you really think this is a core issue?

**Comment by Simon-Laux** [comment]
as @Jikstra said those strings come from the core. also those chats are mostly hidden bellow in the chatlist so its ok for now.
There are more important things to do right now than fixing this mini cosmetic bug that only appears when the user changes their language.

**Comment by gerryfrancis** [comment]
@Simon-Laux As long as Delta Chat runs the system language (which did not work out in the past, but now it does), it is OK. When there is enough time left, we can fix this one, of course.

**Comment by Simon-Laux** [comment]
Let's put it into project resurrection then.
