### ISSUE TITLE
Switch to left aligned chat messages

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#164]
Currently the chat messages are left & right aligned which is hard to read in my opinion plus i prefer the telegram way of aligning all messages to the left. 
![image](https://user-images.githubusercontent.com/34889164/46974588-be51cf00-d0c4-11e8-9215-dd0b64b175e9.png)

@karissa @hpk42 @ralphtheninja  @r10s opinions?

**Comment by ralphtheninja** [comment]
I have no opinion. Aligning left is fine. Unless there is some "delta style" we want to maintain across all applications.

**Comment by hpk42** [comment]
On desktop windows are often quite wide.  now at least we have the contact list always there on the left. 
Pending other ideas i think left-aligning is better readable -- maybe the x-platform similarity in style 
can more be done in how the message-boxes are colored etc.  Just my 2ec.

**Comment by r10s** [comment]
i would definitely leave the "own" messages right aligned. it's far more easier to differ between own/other messages this way. 

it windows get too wide on desktop, it may make sense to allow only a maximal width, so that bubbles of typical size overlap a bit.

**Comment by hpk42** [comment]
fine with me. closing it for you :)
