### ISSUE TITLE
The URI of the invitation QRCode is shown cut in half.

### ISSUE THREAD

**Issue by AndreazLattmann** [deltachat/deltachat-desktop#1644]
- Platform (linux/mac/windows):
Windows 7
- Delta Chat Desktop Version:
1.3.3
- Expected behavior:
When I open the Invitation QR Code window, I would like to see the complete URI.
- Actual behavior:
The URI is seen at half.
- Steps to reproduce the problem:
Open the invitation window.
- Screenshots:
![image](https://user-images.githubusercontent.com/63752768/82085008-d98b2300-96db-11ea-82d4-38250bc74bb5.png)
- Logs:

**Comment by AndreazLattmann** [comment]
Excuse me, I found the reason why you see the URI halfway: it is the zoom factor. If imposed at 1.4x Hunge you see in half, if you imposed 1.2x large you can see me at 1/4. I hope this can facilitate the correction of the bug.

**Comment by AndreazLattmann** [comment]
I discovered why the uri of the qrcode can be seen halfway. It is due to the Factory zoom. I had tried to set 1.4x Hunge to test it and that's how I discovered the bug. If you set the normal zoom the problem does not occur. 😅

**Comment by Simon-Laux** [comment]
The interface doesn't have this field anymore, so I'll close this.
