### ISSUE TITLE
Flathub package "Show encryption info" is broken

### ISSUE THREAD

**Issue by B-X-M** [deltachat/deltachat-desktop#1648]
- Platform (linux/mac/windows): Linux, Flathub package
- Delta Chat Desktop Version: 1.32
- Expected behavior: Show encryption info of a contact
- Actual behavior: White screen, app has to be restarted to work again
- Steps to reproduce the problem: Right-click on a contact, choose "show encryption info"

The show encryption info function is broken on linux, at least in the flatpak. Provides only a blank whihte scree with no way to restore app functionality.

**Comment by Jikstra** [comment]
This is fixed in 1.3.3. Not sure if it's already deployed to flathub.
https://github.com/deltachat/deltachat-desktop/compare/v1.3.2...v1.3.3
