### ISSUE TITLE
Feature request: automatic loading avatara from gravatar, etc

### ISSUE THREAD

**Issue by the-Arioch** [deltachat/deltachat-desktop#1660]
You try to load most possible setting just by providing e-mail.

However you do not load perosn name and avatara, at least not on Win32 version lacking OAuth

I don't know if there is a practical non-OAuth way to load user name.
But at least for a picture there is a long standing de factor standard - gravatar.

And maybe others less known gravatar-like services too.

So i wish you fetch the user's picture automatically as soon as e-mail is authenticated.

**Comment by Jikstra** [comment]
I don't know how gravatar works, but from what i know is that we don't support it on any platform. Also not sure if we want to integrate a centralized service. I would propose moving further discussion about this feature request to the support forum, we try to keep the github issues a place for bugs :)

**Comment by the-Arioch** [comment]
Since XFace MIME header got all but forgotten (did you even heard?) then to fetch an avatara only two  options are left - make custom non-RFC provider-specific plugins (one for Gmail, one for Yandex, etc) and to use some de-facto standard as a fall-back

**Comment by Simon-Laux** [comment]
read first (the issue that led to our current implementation): https://github.com/deltachat/deltachat-core-rust/issues/807

related (send avatar as vcard): https://github.com/deltachat/deltachat-core-rust/issues/1256
