### ISSUE TITLE
Login button is getting disabled when an error happens. Sometimes this is not wanted.

### ISSUE THREAD

**Issue by the-Arioch** [deltachat/deltachat-desktop#1661]
I don't know why, i suspect our VPN setting, but the initial login failed on me. I suspect the IMAP/SSL 993 port was blocked.

So, when i tried to log int, into different e-mail services, i got a looong waiting, the gauge run to about 60%, then the i/o error was displayed.

The bug: after the error was dismissed the Login button remained disabled. There was nothing normal i could to to try logging in again, with the same or altered settings.

Chrome devtools probably would have worked, at least on GUI part if not on middleware, but that is hardly a normal UX

**Comment by Jikstra** [comment]
I notices some weird things with the login yesterday too, on which version are you? 

Thanks for reporting :)

**Comment by Jikstra** [comment]
Can you try out 1.3.4? Fixed some bugs related to the login.
https://download.delta.chat/desktop/v1.3.4/

If it doesn't appear on 1.3.4, please close this issue :)

**Comment by the-Arioch** [comment]
Going into unreleased bleeding edge.... uh-oh....
I'll try later.

BTW, can there be some explicit indicator where mail server IS connected or not right now ?

Traditional mailer has a special "mail transfer" dialog that logs errors and pops-up to the user, if thos happenned.

Traditional chats (ICQ, Skype, etc) have a "current mode" icon (free/busy/AFK, etc), which also has "connecting attempt" and "disconnected" statuses.

DeltaChat seems to lack both, so it seems that only a fleeting and after long timeout error message can convey the current state to user.
If some other perosn closed the error shade - then there is no more indication chat app gone offline.

**Comment by the-Arioch** [comment]
It seems i would have to delete all the user profile to really check it...
Otherwise i can not trigger DC to re-launch the welcome screen on me.

Meanwhile, in 1.3.4
I did not delete the first profile, but i tried to add the second one.
And the same bug there.
After IMAP connection fails - the Login button remains disabled.

I wonder if some token ARC-object can be used to automatically enabled-disable the button.
As long as the object is freed (exiting the conneciton attempt subroutine no matter properly or by exception) - it automaticalyl revert "disabled state from the button. I did not program in JS or Chrome, so maybe a stupid question.

I repeat, the IMAP/SSL port 993 is blocked on this internet setup. This condition is not in my power but you can reproduce it on your box), but it reveals the bug in DC.

**Comment by Jikstra** [comment]
>  after long timeout error message can convey the current state to user.

It seems like the core library isn't giving us this information and probably doesn't know it itself. For sure it knows if it's connected or not, but going "offline" takes quite some time. Why and where do you need it? In the 1.4 branch we just implemented a getNetworkStatus method which would allow us to show an Connected/Disconnected thingy in the settings as telegram does it? Would that help? What 1.4 also will do, is show an offline toast as soon as it notices (after the timeout) that it's offline.

It will feel like this:
https://user-images.githubusercontent.com/18725968/81890943-7ac48d00-95a7-11ea-98ca-2a87c9a8e155.png

**Comment by the-Arioch** [comment]
The screenshot looks good. Especially if that popu-up can be clicked to trigger immediate reconnect attempt. Of course just looking at the static picture :-)

I think it does not get re-enabled aft i "change the input", i especially tried it, at very least with initial reporting (1.2.0 and empty profile)

And yes, that is not good ux because the error may be unrelated to user input, like a problem with general internet connecticity, etc

> You can go to the three dot menu -> Switch Account and add another account

That was exactyly what i did 

>> Meanwhile, in 1.3.4  I did not delete the first e-mail profile, but i tried to add the second one.

But that window looked DIFFERENTLY from my first DC launch. So i suppose that is either a different program object or at least loaded with different properties. So is not a total repro of my 1st experience.

**Comment by Jikstra** [comment]
> I think it does not get re-enabled aft i "change the input", i especially tried it, at very least with initial reporting (1.2.0 and empty profile)

But this should be the behaviour in 1.3.4

> But that window looked DIFFERENTLY from my first DC launch. So i suppose that is either a different program object or at least loaded with different properties. So is not a total repro of my 1st experience.

A lot of things are currently changing, so quite possible that something there has changed :D

**Comment by the-Arioch** [comment]
Is there some launching option, like command line parameter, to run the program with non-default profile? something like `DeltaChat.exe -p tempNameForTest` ?

would be handy to check some erratic behavior, whether it was triggered by user customizations (settings, plugins, messages history and what not) or is repro on clean vanilla profile too.

**Comment by the-Arioch** [comment]
Oh, and BTW, keep forgetting it. 
The "Switch account" item of the menu is not localized in Russian UI

**Comment by the-Arioch** [comment]
Ok, at least in 1.3.4 and if there is already one account existing, then in the "add 2nd account" window the Login button gets re-enabled.

But what i noticed made me very surprised.

There is a "Cancel" button, invisible by default.
And the "Cancel" button is getting shows/hidden correctly!

Why not making a separate switching function that fix both button at once?
It seems to be almost a binary option here, either Login disabled Cancel displayed, or Login enabled Cancel hidden.

The single exception is when user did not keyed in any valid e-mail address at all.
However, if Cancel buton goes from visible to invisible it seems ot be a safe point to re-enable Login as well

**Comment by Jikstra** [comment]
Good idea. I think we tried to be too smart here, forcing the user to change invalid input if an error occured. But that's too smart. The whole login process needs some overhault for various reasons and we will tackle this all together. Thanks for your feedback!

**Comment by the-Arioch** [comment]
One nerdy wish is being able to copy the error message text as raw as it can get, if a user will get to contact his support stuff - he would need something better than mumbling kinda-correct retelling from something he saw for a minute on the screen hour ago :-D

In particular, that means if there is some data too technical to be even displayed - it still better be copied. Including IMAP settings, etc.

To go over the board :-) in one my program the fatal error message is not only displayed but also gets persistently stored into Windows EventLog. Granted, i have the luxury to ignore non-Windows platforms and it is only for early and fatal crashes.

**Comment by Jikstra** [comment]
Haha you're good :D Another thing that i hate in other programs too, not being able to copy the error message. I have to say i don't like those "error toasts". They are a huge hack be able to collect all errors/warnings/successes at one place and display them, no matter what.

My idea of the login screen is following:
If you click login, you get a small dialog popup with a spinner/progress bar. If an error happens, it will show it in that dialog, or at least integrated with the existing ui and not as an unrelated toast thingy.

**Comment by the-Arioch** [comment]
And the error message has to have a copy button or something. Though may users got so trained on lacking copying that they screenshot everything without an second thought.

Just think, what relevant info would you like user to collect when reporting this or that kind of error to you (oir to forum, etc) - and make the program just add it to the copied text. The simple example - IP addresses of the box, try to make a regular non techie user find them all, by a phone line, good luck. But the program could enumerate them and attach to the error text with accuracy. Also, OS error codes and all that enrdy stuff that can at least be googled for :-)

**Comment by the-Arioch** [comment]
> a huge hack be able to collect all errors/warnings/successes at one place

IOW, the logging framework :-)

This is not merely a hack but a useful infrastructure too. Think about persistently storing them errors, or automatically sending them over network. The very ability One True Function to oversee all the errors is actually really useful per se. Don't lose it just because of UI revamp :-)

**Comment by Jikstra** [comment]
The logging happens anyways, talking about pure ui things here. You can find the logs in your account folder (or go to View -> Developers -> Open the log folder)

**Comment by the-Arioch** [comment]
I also noticed the folder for new mailbox is getting created even if the error happenned and the profile did not get created afterall.

While as of now SQLite DB seems but empty and did not have password, still it feels liek a potential avenue for a leak, at least after some random later change in the program.

The situation when GUI says i have a single account but file system has three of them (one outside *accounts* subfolder and with `616e6e6f796e696d6f7573654079612e7275` name, so maybe a remnant from DC 1.2.0) feels inconsistent.

Like, a user leases/sells his computer. He opens DC and deletes the accounts one can see. Then he is sure everything got deleted. But it was not so.

I know there are more reliable ways to wipe one's data, just trying thinking about less experienced users.

Since SQLite can have in-memory databases i wonder if persisting it onto the disk can be delayed until after succesful connect.

**Comment by Simon-Laux** [comment]
> I also noticed the folder for new mailbox is getting created even if the error happenned and the profile did not get created afterall.

Very valid point... we should at least delete them again if it didn't work.

> Since SQLite can have in-memory databases i wonder if persisting it onto the disk can be delayed until after succesful connect.

Great idea, but lets discuss it rather on the [forum](https://support.delta.chat/) before it gets lost.
