### ISSUE TITLE
AppImage No works in Mageia 7 Plasma

### ISSUE THREAD

**Issue by Joselpdj** [deltachat/deltachat-desktop#1669]
- Platform (linux/mac/windows): Mageia 7 Plasma KDE
- Delta Chat Desktop Version: 1.3.2
- Expected behavior: Appimage should works in Mageia 7, the app boot but no works.
- Actual behavior: The app boot but no works.
- Steps to reproduce the problem: Download the appimage and run on Mageia 7 Plasma
- Screenshots:
- Logs: Please go to https://bugs.mageia.org/show_bug.cgi?id=26353 for more information of this bug

**Comment by Jikstra** [comment]
First, can you update to 1.3.4 ?
https://download.delta.chat/desktop/v1.3.4/

Second, can you start it like this: "./DeltaChat-1.3.4.AppImage -- --debug" and post the log here? The only log i see on mageia is from 1.1.1 which is quite dated.

**Comment by Joselpdj** [comment]
Hi! Whit the new version neither works. I put the konsole output here:

[Bugdeltachat.txt](https://github.com/deltachat/deltachat-desktop/files/4651435/Bugdeltachat.txt)

**Comment by Simon-Laux** [comment]
> The app boot but no works.

can you specify what exactly doesn't work?

**Comment by Joselpdj** [comment]
The application starts but after putting the email and password, it closes and does nothing, does not reopen.

I've put the konsole output in the comment above.

**Comment by Simon-Laux** [comment]
Ah it crashes with an segfault:
```
19.8s [i]core/event: DC_EVENT_INFO  ThreadId(14) src/imap/mod.rs:315: IMAP unsetup_handle step 3 (clearing config).
Violación de segmento (`core' generado)
[jose@localhost Descargas]$ 
```

**Comment by Joselpdj** [comment]
So, It is a deltachat bug? or it is a Mageia bug.

**Comment by Simon-Laux** [comment]
Likely it's a delta-chat bug, but if it only occurs on Mageia it could be a bug there as well. I'll download `Mageia 7.1 Live Plasma 64bit` and try it in a virtual machine, let's see if I can reproduce your issue.

**Comment by Simon-Laux** [comment]
So the appimage works perfectly on my system, but in the Mageia VM it segfaults with the same error that you have.

**Comment by Jikstra** [comment]
@Simon-Laux can you dive in where it segfaults? Does it produce a core dump or anything?

**Comment by the-Arioch** [comment]
The crash seems to be in the Rust - is Appmage bundling their own Rust libs or using host OS ones?

**Comment by Jikstra** [comment]
rust is getting compiled to a binary, so nothing needs to get shipped  besides the binary. I guess the crash happens on the node/electron side. Probably a different glibc or whatever.

**Comment by Joselpdj** [comment]
Hi, in mageia, the glibc version is 2.29-20.

**Comment by Joselpdj** [comment]
Hello, any news about this?

**Comment by Joselpdj** [comment]
Hello, any news about this?

**Comment by Joselpdj** [comment]
The latest version 1.3.4 Appimage still doesn't work in Mageia 7.1

**Comment by Jikstra** [comment]
The latest version got released before this issue. The last deltachat-node release i built on ubuntu 16.04 so it should have an older glibc. Probably this helps, probably not.

**Comment by Jikstra** [comment]
You can try out this preview: https://download.delta.chat/desktop/preview/deltachat-desktop-1734.AppImage

https://github.com/deltachat/deltachat-desktop/pull/1734

**Comment by Joselpdj** [comment]
The same bug, no works.

**Comment by Jikstra** [comment]
A segmentation fault, that's weird. Can you execute it like this: `DEBUG=* ./deltachat-desktop-1734.AppImage -- --debug` and post the logs?

**Comment by Joselpdj** [comment]
Running the command, I add the output
[Bugdeltachat.txt](https://github.com/deltachat/deltachat-desktop/files/4798400/Bugdeltachat.txt)

**Comment by Jikstra** [comment]
Hmm weird. Can you try to build deltachat-desktop manually and see if it happens there too? This doesn't really look like a glibc issue as you're able to use some core functionality.
can you run `gdb --args './deltachat-desktop-1734.AppImage -- --debug'` and enter start, later backtrace to get the c/rust code where the segmentation fault happens?

**Comment by Joselpdj** [comment]
[jose@localhost Descargas]$ gdb --args './deltachat-desktop-1734.AppImage -- --debug
> start
> backtrace
> 

it doesn't do anything, it stays there

**Comment by Joselpdj** [comment]
I have tried the latest version 1.4.3 and it keeps giving the same error:

Violación de segmento (`core' generado)

**Comment by Simon-Laux** [comment]
The appimage works fine on Mageia 8 Plasma, login and writing messages works fine there. Does this solve the issue for you or do you still need it to work on Mageia 7?

**Comment by Joselpdj** [comment]
No, I have updated to Mageia 8 and work fine. Mageia 7 is EOL from 31-05.

We can close this bug.

Very thanks and greetings!!
