### ISSUE TITLE
For newly added contact, sync keys between devices... FAQ/HowTo?

### ISSUE THREAD

**Issue by TheOtherDoctor** [deltachat/deltachat-desktop#1679]
- Platform (linux/mac/windows): deltachat-desktop on windows in coop with android
- Delta Chat Desktop Version: 1.2.0
- Expected behavior: When I add a contact on one device/instance (in this case, DC desktop), the autocrypt is negotiated and when I then open DC on another device, chatting with that newly added contact should be able to continue seamlessly, as it works for contacts taken from an import.
- Actual behavior: On the 2nd device, the contact added on the 1st device does not show up. When I add it from my adressbook, an unconnected (broken) channel gets set up, not showing the previously sent messages, and all messages sent in the new channel do end up in some dark void, never reaching the receiver.
- Steps to reproduce the problem: create a new contact on one device, try to reach same contact on 2nd device.
- Screenshots: -
- Logs: -

As far as I know, this can be overcome by reinstalling DC on any "2nd" device (according to  from a backup taken on "1st" device... just cannot believe I have to redo this after each added contact?!? I have about 4 DC desktop and 2 DC Android on same account - the ability to have the same simple chat on several devices is for me a great feature of DC. If the contact re-sync cannot be handled easy this is a risk to become quite a show stopper...

Maybe a howto on how to fulfill this expectation is already covered - I didn't find it. This issue might be primarily a topic to be added into the FAQ - either as a usable solution or a note on how to deal with this; I looked through FAQ and forum but did not find any.

In case this is actually a missing feature, I am also unsure if this is a core issue or related only to frontend(s), thus I just put it into desktop as I encountered the effect there. I guess it is also relevant on other platforms?

**Comment by Simon-Laux** [comment]
Did you send an initial message the content in question from the first device?

**Comment by Jikstra** [comment]
How did you setup your devices? Did you "just" login on all the devices with the same email credentials? Because this will create a new key for each device and therefore chats wont get synced. What you should do is, if you set up a new device, export a backup from the "old" device, import that in the new device. This will give you the same key, a history of all chats/files/contacts... and both instances should keep in sync from that point on.

**Comment by TheOtherDoctor** [comment]
I am aware about the import-from-backup, and that's how I intially setup each app/device. This "broken contact channel on the 2nd device" is not a "new device" issue IMHO - I add a new contact on device A, exchange some messages with the new contact and autocrypt does its job; but device B does not know/show that contact, and I found no practicable way (other than resetting apps on all devices via import-from-backup) in order to propagate the contact/keypair to device B.

I just tried the naive-user approach of adding the contact from adress book in the android app, which fails (which is no surprise, as far as I understand the usual autocrypt flow).

To me this felt like something which needs some work at least in the documentation, or even some friendly function, e.g. like piping new contacts autocrypt messages through the "saved messages". 

I understand your comments that it's probably not a missing feature, so I can try to bring this over to the forum and just leave the solution note here to close.

**Comment by Jikstra** [comment]
Normally this should work. Do you verify the other side (with scanning the qr code) or are you just doing a normal autocrypt exchange? Can you make sure that watching the DeltaChat folder is activated in the settings on all devices? And what happens if you send a message to your self (Saved Messages). Can you encrypt it/receive it on all other devices?

**Comment by gerryfrancis** [comment]
@TheOtherDoctor Please try again with with the current Desktop version of Delta Chat, 1.3.4.

**Comment by Simon-Laux** [comment]
please reopen if this issue is still present in the current dc version (1.13.1 desktop, 1.12.5 android)
