### ISSUE TITLE
preserve order of chats as returned from core

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#168]
Currently the chatlist applies some sort of ordering (appears random to me). 
As i am trying to use the app with a lot of chats that's a bummer.
the ``dc_get_chatlist`` function's returns chats ordered by sending time (mostly), let's just make sure to not re-order it.

**Comment by ralphtheninja** [comment]
https://github.com/deltachat/deltachat-desktop/commit/d0d43a18345b0e0dba1946f6007145aaf9c9d264
