### ISSUE TITLE
Combined picture+annotation type message - missing feature? unclear workflow?

### ISSUE THREAD

**Issue by TheOtherDoctor** [deltachat/deltachat-desktop#1680]
- Platform (linux/mac/windows): windows 10
- Delta Chat Desktop Version: 1.2.0 & 1.3.4
- Expected behavior: Being able to create similar picture-with-note-below messages like the android DC app.
- Actual behavior: I fail to achieve this - however I add the attachment/picture, the text and pic are always in two separate boxes.
- Steps to reproduce the problem: try to add a picture with (embedded) annotation below.
- Screenshots: -
- Logs: - 

Having messages composed of a picture and an annotation right below, in one surounding context frame, it is for my perception much better than having them separated - thus I favor this way. 
I simply fail to get that done in the desktop app. :-(

Maybe my intuition is just twisted, and I'd just need a hint in the help or the UI... or is this actually a missing feature?

**Comment by Jikstra** [comment]
It's a missing feature :/
