### ISSUE TITLE
On high screens the loading of old messages and scrolling doesn't work properly

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-desktop#1684]
DC 1.3.4 - Linux (Debian, MATE)
Screen size 1920 x 1080

When I start DC (opens in fullscreen) and open my chats I see some of the more recent messages but none of the older ones. I cannot scroll up to see them.

If I then make the window smaller (about half the size of my screen) the scrollbar appears and I can scroll up to see the older messages.

After that I can go back to fullscreen and the program works as expected not only for the chat where I provoked the loading of older messages but also for other chats.

**Comment by angelo-fuchs** [comment]
After a switch account the problem reappears and the same workaround needs to be applied again.

**Comment by Simon-Laux** [comment]
@angelo-fuchs can you check if this is fixed in the new test version?
(remember to backup your accounts or try it on another user, because this version might not be downgradable)

https://support.delta.chat/t/help-testing-the-upcoming-1-27-x-release/2042

**Comment by Simon-Laux** [comment]
closing, please reopen or make a new issue if it apprears again
