### ISSUE TITLE
dc_event_network_error upon login

### ISSUE THREAD

**Issue by arthurlogilab** [deltachat/deltachat-desktop#1699]
- Operating System (Linux/Mac/Windows/iOS/Android): Ubuntu bionic
- Delta Chat Version: 1.3.2  

```
{
    "arch": "64",
    "deltachat_core_version": "v1.32.0",
    "sqlite_version": "3.30.1"
}
```

- Expected behavior: Be able to login 
- Actual behavior: Login fails with red bubble indicating "dc_event_network_error" 
- Steps to reproduce the problem: we have an imap and smtp server behind a VPN, the server is a cyrus server with LDAP auth
- Screenshots:

![Screenshot from 2020-06-04 13-09-18](https://user-images.githubusercontent.com/445200/83749991-e492fc80-a664-11ea-8a02-a99744eac47b.png)

- Logs:

**Comment by arthurlogilab** [comment]
```
 flatpak info chat.delta.desktop/x86_64/stable                       
Ref: app/chat.delta.desktop/x86_64/stable
ID: chat.delta.desktop
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2020-05-11 21:38:28 +0000
Subject: updated to 1.3.2 (21b82ab1)
Commit: 7f2c9d62e08d8a97865df546e22be1990eb23b44a11f061a0a2e4a84208a4892
Parent: 487cc5f9229c8580eb549884c0f66a9249fcc7fba5eccb73bb0ea7a840b1289c
Location: /var/lib/flatpak/app/chat.delta.desktop/x86_64/stable/7f2c9d62e08d8a97865df546e22be1990eb23b44a11f061a0a2e4a84208a4892
Installed size: 615,5 MB
Runtime: org.freedesktop.Platform/x86_64/19.08
Sdk: org.freedesktop.Sdk/x86_64/19.08
```
Any reason why I'm not getting version 1.3.4 ? should I switch to the .deb version ?

**Comment by Simon-Laux** [comment]
flathub is community maintained.
pin @muelli

**Comment by muelli** [comment]
> Any reason why I'm not getting version 1.3.4 ?

yeah, somebody needs to update the package on flathub.
It's not really hard, just takes some time. It's quite a mechanical job.
The procedure should be described [here](https://github.com/flathub/chat.delta.desktop/blob/99d9bab533c1c0324a5a62b334cc7d94469c0882/README.md).

**Comment by arthurlogilab** [comment]
no problem, I fully understand. Indeed upgrading to the 1.3.4 version with debian package I get a more explicit error (might post another issue if I can't solve it). 

Maybe https://delta.chat/en/download should display which method is recommended over another. I assumed you recommended flatpack since it was first on the list.

**Comment by muelli** [comment]
From that list, the Flatpak version is the only one, AFAICT, that gets you updates.

**Comment by Jikstra** [comment]
Should be fixed on latest master and in the next version :)
