### ISSUE TITLE
Warning: Each child in an array or iterator should have a unique "key" prop

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#170]
![screenshot from 2018-10-17 15-33-17](https://user-images.githubusercontent.com/308049/47089927-18b47200-d222-11e8-9689-138f015136f2.png)

Probably minor issue, just annoying to see it in the logs.

**Comment by Jikstra** [comment]
Can take this into account when i write better wrapping components as discussed in irc. It's simply just a `<ComponentName key={id} .../>`

**Comment by ralphtheninja** [comment]
Speaking of, I'll create an issue for the wrappers where we can track what has been wrapped and what needs to be wrapped
