### ISSUE TITLE
Error message on login screen starts with ","

### ISSUE THREAD

**Issue by arthurlogilab** [deltachat/deltachat-desktop#1702]
- Operating System (Linux/Mac/Windows/iOS/Android): Ubuntu Bionic
- Delta Chat Version: 1.3.4 (deb package)
- Expected behavior: Error message to be easily readable
- Actual behavior: The sentence starts with a ","
- Steps to reproduce the problem:
- Screenshots:

![Screenshot from 2020-06-05 09-12-15](https://user-images.githubusercontent.com/445200/83847616-dac4d400-a70c-11ea-90a4-049dff731ed4.png)

- Logs:

**Comment by gerryfrancis** [comment]
@arthurlogilab Confirmed, but the message itself is really weird, too. I think it should be addressed as a new issue.

**Comment by arthurlogilab** [comment]
@gerryfrancis see https://github.com/deltachat/deltachat-core-rust/issues/1556
