### ISSUE TITLE
DeltaChat's window size on Windows increases with each launch

### ISSUE THREAD

**Issue by whalehub** [deltachat/deltachat-desktop#1705]
- **Operating System (Linux/Mac/Windows/iOS/Android):** Windows
- **Delta Chat Version:** 1.3.4
- **Expected behavior:** DeltaChat remembers its last window size across launches.
- **Actual behavior:** DeltaChat's window size increases each time it is started.
- **Steps to reproduce the problem:**

1. Launch DeltaChat.
2. Resize its window.
3. Close DeltaChat.
4. Repeat steps 1 and 3 to see the window size increase with each launch.

- **Screenshots:**

**DeltaChat window (1st launch)**

![DeltaChat_2020-06-05_14-57-02](https://user-images.githubusercontent.com/44198148/83878986-42931300-a73d-11ea-8d21-ec9922732ee6.png)

**DeltaChat window (5th launch)**

![DeltaChat_2020-06-05_14-57-19](https://user-images.githubusercontent.com/44198148/83878995-44f56d00-a73d-11ea-8494-dadc9c8dea96.png)

**DeltaChat window (10th launch)**

![DeltaChat_2020-06-05_14-57-41](https://user-images.githubusercontent.com/44198148/83879003-4757c700-a73d-11ea-82b6-b264eb5f2f92.png)

- **Logs:** N/A

**Comment by Simon-Laux** [comment]
looks like this only affects height. maybe its not saved correctly

**Comment by whalehub** [comment]
@Simon-Laux I thought that at first as well, but these are the image dimensions:

**1st launch:** 1009x750
**5th launch:** 1073x986
**10th launch:** 1153x1281

So the window's width also increases with each launch, just at a slower rate than the height.

**Comment by Simon-Laux** [comment]
Found the issue and fixed it, will come shipped in <=1.4

**Comment by whalehub** [comment]
@Simon-Laux Thanks for the quick fix!
