### ISSUE TITLE
qr-code scan permission on mac is not always asked

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1709]
for me, on mac, the latest stable release stops scanning qr-codes, no error or so, it is again in the state of https://github.com/deltachat/deltachat-desktop/issues/1586 - where it was worked before.

using the master in another installation with `npm run dev` (@Simon-Laux learnt me that :), shows a question about the permission and the qr-code-scanning works, at least for the moment.

maybe there is sth. wrong with the permission handling? sth. as if the system wants re-confirmation after some time and we miss that?

**Comment by Simon-Laux** [comment]
please reopen this issue if it still occurs
