### ISSUE TITLE
UI regressions

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#1713]
- [x] the default avatar is different in group edit then in navbar/chatlist for unverified groups without an avatar
![Screenshot_20200612_184515](https://user-images.githubusercontent.com/34889164/84525967-cb312680-acdc-11ea-8183-f05a5f8d38bb.png)

- [x] the edit group image icon has a weird violet (besides this i like it :D)
- [x] the chatlist seperator (Contacts/Chats/Messages) looks different from other seperators that we have
- [x] clicking on navbar for opening viewprofile editgroup

**Comment by Simon-Laux** [comment]
note: For the avatar we don't have the color when creating a chat. it is dependent on the first group member.

**Comment by Jikstra** [comment]
It's not about creating a group, it's editing an existing & verified group
