### ISSUE TITLE
Addr still sometimes missing

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#1740]
```
/home/kerle/Coding/deltachat-desktop/tsc-dist/main/logins.js:67:17,
fulfilled (/home/kerle/Coding/deltachat-desktop/tsc-dist/main/logins.js:5:58)
2.6s [E]main/find_logins: Account /home/kerle/.config/DeltaChat/accounts/ac9 is inaccessible TypeError: Cannot read property 'addr' of null
    at /home/kerle/Coding/deltachat-desktop/tsc-dist/main/logins.js:55:31
    at Generator.next (<anonymous>)
    at fulfilled (/home/kerle/Coding/deltachat-desktop/tsc-dist/main/logins.js:5:58) 
```

The ac9 folder has a db.sqlite file in it, but not any .json or anything. Probably it didn't get properly deleted?

**Comment by Simon-Laux** [comment]
why the hell should it have a json in it?
I think this could be the bug that the addr value gets missing that we observed before.

@pabzm had it at some point in time and we had the issue #1493 for it which you close because I solved the second thing you requested in it (account folder renaming).
