### ISSUE TITLE
"Settings" window cannot be closed by hitting the ESC key

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#1743]
- Operating System (Linux/Mac/Windows/iOS/Android):
Windows 8.1 Pro.

- Delta Chat Version:
1.3.4.

- Expected behavior:
When the "Settings" window is opened, hitting the ESC key should close the window.

- Actual behavior:
When the "Settings" window is opened, hitting the ESC key does not close the window. Instead, the mouse must be used to achieve this.

- Steps to reproduce the problem:
Select "Settings" which opens the "Settings" window.
Hit the ESC key which should close the window. (Currently it does not.)

- Remark:
The other windows in Delta Chat do close fine when the ESC key is hit.

**Comment by Jikstra** [comment]
This is on purpose but unsure if this is actually good ux. The idea was that you cant accidentially close the settings dialog, but i think this is a quite rare case...

**Comment by gerryfrancis** [comment]
> i think this is a quite rare case...

@Jikstra Unfortunately not that rare for Desktop users, who are used to work with the keyboard a lot, like myself.
