### ISSUE TITLE
Invalid view after closing and restarting, trying to load a deleted chat

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#1753]
- Operating System (Linux/Mac/Windows/iOS/Android):
Windows 8.1 Pro.

- Delta Chat Version:
1.3.4.

- Expected behavior:
The last view should be displayed when Delta Chat has been started.

- Actual behavior:
When started, Delta Chat shows a view that is no longer valid.

- Steps to reproduce the problem:
-- Select "New chat" and add/select a (new) chat member. (Do not send a message, yet.)
-- Delete this chat.
-- Close Delta Chat and start it again.

- Screenshots:
![Delta_Chat](https://user-images.githubusercontent.com/51095533/85542065-fbe85880-b618-11ea-915d-f1ee4c810090.png)

- Logs:
N/A.

**Comment by gerryfrancis** [comment]
I have just found out that it also happens when the same account is selected again.

**Comment by Jikstra** [comment]
Thanks for reporting :)
Fixed by https://github.com/deltachat/deltachat-desktop/pull/1754

**Comment by gerryfrancis** [comment]
@Jikstra You are welcome, and thanks for the quick fix! :+1:
