### ISSUE TITLE
Infinite (?) logging growth and too much verbosity

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#1757]
my current Desktop log file is 837M and counting, and there are more like it:

    ....
    -rw-rw-r--  1 hpk hpk  13K Jun 13 23:06 2020-06-13-23-06-30.log
    -rw-rw-r--  1 hpk hpk  92M Jun 15 08:07 2020-06-13-23-07-22.log
    -rw-rw-r--  1 hpk hpk 102M Jun 18 06:28 2020-06-15-14-16-10.log
    -rw-rw-r--  1 hpk hpk 837M Jun 26 16:23 2020-06-18-08-20-55.log

altogether the log dir takes  3.3GB. 

I noticed there are some renderer/* log lines with 1k each.  If i strip the renderer/* namespaces the 837M file goes to 37M.  

So i suggest to:

- [ ] make the logging of renderer/* and other namespaces conditional on an DC_DESKTOP_DEBUG env var or so. Most often this log file is sent by users for identifying problems often relating to core.  Current log is geared towards desktop development but devs can set DCC_DESKTOP_DEBUG or some other var in their shell. (or dunno, maybe a setting in the file-menu for switching it on/off?)

- [ ] remove all but the last two log files when creating a new one, and have a max-log-file-size of 100M before starting a new one.

**Comment by Simon-Laux** [comment]
You probably started the desktop with `--debug`. `npm run start` also enables debug mode.
Feel free reopen when this issue isn't solved by running `npx electron .` (to start without debugging and the other development options that are enabled by `npm run start`)
