### ISSUE TITLE
Leave Group menu alternative

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#176]
You should be able to leave a group.

**Comment by ralphtheninja** [comment]
![screenshot from 2018-10-20 01-48-03](https://user-images.githubusercontent.com/308049/47248383-5247d180-d40a-11e8-803c-cf33f8859de3.png)

**Comment by karissa** [comment]
Cool! there seem to be a ton of options here though, perhaps we need to start thinking about consolidating these (perhaps look at telegram/signal for cues... a settings window perhaps?)

**Comment by ralphtheninja** [comment]
> Cool! there seem to be a ton of options here though, perhaps we need to start thinking about consolidating these (perhaps look at telegram/signal for cues... a settings window perhaps?)

Agreed, it's getting crowded in there. @Jikstra had some ideas on this iirc.
