### ISSUE TITLE
search shows placeholders

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1762]
on some searches, maybe when typing a bit faster, not sure, only the first few chats are shown, for he others the placehoders stay.

the placeholders are not clickable.

the number of chats in the title is correct.

<img width=320 src=https://user-images.githubusercontent.com/9800740/85919605-11ee5700-b86d-11ea-8f98-f8dd675afd59.png>

<img width=320 src=https://user-images.githubusercontent.com/9800740/85919634-61348780-b86d-11ea-8e31-c275636edc79.png>

**Comment by Simon-Laux** [comment]
I have this bug too

**Comment by Simon-Laux** [comment]
strange that this only applies to chats
