### ISSUE TITLE
search: rethink click on contact name

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1763]
when doing a search, one tends to browse through the results, looking here and there.

i find it pretty unexpected, when a click on a contact creates a chat without asking and even alters the search result then.

i think, the user should be asked, if a chat should be created (if no chat exists)

**Comment by Simon-Laux** [comment]
maybe we should open the profile view instead?

**Comment by Jikstra** [comment]
How is it behaving on Android or ios?
