### ISSUE TITLE
Localization fails

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#1765]
- Operating System (Linux/Mac/Windows/iOS/Android):
Windows 8.1 Pro.

- Delta Chat Version:
1.4.2 & 1.4.3.

- Expected behavior:
Delta Chat starts with the standard language of the operating system. (My system has German installed as standard.)

- Actual behavior:
Delta Chat starts with two different languages, German for the mehu bar, and English for the rest.

- Steps to reproduce the problem:
-- Set another language (e.g. German) as standard in your operating system.
-- Install Delta Chat.

- Screenshots:
![grafik](https://user-images.githubusercontent.com/51095533/85923730-de6ff480-b88d-11ea-92f4-e898d763285b.png)

- Logs:
```
2020-06-27T13:28:23.786Z	main/index            	INFO		"cwd C:\\Users\\PC_USER\\AppData\\Local\\DeltaChat"
2020-06-27T13:28:23.886Z	main/menu             	INFO		"rebuilding menu with locale de"
2020-06-27T13:28:29.181Z	main/state            	INFO		"Saving state to C:\\Users\\PC_USER\\AppData\\Local\\DeltaChat\\config.json"
```

**Comment by Simon-Laux** [comment]
I can reproduce it on linux as well

**Comment by gerryfrancis** [comment]
@Simon-Laux Maybe related to https://github.com/deltachat/deltachat-desktop/issues/1637 ?

**Comment by gerryfrancis** [comment]
Thanks, I will test the fix in the upcoming release! :+1:

**Comment by gerryfrancis** [comment]
Unfortunately it is still an issue in version 1.4.3 (German menu bar and English window content like shown in the screenshot above).

**Comment by Simon-Laux** [comment]
looks like it appeared again when restarting

**Comment by gerryfrancis** [comment]
> looks like it appeared again when restarting

@Simon-Laux It seems that it appears from the very beginning where no language has been set, yet.

**Comment by Simon-Laux** [comment]
1.4.2 has that bug, 1.4.3 doesn't have it for me. I can not test the beginning stuff right now because my OS language is en

**Comment by gerryfrancis** [comment]
@Simon-Laux AFAIK, a one-for-all default system language in Windows does not exist anymore, except for the installation process. Actually it is all about the display language that a user prefers. If there are different language packs installed, a user can choose the appropriate language to be a display language. This can be changed quite easily, so there is no need to install another Windows OS in a different language.

**Comment by Simon-Laux** [comment]
I'm on linux, do you think this bug is windows specific?

**Comment by gerryfrancis** [comment]
> the app is only partially translated on start,
@Simon-Laux Correct, just as I described. (See above.)

> but when changing the lang everything worked as expected until the app was restarted.
@Simon-Laux On my machine (Windows 8.1 Pro), when changing the language (first to English because of the menu bar, and then to German), then quitting, and running Delta Chat again, this works. So, this bug is true just for the very beginning where Delta Chat has been installed from scratch.

**Comment by gerryfrancis** [comment]
> On windows it doesn't pick up the system language on first start you say? that would then reopen #1751

@Simon-Laux That has been a fix for https://github.com/deltachat/deltachat-desktop/issues/1712 , which, obviously, is right, because the correct language is used _for the menu bar_. (See screenshot above.)

**Comment by gerryfrancis** [comment]
@Simon-Laux I have tested in version 1.10.0 and now it works, great! Thanks a lot! :+1:
