### ISSUE TITLE
Installed Delta Chat the icon is not visible

### ISSUE THREAD

**Issue by AndreazLattmann** [deltachat/deltachat-desktop#1772]
- Operating System (Linux/Mac/Windows/iOS/Android): Linux
- Delta Chat Version: 1.4.2
- Expected behavior: When I install Delta Chat, the icon is visible
- Actual behavior: The default icon of an executable appears, instead of the Delta Chat icon.
- Steps to reproduce the problem: Install the .deb app overwriting the old version
- Screenshot:
![delta_chat](https://user-images.githubusercontent.com/63752768/86163283-4fbeda00-bb10-11ea-8251-6f71139a7080.png)

**Comment by EclecticSoftwareEngineer** [comment]
I can confirm this is Debian desktop 1.4.2 and 1.4.3.

**Comment by AndreazLattmann** [comment]
This also happens in version 1.10.3 🙄

**Comment by EclecticSoftwareEngineer** [comment]
On Mon, Aug 03, 2020 at 11:36:13AM -0700, Andreas Lattmann wrote:

> This also happens in version 1.10.3 🙄

I confirm that the issue remains in Debian Desktop 1.10.3. (Application icon not packaged??)

David

**Comment by g6094199** [comment]
also on 1.1.12 on Ubuntu/Debian

**Comment by Norbert80** [comment]
Same on 1.4.3 and 1.12.0.

**Comment by sT331h0rs3** [comment]
Can confirm it with Fedora 32 and RPM package.
The desktop file has `Icon=deltachat-desktop`, but the icon file is unpacked to `/usr/share/icons/hicolor/0x0/apps/deltachat-desktop.png` for some reason. Icon shows up well if absolute path is set directly: `Icon=/usr/share/icons/hicolor/0x0/apps/deltachat-desktop.png`. I've tried resizing the `build/icon.png` to 256x256 and rebuilding the RPM, but the icon path remained the same with `0x0`.

**Comment by Jikstra** [comment]
Seems like electron builder is making weird things here :/
