### ISSUE TITLE
Chat avatars are not visible

### ISSUE THREAD

**Issue by AndreazLattmann** [deltachat/deltachat-desktop#1773]
- Operating System (Linux/Mac/Windows/iOS/Android): Linux
- Delta Chat Version: 1.4.2
- Expected behavior: I expect to see chat avatars and not a corrupt image "icon".
- Actual behavior: A corrupt image icon is displayed, as per screenshot.
- Steps to reproduce the problem: I don't know how to reproduce the problem.
- Screenshots:

![delta_chat_avatars](https://user-images.githubusercontent.com/63752768/86165102-20f63300-bb13-11ea-9a4a-f1559becd3c3.png)

- Logs:

[2020-06-30-20-35-26.log](https://github.com/deltachat/deltachat-desktop/files/4853866/2020-06-30-20-35-26.log)

**Comment by AndreazLattmann** [comment]
By importing the backup, I recover all the avatars. 🤔

**Comment by Jikstra** [comment]
This problem shows up every now and then and with reimporting a backup seems to disappear again. Not sure where it comes from. @r10s @cyBerta is anything like this happening on ios or android too?

**Comment by Simon-Laux** [comment]
I suspect that the core is deleting avatars sometimes, for one of my accounts the avatar for the saved messages chat went missing.

**Comment by AndreazLattmann** [comment]
@Jikstra It never happened to me with Android.

**Comment by hpk42** [comment]
On Tue, Jun 30, 2020 at 22:51 -0700, Andreas Lattmann wrote:
> @Jikstra It never happened to me with Android.

same here so far -- i only had disappearing avatrs with desktop so far
(not lately though).

**Comment by Jikstra** [comment]
@hpk42 are they missing on hard drive or is deltachat just not able to load the from the correct path? With the browser development tools you can figure out the path desktop is trying to load the file from and let us know what it is :)

**Comment by Simon-Laux** [comment]
for me its missing on the actual filesystem

**Comment by Simon-Laux** [comment]
I believe this is/was a core bug. I'm closing this now as this problem didn't appear for me in a long time. Please reopen this issue when it appears again.
