### ISSUE TITLE
Please provide an APT repository

### ISSUE THREAD

**Issue by geor-g** [deltachat/deltachat-desktop#1774]
Well, the title tells it all. 

Otherwise, unless I'm missing something (?), it's a bit cumbersome to pull in new versions, as one has to parse the website, download the .deb and install it afterwards.

**Comment by EchedeyLR** [comment]
Maybe using OpenSUSE Build Service like Ungoogled Chromium repos could help a lot. You can maintain repos for different distros including APT one for Debian and Ubuntu as the example I gave...

**Comment by franck-x** [comment]
Here is a -hacky but working- script to verify if installed version is the latest version available, and if so, download and install the .deb file.

May need to be updated to your need, and also if website template change.

```bash
#!/bin/bash

regex="(VERSION_DESKTOP = \")(.*)(\" %})"
url='https://raw.githubusercontent.com/deltachat/deltachat-pages/master/_includes/download-boxes.html'
dom="`wget -qO- $url`"
installedVersion="`dpkg-query --showformat='${Version}' --show deltachat-desktop`"

if [[ $dom =~ $regex ]]
then
	latestVersion="${BASH_REMATCH[2]}"
	echo "installed version: ${installedVersion}"
	echo "latest version: ${latestVersion}"

	if [[ ${installedVersion} != ${latestVersion} ]]
	then
		deburl="https://download.delta.chat/desktop/v${latestVersion}/deltachat-desktop_${latestVersion}_amd64.deb"
		echo "will download: $deburl"

		wget -O /tmp/deltachat.deb $deburl
		sudo dpkg -i /tmp/deltachat.deb
	else
		echo "latest version already installed"
	fi
else
	echo "error fetching latest version"
fi
```

**Comment by rafael2k** [comment]
I added 1.34.1 here:
http://packages.hermes.radio/
Plan to keep it to the latest version (amd64 only for now).

**Comment by Simon-Laux** [comment]
- https://wiki.debian.org/DebianRepository/Setup#Debian_Repository_Generation_Tools
- https://wiki.debian.org/DebianRepository/Format

**Comment by Simon-Laux** [comment]
I made a forum topic for this, make sure to vote on the survey there if you want to see us maintaining an official apt repo: https://support.delta.chat/t/survey-additional-ways-to-get-dc-desktop-on-linux/3320

moving the discussion to the forum and this issue to project resurrection. We can reopen it when someone is willing to work on it.

**Comment by rafael2k** [comment]
I get "You need to be a member of trust_level_1 to vote in this poll.".
My vote is to add a "debian" directory to serve as reference for upstream inclusion for at least Debian and Ubuntu.

**Comment by Simon-Laux** [comment]
![Bildschirmfoto 2024-11-14 um 17 23 06](https://github.com/user-attachments/assets/a6c1ccf4-e1d8-41fd-a548-65206fac58ac)

That restriction is to increase the cost of cheating. click around on the forum a bit or send me your forum handle / username so I know what account to promote. (I everyone to trust level 1 that has posted on this issues so far, just send me your forum name)

**Comment by g6094199** [comment]
Hi @all,

since there is still a need for a debian repo (snaps are a pain in the a***. slow, and buggy. while flatpack is better there is no need to download hundreds of MB on dependencies for each installed programm. this windoze behaviour is annoying and only good for single programm testing). so real packaging is the only way.

 there is an easy github reicpe.

 simply use the [github doku for debian packaging](https://github.com/flavienbwk/deb-package-tutorial). 


;-)

THX
