### ISSUE TITLE
Desktop Client forget the choosen language

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-desktop#1775]
- Operating System (Linux/Mac/Windows/iOS/Android): Linux
- Delta Chat Version: 1.4.2 (preview)
- Expected behavior: don't change the choosen language
- Actual behavior: after client restart the language is always set to english
- Steps to reproduce the problem:

1. Choose german as language
2. See the menue is german
3. Close DC Client
4. The three dots menue is now in english again (all other still german)
5. But the menue item "view>language" is still set to german

So all in all it seems it's infected only the "three Dot menue" in the right upper corner.

**Comment by gerryfrancis** [comment]
@webratte See https://github.com/deltachat/deltachat-desktop/issues/1765 . I would like to know if this is an issue in version 1.4.3, too, could you check this, please?

**Comment by webratte** [comment]
Is a downgrade (or a parallel installation) possible without loosing my Data?

**Comment by webratte** [comment]
Sorry, my fault.
It's a upgrade of course.
I will check it out.

**Comment by webratte** [comment]
My issue is fixed in V.1.4.3
So, if you like you can close this.

Thank you

**Comment by gerryfrancis** [comment]
@webratte Thank you for reporting back. I cannot close your issue, please do it yourself. Thanks!
