### ISSUE TITLE
Version 1.3.4 not autoupdate messages

### ISSUE THREAD

**Issue by prokopiy** [deltachat/deltachat-desktop#1776]
Version 1.3.4 for Windows not autoupdate messages. You have to restart the application to see new messages.

**Comment by gerryfrancis** [comment]
@prokopiy Could you check out current version 1.4.3 and try to reproduce your issue, please? Thanks in advance.

**Comment by Simon-Laux** [comment]
https://download.delta.chat/desktop/v1.4.3/

**Comment by Simon-Laux** [comment]
or even better try the upcoming release https://support.delta.chat/t/test-upcomming-desktop-1-10-x-release/1080

**Comment by Jikstra** [comment]
Closing as we don't get any more info about this
