### ISSUE TITLE
flatpak: Error: Cannot find module './tsc-dist/main'

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-desktop#1777]
- Operating System (Linux/Mac/Windows/iOS/Android): Linux (Manjaro)
- Delta Chat Version: 1.4.3
- Steps to reproduce the problem: I just updated it
- Behavior: When trying to start DC nothing happens

<pre>$ flatpak run chat.delta.desktop
Gtk-<font color="#55FF55"><b>Message</b></font>: <font color="#0000AA">21:31:02.390</font>: Failed to load module &quot;canberra-gtk-module&quot;
Gtk-<font color="#55FF55"><b>Message</b></font>: <font color="#0000AA">21:31:02.390</font>: Failed to load module &quot;canberra-gtk-module&quot;
<span style="background-color:#AAAAAA"><font color="#FF5555"><b>A JavaScript error occurred in the main process</b></font></span>
<span style="background-color:#AAAAAA"><font color="#555555"><b>Uncaught Exception:</b></font></span>
<span style="background-color:#AAAAAA"><font color="#555555"><b>Error: Cannot find module &apos;./tsc-dist/main&apos;</b></font></span>
<span style="background-color:#AAAAAA"><font color="#555555"><b>Require stack:</b></font></span>
<span style="background-color:#AAAAAA"><font color="#555555"><b>- /app/delta/resources/app.asar/index.js</b></font></span>
<span style="background-color:#AAAAAA"><font color="#555555"><b>- </b></font></span>
<span style="background-color:#AAAAAA"><font color="#555555"><b>    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)</b></font></span>
<span style="background-color:#AAAAAA"><font color="#555555"><b>    at Function.Module._resolveFilename (/app/delta/resources/electron.asar/common/reset-search-paths.js:41:16)</b></font></span>
<span style="background-color:#AAAAAA"><font color="#555555"><b>    at Function.Module._load (internal/modules/cjs/loader.js:531:27)</b></font></span>
<span style="background-color:#AAAAAA"><font color="#555555"><b>    at Module.require (internal/modules/cjs/loader.js:685:19)</b></font></span>
<span style="background-color:#AAAAAA"><font color="#555555"><b>    at require (internal/modules/cjs/helpers.js:16:16)</b></font></span>
<span style="background-color:#AAAAAA"><font color="#555555"><b>    at Object.&lt;anonymous&gt; (/app/delta/resources/app.asar/index.js:5:1)</b></font></span>
<span style="background-color:#AAAAAA"><font color="#555555"><b>    at Module._compile (internal/modules/cjs/loader.js:786:30)</b></font></span>
<span style="background-color:#AAAAAA"><font color="#555555"><b>    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)</b></font></span>
<span style="background-color:#AAAAAA"><font color="#555555"><b>    at Module.load (internal/modules/cjs/loader.js:645:32)</b></font></span>
<span style="background-color:#AAAAAA"><font color="#555555"><b>    at Function.Module._load (internal/modules/cjs/loader.js:560:12)</b></font></span></pre>

**Comment by Simon-Laux** [comment]
this is from bundling the flatpak which is managed by @muelli https://github.com/flathub/chat.delta.desktop
Looks like either the build wasn't run or the result was deleted (from the error, didn't look into the flathub building process).

**Comment by Simon-Laux** [comment]
its the same as https://github.com/flathub/chat.delta.desktop/issues/41
