### ISSUE TITLE
Profile picture is distorted if not square

### ISSUE THREAD

**Issue by arthurzenika** [deltachat/deltachat-desktop#1779]
- Operating System (Linux/Mac/Windows/iOS/Android): Ubuntu Focal
- Delta Chat Version: 1.4.3 via deb packages
- Expected behavior:

![Screenshot from 2020-07-07 10-21-03](https://user-images.githubusercontent.com/445200/86746885-ab6ef300-c03b-11ea-9791-a8f5d79934cc.png)

- Actual behavior:

![Screenshot from 2020-07-07 10-20-38](https://user-images.githubusercontent.com/445200/86746919-b033a700-c03b-11ea-86b0-b5c5985892b1.png)

**Comment by Simon-Laux** [comment]
We should make sure it is square than, maybe with a crop dialog like on android.

**Comment by gerryfrancis** [comment]
I think the image could also be cropped to a circle, that would be nice!

**Comment by EchedeyLR** [comment]
I think that crop to square and show it in a circle (hiding overflowed part) would be better since apps like whatsapp or similar do that allowing the picture to be showed completely when clicking on it.

**Comment by EchedeyLR** [comment]
Well, maybe I misread the issue and is just being used already, the thing is that I maintain my opinion about squares are better.

**Comment by r10s** [comment]
> We should make sure it is square than, maybe with a crop dialog like on android.

or, maybe there is some css option that does this center+crop while keeping aspect ratio? that might be the simplest solution for now. and would probably also be need for existing images or images from other sources.

core could also force a square, however, as by the "enlarge" we do show all of the image there is some sense in keeping all detail.

**Comment by EchedeyLR** [comment]
> or, maybe there is some css option that does this center+crop while keeping aspect ratio?

Clip-path... ?? <.<

**Comment by gerryfrancis** [comment]
Some more information about `clip-path`: https://www.w3schools.com/cssref/css3_pr_clip-path.asp

**Comment by Simon-Laux** [comment]
we could just crop it, I don't like css hacks to do hide the problem.
https://foliotek.github.io/Croppie/
https://fengyuanchen.github.io/cropperjs/
https://github.com/thegreatercurve/react-simple-crop/
https://github.com/DominicTobias/react-image-crop#usage/

**Comment by EchedeyLR** [comment]
> we could just crop it, I don't like css hacks to do hide the problem.

A standard CSS property, not a hack, to show the part in which you are interested while the image is a square and add, in a future, an event handler to show the image more detailed.

I strongly think that your "trick" is to hide the real problem handling the images.

**Comment by EchedeyLR** [comment]
Sorry. Just think on the other idea.

**Comment by farooqkz** [comment]
I can't reproduce it on 1.38.1
Maybe it has been fixed?
