### ISSUE TITLE
On Crash, better exit if context can not be stopped

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#1794]
i had duplicate message issues (https://github.com/deltachat/deltachat-core-rust/issues/1701 ) which i thought were core-related bu i now think it was just desktop. I had a Desktop crash multiple times and "reloaded" (a new option i didn't see before) but i now think that this does not "stop_io()" the context.  So this is how i ended up with at some point 4 contexts running, and saw each incoming messages four times. 

So if stop_io() can not be called anymore, it's better to only offer the option to exit, and not reload.

**Comment by Simon-Laux** [comment]
reload does reload the browser window which also logs the user in since the last login refactoring and for some reason the login doesn't check if there is already an active account...

**Comment by Simon-Laux** [comment]
The whole system is really messy, but I think that will improve with the planned backend refactoring.

**Comment by Jikstra** [comment]
I have the feeling that this is electron related and somehow spawns another main process. I saw this too with the "too many connections" error.

**Comment by Simon-Laux** [comment]
why should it spawn another main process? I believe the too many connections error is a different one.

**Comment by Jikstra** [comment]
I don't know why, would be completely stupid.
