### ISSUE TITLE
Option LeftArrow keys don't move cursor to previous word

### ISSUE THREAD

**Issue by Gozala** [deltachat/deltachat-desktop#1796]
- Operating System (Linux/Mac/Windows/iOS/Android): mac
- Delta Chat Version: Version 1.4.1 (1.4.1)
- Expected behavior: Move cursor to a previous word in the text
- Actual behavior: Cursor does not move
- Steps to reproduce the problem:
   - In any chat type text: "hello world" 
   - Press Option LeftArrow
   -  Caret should appear between space and `w` (but it does not move)

Option RigtArrow doesn't seems to work as expected.
`Shift Options LeftArrow` should select word to the left, but that also does nothing.

**Comment by gerryfrancis** [comment]
I cannot reproduce this in Delta Chat for Desktop 1.4.3 on Windows 8.1 Pro.

@Gozala Please try to reproduce your issue in version 1.4.3 and report back. Thanks!

**Comment by Jikstra** [comment]
@gerryfrancis this is probably mac specific?

**Comment by gerryfrancis** [comment]
@Jikstra Maybe, but it should be verified with the latest version of Delta Chat.

**Comment by Simon-Laux** [comment]
Looks like we need other keybindings for mac:
```js
} else if (ev.altKey && ev.key === 'ArrowLeft') {
      return KeybindAction.ChatList_ScrollToSelectedChat
```
