### ISSUE TITLE
Show sender/authors name in ChatView

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#180]
Didn't track it down completely but somewhere in the conversations stuff the profileAuthorName /DisplayName isn't getting pushed through correctly or something. But the profileAuthorName is given through the initial conversations stuff correctly or at least more is borken.

**Comment by ralphtheninja** [comment]
Can you paste some links to where the problem is? And/or some screenshots.

**Comment by ralphtheninja** [comment]
I think we should nail this one before releasing 1.5.0

**Comment by r10s** [comment]
the android versions show the name of the senders directly above the text in a slightly different font/color.

on android, this is done _only_ for group chats, for normal chats, this is not required (skipped to save monitor space, however, on desktop maybe this optimization in not required)
