### ISSUE TITLE
Term "Select" (button) not localized (hardcoded) in preferences dialog

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#1800]
- Operating System (Linux/Mac/Windows/iOS/Android):
Windows 8.1 Pro.

- Delta Chat Version:
1.10.0-1.12.0.

- Expected behavior:
Button "Select" should be localized.

- Actual behavior:
Button "Select" is not localized.

- Steps to reproduce the problem:
-- Set language of Delta Chat to a different one than English (if not configured this way, yet).
-- Open the preferences dialog.

- Screenshots:
![grafik](https://user-images.githubusercontent.com/51095533/87658262-3d71ac80-c75c-11ea-83ec-81e4630cd979.png)

- Logs:
N/A.

**Comment by gerryfrancis** [comment]
Still an issue in version 1.12.0.

**Comment by r10s** [comment]
i've just added the string `select` to transifex so that it can be used by deltachat-desktop.

**Comment by Simon-Laux** [comment]
same goes for the remove option I guess, only found the `remove_desktop` string, so I'll use that one.

**Comment by gerryfrancis** [comment]
@Simon-Laux Thanks, I did not have this one on my radar anymore! ;-)
