### ISSUE TITLE
"New contact" in search results does not work

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#1804]
- Operating System (Linux/Mac/Windows/iOS/Android):
Windows 8.1 Pro.

- Delta Chat Version:
1.10.0.

- Expected behavior:
"New contact" does not show up in search results.

- Actual behavior:
"New contact" shows up in search results.

- Steps to reproduce the problem:
-- Focus the search bar and type a phrase that does not match with a part of a name from the contact list.

- Screenshots:
![grafik](https://user-images.githubusercontent.com/51095533/87775804-fac8d680-c826-11ea-86fe-63bdffc8195c.png)

- Logs:
N/A.

**Comment by Jikstra** [comment]
That's expected behaviour. If you search for `foobar@newmail.com` you can add the user directly. But probably we should just hide this New Contact thing.

**Comment by gerryfrancis** [comment]
> That's expected behaviour.

@Jikstra I thought it is a bug, because it does not work. Have you tested this function?
