### ISSUE TITLE
"Invalid date" shown in message details for searched messages

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#1805]
- Operating System (Linux/Mac/Windows/iOS/Android):
Windows 8.1 Pro.

- Delta Chat Version:
1.10.0.

- Expected behavior:
When looking at details for a message that has been searched for, the sent date should be displayed.

- Actual behavior:
When looking at details for a message that has been searched for, the sent date is not displayed. It shows "Invalid date" instead.

- Steps to reproduce the problem:
-- Focus the search bar and type a phrase that can be found in a stored message.
-- Click on (one) message shown in the chat list (as the search result).

- Screenshots:
![grafik](https://user-images.githubusercontent.com/51095533/87776989-f9001280-c828-11ea-974e-5355d6647e8f.png)

- Logs:
N/A.

- Remarks:
Have a quick look at date in the first line, the date/time format is not English (AM/PM).

**Comment by Jikstra** [comment]
I think it's the same on android? As far as i know the core doesn't translate this. It's mainly for "debugging".

**Comment by gerryfrancis** [comment]
@Jikstra I cannot verify if it happens on Android, too, because I have no device to test with at the moment.
