### ISSUE TITLE
Desktop search feature crashing

### ISSUE THREAD

**Issue by EclecticSoftwareEngineer** [deltachat/deltachat-desktop#1812]
- Operating System (Linux/Mac/Windows/iOS/Android): Debian GNU/Linux (Buster)
- Delta Chat Version: 1.4.3
- Expected behavior: Search term found, if present
- Actual behavior: On typing two or three characters, a crash occurs, and Delta Chat needs to be reloaded.

- Steps to reproduce the problem: 

On desktop DC, click search box and type first few letters of a term which is present in some recent message.

On the second or third letter, a crash will occur.

- Screenshots:

![Screenshot_20200726_104415](https://user-images.githubusercontent.com/22928836/88468982-c0e68700-cf2e-11ea-8b11-1cfb24df0597.png)

- Logs:

**Comment by EclecticSoftwareEngineer** [comment]
The problem does not appear to occur on DC Android 1.10.4

**Comment by Simon-Laux** [comment]
dupliacate of https://github.com/deltachat/deltachat-desktop/issues/1803
will be fixed in the next release (1.10.x) 
The 1.10.0 build is currently in testing phase, you can help testing if you want: https://support.delta.chat/t/test-upcomming-desktop-1-10-x-release/1080

**Comment by EclecticSoftwareEngineer** [comment]
Thanks, Simon. For some reason I did not find the existing report when I looked for it.

Kind regards,
David
