### ISSUE TITLE
Clicking search result does not display the message

### ISSUE THREAD

**Issue by EclecticSoftwareEngineer** [deltachat/deltachat-desktop#1813]
- Operating System (Linux/Mac/Windows/iOS/Android): Debian GNU/Linux (Buster)
- Delta Chat Version: 1.10.0
- Expected behavior: Clicking on message search result should display the message.
- Actual behavior: A "Message Details" dialogue is displayed, which notes an invalid sent date.

- Steps to reproduce the problem:

Type a search term which is known to exist in a recent message.

Click one of the found messages.

The message is not displayed, but a message details dialogue is displayed instead. This dialogue seems normal except for the very last line, which notes an invalid sent date, for some reason ("inviato  Invalid date ()"). ("inviato" = "sent")

- Screenshots:

![Screenshot_20200726_123041](https://user-images.githubusercontent.com/22928836/88470235-61dc3e80-cf3d-11ea-8c77-170365db539c.png)

I am assuming that clicking the search result should show the message.

**Comment by gerryfrancis** [comment]
> A "Message Details" dialogue is displayed, which notes an invalid sent date.

The "invalid sent date" issue will be fixed in the next version, see https://github.com/deltachat/deltachat-desktop/issues/1805 .

**Comment by EclecticSoftwareEngineer** [comment]
On Sun, Jul 26, 2020 at 03:57:47PM -0700, gerryfrancis wrote:
> > A "Message Details" dialogue is displayed, which notes an invalid sent date.
> 
> The "invalid sent date" issue will be fixed in the next version, see https://github.com/deltachat/deltachat-desktop/issues/1805 .

Thanks again, Gerry. I see I will have to get better at searching those existing issues!

Cheers,
David

**Comment by Simon-Laux** [comment]
> The message is not displayed, but a message details dialogue is displayed instead. 

that's the current behavior until we can implement jumping to the message in question.

**Comment by jchook** [comment]
> that's the current behavior until we can implement jumping to the message in question.

Sorry to resurrect a dead issue but are we tracking this in an issue?

**Comment by Jikstra** [comment]
@jchook https://github.com/deltachat/deltachat-desktop/pull/2159 fixes this. I hope I can reimplement that pr soon and fix the last bugs. Current eta is to have this ready for the version after this.
