### ISSUE TITLE
login-screen shortly flashes on startup

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1815]
even when an account is already configured and the login screen is not needed, the app starts with the login-screen shortly flashing up, showing the normal view half a second later.

this looks unprofessional and is not nice, also leaves the user with the impression they have missed something or something went wrong.

the app should just start in the chatlist-screen as before.

(this issue is introduced in 1.10, iirc, it was not there in the version before)

**Comment by gerryfrancis** [comment]
Confirmed.

**Comment by Simon-Laux** [comment]
It fixed it for the most part, but for me the dialog still flashes, even though now it doesn't load completely and the flash is shorter.
