### ISSUE TITLE
History of chat not shown on new device

### ISSUE THREAD

**Issue by konsta-n-tin** [deltachat/deltachat-desktop#1822]
- Operating System (Linux/Mac/Windows/iOS/Android): Win10
- Delta Chat Version: 1.4.3
- Expected behavior: When I install DeltaChat on new device and make connect with Autocrypt setup message I want to see histories of all of my chats
- Actual behavior: On new device I see only new messages

**Comment by Simon-Laux** [comment]
Autocrypt setup only transfers a key, you need to do a **backup export** on your previous device and an **backup import** on your device that you want to add the account to.

There are two plans to make this simpler in the future:
- Download imap history
- easier backup export/import workflow over an qr code

If you got more questions / feature proposals feel free to ask them on the forum https://support.delta.chat/
