### ISSUE TITLE
Use virtual scrolling for other contact lists to account for slow loading

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1830]
Some users (probably users with many contacts) observe slow loading of the dialogue when creating a new chat, this is caused by the contact list component.

There are two separate fixes which will help with lowering the loading time:

* Use faster `getContactIds` RPC call (as pointed out by @link2xt)
* Use virtual scrolling as we already use it in the global search (as pointed out by @Simon-Laux)

**Comment by Simon-Laux** [comment]
I think the only place where it would make some sense is the new chat dialog, UnblockContact and ViewGroup don't likely have so much items that it would be worth it.

**Comment by Simon-Laux** [comment]
merging in comments from #3632:

> Contact list is using slow getContacts JSON-RPC call which returns a list of objects rather than calling fast getContactIds and then loading contacts on demand.
> 
> This result in 150-200ms delay when clicking on "+" button in the chatlist before any contacts are displayed.
>
> ~ link2xt in #3632


> Actually measured with:
> 
> ```
> console.time("foo"); exp.rpc.getContacts(1, 2, ''); console.timeEnd("foo")
> ```
> 
> and it shows at most 27ms :/
> 
> So react debounce/memo wrappers might be adding something to it.
>
> ~ link2xt in #3632


> You forgot an `await`:
> 
> ```js
> console.time("foo"); await exp.rpc.getContacts(window.__selectedAccountId, 2, ''); console.timeEnd("foo")
> ```
> 
> In my tests: `exp.rpc.getContactIds`: is 1,5-25ms `exp.rpc.getContacts`: is 65-77ms
> 
> The debouncing might add a delay, especially if it waits the initial time, haven't looked at the code, but I think using a virtual list as the already existing issue #1830 says is the real solution.
>
> ~ simon-laux in #3632

**Comment by WofWca** [comment]
Uh-oh, not great news. What I didn't realize is that [`BackendRemote.rpc.getContacts()`](https://github.com/deltachat/deltachat-desktop/blob/bf11419376a1263b62699c770f6ed7b6c12a059c/src/renderer/components/contact/ContactList.tsx#L96) is async...
Itself it takes ~3 seconds to finish for 5000 contacts:

![image](https://github.com/deltachat/deltachat-desktop/assets/39462442/1f2dd0ae-6fc9-48c7-9a57-408b6c9b0a03)

So after all it's not _only_ the UI, as I initially said. @link2xt and @Simon-Laux were both right.

**Comment by r10s** [comment]
thanks a lot for the measuring and for diving into this topic. 

just a single data point i have, however, i cannot realise how my iphone13mini with >9000 contacts, loaded in 10ms or less fits into that (i killed the app to avoid caching, then reopened and opened "New Chat" with the contact list, that is displayed really quick)

<img width=280 src=https://github.com/deltachat/deltachat-desktop/assets/9800740/2bc83227-183c-4a5f-967e-a67285785ca4>
<img width=280 src=https://github.com/deltachat/deltachat-desktop/assets/9800740/3a24f329-7210-4844-b207-18abcc1d1c51>

(measurement at https://github.com/deltachat/deltachat-ios/blob/ab375b06bd254a708425efd107e765fa958c288b/deltachat-ios/DC/DcContext.swift#L115 )

**Comment by WofWca** [comment]
`BackendRemote.rpc.getContacts` in Desktop is the same as `dc_get_contacts` in iOS, right?

**Comment by r10s** [comment]
get_contacts() in https://github.com/deltachat/deltachat-core-rust/blob/main/deltachat-jsonrpc/src/api.rs#L1357 looks to me as if all contacts are loaded ...

**Comment by Simon-Laux** [comment]
iOS also uses a virtual / lazy loaded list afaik.

**Comment by WofWca** [comment]
Update: #3842 is merged, so the UI part is solved. Now it's about `BackendRemote.rpc.getContacts()` being slow.

**Comment by Simon-Laux** [comment]
> Update: https://github.com/deltachat/deltachat-desktop/pull/3842 is merged, so the UI part is solved. Now it's about BackendRemote.rpc.getContacts() being slow

nope, the solution is to add lazy loading/infinite loading and that is a UI task. I doubt that we could make the core/jsonrpc function `BackendRemote.rpc.getContacts()` much faster.
Chatlist also uses lazy loading for that purpose.
