### ISSUE TITLE
Bug: Search bar crash - Строка поиска отпадает

### ISSUE THREAD

**Issue by GoodMan666** [deltachat/deltachat-desktop#1834]
Я буду писать на русском по скольку это мой родной язык, с гугл переводчиком. 
I will write in Russian since it is my native language, with google translator.
- Operating System: win 10 ltsc
- Delta Chat Version: Version 1.4.3 (git: v1.4.3)
- Expected behavior: Я пытаюсь воспользоваться поиском, что бы найти собеседника. - I want to find a person.
- Actual behavior: Я получаю мгновенно ошибку при попытке вписать что либо в строку поиска. - I enter something into the search bar and instantly get an error.
- Steps to reproduce the problem: Reloaded
- Video: [>Mega link<](https://mega.nz/file/j5VijK4J#AwygKs9dUEB9WOpXWm6EhywRQqzYIDwzFXpR2mqcEks)
- Logs: [>Mega link<](https://mega.nz/file/HwdCzYCI#TTyCnz07kf8Ee2TCTAAdc9GZZkh__ZlKbn0Ymf3014o)

**Comment by gerryfrancis** [comment]
@GoodMan666 Thank you for your report. Your issue is already fixed, see https://github.com/deltachat/deltachat-desktop/issues/1803 . Please update to the latest version of Delta Chat, currently 1.12.0. You can download it from here: https://download.delta.chat/desktop/v1.12.0/
