### ISSUE TITLE
Building pre-release 1.12.0 from tarball fails

### ISSUE THREAD

**Issue by hnrd** [deltachat/deltachat-desktop#1841]
- Delta Chat Version: 1.12.0
- Expected behavior: npm run build succeeds
- Actual behavior: Build fails on `git submodule`, as the tarball is not a git repository

The build script introduced a dependency on the build directory being a git clone:
```
[...]
> deltachat-desktop@1.12.0 install:submodules /build/deltachat-desktop/src/deltachat-desktop-1.12.0
> git submodule update --recursive --init

fatal: not a git repository (or any of the parent directories): .git
npm ERR! code ELIFECYCLE
npm ERR! errno 128
npm ERR! deltachat-desktop@1.12.0 install:submodules: `git submodule update --recursive --init`
npm ERR! Exit status 128
npm ERR! 
npm ERR! Failed at the deltachat-desktop@1.12.0 install:submodules script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2020-08-04T16_20_47_849Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 128
npm ERR! deltachat-desktop@1.12.0 install: `npm run install:submodules`
npm ERR! Exit status 128
npm ERR! 
npm ERR! Failed at the deltachat-desktop@1.12.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2020-08-04T16_20_47_906Z-debug.log
```

**Comment by Simon-Laux** [comment]
already fixed that in master https://github.com/deltachat/deltachat-desktop/blob/master/.gitmodules

I suggest to patch this file or using the current master

**Comment by hnrd** [comment]
I'm building the releases, from the release tarballs, e.g. the asset on https://github.com/deltachat/deltachat-desktop/releases/tag/v1.12.0

Not avoiding git per se, I just try to stick to the "official" releases.
I'll close this and will try to fetch a basicwebrtc-snapshot in another way in my PKGBUILD.

Still you maybe would want to mention that the tarballs aren't buildable on their download page :)
