### ISSUE TITLE
no new messages after sleep

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1842]
on mac, also on 1.12.0, new messages are not fetched after device wakeup.

i had a closer look at the logs, i would expect some loops stuck in core or so, however, i found nothing like that, only some log lines saying **Saving state to /Users/NAME/Library/Application Support/DeltaChat/config.json** - see end of `log1.txt`

log1.txt: https://gist.github.com/r10s/ac515b74edd2d64f3ff44032cd9cf3ba

after a restart, messages are fetched as expected:

log2.txt https://gist.github.com/r10s/e17566f8fa90f7aecbf3f8e594e3bc02

**Comment by gerryfrancis** [comment]
Cannot confirm this in Windows.

**Comment by Simon-Laux** [comment]
I can't tell anything from your logs, maybe you could test how the repl behaves or a simple bot that prints all core events to the console.

If we upgrade electron we could use https://www.electronjs.org/docs/api/power-monitor to call maybeNetwork on screenunlock, maybe that would help? (though the resume event would be much better for this case, but it isn't implemented for mac.

**Comment by Jikstra** [comment]
I'm experiencing the same on android sadly, that i need to log out and log in again to fetch new messages.

**Comment by r10s** [comment]
well, i cannot tell anything directly from the logs neither. 

it does not happen every time, but some times, maybe it is a core issue. however, i cannot confirm this happens on android (not saying it does not exist :).

actually, i only have that after looong sleeps, eg. one whole night (had that just now, here is another log: https://gist.github.com/r10s/015f3bbdce1415df7b33e5c253eb2055 - in this case, there was some action, messages were retrieved, however, they were definitely not shown - maybe there is a redraw missing? sth. like that? i will keep an eye on that.

**Comment by Simon-Laux** [comment]
maybe its not sleep related but it stops working randomly? because I had message receiving problems without any sleep states in 1.12, too. But I didn't investigate it. (I could write/send new messages but I didn't receive any messages until I restarted the app).

> maybe there is a redraw missing?

then reentering the chat should show the missing new messages, can you reproduce it and try that out? (select other chat than the go back to the chat)

**Comment by r10s** [comment]
i still have an eye on that, for me, it is still not reliable. however, i would be fine with closing this issue until there are more findings and an actionable item.

**Comment by shockme** [comment]
I am experiencing this on Ubuntu 16.04 with the 1.12.0 AppImage (although I don't think the distribution format is relevant). New messages are eventually fetched but it takes many minutes for it to happen after resuming from standby.
