### ISSUE TITLE
Latest contact request sometimes missing in contact request view

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#1843]
- Operating System (Linux/Mac/Windows/iOS/Android):
Windows 8.1 Pro.

- Delta Chat Version:
1.12.0.

- Expected behavior:
The latest contact request is shown among the others when the contact request view is displayed.

- Actual behavior:
The latest contact request is not always shown in the contact request view. (However, it is shown in the chat list.)

- Steps to reproduce the problem:
-- Configure Delta Chat to receive classic mails.
-- Open the contact request view.
-- Quit Delta Chat.
-- Let someone send a mail to your address.
-- After the mail has been sent, run Delta Chat again. The latest view, which is the one for contact requests, is opened automatically.
-- Scroll to the bottom, if necessary. (Result: The latest contact request is not displayed.)

- Screenshots:
N/A.

- Logs:
N/A.

**Comment by Simon-Laux** [comment]
does this still occur?

**Comment by gerryfrancis** [comment]
@Simon-Laux Thanks for reminding, yes, I have just tested with version 1.15.3.
