### ISSUE TITLE
Updating message status fails when respective message not delivered (user unknown)

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#1845]
- Operating System (Linux/Mac/Windows/iOS/Android):
Windows 8.1 Pro.

- Delta Chat Version:
1.12.0.

- Expected behavior:
The current message status is displayed in the respective green bubble for messages that could not be sent.

- Actual behavior:
The current message status is not displayed when the message could not be sent.

- Steps to reproduce the problem:
-- Manually add a contact that does not exist, e.g. "sdklfjsd@gmx.net". (Note: The domain must exist to reproduce the issue!)
-- Send a message to this fake contact.

- Result:
The check (status "Delivered") appears in the green bubble of this message, and it stays that way. Unless the screen is not refreshed (manually by the user),

- Screenshots:
![grafik](https://user-images.githubusercontent.com/51095533/89524115-464a2100-d7e4-11ea-8bd7-02272bb84a58.png)

- Remark:
This is quite an unfortunate user experience. You have been given a mail address and enter it with a typo in Delta Chat. Then, you send a message (which in fact is not delivered), see the check in the message bubble, and leave your desktop. When you return, Delta Chat still shows the check mark, although it does not comply with the reality, because the message has not been delivered, and the screen has not been refreshed, yet. The only part that immediately refreshes after the message has been sent away (but not been delivered), is the little red circle holding an exclamation mark within the entry in the contact list. (See screenshot above.)

- Logs:
N/A.

**Comment by Simon-Laux** [comment]
is this still an issue?

**Comment by gerryfrancis** [comment]
@Simon-Laux Thanks for reminding (again), no, I have just tested with version 1.15.1, it looks good now. Closing here.
