### ISSUE TITLE
Failed attempt sending a message to mistyped contact mail address does not deploy exclamation mark icon

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#1846]
- Operating System (Linux/Mac/Windows/iOS/Android):
Windows 8.1 Pro.

- Delta Chat Version:
1.12.0.

- Expected behavior:
An exclamation mark should appear next to the name of a contact who has been added with a mistyped (non-existing) mail address after a message could not be sent.

- Actual behavior:
An exclamation mark does not appear next to the name of a contact who has been added with a mistyped (non-existing) mail address after a message could not be sent.

- Steps to reproduce the problem:
-- Manually add a contact that does not exist, e.g. "sdklfjs@sdklfjs.net". (Note: The domain must not exist to reproduce the issue!)
-- Send a message to this fake contact.

- Screenshots:
![grafik](https://user-images.githubusercontent.com/51095533/89574083-de1f2d80-d82b-11ea-8061-9e87439412f6.png)
(Note the next contact below in this list. The difference is that an error message is received instantly from the mail system because the domain does not exist.)

- Logs:
N/A.

**Comment by Simon-Laux** [comment]
is this behaviour already on android or iOS? otherwise this is a feature request

**Comment by gerryfrancis** [comment]
@Simon-Laux Why do you think it was a feature request? The red sign indicating that the message could not be sent is missing on the first of the two contacts in the contact list:

![grafik](https://user-images.githubusercontent.com/51095533/89613909-9b893f80-d883-11ea-80f1-108c1f793e77.png)

The prior screenshot shows the green bubble with a circle that the message has not been sent, yet, but this is wrong, too. When I change the view and come back to this later on, it says "COULD NOT SEND MESSAGE", which is why I have filed another issue, https://github.com/deltachat/deltachat-desktop/issues/1845 .

**Comment by Simon-Laux** [comment]
that is the chat-list not the contact-list now it makes sense

**Comment by gerryfrancis** [comment]
@Simon-Laux Ah, thanks! ;)

**Comment by Jikstra** [comment]
Should be fixed by https://github.com/deltachat/deltachat-core-rust/pull/2126
