### ISSUE TITLE
Changing contact name does not refresh views

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#1850]
Current master-desktop/node/core: when changing the profile name of a contact & clicking  ok, the chatview does not refresh with the new name.  Selecting a different chat fixes the problem.  So the name is updated but a redraw event is missing, it seems.

**Comment by Jikstra** [comment]
Can't reproduce on current master.

![no-bug](https://user-images.githubusercontent.com/34889164/89743940-4c702400-daa8-11ea-834e-3e7cda10be88.gif)

**Comment by gerryfrancis** [comment]
@Jikstra I think @hpk42 means the sentence "Es ist in Ordnung, [...]". The name in there should refresh to "abc", but it does not in your video either.

**Comment by Jikstra** [comment]
Aaaaah, you also reported some of them. Not really sure if I want to tackle those bugs now. We need to redraw everything, which is expensive or need to be super picky about what to force rerender, which can cause many bugs again.

**Comment by gerryfrancis** [comment]
@Jikstra In this case, maybe the chat overview (on the right) could be redrawn after renaming a contact (after click on OK) only when a) this contact is selected, and b) the chat overview does not include any messages? (That would include if all past messages were deleted before, too.)

**Comment by hpk42** [comment]
@jikstra are you saying that it's too expensive to force a redraw after
a user hit the "OK" button after editing the name?  Can't imagine this. 
Before changing the name was updating things constantly while typing IIRC. 
So it should be possible to now get a single redraw on OK.

**Comment by Jikstra** [comment]
It's not so much about redrawing, it's about refechting the same state

**Comment by Simon-Laux** [comment]
rerendering the chatview?

**Comment by Jikstra** [comment]
We can make this specific bubble rerender on group name change.

**Comment by gerryfrancis** [comment]
> We can make this specific bubble rerender on group name change.

@Jikstra Great, that is how I have meant.
