### ISSUE TITLE
indicator for disappearing messages missing

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1855]
if disappearing messages are enabled for a chat, no indication about this state is shown if the "enabled" message is out of view.

i suggest to indicate the state by a small icon beside the chat title (atop of the chat) - this is the place that also android and ios are using for an indicator-icon, we should also use the same icon as on android/ios, a small stopwatch.

that should be pretty easy to do and would be already really helpful and does not require new api or so.

(if the icon is already in master, please just close, i am referring to 1.12.0 from the download-page)

**Comment by Simon-Laux** [comment]
android code for reference:
```java
boolean isEphemeral = dcContext.getChatEphemeralTimer(chatId) != 0;
ephemeralIcon.setVisibility((showAddInfo && isEphemeral)? View.VISIBLE : View.GONE);
```
I was unable to find the stopwatch icon in the android sources in a quick search.

Should it only be displayed for the selected chat or also in the chat list?

**Comment by r10s** [comment]
i think, it is sufficient to show it in the title. 

wrt icon: the icon is also available in any size and color at https://romannurik.github.io/AndroidAssetStudio/icons-generic.html#source.type=clipart&source.clipart=timer&source.space.trim=1&source.space.pad=0&size=111&padding=8&color=rgb(158%2C%20158%2C%20158)&name=ic_timer3 - maybe that tool also allows svg download somehow.

**Comment by Simon-Laux** [comment]
looks like the source of these icons is https://github.com/google/material-design-icons
https://github.com/google/material-design-icons/tree/master/src/image/timer/
https://github.com/google/material-design-icons/blob/master/src/image/timer/materialicons/24px.svg

And I just found out that we already have this image, but saved under a different name https://github.com/deltachat/deltachat-desktop/blob/master/images/clock.svg :laughing:

**Comment by TheOtherDoctor** [comment]
Nice new feature. What I find slightly suboptimal yet is that when I click on the clock icon, it opens the user profile screen. Opening the disappearing messages config dialog directly would be more intuitive...

**Comment by Simon-Laux** [comment]
at the moment its an indicator, not a button. But nice idea, if you want you can open an issue for this enhancement.
