### ISSUE TITLE
Crash when user tries to open "Settings" after first (initial) profile setup

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#1856]
- Operating System (Linux/Mac/Windows/iOS/Android):
Windows 8.1 Pro.

- Delta Chat Version:
1.13.0 RC1.

- Expected behavior:
The user can access the "Settings" window.

- Actual behavior:
The user cannot access the "Settings" window. (Delta Chat crashes when "Settings" is selected.) When the application is closed and rerun again, "Settings" can be accessed normally.

- Steps to reproduce the problem:
-- Install Delta Chat from scratch.
-- Run Delta Chat and set up a new profile.
-- Open "Settings" from the three-dot menu.

- Screenshots:
![grafik](https://user-images.githubusercontent.com/51095533/90334946-950c6d80-dfd1-11ea-9076-259e0eba2d5d.png)

- Logs:
N/A, nothing unusual has been logged.

**Comment by Jikstra** [comment]
Should be fixed with https://github.com/deltachat/deltachat-desktop/pull/1869

**Comment by gerryfrancis** [comment]
@Jikstra Great, thank you so much, I will test the next release when it is available. :+1:

**Comment by gerryfrancis** [comment]
Yeah, it is fixed in version 1.13.0! Thanks a lot!
