### ISSUE TITLE
Subject not localized when only attachment (image or document) is sent

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#1861]
- Operating System (Linux/Mac/Windows/iOS/Android):
Windows 8.1 Pro.

- Delta Chat Version:
1.13.0 RC1.

- Expected behavior:
When sending an attachment (image or document file) only, the subject is localized in the selected language. (In German, this would be "Nachricht von [Absender]".)

- Actual behavior:
When sending an attachment (image or document file) only, the subject is not localized in the selected language. (It stays with "Message from [sender]".)

- Steps to reproduce the problem:
-- Send a picture to a contact of your choice.

- Screenshots:
N/A.

- Logs:
N/A.

- Remarks:
In the latest Android release, the subject is localized.

**Comment by Simon-Laux** [comment]
solving #1941 could solve this

**Comment by r10s** [comment]
> solving #1941 could solve this

pretty sure it is solved by that, i just had a look where core takes the string from: core uses string from DC_STR_SUBJECT_FOR_NEW_CONTACT that was missing in desktion before #1941 was merged.
