### ISSUE TITLE
Importing keys: cannot select keys to import

### ISSUE THREAD

**Issue by micah** [deltachat/deltachat-desktop#1863]
- Operating System (Linux/Mac/Windows/iOS/Android): Ubuntu 20.04
- Delta Chat Version: 1.12.0
- Expected behavior: I should be able to select the keys to import.
- Actual behavior: When I am provided the file selection dialog, I can see my keys in my home directory, they are readable by me, but they are 'greyed out', so I cannot select them. 
- Steps to reproduce the problem: Settings->Import Secret Keys
- Screenshots: I can not figure out how to add an image to an issue in github. I'm not using a window manager that has 'drag and drop', and I see no file picker here :(

**Comment by gerryfrancis** [comment]
@micah Thank you for reporting. My system does not run Ubuntu, but AFAIK not the key(s) is/are to be selected, but the folder in which the key(s) is/are stored. Could you check if your problem is solved by selecting the folder, and report back, please? Thanks in advance.

**Comment by Jikstra** [comment]
Thanks for reporting, for uploading files without drag&drop:
![Screenshot_20200827_125907](https://user-images.githubusercontent.com/34889164/91434333-f4d20680-e864-11ea-8c33-ec5d699d6c27.png)

**Comment by micah** [comment]
@gerryfrancis indeed, that looks like it is the issue. If I select the folder where the keys are, then I get what #1792 is to solve.

**Comment by micah** [comment]
@Jikstra Yeah, but as I said in the original message, I am using a tiling window manager (awesome), that does not have 'drag and drop', nor does it have an icon system where you can copy and paste images. 

It seems the only way to do this is to host the image elsewhere, and link to it here.

After an absurd amount of time, I found I could do this: 

`cat 2020-08-26-195324_1129x827_scrot.png | xclip -selection clipboard -t image/png -i`

![image](https://user-images.githubusercontent.com/2832/91446135-8f7f1500-e866-11ea-80f1-3e8dc7052f71.png)

**Comment by Simon-Laux** [comment]
@micah just click on the section jikstra showed. it should open the file select dialog.

**Comment by micah** [comment]
> @micah just click on the section jikstra showed. it should open the file select dialog.

Wow, ok, yeah that does work. Great user interface github :D

**Comment by lesavik** [comment]
Have the same issue on PopOS. I can only try to import a directory, which has no sense. I should be able to import a text file. Maybe the problem is with an import type.

I tried to find functions that import files. I found `onClickImportBackup` function. It has argument `properties` with attribute `openFile`.
```typescript
const ImportButton = function ImportButton(_props: any) {
  const tx = useTranslationFunction()

  async function onClickImportBackup() {
    const file = await runtime.showOpenFileDialog({
      title: tx('import_backup_title'),
      properties: ['openFile'],
      filters: [{ name: '.tar or .bak', extensions: ['tar', 'bak'] }],
      defaultPath: runtime.getAppPath('downloads'),
    })
```
If my assumption correct, then the function that imports keys should have the same argument with the same attribute.
[Settings-ManageKeys.tsx](https://github.com/deltachat/deltachat-desktop/blob/master/src/renderer/components/dialogs/Settings-ManageKeys.tsx)
```typescript

async function onKeysImport() {
  const tx = window.static_translate

  const opts: OpenDialogOptions = {
    title: tx('pref_managekeys_import_secret_keys'),
    defaultPath: runtime.getAppPath('downloads'),
    properties: ['openDirectory'],
  }
```

**Comment by Jikstra** [comment]
> Have the same issue on PopOS. I can only try to import a directory, which has no sense. I should be able to import a text file. Maybe the problem is with an import type.

The api expects a specific format in this folder which is hella annoying but currently how it is. So having a directory makes sense (to some degree). But yes it's confusing and not good ux.
