### ISSUE TITLE
outgoing info messages don't have a visible status

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1867]
change of group state (member add/remove, change avatar img, name) have no status indication so you can't tell when they are pending. (you can see the status in the chatlist if its the last message)
I suggest somekind of border animation for pending and a red border for failed, but maybe we should just add the icons the user already knows (the one for error and the one for pending).

**Comment by gerryfrancis** [comment]
Icons are fine, maybe it is possible to enlarge them a little bit for users having high screen resolutions. Just my two cents.

**Comment by r10s** [comment]
> I suggest somekind of border animation for pending and a red border for failed, but maybe we should just add the icons the user already knows (the one for error and the one for pending).

i would use the ones the user already knows or a subset of that - but not a new ui-element. maybe just use the same "delivery bar" as for the other messages, maybe without time/checkmarks.

**Comment by Simon-Laux** [comment]
![2020-11-03_22-01](https://user-images.githubusercontent.com/18725968/98040724-04e80280-1e21-11eb-982e-7d5540f9c79e.png)
In essence its only sending/pending and error that needs to be shown, I'm adding this to the message-refactor-add-qoutes-pr
