### ISSUE TITLE
No way to download audio? (in gallery)

### ISSUE THREAD

**Issue by rrthomas** [deltachat/deltachat-desktop#1874]
- Operating System (Linux/Mac/Windows/iOS/Android): Ubuntu
- Delta Chat Version: 1.12.0
- Expected behavior: Should have some way to download audio attachments
- Actual behavior: Can't find a way. Images have an obvious download button; and I can download audio from the Android app.

**Comment by Simon-Laux** [comment]
ah you mean in the gallery view? right there isn't a way to download audio files in this way.

**Comment by rrthomas** [comment]
That's right, @Simon-Laux. Sorry I wasn't more precise!

**Comment by rrthomas** [comment]
Thanks for fixing this issue! I look forward to getting the next version.
