### ISSUE TITLE
"Remove account" should read "Delete account"

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1880]
"remove" connotes take away and set aside (but kept in existence).

fortunately, "Delete account" is also already translated.

so, possibly untranslated "Delete account" and also `a11y_remove_account_btn_label` should be replaced by `delete_account` both. 

just came over this bit because of https://support.delta.chat/t/testing-upcoming-v1-13-0-release/1199/7 :)

**Comment by r10s** [comment]
is `a11y_remove_account_btn_label` also replaced or is it not used at all?

**Comment by Jikstra** [comment]
I didn't find it in the codebase

**Comment by r10s** [comment]
thanks for checking, then i remove it from the translation file. if that makes problems later, just use `delete_account` :)
