### ISSUE TITLE
crashing wile sending file

### ISSUE THREAD

**Issue by sinakeivansaraei** [deltachat/deltachat-desktop#1891]
- Operating System (Linux/Mac/Windows/iOS/Android):
- Delta Chat Version: Windows version 1.12.0
- Expected behavior: sending file correctly
- Actual behavior: it is crashing while sending a file
- Steps to reproduce the problem:
- Screenshots:
- Logs:

**Comment by Simon-Laux** [comment]
**please reopen if this still happens in newer versions**, also it works for me on windows so we need more information like windows version, filetype, filesize and the log before the crash  or at least some steps that help us to reproduce this error.

You can download the new versions on https://delta.chat/en/download
