### ISSUE TITLE
markdown link at end of line eats linebreak

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1893]
```
have a look at [foobar.chat](https://foobar.chat)
the best link ever!
```

renders to 
```
have a look at foobar.chatthe best link ever!
```

the link as such is working.

**Comment by Simon-Laux** [comment]
found another bug:
```[delta.chat](https://delta.chat)[delta.chat](https://delta.chat)```
gets collapsed to just ```delta.chat```
