### ISSUE TITLE
improve button order in markdown-link confirmation

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1894]
the current dialog looks like:

![Screen Shot 2020-09-26 at 23 53 59](https://user-images.githubusercontent.com/9800740/94350917-a8d8d400-0053-11eb-8c7b-eecafd827301.png)

i suggest to move the "copy" or "copy link" button to the left side and add the normal "cancel" and "ok" or maybe "open" to the right:

![Screen Shot 2020-09-26 at 23 53 59-2](https://user-images.githubusercontent.com/9800740/94351004-9743fc00-0054-11eb-9be2-8c369add3f1b.png)

ftr: in general, i am not a fan of this dialogs at all. showing the clickable link directly (as in the past) seems to be better. but this is another issue/discussion :)

**Comment by r10s** [comment]
> The problem with that is that some users can start an outrage than: delta chat is un-secure because I clicked on a phishing link

i totally agree, therefore i would strike the "Trust all labeled links" dialog completely.

my point is that i would try to avoid using labeled links at all (where we have that under control):

eg. the desktop device messages read in the past eg.:

... Full changelog: https://delta.chat/f32/ ...

clicking on the link **opens the link in the browser directly**. newer device messages use "labeled links" as:

... [Full changelog]() ...

clicking on the link **opens the dialog shown above, the user has to understand that, may do some action, and _then_ the link is opened in the browser** - i see that as a ux degradation.

i know, markdown links may be generated in the core when converting html mails, then, the dialog may make some sense, not sure, though, esp. when the link is pretty long.

**Comment by Simon-Laux** [comment]
> esp. when the link is pretty long.

Or when it contains punycode or look-alike characters.

I agree that we should not use the dialog for labeled links that **we** provided (we know its safe to click them).
So I see two possibilities here:
- Implement some kind of whitelist for links that we provide. (maybe even something like - all links in the device chat)
- Avoid the problem and get a way to create the shortcut links without asking our sysadmins. (that's the solution that you proposed)

**Comment by r10s** [comment]
i would even be fine doing 2. _without_ shortcut links :) we never used these special links eg. on android the links to our blog or so are not that long :)

but, it goes offtopic, i opened this issue only because of the button order :)

**Comment by Simon-Laux** [comment]
> but, it goes offtopic, i opened this issue only because of the button order :)

then next time feel free to open two issues instead of doing 1,5 issues in one issue :wink: 

> ftr: in general, i am not a fan of this dialogs at all. showing the clickable link directly (as in the past) seems to be better. but this is another issue/discussion :)

>  android the links to our blog or so are not that long.

the changelog links to github are annoyingly long:
```
https://github.com/deltachat/deltachat-desktop/blob/master/CHANGELOG.md#1130---2020-10-01
vs.
https://delta.chat/en/2020-11-05-android-update
```
