### ISSUE TITLE
Remove update suggestion?

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1895]
With the new core this is handled by the core. (even though the update message is sent after a year instead of 90 days, so should we keep both?)

https://github.com/deltachat/deltachat-core-rust/pull/1901

**Comment by r10s** [comment]
i would remove it and rely on core.

in practice, the update warning will a bit faster than a year as it takes the last provider-db-update as reference - and this is not updated every time.

what is used as reference date for desktop?

**Comment by Simon-Laux** [comment]
> what is used as reference date for desktop?

build time of the desktop

**Comment by Simon-Laux** [comment]
one year is to long for now. Let's keep both for now and change it when we have less frequent releases.
