### ISSUE TITLE
Real Portable Windows Version using portableapps.com

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1907]
Problem: current portable build out of electron builder is not 100% portable.
Solution: making a portable version using the tools from https://portableapps.com/development and also publishing on that platform.

original discussion: https://github.com/deltachat/deltachat-desktop/issues/1478

**Comment by Darthagnon** [comment]
A possible (more modern?) solution could be the [Portapps launcher](https://portapps.io/) - I've noticed it is used extensively with other Electron-based projects.

**Comment by TheAntHeap** [comment]
Windows "portable" version creates folders in \AppData\Roaming\ . Can it be prevented ?

**Comment by Darthagnon** [comment]
> Windows "portable" version creates folders in \AppData\Roaming\ . Can it be prevented ?

Yes, by using a custom launcher like Portapps. Deltachat uses Electron, which is a custom build of Chromium. Chromium can be run completely portably using [chrlauncher](https://www.henrypp.org/product/chrlauncher), which supplies custom launch arguments. I don't know if Deltachat supports custom launch arguments.

**Comment by Simon-Laux** [comment]
I'll close this issue because of lack of interest, no body worked on it, moving it to project resurrection, we can reopen it if someone wants to pick this issue up again.

not "100%" portable was meant as in "stores data in the system outside of the portable delta chat data directory", a portable apps app wouldn't do that AFAIK.

<img width="1390" alt="Bildschirmfoto 2024-07-31 um 23 41 21" src="https://github.com/user-attachments/assets/330bccc8-905b-436f-8ac6-79d50b95392d">

green box is expected, red box is not expected
