### ISSUE TITLE
Resend Message

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#191]
When a message couldn't be sent, there's a `Resend Message` menu alternative in the message context menu. See https://github.com/deltachat/deltachat-desktop/pull/190

**Comment by r10s** [comment]
what would you like to do here? just send the same message a second time (sth. as dc_send_msg(context, chat_id, dc_get_msg(...))? 
in the medium term, we could also add a resend function to the core, however, the best would be if the core just tries harder as it does currently (currently, it gives up after 3 retries _with network_, this is not sufficient on flaky networks and will probably be increased significally (older versions of deltachat-core did _never_ give up - which however, could result in massive traffic if eg. an attachment is just too large)

**Comment by ralphtheninja** [comment]
> what would you like to do here? just send the same message a second time (sth. as dc_send_msg(context, chat_id, dc_get_msg(...))?

I haven't really thought about it. Just created the issue for discussion. I guess the message is in the database with a `msg_id` etc? It would be nice if it was a "simple" operation that could just be re-tried with a command, e.g. `dc_msg_retry_send()` or something.

**Comment by karissa** [comment]
what is the progress here? is core handling resending of messages now?

**Comment by hpk42** [comment]
On Tue, Dec 18, 2018 at 17:09 -0800, Karissa McKelvey wrote:
> what is the progress here? is core handling resending of messages now?

yes, core is handling re-sending and there is no API for manually triggering 
a resend.  After 2-3 weeks (IIRC) the message is considered unsendable
and can not be resend currently.

**Comment by karissa** [comment]
cool, we'll call this closed then
