### ISSUE TITLE
use context-menu also for info-messages

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1915]
when right-clicking an info-message as "member added", the message-context-menu is skipped and the message-info is shown directly.  
i assume, this is because this is the only option that would be available in the context menu.

however, this is unexpected. a right click on an object should just open the context-menu unconditionally, whenever there is a possible action. if there is only one entry in the context-menu, this is not a problem.

**Comment by Simon-Laux** [comment]
> i assume, this is because this is the only option that would be available in the context menu.

It's because the currently used context menu needs a hack to open so no-one likes to use it.

This will change with #1790. I'll write it on my list of things we do with the new menu.

Also there is https://github.com/deltachat/deltachat-desktop/issues/1866 which also should be fixed

**Comment by r10s** [comment]
thanks for clarifying. if it is not easy to do, for sure, this issue has no priority at all.
