### ISSUE TITLE
Logout button and currently logged in user floats over each other

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#193]
![screenshot from 2018-10-20 18-39-09](https://user-images.githubusercontent.com/308049/47258163-8c12e980-d497-11e8-8228-7f02abef4f5a.png)

Maybe move the currently logged in username elsewhere? Maybe to window title? Email addresses can be quite long as well.

This goes away if the window is stretched to over 650 pixels wide.

**Comment by sbadux** [comment]
Same for the Members string at the end

![image](https://user-images.githubusercontent.com/28478027/47260115-4402bf80-d4b5-11e8-90d2-a7af384997bc.png)

I think you can put the account in the menu. Maybe Settings -> Accounts ->  my@account.com. So you can list there the others account. 
With this menu I think you can also add a button "Add a new account" and thus remove the "home" screen where you have to click on the account. Just login with the last used account.

**Comment by ralphtheninja** [comment]
> Same for the Members string at the end

@sbadux Please create an issue for this.

**Comment by ralphtheninja** [comment]
Logout button was moved to hamburger menu, so closing this issue.

**Comment by r10s** [comment]
great, also wanted to suggest to move the logout-button somewhere else so that it is not that "in your face" (people should just use the app, not logout :)

**Comment by ralphtheninja** [comment]
> people should just use the app, not logout :)

:smile:
