### ISSUE TITLE
Email address in lastChats isn't cleared after account deletion.

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1931]

**Comment by Jikstra** [comment]
What is lastChats?

**Comment by Simon-Laux** [comment]
cat ~/.config/DeltaChat/config.json | jq .lastChats

**Comment by Simon-Laux** [comment]
maybe we should revisit account specific config and store this value inside of the account db? or at-least the account folder?

Also this data (which chat was last opened) is not too important so losing it is no problem.

**Comment by Simon-Laux** [comment]
https://github.com/deltachat/deltachat-desktop/pull/2342 solves this for the most part, with it only account ids are stored, not the email addresses anymore, so it can only be told that another account existed, but not which email address it had.
