### ISSUE TITLE
E-mail addresses in messages should be clickable and open add new contact dialog

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#1937]

**Comment by Simon-Laux** [comment]
i assume the same goes for `mailto:` links

**Comment by Simon-Laux** [comment]
If we do the same for #1763, they both could be implemented together in one pr.

**Comment by Jikstra** [comment]
Maybe just opening the view profile dialog is enough/better?

**Comment by Simon-Laux** [comment]
solved with #2404
