### ISSUE TITLE
Login/Configuration error still useless

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1942]
![2020-10-27_01-35](https://user-images.githubusercontent.com/18725968/97243140-f0d74c00-17f5-11eb-8f8c-5db9a9a6d5be.png)
Not sure if this is a core or a desktop thing. I suspect its an core issue.
This shows the result from core 1.47
(the error is the thing beneath the explanation text that we added because of the uselessness-nature of the 1.46 configure error)

The log has nothing helpful either:
```
18.7s [D]core/event: DC_EVENT_CONFIGURE_PROGRESS 310 
18.7s [D]main/deltachat: sendToRenderer: DC_EVENT_CONFIGURE_PROGRESS [ 310, '' ]
18.7s [D]core/event: DC_EVENT_CONFIGURE_PROGRESS 500 
18.7s [D]main/deltachat: sendToRenderer: DC_EVENT_CONFIGURE_PROGRESS [ 500, '' ]
18.7s [D]core/event: DC_EVENT_CONFIGURE_PROGRESS 550 
18.7s [D]main/deltachat: sendToRenderer: DC_EVENT_CONFIGURE_PROGRESS [ 550, '' ]
18.7s [D]core/event: DC_EVENT_CONFIGURE_PROGRESS 600 
18.7s [D]main/deltachat: sendToRenderer: DC_EVENT_CONFIGURE_PROGRESS [ 600, '' ]
18.7s [D]core/event: DC_EVENT_CONFIGURE_PROGRESS 0 Error:

“”
18.7s [D]main/deltachat: sendToRenderer: DC_EVENT_CONFIGURE_PROGRESS [ 0, 'Error:\n\n“”' ]
```

### Expected (With core 1.45):
![2020-10-27_01-58](https://user-images.githubusercontent.com/18725968/97243985-c5556100-17f7-11eb-9c17-ae7780facb3f.png)

```
261.5s [D]main/deltachat: sendToRenderer: DC_EVENT_WARNING [
  0,
  'src/imap/mod.rs:309: Login als "***" nicht möglich. ' +
    'Bitte E-Mail Adresse und Passwort auf Richtigkeit überprüfen. (no ' +
    'response: code: None, info: Some("[AUTHENTICATIONFAILED] Authentication ' +
    'failed."))'
]
261.5s [E]core/event: DC_EVENT_ERROR_NETWORK 0 Login als "***" nicht möglich. Bitte E-Mail Adresse und Passwort auf Richtigkeit überprüfen.
```

**Comment by r10s** [comment]
might be already fixed on current master with https://github.com/deltachat/deltachat-core-rust/issues/2024

**Comment by Simon-Laux** [comment]
so current core shows an but its prefixed with `Error: Error:`:
```
Error: Error:↵↵“Could not find your mail server.↵↵Please check your internet connection.
```

So now its still pretty but at-least it works.

**Comment by r10s** [comment]
does the double Error: prefix come from core? so it is a direct result of DC_EVENT_CONFIGURE_PROGRESS(data1=0)? then, of possible, this has to be fixed in core (might be tricky as we pass through some error strings from underlaying libs).

in general, UIs should not prefix anything to the error string coming from core. instread, things should be fixed/adapted in core. there were longer discussions that on that, on irc and also on [several issues/pr](https://github.com/deltachat/deltachat-core-rust/issues?q=configuration+error) - however, iirc, that was the outcome :)

**Comment by Simon-Laux** [comment]
the double error prefix is a bug of how desktops ipc system currently handles errors.
Not all errors come from `DC_EVENT_CONFIGURE_PROGRESS`... actually currently it takes the error from the promise reject-cause. and the ipc currently adds another error.
