### ISSUE TITLE
Search - select archived chat doesn't switch view

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1949]
When I select an archived chat and exit the search I'm not switched into the archived view so the chat does not appear in the chatlist.
Also occurs when opening an archived chat from the mutual-chats list in the profile view. 

A solution could be to switch the show archived stated var inside of the chatlist on chat selection.

**Comment by Jikstra** [comment]
Hmm I don't really now what a good ux would be for this issue. Switching to archived chats when selecting an archived chat feels weird, unarchiving it when we select it in the search seems weird to me too.

**Comment by Simon-Laux** [comment]
> unarchiving it when we select it in the search seems weird to me too

Who would propose something like that? :confused:

**Comment by Simon-Laux** [comment]
Don't close issues that are not completely fixed yet
