### ISSUE TITLE
Tweaks to Autocrypt Key Transfer

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#195]
When starting the key transfer, the same message is used when initiating the key transfer and also when typing in the code on the other device, e.g.:

Perhaps we should tweak this a bit

![screenshot from 2018-10-20 22-23-08](https://user-images.githubusercontent.com/308049/47260209-099a2200-d4b7-11e8-9611-e67b59d53be8.png)

![screenshot from 2018-10-20 22-22-52](https://user-images.githubusercontent.com/308049/47260211-0dc63f80-d4b7-11e8-93e6-bbf27b7565b4.png)

Also the `'Transfer Key'` button should be moved a bit.

**Comment by ralphtheninja** [comment]
Agreed. And the second screen on the other device should have a very brief text. "Please enter bla bla".

**Comment by Jikstra** [comment]
Yup, and instead of having some 'Transfer key' button, an "OK" button would be enough.
