### ISSUE TITLE
Black text on black background

### ISSUE THREAD

**Issue by sbadux** [deltachat/deltachat-desktop#196]
The menu texts are black on a black background. This happens in Ubuntu 18.10 and it may be related to the Ubuntu theme. I've the default Ubuntu theme so I think this should be fixed if possible.

![image](https://user-images.githubusercontent.com/28478027/47260199-e8393600-d4b6-11e8-858b-8067e85c0523.png)

EDIT: I'm talking about the black bar under the Title Bar. In this bar there are the "hidden" menu buttons

**Comment by ralphtheninja** [comment]
Hmm interesting, is this only due to Ubuntu 18.10?

**Comment by sbadux** [comment]
I don't know because I've never used DeltaChat Desktop v1.5 on Ubuntu 18.04. Today I've upgraded to 18.10 and THEN installed the DC v.1.5. If you haven't done any change that could have caused this problem, I can suppose that it's related to the new Yaru theme https://community.ubuntu.com/c/desktop/theme-refresh

**Comment by Jikstra** [comment]
This is because of your GTK theme but I remeber that there were very similiar problems with atom editor and electron not changing menu colors. I'm not sure, but i think it was an GTK2/GTK3 problem. @ralphtheninja  are we using an electron framework which is using GTK2 or 3?
https://github.com/electron/electron/issues/2927

**Comment by ralphtheninja** [comment]
We use electron v2, have no idea about gtk.

**Comment by Jikstra** [comment]
It's possible that this is fixed as soon as we switch to electron v3.

**Comment by Jikstra** [comment]
@sbadux can you test out latest master with electron v3? Don't have a ubuntu running :/ For me dark gtk themes work, but they also worked with electron v2.

**Comment by sbadux** [comment]
> @sbadux can you test out latest master with electron v3? Don't have a ubuntu running :/ For me dark gtk themes work, but they also worked with electron v2.

I can test it, but I don't know how to do the test. I'm not a developer so I really don't know what I should do. Can you please explain me how to do this test?

**Comment by r10s** [comment]
on ubuntu 18.04 with standard theme the menu looks okay

**Comment by Jikstra** [comment]
> I can test it, but I don't know how to do the test. I'm not a developer so I really don't know what I should do. Can you please explain me how to do this test?

No problem, we are currently thinking of doing a new release with binaries today/tomorrow, so it's a lot easier to install than trying to compile/build it on your own which also isn't hard but maybe harder :D

**Comment by Jikstra** [comment]
@r10s okay you're using the "old" theme. Just to show the difference:
https://i.redd.it/cljbq1bqsqt11.png

Source: https://www.reddit.com/r/linux/comments/9qe0yn/ubuntu_with_and_without_yaru_communitheme_is/

**Comment by ralphtheninja** [comment]
Missing a lot of German translations ;)

**Comment by ralphtheninja** [comment]
@sbadux You can try a new release here https://github.com/deltachat/deltachat-desktop/releases/tag/v1.6.0 , hopefully switching to electron 3 fixes your problem

**Comment by sbadux** [comment]
Thanks a lot for the new .deb :-)
The bar is still back, but I noticed that it turns black only when the windows has the focus. The menus are readable if I click on the desktop o focus another window.

https://youtu.be/0J4D6tu4ZDs

**Comment by ralphtheninja** [comment]
I'm wondering if this is related:

https://github.com/deltachat/deltachat-desktop/blob/63119bb0e01cd24bac2bf3d78e17efdb8ae5c3cb/src/main/windows/main.js#L34

**Comment by Jikstra** [comment]
I'm not really through all the info, but maybe this helps:
https://github.com/electron/electron/issues/13381
https://github.com/ubuntu/yaru/issues/715

It's possible that this is an electron or yaru bug.

**Comment by ralphtheninja** [comment]
Just updated to Ubuntu 18.10 and I can reproduce when using the Yaru theme. However, I have no idea of how to fix it. The `darkTheme` property doesn't make a difference.

**Comment by karissa** [comment]
On the latest release, let us know if you still see this bug @sbadux . I think we are going to retire it though in favor of more pressing fixes at the moment
