### ISSUE TITLE
Can we decrease unused var check to warning?

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1965]
at the moment it makes a error that means the typescript build fails, this breaks the fast-iteration workflow.

So maybe there is a way to reduce it to a warning so its shown but not mandatory to fix immediately.
Or create another script that just checks it and call it lint or something like that.

**Comment by Jikstra** [comment]
Yup it's annoying. Maybe we can just turn it off for now and have a small script in the ci which turns this setting on? So we see on the ci if unused variables are around.
