### ISSUE TITLE
multiple Tray icons on Gnome desktop

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1974]
When turning it on and off for a few times, only the menu of the last added one works.
They stay until the app is fully shutdown.
![](https://user-images.githubusercontent.com/18725968/97352058-df904d00-1892-11eb-98c0-ab5bb93fdc1f.png)

related electron issue electron/electron#17622

see #1906

**Comment by Jikstra** [comment]
Hard to fix as electron seems to not care about this issue :/

**Comment by Simon-Laux** [comment]
strangely when packaged as flatpak (https://github.com/flathub/chat.delta.desktop) it works correctly
