### ISSUE TITLE
forwarded-hint is misleading

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1977]
currently, the "forwarded message" title is shown above the name of the sender:

![Screen Shot 2020-11-25 at 00 59 19](https://user-images.githubusercontent.com/9800740/100165072-97784080-2eb9-11eb-9ba7-df51ac4ae4e5.png)

the example above looks as if holger wrote "WTF!!!!" and this message was forwarded by someone.

in fact, holger did not wrote "WTF!!!!" - holger forwarded a message with this text.

so, the two titles should at least be swapped. ~~to make it even clearer, i suggest to strike the name completely - just say "forwarded message" - this is what we are doing on ios/android and what eg. also whatsapp is doing~~ EDIT: we are about to fine-tune that, see below.

**Comment by Simon-Laux** [comment]
> so, the two titles should at least be swapped. to make it even clearer, i suggest to strike the name completely - just say "forwarded message" - this is what we are doing on ios/android and what eg. also whatsapp is doing.

Then who forwarded the message in a group?

We could maybe do something "holger has forwarded this message" or a similar combined thing. or something different like really swapping it and maybe a some subtle ux indication.

**Comment by r10s** [comment]
> Then who forwarded the message in a group?

there is still the avatar, this is enough.

> We could maybe do something "holger has forwarded this message" or a similar combined thing. or something different like really swapping it and maybe a some subtle ux indication.

i would just strike the name and replace it by "Forwarded message", not swap. we are doing this one android since "forever", there were no issues with that.

**Comment by r10s** [comment]
i suggest to target https://github.com/deltachat/deltachat-android/issues/1743 (quoting forwarded message no longer look as beeing forwarded ) when on that as well, **all in all**, i suggest the following:

1. define some unknown_sender grey color, on android we use #99999 for that, that fits well in light mode as well as in dark mode and has a similar brightness as the contact/chat colors (that also do not differ between light and darkmode)

2. when displaying a forwarded message, display the string "Forwarded message"  in unknown_sender grey above the message. do not display the name of the forwarder above the message in groups (there is still the avatar and message-info to get these details)

3. when a quote is displayed, and the quote is a forwarded message, do the same: display "Forwarded message" instead of the forwarder name. bar and string should be in unknown_sender grey. it is a bit unfortunate, that "jump to original" is not yet implemented, however, as for 5. the sender sees exactly the same on composing and this is a cornercase anyway, it is fine. if would vote for simple and unique display across platforms here.

4. when a quote is displayed, and this is not a forwarded message but the author of the quote is unknown, do not display a name/placeholder at all, but use unknown_sender grey for the bar

5. do 3+4 also for quotes in the staging area.
