### ISSUE TITLE
do not word-wrap context menu items

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1978]
if the context menu entries are a bit longer, they are word-breaked. this is quite unusual for menus in general as it is harder for the eyes to get the next entry.

example: german entry "In Zwischenablage kopieren"

**Comment by Simon-Laux** [comment]
> do not word-wrap context menu items

so change "dynamic" height to dynamic "width"? or just change translations for now?

**Comment by Jikstra** [comment]
@Simon-Laux does your context menu code depend on a fixed width?

**Comment by Simon-Laux** [comment]
currently the height is dynamic, but the width is static

**Comment by r10s** [comment]
we could just use the (also already existing) string "Copy" instead of "Copy to clipboard" or "Copy selection" - many context menus also use this short wording.

that might already fix the issue, however, it will pop up again, when there are other longer strings :)

so, in general, yip, the width should grow depending in the content, word-wrapping should be avoided in menus.

but i also want to point out: if this is somehow complicated, we can postpone this issue, it is not the most important thing :)

**Comment by Simon-Laux** [comment]
The logic that needs to be aware of width and size is the positioning logic that makes sure the context menu isn't cut short by the borders. Also with scaling (zoom) I'm not sure how the context menu will behave so its not the easiest thing to change -> static to dynamic width.

**Comment by Jikstra** [comment]
That was what i was thinking of. I guess the only "proper" but time consuming way to solve this is offscreen rendering, getting the sizes and then doing the positioning. So let's just change the wording for now :D

**Comment by r10s** [comment]
> So let's just change the wording for now :D

maybe this is just "good enough" then. i mean there, is exactly one string with the issue in german :)
