### ISSUE TITLE
Electron Security Warning

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#198]
![screenshot from 2018-10-21 04-43-28](https://user-images.githubusercontent.com/308049/47262561-eccc1180-d4eb-11e8-898c-d4736a67a98b.png)

Just something to check out.

--------------------------------------------------

Checklist (from https://electronjs.org/docs/tutorial/security):

- [x] Only load secure content

We're doing `.loadURL()` on `file://` and `main.html` is not loading any remote content.

- [x] Disable the Node.js integration in all renderers that display remote content

We can't do `{ webPreferences: { nodeIntegration: false } }` since we're using `require` directly in `main.html`, but we're not loading any remote content so we should be good?

- [x] Enable context isolation in all renderers that display remote content

- [x] Use `ses.setPermissionRequestHandler()` in all sessions that load remote content

- [x] Do not disable `webSecurity`

- [x] Define a `Content-Security-Policy` and use restrictive rules (i.e. `script-src 'self'`)

- [x] Override and disable `eval`, which allows strings to be executed as code. https://github.com/deltachat/deltachat-desktop/commit/1cf6750c0ce5ac454968c37c547c90c29b708f63

- [x] Do not set `allowRunningInsecureContent` to `true`

- [x] Do not enable experimental features

- [x] Do not use `enableBlinkFeatures`

- [x] `<webview>`: Do not use `allowpopups`

- [x] `<webview>`: Verify options and params

- [x] Disable or limit navigation https://github.com/deltachat/deltachat-desktop/commit/5026b502292d88f2de6217703be3cd24ab68269d

- [x] Disable or limit creation of new windows https://github.com/deltachat/deltachat-desktop/commit/303380568ba75816e055c26fabc058690b7a0567

**Comment by ralphtheninja** [comment]
Several of these points are irrelevant since we're not loading any remote content.

**Comment by ralphtheninja** [comment]
Maybe we should `browserify` the web code in `es5/renderer` so we can get rid of `require` and then set `{ webPreferences: { nodeIntegration: false } }`?

Also, why are we doing `buble` on the main js code? Shouldn't it be enough to buble the code in `src/renderer`?

**Comment by karissa** [comment]
ok did that see #329 and #330
