### ISSUE TITLE
reorder message context menu items

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#1982]
currently, "Copy to clipboard" is the topmost entry, however, i think new "Reply" is more interesting and important and will probably be used more often (context menus usually have some order like that).

therefore, i suggest to move "Copy to clipboard" below "Forward".

order would be:

```
Reply
Reply privately
Forward
---------------------
[Download attachment]
Copy
[Copy link]
Message details
---------------------
Delete
```

this is also nice as the first entry is the one that is executed by a double click  - also a thing, you will see in several context menu.

i've also added some horizontal lines - the main menu have them, so, it seems possible somehow. but also without the lines, i suggest to adapt the order.

**Comment by Simon-Laux** [comment]
> the main menu have them, so, it seems possible somehow.

the main menu uses a different implementation. But as we control. the code for the context menu we can really do anything we want in theory.

when we start with lines we could also think about making delete red IMO... (that you can find it faster)

where would you put `Copy Link` in your order? Top most? because it only appears if you right click on a link.

**Comment by r10s** [comment]
> where would you put Copy Link in your order? Top most? because it only appears if you right click on a link.

i would put it above/below "Copy to clipboard". it is not a command that is used that frequently and i would vote for keeping a recognizable order and internal consistence in this case.

**Comment by Simon-Laux** [comment]
>  it is not a command that is used that frequently

It it is the most used command from the menu for me

**Comment by r10s** [comment]
i refined the suggestion and extended it to the chat-menu at https://github.com/deltachat/deltachat-desktop/pull/1993#pullrequestreview-540369603
