### ISSUE TITLE
Non-emoji get bigger when jumbomoji (big emoji) enabled

### ISSUE THREAD

**Issue by jeifour** [deltachat/deltachat-desktop#1989]
https://github.com/deltachat/deltachat-desktop/blob/69fe2c67d8f44cd6ae7eca9c3fac3676816b49dd/src/renderer/components/message/MessageBody.tsx#L18

I'm no regex expert but I suspect this will recognize messages even when they don't only consist of emoji. See example:

<img width="233" alt="スクリーンショット 2020-11-27 15 05 43" src="https://user-images.githubusercontent.com/3247063/100457281-088a4480-30c2-11eb-9fad-e2fb3bc7875b.png">

**Comment by Simon-Laux** [comment]
not the right regex / code line but thanks for the bug report.

**Comment by Simon-Laux** [comment]
@jeifour which DC version are you using?
