### ISSUE TITLE
Delete Chat confirmation

### ISSUE THREAD

**Issue by sbadux** [deltachat/deltachat-desktop#199]
Hello, again :)
1) The "Delete Chat" button should ask for a confirm before delete the chat.
2) IMHO also the "archive chat" button should ask for a confirm, but a more important question is: how do I restore archived chat?

**Comment by ralphtheninja** [comment]
>     2\. but a more important question is: how do I restore archived chat?

It's fixed now. Can release a new version if you want.

**Comment by ralphtheninja** [comment]
@karissa Any neat ways to do confirmation dialogs in electron? Or should we just pull in `<Dialog>` from `blueprintjs`?

**Comment by karissa** [comment]
renaming this to 'delete chat confirmation' since that's the only issue left here.

we can use the new `dialogs.confirmation` function to do this.
