### ISSUE TITLE
Odd looking Autocrypt Setup Message

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#202]
![screenshot from 2018-10-22 20-48-15](https://user-images.githubusercontent.com/308049/47312168-e64caf80-d63b-11e8-8cf8-1aa5858de002.png)

**Comment by karissa** [comment]
When you open the chat, it should just automatically do the setup message.

**Comment by ralphtheninja** [comment]
> When you open the chat, it should just automatically start the setup message process

This is not in line with how it currently works on android. The chat contains all messages that you have sent to yourself and this can be any kind of message. I think we should just tweak the style of the setup message.

**Comment by karissa** [comment]
Sounds good
