### ISSUE TITLE
misleading error-message

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2020]
when a message is sent out but some address are not working, the message goes into an error state.

on android/ios we're just showing some error symbol instead of the checkmarks in this case, date/time is shown as usual.

on desktop, date/time/checkmark is removed and replaced by a bold text "COULD NOT SEND MESSAGE"

![Screen Shot 2020-12-12 at 21 15 25](https://user-images.githubusercontent.com/9800740/101994072-dda61000-3cbf-11eb-93cf-c15c79102e67.png)

i think, this is misleading, as the message is acutally sent out. the user might try to send it again, with exactly the same error.

i suggest to leave date/time as is and just show the little red "i" - this should be a "clear enough" indication that sth. was going wrong. maybe the "i" can also be clickable and open the message-details (where the full error is shown) (maybe we can also have a tooltip with the error message, however, this is a bit more advanced).

(we had some discussions about a better symbol on android recently, however, i cannot really remember the outcome :)

**Comment by r10s** [comment]
@Hocuri just tweaked the layout on android: https://github.com/deltachat/deltachat-android/pulls , this also contains a screenshot :)

**Comment by Hocuri** [comment]
BTW, "Could not send message" is technically wrong when the message could be sent to 19 of 20 participants of a group, but we still got a non-delivery-notification for this one participant.

**Comment by Simon-Laux** [comment]
Is there a way to find out if it was partially delivered?

**Comment by r10s** [comment]
> Is there a way to find out if it was partially delivered? Otherwise we could do the same as android I suppose.

no, there is no way to find that out, probably there will never be. therefore, yes, just showing a red warning-symbol instead of the checkmark and an option to display the error message, should do the job.

**Comment by Simon-Laux** [comment]
> (we had some discussions about a better symbol on android recently, however, i cannot really remember the outcome :)

using the android symbol does not work, because the status symbols are too small on desktop for it to be more than a red dot:
![2020-12-14_18-10](https://user-images.githubusercontent.com/18725968/102112031-6e532c00-3e37-11eb-888d-a51420a9bfef.png)

So we either need to change the whole css of this area or think of something different.

**Comment by Simon-Laux** [comment]
should the padlock be also shown when there was an error?

**Comment by Simon-Laux** [comment]
for the icon, we could theoretically choose a cross, that looks better IMO, but does not convey the same meaning as the exclamation mark so it might not be suitable:
![2020-12-14_18-55](https://user-images.githubusercontent.com/18725968/102116916-f2a8ad80-3e3d-11eb-9696-70b05cb5c7e8.png)

**Comment by Hocuri** [comment]
We just switched from a cross to an exclamation mark on Android because that's what all other messengers show and it's more clear that there was a failure (a cross could also just be there to close something)

**Comment by r10s** [comment]
> should the padlock be also shown when there was an error? I'd say yes for now.

yip, i would show everything as usual and replace only the checkmark by an error symbol.

wrt the cross, i agree with @Hocuri , that may be confused with a close-symbol. a red exclamation mark is better, making it bolder should do the job: 

![102112031-6e532c00-3e37-11eb-888d-a51420a9bfef](https://user-images.githubusercontent.com/9800740/102139860-b9346a00-3e5e-11eb-96e2-8b23658c1cb4.png)
/me playing around with pixels ;)

or just use the outline exclamation mark from the topmost post, that is also pretty nice imho :)
