### ISSUE TITLE
multiple languages selected accidentally

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2026]
when selecting the _first_ language with the "arabic alphabet", _both items_ are selected afterwards. i assume, this is "arabic" as in the forum there is an [issue that "farsi" is not available](https://support.delta.chat/t/persian-translation/929/5?u=r10s).

<img width="169" alt="Screen Shot 2020-12-19 at 11 28 14" src="https://user-images.githubusercontent.com/9800740/102687143-4f64e900-41ed-11eb-871a-ded3702ee1d1.png">

**Comment by Simon-Laux** [comment]
They both reference the same translation: `ar` so I'll remove one of them.
