### ISSUE TITLE
Android App - Windows Desktop - Sync not working

### ISSUE THREAD

**Issue by michaelshgr** [deltachat/deltachat-desktop#2065]
I've made a backup with my Android app and restored it with Windows Desktop. Works.
But sending a message with an existing chat will not be shown in the android app and vice versa.
The same with new chats.

**Comment by Simon-Laux** [comment]
enable "send to self"/"BCC self" in the settings

**Comment by Simon-Laux** [comment]
if that doesn't help you can reopen this issue
