### ISSUE TITLE
Immediately mark new messages as seen (=read) if chat is open and DC has focus

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-desktop#2069]
- Operating System (Linux/Mac/Windows/iOS/Android): Desktop 
- Delta Chat Version: 1.14.1
- Steps to reproduce the problem: Have a chat open and let messages arrive in the open chat
- Expected behavior: Newly arriving messages should immediately be marked as seen and the chat as noticed
- Actual behavior: No read receipts are sent, the chat is shown to contain unnoticed messages

**Comment by r10s** [comment]
in general, on 1.15.5/mac im getting read receipts if a chat is opened and DC has the focus.

related https://github.com/deltachat/deltachat-desktop/issues/1293

**Comment by Simon-Laux** [comment]
works, im closing this issue
