### ISSUE TITLE
adapt calls to dc_contact_get_first_name()

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2071]
use [`dc_contact_get_display_name()`](https://c.delta.chat/classdc__contact__t.html#accb0ce055f5bcc23dee932a1898a718b) instead.

see https://github.com/deltachat/deltachat-core-rust/pull/2165 and https://github.com/deltachat/deltachat-core-rust/issues/2162 for reasoning.

**Comment by Simon-Laux** [comment]
all calls to that function are inside of deltachat-node, though desktop uses the result at a few places.
