### ISSUE TITLE
Electron11: Color picker is cooler but still weird. Maybe we can make it nicer?

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#2073]

**Comment by Simon-Laux** [comment]
you mean that it is in the top corner? we would need css to translate the color-picker input field to the position of the button.
also it makes sense to tell a bit more in the issue about what the issue is so that others beside us two can understand what it's about too.

**Comment by Jikstra** [comment]
> you mean that it is in the top corner? we would need css to translate the color-picker input field to the position of the button.
> also it makes sense to tell a bit more in the issue about what the issue is so that others beside us two can understand what it's about too.

If ever anybody then us two fixes bugs on here i'm happy to change this :D But if it's just a thing for myself to remember I don't care.

But okay, let's do it. I think it would be nice if we would render the color picker inside of a dialog.
