### ISSUE TITLE
Refactor src/main/window/{index.js,main.js} into src/main/window.js

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#208]
Are we going to need multiple `BrowserWindow` objects? If not, I'd like to refactor this into one file, to make it simpler.

**Comment by karissa** [comment]
@ralphtheninja could use this for the about dialog, instead of using a react dialog? Or anything else that doesn't need a dialog. Maybe also viewing full-size images/videos..

**Comment by ralphtheninja** [comment]
Makes sense!
