### ISSUE TITLE
No notifications.

### ISSUE THREAD

**Issue by markoong** [deltachat/deltachat-desktop#2087]
Since I upgraded from 1.14 to 1.14.1 I don't get new messages notifications anymore.
This is experienced on a flatpak installation.

- Operating System (Linux/Mac/Windows/iOS/Android):
GNU/Linux - KDE 5.14
- Delta Chat Version: 1.14.1
- Expected behavior:
Get system notifications when new messages are received.
- Actual behavior: 
No notifications are shown.
- Steps to reproduce the problem:
- Screenshots:
- Logs:

**Comment by markoong** [comment]
The notifications are *not* shown if the application window is "closed" in the tray, while if the app is only minimized notifications are shown.

**Comment by kd8bxp** [comment]
Notifications only when the client is open, NO notifications when in system tray.
Using the APP Image.
Linux Mint 20.1 64 Bit. 
Mate desktop 1.24.0
Kernel Linux 5.4.0-65-generic x86_64
Delta Chat version 1.14.1

**Comment by Jikstra** [comment]
@markoong @kd8bxp Can you test again with 1.15.5?

**Comment by markoong** [comment]
@Jikstra If you update the flatpak build, I could.

**Comment by kd8bxp** [comment]
@Jikstra 1.15.5 App Image appears to be showing the notifications now.

**Comment by Jikstra** [comment]
Perfect, then let's close this :)
