### ISSUE TITLE
Window title changes from Delta.Chat to DeltaChat (BETA) after login

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#210]
![screenshot from 2018-10-24 17-28-56](https://user-images.githubusercontent.com/308049/47442276-6b59d500-d7b2-11e8-9bfc-c7c10d986f03.png)

![screenshot from 2018-10-24 17-29-06](https://user-images.githubusercontent.com/308049/47442289-70b71f80-d7b2-11e8-9958-702f5fec0c46.png)

**Comment by ralphtheninja** [comment]
Can we agree on what it should be? I personally prefer `DeltaChat`. I don't really know why we use `Delta.Chat` sometimes and sometimes not.

**Comment by ralphtheninja** [comment]
Side note. I'd like to put more information in the window title, maybe the logged in account? Or is that not a kosher thing to do? :smile:

**Comment by karissa** [comment]
@ralphtheninja changing window title is fine! you can do this in windows/main.js, `BrowserWindow` object should have a `setTitle` command or something similar.

**Comment by hpk42** [comment]
i think DeltaChat is the canonical string.  We should try to get 
rid of "Delta.Chat" -- it's hard to write in texts/reports/mails ...
and "deltachat.org" redirects to "delta.chat" FWIW.
Also "deltachat" in google and duckduckgo goes to the
correct domain ...

**Comment by ralphtheninja** [comment]
Also go through translation files.

**Comment by r10s** [comment]
> Side note. I'd like to put more information in the window title, maybe the logged in account? Or is that not a kosher thing to do? smile

i would suggest the same, just sth. as `Delta Chat - user@example.org`.
the title may be shown in many places eg. windows app bar.

i would not put more information to the title nor use square brackets or so. i think this looks too technical and always a bit messy when the title is truncated.
