### ISSUE TITLE
rename "Copy" to "Copy Text"

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#2103]
I confuse it with copy link too often maybe this can help

**Comment by r10s** [comment]
would renaming rename "Copy" to "Copy Message" really help?

i always get the options "Copy selection" and "Copy link" when right-clicking a link - and renaming "Copy selection" to "Copy message" would be misleading.

maybe just replace "Copy selection" by a simple "Copy" would make it easier for the eyes to get the difference (and that the _selection_ is copied when sth. is selected is quite standard)

**Comment by Simon-Laux** [comment]
> i always get the options "Copy selection" and "Copy link" when right-clicking a link

I don't know how you get to that result maybe you made a selection, I get `Copy` and `Copy link`.

In telegram its called `Copy Text` and `Copy Selected Text`.

> (and that the selection is copied when sth. is selected is quite standard)

`Copy` is not shown or greyed out when nothing is selected in most applications.

**Comment by r10s** [comment]
> I don't know how you get to that result maybe you made a selection, I get Copy and Copy link.

i did not made a selection.

on mac, delta chat 1.14.1, just right click a link (the visible selection is not done by the app implicitly and just happens :)

<img width="376" alt="Screen Shot 2021-02-04 at 11 00 48" src="https://user-images.githubusercontent.com/9800740/106876795-65186a00-66d8-11eb-935b-f9b9367de5b2.png">  

but yes, that may be the whole misunderstanding, that on some os, the link is selected on right-click and on other this does not happen.

**Comment by Simon-Laux** [comment]
`copy text` makes more sense then `copy message`, because only the text is copied exclusive attachments

**Comment by Simon-Laux** [comment]
closed by #2174
