### ISSUE TITLE
Add 'Copy image' option for images in gallery and chat-view

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2104]
currently, right-clicking an image _without_ text will offer the context-menu "Copy" - but that does just nothing (it probably copies empty text to the clipboard)

the easiest fix might be will be to hide the "Copy" option from the _image_ context menu and only offer it when right-clicking the message _text_ (this will also fix the maybe unexpected behavior of not copying the image but the text).

maybe more complicated, but better fix would be to actually copy the image data to the clipboard, so that the image can be pasted in other programs.

**Comment by Simon-Laux** [comment]
> maybe more complicated, but better fix would be to actually copy the image data to the clipboard, so that the image can be pasted in other programs.

Voice-messages, attachments and videos can't be easily copied to clipboard (might be too big and I don't know how to do that in electron), we could copy images to clipboard though.
