### ISSUE TITLE
Corrupted letter

### ISSUE THREAD

**Issue by TheLudian** [deltachat/deltachat-desktop#2106]
The letter "i" becomes corrupted when I type "fi" (Ubuntu 20.04.2 LTS).

**Comment by Simon-Laux** [comment]
what's your installed deltachat version?
can you post a screenshot of the corrupted input?

**Comment by Ludan64** [comment]
> what's your installed deltachat version?
> can you post a screenshot of the corrupted input?

![Corrupted letter](https://user-images.githubusercontent.com/78592236/107112314-69bb5a80-685f-11eb-8fff-7afa0580e48b.png)

**Comment by r10s** [comment]
i think, this is a feature of the used font. an `f` followed by an `i` is often shown differently to be not confused with `f` and `l` - fi vs. fl - see https://duckduckgo.com/?q=ligature+fi&iax=images&ia=images

i assume, the same happens elsewhere when the same font is used under similar conditions (kerning enabled etc.)

might be that these ligatures can be disabled system-wise somehow, not sure. but i do not think, there is much Delta Chat can/should do on that.

**Comment by Simon-Laux** [comment]
Right that isn't corruption that is a feature of the used font.
When it is a real problem for you @TheLudian I could look into adding a setting to disable them.

**Comment by Simon-Laux** [comment]
@TheLudian please open a new feature proposal (if possible on https://support.delta.chat (you can use your github to login)) if you want an setting/option to disable font ligatures.
