### ISSUE TITLE
Use dc_contact_get_name to show editable profile name

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop#2109]
Since https://github.com/deltachat/deltachat-core-rust/pull/2206 is merged, `dc_contact_get_name` will return empty string unless user has set contact name manually. `dc_contact_get_display_name` should be used to display the name in the profile, but `dc_contact_get_name` should be used when user starts editing the name.

One option is to show `dc_contact_get_display_name` result in the profile and offer a separate "edit" dialog like Android does. Or show current display name as a placeholder while displaying "name" as a value.

**Comment by r10s** [comment]
> Or show current display name as a placeholder while displaying "name" as a value.

in this case, once should use `dc_contact_get_auth_name()` for the placeholder (see #2225 and docs for reasoning). depending on the layout of the edit dialog, when `dc_contact_get_auth_name()` is an empty string, one could use the email-address or the string "Name" or the empty string as the placeholder.

**Comment by Simon-Laux** [comment]
link2xt already fixed this and we forgot to close this issue:
fix: use display name only as a placeholder in contact profile dialog #2221
