### ISSUE TITLE
[Discussion] Dialogs or own Screens

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#211]
A want to start the discussion about dialogs or screens in an own issue, parts of it got discussed in different other issues or face2face, mailinglists...

The main question is, if we want to use dialogs as a main ui/ux element to show any forms/information which don't fit into the SplittedChatListAndView Component, so everything which isn't the ChatList (list of unarchived chats) and ChatView (Messages in a Chat).

This would affect following ui parts:
- Create a (verfied) Group/Chat
- Display Contacts
- Display Settings
- Init Transfer Key
- Accept Transfer Key
- About
- very probably more...

# There are the two possibilites for the UI which would make sense in my opinion:
#### PROS:
  - Most info which we want to display doesn't need a lot of width, so a smaller overlay over the ChatList&View allows us to display information in a more compact, more "aesthetic" way.
 - No Back button needed, just click away the dialog, very intuitive

#### CONS:
  - We need to write a seperate ScreenController to allow us switch between different "DialogScreens". For example creating a Group needs different Dialogs, one for selecting if we want to create a chat, group, whatever, another one to select the members, one for confirmation... or another example would be settings, where we want to categorize the different properties in own sub menus as it's done on the android side. This is maybe time consuming, maybe not.

#### PROS:
- We're using the signal ui, so this is already baked in into our code. Easy to do, maybe need to update the ScreenController a bit, nothing big.
- We have a lot of space, (80% of the window size currently)

#### CONS:
 - We have too much space and can hardly fill it. We would need to center stuff like embedded contact elements, which would break how we're doing it in other places (use the whole width)
- We need a back button or something to get back to the ChatView, less intuitive
- Even signal is breaking this approach of having own screens for complex user interaction, for example they use a dialog for the settings

##### Group Info
![dialog vs own screen - show group info](https://user-images.githubusercontent.com/34889164/47442792-4ade4a80-d7b3-11e8-8d09-65b2061090a8.png)

##### Settings
![dialog vs own screen - settings](https://user-images.githubusercontent.com/34889164/47442870-6d706380-d7b3-11e8-9f8a-bb59bf97e3d1.png)

##### New Group
![dialog vs own screen - new group](https://user-images.githubusercontent.com/34889164/47442849-62b5ce80-d7b3-11e8-9484-63caa79e8d0c.png)

##### Group Info
![dialog vs own screen - centered content](https://user-images.githubusercontent.com/34889164/47442827-59c4fd00-d7b3-11e8-9f75-8c52b1f924a0.png)

##### Settings
![dialog vs own screen - settings dialog](https://user-images.githubusercontent.com/34889164/47442884-76f9cb80-d7b3-11e8-9cd1-cd1cb936383f.png)

## Please reply in a way which reflects on what to do NOW and what is maybe the better thing to do for the future (once we're rewriting conversations components). We can first implement the logic and do it the simple & fast way, and later do it "properly" with nice ui/ux.

@hpk42 @ralphtheninja @karissa @r10s

**Comment by karissa** [comment]
+1 dialogs

**Comment by ralphtheninja** [comment]
dialogs

**Comment by hpk42** [comment]
dialogs :)

**Comment by r10s** [comment]
and one more time: dialogs :)

**Comment by ralphtheninja** [comment]
Discussion over? :)
