### ISSUE TITLE
Build fails on OpenBSD

### ISSUE THREAD

**Issue by errhammr** [deltachat/deltachat-desktop#2120]
I tried building Delta Chat Desktop from source on OpenBSD because I could not find a precompiled binary. I hoped for the best and feared for the worst.

Checking out the repository from git worked just fine. When I ran `npm install` things started to go wrong. The first sign of trouble was this line of console output:

`(node:2355) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v10.0.0/chromedriver-v10.0.0-openbsd-x64.zip`

However, `npm install` continued to run. Eventually it started compiling Rust dependencies, which also ran into an error and bailed:

```
error: failed to run custom build command for `openssl-sys v0.9.58`

Caused by:
  process didn't exit successfully: `/home/user01/git/deltachat-desktop/node_modules/deltachat-node/deltachat-core-rust/target/release/build/openssl-sys-fcb2e73c0ec85626/build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_OPENBSD_OPENSSL_NO_VENDOR
  X86_64_UNKNOWN_OPENBSD_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset

  --- stderr
  thread 'main' panicked at 'don't know how to configure OpenSSL for x86_64-unknown-openbsd', /home/user01/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.11.0+1.1.1h/src/lib.rs:216:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

That finally caused `npm install` to abort with beautifully colorful error messages.

- Operating System (Linux/Mac/Windows/iOS/Android): OpenBSD 6.8 amd64
- Delta Chat Version: current master (`git describe`: v1.15.1-2-gc6850fe8)
- Expected behavior: I was curious what would happen when building from source on OpenBSD
- Actual behavior: `npm install` aborted with an error
- Steps to reproduce the problem: follow [the readme](https://github.com/deltachat/deltachat-desktop#from-source-) on OpenBSD
- Screenshots:
- Logs: [deltachatdesktop_2021-02-14T12_58_53_229Z-debug.log](https://github.com/deltachat/deltachat-desktop/files/5977744/deltachatdesktop_2021-02-14T12_58_53_229Z-debug.log)

**Comment by Simon-Laux** [comment]
So two issues: 
- it could not find a build of electron for OpenBSD amd64
- and the rust crate for openssl bindings doesn't support OpenBSD: ' don't know how to configure OpenSSL for x86_64-unknown-openbsd', maybe we should post an issue on https://github.com/sfackler/rust-openssl/issues

CC: @link2xt @flub

**Comment by link2xt** [comment]
I don't think Electron runs on OpenBSD at all, there is a related issue for FreeBSD: https://github.com/electron/electron/issues/3797

As for the failed openssl-sys build, there are some environment variables which allow to use OpenSSL instead of default LibreSSL during build: https://github.com/sfackler/rust-openssl/blob/71b6e3f81f9cf0d1772d00577873cc21ee8f86bf/openssl-sys/build/main.rs But even if you build the core, Electron will not build.

**Comment by errhammr** [comment]
I guess this is a wontfix then until someone over at electron figures out how to get things running on OpenBSD? Are there alternative DeltaChat clients for desktop that do not require electron?

**Comment by link2xt** [comment]
> Are there alternative DeltaChat clients for desktop that do not require electron?

There is a thread on the forum: https://support.delta.chat/t/version-without-electron-or-webcrap/1377

**Comment by link2xt** [comment]
> I guess this is a wontfix then until someone over at electron figures out how to get things running on OpenBSD?

There are plans to decouple the frontend from electron to make it possible to run the web app and open it in a browser, like Syncthing. Synthing has OpenBSD downloads, yet it has a web frontend: https://syncthing.net/downloads/

So running this client on OpenBSD could happen sooner, but for now let's close this issue.

**Comment by Jikstra** [comment]
> While you are able to RUN electron apps in FreeBSD you cannot BUILD an app and target BSD like you can with the other OSs. I write an app on a Mac and make a build target Linux or Windows, the same is not true for BSD. In order for a BSD build for an app to be made it needs to be built IN BSD. THAT is the support needed.

Quoting from https://github.com/electron/electron/issues/3797#issuecomment-761082555

It seems as there are electron binaries available, but we are not able to build directly on open/freebsd. So I guess you could use the .deb, extract the dependencies and resources, and then run them with your locally installed electron (as soon as deltachat-node is fixed). It that's a solution.
