### ISSUE TITLE
right click on image mesage opens both context menus

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#2122]
[todo description and image]

**Comment by r10s** [comment]
information an option overload :) what a nice bug :) i can confirm this behavior on macos:

<img width="339" alt="Screen Shot 2021-02-15 at 11 05 29" src="https://user-images.githubusercontent.com/9800740/107932387-ca444900-6f7d-11eb-994a-cb005f890c80.png">
