### ISSUE TITLE
Crash when user tries to open "Settings" after first (initial) profile setup

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#2123]
- Operating System (Linux/Mac/Windows/iOS/Android):
Windows 8.1 Pro.

- Delta Chat Version:
1.15.1.

- Expected behavior:
The user can access the "Settings" window.

- Actual behavior:
The user cannot access the "Settings" window. (Delta Chat crashes when "Settings" is selected.) When the application is closed and rerun again, "Settings" can be access normally.

- Steps to reproduce the problem:
-- Install Delta Chat from scratch.
-- Run Delta Chat and restore a local backup.
-- Open "Settings" from the three-dot menu.

- Screenshots:
![grafik](https://user-images.githubusercontent.com/51095533/107890043-e52fa280-6f16-11eb-9ba5-062c7c01fc73.png)

- Logs:
`2021-02-14T15:11:49.569Z	renderer/react-crashhandler	ERROR	"\nKw.componentDidCatch (dc://deltachat/bundle.js:624:681696),\nKw.SL.s.componentDidCatch.r.callback (dc://deltachat/bundle.js:2:79748),\nHT (dc://deltachat/bundle.js:2:45914),\njT (dc://deltachat/bundle.js:2:45702),\nmre (dc://deltachat/bundle.js:4:11871),\nqa.unstable_runWithPriority (dc://deltachat/bundle.js:1:11874),\nI2 (dc://deltachat/bundle.js:2:41398),\nhf (dc://deltachat/bundle.js:4:8083)"	"The app encountered an react error"	{}`

**Comment by Jikstra** [comment]
@gerryfrancis can you post a longer log?

**Comment by Simon-Laux** [comment]
> "Cannot read property 'displayname' of null"
> ~error from the image

What do you need a log for @Jikstra

**Comment by gerryfrancis** [comment]
> can you post a longer log?

@Jikstra I would like to, but I deleted my backup from Android already, and would have to use a USB data cable to copy a new backup to my Windows notebook. Unfortunately I do not have such a cable at hand right now. Please check again after importing a Delta Chat backup from Android, thanks!

**Comment by Simon-Laux** [comment]
there are other methods of file transfer like ftp over wifi or https://syncthing.net/ or using the sdcard if your android device has one.
Or maybe Bluetooth file transfer.
or use https://github.com/svenstaro/miniserve  `miniserve --upload-files path/to/destination/folder`

**Comment by gerryfrancis** [comment]
@Jikstra Here is a complete log made from preview build 2126:

[2021-02-19-15-29-06.txt](https://github.com/deltachat/deltachat-desktop/files/6010783/2021-02-19-15-29-06.txt)

**Comment by Jikstra** [comment]
For whatever reason the key of the setting is `"display_name":"Anonymous"`. Don't get why.

**Comment by Jikstra** [comment]
> @Jikstra Here is a complete log made from preview build 2126:
> 
> [2021-02-19-15-29-06.txt](https://github.com/deltachat/deltachat-desktop/files/6010783/2021-02-19-15-29-06.txt)

The log doesn't include a get_settings line, did you trigger the bug with this log?

**Comment by Simon-Laux** [comment]
@Jikstra can't we check if the loaded settings are null and then show no settings until its loaded or show an error or something?

**Comment by Jikstra** [comment]
> @Jikstra can't we check if the loaded settings are null and then show no settings until its loaded or show an error or something?

Good idea :)

**Comment by gerryfrancis** [comment]
I cannot reproduce the issue with version 1.15.5 anymore. @Jikstra Any reason why we do not close here?

**Comment by Jikstra** [comment]
> I cannot reproduce the issue with version 1.15.5 anymore. @Jikstra Any reason why we do not close here?

No :)
