### ISSUE TITLE
"This message cannot be decrypted." for messages sent to "Saved messages" between android app and windows desktop

### ISSUE THREAD

**Issue by Hefaistos68** [deltachat/deltachat-desktop#2134]
- Windows 10 Home with latest updates as of today
- Delta Chat Version: Version 1.14.1 (git: v1.14.1)
- Expected behavior: being able to read my own messages sent to "Saved messages"
- Actual behavior: receiving error message "This message can not be decrypted" on windows desktop app after sharing an image on the android app to the "Saved messages" folder
- Steps to reproduce the problem: Share any image on the android app to the Delta Chat and select "Saved Messages" as destination
- Screenshots:  
![image](https://user-images.githubusercontent.com/8855055/108349756-4ab3b580-71db-11eb-8a2a-9a7482a31800.png)
![image](https://user-images.githubusercontent.com/8855055/108349951-8189cb80-71db-11eb-9648-734b63b840dc.png)

- Logs: No logs, "open log folder" doesnt work, and "open current logfile" tries to open a file that doesnt exist (windows desktop).

**Comment by Simon-Laux** [comment]
Do you have the same encryption keys on both devices? Do an autocrypt setup or better transfer an backup from the device you used first and then import that backup on the second device (this will also transfer existing chats, contacts and messages).

So the bug is actually that the logs can't be opened on windows over the menu?

**Comment by Hefaistos68** [comment]
From a "simple user" point of view: I dont even know, installed Delta Chat on my android phone, set it up with my gmail account, installed it on my Windows 10 through the app store, configured it with the same gmail account. Thats all. Can exchange messages with anyone, but saved messsages on one device cant be decrypted on the other.

As for the logs, I can open another bug report (actually the %AppData%\Local\DeltaChat\ folder hasnt been created at all)

**Comment by Hefaistos68** [comment]
After sending a Autocrypt message from Windows Desktop and completing it on Android, it continues to be unable to decrypt messages in the "Saved Messages" folder

**Comment by Hefaistos68** [comment]
Backup on the android app did never finish. stays forever on the backup in work dialog.
Made a backup on Windows Desktop, sent it via bluetooth to the android, imported the backup and all is working fine. all messages decrypt correctly now.
After that, the backup on Android also started working normally.

**Comment by gerryfrancis** [comment]
@Hefaistos68 Thanks for reporting, and have fun with Delta Chat! :)
