### ISSUE TITLE
"Device Messages" profile can be edited but not changed on Windows

### ISSUE THREAD

**Issue by Hefaistos68** [deltachat/deltachat-desktop#2135]
When opening the profile of the default "Device Messages" chat, one can edit the name but it does not save the changes. Opposite of the "Saved Messages" where the profile shows the name but does not allow altering.
On the android app this profile can not be edited.

- Operating System Windows 10 Home with latest updates as of today
- Delta Chat Version: 1.14.1
- Expected behavior:
- Actual behavior:
- Steps to reproduce the problem: select the "Device Messages", context menu "View Profile", edit the name and click ok

**Comment by gerryfrancis** [comment]
@Hefaistos68 Thank you for your report. Please try to reproduce the issue with the latest Desktop version 1.15.1. You can get it here: https://download.delta.chat/desktop/v1.15.1/ Than, please report back afterwards. Thanks!

**Comment by r10s** [comment]
i just. tried on 1.15.1, it is the same.

as gallery/docs/mute are not part of the profile (in contrast to android/ios), i think, we can deactivate the profile view completely for both, for saved-messages as well as for device-messages. i think none of the offered functions make sense for these chats.
