### ISSUE TITLE
Every email from accepted contacts creates new chat

### ISSUE THREAD

**Issue by cooper2k4** [deltachat/deltachat-desktop#2136]
Thank you for creating DeltaChat!

When using DeltaChat with non-DeltaChat users often answers to my chats don't get recognized as chat and won't be shown unless I enable emails from accepted contacts. But then for every new subject (e.g. prefix Re: or Aw:) a new chat gets created what makes the message list totally confusing. Why are not all messages from one contact combined in one chat? This is what I would expect from a messenger.

**Comment by Simon-Laux** [comment]
this issue tracker is for deltachat dektop bugs only (bugs that are desktop ui specific).
if you find a bug about the email handling please report it on the core repo: https://github.com/deltachat/deltachat-core-rust/issues

But your specific question is a discussion topic and not a concrete bug, so it is something for our forum: https://support.delta.chat/ (you can login with github there).

related topics on the forum:
- https://support.delta.chat/t/subject-of-emails/264
- https://support.delta.chat/t/ability-to-add-a-message-subject/941
- https://support.delta.chat/t/traditional-email-mode/534
