### ISSUE TITLE
add Khmer, Kurdish and more languages

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2137]
just a reminder, not urgent or so:

- Khmer and Kurdish are new and pretty well translated
- Sardu, Slovak, Norwegian are a bit older, however seems to be missing

a complete list, including english and local names is at  https://github.com/deltachat/deltachat-android/blob/master/res/values/arrays.xml#L8

**Comment by r10s** [comment]
please wait with adaption until https://github.com/deltachat/deltachat-android/issues/1818 is solved, seems we're using a wrong language code for kurdish.

**Comment by Simon-Laux** [comment]
> Sardu, Slovak, Norwegian are a bit older, however seems to be missing

are they now complete enough to be added? nice

**Comment by r10s** [comment]
> are they now complete enough to be added? nice

yip, i'd say so, esp. when compared to languages already in.

wrt kurdish issue this is figured out now: **the code to use is `ckb` (using arabic script, right-to-left) - not: `ku**` (this is kurdish with latin script), see

**Comment by Simon-Laux** [comment]
should we think about adding `el` and `la`? they both have already some translation progress if not much.

**Comment by r10s** [comment]
> should we think about adding el and la? they both have already some translation progress if not much.

hm, they're both not really actice, `la` was started by @paulaluap, not sure if she wants to continue :)

and for `el` - it is a shame! a software that has a greek letter as its name but no greek translation :D
