### ISSUE TITLE
Deltachat claims: "your data stays on your device"

### ISSUE THREAD

**Issue by allo-** [deltachat/deltachat-desktop#2143]
Deltachat claims: "your data stays on your device", even when the data stays on your IMAP-Server.

In some cases it may be your device, e.g., when self-hosting on a raspberry pi, but in most cases it stays on the server of your mail provider, which can be accessed by other people than just yourself. The information text should reflect this.

_The bug was updated because, at first, I thought it would be only a problem with the german translation when I opened it._

---

Original bug

     <string name="login_no_servers_hint">Es gibt keine Delta Chat Server! Ihre Daten bleiben auf Ihrem Gerät!</string>

means "Your data stays on your device" and not "your data stays in your mailbox"

- Delta Chat Version: 1.14.1

**Comment by r10s** [comment]
where do you got the "your data stays in your mailbox" from?

the [translation template reads `There are no Delta Chat servers, your data stays on your device.`](https://github.com/deltachat/deltachat-android/blob/master/res/values/strings.xml#L387) - and for that, the translation looks good.

**Comment by allo-** [comment]
Sorry, I was just guessing that the original may be better.

Then this is a more general bug: The line is not correct. The data stays on my mail server, not on my device.

**Comment by r10s** [comment]
you have to see the context: the claim is mainly about what the user is doing in exactly that dialog.

there are many comparable apps that copy the password to some central severs, this is not the case for delta chat. there were lots of discussions about this first line, ppl were scared to enter the password "why shall i give my password to delta chat ppl?" and so on.

tbh, the current claims works quite nice. maybe it can be improved, of course, but that would need to get the whole picture and history.

but in any case, this is nothing that can be changed in this repo (translations are the same over all systems), i suggest to close this issue and open an discussion at https://support.delta.chat, that would also include other operating systems that are using the translations.

**Comment by allo-** [comment]
Okay, it is in any case no translation issue. I think it is misleading and "data" should be something like "credentials" as other messengers make similar claims about data (and may even store more data locally, e.g., many clients store received messages only on the devices that received them and delete them from the server soon) meaning messages.
