### ISSUE TITLE
Handle selectedChat inside of DeltaChatController

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#215]
Currently we leave this up to SplittedChatListAndView Component which makes some trouble. We should leave this up to DeltaChatController and implement a method which lets is change the selectedChat. This also would allow us to mark messages noticed for the selected chat before we actually render.

**Comment by ralphtheninja** [comment]
Side note: The backend needs to update the selectedChat when a _selected_ chat is either deleted or archived.

**Comment by ralphtheninja** [comment]
In a similar fashion we should also move view archived chats to the backend, so when the user clicks "Archived chats", the backend will save that state, and instead return archived chats to the chat list.

**Comment by karissa** [comment]
yeah it would be great to move as much state as possible to the backend, and so the frontend is just simply displaying data and not managing any separate state

**Comment by ralphtheninja** [comment]
Done
