### ISSUE TITLE
Document GitHub Actions

### ISSUE THREAD

**Issue by missytake** [deltachat/deltachat-desktop#2175]
In https://github.com/deltachat/deltachat-desktop/blob/master/.github/workflows/test-windows.yml#L1, it says the test-windows.yml workflow is documented in the sysadmin repository - this is wrong, and probably a copy-paste error from the build-preview.yml github action.

It is not obvious at first glance what the following GitHub actions are supposed to do - so they should be documented, at best directly in the workflow yml file:

- [ ] test-windows.yml
- [ ] test-linux.yml

**Comment by Jikstra** [comment]
They run the unit and integration (e2e) tests for deltachat. On windows and linux.
