### ISSUE TITLE
Desktop app (.deb on Ubuntu) fails to update incoming messages even though the Android app is up-to-date

### ISSUE THREAD

**Issue by SRoyPC** [deltachat/deltachat-desktop#2176]
- Operating System (Linux/Mac/Windows/iOS/Android): Linux Ubuntu 20.04.2
- Delta Chat Version: v1.14.1
- Expected behavior: Incoming messages should sync across all platforms.
- Actual behavior: Outgoing messages are only updated. Incoming messages aren't updated on the desktop, and only the Android app receives them.
- Steps to reproduce the problem: N/A
- Screenshots: N/A
- Logs: N/A

**Comment by Simon-Laux** [comment]
Have you enabled "BCC Self" on both devices?
What are folder folder watch settings on both devices?

**Comment by SRoyPC** [comment]
Dear Simon: Thank you for the response. On both the desktop and mobile
apps, I have 'Send copy to self' as disabled. Moreover, on both the
devices, I have the following folders watched - Inbox, Sent and DeltaChat.
Thank you again.

**Comment by Simon-Laux** [comment]
you need to enable  'Send copy to self'  on both devices and then try again

**Comment by SRoyPC** [comment]
Thank you Simon. Enabling that option resolved the issue. Thank you again.

**Comment by SRoyPC** [comment]
There is one issue though - messages sent from the Android app are stored in 'Saved messages' of the Desktop app and vice versa. What I'm missing here is continuity. Is there any workaround to that? Thanks.

**Comment by Simon-Laux** [comment]
what email provider are you using?

**Comment by SRoyPC** [comment]
It is Gmail. Thanks.

**Comment by Simon-Laux** [comment]
please reopen if the 1.26 version still has this issue for you
