### ISSUE TITLE
[Progress] Release 1.15.4 / 1.15.5

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#2187]
- [X] website (https://github.com/deltachat/deltachat-pages/commit/f05845154732a6c13a351eef45cc369ba069f1a8)
- [ ]  flathub (https://github.com/flathub/chat.delta.desktop/pull/52)
- [X] github release (https://github.com/deltachat/deltachat-desktop/releases/tag/v1.15.4) 
- [X] mac store
- [Pending] windows store
- [X] homebrew (Homebrew/homebrew-cask#102527)

**Comment by cwerner1** [comment]
Homebrew pull requested ( https://github.com/Homebrew/homebrew-cask/pull/102527 )

**Comment by cwerner1** [comment]
homebrew pull request for 1.15.5 https://github.com/Homebrew/homebrew-cask/pull/102765

**Comment by Simon-Laux** [comment]
I think we can close this, there won't be a flatpak release for 1.15.
1.20.2 will have flatpak again and it's progress is tracked in #2276
