### ISSUE TITLE
virus alarm for "DeltaChat Setup 1.15.3.exe"

### ISSUE THREAD

**Issue by abzr12** [deltachat/deltachat-desktop#2188]
windows defender reported a virus alarm in file "DeltaChat Setup 1.15.3.exe": "Trojan:Win32/Spursint.F!cl"

**Comment by Simon-Laux** [comment]
Looks like a false positive, virustotal says its clear:
https://www.virustotal.com/gui/file/6748a5b0280877d0f5eb1873c52810ce6aeafac5757d45c7e47deca11ce4bff5/detection

**From where did you download it?**
The official sources are:
- https://download.delta.chat/desktop/v1.15.3/
- https://delta.chat/en/download

**Comment by abzr12** [comment]
My source was
https://download.delta.chat/desktop/v1.15.3/DeltaChat%20Setup%201.15.3.exe

> Looks like a false positive, virustotal says its clear:

Ok, for me.
But a friend said, that his Kaspersky Internet Security SW blocked the exe too.

**Comment by abzr12** [comment]
Oh - I checked "DeltaChat Setup 1.15.3.exe" today again without an alarm message. Virus definition today is "1.333.963.0". Maybe the Windows defender virus definition database from yesterday raised the problem.

**Comment by abzr12** [comment]
Today my colleague said: his Kaspersky reported "virus free" an installation was possible.
So it looks like a 'false positive' too.

**Comment by Jikstra** [comment]
So let's close it :) Thanks for reporting :)

**Comment by abzr12** [comment]
> 
> 
> So let's close it :) Thanks for reporting :)

That's ok for me. Thanks!

**Comment by gerryfrancis** [comment]
FYI: Windows Smartscreen is "annoyed" every time I run Delta Chat setup because the file has no (valid) signature.
