### ISSUE TITLE
notifications are sometimes not clickable

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2198]
notifications show up nicely in the notification center of mac, however, clicking the notifcations, nothing happens (or i missed something :)

i would expect Delta Chat to be opened, ideally, in the correct chat.

**Comment by Simon-Laux** [comment]
> i would expect Delta Chat to be opened, ideally, in the correct chat.

it's implemented, but there might be a bug somewhere. while testing I also saw that behavior, but I couldn't reproduce it reliable.
Which version are you using?

**Comment by r10s** [comment]
i am using 1.15.5 on mac.

i just double-checked: 
- a click on the shortly appearing "headup notification" works - even the correct chat is opened and the notification disappears afterwards
- this "headup notification" disappears after 2 seconds or so and then the notification goes to the notification-center, however, also this works now.

this is weird - i am pretty sure, it did not worked before, also on 1.15.5, however, as i cannot reproduce the issue, i think it can be closed for now. if it happens again and i find a way to reproduce, we can reopen. sorry for the noise.

**Comment by Simon-Laux** [comment]
I also had this not working sometimes, so lets rather keep it open. maybe there is a problem in opening the deltachat window on click on notification if it was minimized/hidden in a specific way...

**Comment by Simon-Laux** [comment]
at this point I think we should make our own native npm module to handle notifications as currently if you restart deltachat you can not control the notifications from previous sessions.
