### ISSUE TITLE
notifications are not removed from notification center

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2199]
notifications show up in the notification center of mac (probably also on other os), however, they are not removed when the corresponding chat is opened and the belonging messages are no longer "fresh".

eg. on android, we dismiss all notifications belonging to a chat once the chat is opened, i assume sth. like that would be nice for desktop as well.

also, the question arises what should happen to the notifications on account switching, esp. if they get clickable by #2198 - an easy approach would be to just dismiss all notifications on account switching.

**Comment by Simon-Laux** [comment]
it is implemented, so if it doesn't work its a bug.

**Comment by r10s** [comment]
to be clear:

- the notification _is_ removed when the notification itself is clicked and delta chat opens the corresponding chat (which seems to work, although i stated differently at #2198 )

what is not working for me on 1.15.5/mac:

- a notification appears for ChatA, also the badge counter is increased correctly

- the notification is _not_ clicked, instead, the user navigates to ChatA inside Delta Chat, using the chatlist

- now the badge-counter is decreased correctly, but the notification stuck inside the notification center

<img width=700 src=https://user-images.githubusercontent.com/9800740/112890435-2bac1b80-90d7-11eb-8907-cbbac081d244.png> <br><i>(the chat is opened on the left and there are no "new" messages, the notification center still notifies about notifications are are long read)</i>

i would expect the notifications being removed along with removed badge counter (in other words, remove all notifications belonging to the chat that was just opened)

**Comment by Simon-Laux** [comment]
looks like this is the case on windows 10 too, even for the current session
