### ISSUE TITLE
Uncaught exception after quitting

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#2201]
- Operating System (Linux/Mac/Windows/iOS/Android):
Windows 8.1 Pro.

- Delta Chat Version:
1.15.5/1.33.2.

- Expected behavior:
Delta Chat does not crash (uncaught exception) after quitting.

- Actual behavior:
Delta Chat crashes (uncaught exception) after quitting.

- Steps to reproduce the problem:
Unfortunately I cannot reproduce the issue.

- Screenshots:
![DC_uncaught exception](https://user-images.githubusercontent.com/51095533/113032354-1515cb00-9190-11eb-91be-003bb04c04dd.png)

- Logs:
[DC_uncaught_exception.txt](https://github.com/deltachat/deltachat-desktop/files/6231073/DC_uncaught_exception.txt)

**Comment by gerryfrancis** [comment]
I cannot reproduce the issue in the current version 1.20.3 anymore, so I am closing here...

**Comment by gerryfrancis** [comment]
I am reopening here because the issue seems to have come back. (Using current version 1.33.2 now.) Here is the log:

[2022-11-17-13-45-26_2.txt](https://github.com/deltachat/deltachat-desktop/files/10041223/2022-11-17-13-45-26_2.txt)

**Comment by farooqkz** [comment]
I can reproduce on:

 - Linux(xUbuntu 22.04) + Xorg
 - DeltaChat from 03464e4e42d8730414624d

Steps to reproduce:

 - Right click on the DC icon in status bar
 - Click "Quit"
 - See these logs:

```
908.7s [E]main/mainWindow: can not send message to window, error: TypeError: Object has been destroyed
    at Object.send (/home/farooqkz/playground/DC/desktop/src/main/windows/main.ts:163:12)
    at AccountManager.<anonymous> (/home/farooqkz/playground/DC/desktop/src/main/deltachat/controller.ts:100:18) 
Object.send (/home/farooqkz/playground/DC/desktop/src/main/windows/main.ts:165:9),
AccountManager.<anonymous> (/home/farooqkz/playground/DC/desktop/src/main/deltachat/controller.ts:100:18)
908.7s [i]core/event: 0 src/accounts.rs:267: Stopping IO for all accounts.
909.2s [i]main/index: Quitting now. Bye.

```

**Comment by gerryfrancis** [comment]
@farooqkz Thank you for taking care! :)

**Comment by farooqkz** [comment]
Did nothing but yw ;)
