### ISSUE TITLE
Add an Add-Attachment menu

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#2203]
A menu when clicking on the paperclip 📎 icon that allow you to specify whether you want to send an file image or video hangout/chat invitation.

**Comment by naomiceron** [comment]
Hello, I would like to work on this, this is my progress so far, does it seems about right?
![Screen Shot 2022-01-04 at 11 48 30](https://user-images.githubusercontent.com/58761246/148112277-10b6fd14-a4a5-40d5-86d6-58f65bd48a48.png)

**Comment by naomiceron** [comment]
I haven't been able to find the extension that an Invitation would need, is it a .qr? or should it allow to select any type of attachment? Thanks in advance! :)

**Comment by r10s** [comment]
@naomiceron looks great! thanks a lot for taking care!

to your question: as far as i know, there is currently no extension or file format for invitations, neither android nor ios has sth. like that. invitations are either strings that are copy+pasted around or images containing a qr-code, the latter is not supported on all platforms.

it probably makes sense to think about a separate invitation format, however, in the context of this approach, this seems out of scope. so maybe just leave the "invitation" thingie out for now and start with the more concrete things.

**Comment by Jikstra** [comment]
> it probably makes sense to think about a separate invitation format, however, in the context of this approach, this seems out of scope. so maybe just leave the "invitation" thingie out for now and start with the more concrete things.

I think invitation is about video chat invitation, which surely exists. But actually I'm not so sure if it's not better to have that in the context menu.

@naomiceron what would be your idea on how to filter files for video/pictures/documents...? Because desktops dont really have that gallery like thing that android/iphones have. But maybe I'm overseeing something?

**Comment by Simon-Laux** [comment]
I think that its great ui wise, also a good place for the video chat invitation.

@jikstra we just need a list of what we support to be displayed, everything other is just a file. the other ui option would be autodetection of view type from attachment and a toogle for sending it with/without core-compression (send as file or as image/video)

I'm currently reworking on the composer system so draft ids stay (also hopefully I can finally fix the rare bug where drafts sometimes stay after sending), so @naomiceron it would be enough if you just made a pr with the ui part, I can then integrate it and do the harder draft handling stuff.

**Comment by r10s** [comment]
> I think invitation is about video chat invitation, which surely exists

thanks for clarification!

indeed, i think, this is a much better place for video chat invitations, we are also thinking on android/ios moving it there. the place will have the advantage to better match user expectations, it is more clear that a "message as usual" is sent - and not sth. special that will "ring" the recipients phone. additional text input can improve the ux further.  
but still, i would remove that out of the initial approach of adding an attachment-menu, we can change that later once the "simpler" parts of the attachment menu are settled.

- so, for the menu entries, maybe just start with "Images" and "Files" - both will open the file selector, with an image filter set in the latter case. also in the latter case, messages could be sent as DC_MSG_IMAGE, which will result in downscaling, that is completely missing on desktop currently afaik. 

that would be the set i'd start with :)

**Comment by naomiceron** [comment]
Thank you for your comments :), @Simon-Laux I will do a PR shortly with the UI implementation. Also, my original plan was to filter by file extensions @Jikstra, but I will remove it to be according to what @r10s suggested, having a menu with option for files and images.
