### ISSUE TITLE
Delta Chat Flatpak seems unable to save images to /tmp

### ISSUE THREAD

**Issue by rduivenvoorde** [deltachat/deltachat-desktop#2205]
- Operating System Debian Testing
- Delta Chat Version: 1.14.1 via flatpak
- Expected behavior: when somebody sents me an images in a chat, downloading and (seemingly) save it to /tmp they are visible in DeltaChat itself (eg when saving the same img with different names)
- Actual behavior: BUT: on the actual file system the images are not available. NOTE: when downloading and saving to /home/me all is fine
- Steps to reproduce the problem: on Debian Testing, install via flatpak. Let somebody sent you a photo or image, using the little 'download' button top-right try to save it to /tmp. Go to /tmp and check if the file is there.

It could be that this has something to do with the flatpak magic/permissions? As said: saving it to my /home dir just works....

Some info from the About Delta Chat (some personal info removed):
```
{
    "arch": "64",
    "bcc_self": "0",
    "configured_mvbox_folder": "DeltaChat",
    "configured_sentbox_folder": "Sent",
    "database_version": "69",
    "deltachat_core_version": "v1.50.0",
    "display_name": "0",
    "e2ee_enabled": "1",
    "entered_account_settings": "richard@duif.net 
    "folders_configured": "3",
    "inbox_watch": "1",
    "is_configured": "1",
    "journal_mode": "wal",
    "level": "awesome",
    "mdns_enabled": "1",
    "messages_in_contact_requests": "0",
    "mvbox_move": "1",
    "mvbox_watch": "1",
    "number_of_chat_messages": "8",
    "number_of_chats": "3",
    "number_of_contacts": "139",
    "private_key_count": "1",
    "public_key_count": "1",
    "selfavatar": "<unset>",
    "sentbox_watch": "1",
    "sqlite_version": "3.33.0",
    "uptime": "0h 15m 39s",
}
```

**Comment by Simon-Laux** [comment]
please report this to https://github.com/flathub/chat.delta.desktop instead, I'm closing this here as it works for me (I'm not using the flatpak)
