### ISSUE TITLE
let mailto:-links in other apps open Delta Chat

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2208]
now, that classic email becomes more a thing for Delta Chat, it would be great if Delta Chat opens when the user clicks a `mailto:`-link in other apps.

@Hocuri did a testing page for that when the stuff got implemented on android, probably, that is useful for Desktop as well:
https://github.com/deltachat/interface/blob/master/user-testing/mailto-links.md

**Comment by Simon-Laux** [comment]
the old issue https://github.com/deltachat/deltachat-desktop/issues/905
