### ISSUE TITLE
Add a "forget account" button next to cached accounts in login page

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#221]
This is useful for both the user and the developer. Basically:

* take the addr
* compute the folder name
* wipe the folder (needs confirmation dialog)

**Comment by Jikstra** [comment]
Is there no core api method for this?

**Comment by r10s** [comment]
> Is there no core api method for this?

no, was not needed until now :)
but deleting the blob-folder and the database should do the job.
