### ISSUE TITLE
Recieved messages not shown

### ISSUE THREAD

**Issue by havet** [deltachat/deltachat-desktop#2210]
Hi,
Today I cannot receive any messages in a chat. They are not visible in DeltaChat. I've found them in the inbox, though.

Yesterday all worked as a charm. I can find those messages in the DeltaChat folder.

The messages where sent from my Android phone. DeltaChat version 1.14.5

    Operating System (Linux/Mac/Windows/iOS/Android): Windows 10

    Delta Chat Version: 1.15.3

    Expected behavior: Chat messages showed in the chat

    Actual behavior: All messages sent from the phone to the computer are missing. All messages from the computer are showed   in the chat on the phone, as well as the messages sent from the phone.

    Steps to reproduce the problem: Chat with an Android phone. Have a look in the mail folders.

    Screenshots: NO
    
    Logs: NO.

**Comment by havet** [comment]
No,  for testing purposes I'm using two different accounts.
The settings above are only available on my phone, not in the Windows version.

Strange that I got the 1.15.3 version through the Windows store. Is the update delayed?

BTW I've got some old mail in the inbox for the account with the problems.  This should not interfere with the chats, I suppose.

I do want to keep those mails. I check this account by webmail for ordinary mail. I don't want them to appear in Delta Chat. And they haven't, so far.

**Comment by Simon-Laux** [comment]
> The settings above are only available on my phone, not in the Windows version.

you might need to scroll down in the settings dialog to find them.

Which providers do you use, also have you tried restarting the windows version. maybe there is an network connection bug somewhere?

**Comment by havet** [comment]
Hi Simon,
found the settings.
The option "Watch Sent folder" was unchecked.

Obviously, this shouldn't be the default.

**Comment by Jikstra** [comment]
> Obviously, this shouldn't be the default.

Hmm currently it's like this for reasons of traffic and limiting concurrent threads. But it will change, we know it's annoying and all those options will be magically gone at some point. For now this is the sad reality :P

**Comment by havet** [comment]
Yes, changing the default setting solved the problems.
But, I insist: "Watch Sent folder" should be the default option. Otherwise the user has to successfully create a filter at the mail server, moving chat messages to the DeltaChat folder. That's a job for an expert - not an ordinary user. Delta Chat should work "out of the box".
The help tells:
"Why can I choose not to watch the Inbox?
This is an experimental setting for some people who are experimenting with server-side rules. Not all providers support this, but with some you can move all mails with a “Chat-Version” header to the DeltaChat folder. Normally, this would be done by the Delta Chat app. ..."
Please check why Delta Chat on first use did check the inbox and didn't on second use. This isn't an acceptable behaviour.
I'd call it a bug.

**Comment by gerryfrancis** [comment]
@havet I found [this comment](https://github.com/deltachat/deltachat-core-rust/pull/2067#issue-514994048) with this note:

> We now also move self-sent messages from the Inbox to the Sent folder if `mvbox_move` is off, as this was very easy to do now. This way, we now behave more like a normal MUA if the user wants this.

What I think about what might have happened: Maybe you sent some messages with the older branch version 1.14.x with the function `Send copy to self` enabled. (Copies are sent to yourself in Bcc and are delivered to your Inbox folder.) Then, you installed a newer Delta Chat version 1.15.x on another device (e.g. Desktop PC). Both Delta Chat clients might have the functions `Watch Sent folder` and `Watch DeltaChat folder` disabled. While you see the self-sent messages on the first client (version 1.14.x) due to the enabled function `Watch Inbox folder`, they are not visible anymore within the second client (version 1.15.x) because they were automatically moved to the (non-watched) Sent folder.

@Hocuri Am I right with my conclusion?

**Comment by gerryfrancis** [comment]
The answer seems to be here: https://github.com/deltachat/deltachat-core-rust/pull/2184

So, the change has been reversed to the old logic.

@havet Which versions of Delta Chat are you using currently?

**Comment by havet** [comment]
No, i've got just one installation for this mail account. Testing against other devices of all sorts with separate accounts.

**Comment by havet** [comment]
1.15.3 on a Windows box.
I have tried to reproduce the error on an other Windows box and a Linux box (Debian), but it has not occurred. Those installations have work as expected.
It's a pity I cannot get hold of the log.

**Comment by gerryfrancis** [comment]
> It's a pity I cannot get hold of the log.

@havet For Windows, the log is located in `C:\Users\[User]\AppData\Local\DeltaChat\logs`.

**Comment by havet** [comment]
My mail answer seems to have got lost.
NO, the log cannot be found in the expected folder when using the Microsoft Store version of Delta Chat.
In fact I cannot find it anywhere. I'm blocked from the installation folder by Windows.

**Comment by gerryfrancis** [comment]
@havet Thanks, I did not know that you filed another issue regarding the log file, my bad. Unfortunately we need a current log to see what is going on in the background...

**Comment by havet** [comment]
Well, nothing to do then. I hope the log file issue will be solved, in case anyone else would experience the same problem in the future.

**Comment by gerryfrancis** [comment]
@havet I suggest to wait for the next release of Delta Chat for Desktop and give it a try. The developers fixed similar issues for Android already, so I am confident that Desktop will get these fixes as well. However, many thanks for your commitment! :)
