### ISSUE TITLE
Setup file not signed

### ISSUE THREAD

**Issue by havet** [deltachat/deltachat-desktop#2213]
- Operating System (Linux/Mac/Windows/iOS/Android): Windows
- Delta Chat Version: 1.15.5
- Expected behavior: Installation without Windows complaining about unknown software of suspect origin
- Actual behavior: Windows stops the installation and warns me that installation might be harmful for my computer
- Steps to reproduce the problem: Digitally sign the installation files with a valid code signing certificate

Apparently the version for the Windows Store is signed. Thus, it's a mystery to me why the other installation file isn't signed.

**Comment by Simon-Laux** [comment]
the windows store signs it, we didn't came around to buying a signing certificate yet.
But you're right we should do so soon, thanks for opening the issue to remind us.

**Comment by Simon-Laux** [comment]
next update will be signed

**Comment by Simon-Laux** [comment]
> I was trying to update the manifest for DeltaChat for the Windows Package Manager which is currently on 1.20.3, however it's not possible to do that until the program can install without popups.

please open a separate issue if you want that we look into silent install options.
