### ISSUE TITLE
Does not play nice with .webp files

### ISSUE THREAD

**Issue by mrmannet** [deltachat/deltachat-desktop#2216]
- Operating System (Linux/Mac/Windows/iOS/Android): Mac OS
- Delta Chat Version: Version 1.15.5 (git: v1.15.4-1-g77948e7b)
- Expected behavior: Show webp image when attaching to a chat
- Actual behavior: Renamed the file to .w and sent it as an octet-stream
- Steps to reproduce the problem: drag and drop a .webp file into the chat window and send away
- Screenshots: ![Capture d’écran 2021-04-10 à 20 08 20](https://user-images.githubusercontent.com/48960763/114280204-87ac6380-9a38-11eb-8ac0-2f439535d13c.png)
- Logs:

**Comment by mrmannet** [comment]
![Capture d’écran 2021-04-10 à 19 57 40](https://user-images.githubusercontent.com/48960763/114280243-aad71300-9a38-11eb-8687-f1e8faba9308.png)
I forgot to include the original file details

**Comment by gerryfrancis** [comment]
@mrmannet Thank you for your report, I think there is some work going on already: https://github.com/deltachat/deltachat-desktop/pull/2207

**Comment by Jikstra** [comment]
Yes It should be fixed already/for the next version :)
