### ISSUE TITLE
Filename issue when sending file.

### ISSUE THREAD

**Issue by YamatoRyou** [deltachat/deltachat-desktop#2219]
- Operating System (Linux/Mac/Windows/iOS/Android): Windows 7
- Delta Chat Version: 1.15.5
- Expected behavior: The image file can be previewed normally when it is sent, and it does not depend on the file name.
- Actual behavior: Image files with certain characteristics in their file names cannot be previewed when they are sent.
- Steps to reproduce the problem: n/a
- Screenshots: See the text for details.
- Logs: n/a

---------------
For the file to be sent, the position and number of the prefix and suffix separator in the file name will cause the display mode and opening mode of the file in Delta Chat to be changed.

Example of file name:
* File A: file name `90.12345678901234567890123456789.png`: Unexplained characters are added to the file name when sending using Delta Chat, there is no preview, and after sending, the file cannot be opened in the correct way;
* File B: file name `901.2345678901234567890123456789.png`: The above problem does not exist.

It seems that it is not limited to image files. Delta Chat also seems to automatically modify the file name of other types of files, sometimes causing some files to fail to preview in Delta Chat.

Screenshots:
![9405b762940ebd91de5b64630d02a5c19595d9a1](https://user-images.githubusercontent.com/48104960/114393560-b9eeca00-9bcc-11eb-91ea-70c7deeda2e8.png)
![24a39174b12440760ccf85da755540be0c6d2a07_2_690x286](https://user-images.githubusercontent.com/48104960/114393569-bbb88d80-9bcc-11eb-87ee-51ac3b808828.png)

**Comment by Jikstra** [comment]
I can reproduce this. Weird.

**Comment by Jikstra** [comment]
Some first debugging brought to light that something goes nuts between setFile and getFile. So actually some conversion in the core? But I don't see anything causing this besides the lossy conversion... Weiiiird. @Simon-Laux

**Comment by Hocuri** [comment]
This is a core issue (https://github.com/deltachat/deltachat-core-rust/issues/3090: Exactly 32 characters after the first point in the filename, the name is just cropped, sometimes even cropping away the extension), so we can close it here.
