### ISSUE TITLE
Start a videochat is not available for groups

### ISSUE THREAD

**Issue by AUtech-dev** [deltachat/deltachat-desktop#2222]
The option in the menu to send a videochat invitation does not appear in groups.
As the videochat itself is handled externally, I don't see a reason why DeltaChat should not enable this button for groups.

- Operating System (Linux/Mac/Windows/iOS/Android): Windows
- Delta Chat Version: 1.15.4
- Expected behavior: Menu for a chat includes "videochat" even for groups
- Actual behavior: Menu only contains the option "videochat" for 1 to 1 chats
- Steps to reproduce the problem: Open a group chat, click on the 3 dot button in the top left corner and do not see the videochat entry
- Screenshots: 

Menu from a 1-to-1 chat with the videochat entry:
![grafik](https://user-images.githubusercontent.com/72972651/114846011-8edac500-9ddc-11eb-9d99-f360b1f84fc8.png)

- Source:

https://github.com/deltachat/deltachat-desktop/blob/master/src/renderer/components/Menu.tsx#L124

**Comment by r10s** [comment]
this is by design currently, the experimental videochat-feature is available for one-to-one-chats only, this is also how the feature is described in the settings.

groups are a bit more tricky ux-wise, esp. as we had some integrated videochat-code up to some point, therefore, we started that way.

however, i think, we will revise and finish the feature at some point and probably open it also for groupchats then :)

**Comment by AUtech-dev** [comment]
I have suggested the minimal implementation for the current state with the URL based chat in #2223 .

Wouldn't it be great to add this at least until the integrated videochat is available?

As you noted the description text in the settings needs to be changed in order to be complete.

Maybe also add a checkbox for activating this in group chats? 

Or a kind of combobox for choosing the internal method or external via an URL? As far as I know all URL based chat systems will work with more than two people.

**Comment by r10s** [comment]
thank you for your pull request!

> Wouldn't it be great to add this at least until the integrated videochat is available?

indeed, as it is experimental anyway, it is probably okay open these invites to groups that way. things can be refined once we pull it out of "experimental" (wordings, defaults, maybe a warning to not invite 50 ppl accidentally). however, as i am not deep into javascript, final/technical approvment should be done by the code maintainers :)
