### ISSUE TITLE
Setup Message not shown in Windows Store version

### ISSUE THREAD

**Issue by havet** [deltachat/deltachat-desktop#2228]
- Operating System (Linux/Mac/Windows/iOS/Android): Windows 10
- Delta Chat Version:1.15.3 (Store version)
- Expected behavior: Setup message is shown and can be acted upon.
- Actual behavior: Nothing shown at all.
- Steps to reproduce the problem: Send a setup message from an other unit, open Delta Chat in Windows.
- Screenshots: NO.
- Logs: NO See issue #2209

I sent the setup message from a Linux-box and checked with web mail that it had arrived to the inbox at the server.

I started Delta Chat Windows, chose Switch account, and created the new account. After logging in nothing happened. I looked in the folder "Saved messages": nothing. I tried to start a new chat to myself and returned to "Saved messages".
Then I changed the settings to "Show classic emails": NO difference!
I sent an ordinary mail to this account and it appeared under "Contact requests". But the setup message is still not shown anywhere in Delta Chat.

I tested to send a new setup message from the Linux-box and setup the account on an Android phone: it worked as expected. The setup message appeared in "Saved Messages" and could be opened and acted upon. The settings (keys) where transferred as expected.

**Comment by Jikstra** [comment]
> I started Delta Chat Windows, chose Switch account, and created the new account. After logging in nothing happened. I looked in the folder "Saved messages": nothing. I tried to start a new chat to myself and returned to "Saved messages"

So you sent the autocrypt setup message before you added the account on windows? If that's the case, deltachat doesn't fetch messages that arrived before first login. Send it again and it should appear. To keep your history/contacts, use the export/import backup feature.

**Comment by havet** [comment]
Yes, indeed, I did. Tested creating the account after sending the setup message and it works OK. Might be a bit confusing to any user, though. Maybe you'd better put a hint somewhere? FAQ/Help?
By the way:
In the switch-account window I find "Scan QR-code". Is that an other way to setup a new account? How?

**Comment by Simon-Laux** [comment]
> Is that an other way to setup a new account? How?

yes it's for special account creation qr codes generated by https://github.com/deltachat/mailadm.

**Comment by havet** [comment]
Ok.
I'll close the issue with a note:
NB Create the account on the other device BEFORE sending the setup message from the first device. Otherwise the message will not be found.
