### ISSUE TITLE
read receipts are sent when chat is opened while screen turns off

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2229]
read receipt should only be sent when messages are really displayed to the user.

if the chat is open but the screen is turned off, no read receipt should be sent.

if later the screen is turned on again, and the user sees the messages, the read receipts should be sent.

a similar issue is, when the Delta Chat window is completely covered by another window, cmp. https://github.com/deltachat/deltachat-desktop/issues/1293, https://github.com/deltachat/deltachat-desktop/issues/2069

(tested in 1.15.5 on mac)

ios/android has the same issue, btw: https://github.com/deltachat/deltachat-ios/issues/1178, https://github.com/deltachat/deltachat-android/issues/1900

**Comment by Simon-Laux** [comment]
this should be already solved on master
