### ISSUE TITLE
Where to put yahoo generated code ?

### ISSUE THREAD

**Issue by Attil69** [deltachat/deltachat-desktop#2230]
Hi, I tried to connect deltachat with a yahoo.fr mail account, but cant make it work.
On your website, it says we need to get a yahoo security code and enter it in delta.chat... But where ???

Thanks, your app is just amazing, love it. 

- Operating System (Linux/Mac/Windows/iOS/Android): MX linux
- Delta Chat Version: 1.15.4
- Expected behavior: should be able to enter yahoo generated code
- Actual behavior: No place to do so
- Steps to reproduce the problem: ?
- Screenshots: "ID/PSW error"
- Logs:

**Comment by Simon-Laux** [comment]
the" yahoo security code" is the password you use in dc, its also called "app **password**".
also I recommend checking the spam filter setting in yahoo if its unreliable.

Please ask such questions in our forum in the future, the github issues are only for development things and bug reports:
https://support.delta.chat/c/help/5 (you can login to our forum with github, no new account required)
