### ISSUE TITLE
Closing bracket in URLs not recognised

### ISSUE THREAD

**Issue by msCran19** [deltachat/deltachat-desktop#2238]
- Operating System (Linux/Mac/Windows/iOS/Android):

Windows 7, Windows 10

- Delta Chat Version:

1.15.5

- Expected behavior:

A URL like [https://en.wikipedia.org/wiki/Bracket_(disambiguation)](url) sent in a DeltaChat message should open on click without problems.

- Actual behavior:

The closing bracket is omitted, i.e. the link opened in the browser is [https://en.wikipedia.org/wiki/Bracket_(disambiguation](url)

- Steps to reproduce the problem:

Send the URL https://en.wikipedia.org/wiki/Bracket_(disambiguation) as message in DeltaChat and then click it.

Furthermore, different bevaviour for different (combinations of) closing brackets can be observed. Send the following links as DeltaChat message and then click the links:
https://delta.chat
https://delta.chat)
https://delta.chat}
https://delta.chat]}
Especially the last one is slightly worrying (as it opens the Windows Explorer).

The problem doesn't occur on Android.

**Comment by Jikstra** [comment]
@Simon-Laux we are fixing your regex again and again, maybe time to use something like https://www.npmjs.com/package/linkifyjs ?

**Comment by Simon-Laux** [comment]
I rather think its time for message parsing in the core, but that's nothing we can quickly do now. Also I think including linkify is not  trivial either, even if its probably still easier than a core feature, fixing the regex is probably faster.
also we could create unit tests for the regexps.

possible related https://support.delta.chat/t/problem-with-shared-links-that-contain-other-languages/1645
