### ISSUE TITLE
add 'Forwarded' string

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2244]
pass new 'Forwarded' string to core once https://github.com/deltachat/deltachat-android/pull/1924 is merged; maybe also check if the other translations passed to core are complete.

**Comment by Simon-Laux** [comment]
I planed to push this soon with the untranslated desktop translations - you were faster. so pr is here: https://github.com/deltachat/deltachat-desktop/pull/2241
I'll close this issue as that part is already done.
