### ISSUE TITLE
cannot add new e-mail addresses directly to a group

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2256]
one cannot add an e-mail-address, that is not known as a contact yet, directly to a group - neither on group creation nor on group editing.

maybe, i've oversee something, however, my path was _"New chat / enter address / New contact"_ to create a  one-to-one chat. then, _"New chat / New group / Add members / enter address [x] / Ok / Create group"_ to create group with that contact.

it would be great, if one could add a new contact already at [x]

**Comment by cavesdev** [comment]
I'll work on this. Want to contribute a little more towards the release!
