### ISSUE TITLE
MacOS: open deltachat from uri doesn't detect the uri

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#2257]
This affects both `mailto` and `OPENPGP4FPR` they are correctly detected/handled once deltachat is opened.

**Comment by r10s** [comment]
i just tested with 1.20.2, `openpgp4fpr` opens Delta Chat whether it is already running or not, that is great!

however, once started, the secure-join-protocol is not started, it should basiccally do the same as if a qr-code with the content was scanned, so ask the user and pass the qr-code to dc_join_securejoin().

the goal is that snippets as the following work:

```
<!DOCTYPE html>
<html>
<head>
</head>
<body>

<a href="OPENPGP4FPR:61D37E30CA7C4630C66D564977FB68391D3B7184#a=tunis4%40testrun.org&n=&i=sp2gRzrr7AA&s=QrDr3ASfZGA">
   <img src="QR code here .." />.
</a>

</body>
</html>

```

**Comment by r10s** [comment]
the same issue is true if Delta Chat is the "Default E-Mail App" on mac os and the uses selectes "Share to Delta Chat" eg. from Safari - if Delta Chat is not yet started, it is started, however the things to be shared are lost.

**Comment by Simon-Laux** [comment]
https://github.com/electron/electron/issues/23852

**Comment by Simon-Laux** [comment]
in GitHub desktop somehow works, it uses electron 17.0.1, so maybe it is fixed in electron 17?

**Comment by Simon-Laux** [comment]
so found out why it did not work: macOS only uses `app.on('open-url')` for this, but the listener needs to be registered early so it can catch the event. we set the listener too late to get the url.
