### ISSUE TITLE
"Group left" message should be optional?

### ISSUE THREAD

**Issue by sbadux** [deltachat/deltachat-desktop#226]
Hello,
today I was testing the new v1.7 and I quitted the the mailing list group (it was automatically created by the app). I left the group with the specific button and the app sent a "group left" message to everybody (the mailing list).
Maybe the "group left" message should be sent only with the OK from the user? Maybe you can add a pop-up to ask if the user wants to send the message or not?

**Comment by ralphtheninja** [comment]
> Maybe the "group left" message should be sent only with the OK from the user? Maybe you can add a pop-up to ask if the user wants to send the message or not?

This seems related to core.

cc @r10s

**Comment by sbadux** [comment]
> @sbadux This sounds a bit strange to start with. I'm wondering how the mail list could invite you and create a group for you in the desktop app.

I'm not invited BY the ML but Desktop app created a chat for the ML.

![image](https://user-images.githubusercontent.com/28478027/47599254-14b6eb80-d9aa-11e8-855b-771e8419232b.png)
 
I left this chat (as the "group left" email confirms) but the chat has been re-created at the next startup

**Comment by ralphtheninja** [comment]
Oh, I see, sorry. So you're using your "normal" email address and don't have a dedicated account for delta. So, the question is two-fold:

1. why does the group automatically get re-created
1. can the "Group left" message somehow be configured so it's not always sent

Both of these I'll defer to @r10s

**Comment by r10s** [comment]
> 1. why does the group automatically get re-created

unless the user sending a message is blocked, groups are recreated if new messages arrive, eg. after deletion.

deleting a _chat_ does undo creating a _chat_ - so if new messages arrive the chat is re-created (or, more exact, the user is asked if he wants to have this chat).
there is no _delete group_ option - one can leave a group or delete the represenation on the own device, but the group won't be deleted this way.

to avoid recreation, you have to leave the group first (maybe it makes sense on group deletion to ask if one wants also to leave the group).

wrt. the mailing list: normally it should not appear at all, messages from mailing lists are normally discarded currently. not sure how this could happen, but this is another issue :)

> 2. can the "Group left" message somehow be configured so it's not always sent

no.

it makes sense to inform the user that all other group members will get a message about that he wants to leave the group.

however, there is no chance currently to leave the group without sending a message - if one want to leave a group, one has to inform the others that they should not sent any messages anymore.

so, an option does not make sense currently.

**Comment by sbadux** [comment]
> it makes sense to inform the user that all other group members will get a message about that he wants to leave the group.
> however, there is no chance currently to leave the group without sending a message - if one want to leave a group, one has to inform the others that they should not sent any messages anymore.
> so, an option does not make sense currently.

You're right. This make perfectly sense
