### ISSUE TITLE
Empty "Settings" window displayed

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#2260]
- Operating System (Linux/Mac/Windows/iOS/Android):
Windows 8.1 Pro.

- Delta Chat Version:
1.20.0.

- Expected behavior:
The "Settings" window displays control elements and input fields.

- Actual behavior:
The "Settings" window is empty.

- Steps to reproduce the problem:
-- Run Delta Chat from scratch.
-- Import a(n Android) backup.
-- Open "Settings" from the three-dot menu.

- Screenshots:
![grafik](https://user-images.githubusercontent.com/51095533/119235134-46c46600-bb31-11eb-83a5-48931e865a2f.png)

- Logs:
N/A.

**Comment by Simon-Laux** [comment]
atleast it isn't a crash anymore...
you got a way to reproduce it reliable?

**Comment by gerryfrancis** [comment]
> you got a way to reproduce it reliable?

@Simon-Laux Yes, please see "Steps to reproduce the problem".

**Comment by Simon-Laux** [comment]
I saw it, just wanted to reassure myself that I read correctly :smile:

**Comment by Simon-Laux** [comment]
Looks like this is a problem of how we load the account after importing it

**Comment by gerryfrancis** [comment]
Thanks, the new portable build works as expected! :+1:
