### ISSUE TITLE
The newly released 1.20.0 still cannot push notifications in Windows 10 (1809 LTSC).

### ISSUE THREAD

**Issue by YamatoRyou** [deltachat/deltachat-desktop#2263]
- Operating System: Windows 10 (x64, 1809, 10.0.17763)
- Delta Chat Version: 1.20.0
- Expected behavior: When the program has no focus or is minimized to the tray, a push notification should be sent to the user when a message is received.
- Actual behavior: When the program has no focus or minimizes to the tray and receives a message, Delta Chat has no notification push.
- Steps to reproduce the problem: Minimize the program, or make it lose focus, and then send a message to the account logged in in the program.
- Screenshots: n/a
- Logs: n/a

------
This issue was reported earlier. #2095

**Comment by Simon-Laux** [comment]
I tested it recently on win7 and it worked there, so this seems windows 10 related.

**Comment by gerryfrancis** [comment]
@YamatoRyou Thanks for your report. In Windows 10, notifications, banners, and sounds can be turned on/off individually. More information here: https://support.microsoft.com/en-us/windows/change-notification-settings-in-windows-10-ddcbbcd4-0a02-f6e4-fe14-6766d850f294

**Comment by YamatoRyou** [comment]
> @YamatoRyou Thanks for your report. In Windows 10, notifications, banners, and sounds can be turned on/off individually. More information here: https://support.microsoft.com/en-us/windows/change-notification-settings-in-windows-10-ddcbbcd4-0a02-f6e4-fe14-6766d850f294
> (For reference, I have checked with my Windows 8.1 Pro system and do not have these many possibilities in there...)

However, Delta Chat does not appear in the system settings.
In order to confirm that I may have manually blocked notifications, I tried to delete all files under %LOCALAPPDATA%\Microsoft\Windows\Notifications, and "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings\electron.app.DeltaChat".
The above operation can restore the manually blocked notification in 20H2, but it is invalid in 1809. That is to say, it is not that I blocked the notification.

**Comment by gerryfrancis** [comment]
> Delta Chat does not appear in the system settings.

@YamatoRyou That might be a known issue. From https://support.delta.chat/t/help-testing-the-upcoming-1-20-x-release/1688 :

> on Windows delta chat does not appear in the list of email clients that you can select as standard ones.

Just a guess whether it is related to your issue or not...

**Comment by Simon-Laux** [comment]
> Just a guess whether it is related to your issue or not...

not related in that point, maybe related in the sense that some registry keys might be missing, but also I don't know if the notification settings are only for UWP/appx apps or also for classical windows application.

**Comment by YamatoRyou** [comment]
> > Delta Chat does not appear in the system settings.
> 
> @YamatoRyou That might be a known issue. From https://support.delta.chat/t/help-testing-the-upcoming-1-20-x-release/1688 :
> 
> > on Windows delta chat does not appear in the list of email clients that you can select as standard ones.
> 
> Just a guess whether it is related to your issue or not...

I just re-tested (including adding a control group (notify-send.exe, first block its notifications, and then use the above methods to restore)).
The result is still the same.
Except for the different system version, the other settings are the same (no matter whether it is 1809 or 20H2, Delta Chat does not appear in the system settings related to notifications).

"No notification push failure under 1809" has appeared since 1.14.x, I am using the portable EXE version.

**Comment by YamatoRyou** [comment]
> > > Delta Chat does not appear in the system settings.
> > 
> > 
> > @YamatoRyou That might be a known issue. From https://support.delta.chat/t/help-testing-the-upcoming-1-20-x-release/1688 :
> > > on Windows delta chat does not appear in the list of email clients that you can select as standard ones.
> > 
> > 
> > Just a guess whether it is related to your issue or not...
> 
> I just re-tested (including adding a control group (notify-send.exe, first block its notifications, and then use the above methods to restore)).
> The result is still the same.
> Except for the different system version, the other settings are the same (no matter whether it is 1809 or 20H2, Delta Chat does not appear in the system settings related to notifications).
> ![{E82FCAD9-7ADD-D3C3-EE29-3216E1CF068A}](https://user-images.githubusercontent.com/48104960/119269307-95552b80-bc29-11eb-85b0-ff3a0e28ba96.png)
> 
> "No notification push failure under 1809" has appeared since 1.14.x, I am using the portable EXE version.

Later, in order to confirm whether this is an isolated phenomenon, I installed a new Windows 10 (x64, 1809) on the virtual machine of another computer. After the system is installed and the notification-related settings are not changed, Delta Chat still cannot push notifications.

**Comment by Simon-Laux** [comment]
Does the non portable version work better?

Also for me it worked in this version:

![image_2021-05-25_15-40-27](https://user-images.githubusercontent.com/18725968/119520667-c729d780-bd7a-11eb-9300-1df9e98198ea.png)
I used the portable version, but I have 1.3.4 version installed, so maybe that makes a difference.

Updated windows to:
```
Edition    Windows 10 Home
Version    20H2
Installiert am    ‎14.‎06.‎2020
Betriebssystembuild    19042.985
Leistung    Windows Feature Experience Pack 120.2212.2020.0
```
and it still works.

So maybe the installation adds some required registry keys :thinking:

**Comment by Simon-Laux** [comment]
Does the non portable version work better?

Also for me it worked in this version:

![image_2021-05-25_15-40-27](https://user-images.githubusercontent.com/18725968/119520667-c729d780-bd7a-11eb-9300-1df9e98198ea.png)
I used the portable version, but I have 1.3.4 version installed, so maybe that makes a difference.

Updated windows to:
```
Edition    Windows 10 Home
Version    20H2
Installiert am    ‎14.‎06.‎2020
Betriebssystembuild    19042.985
Leistung    Windows Feature Experience Pack 120.2212.2020.0
```
and it still works.

So maybe the installation adds some required registry keys :thinking:

**Comment by gerryfrancis** [comment]
@Simon-Laux In this case, Windows 10 Enterprise 2019 LTSC (based on edition 1809 of the "Long-Term Servicing Channel" (LTSC)) is used. According to this article, this is the latest LTSC available from Microsoft to date: https://docs.microsoft.com/en-us/windows/whats-new/ltsc/

**Comment by Simon-Laux** [comment]
I deleted registry keys that contained "DeltaChat", maybe i missed some because the registry editor has really bad ux for that function. But it still worked as expected after uninstalling the installed versions.

@gerryfrancis do you think this could be a problem only in specific windows versions?

**Comment by gerryfrancis** [comment]
@Simon-Laux Maybe the installer does not work correctly in Enterprise editions of Windows 10, but Home and Pro only.

**Comment by YamatoRyou** [comment]
> Does the non portable version work better?
> 
> Also for me it worked in this version:
> 
> ![image_2021-05-25_15-40-27](https://user-images.githubusercontent.com/18725968/119520667-c729d780-bd7a-11eb-9300-1df9e98198ea.png)
> I used the portable version, but I have 1.3.4 version installed, so maybe that makes a difference.
> 
> Updated windows to:
> 
> ```
> Edition    Windows 10 Home
> Version    20H2
> Installiert am    ‎14.‎06.‎2020
> Betriebssystembuild    19042.985
> Leistung    Windows Feature Experience Pack 120.2212.2020.0
> ```
> 
> and it still works.
> 
> So maybe the installation adds some required registry keys

According to my test results here, all updated versions except 1809 LTSC can push notifications (regardless of whether Delta Chat is a portable version or not). Up to now, the Windows 10 versions I have tested are:
❌ 1809 LTSC x64;
✔️ 2004 Pro x64;
✔️ 20H2 Pro x64;
✔️ 21H1 Pro x64

**Comment by gerryfrancis** [comment]
This obviously seems to be an issue with Windows 10 _Enterprise_, as reported here, too: https://support.delta.chat/t/help-testing-the-upcoming-1-20-x-release/1688/13

**Comment by YamatoRyou** [comment]
Since I installed Windows 10 21H2 LTSC, Delta Chat has been able to push messages normally.

**Comment by gerryfrancis** [comment]
@YamatoRyou Thank you for letting us know, much appreciated! :+1:

**Comment by YamatoRyou** [comment]
> @YamatoRyou Thank you for letting us know, much appreciated! +1

But...Under Windows 7, the problem that there is no sound for push notifications still exists, and it is recommended to fix it.

**Comment by gerryfrancis** [comment]
@YamatoRyou Please check out the latest version 1.25.1: https://download.delta.chat/desktop/v1.25.1/DeltaChat%20Setup%201.25.1.exe
If this does not solve your notification sound problem under Windows 7, please open a new issue here. Thanks!
