### ISSUE TITLE
Can scroll sideways in autocrypt-setup dialog

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#2277]
where the numbers are shown in the autocrypt setup dialog, I can scroll sideways. this should not be the case, as then some numbers are obstructed/hidden, while before scrolling to the side I could clearly read them all.
![2021-06-02_10-18](https://user-images.githubusercontent.com/18725968/120448689-16c85e80-c38c-11eb-852c-178730d17b32.png)

also the receiving dialog has a similar sideways scrolling issue:
![2021-06-02_10-18_1](https://user-images.githubusercontent.com/18725968/120448673-1334d780-c38c-11eb-94aa-72c31828aaa8.png)

**Comment by cavesdev** [comment]
Working on this too.
