### ISSUE TITLE
Too many Notifications

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#2278]
I just opened deltachat and had around 300 new messages. And i got wayyy to many notifications about new messages. Not sure how we can debounce this in a smart way, but definetly something has to improve.

**Comment by r10s** [comment]
isn't that also a bit related to the used os? on mac, the situation is quite fine, this looks typically like the following:

![Screen Shot 2021-06-02 at 16 27 28](https://user-images.githubusercontent.com/9800740/120499480-5dd04700-c3c0-11eb-9627-40e37cffd49b.png)

would be interesting how windows behaves here.

however, grouping seems to be missing; notifications are not grouped by chat, at least this is not visible to me. maybe adding that bit already helps other os to display things better.

**Comment by YamatoRyou** [comment]
I have observed that the desktop version pops up at most 3 notifications at a time, the fourth pops up after the first disappears, the fifth pops up after the second disappears, and the sixth pops up after the third disappears. And so on.
For multiple messages received from the same contact after startup, it can be displayed as:
"Yyy messages from xxx."
The contact's avatar is displayed on the left side of the notification entry.

For multiple messages received from different contacts after startup, it can be displayed as:
"Messages from x contacts, yyy total."
The left side of the notification entry shows the avatars of several contacts, usually 2~4. Multiple avatars can be stacked or displayed in a 2*2 matrix.

In addition, the tray icon should be marked with eye-catching marks.

The above experience results were obtained in Windows 7.
You can refer to the method of handling a large number of notifications in the desktop version of Telegram:
Provide a floating button with multiple notification entries at the same time, click it to clear all notifications at once.

**Comment by Jikstra** [comment]
I guess it really depends on the os/desktop environment. On KDE/Plasma this is the case.

**Comment by Simon-Laux** [comment]
Maybe check if there are already multiple messages for that chat before creating the notification and then clearing the old notifications for that chat and state that there are more new messages in the displayed notification.

**Comment by missytake** [comment]
I have a problem which I think only appears since 1.22 where every incoming message causes multiple notifications... yesterday it was 4, now it's at 6 notifications per message. Could this be related? Otherwise I'll just open a new issue.

**Comment by Frando** [comment]
I reopened Deltachat Desktop after not using it for two months, and had my screen filled with notifications for about 2 minutes. Each and every new message seemed to trigger a new notification. I am using a very simple desktop notification system called `dunst` which does not group notifications by default. Can we add something to Deltachat Desktop to just omit all notifications for new messages that are coming in in the first X minutes after startup? I expect new messages, and not notifications, when I open the app.

**Comment by Jikstra** [comment]
> I reopened Deltachat Desktop after not using it for two months, and had my screen filled with notifications for about 2 minutes. Each and every new message seemed to trigger a new notification. I am using a very simple desktop notification system called `dunst` which does not group notifications by default. Can we add something to Deltachat Desktop to just omit all notifications for new messages that are coming in in the first X minutes after startup? I expect new messages, and not notifications, when I open the app.
> 
> This really makes Deltachat Desktop a bit annoying to use for me, likely the more so due to my simplistic desktop notification handler. However, Deltachat Desktop is the only app I ever used on my linux desktop that pushes these amounts of notifications and leads to these walls of notifications. All other messengers (Signal, Telegram, Discord, Element, Thunderbird) never push more than a single notification when starting the app.

I think a dc core function ala "dc_did_initial_sync()" would be very helpful for this. Basically this function returns true if core read/received all messages after the first connection to the imap server.

**Comment by Jikstra** [comment]
Actually there is a related core pr that would implement a new event that would inform us about message bunches. I guess with this we could implement something a lot less spammy. https://github.com/deltachat/deltachat-core-rust/pull/3643
