### ISSUE TITLE
two different "about dialogs"

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2280]
on mac, there are two menu entries named "About Delta Chat", each opening different dialogs.

the one is in the "Delta Chat" menu, the other in the "Help" menu:

<img width=400 src=https://user-images.githubusercontent.com/9800740/120503413-932a6400-c3c3-11eb-8352-25bc49da122f.png> <img width=400 src=https://user-images.githubusercontent.com/9800740/120503421-945b9100-c3c3-11eb-886e-f27e6881247a.png>

![Screen Shot 2021-06-02 at 16 47 31](https://user-images.githubusercontent.com/9800740/120502915-2020ed80-c3c3-11eb-833f-3e55b3a64e08.png)

i think, this is a bit confusing, esp. when guiding users to some debug information. also, it looks weird :)

i think, in general, it is okayish to keep both entries, however, they should open the same dialog.

i assume there is some hook in electron, handling this special "Delta Chat / About Delta Chat" entry.

**Comment by Jikstra** [comment]
The one is from mac os i think, looks like a native dialog.

**Comment by r10s** [comment]
> The one is from mac os i think, looks like a native dialog.

the menu-entry itself is created by Apple, one cannot suppress that afaik. 

the dialog, however, i assume, is created by Electron. and i assume one can also do something else instead - eg. Signal seems to show a more fancy dialog there. so, maybe it is just some event to catch.

**Comment by r10s** [comment]
> or declaring the help/about entry as such.

seems to be that one.

https://www.electronjs.org/docs/api/menu#standard-menus says: 

> macOS has provided standard actions for some menu items, like About xxx, Hide xxx, and Hide Others. To set the action of a menu item to a standard action, you should set the role attribute of the menu item.

somthing like that is already done at https://github.com/deltachat/deltachat-desktop/blob/ae5c04b9d57351378385ada98405db0d879fb42c/src/main/menu.ts#L156 , not sure, why that is not working.
