### ISSUE TITLE
empty lines not working in status/signature

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2287]
with closing https://github.com/deltachat/deltachat-desktop/issues/2271, linebreaks and links were introduced in the status/signature field.

however, _empty lines_ (so, two linebreaks) are not working as expected.

example: the same status/signature on desktop and ios:

<img width=320 src=https://user-images.githubusercontent.com/9800740/121395104-5544b700-c952-11eb-886d-3ae85dec2f25.png> &nbsp; &nbsp; &nbsp;  <img width=230 src=https://user-images.githubusercontent.com/9800740/121395098-54ac2080-c952-11eb-8a0c-91a25d266036.png>

when on that, consider also to tune down the links, making them appear the same way as other user-generated links (so, just text-color and underline, this is [also wrong on android](https://github.com/deltachat/deltachat-android/issues/1950) btw).

**Comment by Simon-Laux** [comment]
closed by #2409
