### ISSUE TITLE
on show_emails=all, open contact-request-chat; badge-counter

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2288]
if all emails are handled by Delta Chat, there will typically be much more "contact requests" as usual.

handling these contact requests in the stacked way, one by one, is some pain.

for a first improvement, on [android](https://github.com/deltachat/deltachat-android/issues/1896)/[ios](https://github.com/deltachat/deltachat-ios/pull/1177) with show_emails=all, we just open the contact-request-chat directly, the user can pick a contact request from there.

this is a very small change with some effect and a huge improvement. it is not a perfect contact-request solution, there are "larger" ideas around, however, as said, quite simple to do. further improvements can come anyway.

there is also a bug: at least i could never make the contact requests chatlist-item disappear, probably, there is a "makenoticed" missing.

once, that is done, i think we can also add the contact-request-badge-counter from https://github.com/deltachat/deltachat-core-rust/pull/2493

**Comment by link2xt** [comment]
Why not always open the chat, even without `show_emails=all`? Maintaining and testing multiple workflows is difficult. And if users observes different behavior, e.g. on their friends laptop, they will have hard time figuring out why their device has a different contact requests workflow, as it is completely non-obvious that it depends on the "show all emails" setting.

**Comment by r10s** [comment]
> Why not always open the chat, even without show_emails=all?

yip, i am not against that, we can do so. we did not do that on android at the first thing to not change workflow for "chat only" and to get a "feeling" first :) but i agree, we can change that also on android/ios.

**Comment by link2xt** [comment]
I was not even aware that android has a different workflow for chat-only.

**Comment by r10s** [comment]
> I was not even aware that android has a different workflow for chat-only.

did you use `show_emails=all`?

**Comment by link2xt** [comment]
I have classic emails enabled, thought the flow was changed to always open the chat.

**Comment by r10s** [comment]
closing this, as the discussion around contact requests is [already moving forward](https://support.delta.chat/t/show-all-classic-emails-no-requests/1584/13), it does not make much sense to do this intermediate step.
