### ISSUE TITLE
pictures without description are not shown in chat view

### ISSUE THREAD

**Issue by IT-Ing** [deltachat/deltachat-desktop#2292]
when receiving an image without an addition description it ist not shown in the chat window but it is shown in the images overview view.

steps to reproduce:
send an image with a description.
send another image without a description.
compare chat view and media overview

**Comment by IT-Ing** [comment]
ok... Version 1.15.5 (1.15.5) on macOS 11.4

**Comment by Jikstra** [comment]
Can you try 1.20.2?

**Comment by IT-Ing** [comment]
Solved! THX!
