### ISSUE TITLE
Update to latest deltachat-node

### ISSUE THREAD

**Issue by karissa** [deltachat/deltachat-desktop#23]
The newest deltachat-node has a different method for initializing the repository, let's use that instead.

**Comment by ralphtheninja** [comment]
@karissa I could try giving this a shot if you like. It would force me to learn more about this code base. Probably quicker if you do it though.

**Comment by karissa** [comment]
@ralphtheninja it would be good for you to take a look if you want!

This is where the desktop wrapper for deltachat-node is initialized: 
https://github.com/deltachat/deltachat-desktop/blob/master/src/main/ipc.js#L46-L51

`init` is called with the email and password when someone logs in:
https://github.com/deltachat/deltachat-desktop/blob/master/src/renderer/components/Login.js#L32-L39

This is where configuration currently happens: 
https://github.com/deltachat/deltachat-desktop/blob/master/src/main/deltachat.js#L85

**Comment by ralphtheninja** [comment]
I'll have a look tomorrow.
