### ISSUE TITLE
wrong mail address

### ISSUE THREAD

**Issue by MrMini1025** [deltachat/deltachat-desktop#2306]
- Operating System (Linux/Mac/Windows/iOS/Android): Linux
- Delta Chat Version: Version 1.20.3 (git: v1.20.3)
- Expected behavior: Login and work **(the email addresses are valid as per RFC 5322)**
- Actual behavior: it doesn't work with tld domains
- Steps to reproduce the problem: use email with tld domain in login like **bob@mymail**
- Screenshots: 
![Screenshot_20210711_231932](https://user-images.githubusercontent.com/19595503/125209211-ff8c6300-e29f-11eb-862c-e8a7a73615b3.png)

**Comment by link2xt** [comment]
Fixed by #2317?

**Comment by Jikstra** [comment]
@link2xt yes should be
