### ISSUE TITLE
Zooming into an image in FullscrenMediaView

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#2308]
would be useful to have for big images.

**Comment by r10s** [comment]
yip, that'd be useful. maybe that can be targeted together with https://github.com/deltachat/deltachat-desktop/issues/1539, which seems to be even more basic.

**Comment by Jikstra** [comment]
Fixed by https://github.com/deltachat/deltachat-desktop/pull/2516
