### ISSUE TITLE
[DEP0062] `node --debug` and `node --debug-brk` are invalid

### ISSUE THREAD

**Issue by jchook** [deltachat/deltachat-desktop#2315]
Hello, thanks for making delta-chat. When trying to set-up a local dev environment, I ran into an issue launching electron.

- Operating System (Linux/Mac/Windows/iOS/Android): Linux
- Delta Chat Version: master (v1.20.3)
- Expected behavior: Able to start electron with `npm run start`
- Actual behavior: Electron exits with a deprecation notice and status 9
- Steps to reproduce the problem: 

1. Clone the project
2. `npm ci` to install dependencies
3. `npm run start` to launch electron
4.  See that electron exits with status 9 and a deprecation notice

I can also reproduce by running the electron command manually:

```sh
electron . --debug --log-debug --log-to-console --disable-http-cache --translation-watch
echo $? # 9
```

- Screenshots:
- Logs:

```
electron: [DEP0062]: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` and `node --inspect-brk` instead.
```

---

I temporarily solved the issue the issue by replacing the `--debug` flag from the `start` script in package.json with `--inspect`.

**Comment by jchook** [comment]
Separately I encountered this error, which prevented `npm run watch` from working:

```
> deltachat-desktop@1.20.3 watch:shared /home/jchook/forks/deltachat-desktop
> npm run watch:shared:translations

npm ERR! missing script: build:frontend:source_map_support
npm ERR!
npm ERR! Did you mean one of these?
npm ERR!     build:frontend:source-map-support
npm ERR!     build:frontend:themes
npm ERR!     build:frontend:scss
```

I fixed this by updating the script in package.json...

```diff
-     "watch:frontend": "npm run build:frontend:source_map_support && npm run watch:frontend:ts & npm run watch:frontend:static & npm run watch:frontend:scss",
+     "watch:frontend": "npm run build:frontend:source-map-support && npm run watch:frontend:ts & npm run watch:frontend:static & npm run watch:frontend:scss",
```

**Comment by Simon-Laux** [comment]
which node version did you use? we only tested with version 12.

**Comment by jchook** [comment]
I tried node 10, 12, and 14.

Looks like `--debug` and `--debug-brk` have been [deprecated since Node v7.7.0](https://nodejs.org/en/docs/guides/debugging-getting-started/#legacy-debugger)

**Comment by Jikstra** [comment]
Is this fixed?

**Comment by Simon-Laux** [comment]
strange, which version of electron are you using?
I don't get that error somehow.

Anyways, the `--debug` we use is not meant for node debugging but for triggering our debug logging (a shortcut for `--log-debug` & `--log-to-console`) maybe we should rename it if it conflicts with electron/node -arguments.
