### ISSUE TITLE
Switching Accounts too cumbersome

### ISSUE THREAD

**Issue by porky11** [deltachat/deltachat-desktop#2331]
- Operating System (Linux/Mac/Windows/iOS/Android): Linux
- Delta Chat Version: 1.20.3

I have multiple E-Mail addresses and want to use multiple of them at a time.

I can't run multiple instances of Delta Chat at the same time:

```
Only one instance allowed. Quitting.
```

I know, you can switch between email addresses using the tab at the top right, but that's slow.
I think, there are multiple reasons for that:

* three clicks required to switch selected address
* small animations after clicking the button, which take just about 0.2 seconds, but slows the process down anyway
* first two clicks on the top right, third click in the center of the app
* contacts on the left, while the button to switch is on the right

Instead of fixing these problems, I'd prefer to see all contacts of all my email addresses at once, similar to how common email clients work.
The contacts could be sorted by address and have small headers inbetween, which shows the email address, they belong to.
Maybe you would still have a currently active address, so adding new contacts and groups etc. applies to a single address only.

Or the simplest quickfix: Just allow multiple instances of DeltaChat

**Comment by Jikstra** [comment]
1. You can run multiple instances of deltachat if you run it like this `deltachat --multiple-instances`
2. With the new accounts api all accounts will be connected simultanously. We will probably also overhaul the ui to make switching between accounts easier, or receiving notifications of all accounts on the same time
3. searching through contacts of all accounts could be interesting, but for the beginning mixing things between accounts will be unlikely i guess, but maybe @r10s has an idea for this problem

**Comment by Darthagnon** [comment]
Suggestion for multi-account UI: [Jami](https://jami.net/) has a really nice-looking account switcher; the current searchbox could become a popout from a search button. For sorting emails from all accounts, some sort of Discord/[Nheko](https://github.com/Nheko-Reborn/nheko)-style sidebar could be an idea (though I don't really like sidebars, Nheko's one with tags/Matrix rooms works quite well)
