### ISSUE TITLE
option to get from memberlist to user's profile missing

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2343]
i think a click on a member in group's memberlists should open the profile of the contact as on android/ios.

this way, one can "browse" groups much better and one can also send a message to a member without much hassle.

for "browsing", however, it should be possible to go back to the group's profile - so, "Cancel" or "Ok" should bring you back there. at best, the contact-profile lies over the group-profile and the group-profile is still a bit visible, might be complicated in the current environment, not sure.

**Comment by Simon-Laux** [comment]
closed by #2381
