### ISSUE TITLE
tune down chat requests

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2352]
chat requests should not appear as "strong" as other unread messages, with some chance, they're just spam.

therefore, do not show them in bold and do not show an unread counter (that always says, there is something to do :)

this is what we're doing on android/ios and what was discussed that time, cmp https://github.com/deltachat/deltachat-android/issues/1990 , would be great, if desktop just behaves the same here.

eg. this view is much too bold:

<img width=320 src=https://user-images.githubusercontent.com/9800740/132726773-dd77630d-8fb5-4200-bdd5-7b45f385f270.png>

**Comment by Simon-Laux** [comment]
could you also post a screenshot of andoid how it should look like?

**Comment by r10s** [comment]
> could you also post a screenshot of andoid how it should look like?

it is just  without the counters and the summary-text is not bold.

**Comment by r10s** [comment]
ah, and when on that: i'd swap `[Archived]` and `[Request]` tags - looks more sorted that way, esp. when the counter is gone. also, that is in sync with android/ios then.

**Comment by Jikstra** [comment]
> leaving out the "unread" marks (bold, counter) has also the advantage that that covers the bug that opening a chat request does not mark the things as seen (so that bold/unread goes away) - this is currently not possible on desktop (not sure if that is related to desktop, node or core, however)

They are getting marked as read, but you need to load them. So if a chat has 40 new messages, and you only load the last 30, the 10 before will still stay there as unread. But with new messagelist that will be different anyways, as it will jump to the first unread message anyways.

**Comment by r10s** [comment]
> So if a chat has 40 new messages, and you only load the last 30, the 10 before will still stay there as unread.

this is about [`dc_markseen_msgs()`](https://c.delta.chat/classdc__context__t.html#ae5305a90c09380dffe54e68c2a709128), `dc_markseen_msgs()` does nothing on chat requests (i just checked [the code](https://github.com/deltachat/deltachat-core-rust/blob/master/src/message.rs#L1461)).

what should be called unconditionally when a chat is opened, and probably is missing is [`dc_marknoticed_chat()`](https://c.delta.chat/classdc__context__t.html#a7286128d6c3ae3f274f72241fbc4353c).

but anyway, the unread-counter should not be displayed anyway for now for reasons mentioned above.

**Comment by Jikstra** [comment]
> what should be called unconditionally when a chat is opened, and probably is missing is dc_marknoticed_chat().

Yup i never implemented that as i then dont know how many messages i didnt read yet. We can tweak that with the new messagelist, before that i wouldnt touch it.
