### ISSUE TITLE
Wrong install path suggested in setup under Windows

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#2356]
- Operating System (Linux/Mac/Windows/iOS/Android):
Windows 8.1 Pro.

- Delta Chat Version:
1.21.0.

- Expected behavior:
For installations in the Windows current user's profile, Delta Chat setup shall suggest the correct path (which is the one that always has been used before), it is `C:\Users\[CURRENT_USER]\AppData\Local\DeltaChat` .

- Actual behavior:
Delta Chat setup suggests a different path than the older setups did before: `C:\Users\[CURRENT_USER]\AppData\Local\Programs\DeltaChat` . (The part `Programs\` should not be there.) This could have negative consequences after un- and reinstalling Delta Chat, because the app might not find the profile data that already exists.

- Steps to reproduce the problem:
-- Start setup and choose to install for the current user, then click "Next".

- Screenshots:
N/A.

- Logs:
N/A.

**Comment by Simon-Laux** [comment]
the program directory and userdata directory are not the same,  did it really change?

**Comment by gerryfrancis** [comment]
> did it really change?

@Simon-Laux Yes, definitely, please compare with versions <1.21.0.

**Comment by hhrhhr** [comment]
> (The part Programs\ should not be there.)
I do not quite understand why this should not be here?
The user can choose any other location, the program may read this location with further update.

**Comment by Simon-Laux** [comment]
![vergleich](https://user-images.githubusercontent.com/18725968/133893693-1f2f4fe5-0d1e-4634-a2c5-a68661c31869.PNG)

left: 1.20.3; right: 1.21.0 -> user installation with the preset-settings

Nothing changed except for that you can now change the path where it should be installed to.

`C:\Users\[CURRENT_USER]\AppData\Local\DeltaChat` is the data directory not the installation directory.
I think you might have confused those two.

**Comment by gerryfrancis** [comment]
Thanks for checking, it seems I got confused and thought of just one folder for the program (app) and data. My bad, sorry.

However, I am thankful for this because I just found a real critical after I uninstalled the app from `C:\Users\[CURRENT_USER]\AppData\Local\DeltaChat` : My data was gone, too. (I have had a backup.) It is a "golden rule" not to delete the data of an app during uninstall! Therefore we have to ensure that the user must not install the app in the data folder by accident.

**Comment by Simon-Laux** [comment]
> Therefore we have to ensure that the user must not install the app in the data folder by accident.

cost benefit ratio is too low, so an issue for it would likely be closed with the `wont-fix` tag.

Only thing we could do is to remove the option to choose install path, that way we prevent users from making errors there.

**Comment by gerryfrancis** [comment]
> cost benefit ratio is too low, so an issue for it would likely be closed with the wont-fix tag.

@Simon-Laux Sorry, I do not second that. If an uninstall of Delta Chat means that data might be removed, too, the user must be informed about it, which is absolutely mandatory and the least we can do, although it is very bad practice during uinstall, unless the user confirms to wipe personal data, too.
