### ISSUE TITLE
Follow-up test on pasting images in Windows desktop version.

### ISSUE THREAD

**Issue by YamatoRyou** [deltachat/deltachat-desktop#2380]
#2378
Version: 1.22.2 (git: v1.20.3-198-g6bd4fb40)
If you copy an image from a file browser (explorer), if the file name has the following characteristics, the paste will fail:

```
%3F.gif
%41.jpg
%4A.webp
%44.png
```

When the extension is BMP, it is not affected by the above features, and this type of file will be automatically pasted into the chat in the form of a file.
If an image with the above characteristics is opened in a browser and copied from the browser, it can be pasted into the chat normally.

**Comment by maxphilippov** [comment]
I know it's been a long time, but can you confirm if it's still happening? Which version of Windows are you using?
Correct me if I got it wrong:
- you're talking about doing pressing Ctrl+c in Windows Explorer and then pasting to DeltaChat
- filenames should end with these strings or these are exact strings? Should it be encoded that way or non-encoded version doesn't work too (%44.png and D.png)

**Comment by YamatoRyou** [comment]
> I know it's been a long time, but can you confirm if it's still happening? Which version of Windows are you using? Correct me if I got it wrong:
> 
> * you're talking about doing pressing Ctrl+c in Windows Explorer and then pasting to DeltaChat
> * filenames should end with these strings or these are exact strings? Should it be encoded that way or non-encoded version doesn't work too (%44.png and D.png)

The operating system is 64-bit Windows 7.
At that time, it was found that as long as the file name contains a character string with the above characteristics (a percent sign and 2 hexadecimal characters), the paste must fail.

As of now I've retested 1.34.3 and found that the glitch has gone away.
