### ISSUE TITLE
Spellchecker missing on xubuntu 20.4

### ISSUE THREAD

**Issue by vexillia** [deltachat/deltachat-desktop#2389]
- Operating System (Linux/Mac/Windows/iOS/Android): xubuntu 20.4
- Delta Chat Version: Version 1.20.3 (git: v1.20.3)
- Expected behavior: Global spellchecker highlights misspelling.
- Actual behavior: Nothing.
- Steps to reproduce the problem: Type a message.

**Comment by Simon-Laux** [comment]
unless electron addresses https://github.com/electron/electron/issues/27403 there is not much we can do, moving to project resurrection for now
