### ISSUE TITLE
Arch Compile Fail: aur/deltachat-desktop 1.22.2-1 (+11 0.34) 

### ISSUE THREAD

**Issue by nobicycle** [deltachat/deltachat-desktop#2421]
- Operating System (Linux/Mac/Windows/iOS/Android):
-  uname -a
Linux tower 5.10.70-1-MANJARO #1 SMP PREEMPT Thu Sep 30 15:29:01 UTC 2021 x86_64 GNU/Linux

- Delta Chat Version:
 1.22.2-1

- Actual behavior:
- Compile fail
-npm verb npm  v8.0.0
npm ERR! code 1
npm ERR! path /home/user/System/Manjaro/yay/deltachat-desktop/src/deltachat-desktop-1.22.2/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! RequestError: read ECONNRESET
npm ERR!     at ClientRequest.<anonymous> (/home/user/System/Manjaro/yay/deltachat-desktop/src/deltachat-desktop-1.22.2/node_modules/got/source/request-as-event-emitter.js:178:14)
npm ERR!     at Object.onceWrapper (node:events:510:26)
npm ERR!     at ClientRequest.emit (node:events:402:35)
npm ERR!     at ClientRequest.origin.emit (/home/user/System/Manjaro/yay/deltachat-desktop/src/deltachat-desktop-1.22.2/node_modules/@szmarczak/http-timer/source/index.js:37:11)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:447:9)
npm ERR!     at TLSSocket.emit (node:events:390:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm verb exit 1

- Steps to reproduce the problem:
-yay -S deltachat-desktop

- Logs:
[2021-11-17T23_47_23_379Z-debug.log](https://github.com/deltachat/deltachat-desktop/files/7558720/2021-11-17T23_47_23_379Z-debug.log)

**Comment by Jikstra** [comment]
We are not maintaining deltachat-desktop, actually i'm not sure how does it. But I personally maintain the deltachat-desktop-git AUR package, so feel free to use that. Obviously it gives you the latest git version.

**Comment by nobicycle** [comment]
> Actually it would be nice to have deltachat-desktop in the official arch repos at some day?

I checked - the procedure seems described here: https://wiki.archlinux.org/title/Official_repositories

Thanks for the help.
I will use your AUR
