### ISSUE TITLE
When opening the main interface from the tray icon, the interface is blank, and the memory usage continues to increase.

### ISSUE THREAD

**Issue by YamatoRyou** [deltachat/deltachat-desktop#2426]
- Operating System (Linux/Mac/Windows/iOS/Android): x64 Windows 7
- Delta Chat Version: 1.22.2 (v1.20.3-198-g6bd4fb40)
- Expected behavior: n/a
- Actual behavior: 
1. Sometimes, when you double-click the tray icon to open the main interface, the interface is blank. The menu in the window can still respond to basic operations such as user clicks.
![{F8B31D3C-3BDF-FEAE-E713-F745DD3F898D}](https://user-images.githubusercontent.com/48104960/142771700-b8c017b0-ad42-45f4-a7cc-57c7ce72a48f.png)
2. If you exit DeltaChat at this time, you can find from the task manager that a process still exists, and this process will use up the remaining physical memory of the computer little by little (the time when the memory is exhausted depends on the remaining memory size).
![{F716844E-62BF-0A73-0AC1-53EBED766276}](https://user-images.githubusercontent.com/48104960/142771714-5a8be92c-859a-4c79-bcbf-55da652e1187.png)
![{0D267999-1E52-225E-D465-878D668DB653}](https://user-images.githubusercontent.com/48104960/142771726-af077664-d0b6-4496-a8fd-793fb7f807b8.png)
![{D52F9A60-ACDF-31EE-4C65-AF7FB7085522}](https://user-images.githubusercontent.com/48104960/142777347-a1c2a336-4147-4755-aafb-ff126fe9db58.png)

Memory usage trends of residual processes:
![{8CFF9D11-3FCB-D4DD-C1C9-840FADC49FD8}](https://user-images.githubusercontent.com/48104960/143349086-b4a5bd78-5f11-40ac-b530-f8ec31364577.png)
![{6B8759A1-03DB-475C-8290-D2FE14B12909}](https://user-images.githubusercontent.com/48104960/143349140-46a24a7f-9eb4-4847-aac6-8369b123327c.png)
![{61C3A0EE-8A94-8C4D-3B53-10B856312F72}](https://user-images.githubusercontent.com/48104960/143349234-d1edd7bd-be51-43a4-9bb8-6046e84cf6c7.png)
![{0E3A0951-4E0B-23A2-C1C1-15CF714DDE6C}](https://user-images.githubusercontent.com/48104960/143349289-9793c028-bf20-479a-8ed1-e29c164d4ece.png)

This was discovered by accident about a day ago, and the memory was almost exhausted. Finally, it ended up manually terminating the remaining processes.

- Steps to reproduce the problem: Double-click the tray icon
- Screenshots: n/a
- Logs: n/a

**Comment by Jikstra** [comment]
Is any error shown in the Console tab of the Developer Console? I have the feeling this could be an electron & windows 7 problem.

**Comment by YamatoRyou** [comment]
> 开发者控制台的控制台选项卡中是否显示任何错误？我感觉这可能是电子和 Windows 7 的问题。



> Is any error shown in the Console tab of the Developer Console? I have the feeling this could be an electron & windows 7 problem.
In my impression, the console did not output an error.
This problem is not 100% triggered, and it may take a few days for the next occurrence.

**Comment by r10s** [comment]
after updating to mac 1.25, my screen stays white as well, always, not related to tray icon, just after start.

not sure if that is the same issue, however, i could also observe the memory usage increasing "little by little", from 44.6 to 45.1 within 10 minutes, however, that may also be normal by the gc.

![1638217991 776021](https://user-images.githubusercontent.com/9800740/143940860-5f2ea65f-d86b-42f5-9d5e-527568556734.jpg)
.

**Comment by Simon-Laux** [comment]
@r10s that's a completely different issue, caused by a mistake in the release script, fixed in https://download.delta.chat/desktop/v1.25.1/

**Comment by Jikstra** [comment]
> > Is any error shown in the Console tab of the Developer Console? I have the feeling this could be an electron & windows 7 problem.
> 
> ![{ADCCAE78-3561-A5B3-6958-467C4B3A49BC}](https://user-images.githubusercontent.com/48104960/143322759-8dda9ca5-cef4-439c-bfc7-78602769cd2d.png)

Hmm can you start DeltaChat.exe with --debug from the cmd?

**Comment by YamatoRyou** [comment]
> > > Is any error shown in the Console tab of the Developer Console? I have the feeling this could be an electron & windows 7 problem.
> > 
> > 
> > ![{ADCCAE78-3561-A5B3-6958-467C4B3A49BC}](https://user-images.githubusercontent.com/48104960/143322759-8dda9ca5-cef4-439c-bfc7-78602769cd2d.png)
> 
> Hmm can you start DeltaChat.exe with --debug from the cmd?

It may take a few days to encounter this problem next time...

**Comment by YamatoRyou** [comment]
> > > Is any error shown in the Console tab of the Developer Console? I have the feeling this could be an electron & windows 7 problem.
> > 
> > 
> > ![{ADCCAE78-3561-A5B3-6958-467C4B3A49BC}](https://user-images.githubusercontent.com/48104960/143322759-8dda9ca5-cef4-439c-bfc7-78602769cd2d.png)
> 
> Hmm can you start DeltaChat.exe with --debug from the cmd?

Since this issue has not appeared in the last week, I will close this issue. I will add it if it reoccurs in the future.

**Comment by YamatoRyou** [comment]
> > > Is any error shown in the Console tab of the Developer Console? I have the feeling this could be an electron & windows 7 problem.
> > 
> > 
> > ![{ADCCAE78-3561-A5B3-6958-467C4B3A49BC}](https://user-images.githubusercontent.com/48104960/143322759-8dda9ca5-cef4-439c-bfc7-78602769cd2d.png)
> 
> Hmm can you start DeltaChat.exe with --debug from the cmd?

Just now, it has been reproduced on 1.25.1.

![{B22B6286-ADAF-B91A-6761-3EFBBBC633EF}](https://user-images.githubusercontent.com/48104960/145635968-d46310b1-ecea-4d97-b33c-e51e882351a8.png)
Log (desensitized): [{86AFEB7F-9BAE-768B-B3F5-34D488A6D22A}.zip](https://github.com/deltachat/deltachat-desktop/files/7695224/86AFEB7F-9BAE-768B-B3F5-34D488A6D22A.zip)

**Comment by YamatoRyou** [comment]
> > > Is any error shown in the Console tab of the Developer Console? I have the feeling this could be an electron & windows 7 problem.
> > 
> > 
> > ![{ADCCAE78-3561-A5B3-6958-467C4B3A49BC}](https://user-images.githubusercontent.com/48104960/143322759-8dda9ca5-cef4-439c-bfc7-78602769cd2d.png)
> 
> Hmm can you start DeltaChat.exe with --debug from the cmd?

I may have found the reason.
I am using a screen recording software: https://mirillis.com/en/products/action.html
When recording starts, the Delta Chat UI may go blank.
Since I've given up on Delta Chat and moved to Matrix + Element, I had the same problem with Element while trying out the desktop version of Element (the trigger condition is also to open a window from the tray icon). That is, screen recording software or Electron may be is the cause of this problem.
Once a blank appears, only the corresponding client can be restarted.
I will close this topic.
