### ISSUE TITLE
set DC_STR_SETUP_CONTACT_QR_DESC and DC_STR_SECURE_JOIN_GROUP_QR_DESC

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2431]
just a reminder to a void a translation regression, please close if already done :)

cmp https://github.com/deltachat/deltachat-ios/pull/1403/files

**Comment by Simon-Laux** [comment]
done in https://github.com/deltachat/deltachat-desktop/pull/2420
