### ISSUE TITLE
Yggmail addresses overflow account deletion dialog

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#2432]
likely fixable with only css

<img width="843" alt="Screenshot 2021-11-25 at 03 53 27" src="https://user-images.githubusercontent.com/18725968/143371717-1837538a-c5e9-4049-b708-309807352487.png">

**Comment by Abhijnan-Bajpai** [comment]
Hey @Simon-Laux! I would like to work this, could I be assigned?

**Comment by r10s** [comment]
@Abhijnan-Bajpai i just assigned you, thanks a lot for taking care! for questions on desktop, however, you're right to ping @Simon-Laux, however, the desktop team is currently a bit busy with releases :)

**Comment by Abhijnan-Bajpai** [comment]
> @Abhijnan-Bajpai i just assigned you, thanks a lot for taking care! for questions on desktop, however, you're right to ping @Simon-Laux, however, the desktop team is currently a bit busy with releases :)

Oh no problem, I'll try figuring this out myself meanwhile.

**Comment by Jikstra** [comment]
> > @Abhijnan-Bajpai i just assigned you, thanks a lot for taking care! for questions on desktop, however, you're right to ping @Simon-Laux, however, the desktop team is currently a bit busy with releases :)
> 
> Oh no problem, I'll try figuring this out myself meanwhile.

Awesome :)
