### ISSUE TITLE
Quote should use summary text instead of just text

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#2434]
Because currently when quoting an document or and image without any text set it shows an empty qoute:
<img width="170" alt="Screenshot 2021-11-22 at 01 18 52" src="https://user-images.githubusercontent.com/18725968/143489747-dd1fcc54-fadf-40b8-bf93-b38234e4954a.png">

**Comment by r10s** [comment]
afaik, the idea is to use always `dc_msg_get_quoted_text()` for the text to display. if that is empty or null, there is no quote by definition.

`dc_msg_get_quoted_msg()` may be used to enrich the quote then.
