### ISSUE TITLE
Styling for signature textarea needed 

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#2442]
because it looks strange in dark theme:

<img width="496" alt="Screenshot 2021-11-28 at 22 28 30" src="https://user-images.githubusercontent.com/18725968/143786804-89cc5067-3afb-4440-9d6b-a7c09ca8f04a.png">

**Comment by ejgonzalez17** [comment]
Hello, I would like to contribute by making this issue

**Comment by ejgonzalez17** [comment]
Hello, I worked on this issue and in the pull request I attached an image where the "Delete Profile Image" button is shown when it is disabled in the different themes, taking care that the bug one did not happen again. I will be attentive to your comments.

**Comment by Jikstra** [comment]
@ejgonzalez17 looking at this issue again, @Simon-Laux probably was talking about the textarea element, but nevertheless the disabled Delete profile image button looked horrible too ^^

**Comment by ejgonzalez17** [comment]
What could be some guides of what would be the correct style for textarea?

**Comment by Jikstra** [comment]
> What could be some guides of what would be the correct style for textarea?

I would say making it similiar to the "Your name" inout field. So `color: var(--bp3InputText)` and a transparent background. Maybe even adding this white border-bottom?

**Comment by ejgonzalez17** [comment]
I changed the background and also added to your color var (- mp3 OutputText), Here is what it would look like, is that ok?
<img width="589" alt="Screen Shot 2022-01-06 at 10 03 19 AM" src="https://user-images.githubusercontent.com/70716664/148412283-9f19a23f-3eab-45a5-8a2b-01854715fd47.png">

**Comment by Jikstra** [comment]
@ejgonzalez17 looks really good :+1:

**Comment by ejgonzalez17** [comment]
Okay, I'll proceed to do the Pull Request =)
