### ISSUE TITLE
Search results cannot jump to the message body and context.

### ISSUE THREAD

**Issue by YamatoRyou** [deltachat/deltachat-desktop#2448]
- Operating System: x64 Windows 7
- Delta Chat Version: 1.22.1 & 1.25.1
- Expected behavior: When you click the search result, you should jump to the corresponding message body and display the context of this message.
- Actual behavior: Only the message details can be displayed when you click the search result.
- Steps to reproduce the problem: Type in keywords to get search results; click on a search result.
- Screenshots: 
![{4F7B314F-6737-30F9-B4AE-F37626DD1252}](https://user-images.githubusercontent.com/48104960/144118296-5f0ed3f3-c097-45f1-b6a1-d9cb317f74b5.png)

- Logs: n/a

**Comment by Jikstra** [comment]
Yes this is a missing feature. I will hopefully find time to implement this soon :)

**Comment by Jikstra** [comment]
@YamatoRyou we can leave it open :)
