### ISSUE TITLE
Localization issues

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#2451]
- Operating System (Linux/Mac/Windows/iOS/Android):
Windows 8.1 Pro.

- Delta Chat Version:
1.25.1.

- Expected behavior:
No localization woes. ;)

- Actual behavior:
-- Date and time of messages are kept in English formats when the app starts for the first time after updated, although regional settings of the operating systems are set to German date/time format.
-- After the language is changed from English to German by the user, some strings are not localized appropriately.

- Steps to reproduce the problem:
-- For the first issue: Run Delta Chat for the first time after updated.
-- For the second issue: Change the language from one to another (in "View" menu).

- Screenshots:
-- Change from English to German:
![grafik](https://user-images.githubusercontent.com/51095533/144424522-755e23b5-ea46-443f-a6c3-ae6eb21f616e.png)

- Logs:
N/A.

**Comment by Simon-Laux** [comment]
is the update message also missing right after the update?

**Comment by gerryfrancis** [comment]
@Simon-Laux If you mean the device message(s): Yes, they are not localized.

**Comment by Simon-Laux** [comment]
device update messages are not localised in desktop at all currently.
Also system messages are translated upon their creation, so this is unfortunately a won't-fix.
Maybe we could add a core issue about it or a forum feature proposal, though I'm unsure if the effort-required vs. usefulness ratio is good enough in this case.
