### ISSUE TITLE
The tray icon cannot display a mark for unread messages.

### ISSUE THREAD

**Issue by YamatoRyou** [deltachat/deltachat-desktop#2452]
- Operating System: x64 Windows 10 Enterprise LTSC (21H2)
- Delta Chat Version: 1.25.1
- Expected behavior: n/a
- Actual behavior: According to the 1.25.x change log, the tray icon will display a blue dot when there are unread messages, but it has only been seen once so far. Most of the time, it is not displayed.
- Steps to reproduce the problem: n/a
- Screenshots:
![{54DF1CF8-1F26-8C17-ADFA-D52BE536B9FD}](https://user-images.githubusercontent.com/48104960/144582738-91a01636-8e75-472d-ae5a-b2e37305d452.png)
- Logs: n/a

---------
My Windows 7 computer is still monitoring 1.22 for a bug (#2426), but I guess the same problem will occur under Windows 7.

**Comment by Simon-Laux** [comment]
I can confirm this bug, and looking at the code I found a clue: the feature is based on the unread badge feature which is disabled for windows currently:

https://github.com/deltachat/deltachat-desktop/blob/09599fef6dcd0b63fad3294aa8e88c1acacc5da5/src/main/unread-badge.ts#L7
