### ISSUE TITLE
Offline Toast obscures message composer on small width window

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#2454]
![image_2021-12-06_01-25-05](https://user-images.githubusercontent.com/18725968/144772920-7906200c-c75f-400e-9578-78b8ce94fdc4.png)

maybe have a max with so that it cannot be wider than the chatlist or maybe an icon for the retry text instead of the long text? or split it into two lines instead of one?

**Comment by gerryfrancis** [comment]
I would go for two lines, as clickable actions should be positioned for themselves in one line. (Just my two cents.)

**Comment by Simon-Laux** [comment]
Also we should make sure the archived chats button is still clickable in that case

**Comment by trujillo9616** [comment]
Hey! I would like to contribute in solving this issue 😁

**Comment by adbenitez** [comment]
@trujillo9616 thanks a lot for taking care!!! :heart:
