### ISSUE TITLE
use `chat_new_one_to_one_hint` instead of `chat_no_messages_hint`

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2458]
`chat_no_messages_hint` will be removed and is replaced by `chat_new_one_to_one_hint` (we could not just change the wording as the number of placeholders differ).

see https://github.com/deltachat/deltachat-android/pull/2165 for more details and reasoning.

**Comment by r10s** [comment]
wondering if we can already remove `chat_no_messages_hint`, we are currently in clean-up-mode at https://github.com/deltachat/deltachat-android/pull/2169 - i assume the strings are pulled not before the final 1.26 release anyway? and if, it is probably not much work to get that right ...

**Comment by Simon-Laux** [comment]
you can already remove it, I will change it to the new string when I pull translations.

**Comment by r10s** [comment]
k, i will merge the whole https://github.com/deltachat/deltachat-android/pull/2169 tomorrow then.
