### ISSUE TITLE
add Bulgarian translation

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2460]
bulgarian is new and quite complete. local name to use in the menu is Български 

cmp. https://github.com/deltachat/deltachat-android/pull/2172 and https://github.com/deltachat/deltachat-ios/pull/1423

**Comment by Simon-Laux** [comment]
note / nice to know: I recently made a script that checks for languages that have more than 150 lines and are not already included in the language list. It gets automatically run after pulling translations when executing `npm run translations-update`:
https://github.com/deltachat/deltachat-desktop/blob/master/bin/find_complete_translations.sh

**Comment by Simon-Laux** [comment]
OK, it's already included in the language list, I wasn't sure, because the first letter looked a bit different in the front in my IDE.

**Comment by r10s** [comment]
> because the first letter looked a bit different in the front in my IDE

i think, this is lower case, `Български` (Bulgarian for "Bulgarian") is upper case, as used for the other menu entries, so maybe change that, but probably @link2xt knows better with these cyrillic alphabet :)

**Comment by link2xt** [comment]
Yes, the first letter capitalized should be Б not б

**Comment by r10s** [comment]
reopening to not forget fixing that ...
