### ISSUE TITLE
rename Auto-Download "No Limit" to "All"

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2468]
if auto-download is disabled, the option should read just "All", not "No Limit".

we used "No Limit" in the first iteration on android, however, decided that "All" is easier to understand then. the string "No Limit" can be removed at some point from transifex then. for the string "All", just use the same as for "Show Classic E-Mails: All".

**Comment by Simon-Laux** [comment]
sure the one with the key `pref_show_emails_all`? would it make sense to rename the key then?
