### ISSUE TITLE
change CSS for incoming contact requests 

### ISSUE THREAD

**Issue by karissa** [deltachat/deltachat-desktop#247]
The contact request looks too similar to a chat messsage in the chat list. We should try to mimic the android app and change it to look grey.

**Comment by ralphtheninja** [comment]
> The contact request looks too similar to a chat messsage in the chat list. We should try to mimic the android app and change it to look grey.

At the same time I think we should tweak the css for the "normal chats", i.e. _not_ grey when hovering over it and when selected.

**Comment by r10s** [comment]
this is how the contact requests look like in android:

![image-4](https://user-images.githubusercontent.com/9800740/49462800-4025c500-f7f7-11e8-9306-4a46da61c6df.png)

**Comment by ralphtheninja** [comment]
@r10s Shouldn't it say `Contact request`?

**Comment by ralphtheninja** [comment]
Fixed in https://github.com/deltachat/deltachat-desktop/pull/375
