### ISSUE TITLE
Delta Chat window does not go away

### ISSUE THREAD

**Issue by Yettte** [deltachat/deltachat-desktop#2470]
Hi, on my Linux (debian 64) the latest DC Desktop version (1.26.0) does not go away when I click on another open window. For example I have libre office, firefox, dolphin and Delta Chat windows open. Usually when you click on another window the currently visible one goes to the background. But Delta Chat Desktop does not go away. I have to minimize it in order to access e.g. my libre office document. 
![Screenshot from 2021-12-18 16-10-19](https://user-images.githubusercontent.com/82230211/146645859-24d1a4c5-f8a5-4ed2-a2d1-48f6ff6a9b31.png)

**Comment by Simon-Laux** [comment]
Make sure you don't have activated always on top in the view menu or in your window-manager (most of the time it is right clicking on the bar with the program title on the top).

If that is not the issue, feel free to reopen this issue.
