### ISSUE TITLE
Download of new version does not work without terminal

### ISSUE THREAD

**Issue by Yettte** [deltachat/deltachat-desktop#2471]
When I tried to install the latest DC Desktop version (1.26.0) by just clicking on the downloaded file it does not work (see screenshot). I could only install it by using "sudo apt install" in the terminal.
![Screenshot from 2021-12-18 13-37-46](https://user-images.githubusercontent.com/82230211/146646062-cc1e1c15-d124-456f-8a60-445b91be42bf.png)

**Comment by Simon-Laux** [comment]
might be an ubuntu bug? are you sure you clicked on the right file (the version says still `1.22.2` in your screenshot)

**Comment by Yettte** [comment]
Hi sorry, for not responding to this issue, still trying to learn good github behavior. It has been so long ago now, that I cannot give adequate feedback anymore. So I will close this until it happens again.
