### ISSUE TITLE
System Notifications Not Working and Message Receipts Not Sent

### ISSUE THREAD

**Issue by EclecticSoftwareEngineer** [deltachat/deltachat-desktop#2473]
This relates in particular to desktop Version 1.25.2 (git: v1.25.0-6-gc424b5ec) (deltachat-desktop_1.25.2_amd64.deb), but the same behaviour was occurring also in 1.22.2 and perhaps earlier versions. The same symptoms occur in the Android versions (in particular version 1.26.2 F-Droid) (i.e. no notifications and no sending of receipts).

On the theory that some configuration was affecting this behaviour, I followed the procedure as outlined in the attached PDF to delete all the config settings for Delta Chat and being again from scratch. However, the same problems occurred in the newly set up Delta Chat, indicating that the configuration settings are not the problem.

I am also getting an "io: inner stream closed" error message in Settings, but this does not appear to affect message sending or receiving, and seems unrelated to notifications and receipts.

[2021-12-19_reinstallazione-di-delta-chat.pdf](https://github.com/deltachat/deltachat-desktop/files/7740272/2021-12-19_reinstallazione-di-delta-chat.pdf)

**Comment by Gh0stz0x** [comment]
I can confirm what was said by EclecticSoftwareEngineer

**Comment by Simon-Laux** [comment]
please reopen if this is still an issue in 1.34
