### ISSUE TITLE
Can't find backup file

### ISSUE THREAD

**Issue by mdfOffman** [deltachat/deltachat-desktop#2482]
- Operating System (Linux/Mac/Windows/iOS/Android):
- Delta Chat Version:
- Expected behavior:
- Actual behavior:
- Steps to reproduce the problem:
- Screenshots:
- Logs:

**Comment by mdfOffman** [comment]
I have an account on my iPhone and made a back up to load on my Mac.  It told me I must send it "somehow" to my Mac.  But I have no idea where the backup file is on my iPhone!   Where are iPhone backup files stored?

**Comment by Simon-Laux** [comment]
in the app container - look at the files app or finder when you have your iphone connected

**Comment by mdfOffman** [comment]
Thanks for that, Simon.  Yes, I found the files after a while and I imported the backup onto my Mac.  But, even after the import, the devices didn’t sync outgoing messages.  Delta chat is really nice in many ways but it is useless to me if I can’t see my own outgoing messages on any device that didn’t send that particular message :-(

**Comment by hpk42** [comment]
you need to switch on "copy to self" in advanced settings -- here is a little howto 
for Mac https://support.delta.chat/t/how-to-use-deltachat-on-both-iphone-and-mac/1236/5
and Android https://support.delta.chat/t/how-to-sync-your-mobile-delta-chat-account-with-your-computer-desktop/1962/2

and yes, we are aware that setting up multiple devices is a bit of a pain. Hopefully we can finally improve this in 2022 :)

**Comment by mdfOffman** [comment]
Thank you, Holger

Almost there!  I found “send copy to self” on the iPhone and enabled it and it showed on the Mac.  But i don’t find that setting on the Mac.  For me, the whole point of using it on the Mac is so that I can use the keyboard so it is very important to see my outgoing Mac messages on my iPhone.  How do I do that?

Thanks,

Martin

**Comment by hpk42** [comment]
it should be in the 3-dot menu under "Settings" and then scroll down to "IMAP folder handling" and enable "send copy to self".

**Comment by Jikstra** [comment]
![Screenshot_20220103_192249](https://user-images.githubusercontent.com/34889164/147965668-dd24f53f-5d5b-4e2f-a859-0fee0636bfd2.png)

**Comment by mdfOffman** [comment]
Found it!  I had looked for it under the IMAP settings in the account setup section.

Thank you, Jikstra and Holger.  

I have made a rule in Mac mail to automatically file all outgoing messages in a separate delta chat folder.  I don’t want to see them in my day-to-day work but I really appreciate their being stored in email.  My main complaint about WhatsApp, Telegram, Signal etc (after security issues) is that people send me documents and I have no clear record on when they sent what.  Searching is a real pain.  With DC storing in email, I can use all the email tools to search the historical record.

I look forward to testing this.

**Comment by mdfOffman** [comment]
May I please ask for some more help?

My iPhone is giving me the error: “This message cannot be decrypted on all incoming messages but my Mac Mini is reading them all perfectly.  What gives and what should I do about it?

Many thanks,

Martin

**Comment by Jikstra** [comment]
You need to transfer the encryption key from your mac mini to your phone. The recommended way is to export a backup on the mac mini and import it on your phone.

Have a look here for more info :)
https://delta.chat/en/help#can-i-use-delta-chat-on-multiple-devices-at-the-same-time

**Comment by mdfOffman** [comment]
Thank you once again so much.

That’s very strange because my Mac app was originally created from a backup of the iPone app!  However, it is all working now and I really like the app.

Thanks you.

Martin

**Comment by Jikstra** [comment]
That's weird. Did you maybe reinstall on your iphone inbetween?

**Comment by mdfOffman** [comment]
Well, I don’t think so but I have to admit that my process has been far from “controlled” so I can’t do more than say “weird”. :-)
