### ISSUE TITLE
Settings->Advanced->Prefer e2e ecnryption

### ISSUE THREAD

**Issue by karissa** [deltachat/deltachat-desktop#250]
This option should be a checkbox with some extra information (as seen in the android app.)

**Comment by bokf** [comment]
I cant find the option: Settings->Advanced->Prefer e2e encryption at all.
What I miss is an option to completely disable encryption. In my case a wrote a message from the desktop version V2.0.0 but after synchronizing in the mobile version came only the message: "Chat: Verschlüsselte Nachricht - [This message was encrypted for another setup]"
So I would like to have the possibility to disable encryption.

**Comment by hpk42** [comment]
On Sun, Dec 09, 2018 at 06:39 -0800, bokf wrote:
> I cant find the option: Settings->Advanced->Prefer e2e encryption at all.
> What I miss is an option to completely disable encryption. In my case a wrote a message from the desktop version V2.0.0 but after synchronizing in the mobile version came only the message: "Chat: Verschlüsselte Nachricht - [This message was encrypted for another setup]"
> So I would like to have the possibility to disable encryption.

fair enough. have you tried an "Initiate Key transfer" from Desktop to mobile? 
this should allow your mobile to read the currently-unreadable message.

**Comment by ralphtheninja** [comment]
> So I think there should be the option to activate encryption as it is in the normal android version.

Yes, that's the reason for this issue in the first place. It only needs to be implemented.

**Comment by r10s** [comment]
yip, `dc_set_config()` is persistent. it writes the config to the database. you only have to call this function from within the configuration-dialog, no need to init values or so.
