### ISSUE TITLE
New contributors

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#2503]
Not really sure how I can address you in another way, so I will use an issue for now ^^
First, big thanks to @ejgonzalez17 @naomiceron @IrvinLara9 @trujillo9616 @Abhijnan-Bajpai @cavesdev & @jesusj0o for the various contributions in the last weeks. Really cool to see new people helping working on deltachat-desktop!

I have to admit, I'm a bit curious about you people. I had a look at your github repositories and some of you mention Encora Mexico. Is this a coincidence? Did deltachat just get some traction at your place and you couldn't stand some annoyances? I really don't have a clue but would love to know what is going on :D

Also, if I already have your attention, we are currently working on the 1.28 desktop release. It's going to be a bug fix release, so in case you want to help out with some of the issues we priorizied for this release, have a look at https://github.com/orgs/deltachat/projects/44

Besides this we will also have a small gathering from the 13th to the 20th January, where we want to talk about the future of DeltaChat Desktop and hack on various things (new backend in rust, better messagelist, some non disclosed thingies...). @Simon-Laux and josy will be around too, some other people from the deltachat team too. In case you are interested in it, having an audio/video call or something, feel free to drop me a message at jikstra@riseup.net :) Would love to hear from you!

**Comment by naomiceron** [comment]
Must of us are part of the Apprentice program at Encora México, and we were encouraged to contribute on open-source projects, but I think it was a coincidence to find DeltaChat desktop. Thank you so much for considering us on the new release! ❤️

**Comment by IrvinLara9** [comment]
Thank you :D, it's a pleasure to contribute to this awesome project!

**Comment by Abhijnan-Bajpai** [comment]
Thanks for the mention! Will surely stick around for helping out with more bugs.

**Comment by ejgonzalez17** [comment]
Thank you for taking us into account! as @IrvinLara9  commented, it was a pleasure to contribute to your project =)

**Comment by cavesdev** [comment]
Thanks for the mention! I'm glad we're able to help in this great project :)

**Comment by Jikstra** [comment]
> Must of us are part of the Apprentice program at Encora México, and we were encouraged to contribute on open-source projects, but I think it was a coincidence to find DeltaChat desktop. Thank you so much for considering us on the new release! heart

Aaah! What a cool program. Now things make a bit more sense :D Happy that you enjoyed contributing and would love to see some of you sticking around :)
