### ISSUE TITLE
Delta Chat is not a suggested (default) email client/ app 

### ISSUE THREAD

**Issue by Yettte** [deltachat/deltachat-desktop#2505]
- Operating System: Linux (tested) and probably for Mac/Windows (not tested yet) as well
- Delta Chat Version: 1.26.0

- Expected behavior: when I am on a website and click on an email address I would like to choose between Thunderbird and Delta Chat to write Emails.

- Actual behavior: when I am on a website and click on an email address only Thunderbird opens to write an email. Delta Chat is not suggested. On Android and iOS you have the option and can decide whether you want to have it only ones or always

**Comment by Simon-Laux** [comment]
For linux it should be suggested, look into your system- / desktop-enviroment-settings.
For macOS it is in your mail app and for windows the bug really exists, because we never came to adding the required registry keys to our installer.

**Comment by Yettte** [comment]
Thanks Simon!

**Comment by Simon-Laux** [comment]
> Thanks Simon!

I guess that means we can close the issue here, also we could maybe create a guide for how to do it sometime.
