### ISSUE TITLE
Settings->Advanced->Manage Keys

### ISSUE THREAD

**Issue by karissa** [deltachat/deltachat-desktop#251]
Allows you to Export secret keys or Import secret keys.

- [ ] export: It should send a dialog to the user similar to the android app: 'Exported files will contain your end-to-end setup..., etc'. The user should have to enter their password to continue.
- [ ] import: It should ask to confirm with a similar message as android - if the user says 'ok', a file dialog will be opened with [`electron.dialog.showOpenDialog`](https://github.com/electron/electron/blob/master/docs/api/dialog.md#dialogshowopendialogbrowserwindow-options-callback)

**Comment by karissa** [comment]
@r10s @hpk42 curious on your opinion here for keys import/export -- the c core requires a directory to be passed, but in desktop, how do you imagine the User Interface working here? We need to direct the user to pick the directory, not a file, but it might be confusing if there are multiple files it's looking for. How does this work in android?

**Comment by hpk42** [comment]
On Fri, Dec 21, 2018 at 13:09 -0800, Karissa McKelvey wrote:
> @r10s @hpk42 curious on your opinion here for keys import/export -- the c core requires a directory to be passed, but in desktop, how do you imagine the User Interface working here? We need to direct the user to pick the directory, not a file, but it might be confusing if there are multiple files it's looking for. How does this work in android? 

have ATM not much to say for this but would actually expect core to take file paths, not directories.

**Comment by r10s** [comment]
for importing keys: i think we could tweak the core in a way that it accepts a directory as well as a file.

for exporting keys: typically, multiple files are exported here: each private key as a separate file and for each private key the belonging public key.
so i think selecting a directory makes some sense here - otherwise we would end up in a key management dialog or so what is nothing i would like to see in delta :)

**Comment by ralphtheninja** [comment]
Would it be possible to export it as some type of archive file? E.g. tar, zip etc?

**Comment by r10s** [comment]
hm, not sure if that makes things easier for the user. and also not for delta - i think if you export the keys as an zip-archive, users would expect that this archive could be imported later. i see many problems arising here and would not go for it currently.

**Comment by hpk42** [comment]
On Sat, Dec 22, 2018 at 08:07 -0800, björn petersen wrote:
> hm, not sure if that makes things easier for the user. and also not for delta - i think if you export the keys as an zip-archive, users would expect that this archive could be imported later. i see many problems arising here and would not go for it currently. 

that was one of my $reasons as well. I think a single file is enough to allow for importing. 
Such files can already contain many keys (conceptually, not sure Delta supports that).
So even if you want to export a bunch of verified keys and import them somewhere else 
a single file import/export API would be sufficient.  Also gpg allows to specify multiple
keys with "gpg --export" IIRC, or you can simply "cat" the results of multiple queries
into one file. It's an advanced option as we don't talk to users about "keys" 
so i think it's fine to be restrictive ;)
