### ISSUE TITLE
"failed to set draft"

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#2522]
with the node branch prepare_for_core_1_71 and master-desktop as of now, i keep getting "failed to set draft" errors when the input bar is empty.  this also appears after sending a message -- the sent message then remains as draft. I think this happens with both v1.26 desktop and master so probably has more to do with bindings/core. 
![Screenshot from 2022-01-17 11-58-06](https://user-images.githubusercontent.com/73579/149757812-151f92b0-bddd-47d3-97ff-c7f7a1ca36c2.png)

**Comment by hpk42** [comment]
FWIW i hacked a little local change to core which seems to fix the issue but not sure it's proper.  core explicitly bails on empty text. CC @r10s 
```
diff --git a/deltachat-ffi/src/lib.rs b/deltachat-ffi/src/lib.rs
index ef9b4a8d..83a227ad 100644
--- a/deltachat-ffi/src/lib.rs
+++ b/deltachat-ffi/src/lib.rs
@@ -937,8 +937,13 @@ fn render_info(
     let msg = if msg.is_null() {
         None
     } else {
-        let ffi_msg: &mut MessageWrapper = &mut *msg;
-        Some(&mut ffi_msg.message)
+        let ffi_msg = &*msg;
+        if ffi_msg.message.get_text().unwrap_or_default().is_empty() {
+            None
+        } else {
+            let ffi_msg: &mut MessageWrapper = &mut *msg;
+            Some(&mut ffi_msg.message)
+        }
     };
 
     block_on(async move {
```

**Comment by r10s** [comment]
the `bail!("No text and no quote in draft");` appears only for `Viewtype::Text` and exists already long before 1.71 (just checked 1.60 as an example), so, not sure if that is related to recent core changes. however, might be, there were changes in this area.

but might also be, `set_draft()` calling has changed somehow, and is called for an empty text now.

for the proposed change: that would also remove the ability to draft images etc. without text, so, we would need to be a bit more explicit here.

but as said, maybe it is better to catch that on caller side - so, if there is no text, no quote, no image, nothing, call `set_draft(null)`

> the sent message then remains as draft

that looks like another issue? but anyway, that seem to require more investigations :)

**Comment by hpk42** [comment]
you are right -- my patch is not good.  Just tried to attach a file and then type the text and that didn't work.  So i had to type text, then attach -- still overall nicer than having all sent messages as draft messages in the input bar -- choose your bugs :) 

So indeed, it seems desktop / node bindings rather need to set things as NULL properly.
