### ISSUE TITLE
exception // slight stalling of chat-list clicking

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#2542]
With prepare_for_1.72 node branch and desktop master i got the attached exception, co-inciding with a hanging/sluggishness of the UI but it auto-recovered. 
![Screenshot from 2022-01-28 09-49-37](https://user-images.githubusercontent.com/73579/151516346-815c524d-bbd5-4d0f-9ffa-f3c50f50bc77.png)

**Comment by Jikstra** [comment]
Errors definetly cause slow downs. Seems like we're missing a null check somewhere there.

**Comment by hpk42** [comment]
i haven't exerienced this issue with recent masters, will re-open if it occurs again.
