### ISSUE TITLE
Resolve left over MessageList issues

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#2545]
- [x] sometimes `MessageList.scanScrollLock` seems to not get unlocked
- [x] properly fix duplicate loaded pages
  - [x] implement lockedQueuedEffect
- [x] still duplicate Messages @Simon-Laux ?
 - [x] On stream of incoming messages - scroll up -> results in pages with the same messages
  - [x] implement lockedQueuedEffect
- [x] disappearing messages dont disappear when staying in chat, one needs to switch the chat for them to disappear
  - [x] needs refresh chat 
- [x] scrolls to bottom on incoming webxdc state
- [x] Download message on demand pops up at bottom of the list and not in place
  - [x] needs refresh chat
- [x] Is read state updated?
- [x] Webxdc summary updates work

**Comment by Simon-Laux** [comment]
closing this as everything is checked, we can open a new issue when we find more issues with the messagelist
