### ISSUE TITLE
erroneous info-message after exporting keys

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2553]
after exporting private keys, the message says `... successfully written to "0".` (1.26.0 on macOS)

![Screen Shot 2022-02-08 at 11 59 30](https://user-images.githubusercontent.com/9800740/152974246-9719ac87-54e1-4ae3-89f2-a74fdef16659.png)

**Comment by adbenitez** [comment]
just had this bug

**Comment by Simon-Laux** [comment]
works on Mac for me, shows the path, not `0` for me.
