### ISSUE TITLE
window contents disappear with normal usage

### ISSUE THREAD

**Issue by nolash** [deltachat/deltachat-desktop#2554]
- Operating System (Linux/Mac/Windows/iOS/Android): linux
- Delta Chat Version:  1.17.0
- Expected behavior: visible interface
- Actual behavior: window contents disappear during normal usage, when scrolling, clicking
- Steps to reproduce the problem: see above
- Screenshots: see below
- Logs: https://g33k.holbrook.no/0a31941f

![](https://g33k.holbrook.no/dc19f1f5)

**Comment by Jikstra** [comment]
1.17.0 is a bit old, can you try the newest version from https://delta.chat ? But besides this the grey screen looks the same as this here: https://github.com/deltachat/deltachat-desktop/issues/2543

**Comment by nolash** [comment]
I am following the archlinux packaging - is that stale then?

**Comment by Simon-Laux** [comment]
[deltachat-desktop](https://aur.archlinux.org/packages/deltachat-desktop) or [deltachat-desktop-git](https://aur.archlinux.org/packages/deltachat-desktop-git)?

**Comment by nolash** [comment]
deltachat-desktop (the git one is even older)

**Comment by Simon-Laux** [comment]
the [deltachat-desktop-git](https://aur.archlinux.org/packages/deltachat-desktop-git) downloads and builds from the `master` branch of this git repo, so it is always the newest bleeding edge version

**Comment by Simon-Laux** [comment]
please reopen this issue if it still occurs in 1.28.x
