### ISSUE TITLE
failure to build desktop on ubuntu 16.04

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#2557]
on master desktop and master node bindings, using ubuntu 16.04, npm/nvm v16.13.1 (the readme says at least v14.* is required) and a fresh "npm install" and then running "npm run build" i get the attached log which contains an "esbuild" error.  this used to work some time ago.  If i need to use different versions or so it would be great if the README could be more specific. 
[desktop-esbuild-problem.log](https://github.com/deltachat/deltachat-desktop/files/8098970/desktop-esbuild-problem.log)

**Comment by link2xt** [comment]
Pushed a commit to fix it:
https://github.com/deltachat/deltachat-desktop/commit/edafcac4b117789249386f725cae2b2024ddc3a9

**Comment by hpk42** [comment]
@link2xt fixed it in https://github.com/deltachat/deltachat-desktop/commit/edafcac4b117789249386f725cae2b2024ddc3a9 so it was a real issue and not just something with my environment.
