### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-desktop#2564]
When deleting an yggmail account, the layout looks like this 

<img width="784" alt="Screen Shot 2022-02-21 at 9 17 11 PM" src="https://user-images.githubusercontent.com/2614900/155021312-809b1304-70d8-454e-b7d8-7008ba3035b4.png">

Similar when creating new chats to yggmail addresses:

<img width="677" alt="Screen Shot 2022-02-21 at 9 34 04 PM" src="https://user-images.githubusercontent.com/2614900/155023103-b7055ef9-1667-4dfd-b4d9-76e439eecb94.png">

Version 1.26.0 (1.26.0)

**Comment by Simon-Laux** [comment]
already fixed on master
See https://github.com/deltachat/deltachat-desktop/issues/2432
