### ISSUE TITLE
add Contact Profile View: last seen

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#2573]
sometime ago core added a last seen property to contacts, android displays that information in the profile screen of a contact.
how it looks on android:
![image_2022-02-26_14-54-59](https://user-images.githubusercontent.com/18725968/155848464-1c7f5209-9c73-4570-bb16-f7ddb736e237.jpg)

the android pr: https://github.com/deltachat/deltachat-android/pull/2144

**Comment by canastillo** [comment]
Hi! I'm looking for a project to make my first open source contribution. Is anyone working on this? I wanna give it a shot

**Comment by Jikstra** [comment]
@canastillo nobody is working on it right now, but we would highly appreciate any contributions on this :) If you need help/have questions about the codebase, feel free to contact me on jikstra * at * riseup.net :)

**Comment by canastillo** [comment]
Awesome, I'll get to it then. Thanks!
