### ISSUE TITLE
`deltachat --version` does not work

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#2582]
would be nice if it could print some info without starting DeltaChat

**Comment by Jikstra** [comment]
Also --help would be nice

**Comment by nadia12-p** [comment]
hi guys, can I work on this?

**Comment by nadia12-p** [comment]
hi! the --version flag is working, but I'm not sure what info you want to put in --help, the only command right now is 
--version, so it will only print that info, is it ok or am I missing something?

**Comment by Simon-Laux** [comment]
there are more options, see https://github.com/deltachat/deltachat-desktop/blob/master/docs/CLI_FLAGS.md
Also because you haven't found this file on your own, we improve it's discoverability, what do you think we could do to make that file more visible?

**Comment by nadia12-p** [comment]
@Simon-Laux thanks for the help!! I think keeping it like that is fine. However, I can't find the code where these options are declared which is why I'm confused hahaha do you know how they work or where I can look at the logic of these flags?

**Comment by Simon-Laux** [comment]
closed by https://github.com/deltachat/deltachat-desktop/pull/2821
