### ISSUE TITLE
"Send Message" does not always open chat view

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2592]
in the contact-profile there is a "Send Message" button that usually opens the chat of the contact and allows sending a message to that contact.

however, this does not work when the "Gallery" was opened before:

- open a one-to-one chat
- open the gallery in that one-to-one chat
- tap on the title bar to open the contact's profile
- tap "Send Message"

-> the chat is not opened, no message can be send. instead, the windows stays in "Gallery".

probably easy to fix. the same is true for the "Map View", btw.

tested with 1.27.0 on mac.

**Comment by Jikstra** [comment]
> probably easy to fix. the same is true for the "Map View", btw.

Sadly not :D The state for this is currently not changeable from the outside, therefore not so easy to fix.

**Comment by Simon-Laux** [comment]
we could use a trusty pass function around via an `window.__switch_to_chat_view` workaround
