### ISSUE TITLE
chat does not always scroll down

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2593]
when sending a videochat-invitation, the chat view is not scrolled down.

apart from the window being opened, it looks as if no invitation is sent to the chat.

tested with 1.27.0 on mac.

maybe related: https://github.com/deltachat/deltachat-desktop/issues/1407

**Comment by Simon-Laux** [comment]
still an issue

**Comment by Jikstra** [comment]
It happens if we get a DC_EVENT_MSGS_CHANGED event and don't know how many new messages we have.

**Comment by r10s** [comment]
i think, on adding messages, we should check if the view is already scrolled down.

if so, we should keep that scrolling position. i am pretty sure, that was the case in 1.26, but i cannot tell for sure. DC_EVENT_MSGS_CHANGED, however does not help here, indeed, as it does not tell the number of new messages.

**Comment by hpk42** [comment]
With recent masters i still reliably get a failure to scroll down properly when i invite to a video chat.  The message view remains still after the "attach - video chat" action and when i scroll down i see there was a video-chat invitation icon added.

**Comment by r10s** [comment]
still in issue with 1.30, it also happens in normal chats when the chat was just opened, no scroll down takes place and one does not really know if the message was acually sent.

**Comment by Simon-Laux** [comment]
should be fixed now, please reopen if it reapears
