### ISSUE TITLE
message input lagging

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2594]
when typing in a message to the input windows, the update of the typed in characters is slow, typically the characters appear half of a second or more after typing - where it should be instant.

the issue is not only there when typing in lots of lines of text, it is also noticeable when there is very few text. it does not happen all the time, however, pretty much often (just play around ...)

the reason is probably that on every character the draft is updated.

**Comment by Simon-Laux** [comment]
> when typing in a message to the input windows, the update of the typed in characters is slow, typically the characters appear half of a second or more after typing - where it should be instant.

I can not really reproduce this, in which versions does this appear?

What I noticed is that I can not keep a character pressed to spam it, but trying in text works as expected.

> the reason is probably that on every character the draft is updated.

not in 1.27.2, currently the debouncing works (500ms after I stop typing the draft is saved to core).
But I noticed that the react state changes on every character and that could trigger re-rendering:
<img width="744" alt="Bildschirmfoto 2022-03-16 um 15 04 30" src="https://user-images.githubusercontent.com/18725968/158609016-eda72fe5-7767-48e4-93c5-ce3b6eafd412.png">

**Comment by Jikstra** [comment]
@hpk42 @r10s can one of you do a performance recording? You can start it like this:
1. Open the developer console
2. Go to performance tab
3. click on the record button (its a grey circle) in the upper left
4. perform what is slow
5. stop the recording
6. Save the profile with the arrow down button in the performance tab, it's in the same row as the record button
7. Send me the saved recording

**Comment by r10s** [comment]
@Jikstra sent you a recording to your riseup address, not sure if that help - but the tool is impressive, at a first glance :)

**Comment by hpk42** [comment]
with recent masters i don't get lagging message input.  typed quite some things, and it seems the "setDraft" debouncing is working. please re-open if you still have this issue with recent master's of core/node/desktop .... or with the upcoming desktop test release.
