### ISSUE TITLE
support new emojis

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#2595]
we are still at 2019 emoji in the meantime unicode released two new versions and is now at a version from 2021. https://www.unicode.org/emoji/charts/emoji-versions.html

When updating our users would get access to the following new emojis:
![image](https://user-images.githubusercontent.com/18725968/157543075-dcf52433-b9c4-4e14-8fa6-53624a993aea.png)

This issue has two parts:
- [x] Displaying them: Update google-noto-emoji font
- [x] Letting the user pick them: emoji picker emoji definition needs to be updated.

I assume on iOS the emojis are dependent on system version, so only dc-android might want to update it's emoji set as well. (ping @r10s @Hocuri @adbenitez)

**Comment by dotlambda** [comment]
Would it be a problem to use a different version of this font in Nixpkgs? I could reduce the package size by using the noto-emoji font packaged in Nixpkgs.

**Comment by Simon-Laux** [comment]
> Would it be a problem to use a different version of this font in Nixpkgs? I could reduce the package size by using the noto-emoji font packaged in Nixpkgs.

I don't think so as long as it is newer and more up to date

**Comment by Darthagnon** [comment]
Is there any way we could use iOS emojis? e.g. by supplying the font extracted from MacOS or Telegram?

**Comment by Simon-Laux** [comment]
you could theoretically extract the emoji font from apple and install it on your system, delta chat should pick it up.

**Comment by Simon-Laux** [comment]
deltachat uses system fonts, you can also inject custom css at runtime via custom user themes: https://github.com/deltachat/deltachat-desktop/blob/master/docs/THEMES.md

you can look at https://github.com/deltachat/deltachat-desktop/search?q=%22apple+color+emoji%22 to see which classes you'd need to overwrite. Or just get the font somehow installed as "Apple Color Emoji" system font.

**Comment by Darthagnon** [comment]
> we don't connect to servers to download stuff by default
Not downloading external data is a very good policy! Please don't change it! at least for my use cases, a File >> Select dialog for a separately downloaded emoji pack would be better (less risk of the inevitable 404). I've updated my earlier comment, as I've managed to located Telegram's Apple Emoji files. I'll take a look and see what I can do.

**Comment by Simon-Laux** [comment]
@Darthagnon Soon you can easily change the used emoji font with the theming system, I also wrote a mini guide on how to do it: https://github.com/deltachat/deltachat-desktop/blob/2e783fd04e66b1b1c7ac5e5a9f5bbcdd5a89e842/docs/THEMES.md#guide-changing-the-emoji-font
