### ISSUE TITLE
Group Management (Edit Group screen)

### ISSUE THREAD

**Issue by karissa** [deltachat/deltachat-desktop#26]
When in the chat view for a group, you should be able to click the menu in the upper right and hit 'Edit Group' to go to the Edit Group screen.

To keep it simple, screen could be the same as the one that is shown when the group is created -- `createGroup.js`. Upon save, the changes in the members and name are then reflected in the group, and the screen returns to the chat window.

**Comment by ralphtheninja** [comment]
You should be able to:

1. change group name
  * input field can be populated with current group name
  * create group button could be labeled with "Save" instead
1. add more members to the group
  * show list of users that aren't yet in the group
  * clicking on users will mark them green just like as in the Create Group use case
  * selected users are added to the group when "Save" is clicked

Apart from this, we should list current group members (which shouldn't be editable)

**Comment by ralphtheninja** [comment]
I think instead of tweaking `CreateGroup.js` (which will handle both create and edit) we can copy `CreateGroup.js` to `EditGroup.js` and tweak that. Once that's done we can try refactor common code into a base class component.
