### ISSUE TITLE
Deltachat 1.27.0 & Yahoo.co.uk: Stuck on Connecting

### ISSUE THREAD

**Issue by Darthagnon** [deltachat/deltachat-desktop#2602]
## Operating System (Linux/Mac/Windows/iOS/Android):
Windows
## Delta Chat Version:
v1.27.0
## Expected behavior:
Launch, connects to email account, or, on failure, prompt to re-login.

## Actual behavior:
Launch, tries to connect to email account using "app password" (no problems visible on Yahoo.co.uk account settings page), fails silently, simply no send/receive occurs and it says "connecting" forever. 
## Steps to reproduce the problem:
I tried restoring from a backup of the current account, but there was no prompt to re-login nor any clear way of doing so, short of recreating my account from scratch (and I suppose losing all my PGP keys).
## Logs:
[2022-03-11-13-27-09.log](https://github.com/deltachat/deltachat-desktop/files/8232335/2022-03-11-13-27-09.log)

**Comment by Jikstra** [comment]
> 
Launch, tries to connect to email account using "app password" (no problems visible on Yahoo.co.uk account settings page), fails silently, simply no send/receive occurs and it says "connecting" forever.

Will have a look into the logs, most likely a core issue. Thanks for reporting :)

> I tried restoring from a backup of the current account, but there was no prompt to re-login nor any clear way of doing so, short of recreating my account from scratch (and I suppose losing all my PGP keys).

Normally if you have a backup you import it and it automatically logs in. Did this not work for you?

**Comment by Jikstra** [comment]
@Darthagnon so reading the log, it looks like you logged into the account, exported the backup and then tried to import it again? Then I'm starting to see a lot of those messages:
```

2022-03-11T13:33:48.708Z	core/event            	INFO	""	2	"DC_EVENT_INFO"	0	"src\\imap\\select_folder.rs:35: Expunge messages in \"DeltaChat\"."
2022-03-11T13:33:48.709Z	core/event            	WARNING	""	2	"DC_EVENT_WARNING"	0	"src\\imap.rs:423: failed to close folder: CloseExpungeFailed(Io(Custom { kind: BrokenPipe, error: \"inner stream closed\" }))"
2022-03-11T13:33:48.709Z	core/event            	WARNING	""	2	"DC_EVENT_WARNING"	0	"src\\imap.rs:429: failed to logout: Io(Custom { kind: BrokenPipe, error: \"inner stream closed\" })"
```

Which look weird and seem to be that something is broken.

**Comment by Darthagnon** [comment]
So when I run it, it looks like it's logged in, save for a "Connecting" down in the bottom left corner. I can send messages (but I'm pretty sure they're not actually getting sent); no new messages are downloaded, either.

Making a backup and reimporting it makes a new profile in exactly the same state.

I was going to take a screenshot, but it now crashes on launch:
![DeltaChat_2qb8eRk4hT](https://user-images.githubusercontent.com/20792748/157908804-fda9e2fd-48bb-4abb-862b-18025aa3c372.png)

New logfile:
[2022-03-11-16-29-28.log](https://github.com/deltachat/deltachat-desktop/files/8233662/2022-03-11-16-29-28.log)

**Comment by Simon-Laux** [comment]
@Darthagnon can you test https://download.delta.chat/desktop/v1.27.2/ and look inside of the log what message is crashing the message-parser?

atleast the message-parser crash should now not crash the whole app anymore

**Comment by Darthagnon** [comment]
> @Darthagnon can you test https://download.delta.chat/desktop/v1.27.2/ and look inside of the log what message is crashing the message-parser?
> 
> atleast the message-parser crash should now not crash the whole app anymore

Installed the update and now it's working perfectly. sent and received messages, no new login needed. Here's the latest log, just to be on the safe side: [2022-03-16-01-41-50.log](https://github.com/deltachat/deltachat-desktop/files/8258329/2022-03-16-01-41-50.log)

**Comment by Darthagnon** [comment]
Possible security issue: I was scrolling the log, and it's got a fair amount of private metadata (email folder names, full plaintext of Deltachat messages (`parseMessage failed:"	{"input":" [insert full plaintext message from Snowden to Assange here][...]","error":{"stack":"RuntimeError: unreachable\n`)

If I would remember..\n\nI think I used some sort of installer for the first time. Now I just overwrite the files on update.\n\nI use builds from https://chromium.woolyss.com/ too. Actually, you can install (via installer provided) any version of chromium (so it should register it in the system) and then just overwrite the installation with your own build (ungoogled, whatever). You don't need to re-register it each time you deploy another build.\n\nWhen I say \"overwrite\" I mean \"remove all the files manually and then unpack another ones\".\n\nOn Tue, 13 Apr 2021 16:30:43 +0300, Darren de Lima <darren.delima@yahoo.co.uk> wrote:\n\nThank you so much! I'm really looking forward to it!\n\nWondering, how did you register Ungoogled Chromium on your system? Did you use a script? or an installer from Eloston's homepage ([https://ungoogled-software.github.io/ungoogled-chromium-binaries/](https://ungoogled-software.github.io/ungoogled-chromium-binaries/))?\n\nI haven't been able to, as I use builds (often older ones for testing purposes) from Woolyss' project ([https://github.com/macchrome/winchrome/releases/](https://github.com/macchrome/winchrome/releases/)) (project homepage: [https://chromium.woolyss.com/](https://chromium.woolyss.com/)), which didn't offer installers for All Codecs builds (though I checked just now, and looks like they've started to, recently, for the newest builds). Until now, I've been trying chrlauncher (which keeps glitching out and occasionally launching without loading the User Profile).\n\nMany thanks,\n\nDarren J. de Lima

**Comment by Simon-Laux** [comment]
yeah people should redact their log or send it over another channel to us so it's not public.
the "parseMessage failed" is actually the thing I need to know fix the message parser.
To fix the message parser I need to have the input that crashed it or at least a similar input with which I can reproduce the crash: you can also try https://deltachat.github.io/message-parser/ (watching the console in the browser devTools (inspect element) or if you should not trust that site you can build it yourself from https://github.com/deltachat/message-parser.

**Comment by Simon-Laux** [comment]
> Possible security issue

what's the threat model? sharing the log online or someone finding the log on your system?

Sure there is personal data in the logs, but most of what's in there [^1] is needed for us to help users with issues.
Maybe we could also think about log encryption, but not until we have encrypted account databases on all platforms ( something we are currently working on), though if your OS is compromised you have already lost anyway in most of the cases.

[^1]: besides from the log in debug mode which currently might have more info than needed.

**Comment by Darthagnon** [comment]
> the "parseMessage failed" is actually the thing I need to know fix the message parser.
I've got the logs, what bit do you need (a grep of the logfiles I posted should show it up, though)? Do they need to be run through the message parser website (can't really tell how to use the site or what data it's expecting)? 

> what's the threat model?
Uncertain. It was a bit of a random thought, as I was surprised to see email contents in the log. Like I said, I don't really care, it's non-critical stuff; but maybe someone who's read up on the Autocrypt/PGP stuff might be more nervous at their message content appearing in logs which might one day be autosubmitted somewhere (afaik you don't do this). Most (of the admittedly few) logs I've looked at for other software doesn't have message data/user-generated content (worst case: folder names, hardware/driver versions)

**Comment by Simon-Laux** [comment]
the message parser, as the name should suggest, parses the messages (makes email addresses and links clickable).
Some aspect of the message you found crashed it and it should never crash, so it's important that we find out what crashed it so we can fix it.
If you can not share the whole message, then please try to find out what part of it crashed the message parser or find a similar message that crashes it too.

To try stuff you can type or paste stuff in the input field on https://deltachat.github.io/message-parser/ and open the browser's dev console (press f12 or right click somewhere on the page and click on "Inspect element", then select the console tab in the dev tools that you just opened). Another option to try things out would be sending variations of the message in deltachat and looking at the log to find out what works and what results in the message-parser crash.

**Comment by Darthagnon** [comment]
> (file:///C:/Users/Darren/AppData/Local/Programs/deltachat-desktop/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:243:163)"	"parseMessage failed:"	{"input":"If I would remember..\n\nI think I used some sort of installer for the first time. Now I just overwrite the files on update.\n\nI use builds from https://chromium.woolyss.com/ too. Actually, you can install (via installer provided) any version of chromium (so it should register it in the system) and then just overwrite the installation with your own build (ungoogled, whatever). You don't need to re-register it each time you deploy another build.\n\nWhen I say \"overwrite\" I mean \"remove all the files manually and then unpack another ones\".\n\nOn Tue, 13 Apr 2021 16:30:43 +0300, Darren de Lima <darren.delima@yahoo.co.uk> wrote:\n\nThank you so much! I'm really looking forward to it!\n\nWondering, how did you register Ungoogled Chromium on your system? Did you use a script? or an installer from Eloston's homepage ([https://ungoogled-software.github.io/ungoogled-chromium-binaries/](https://ungoogled-software.github.io/ungoogled-chromium-binaries/))?\n\nI haven't been able to, as I use builds (often older ones for testing purposes) from Woolyss' project ([https://github.com/macchrome/winchrome/releases/](https://github.com/macchrome/winchrome/releases/)) (project homepage: [https://chromium.woolyss.com/](https://chromium.woolyss.com/)), which didn't offer installers for All Codecs builds (though I checked just now, and looks like they've started to, recently, for the newest builds). Until now, I've been trying chrlauncher (which keeps glitching out and occasionally launching without loading the User Profile).\n\nMany thanks,\n\nDarren J. de Lima [...]","error":{"stack":"RuntimeError: unreachable\n    at null.<anonymous> 

(line 531, 2022-03-16-01-41-50.log) 

**WIP post, will update here as I find more info**

**Comment by Simon-Laux** [comment]
Strange, I tried your post as input, but for me it does not trigger any errors.

**Comment by Darthagnon** [comment]
NB. this was from the first log after it started working again, after updating. Do you want me to be looking through the logs from when it was crashing?

**Comment by Simon-Laux** [comment]
not necessary, maybe you could try forwarding the message in question to saved messages and check if the error is logged again when opening the saved messages chat. maybe there is some strange windows encoding in there or sth else that is not saved in the logs?

**Comment by Darthagnon** [comment]
[2022-03-21-10-15-04.log](https://github.com/deltachat/deltachat-desktop/files/8314621/2022-03-21-10-15-04.log)
Tried forwarding it to myself in Saved (though I think I might have posted the wrong email file above, will try and find the right one), no errors, worked perfectly, pinged in my other email client.

**Comment by Simon-Laux** [comment]
strange, let's give up finding the issue, as we can not really reproduce it, and its catched now anyway 😉)

Do you still have the yahoo issue or can we close this issue too?

> Can't find a way to relogin, though

go to `Settings` -> `Password and Account`

**Comment by Darthagnon** [comment]
I reckon it's all solved. Thank you so much!
