### ISSUE TITLE
too wide clickable area on forwarded messages

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2627]
having a forwarded message, the title shows "Forwarded Message" instead of the sender's name, which is fine.

however, while the clickable area is usually only as wide as the text is (eg. if the name is displayed), in case for "Forwarded Message", the clickable area is as wide as the bubble, which raises questions if eg. the cursor moves to a "pointing hand" in the right area of the bubble:

<img width=640 src=https://user-images.githubusercontent.com/9800740/158412643-d098a1d2-6e34-4272-ae1f-c1010f2560ab.png>

the effect is larger if the bubbles have some content  and some width therefore.

maybe nitpicking, however, i came over that several times ...

**Comment by andresmc98** [comment]
Hi, is someone working on this issue?
i'd like to take it

**Comment by r10s** [comment]
not totally sure, but it seems unlikely that someone starts just now :)

great that you want to take care of it, @andresmc98

**Comment by andresmc98** [comment]
I think the issue its solved or I can't replicate it
