### ISSUE TITLE
Cant select proper camera.

### ISSUE THREAD

**Issue by thecodewarrior2** [deltachat/deltachat-desktop#2634]
<!--

- Operating System (Linux/Mac/Windows/iOS/Android): windows
- Delta Chat Version:1.27
- Expected behavior: select working web cam
- Actual behavior: selects first webcam it detects
- Steps to reproduce the problem: scan a qr code
- Screenshots:
- Logs:

My built-in webcam is broken. Cant select an external webcam.

**Comment by Simon-Laux** [comment]
could you elaborate?

**Comment by Simon-Laux** [comment]
do you mean you have multiple cameras and want to select which one to use for the qr code scan?

**Comment by thecodewarrior2** [comment]
Yes.

**Comment by thecodewarrior2** [comment]
if there are multiple webcams installed, there is no way within the
application to select the correct one.

See device manager screenshot. ( attached ) DeltaChat defaults to the
laptops usb 2.0 built-in webcam. This can not be used in the docking
station it has. I have an external usb webcam.  The Logitech one in the
bottom of the screenshot.  The only way to select the Logitech camera is to
disable the usb 2 camera. There is no setting in deltachat to pick the
correct camera. On the Desktop version of deltachat, I would recommend a
dropdown selection option of webcams to pick on the scan qr code screen.

**Comment by r10s** [comment]
as this is part of "QR Scanner Refactor" - is there something planned/possible that goes beyond [MediaTrackConstraints](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints) - because  this is also exposed to https://github.com/JodusNodus/react-qr-reader/#component-api and just using this might remove pressure from a  refactoring requirement

**Comment by r10s** [comment]
ftr: i also ran into that an with the continuous camera of macos/iphone, however, at the end it turns out, it was more my fault as the iphone was used for "facingMode: user" - and switching this is part of the system, not even sure if an app has access to that

**Comment by Simon-Laux** [comment]
I also already stated this on a local branch
