### ISSUE TITLE
Missing qr code to setup account on mobile device

### ISSUE THREAD

**Issue by thecodewarrior2** [deltachat/deltachat-desktop#2635]
- Operating System (Linux/Mac/Windows/iOS/Android): windows, android
- Delta Chat Version: 1.27
- Expected behavior: Scan QR code to setup existing account on new deivce
- Actual behavior: No barcode exists to setup an existing account on new device. Only to chat to someone else.
- Steps to reproduce the problem:
- Screenshots:
- Logs:
Scan to setup account exits, but there is no QR code to scan in desktop or mobile to easily setup the existing account being used on another device.

**Comment by Simon-Laux** [comment]
this is a feature proposal not a bug, the qr code scan is for burner accounts set up by mailadm: https://mailadm.readthedocs.io/en/latest/
feel free to discuss the in the forum (https://support.delta.chat), though we already have something like it planned for the future.
