### ISSUE TITLE
re-add provider-info

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2644]
on 1.28, no provider-information are shown before login for $reasons (they are used nevertheless from core).

that should be re-added.

**Comment by Simon-Laux** [comment]
See https://github.com/deltachat/deltachat-core-rust/issues/3086

**Comment by r10s** [comment]
i created https://github.com/deltachat/deltachat-core-rust/pull/3256 that should remove network from `dc_provider_new_from_email()` completely - so you should be able to revert the change that removes provider-db that time.
