### ISSUE TITLE
Layout issues in Settings window

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#2647]
- Operating System (Linux/Mac/Windows/iOS/Android):
GNU/Linux, Windows.

- Delta Chat Version:
1.28.0.

- Expected behavior:
No layout issues in Settings window.

- Actual behavior:
Misaligned text labels in Settings window.

- Steps to reproduce the problem:
-- Open Settings window.

- Screenshots:
![grafik](https://user-images.githubusercontent.com/51095533/160199749-1b44499a-67e1-4f52-abee-5dda6eb602ce.png)
![grafik](https://user-images.githubusercontent.com/51095533/160199819-c06e99ff-cc66-4044-a599-56daf905678a.png)

- Logs:
N/A.

- Credits:
Reported by user "Andrea (Gh0stz0x)" from Delta Chat group "Testing Delta Chat".

**Comment by M4ss1ck** [comment]
I can confirm. Exact same issues in Spanish (at first I thought it got something to do with translations, then I came here and found this issue)

![image](https://user-images.githubusercontent.com/34517932/161174121-04b8984b-0328-487d-b922-7a4f4787613d.png)
