### ISSUE TITLE
Appimage: the links to github and the delta chat site that should open from the "Help" menu do not work

### ISSUE THREAD

**Issue by darhma** [deltachat/deltachat-desktop#2657]
- Operating System (Linux/Mac/Windows/iOS/Android): 
Linux (debian sid/unstable)

- Delta Chat Version: 
1.28.0 Appimage (the same version 1.28.0 installed as Flatpak works correctly, I have not tried the .deb version)

- Expected behavior: 
When I go to the "Help" section of the menu and select one of the items:
Learn more about Delta Chat
Contribute on GitHub
Report an Issue
the corresponding web page should open in the browser

- Actual behavior:
When I go to the "Help" section of the menu and select one of the items:
Learn more about Delta Chat
Contribute on GitHub
Report an Issue
nothing happens

**Comment by Simon-Laux** [comment]
we could not reproduce this, what about links in messages?

**Comment by darhma** [comment]
I have both versions (appimage and flatpak) installed on the same computer and I had encountered the problem on appimage trying to report bug #2659 I had tried several times before opening the report but now that you told me you could not reproduce it I also tried again and it actually seems to work now. I don't know exactly what happened and I'm sorry I wasted your time. As for the links in the messages, there have never been any problems.
