### ISSUE TITLE
chatlist not updated when a contact is blocked

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#2664]
after opening a 1:1 chat I go to the menu, click block contact, then the chat is closed but in the chat list the 1:1 chat is still there until I search something to update the chatlist manually (I guess receiving messages will also update it) the thing is that the chat list is not updated in the block event

**Comment by Simon-Laux** [comment]
fixed by https://github.com/deltachat/deltachat-desktop/pull/2879
