### ISSUE TITLE
date label's text color in image messages is hard to read

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#2666]
![image](https://user-images.githubusercontent.com/24558636/161485620-c52e0f62-6024-4434-b94d-73383b802a4f.png)

would be better if the label's text color is white like on Android

**Comment by r10s** [comment]
> would be better if the label's text color is white like on Android

+1

in more detail, android (and ios) use #FFFFFFFF as the foreground and #55444444 ("universal_overlay" there) as a translucent text background.

this combination has proven to be readable on mostly all images - while still looking good. the combination is also used for in-chat-status-messages and date-labels that also has to fight with weird backgrounds.

Delta Chat iOS also uses these colors.

**Comment by Simon-Laux** [comment]
right could be different, though for me the green is clearly readable:
![2022-04-04_13-34](https://user-images.githubusercontent.com/18725968/161535458-bae854a4-a18b-4af8-927a-8359f894a068.png)
