### ISSUE TITLE
Uninformative error message when burner account qr code fails

### ISSUE THREAD

**Issue by flipsimon** [deltachat/deltachat-desktop#2671]
When the token of a burner account is invalid, [mailadm](https://github.com/deltachat/mailadm) returns no json but a string, making the core return an uninformative error message, leading to another uninformative error message for the user:
![image](https://user-images.githubusercontent.com/28535045/161807420-f97603bb-4c15-4de0-87d6-83e714d192aa.png)
solution: somehow show error message from mailadm to the user (fix core and mailadm)

**Comment by Simon-Laux** [comment]
maybe we need the command/json api to get the error message here:
https://github.com/deltachat/deltachat-desktop/blob/656ca7c4c5cb7062b44fd4884b0dd6972f1aed33/src/main/deltachat/settings.ts#L29-L35

still the error in the log-file is not really useful: "Failed to create account from QR code: Cannot create account, request to "https://testrun.org/new_email?t=1d_XXXXXXXX" failed: expected ident at line 1 column 2"

**Comment by Simon-Laux** [comment]
with jsonrpc we already get the error of core, which will close the desktop part of the issue:
<img width="507" alt="Bildschirmfoto 2022-07-03 um 21 57 56" src="https://user-images.githubusercontent.com/18725968/177055552-e752dc71-cea2-41d5-ac0d-67783869272c.png">
