### ISSUE TITLE
Attachment extension is lowercased for no reason

### ISSUE THREAD

**Issue by dumblob** [deltachat/deltachat-desktop#2685]
- Operating System (Linux/Mac/Windows/iOS/Android): Mac, Linux
- Delta Chat Version: 1.26.0 (git: v1.25.0-11-g3114f3d3)
- Expected behavior: the whole filename is untouched
- Actual behavior: the extension of filenames is lowercased before sending
- Steps to reproduce the problem:
1. create file `teST00.Rmd` (yes, R language requires files to have upper case `R` in related extensions :open_mouth:)
2. use DC desktop client to send the file to someone else
3. see in the message feed that the file was sent as `teST00.rmd` (notice the lowercased `r` instead of uppercased `R`)

Same thing happened with `.R` files.

- Screenshots: N/A
- Logs: N/A

I don't know if this is only a DC Desktop issue or DC Rust core issue, but I wanted to start low - therefore first here :wink:.

**Comment by r10s** [comment]
i just played around: 
- setting a draft with an `.Rmd` file is okay on android and already converts to lowercase on desktop
- on sending, however, it is converted to lowercase on both, desktop and android
so, there is probably a core issue _plus_ some additional desktop issue :)

**Comment by Simon-Laux** [comment]
probably only a core issue, there is no code that I know of that modifies the filename in desktop. in desktop the draft file is already saved in core and then displayed, so core had a chance to modify it.

**Comment by Simon-Laux** [comment]
already filed in core, nothing desktop can currently do about it. not that this is an issue desktop could solve, but moving to resurrection non the less for now.
