### ISSUE TITLE
missing .xdc files in Documents tab

### ISSUE THREAD

**Issue by M4ss1ck** [deltachat/deltachat-desktop#2696]
Hi!

When looking for the multimedia in a chat, `.xdc` files are not in Documents tab (same for the other tabs as well, although it wouldn't make sense)

Disclaimer: I make sure that there were `.xdc` files in that chat

**Comment by r10s** [comment]
for me, 1.28.2 shows .xdc files in the documents tab, not as nice as on android by [recent changes](https://github.com/deltachat/deltachat-android/pull/2273), but they're there:

<img width="962" alt="Screen Shot 2022-04-16 at 11 15 11" src="https://user-images.githubusercontent.com/9800740/163669423-b83d1ef6-1719-450c-84ae-ad9140d32185.png">

**Comment by M4ss1ck** [comment]
I'm on unreleased version, doing `pnpm dev` on my Windows 10 PC fwiw

**Comment by M4ss1ck** [comment]
I'm on 1.76, it must be that

**Comment by Simon-Laux** [comment]
ah, right thats it there are probably another view type than file when core detects them as webxdc and me and @r10s  see old webxdc's that were not detected by core (because of using an older core at that time probably)
