### ISSUE TITLE
Rocket theme: settings icon buttons have wrong font color when hovering over them

### ISSUE THREAD

**Issue by flipsimon** [deltachat/deltachat-desktop#2697]
![image](https://user-images.githubusercontent.com/28535045/163668914-72c38c63-6ced-4fe0-8282-c6aedc55f0ed.png)

**Comment by Simon-Laux** [comment]
The rocket theme is super experimental, not even shown as option when you are not in dev mode, thats why I would prefer tracking its issues all in https://github.com/deltachat/deltachat-desktop/issues/2338 instead of making separate ones that clutter the issue list.
