### ISSUE TITLE
Add attachments to chat messages

### ISSUE THREAD

**Issue by karissa** [deltachat/deltachat-desktop#27]
There is a little paperclip icon in the chat window. A user should be able to click that button and a file chooser appears. The user should be able to select multiple files from this picker, and send them.

**Comment by ralphtheninja** [comment]
Is the `image-attachments` branch for this issue?

**Comment by karissa** [comment]
yes

**Comment by karissa** [comment]
but it should probably be extended to detect the filemime from the file extension and create the appropriate message type
