### ISSUE TITLE
x-button for removing group image

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#270]
https://github.com/deltachat/deltachat-desktop/pull/263#discussion_r230356958

**Comment by nicodh** [comment]
@ralphtheninja  we have a "remove" button, is that what you meant? So can we close this?

**Comment by ralphtheninja** [comment]
We always had a remove button. I wrote this issue because of karissas comment. I don't mind closing it.

**Comment by nicodh** [comment]
In my opinion the image is too small to add an x button and at the moment the x button is used as "close" button in other places...
So I think we should stay with the current solution
