### ISSUE TITLE
App crashes on login because of missing .mail_pw <3

### ISSUE THREAD

**Issue by jankass** [deltachat/deltachat-desktop#271]
```
throw new Error('Missing .mail_pw')
            ^

Error: Missing .mail_pw
    at DeltaChat.configure (/opt/DeltaChat/resources/app.asar/node_modules/deltachat-node/index.js:106:13)
    at /opt/DeltaChat/resources/app.asar/es5/main/deltachat.js:84:10
    at binding.dcn_open.err (/opt/DeltaChat/resources/app.asar/node_modules/deltachat-node/index.js:478:9)
```

**Comment by ralphtheninja** [comment]
Seems we broke the code activating/deactivating the login button?

**Comment by ralphtheninja** [comment]
I can't repro on latest version, so I'm guessing this is an old version.

**Comment by Jikstra** [comment]
@ralphtheninja she uses `1.7.3`

**Comment by jankass** [comment]
This is because we pass a credentials object to deltachat-node with keys in camelcase (eg: mailPw) instead of snakecase (eg: mail_pw).

**Comment by ralphtheninja** [comment]
> This is because we pass a credentials object to deltachat-node with keys in camelcase (eg: mailPw) instead of snakecase (eg: mail_pw).

Oh, haha, sorry. ANY password fails. The reason "I couldn't repro" was because I thought you had to input an empty password :)

**Comment by ralphtheninja** [comment]
How can _any_ parameter work at all?
