### ISSUE TITLE
esc-key does not close menus

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2718]
the esc-key should close opend menus, eg. the menu in the upper right corner, ~~the context menus~~ and the attach menu. 

esp. for the latter, it happens to me often that i want to place the cursor somewhere with the mouse and accidentally click on the attach menu and intuitively hit "esc" - and nothing happens :)

(does not work at least on mac/1.28.2O)

**Comment by Simon-Laux** [comment]
on which context menu does this appear? context menu escape work for me

**Comment by r10s** [comment]
you are right, the right-click context menu is fine. 

the issue is about the upper-right-corner menu and the attach-menu.

**Comment by r10s** [comment]
@Simon-Laux and me just figured out that this is no longer an issue on current master, for whatever reason :)
