### ISSUE TITLE
checks for node versions 

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#2724]
Had some fun trying to build again, got a bunch of those errors, puzzling to me: 
```
> deltachat-desktop@1.28.2 build:backend /home/hpk/p/delta/desktop
> tsc --build src/main

../node/dist/context.d.ts:9:10 - error TS2305: Module '"stream"' has no exported member 'EventEmitter'.

9 import { EventEmitter } from 'stream';
```
While the README says v14.0.0 or newer is required, i use v14.8.12.  Turns out that v14.8.13 avoids the above error. 
It seems that v16 (stable node) is actually working.  The whole thing took me like an hour to figure out, and it has happened before that i stumbled into node version issues. 
Could the "npm run build" (or npm install) be made to check that a known-to-work version (from some list) is used?

**Comment by Simon-Laux** [comment]
you need to use https://github.com/deltachat/deltachat-desktop/pull/2687
