### ISSUE TITLE
update internal help

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2727]
the "funding" section and other parts are revamped and updated. i am currently still on some minor things, so it makes sense to do the update shortly before the release, also to get as many translations as possible in.

this is just a reminder, please close this issue in case that happens automatically or by some checklist anyway.

**Comment by Simon-Laux** [comment]
can't you do this pr @r10s ? It's always such a hassle for me to get the right ruby & Jekyll version to get the files. If you already do it for android and iOS it would not be much extra effort for you to also do it for desktop too.

**Comment by r10s** [comment]
if Ruby & Jekyll are required to generate the desktop help, i fear, i cannot help here (i also avoid that where possible).

however, good news is that Ruby & Jekyll are not required :)

for Android/iOS, we use the a script that just copies the already generated html-files:

```
./deltachat-pages/tools/create-local-help.py ./deltachat-pages/_site OUTPUT_DIR
```

of course, that needs to have `deltachat-pages` to be checked out somewhere. roughly, that should just do the job in case the css is in place (whereever that is, i do not know these details on desktop)

**Comment by Simon-Laux** [comment]
> already generated html-files

`deltachat-pages/_site` is generated by `jekyll serve` or a similar command isn't it?

**Comment by r10s** [comment]
> deltachat-pages/_site is generated by jekyll serve or a similar command isn't it?

yes, sth. like that - i thought, the generated files are also in the repo, but actually are not (but i am sure, at some point, they were). but i can generate the files and run the script on the deltachat-desktop dir and do a pr then.

**Comment by r10s** [comment]
did so - maybe we should also add a `scripts/create-local-help.sh` as for Andorid/iOS, so that the way for updating is exactly the same on all os (i am sure, next time, i forgot about the details)
