### ISSUE TITLE
Showing 1970 dates before first message

### ISSUE THREAD

**Issue by rosano** [deltachat/deltachat-desktop#2752]
It seems like on the desktop it shows a '1970' date when there are no messages:

<img width="753" alt="Screen Shot 2022-05-12 at 07 34 24" src="https://user-images.githubusercontent.com/1680612/168003198-aba12b74-2627-4b00-ab81-73a3b738b0ec.png">

On iOS it just doesn't show a timestamp.

<img width="375" alt="Bild" src="https://user-images.githubusercontent.com/1680612/168003407-6b6f00be-9886-46ad-9a48-5bbdc517bc66.png">

**Comment by Gh0stz0x** [comment]
I was pointed out to this problem on Android as well.
Unfortunately, the smartphone wasn't mine, so I couldn't investigate.
I think this bug needs to be moved to the core

**Comment by Simon-Laux** [comment]
nope its not a core bug, also this should be fixed in the new test release 1.29.0:

> Fix chatlist item showed wrong timestamp (jan 1 1970) if there was no timestamp
> ~ https://github.com/deltachat/deltachat-desktop/blob/master/CHANGELOG.md#1290---2022-05-05
