### ISSUE TITLE
Merge Help menu items with About dialog?

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#276]
Currently we have multiple links pointing to the homepage and various github addresses (issues etc) and they can be found both under the Help dialog and the About dialog.

![screenshot from 2018-11-04 15-47-05](https://user-images.githubusercontent.com/308049/47965596-7a117900-e049-11e8-8379-380362b12b34.png)

I propose we move everything into the About dialog leaving `Help -> About DeltaChat` a single menu item.

- [ ] merge Help menu with About dialog
- [ ] use urls from `config.js`
- [ ] remove `GITHUB_URL_RAW` (not used)

**Comment by karissa** [comment]
related to #403

**Comment by karissa** [comment]
I think it's actually quite fine how it is, usually 'about' is just an informational box like that whereas help items are in their own items. OK to close?
