### ISSUE TITLE
webxdc-title should be shown in bold

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2774]
the webxdc-title (and/or maybe the -document, so, the line above the summary) should be shown in bold.

the summary and the other texts are fine as they are now. the webxdc-title/document in the gallery is also already fine.

tested for 1.29.0 - if that is changed meanwhile, please just close this issue.

**Comment by Simon-Laux** [comment]
bold looks not so nice, I prefer slightly bigger text:
<img width="310" alt="image" src="https://user-images.githubusercontent.com/18725968/170690018-d4ab5214-951b-483b-96cd-a5988ca01b61.png">

<img width="310" alt="image" src="https://user-images.githubusercontent.com/18725968/170690118-cb7d5bf1-83d9-4354-8cc1-7de18e5b7597.png">

**Comment by r10s** [comment]
> bold looks not so nice, I prefer slightly bigger text:

let's go for consistency and stay in sync with android and ios and the desktop gallery which all show the titles in bold.

however, using a slightly bigger font-size in addition ("both", last image) would also be fine wrt consistency. i personally would just go for the same font-size and too many different font-sized easily look messy when not always having all combinations in mind.
