### ISSUE TITLE
CMD + / not opening keyboard cheatsheet

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#2776]
Reported in forum https://support.delta.chat/t/help-testing-the-upcoming-1-29-x-release/2091/9?u=jikstra

**Comment by Simon-Laux** [comment]
can not reproduce, we need more info on it to fix it

**Comment by Simon-Laux** [comment]
So this is actually about Mac being quirky again on keyboard layouts that are not the US variant, see that pressing cmd also changes the keyboard layout:

https://user-images.githubusercontent.com/18725968/170826616-e0f3720b-c643-4619-a0da-c99095d69ea3.mp4

So we can declare this as user error (or mistake of apple for not communicating it to the user)
