### ISSUE TITLE
Signing in .deb app, but never finished, stuck at 2/3

### ISSUE THREAD

**Issue by johdough** [deltachat/deltachat-desktop#2789]
Hello, and thank you all for a chance at Delta Chat...

Installed in to MINT 20.04 today with .deb file, 
Delta Chat opened, 
and input an email and a password, on new account!
 and I have Internet, or I couldn't do this "please help" ticket!
Progress Bar went to 2/3rds the way, in about 3 or 4 minutes and "Stopped" frozen in place!

So how do I get that fixed?

I have to GIVE UP on Telegram and Signal and a few others, and NEED Delta Chat asap! 

Thank you and please stay FREE!

**Comment by Jikstra** [comment]
Which version did you install, what is your provider?

**Comment by johdough** [comment]
Wow great that was awesomely fast! THANK YOU!
1. Version downloaded today...
deltachat-desktop_1.30.0_amd64.deb
2. My providers 
3. A. Cox cable, thru WIFI, and I also tried....
4. B. Data plan Tether form on my Android, with unlimited data only 300Mb used.
I hope that helps fixing the first time login!

**Comment by Jikstra** [comment]
Ah i wanted to know your email provider :P

**Comment by johdough** [comment]
Im getting the idea about whats wrong.. ... 
I'm on youtub university (lol)  So.... I'm getting more how tos there. I have to use an IMAP server, to sign up into! So I have to locate one that I can use secretly, other than googirl!
So I'll be back.... in a few days!
Thank you Jikstra!

**Comment by Jikstra** [comment]
Claro, good luck :)

**Comment by Jikstra** [comment]
Closing issue for now, feel free to reopen if it's still a problem :)
