### ISSUE TITLE
[README] install instructions should cover all deltachat-core dependencies which are needed to installed

### ISSUE THREAD

**Issue by jankass** [deltachat/deltachat-desktop#279]
Build steps for deltachat-node/deltachat-desktop are bit different than the ones for core (eg: you shouldn't install libetpan) and we should have them all in the readme. Currently it says we need pyhon-pip and libssl, but doesn't mention libsasl libsqlite...

**Comment by ralphtheninja** [comment]
Nice catch. However, we should mention that some of them are optional. libsasl isn't really needed since we have a fallback in core.
