### ISSUE TITLE
translation of "About" does not really work

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2796]
currently, the "info" line in the new drawer loosk like

```
Delta Chat Desktop
Version 1.30 - About
```

this "About" string is hard to translate. in other languages, this only works in combination with the app name. or translation result in "Circa", "Ungefähr" :) we could use sth. as "info" here, which, however, does not match the expectation of getting an "About dialog".

i suggest to change the line to

```
v1.30 - About Delta Chat
```

these strings are aleady present, so that would work out of the box. also, for internal consistency, it is good to use the same string as in the help menu.

and: android and ios look similar, at least for the version.

EDIT: as issues on transifex already pop up with these strings, i removed them [directly](https://github.com/deltachat/deltachat-android/commit/b0aaecddc3b2b9deac4d3a098e36d5b8738272ef) there.

**Comment by Simon-Laux** [comment]
those 3 strings are links, to the delta chat website, changelog and about dialog. your proposal removes atleast one of the links.
what do you think @Jikstra @flipsimon
