### ISSUE TITLE
daymarkers are missing sometimes

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2801]
the daymarkers are not always shown in 1.30.0, not sure about older versions.

eg. in the following image, there is no marker for the 27th:

<img width=500 src=https://user-images.githubusercontent.com/9800740/171999096-6fcb4896-c23c-4c89-b12d-3741bab57dca.png>

scrolling through chats, for me many more daymarkers are missing.  i cannot tell which ones, however :)

**Comment by Simon-Laux** [comment]
https://github.com/deltachat/deltachat-desktop/pull/2788/files aimed to address this

**Comment by r10s** [comment]
cool, then it seems to be fixed already. thanks for the link!
