### ISSUE TITLE
Error: Cannot find module 'deltachat-node/dist/constants'

### ISSUE THREAD

**Issue by substack** [deltachat/deltachat-desktop#2804]
When I do `npm install && npm run build && npm start` with the latest commit (85af33693132deeca81c87958b9ce35c051e6998 dated June 4 2022), I get this error:

```
Error: Cannot find module 'deltachat-node/dist/constants'
```

And there is no `dist/` directory in `node_modules/deltachat-node`

```
$ json version < node_modules/deltachat-node/package.json 
1.84.0
$ node --version
v16.14.0
$ json version < package.json 
1.30.0
$ uname -a
Linux bg 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
```

**Comment by dotlambda** [comment]
> ```
> Error: Cannot find module 'deltachat-node/dist/constants'
> ```

On which line of which file does the error occur?

**Comment by substack** [comment]
the error comes from src/shared/constants.ts line 1:

```
import { C } from 'deltachat-node/node/dist/constants'
```

**Comment by link2xt** [comment]
Works for me both on this commit and on the currently latest commit 786b7514d69ffb723bbe6e706494852a2641bfcd
Maybe some package-lock changes stuck in the staging? Does it happen on a fresh clone or after `git clean -xffd .`, `git reset --hard`?

My `node --version` is v18.3.0

**Comment by substack** [comment]
Fixed when I removed node_modules and `until npm i; do date sleep 1; done` again. I've done this before but this time I got lucky and it worked. npm install basically always fails with a timeout, so it might be related to npm crashing in a broken state.
