### ISSUE TITLE
download on demand messages appear earlier in list once downloaded

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#2816]
once downloading a download on demand message they appear at a different place in the list than the message with the download button.
This does happen often, but not every time.
Most of the time the downloaded message appears above/earlier than it's download on demand message.

@r10s do you know more about this issue, is there some special handling done on android? is this behaviour normal?

The bad UX here is that the download message you just clicked just disappears and if you don't know where to look you won't notice that it was added above.

**Comment by Simon-Laux** [comment]
just had the same problem on android, so its on all platforms.
Maybe it has something todo with timestamps. Its about message order and **not about scroll position**.

Here is it in action on desktop:
https://user-images.githubusercontent.com/18725968/176642271-8a064311-b130-471e-aee2-3ec4aa759ad2.mp4

**Comment by r10s** [comment]
yes, if scrolling position is left as is, there is probably nothing more to do on that on that on desktop or android.

still wondering, where the re-ordering, probably related to different sort_timestamp, comes from.

is it reproducible? maybe we can write a test for it.

**Comment by Simon-Laux** [comment]
> is it reproducible for you? maybe we can write a test for it.

it works as expected on iOS, maybe a recent core fixed it or dc iOS makes something better than android & desktop.

Did you test it on android with a version newer than the play store release?

**Comment by r10s** [comment]
> Did you test it on android with a version newer than the play store release?

no.

**Comment by Simon-Laux** [comment]
Have not noticed this for a while, closing for now, let's reopen if it appears again
