### ISSUE TITLE
Improvements to entering transfer autocrypt key dialog ui/ux

### ISSUE THREAD

**Issue by jankass** [deltachat/deltachat-desktop#282]
It would be nice that
1. we don't loose the entered transfer verification key if it's incorrect (currently it gets cleared after submit)
2. as soon as we typed in 4 figures into one input, automatically focus the next one so that users don't have to press tab after every 4th figure

**Comment by ralphtheninja** [comment]
>     2\. as soon as we typed in 4 figures into one input, automatically focus the next one so that users don't have to press tab after every 4th figure

:+1:
