### ISSUE TITLE
make email address editable to allow AEAP, add confirmation dialog

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2820]
to make AEAP basically work, the email address at "Password and Account" needs to be editable.

removing the `disabled` tag may already fulfill this purpose.

**Comment by Simon-Laux** [comment]
+ any dialogs for aeap?

**Comment by r10s** [comment]
> + any dialogs for aeap?

see discussion at https://github.com/deltachat/deltachat-android/issues/2328

**Comment by r10s** [comment]
dialog text is in the string `aeap_explanation`, buttons should be "Cancel", "Continue" and maybe "More Info", which points to the final blogpost address (see https://github.com/deltachat/deltachat-pages/pull/550 , so probably https://delta.chat/en/2022-07-10-aeap )
