### ISSUE TITLE
Main window content doesn't get rendered because of config folder not found

### ISSUE THREAD

**Issue by jankass** [deltachat/deltachat-desktop#283]
Reproducable by deleting `~/.config/DeltaChat` and `~/.config/Delta.Chat`.
When the program is started for the second time, it works. 

```
$ npm start

> deltachat-desktop@1.7.3 start /home/jankass/Workspace/deltachat-desktop
> electron . --debug --disable-http-cache

(node:26368) Warning: N-API is an experimental feature and could change at any time.
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, scandir '/home/jankass/.config/DeltaChat'
Missing config file: Creating new one
```

**Comment by ralphtheninja** [comment]
Nice find!

**Comment by ralphtheninja** [comment]
It's also a bit strange that there are _two_ configurations folders. There should be only _one_.

http://www.lovethispic.com/uploaded_images/208687-There-Can-Be-Only-One.png

**Comment by ralphtheninja** [comment]
It seems the `Delta.Chat` folder is an remnant. I believe it's related to `productName` (in `package.json`) used to be `Delta.Chat` but is now `DeltaChat`. This folder can be safely removed.
