### ISSUE TITLE
"Save As" does not remember last path

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2832]
using "Save As" either from chat or from gallery, one always ends up in some default path.

saving a bunch of files/pictures/whatever is not very smooth that way, you always have to (a) browse to the destination directory - or (b) save to default and copy later to the destination. both solutions are not very nice and have bad ux.

it would be much nicer, when the last used path is remembered and, when "Save As" is use another time, that path is opened instead of default.

1. i think, it is sufficient, to remember the last path in memory, on app restart, it seems reasonable to start over with the default.

2. if the last directory does not exist, however, the default should be used again

i just tested some other apps: thunderbird does 1.+2. telegram does not offer selection, so that the user always have to do some postprocessing as (b) above, this seems okay for a smartphone, but maybe not really for a desktop app that works with files quite more intensivly. in general, 1.+2. is known from many other desktop apps.

**Comment by Simon-Laux** [comment]
could be done, but might not be as trivial/clean as you might imagine it.

probably checking basename (path without file) of destination and then saving to config.json and then set start location of the file dialog to the last saved value.

**Comment by r10s** [comment]
> probably checking basename (path without file) of destination and then saving to config.json and then set start location of the file dialog to the last saved value

sounds good. before opening the file dialog, however, check that the path read from config.json still exists - otherwise, depending on the system's file-select implementation, one may end up in _totally_ weird folder :)

**Comment by r10s** [comment]
thanks for adding that 🙏 - it already saved me tons of clicks and time :)
