### ISSUE TITLE
mailto: addresses do not work internally

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2835]
when typing a message containing sth. as `mailto:foo@example.org`, a message will be drafted in an external app  (if there is none, probably nothing happens).

in contrast, when typing a message containing `foo@example.org` Delta Chat asks, as expected, if a chat with `foo@example.org` should be started.

test message:

```
you can mail me at this-is-working@example.org ...
you can also mail me at mailto:fail@example.org ...
```

both things should be just the same. if we think, opening in external app is important as well (i would not focus on that now), that could be handled by a right  click - but that should also work for both cases then.

maybe related: https://github.com/deltachat/message-parser/issues/22

**Comment by Jikstra** [comment]
Both work on linux + kde. Are mailto links working at all for you?

**Comment by r10s** [comment]
>  Are mailto links working at all for you?

yes and no :)  mailto links open an external app instead of in-delta-chat processing.

this is true for plain mailto links as well as mailto links with eg. subject.

**Comment by Simon-Laux** [comment]
can reproduce on macOS, works probably for jikstra because he has deltachat set as `mailto:` handler
