### ISSUE TITLE
show mailinglist address

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2840]
while you can meanwhile write to mailinglists, the email address, a messages is actually sent to, is opaque.

with the new ffi from https://github.com/deltachat/deltachat-core-rust/pull/3524, we can get this address from the core and should show it.

android/ios show them in the profile as there is few space in the chat title, see https://github.com/deltachat/deltachat-ios/pull/1654 and https://github.com/deltachat/deltachat-android/pull/2354, for desktop, however, i suggest to show it directly in the subtitle of the chat, so right of the text "Mailing List", after an n-dash, sth. as:

![Screenshot 2022-07-26 at 19 06 56](https://user-images.githubusercontent.com/9800740/181067957-9831e771-2dff-4c2b-a523-82f477ac0cc1.png)

cave: while often the address is "fine", it may also be quite long - so take care not to let it break the layout.

**Comment by Simon-Laux** [comment]
ups no good first issue as it needs jsonrpc stuff?
