### ISSUE TITLE
Problem with sending messages to old and new contacts (from today ) 

### ISSUE THREAD

**Issue by Arya2010** [deltachat/deltachat-desktop#2866]
- Operating System (Linux/Mac/Windows/iOS/Android):  -- Both Android & Windows 
- Delta Chat Version: -- Version 1.30.0 (git: v1.30.0)
- Expected behavior:-- Sending messages easily between two contacts 
- Actual behavior: -- Messages are not able to be sent between to contacts. Even old contacts in DC that we have chatted a lot before this bug today 
- Steps to reproduce the problem: -- Just sent a message in Delta Chat's Twitter account and described the issue 
- Screenshots: 
- Logs: -- I thought delta chat doesn't save logs !!!!!!

**Comment by Simon-Laux** [comment]
I don't understand the problem, please elaborate, not everyone wants or has access to the twitter account.

> I thought delta chat doesn't save logs !!!!!!

the logs are local on your device and automatically deleted after a while. there are just for debugging, finding and fixing bugs

**Comment by Arya2010** [comment]
> I don't understand the problem, please elaborate, not everyone wants or has access to the twitter account.
> 
> > I thought delta chat doesn't save logs !!!!!!
> 
> the logs are local on your device and automatically deleted after a while. there are just for debugging, finding and fixing bugs

Do you want me to send you the logs of yesterday?
The problem is that I can't send and receive any message with my contacts. The version seems up to date and I can't find the technical problem. 
Let me know if sending the log file helps

**Comment by Simon-Laux** [comment]
Let's start with a basic description of what your problem is and what email providers are involved.
Also logfiles can contain personal info so redact/censor them before publicly posting or send them to delta@merlinux.eu instead.

**Comment by Simon-Laux** [comment]
please reopen if it is still relevant
