### ISSUE TITLE
Log folder not opening

### ISSUE THREAD

**Issue by Septias** [deltachat/deltachat-desktop#2868]
- Operating System: Linux Manjaro
- Delta Chat Version: Version 1.32.1
- Expected behavior: When I click on `View > Developer > Open the Log Folder` the folder should somehow show up
- Actual behavior: Nothing happens

**Comment by Simon-Laux** [comment]
what desktop environment are you using? does opening the current log file work?

**Comment by Septias** [comment]
Somehow it fixed itself...?
