### ISSUE TITLE
images are not recoded

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2869]
meanwhile, we have an attach-menu where you can explicitly send out "media", such as images.

however, currently "media" are _not_ recoded, so sending a jpeg can result easily in sending out 8 mb or so. 

fix is probably simple, the media should be sent out as such, then core will recode ("files" are left alone) 

(to save everyone's bandwidth, in general, Delta Chat should make things small _by default_. if one _really_ wants to send raw data, there is still the "file" option. this is what android/ios are doing here, to keep things simple and make things work, i'd just go for that :)

(tested with 1.32.0 on mac)

**Comment by farooqkz** [comment]
@Simon-Laux What is the best way? Just downscaling and compressing would be enough maybe?

**Comment by r10s** [comment]
downscaling and compression is already implemented in core; this should not be done in UI.

instead, if the user selects sth via "Media", send them with the flag DC_MSG_IMAGE (instead of DC_MSG_FILE)

if needed and/or possible, core will change the really outgoing file and type.
