### ISSUE TITLE
message parser bugs

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2872]
these things are a bit annoying ...

- [x] https://github.com/deltachat/message-parser/issues/16
- [x] https://github.com/deltachat/message-parser/issues/60
- [x] https://github.com/deltachat/message-parser/issues/45
- [X] https://github.com/deltachat/message-parser/issues/22
- [x] https://github.com/deltachat/message-parser/issues/34
- [x] https://github.com/deltachat/message-parser/issues/35
- [x] https://github.com/deltachat/message-parser/issues/32

... and i just came over them again and was just about filing an issue as i could not find one :) (the issues in message-parser are a bit out of scope, therefore this placeholder issue :)

**Comment by dev24126** [comment]
See also [Text fragments | MDN](https://developer.mozilla.org/en-US/docs/Web/Text_fragments) about ":~:text=" within links.

**Comment by r10s** [comment]
a new one: https://github.com/deltachat/message-parser/issues/45

**Comment by farooqkz** [comment]
@Simon-Laux I guess we need to upgrade message parser in Desktop. right?
