### ISSUE TITLE
add recently seen indicator

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2873]
the lists are sorted by "last seen" on recent master, having the "recently seen" indicator as well is a great overall improvement of the contact and chat lists.

corresponding pr:  
ios (with screenshot): https://github.com/deltachat/deltachat-ios/pull/1680
android (with screenshot): https://github.com/deltachat/deltachat-android/pull/2371
core: https://github.com/deltachat/deltachat-core-rust/pull/3560

**Comment by Simon-Laux** [comment]
https://github.com/deltachat/deltachat-core-rust/pull/3584
