### ISSUE TITLE
set new stock-translations

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2880]
to get rid of the weird "$action by me" and "$action by $user" strings (cmp. https://github.com/deltachat/deltachat-android/issues/2335 and https://github.com/deltachat/deltachat-core-rust/issues/3429), several stock-translations have been deprecated and new ones have been added.

the diff of https://github.com/deltachat/deltachat-ios/pull/1683/files shows a nice overview about removed and added strings and relation from DC_STR_-constants to strings.

the new strings are already available in the android-repo as well as on transifex.

**Comment by Simon-Laux** [comment]
looks like TS doesn't lint the deprecated/removed constants, because the constants generator doesn't check the `@deprecated` doc comment in `deltachat.h`...
