### ISSUE TITLE
Save picture from chat: "saving as" dialogue pops up in DS background

### ISSUE THREAD

**Issue by g6094199** [deltachat/deltachat-desktop#2891]
- Operating System (Linux/Mac/Windows/iOS/Android): Ubuntu Budgie 22.04
- Delta Chat Version: 1.30
- Expected behavior: "saving as" dialogue should pop up to DS foreground
- Actual behavior: dialogue pops up in DS background
- Steps to reproduce the problem: try to save picture
- Screenshots: 
![Bildschirmfoto vom 2022-09-21 11-16-17](https://user-images.githubusercontent.com/37833326/191467659-33ec865f-ebdf-4df8-84b3-94557c16ead8.png)

**Comment by Jikstra** [comment]
Maybe this helps to fix it? https://github.com/electron/electron/issues/10723

**Comment by Simon-Laux** [comment]
have you enabled "always on top" for the DC window?

Anyways closing this now, we can reopen it when there is new information and it still appears on recent versions
