### ISSUE TITLE
No notification on Mobian

### ISSUE THREAD

**Issue by HERBETC** [deltachat/deltachat-desktop#2906]
- Operating System : Mobian (linux debian mobile)
- Delta Chat Version: Version 1.32.1 (git: flathub)

Can't get notification and/or update for new message.
New message gets only after open app. All other apps have notification like geary, chatty and more

**Comment by Simon-Laux** [comment]
the app must be active for receiving notifications. Also we did not make any effort yet to adjust the desktop app to convergent mobile usage. So the current state of your usecase is unsupported. I'm surprised that it works at all for you, doesn't the chatlist cover half of the chat? also last time i tried it on a pinephone the text was kinda blurry.

**Comment by HERBETC** [comment]
Of course, the application must be active, but it would be nice if it started with a .desktop in autostart with an exec that calls a hidden service (for example: Exec=deltachat --dapplication-service), StartupNotify=true and NoDisplay=true.
also, the .desktop should include
X-GNOME-UsesNotifications=true.
The application works very well (the text is well readable) if you use the zoom function. If the application had windows it would be great.

**Comment by Simon-Laux** [comment]
you can do that autostart file for yourself if you want, there is the `--minimized` cli flag you could use for that. see https://github.com/deltachat/deltachat-desktop/blob/master/docs/CLI_FLAGS.md

**Comment by Simon-Laux** [comment]
mobile linux is not explicitly supported at the moment, when further discussing this we should do so in the forum https://support.delta.chat
