### ISSUE TITLE
escape-key does not always close enlarged image

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2919]
when enlarging an image from the gallery and pressing the "next" button _with the mouse,_ "escape" stops working for that image.

"escape" works in most other cases: when enlarging from the message view or when using the right arrow key for "next".

to reproduce:

- open the gallery from a chat (the chat should have some images)
- open any image
- tap the "next image" button on the right (do not use the keyboard for that)
- the next image is shown, but you cannot close the view by "escape"

**Comment by Simon-Laux** [comment]
pressing escape multiple times works for me, so maybe not too important?

**Comment by r10s** [comment]
> pressing escape multiple times works for me

does not work for me on macos 12.6 with delta chat 1.32.1.

but i agree that, although annoying, this bug is not too important :)

**Comment by farooqkz** [comment]
I can reproduce it in 5ffae911f94e69c113c5 and I can't close it with Esc no matter how many times I press it.

**Comment by farooqkz** [comment]
Okay this bug is from `Overlay` of blueprintjs: 

https://github.com/palantir/blueprint/issues/5947
