### ISSUE TITLE
clicking on system message that is not from webxdc still jumps to previous message

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#2933]
this should not be the case, should it?
Is there even a way to know whether a system message is from a webxdc or not?

**Comment by r10s** [comment]
> this should not be the case, should it?

it should not be the case.

> Is there even a way to know whether a system message is from a webxdc or not?

yes, by checking if the [message parent](https://c.delta.chat/classdc__msg__t.html#aa349dbcf03838d6f371d09b16fd7b4ec) is of type DC_MSG_WEBXDC.

here is the corresponding android check: https://github.com/deltachat/deltachat-android/blob/master/src/org/thoughtcrime/securesms/ConversationFragment.java#L795

**Comment by Simon-Laux** [comment]
I'd prefer using `get_info_type()`, the other option might require more calls to the backend or in the jsonrpc layer.
info type will be available with https://github.com/deltachat/deltachat-core-rust/pull/3707
