### ISSUE TITLE
too much and too fast overscrolling

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2956]
if you scroll up in a larger chat, some more messages are loaded.

however, after some threshold, that usually scrolls for a page or so, the overscrolling is never stopped, scrolling continues for minutes if the chat is large enough.
usually, the scrolling slows down and stops, this was also the case before 1.33.

you can switch to another chat - when switching back, scrolling continues. (EDIT: hard to reproduce, i have seen that point several times, however)

the only way to stop scrolling is to swipe to the other direction.

(using 1.33 mac, scrolling by touchpad, before 1.33, things are fine wrt scrolling)

**Comment by gerryfrancis** [comment]
I can reproduce the issue reliably on my notebook running Windows 8.1 Pro: I just have to wipe my finger down extremely fast several times (five to six per second!), and scrolling up stops only at the beginning of the chat history.

**Comment by r10s** [comment]
> it also gets stuck in scrolling when you with from a chat with only one message to a chat with many messages

yip, i can confirm this. for me, the issue is also reproducible with _few_ messages, as long as all fit on the screen; switching then to a large chat starts scrolling, even without swiping or so at all.
