### ISSUE TITLE
rename "webxdc"  to "Private Apps" for the enduser

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2959]
as discussed at https://github.com/deltachat/deltachat-android/pull/2377 and at other places, the term "Webxdc" is too technical, it is the format of the more understandable term "Private App".

in UI, currently, this seems to affect  the tab "Webxdc" in the gallery only. this one should be called "Private Apps" (string `webxdc_apps`). the "empty hint" should use the string `tab_webxdc_empty_hint`.

moreover, on android/ios, we use the string `webxdc_app` if a concrete app has an empty summary - either in the bubble or as a draft. this makes a bit more clearer, what the things is about. if there _is_ a summary, however, the string is _not_ shown to not clutter UI with too many information. maybe desktop should also adapt to that behavior.

**Comment by Simon-Laux** [comment]
probably just need to pull translations again?

**Comment by r10s** [comment]
> probably just need to pull translations again?

if the mentioned strings are already used, yes :)
