### ISSUE TITLE
high CPU usage on Ubuntu 16.04 with 1.7.4-X

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#296]
Using current 3190bbac8e58cbf1475f12145ecc6bf6cf67a188 i get consistently high CPU usage of desktop even though there is no apparent activities (no arriving messages etc.). see screenshot. 
![snap-desktop-cpu](https://user-images.githubusercontent.com/73579/48400817-17e30300-e730-11e8-9720-5c713f97c0e7.png)

also the whole UI feels more sluggish than it used to feel like (maybe 2-3 weeks ago).

**Comment by karissa** [comment]
This is probably because we're fetching all of the messages all of the time and we had that really long group message for daily coordination. let's see if its better once we get #6

**Comment by hpk42** [comment]
On Tue, Nov 13, 2018 at 09:25 -0800, Karissa McKelvey wrote:
> This is probably because we're fetching all of the messages all of the time and we had that really long group message for daily coordination. let's see if its better once we get #6  

hum, does this fetching of all of the messages really happen continously?
I am seeing the CPU load continously, not just in a spike. 
And does this fetching happen for all of the chats or just the selected chat?

**Comment by Jikstra** [comment]
It would be interesting if this is the render or backend process/thread. @karissa can we figure this out somehow?

**Comment by ralphtheninja** [comment]
@hpk42 Have you logged in/out many times? Can you see how many threads are running? (`htop` is nice here)

**Comment by hpk42** [comment]
On Tue, Nov 13, 2018 at 14:10 -0800, Lars-Magnus Skog wrote:
> @hpk42 Have you logged in/out many times? Can you see how many threads are running? (`htop` is nice here)

no, i don't think i logged in and out. 
I just re-started desktop and for now, the high CPU usage is not there
even if i click around the various (big) chat groups. 

I'll see to run "htop" when it appears again. I leave desktop running
in the background for now ...

**Comment by karissa** [comment]
Hey all, this may or may not be related to the CPU issue, but it might also help us with requesting things as needed (#6)

regarding slowdowns in electron renderer processes:
 * youtube video showing the performance difference before and after https://www.youtube.com/watch?v=A1lVBr5BchE&feature=youtu.be 
 * the code: https://github.com/beakerbrowser/beaker/commit/d60d4a86192be6db3a57652dd723a26b702f9a14

Perhaps need to do something similar for deltachat. The sychronous RPC calls can make the UI hang and if we're spawning an rpc call and it hangs in deltachat, we could wait for the response for some time and not know it's spinning in the background.

here's the API he's using: https://www.npmjs.com/package/pauls-electron-rpc

**Comment by ralphtheninja** [comment]
> Perhaps need to do something similar for deltachat. The sychronous RPC calls can make the UI hang and if we're spawning an rpc call and it hangs in deltachat, we could wait for the response for some time and not know it's spinning in the background.

@karissa I didn't quite get if the "running dat in a separate" process fits in with our use case or if it was the `pauls-electron-rpc` thingie that made it quicker.

**Comment by karissa** [comment]
I wonder if you still see this on the newer versions (esp. ones incoming that use electron 3) @hpk42? Please re-open if you do.
