### ISSUE TITLE
[MessageList] sometimes not getting unlocked?

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#2974]
For me happend after randomly spamming the jumpDown button

**Comment by Simon-Laux** [comment]
just happened to me, while chat store is locked I can not even change the chat, because the chat-store is a singleton (we should really recreate it for each new chat IMHO. Or separate message list from chat store and only replace the message list (which is then holding the scroll locks)

**Comment by Jikstra** [comment]
Nah we should just fix the bug. I think we can add some code that remembers which part of the code locked this lock and when and then report to us if it's locked for longer then x.
