### ISSUE TITLE
Sometimes events stop working

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#2992]
which results in the chatlist not updating, no update on the sending state when sending messages and so on.

I encountered this bug 2 times already, but I don't know I'd cause yet, nor do I have steps to reproduce it yet.

**Comment by r10s** [comment]
the whole app feels is like frozen then? no more clicks work (but things are still drawn)?

this also happens to me some times, however, i also did not found a way to reproduce that (1.33.0/macos)

**Comment by Simon-Laux** [comment]
I had that completely frozen thing too, but this time it's a different issue, ui is still responsive, but does not react to core events at all, could be that it'll be fixed by https://github.com/deltachat/tiny-emitter/commit/8e6490bc38b433a8af5faeb0b377b7e47315b567 (I suspect the event listeners throwing errors was the problem, because if that happens the other listeners are not called anymore :( )

https://github.com/deltachat/deltachat-desktop/pull/2991 should fix it for the incoming messages event, but https://github.com/deltachat/tiny-emitter/commit/8e6490bc38b433a8af5faeb0b377b7e47315b567 should fix it in general (it's already on core master now, was merged with https://github.com/deltachat/deltachat-core-rust/pull/3741)

**Comment by Simon-Laux** [comment]
>  but UI is frozen.

is it really frozen or just does not react to events? are you on the current master branch? does the dev console say something about a chat store being locked?

**Comment by Simon-Laux** [comment]
So after running desktop for some time there are no events anymore (~4680.2s in this case).
The events are not sent by the backend so this is an issue with the node bindings or cffi most likely.

**Comment by Simon-Laux** [comment]
could this have been related to the high cpu usage bug (loop bug in recently seen logic)?

**Comment by Simon-Laux** [comment]
didn't encounter it, so I guess it was the busy task
