### ISSUE TITLE
tweak "forward dialog"

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3006]
as recently discussed in dc, currently, when forwarding messages, there is no confirmation dialog (as for android/ios) and also the dialog lacks context. being only little distracted, easily results in doing things wrong which can have a quite bad social impact :)

- add the title `menu_forward` ("Forward Message") or `forward_to` ("Forward to…")
- before forwarding show a dialog with the text `ask_forward` ("Forward messages to %1$s?") or `ask_forward_multiple` ("Forward messages to %1$d chats?", only in case forward to multiple recipients is possible somehow)

**Comment by Simon-Laux** [comment]
should the destination chat be selected after the confirmation dialog, or before so user can see the chat where they are about to forward the message to?

**Comment by r10s** [comment]
> should the destination chat be selected after the confirmation dialog, or before so user can see the chat where they are about to forward the message to?

showing the destination chat already while the confirmation dialog is shown sounds like a good idea, +1. that would make it even more obvious where the message is forwarded to, indeed.
