### ISSUE TITLE
allow accessing webxdc source

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3007]
if [`source_code_url`](https://c.delta.chat/classdc__msg__t.html#aee526949983962ed25adf33a2f5e6878) is not empty, that should be made available to the user in an unobtrusive way (not taking space in the app window nor adding things there). the already existing menu seems to be an ideal place for that, although there seem to be some implementation issues iirc.

cmp. https://github.com/deltachat/deltachat-android/pull/2301, https://github.com/deltachat/deltachat-ios/pull/1593

**Comment by Simon-Laux** [comment]
This is the case already, just not on macOS:
![image](https://user-images.githubusercontent.com/18725968/201758046-c9f75ac0-11e4-4fbf-b776-caffa5a644fc.png)

there are questions about the macOS menu, as there can only be one menu on macOS, while on linux and windows there can be a different menu for each window.

**Comment by r10s** [comment]
ahh, that one, i remember. shame on electron that it is not handled there. that time, we found some workaround at https://github.com/electron/electron/issues/4327 but yes, it is probably not the most important thing then.

**Comment by r10s** [comment]
was just searching for source code on desktop/mac again while adding [CryptoText](https://github.com/DavidSM100/CryptoText/) to [xdcget](https://codeberg.org/webxdc/xdcget) - then i remembered it is missing on macos 😅 i'd consider this as a bug :)
