### ISSUE TITLE
"show in chat" does not work

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3020]
open a chat gallery with some images -> right tap an image -> select "show in chat"

-> nothing happens (1.33.2/mac)

same for audio/files/videos/apps

also the "show in chat" from "chat audit log" does not work.

**Comment by dotlambda** [comment]
It does work for me on version 1.33.2 on NixOS.

**Comment by Jikstra** [comment]
Also doesn't work on linux for me

**Comment by Simon-Laux** [comment]
I can reproduce in the gallery, but not in the chat audit dialog
