### ISSUE TITLE
[Discussion] Disable mac builds until ssl works?

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#303]
I'd like to stop making releases for mac until we have solved the issues with ssl. I don't think it makes sense to deliver an insecure application, even if it's still a preview version. If others feel that's ok, I don't mind, it just feels wrong for me personally.

**Comment by karissa** [comment]
The mac builds are insecure?

**Comment by ralphtheninja** [comment]
> The mac builds are insecure?

SSL doesn't work, so I'd say so yes.

**Comment by ralphtheninja** [comment]
Correction, you can't even connect to a server over ssl so it's currently unusable. Unless you're connecting to a mail server without ssl.

**Comment by ralphtheninja** [comment]
https://github.com/deltachat/deltachat-desktop/commit/12bab3010946d0dcd9147db36055878df90a739c
