### ISSUE TITLE
sticky "more messages below" indicator

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#3033]
Using a pretty master desktop and core i can not get rid of the "more messages indicator" in a particular chat. 
![Screenshot from 2022-11-28 17-11-46](https://user-images.githubusercontent.com/73579/204327312-98521de9-6da3-4c87-9018-c622eba01a0c.png)

**Comment by r10s** [comment]
i can confirm this bug, but i have not found an easy way to reproduce it yet.

**Comment by Simon-Laux** [comment]
Its when you still have unread messages above, it goes away when you scroll up and down, sure its not ideal, also code should say that its hidden when at bottom I think, so needs some more investigation.
- Is it only broken mark as read logic?

- Also apart from this bug, should we have some kind of indicator when unread messages start?

**Comment by r10s** [comment]
iirc, it was sticky even when switching between chats, i will have a closer look when it happens next time.
