### ISSUE TITLE
show verification marker after contact/group name

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3035]
from nov22 consistency discussions:

- Android always puts the v-mark after contact or group name,  and also in profile
- iOS always puts the v-mark on the avatar (group or contact), also in profile
- Desktop puts v-mark on Chat-avatar, and after contact names,  and v-mark in group-avatar in the group profile but not in the contact profile

Solution: make all platforms do the same thing, namely show v-mark after contact and group names, also in profiles and add a add a byline "verified" ([later ""verified by ..."](https://github.com/deltachat/deltachat-core-rust/issues/3786)) to the profiles.

This also solves the visual conflict between "online" and v-marks.

cmp. https://github.com/deltachat/deltachat-ios/issues/1759, https://github.com/deltachat/deltachat-core-rust/issues/3786

**Comment by Simon-Laux** [comment]
where should the byline be? or can we move that part to a separate issue?

**Comment by r10s** [comment]
as the "View Profile" headline is a bit meaningless anyway, we could change it to "Contact" (string `tab_contact`) and "Verified Contact" (string `verified_contact`).

i think, that is an improvement already now.

but i would also be fine with only adding the verification marks for now and postpone the byline bit until core is ready for the "verified by" information. no need to create a separate issue for that; once we have core ready we probably check that there are issues for the UI anyway.

**Comment by Simon-Laux** [comment]
Implemented in https://github.com/deltachat/deltachat-desktop/pull/3045, we can implement the "verified" / "verified by" text later in a different issue, closing this one for now.
