### ISSUE TITLE
scrollbar on welcome screen superfluous

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3040]
just after starting the app the very first time after a fresh installation, the window size is chosen so that a scrollbar is needed; the last button is shown only partially.

might be nitpicking, however, as this is the very first impression, users get from the app, it seems worthwhile to consider tweaking this dialog. either by choosing a larger height of the window of by tweaking its content to fit to the window.

<img width="1134" alt="Screenshot 2022-12-02 at 14 57 06" src="https://user-images.githubusercontent.com/9800740/205309404-aaf58fc7-5f26-403c-b425-811447a2b490.png">

the dialog is somehow adaptive, on smaller heights, the image is skipped, so, at some point, the gist was probably to never show scrollbars. however, maybe the adaptiveness was designed for two buttons and not for three.

(seen on mac with dc 1.34.0)

**Comment by dumblob** [comment]
I use (very) small screens and scrollbar is essential as fallback, always. So yes, hide on big screens but expose on smaller screens.
