### ISSUE TITLE
cannot show Delta Chat via tray icon sometimes

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3041]
on mac, sometimes, the tray icon is useless as there is no option to show the app when it is hidden; instead, the menu entry "Hide" is shown (although Delta Chat is already hidden):

<img width="826" alt="Screenshot 2022-12-02 at 20 53 24" src="https://user-images.githubusercontent.com/9800740/205375304-dade16b2-4a8b-47b9-8dae-de68870f320a.png">

telegram shows "Show Telegram" if Telegram is hidden  - i think, sth. like  that is missing in Delta Chat.

not sure if it ever worked before , i disabled the icon on the previous installation and just came over it again while setting up a new pc :)

**Comment by cehteh** [comment]
I have the a similar Problem on Linux x86_64, Debian. i3wm/i3bar. Since I installed 1.34 DC has no tray icon anymore (reproducible on another Computer as well). Should this be a new ticket?

**Comment by Simon-Laux** [comment]
>I have the a similar Problem on Linux x86_64, Debian. i3wm/i3bar. Since I installed 1.34 DC has no tray icon anymore (reproducible on another Computer as well). Should this be a new ticket?

yes that's a different enough issue
