### ISSUE TITLE
"Show full message in browser" doesn't work - "Firefox can’t find the file at /tmp/deltachat-8DEtDk/message.html"

### ISSUE THREAD

**Issue by missytake** [deltachat/deltachat-desktop#3056]
- Operating System (Linux/Mac/Windows/iOS/Android): Xubuntu 22.04
- Delta Chat Version: 1.34.0
- Expected behavior: When I receive a message which is too long to be displayed in one message bubble, and I click on "show full message in browser, it's shown in my system browser (Firefox in this case). Alternatively it could be shown in a webview, but I expect it to be shown.
- Actual behavior: A browser tab with the following error is shown: "Firefox can’t find the file at /tmp/deltachat-8DEtDk/message.html." The file does exist though.
- Steps to reproduce the problem:
  - receive a large mail
  - click on "show full message in browser"

**Comment by Simon-Laux** [comment]
maybe reload after some time? or are you using flatpack or some other sandboxing for either DeltaChat or the Browser?

**Comment by missytake** [comment]
right, firefox is delivered with snap in ubuntu 22.04 -.- which creates its own /snap/firefox loop device. Might be the reason.

Reloading after some time doesn't work, also not after confirming that the file is there now.

**Comment by r10s** [comment]
maybe time to show the html-pages internally, by webxdc we should now have enough expertise to harden a webview. iirc the browser thing was only a temporary workaround because of considerations wrt security.

**Comment by Simon-Laux** [comment]
> maybe time to show the html-pages internally, by webxdc we now maybe have enough expertise to harden a webview (iirc the browser thing was only a temporary workaround because of considerations wrt security)

possible but not as easy as you're implying here, we need a new window (that's easy), but we also need a way to provide a button to load the external stuff (I know how to do it, but it's not trivially easy, so a week of work or more I estimate)
