### ISSUE TITLE
"Reply Privately" not available in mailing lists

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#3090]
- Operating System (Linux/Mac/Windows/iOS/Android):
Windows 8.1 Pro.

- Delta Chat Version:
1.34.2.

- Expected behavior:
"Reply Privately" is available in mailing lists.

- Actual behavior:
"Reply Privately" is not available in mailing lists.

- Steps to reproduce the problem:
-- Select a mailing list.
-- Right-click a received message. (Result: "Reply Privately" is not offered in the context menu.)

- Screenshots:
N/A.

- Logs:
N/A.

- Remark:
This is a result based on the comment from @adbenitez here: https://github.com/deltachat/deltachat-android/issues/2430#issuecomment-1396107602

**Comment by Simon-Laux** [comment]
this is something for the forum or core, it's not desktop specific.

**Comment by gerryfrancis** [comment]
@Simon-Laux It is available in the Android client, so I think it is Desktop specific.

**Comment by Simon-Laux** [comment]
there you are: https://github.com/deltachat/deltachat-desktop/pull/3103
