### ISSUE TITLE
 Email account name and/or profile picture in the top banner line

### ISSUE THREAD

**Issue by UserWillie** [deltachat/deltachat-desktop#3109]
Hello,
When using several e-mail accounts, it would be useful on the (Windows) PC if the currently used e-mail account name and/or the current profile picture were permanently visible in the top banner line (similar to the Android mobile phone with the profile picture).
Regards, Willie

**Comment by gerryfrancis** [comment]
@UserWillie Thank you for your inquiry. Good idea, I second that! :)

We do not discuss feature requests in our Github repositories, but in the Delta Chat Community Forum, please look here: https://support.delta.chat/c/features/6

We always welcome good ideas on how to improve Delta Chat, so please post your suggestions in the forum where they can be discussed in public. (Sometimes even the devs chime in and respond, too.)

Thank you again! I am closing here.
