### ISSUE TITLE
Require less clicks to mute the chat

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop#3116]
Currently in Delta Chat Desktop to mute the chat one has to
1) right-click the chat in the chatlist
2) select "mute notifications"
3) select radio button
4) click ok

Compare this to Signal Desktop which uses submenus for options:
![1](https://user-images.githubusercontent.com/18373967/217521050-14ba73dc-1919-4c12-8b8e-6741c21347e5.png)

**Comment by Simon-Laux** [comment]
This requires to implement sub-menus into our custom context menu. maybe a nice task for @maxphilippov if he wants?
