### ISSUE TITLE
show a message Group image deleted without deletion image

### ISSUE THREAD

**Issue by alfaslash** [deltachat/deltachat-desktop#312]
Scenario:
* Select a grout chat without image;
* Select `Edit Group` in hamburger menu;
* Click on `Save` button;
* Show message `Group image deleted.`

Expected result: show a message to delete the image only after the actual deletion of an image group.

**Comment by ralphtheninja** [comment]
You mean you get the message `Group image deleted` without it being deleted at all?

**Comment by ralphtheninja** [comment]
This is most likely due to passing `null` to `deltachat-node/core` which then tries to delete the image.

@r10s Maybe this could be a no-op in core if there is no group image?

**Comment by alfaslash** [comment]
> You mean you get the message `Group image deleted` without it being deleted at all?

Yes, it is
