### ISSUE TITLE
Initially loaded message page size is too low

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#313]
Currently we only load 20 messages if we open a chat, which is quite low in my opinion compared to telegram... This is maybe because of the deltachat-core api only allows us to grab a single message instead of a range which would make it a lot faster and we're not using a "virtual list" but a "prepend on demand" model.

**Comment by karissa** [comment]
The current way we do it is like signal desktop, the first X messages are loaded and when the person scrolls up, it loads the next X. Currently X = 20.

Telegram and DeltaChat Android simulate the rendering of all messages so you can click an arbitrary point back in time and scroll quickly there. This would be a nice UX improvement but seems minor at this time.

**Comment by Jikstra** [comment]
I think leaving X = 20 is fine, but it still feels weird because at the first step the messages double, it feels less weird if it only loads a "bit" more. So having 50 messages loaded initially and then loading 20 more. The scrollbar stays in the upper half instead of jumping to the middle. Minor issue, maybe not fixable without changes to the core. Still wanted to track it because it felt weird to me the first time i tried the new chatview.
