### ISSUE TITLE
Tray Icon missing

### ISSUE THREAD

**Issue by cehteh** [deltachat/deltachat-desktop#3138]
- Operating System (Linux/Mac/Windows/iOS/Android):
  XOrg,  Linux x86_64, Debian 11.6, i3wm/i3bar. 
- Delta Chat Version:
  1.34.3 (and .4)
- Expected behavior:
  Tray Icon is visible in the Status bar as before.
- Actual behavior:
  No Tray Icon
- Steps to reproduce the problem:
  Start Delta chat
- Screenshots:
- Logs:
log shows:
```
2023-03-01T15:26:59.975Z	main/tray             	INFO	""	"add icon tray"
```
but .. not tray icon visible

**Comment by Simon-Laux** [comment]
This seems to be this electron bug: https://github.com/electron/electron/issues/36602, which was already fixed, so it should be fixed with this electron upgrade pr: https://github.com/deltachat/deltachat-desktop/pull/3144

**Comment by Simon-Laux** [comment]
should be fixed in https://download.delta.chat/desktop/v1.36.1/ , please reopen if it still occurs
