### ISSUE TITLE
Display the date near video chat invitation

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop#3146]
Android version displays the date and encryption status near video chat invitations, but on Desktop it is only visible in the message info.

**Comment by Simon-Laux** [comment]
<img width="388" alt="Bildschirmfoto 2023-04-04 um 22 39 02" src="https://user-images.githubusercontent.com/18725968/229915037-632ee92a-180f-4388-a0a2-b04be167fee8.png">
 like this?
