### ISSUE TITLE
why use electron-js instead of tauri or nwjs?

### ISSUE THREAD

**Issue by ghost** [deltachat/deltachat-desktop#3147]
Hi.

I would like to know why they are using electron-js instead of [tauri](https://tauri.app/). Why use electron-js instead of [tauri](https://tauri.app/)?

- I ask this question here because I don't have a Discourse account on the delta-chat community and I don't want to have a account as well.
- I ask about using electron-js because electron-js consumes a lot of ram. And there are good alternatives to electron-js that use less ram. For example, [tauri](https://tauri.app/) or [nwjs.io](https://nwjs.io/).
- Another alternative is to use an architecture similar to [nullboard ](https://github.com/apankrat/nullboard). Where you have an html, css, js website with calls via http on localhost. We can have a client-delta-chat that is responsible for locally using the protocol imap/smtp/pop3 etc. This alternative is more performant than electron-js, nwjs or tauri. 
   - So, this architecture could help in the development of this feature[web-client-possible](https://support.delta.chat/t/web-client-possible/467/1). 
   - So, each person can have a github account or netlify account or vercel account or render account and make fork delta-chat-spa and then locally install delta-chat-agent to have imap/smtp/pop3 support etc.
   - So in this way you would have multiple serverless delta-chat web instances for multiple desktops (linux, windows, macOs) or mobile devices with html, js, css without electron-js, tauri, nwjs.io.

**Comment by Septias** [comment]
We are thinking about porting to tauri at some point, @Simon-Laux an me already had some discussion about it. 
Regarding the nullboard architecture, we are currently using webRTC on the frontend which is similar to the localhost-approach you mentioned. Even though we are not quite there yet, this might enable us to create a web-version in the future.

**Comment by Simon-Laux** [comment]
> , we are currently using webRTC on the frontend 

jsonrpc (over websocket transport or electron ipc) to be exact.

**Comment by Simon-Laux** [comment]
to answer the initial question, tauri did not exist back wen we started deltachat desktop. we have plans for experimenting with tauri and webclients, jsonrpc was a big step into that direction.
closing this issue, because there is no immediate actionable item.

**Comment by 78mF4n** [comment]
Hey everyone!

I had a question similar to this closed issue. So, I appreciate everyone's response here.
