### ISSUE TITLE
nostr in delta-chat?

### ISSUE THREAD

**Issue by 78mF4n** [deltachat/deltachat-desktop#3149]
Hey everyone!

I would like to know if it is possible to support the nostr network protocol in delta-chat. It is possible to support the nostr network protocol in delta-chat?

*Before requesting support for nostr in delta-chat, I would like to say something in general:* 
- what are the advantages and disadvantages of email?
- what are the advantages and disadvantages of nostr?
- what are the advantages and disadvantages of nostr compared to email in delta-chat?
- why not use nostr in delta-chat instead of just email?
- what alternatives do we have to nostr for synchronizing messages?

#### what are the advantages of email?
- E-mails provides faster and easy mean of communication. One can send message to any person at any place of world by just clicking mouse.
- Various folders and sub-folders can be created within inbox of mail, so it provide management of messages.
- It is effective and cheap means of communication because single message can be send to multiple people at same time.
- E-mails are very easy to filter. User according to his/her priority can prioritize e-mail by specifying subject of e-mail.
- E-mail is not just only for textual message. One can send any kind of multimedia within mail.
- E-mail can be send at any hour of day, thus ensures timeliness of message.
- It is secure and reliable method to deliver our message.
- It also provide facility for edition and formatting of textual messages.
- There is also facility of auto-responders in e-mail i.e. to send automated e-mails with certain text.
- To write an e-mail there is no need of any kind of paper, thus it is environment friendly.
- Email is a free tool. Once you are online, there is no further expense that you need to spend on in order to send and receive messages.
- Email is quick. Once you have finished composing a message, sending it is as simple as clicking a button. Email, especially if an email system is integrated into the network, is sent, delivered and read almost immediately.
- Email is simple. It is easy to use. Once your account is set up, composing, sending and receiving messages is simple. Also, email allows for the easy and quick access of information and contacts.
- Email allows for easy referencing. Messages that have been sent and received can stored, and searched through safely and easily. It is a lot easier to go through old email messages rather than old notes written on paper.
- Email is accessible from anywhere – as long as you have an internet connection. Whether or not you are in the office or on the field, or even overseas, you can access your inbox and go through your messages.
- Email is paperless, and therefore, beneficial for the planet. Not only can you reduce the costs of paper, you are actually reducing the damage paper usage does to the environment.
- Email allows for mass sending of messages. An effective medium to utilize to get your message out there, you can send one particular message to several recipients all at once.
- Email allows for instant access of information and files. You can opt to send yourself files and keep messages so that you have a paper trail of conversations and interactions you have online just in case you may need them in the future.

#### what are the disadvantages of email?
- It is source of viruses. It is capable to harm one’s computer and read out user’s e-mail address book and send themselves to number of people around the world. So, It’s best to be aware of this possibility so that you are careful when opening messages from people you don’t know, or when downloading attachments.
- It can be source of various spams. These spam mails can fill up inbox and to deletion of these mail consumes lot of time.
- It is informal method of communication. The documents those require signatures are not managed by e-mail.
- To use facility of e-mail, user must have an access to internet and there are many parts of world where people does not have access to Internet.
- Sometimes, e-mails becomes misunderstood as it is not capable of expressing emotions.
- To be updated, user have to check inbox from time-to-time.
- Email could potentially cause information overload. Some messages may be dismissed or left unread, especially if there are a lot coming in and the network has not integrated some sort of email alert system into the computers at work.
- Email lacks a personal touch. While some things are better off sent as written and typed messages, some things should be verbally relayed or written by hand in a note or letter.
- Email can be disruptive. Going through each email can be disruptive to work as it does require a bit of time. This disruption is decreased through the utilization of an email alert system.
- Email cannot be ignored for a long time. The thing with email is that it needs constant maintenance. If you ignore it, more and more messages will enter your inbox until it gets to the point that your inbox is no longer manageable.
- Email can cause misunderstandings. Because email does not include nonverbal communication, recipients may misinterpret the sender’s message. This is particularly true of senders fail to go through their messages before they send them.
- Email should be kept short and brief. This is especially difficult if you are one to send messages that are too long.
- Email requires timely responses. While some people tend to disregard messages, those that require responses should be replied to as soon as they are received and read. If not, urgent and important messages may be left untended.
- Email is still among the most widely used[communication tools in the workplace today. However, while email is still the go-to medium for a lot of people, companies find that its disadvantages overtakes its advantages if they don’t take steps for improving email communication.
- Although email is just a set of protocols for sending and receiving messages: rpop, pop2, pop3, jmap, smtp, etc. in a decentralized and distributed way. Even so, because there are few known players such as Gmail, Yahoo, Outlook, Protonmail, Tutanota etc - it turns out that the "set of protocols that make up the email in a decentralized and distributed way" becomes centralized

#### what are the advantages of nostr?
- Simple: The protocol is based on very simple & flexible Event objects (which are passed around as plain JSON) and uses standard public-key cryptography for keys & signing. This makes it easy to run relays and build clients and ensures that the protocol can be extended over time.
- Resilient: Because Nostr doesn't rely on a small number of trusted servers for moving or storing data, it's very resilient. The protocol assumes that relays will disappear and allows users to connect & publish to an arbitrary number of relays that they can change over time.
- Verifiable: Because Nostr accounts are based on public-key cryptography it's easy to verify messages were really sent by the user in question.
- You are in control: Built on open internet protocols, there is no platform that can ban or censor you. You are in control of your data & speech.
- Encrypted: End-to-End encrypted private messaging. Keep big tech out of your DMs.
- No registration required: Creating an account doesn't require a phone number, email or name. Get started right away with zero friction.
- No servers required: Messages are distributed via decentralized relays.  No need to run any infrastructure and there are no single points of failure. Simple!
- Programmable: Easily integrate bots that automate your life or business. Get notified when your servers go down, repost to your team and collaborate in realtime
- Without spam: To mitigate spam, relays can implement quotas, speed limits, and payment requirements for posting content. As each message in Nostr is uniquely identified by its ID (which is a hash), it is possible to require that each message be mined in a way that meets a certain established difficulty (Proof of work). The difficulty required for each message can be adapted according to global factors such as traffic and congestion or the size of the content. Customers will choose to connect to relays that offer quality checks and will individually subscribe to identities known for producing quality and genuine content. In the future, Nostr will have one or more trusted networks (Webs of Trust), with which it will be possible to discriminate trusted from untrusted content.
- Usually the "free email" charges ads as is the case with gmail so that the user can create an email. But in the case of nostr, most of the nostr applications are free, there are no paid advertisements. Although there are some proposals in nostr for paid advertisements.
- "Unlimited": In principle any application or social network that uses the nostr protocol network is unlimited, there are no message limits. Although any app or social network with nostr network protocol may or may not add a restriction to the message limit.
- Content moderation and content sharing: The contents are moderated according to the retransmission server by the nostr network protocol, in addition, there are proposals for methods or ways to denounce content that violates copyright, constitutional, civic or human rights.

#### what are the disadvantages of nostr?
- It is an unknown or little known network protocol, there are few solutions available in nostr
- Many email features are not present in nostr. For example not all nostr apps have message filters
- There are few servers, relays to send and receive messages, which is a danger to data protection and security for many users
- Although nostr is an alternative to Twitter, there are still no "official measures" to control content sharing or moderate content. This can be dangerous, as each country, region or state has certain laws, rights, duties, obligations or responsibilities that are different in legal terms
- Although the nostr protocol has a theoretical model for preventing spam with paid content, this is not applicable in most cases
- Deleting a certain content that you wrote wrong is something that is not possible in nostr. For example, let's assume that you wrote a message with some misspelling, as the message was sent, it is not possible to re-edit the message and send the spelling correction, as most nostr clients could have sent the message with the misspelling, which makes it impossible for you to cancel a message already sent
- Privacy, anonymity, security is complicated in the nostr protocol. For example, there are no proposals for tor-like networks, vpn, proxy or firewalls to make the encapsulation of message routes in nostr even more secure, transparent, private and anonymous. It may be that a nostr server registers the number of ips or regions from which you most access
- There are no media types in nostr. This is bad, because when you write messages in emails, you could send .pdf, .txt, etc. files. There are proposals in nostr+ipfs to solve the problem of multimedia files in nostr, but nostr+ipfs is not an official proposal yet
- Not all nostr protocol improvement proposals are accepted. There are proposals for improvement in the nostr protocol that have not yet been accepted
- Things like PGP(Pretty Good Privacy), GPG(Gnu Privacy Guard), OpenPGP are used in email to encrypt the content of messages. However, nostr only has public and private keys, usually the message content in nostr is not encrypted, it will depend on the solution that uses nostr to encrypt the message content or not
- trust: as it is a new network protocol, people may be suspicious of its use

#### what are the advantages of nostr compared to email in delta-chat?
- Even if there are big players, big techs or big companies in general that use the nostr protocol, the nostr is still decentralized. This is an advantage of nostr over email
- you could use the nostr network protocol to synchronize certain messages before sending the e-mail
- you could use the nostr network protocol as a publicly backup message server in case you lose access to your email

#### what are the disadvantages of nostr compared to email in delta-chat?
- Implementing a new network protocol in delta-chat is boring, very technical, difficult and takes some time to develop, plan, create, maintain
- Some nostr developers like bitcoin. But some developers don't like anything related to bitcoin in the delta-chat community, so implementing nostr may lead some developers to leave the delta-chat community, which may compromise the creation, development of certain functionality in delta-chat, which may lead to some delta-chat users leaving the community because it doesn't have more features or differentials that users expect to have
- Perhaps nostr is a different use case for delta-chat, it is a feature that implemented causes more problems in maintenance than it would if it had not been implemented
- Some disadvantages we mentioned related to email like virus and spam can be found in nostr if nostr is very popular as email

#### why not use nostr in delta-chat instead of just email?
- this brings the delta-chat development community closer to the nostr development community, which makes a mutual support between different types of software development community with a general objective that is the internal and external communication of updates of certain resources
- delta-chat could be a "killer-app", a popular app with a new network protocol
- you could use the nostr network protocol as a means to have external storage. Using the nostr network protocol to be an external media is interesting, because in delta-chat there are discussions about using google drive as a backup. The nostr network protocol would be a standardized form of backup, alternative to google drive

#### what alternatives do we have to nostr for synchronizing messages?
 - an alternative to sync messages locally would be to use the localsend protocol

**Comment by Simon-Laux** [comment]
we don't discuss such broad feature proposals on GitHub, for feature proposals we use our forum https://support.delta.chat
closing this here, see you on the forum if you want
