### ISSUE TITLE
Issue with `fr` translation

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#3153]
the test fails with this error:
<img width="1112" alt="Bildschirmfoto 2023-03-30 um 15 52 28" src="https://user-images.githubusercontent.com/18725968/228858685-0ba1a64d-0744-4a53-bd32-7ecafab72e48.png">

reason seems to be the `\\'` in the fr.json locale file:

```json
"ask_delete_chat": {
    "one": "Supprimer %d discussion ? Elle n\\'apparaîtra plus dans la liste des discussions, mais les messages échangés resteront sur le serveur.",
    "many": "Supprimer %d discussions ? Elles n\\'apparaîtront plus dans la liste des discussions, mais les messages qu\\'elles contiennent resteront sur le serveur.",
    "other": "Supprimer %d discussions ? Elles n\\'apparaîtront plus dans la liste des discussions, mais les messages qu\\'elles contiennent resteront sur le serveur."
  },
```

might be because the recent transifex client update. (we switched to the new go version because the old one does not work anymore).

the language still seems usable in deltachat so if this just affects the test then it is low priority

update:
manually removing the double back slashes (\\) makes the test pass, but it's generated so I would prefer to fix the root of the problem instead of the symptoms.

**Comment by Simon-Laux** [comment]
thanks @r10s the plurals hint helped me to find the issue quickly.

**Comment by r10s** [comment]
thanks for taking care, @Simon-Laux :) 👌
