### ISSUE TITLE
add-second-device strings missing

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3178]
the idea of the "Add as Second Device" button in the "Welcome" screen is to let ppl not run into problems when setting up a second device.

while the general functionality is there and working nicely, a hint is missing what ppl should do. currently the screen looks like the following:

<img width=360 src=https://user-images.githubusercontent.com/9800740/231149547-4b15208b-d1f3-4814-a41e-542ca3260857.png>

unless ppl have read instructions somewhere else, they are left completely alone.

as a minimum, we should replace the title and the text below the qr code with `multidevice_receiver_title` resp. `multidevice_open_settings_on_other_device`. ftr, is how android/ios look:

<img width=550 src=https://user-images.githubusercontent.com/9800740/231152194-02fee36d-f643-4cfe-a73e-b84198b8908a.jpg>

related: in the subsequent progress dialog, the title string is missing:

<img width=360 src=https://user-images.githubusercontent.com/9800740/231152964-2fa6afb1-7643-43b1-a2fe-aed90e89c50d.png>

that should be `multidevice_receiver_title` as well.

**Comment by r10s** [comment]
i assume, the milestone is not a prerequisite? i'd change these strings as soon as possible, not a blocker and maybe not the reason for a 1.36.1+, but still should be part of it when it is needed for other reasons

to be cleaer:  no need to change the whole layout, just change the hint would already be a huuuuge ux improvement

**Comment by Simon-Laux** [comment]
the problem is the qr code scanner (which is inside of a dialog), we would need a custom ui there and if we're already doing that then we can do the new scanner as well, it's not that hard.
