### ISSUE TITLE
random scroll position and missing redraws when opening "Archive"

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3208]
- outside the archive, in the normal chatlist scroll some pages down and select a chat
- scroll up in the chatlist and tap "Archive"

-> the archive scrolling position is somewhere some pages down, but not atop (as one would expect eg.  to access just archived chats) 

moreover, when doing this after a fresh app start, the "archive" also not shown, but only some placeholders (they also are not updated after minutes, only after scrolling):

![Screenshot 2023-04-21 at 15 34 10](https://user-images.githubusercontent.com/9800740/233649851-917183a9-037b-4708-9b98-a98e3efe591a.png)

(desktop mac, 1.36.1)

**Comment by Simon-Laux** [comment]
Maybe it could make sense to add some key attribute to force react to rebuild the virtual chatlist when switching between view modes (search, archived, unarchived)?

**Comment by farooqkz** [comment]
Do you think converting `ChatList` to class component and reseting the scroll after component update, if value of `showArchivedChats` has changed, is a good idea?

Or what about having two different components for normal and archived chats?

Note that there aren't actually view modes in `ChatList`, two props, the abovementioned one and `queryStr` are provided to `ChatList` and it determines what ChatItem to show based on value of these two.

**Comment by Simon-Laux** [comment]
This is more probably more complicated, let's see if it still persists after #3268, where I change some things regarding the chat list.

**Comment by r10s** [comment]
> This is more probably more complicated, let's see if it still persists after https://github.com/deltachat/deltachat-desktop/pull/3268, where I change some things regarding the chat list.

to be clear, it happens immediately, just after opening. i would not expect any event at all in case of opening archive.

for me, opening archive looks reproducible like the following:

![Screenshot 2024-03-22 at 09 55 28](https://github.com/deltachat/deltachat-desktop/assets/9800740/47b23c7b-a637-4b5b-bdba-57f4943a162d)

**Comment by Simon-Laux** [comment]
can you try my chatlist event pr?
https://github.com/deltachat/deltachat-desktop/pull/3268

it changes things, so it might already fix this (also needs a core branch, or you just locally remove the event listeners that give type errors and ignore that it isn't updated)

**Comment by r10s** [comment]
indeed, current state of #3268 fixes the issue for me! great! (did not even check out the core PR with the new events)

**Comment by Simon-Laux** [comment]
nice that it works, now I only need to finish the core pr.

> (did not even check out the core branch, it builds just so :)

ah right, frontend code is not type checked when compiling, only "npm run test" does that, so the missing new events don't break the build.
