### ISSUE TITLE
"Add Second Device" doesn't work on Windows because of firewall sometimes

### ISSUE THREAD

**Issue by WofWca** [deltachat/deltachat-desktop#3218]
- Operating System (Linux/Mac/Windows/iOS/Android): Windows 10
- Delta Chat Version: 1.36.1
- Expected behavior: The second device manages to connect to the sending instance of DC
- Actual behavior: Connection times out on the second device
- Steps to reproduce the problem:
  1. Install Delta Chat desktop (if you already have one, you may download the portable version)
  2. Install Delta Chat on another device (say, Android) (if you already have one, you can install an extra [nightly one](https://download.delta.chat/android/nightly/))
  3. On desktop, make sure you're logged in.
  4. On desktop, click "Settings" -> "Add Second Device" -> "Continue"
  5. On the second device, on the log in screen tap "Add as second device" and scan the QR code from the first device.
- Screenshots:
- Logs:

## Debugging

The connection fails, unless you have added DC desktop in "Allow an app through Windows Firewall", or unless it was added there in another way, say through the Windows Firewall alert that can pop up when an app tries to listen on a non-localhost network interface.

The "Add Second Device" feature was added here https://github.com/deltachat/deltachat-core-rust/pull/4007, and it uses `iroh`. The binding address is specified [here](https://github.com/deltachat/deltachat-core-rust/blob/edfdbbdc90e97de92b5f86a74ecddb3be6a8aa9a/src/imex/transfer.rs#L182), down to [here](https://docs.rs/iroh/0.4.1/src/iroh/provider/mod.rs.html#191), but it doesn't trigger the Windows Firewall alert popup, like it usually does with, say, a simple HTTP server app.

I have a suspicion that it may be related to the fact that DC listens for UDP packets, not TCP. [`iroh`](https://docs.rs/iroh/latest/iroh/index.html) uses the QUIC protocol, which is UDP-based. I just tried

```rust
std::net::UdpSocket::bind(("0.0.0.0", 0))?;
```

And it did not trigger the alert, but with a concrete port `("0.0.0.0", 59999)` the alert _is_ triggered. And, again, yes, if you set up an TCP listener, say, with

```rs
std::net::TcpListener::bind(("0.0.0.0", 0))?
```

The alert _does_ get triggered.

## Possible solutions

* A simple hack would be to create another dummy (TCP) interface binding at the same time we create the real (QUIC) one, in order to trigger the Windows Firewall alert and let the user decide whether to allow DC through firewall (see https://github.com/deltachat/deltachat-core-rust/pull/4351)
* @Simon-Laux and @flub pointed me to the `windows-rs` library that DC already depends on, namely these two functions [1](https://github.com/microsoft/windows-rs/blob/a672f5f450b16c947840ab89fdc5ddd16d1fd0d0/crates/libs/windows/src/Windows/Win32/NetworkManagement/WindowsFirewall/impl.rs#L1471), [2](https://github.com/microsoft/windows-rs/blob/a672f5f450b16c947840ab89fdc5ddd16d1fd0d0/crates/libs/windows/src/Windows/Win32/NetworkManagement/WindowsFirewall/impl.rs#L950). But I myself am not sure how they work. I heard they may require elevation ("Run as administrator"). But not only it is a proper solution, I also suspect that it _might_ actually be better because it _might_ (based on my intuition) cause the Firewall alert to pop up a second time if network access was previously denied for the application.

**Comment by WofWca** [comment]
Edited the issue with the info about `UdpSocket::bind()`.

**Comment by WofWca** [comment]
About the `windows-rs` solution.
With the help of https://github.com/microsoft/windows-rs/pull/2466, I have created the following prototype app that adds a firewall rule. It doesn't cause any user prompts, just silently does its thing.

But the problem is that it fails unless you run it as admin.
* Maybe there is a way to make the firewall rule user-specific, so that it doesn't require elevation?
* Or, maybe it can be run when DC is being installed? Though IIRC elevation is only required when you install an app for all Windows users.
* Or maybe there is a way to invoke a user prompt that can allow DC to add the rule.

<details><summary>Code</summary>

```rust
use windows::{
    core::BSTR,
    Win32::{
        Foundation::VARIANT_BOOL,
        NetworkManagement::WindowsFirewall::{
            INetFwPolicy2, INetFwRule, NetFwPolicy2, NetFwRule, NET_FW_ACTION_ALLOW,
        },
        System::Com::{
            CoCreateInstance, CoInitializeEx, CLSCTX_INPROC_SERVER, COINIT_MULTITHREADED,
        },
    },
};

fn main() -> std::io::Result<()> {
    unsafe {
        CoInitializeEx(None, COINIT_MULTITHREADED)?;

        let fw_policy: INetFwPolicy2 = CoCreateInstance(&NetFwPolicy2, None, CLSCTX_INPROC_SERVER)?;

        let rule: INetFwRule = CoCreateInstance(&NetFwRule, None, CLSCTX_INPROC_SERVER)?;
        rule.SetApplicationName(&BSTR::from(
            "C:\\firewall-test\\target\\debug\\firewall-test.exe",
        ))?;
        rule.SetAction(NET_FW_ACTION_ALLOW)?;
        rule.SetEnabled(VARIANT_BOOL::from(true))?;
        rule.SetName(&BSTR::from("firewall-test.exe"))?;

        fw_policy.Rules()?.Add(&rule)?;
    }

    println!("Success!");
    Ok(())
}
```

</details>

**Comment by Simon-Laux** [comment]
can we check if the transfer would be blocked by the firewall? so that we can hint the user at what they need to do to fix it?

**Comment by WofWca** [comment]
That's right.
I couldn't disclose this back when I created this issue haha

**Comment by r10s** [comment]
added a maybe sufficient hint at https://github.com/deltachat/deltachat-pages/pull/799
