### ISSUE TITLE
UI freezes, new messages not shown, unread count not cleared

### ISSUE THREAD

**Issue by marmulak** [deltachat/deltachat-desktop#3221]
- Operating System (Linux/Mac/Windows/iOS/Android): Linux (Fedora 38)
- Delta Chat Version:  1.36.4 (git: flathub)
- Expected behavior: Chats in progress should display new messages as normal; opening a chat and reading unread messages should mark the chat as read in the left pane
- Actual behavior: When I send a message in any chat, the message appears as "sending" but looks like it's never sent, except it is sent but the UI doesn't show that. If I switch to another chat and then back, I will see that the message was already sent, and any subsequent replies will also show. Additionally, if a chat has unread messages shown in the badge on the left pane, opening that chat doesn't clear the badge. Actually it seems that information in the left pane is generally inaccurate, for example a chat with messages in it is shown as having no messages. (See attached screenshots.) Basically UI is not updating properly.
- Steps to reproduce the problem: Install DC 1.36.4 from Flathub, then use it
- Screenshots:

No.1 - Left pane not showing messages
![Screenshot from 2023-04-30 22-08-59](https://user-images.githubusercontent.com/40630991/235366642-ef80bd45-cf4a-4a7f-ad42-ce73aa3cd28a.png)

No.2 - Message not showing as sent (but it's sent; chat pane is not updating)
![Screenshot from 2023-04-30 22-15-03](https://user-images.githubusercontent.com/40630991/235366839-4f7a165b-1b4b-4964-8fc3-0feb7dd787a6.png)

No.3 - Messages not getting marked as read in the left pane
![Screenshot from 2023-04-30 22-18-53](https://user-images.githubusercontent.com/40630991/235367052-3bcb98bd-ead1-4376-8289-ce3aa7ad320b.png)

Note: The third screenshot was taken after deleting ~/.var/app/chat.delta.desktop and loading the app with a fresh config. Account was transferred back onto the device using the "add second device" feature. This is to control for possible corruption in the local config file or other i/o related issues.

**Comment by Simon-Laux** [comment]
https://github.com/flathub/chat.delta.desktop/pull/111
