### ISSUE TITLE
Opening an attachment blocks the renderer

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop#3237]
I have received a PDF in Desktop. When I click it, the attachment is open in my default PDF viewer [Atril](https://github.com/mate-desktop/atril). I can read the PDF, but Desktop becomes unresponsive until I close Atril.

I am running Linux with Xorg.

It seems Desktop is using [`shell.openPath`](https://www.electronjs.org/docs/latest/api/shell#shellopenpathpath):
https://github.com/deltachat/deltachat-desktop/blob/709df3cf9173679fc3d27d44077a961f1e8bf7c5/src/renderer/runtime.ts#L424

There is a closed Electron issue about `shell.openPath` which is said to be resolved in 10.3.0+:
https://github.com/electron/electron/issues/26074
However, we have Electron 22.3.2 in the lockfile and I have Electron 22.3.3 installed system-wide, and the issue is present there.

I am using the command `npx electron --disable-http-cache --devmode .` to start the Desktop.

**Comment by farooqkz** [comment]
I can't reproduce it on:

 - xUbuntu 22.04
 - Xorg
 - Atril
 - `npm run start` from `03464e4e42d8730414624d1`

**Comment by farooqkz** [comment]
@link2xt Regarding this issue, can you please retry clean? Like create another user and test there.
