### ISSUE TITLE
add "send message again" (resend message)

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#3259]
afaik it's currently implemented in android and only for webxdc (for webxdc it resends all state updates together with the xdc).

@adbenitez recently said he missed that functionality in desktop. What's the current state of the feature? I guess the usefulness for helping new members to catch up with normal messages is limited as long as there is no multi selection on desktop.

also resend_message is not implemented in the jsonrpc-api yet.

CC @hpk42 @link2xt @r10s @Hocuri

**Comment by farooqkz** [comment]
IMO, resending own messages in desktop must be implemented too. Sometimes for whatever reason the message does not get sent and the current workaround is copy-delete-send which is inconvenient.
