### ISSUE TITLE
pasting SVG is added as text although already added as attachment

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3261]
when pasting an SVG, it is added to the text area although already added as attachment correctly.

the additional adding as text is unexpected and not needed.

<img width="600" alt="Screenshot 2023-06-09 at 17 39 46" src="https://github.com/deltachat/deltachat-desktop/assets/9800740/f193a722-aa32-48b9-ada1-e7a0f1c419b9">

tested when copying from "SF Symbols" app on macos and pasting to Delta Chat 1.37 using the main menu

**Comment by Simon-Laux** [comment]
"SF Symbols" probably copies sets both a svg file and the text. Are there really no cases where there is normal text plus an image in the clipboard? If we know that there is not we could then say if file and text are both present then always just take the file.

**Comment by r10s** [comment]
> "SF Symbols" probably copies sets both a svg file and the text

might be.

but isn't the clipboard by definition holding only _one_ item in multiple available formats. so, if we find sth matching that is filed as an attachment, we're already done.

**Comment by Simon-Laux** [comment]
> the common clipboard definition is to hold only one item in multiple available formats

let's go with this assumption for now, we can not send multiple files in one attachment yet anyway.
