### ISSUE TITLE
Silent install now opens deltachat  after finishing

### ISSUE THREAD

**Issue by superusercode** [deltachat/deltachat-desktop#3262]
Per https://github.com/microsoft/winget-pkgs/pull/109268#issuecomment-1584951046 where the default nullsoft flags would just install the app silently without launching the program, deltachat now opens itself after install. This prevents updating the package on winget and other package managers where a silent install is expected.

**Comment by Simon-Laux** [comment]
The thing is that we don't directly control how the installer is generated as we use electron-builder which builds the installer for us. 

maybe updating electron builder or setting `runAfterFinish: false` could help: https://www.electron.build/configuration/nsis

**Comment by Simon-Laux** [comment]
`"C:\Users\me\Downloads\DeltaChat Setup 1.40.4.exe" /S` worked for me, could you try again with that version? @superusercode

**Comment by Simon-Laux** [comment]
I'll close this now we can reopen it if there should be any problems with the new version.
