### ISSUE TITLE
View Profile: "Edit Name" is not available when accessing the contact from the members section in a group view

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#3267]
`Edit Name` is not available when accessing the contact from the members section in a group view.
It is confusing to have 2 slightly different versions of the same view, depending on how it was opened.

**Comment by farooqkz** [comment]
Can you elaborate on this please? Like steps to reproduce?

**Comment by Simon-Laux** [comment]
When accessing the profile view directly:
<img width="434" alt="Bildschirmfoto 2023-07-12 um 17 11 29" src="https://github.com/deltachat/deltachat-desktop/assets/18725968/a0627172-f9bd-46f3-9de4-9fae3be13922">
When clicking on a member in a group view:
<img width="434" alt="Bildschirmfoto 2023-07-12 um 17 11 44" src="https://github.com/deltachat/deltachat-desktop/assets/18725968/7d4c8296-fde3-4220-91cf-5e345c1ec4a5">

Note that the pen icon/button to edit the contacts name is missing in that case. I think that is confusing and it should always be accessible.

**Comment by farooqkz** [comment]
From what I understand reading the code, there are actually two different dialogs shown to the user:

 - If the user is in `ViewGroup` and clicks on someone, simply the `viewMode` state of this component is changed to `profile` and a profile using the same component is shown.
 - If the user goes some other way to view the profile, like right-click on DM with someone and then "View Profile", the "ViewProfille" component is shown.

**Comment by Simon-Laux** [comment]
Right that part seems to be outside of `ViewProfileInner`, still we can copy the following over to the other dialog:
- the `onClickEdit` function
- the showEditButton condition (maybe though that condition is unreachable, you can not have a group with the "device chat contact" and you can not click on yourself in the group list, so you might as well always show the edit button)
- if `profileContact` is set then we need to update it when the contact changes (for example when you edit the name, this requires a more involved use effect, so I can do that part if required. (is not really a good first issue anymore unless one is a react expert)

**Comment by farooqkz** [comment]
Why not take the harder but the right way and show the same dialog everywhere?

**Comment by Simon-Laux** [comment]
> Why not take the harder but the right way and show the same dialog everywhere?

We need to think over the whole dialog systems at some point anyway and refactor everything, so I think the duplication is fine for now, I also don't like it, but if we put in the effort we should remove blueprints in that part too while we will be already at it. So better postpone.
