### ISSUE TITLE
Apple requires "notarytool" from Nov 2023

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#3270]
from apple: 

We’re reaching out because you recently used the altool command-line utility to notarize your macOS software with Apple. As announced last year at WWDC22, if you’re still using altool with the Apple notary service, you should transition to the notarytool command-line utility as soon as possible. Notarizing software with altool was deprecated in Xcode 13, and the Apple notary service will no longer accept uploads from altool as of November 1, 2023. Existing notarized software will continue to function properly.

For information on notarizing your apps, read TechNote TN3147: Migrating to the latest notarization tool.

If you have any questions, contact us.

**Comment by Simon-Laux** [comment]
looks like this is required sooner than later

**Comment by Simon-Laux** [comment]
done
