### ISSUE TITLE
Accounts are not always completely deleted on the first attempt

### ISSUE THREAD

**Issue by Raiden-GH** [deltachat/deltachat-desktop#3274]
I’m using DC-Desktop for macOS 13.4 and noticed a small bug that occurs occasionally.
Unfortunately, I can’t always reproduce it.
If you delete an account, it will still be displayed in the list afterwards.
When deleting the next one, either the same thing happens or both accounts disappear.
After restarting DC, they will be displayed as _unconfigured accounts_ and can be deleted.
This problem occurs at least since DC-Desktop 1.36.4.

![Unkonfiguriertes Konto](https://github.com/deltachat/deltachat-desktop/assets/108235546/d6e21006-5a28-49ec-b73c-53009e714ad7)

**Comment by Simon-Laux** [comment]
anything interesting like errors in the log file?

**Comment by farooqkz** [comment]
I have a hypothesis about why this happens:

When you confirm deleting an account, `refreshAccounts` is immediately called(https://github.com/deltachat/deltachat-desktop/blob/master/src/renderer/components/screens/AccountListScreen.tsx#L169) which immediately gets account list from the backend(https://github.com/deltachat/deltachat-desktop/blob/9da44777eb9d61ddb370c718c35d01cb0d6ed477/src/renderer/components/screens/AccountListScreen.tsx#L47) and re-sets the `login` state. For some reason, the backend is still returning the deleted account(s) in the account list.

What do you think?

ping @Simon-Laux @adbenitez @link2xt

**Comment by Simon-Laux** [comment]
@Raiden1982 sent some log files to me, I suspect it is a bug in core.

**Comment by farooqkz** [comment]
Unfortunately, I could not reproduce the bug. But according to the code, and as we have got no logs yet, I can just suspect it's about the backend.

**Comment by Simon-Laux** [comment]
much thanks for testing it again
