### ISSUE TITLE
DeltaChat fails to Display a Headline and an URL/URI (removes underscores). That breask a click on the URL

### ISSUE THREAD

**Issue by winspool** [deltachat/deltachat-desktop#3275]
- Operating System (Linux/Mac/Windows/iOS/Android): X86-64-linux
- Delta Chat Version: 1.36.4 and 1.37.1
- Expected behavior: 
  * An URL, which i send must not be changed, when displayed:
  * An underscore in an URL/URI is never a marker for italic text
- Actual behavior: 
  * The Display of a Headline and an URL in a post is changed in the Desktop App.
  * Receiving in DeltaChat 1.36.5-Android is correct.
  * Sending the same Mail from the Android App is correctly displayed in the Android App,
but the Display in the Desktop App is also broken.
- Steps to reproduce the problem:
- I want to send:
  * the Headline: AM_CONDITIONAL
  * and the URL [ https://www.gnu.org/software/automake/manual/html_node/Usage-of-Conditionals.html ]( https://www.gnu.org/software/automake/manual/html_node/Usage-of-Conditionals.html )
  * DeltaChat Desktop uses the underscore in the Headline and the underscore in the URL as an "Italic text" marker and removes both underscore. That breaks the Headline and the URL.
  * The URL is now broken: ends at "/html" (the location before the underscore) 
  * RAW Message Text: 
```
AM_CONDITIONAL

https://www.gnu.org/software/automake/manual/html_node/Usage-of-Conditionals.html
```
- Screenshots:
  * 3 Messages send with 1.36.4, last message send with 1.37.1
   ![grafik](https://github.com/deltachat/deltachat-desktop/assets/2502762/c1550b76-4183-4ec0-8510-465bf35f1fea)

- Logs:

**Comment by Simon-Laux** [comment]
turn of markdown, it is experimental for a reason, but thanks for reporting anyway.

**Comment by winspool** [comment]
> turn off markdown, it is experimental for a reason, but thanks for reporting anyway.

Thanks, Deactivated. Display is now correct.
Didn't remember, that is was active

> ~Still strange, isn't it the same link in all 4 messages?~ Ah it's from the text above...

* 1: As i needed it -> broken
* 2: Tried with quotation marks -> broken
* 3: Straight link, to remember it -> works
* -: Updated App from 1.36.4 to 1.37.1
* 4: Tried again with 1.37.1 -> broken
* 5: (after the screenshoot): Sending the text from the Android app -> broken

> we should probably just remove `_` from our markdown flavour: [deltachat/message-parser#23](https://github.com/deltachat/message-parser/issues/23)

That's probably the best fix.

Allow an underscore as italic marker only at the start/end of a word or
ignoring an underscore, when the world is "All Uppercase"
would still fail, when sending a test like this: __STDC_VERSION__ >= 202311L

Ignoring an underscore in an URL would at least avoid breaking an URL.

**Comment by Simon-Laux** [comment]
it is tracked and discussed in https://github.com/deltachat/message-parser/issues/23, I closed it here, if you come across this issue please comment over there and disable the experimental markdown feature as a quick fix.
