### ISSUE TITLE
Scanning QR code makes an exception pop up (but things continue to work)

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#3279]
When i use master Desktop and go to qr-code scanning i get an exception but on second attempt it works. 
Not sure it needs to be considered a blocker, also good if someone else could verify this problem on a properly installed ".deb" package or so.  I am using master core/desktop from github. 

![paste-2347861183](https://github.com/deltachat/deltachat-desktop/assets/73579/527d4fab-8ea0-4666-9836-fd171b8400a0)

**Comment by Simon-Laux** [comment]
this was introduced by https://github.com/deltachat/deltachat-desktop/pull/3252, looks like the function in question `systemPreferences.askForMediaAccess` is not defined in non-mac builds.

https://github.com/deltachat/deltachat-desktop/pull/3278 attempts to fix it, if that shouldn't work then we can also remove those platform permission functions again, it already worked before them, so I don't think they actually did anything useful...
