### ISSUE TITLE
sendToChat() dialog can have multiple instances

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#3281]
It should not be able to be opened multiple times on top of each other.

should we just ignore requests to open it when it is already open? or do sth different?

it gets more visible with #3280, but was already a problem before that. (though you needed to have multiple webxdc apps open to trigger it.

**Comment by r10s** [comment]
i'd prefer to abort previous sendToChat() requests. (no need to inform the webxdc, that is more a fire and forget anyway)
