### ISSUE TITLE
“Enter name or e-mail address” bar focus

### ISSUE THREAD

**Issue by tompatulpan** [deltachat/deltachat-desktop#3286]
- Operating System: Kubuntu 22.04
- Delta Chat Version: 1:38 (and previous I think)
- Expected behavior: After "clicking" the plus sign for new address the address bar should be in focus when starting "Enter name or e-mail address"
- Actual behavior: This is only working if I have selected the "Device Messages" and not if I'm reading an old message.

Also see - https://support.delta.chat/t/help-testing-the-upcoming-1-37-x-release/2608/11

**Comment by farooqkz** [comment]
This bug is confirmed.
