### ISSUE TITLE
disable links in quoted messages

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#3290]
if there is a link in a quote-replied message, and you click the quote, it should always jump to the quoted message, not to open the clicked link, links should be disabled there

**Comment by Simon-Laux** [comment]
probably easiest way would be adding `pointer-events: none;` it would not break the rendering of labeled links, links or anything else. maybe also add `user-select: none;` for good measure. but make sure the quote is still clickable, so these css properties need to be applied at the right place.

**Comment by r10s** [comment]
i agree with the initial issue, that a tap on a quote should just jump up (esp. as quotes are shortened, so it is random anyways if a link is shown or not. even links may be shortened, so it is unclear where you go to)

however, _rendering the links as links_ (underlined, colored), but _not having them work as links_, does not sound like a good idea - it easily looks like a bug and breaks expectations - the different pointer is easily overseen as it is no string signal wrt clicking nowadays anyway.

so, better render them as plain text as the other text, no special formatting at all. this is also what android/ios are doing.

i did not reopen the issue as i am not sure what the fix really is, and i also did not text things out how they really look

**Comment by Simon-Laux** [comment]
> so, better render them as plain text as the other text, no special formatting at all. this is also what android/ios are doing.

what about labeled links? I mean we could skip the message parser and just display the plaintext, could maybe give some headache with linebreaks though?

another option would be removing the underline text-decoration via css

**Comment by r10s** [comment]
> what about labeled links? 

just show the label then; if the link is not noticable as such, that's still better (and also a corner case)

**Comment by Simon-Laux** [comment]
> just show the label then; if the link is not noticable as such, that's still better (and also a corner case)

so removing underline via css it is then.

@farooqkz if you want to do it then test also with `#tags` `email@addresses` and `/commands`, those should not have an underline and be not clickable in quotes too, maybe it makes sense to just apply the `pointer-events none` to the whole text if that works?

message parser spec, desktop uses the desktop subset or the markdown subset if markdown is enabled in the experimental settings: https://github.com/deltachat/message-parser/blob/master/spec.md

**Comment by r10s** [comment]
> so removing underline via css it is then.

great! thanks a lot for taking care ❤️
