### ISSUE TITLE
hard to read color in quoted message with sticker reply

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#3291]
if  someone replies a message with a sticker, the author name and vertical bar should have the same color than text, otherwise it is not readable and looks bad

![image](https://github.com/deltachat/deltachat-desktop/assets/24558636/4c357ff2-29c9-4904-903e-62ec58ece057)

I had the impression this issue was solved in the past, maybe it is a regression in the latest version?

**Comment by farooqkz** [comment]
depends on #2998

**Comment by maxphilippov** [comment]
I pushed #4143 as a possible solution. I tried making it a text color but for me on Windows but the name was blending with text. And I personally find color-coding useful to quickly search through the group dialogs. It might confuse something if that's a message not a quote, so I need feedback on this one.

**Comment by Simon-Laux** [comment]
I like the transparency, the current background is consistent with the background for the metadata.
Maybe only change the name to white, but keep the color of the sidebar?
