### ISSUE TITLE
Cannot install or update latest ms store release

### ISSUE THREAD

**Issue by AeliusSaionji** [deltachat/deltachat-desktop#3292]
- Windows - MS Store release
- 1.38.1

Store reports: Error code: 0x80070057

This happens on my 10 desktop, 11 laptop, and for a friend on 10.

Thanks!

**Comment by AeliusSaionji** [comment]
I have a more specific error message

```log
App installation failed with error message:
merlinux.DeltaChat_1.38.1.0_x64__v2ry5hvxhdhyy : error 0x80070057 :
Cannot register the merlinux.DeltaChat_1.38.1.0_x64__v2ry5hvxhdhyy package
because the specified resource language 'az' is not a valid language. (0x80070057)
```

**Comment by Simon-Laux** [comment]
why ever microsoft takes this as a reason not to install the app. Also this all is after they should have reviewed it :thinking:

Anyways I will remove this from the language list, thanks for the more detailed error, I work with that.

**Comment by AeliusSaionji** [comment]
Oddly, it ended up installing on my desktop, but won't install on my laptop. I even tried adding the Az language pack, but that didn't help.

**Comment by zengodgr** [comment]
reporting that there is an issue again, I cant install deltachat in windows 11 with ms store

**Comment by Simon-Laux** [comment]
> reporting that there is an issue again, I cant install deltachat in windows 11 with ms store

could you get more information?

**Comment by zengodgr** [comment]
Sure!
error 0x80070057
windows 11 22H2 22621.2283 Windows Feature Experience Pack 1000.22662.1000.0
ms store 22308.1401.6.0
AMD Ryzen 5 5600G with Radeon Graphics            3.90 GHz
rtx 3060ti

**Comment by hpk42** [comment]
@zengodgr what version of Delta Chat and which download method used?

**Comment by Simon-Laux** [comment]
@AeliusSaionji somehow got a more specific error message from the store, @AeliusSaionji maybe you could share the steps how to get the more detailed error message?

**Comment by WofWca** [comment]
I don't know if it's the way @AeliusSaionji got the log output, but for me it was

1. Open PowerShell
2. `winget install --verbose --logs 9PJTXX7HN3PK`
3. Press "Y" when prompted
3. Open the last log file in the folder that just got opened

**Comment by AeliusSaionji** [comment]
I think I looked in the Event Viewer

**Comment by Simon-Laux** [comment]
I can reproduce it on windows 10 Home 22H2, still need to find some useful error though

**Comment by Simon-Laux** [comment]
I extracted the appx from the ms store using this third party site: https://store.rg-adguard.net/ (putting in the url of our store page: `https://apps.microsoft.com/detail/deltachat/9PJTXX7HN3PK?hl=en-US&gl=US`).
Then I checked the cerificate of the downloaded appx file to make sure it was really signed by microsoft, which it was, so I ran it and now got this more useful error:
```
App installation failed with error message: merlinux.DeltaChat_1.40.4.0_x64__v2ry5hvxhdhyy : error 0x80070057 : Cannot register the merlinux.DeltaChat_1.40.4.0_x64__v2ry5hvxhdhyy package because the specified resource language 'sr' is not a valid language. (0x80070057)
```

We can now test with a local build appx version to make sure only languages are included in the appx file that are actually supported. btw the instructions for locally self-signed appx files are in https://github.com/deltachat/deltachat-desktop/blob/master/docs/APPX_TESTING.md

**Comment by Simon-Laux** [comment]
It is strange because `sr` is listed on the list of supported languages. anyways I will do a pr to remove it.
The self signed apps had the same problem and worked after I removed `sr` from the list of supported languages.

**Comment by AeliusSaionji** [comment]
Ah yes, manually sideloading is where I had gotten that error... Sorry I forgot 🤪

**Comment by Simon-Laux** [comment]
This fix will rollout to users with the next release, maybe already the 1.41 test release that windows store users get a working version sooner already.
