### ISSUE TITLE
race-bug: webxdc status updates get received multiple times

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#3296]
when there are multiple status updates at the same time, sometimes they get send multiple times to the webxdc (also in wrong order?):
<img width="401" alt="Bildschirmfoto 2023-07-01 um 19 13 40" src="https://github.com/deltachat/deltachat-desktop/assets/18725968/1708e624-99f0-4a6d-8860-6e293566ced5">

It is probably that each update causes sending all new update from the update's serial onwards, we should fix this:
- easy: only send the update which serial is in the event
- more efficient / smarter: track what serial was send last and only send them on update if their serial is above the listed serial (also make sure that they have the right order if my suspicion about wrong order should be correct

I found this while using the time tracking webxdc: https://github.com/webxdc/timetracking-webxdc/issues/15

**Comment by ralphtheninja** [comment]
Is `updateListener` function called from an event? If so, it could be the case that it has been registered multiple times.

**Comment by Simon-Laux** [comment]
> Is updateListener function called from an event? If so, it could be the case that it has been registered multiple times.

I also suspected that, but I ruled it out with a log statement. setUpdateListener only supports one listener on desktop and I also think on the mobile implementations. if that is not in the spec we should add it I guess.
