### ISSUE TITLE
appimage in Tails OS does not login using default socks5 settings.

### ISSUE THREAD

**Issue by llamabyte** [deltachat/deltachat-desktop#3298]
- Operating System (Linux/Mac/Windows/iOS/Android):Tails 
- Delta Chat Version: Version 1.38.1 (git: v1.33.0-253-g5ff6e1e3)
- Expected behavior: Connect to email
- Actual behavior: does not connect
- Steps to reproduce the problem: try to login using default with socks5 enabled
- Screenshots:
- Logs:

DeltaChat would not connect trough the tor network with defaults. Would get connection error.

**Comment by llamabyte** [comment]
FIXED

With Socks enabled;

Change default host and port to : 

Host: 127.0.0.1 

Port: 9050

**Comment by Simon-Laux** [comment]
So I guess there is nothing for us to do? please comment or reopen if this is not the case

**Comment by llamabyte** [comment]
I mostly made this for reference and reminder if others ran into the same problem. You could set the default to 127.0.0.1 and port 9050 if you feel it helps to the community.

**Comment by Simon-Laux** [comment]
> You could set the default to 127.0.0.1 and port 9050 if you feel it helps to the community.

not really, most people use DC without tor, I guess most don't even know tor. maybe there could be some auto detection that offers the user to pre-fill the fields with tor, but that is a feature request and we discuss them in tour forum: https://support.delta.chat

I created a forum post, feel free to add more ideas/info over there: https://support.delta.chat/t/auto-detect-tor-and-offer-to-prefill-socks5-settings-with-address-to-tor/2635

**Comment by llamabyte** [comment]
Thanks !
