### ISSUE TITLE
Loading Screens on Key Transfer

### ISSUE THREAD

**Issue by karissa** [deltachat/deltachat-desktop#33]
Right now, generating and verifying a setup message is synchronous, which blocks the user interface. Instead, this should be asynchronous -- this might require the `deltachat-node` library to spawn a thread in C and call a callback once finished, so the UI can render a loading message in the meantime.

- [x] These methods, which are synchronous, should be turned asynchronous: https://github.com/deltachat/deltachat-desktop/blob/master/src/main/deltachat.js#L170-L176
- [x] The frontend calls these functions via the ipc channel here: https://github.com/deltachat/deltachat-desktop/blob/master/src/main/ipc.js#L66-L74

**Comment by karissa** [comment]
https://github.com/deltachat/deltachat-desktop/issues/49#issuecomment-422735100

**Comment by ralphtheninja** [comment]
Fixed in https://github.com/deltachat/deltachat-node/pull/133

**Comment by ralphtheninja** [comment]
Oh sorry, I shouldn't have closed this. The deltachat-node part is done, but not fixed in desktop yet.
