### ISSUE TITLE
Desktop shows alerts when started from the terminal and terminal is closed

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop#3323]
To reproduce, run `npm run start` from `bash`, then press `^Z` to pause, then type `bg` to continue the process in the background, then close the terminal.

Desktop than constantly fails while trying to write the logs to standard output which is now closed:
![1](https://github.com/deltachat/deltachat-desktop/assets/18373967/75ce829d-6e8c-4ac0-a04d-d387c8f7c624)
Closing one message immediately result in opening the next one.

The only way to recover is to use `killall electron` and restarting the desktop.

**Comment by farooqkz** [comment]
Would just checking if `process.stdout.closed` is `true` and not logging be sufficient?
