### ISSUE TITLE
Reminder to update stock strings when using core release with verified 1on1 chats

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#3327]
relevant section in android pr: https://github.com/deltachat/deltachat-android/pull/2560/files#diff-faaf35bfe16342d72a9547e1666b3da5506ac5ad54f23fef815c3141d3b2e29f

iOS issue: https://github.com/deltachat/deltachat-ios/issues/1910

**Comment by Hocuri** [comment]
But don't do this yet without also adapting to verified 1:1 chats in general. The relevant comment in the Android code:

```
    // The next two strings should only be set if the UI actually shows more info when the user clicks on the
    // DC_INFO_PROTECTION_{EN|DIS}ABLED info message
```
