### ISSUE TITLE
Use `Message.file_name` as the proposed filename in Save As dialog rather than the source basename

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop#3330]
Currently the source basename is used as a proposed filename for save as dialog:
https://github.com/deltachat/deltachat-desktop/blob/7b5032a93d824f3391dc6085bed592dcbb4ee534/src/main/ipc.ts#L136

This is usually a mangled filename like `store-890578782.xdc` if the file with this filename was shared more than once, and there is a plan to use completely random filenames or hashes for the blobs stored in the blobdir: https://github.com/deltachat/deltachat-core-rust/issues/4309

If Desktop uses `Message.file_name` instead, a single core change will improve the Save As dialog so right-clicking a media file and selecting `Save As` will always open the dialog with a `store.xdc` proposed name instead.

**Comment by farooqkz** [comment]
> if the file with this filename was shared more than once

Can you please elaborate? Like if I forward the file from a group to another one?
