### ISSUE TITLE
old errors eat up screen space

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3339]
if, for whatever reason, some files are missing in the blob directory, all these error is shown permanently atop of the gallery, with no way for the user to get rid of that - even if the files in question and the corresponding error are several years old.

<img src=https://github.com/deltachat/deltachat-desktop/assets/9800740/7340d1a3-288a-4703-90f0-ea76ab3bff49>

to be clear: the error is real, however the error should not stick forever atop of the gallery; instead, just show them at the place of the image - that way, the user also get some context.

btw. if the list becomes "virtual" (so, load images as needed on scrolling, i think this is planned for the global gallery), this would also be the natural behaviour - as you just do not know that image # 1000 is missing when showing the first tens.

maybe core could also help somehow, however, eg. altering the database in case of partly errors may also be dangerous. and even then, in any case it is better to show the error in place in the UI (as also eg. done on the web).

**Comment by Simon-Laux** [comment]
solved by #3255
