### ISSUE TITLE
Reduce webpack build times on watch

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#334]
Currently webpack rebuilds the whole src folder and does quite some stuff (bundling node_modules and whatever). I think this can be improved and should be improved. Not only to reduce build times but also to allow people with less beefy systems to hack on deltachat-desktop ;)

**Comment by Jikstra** [comment]
Maybe a bit old: https://medium.com/ottofellercom/0-100-in-two-seconds-speed-up-webpack-465de691ed4a

**Comment by karissa** [comment]
webpack also has a `--watch` option if we want to use it but I think our current solution works just fine while we are using tsc for conversations (to watch them separately!)

**Comment by karissa** [comment]
used webpack node externals, it's pretty fast now
