### ISSUE TITLE
Adapt Desktop for breaking JSON-RPC API changes

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop#3341]
There is a breaking change to the API merged into `master` branch of the core: https://github.com/deltachat/deltachat-core-rust/pull/4602

So it would make sense to adapt to this API at some point, but if you do, make sure to create a `stable` branch on desktop repo first that is compatible to the `stable` branch of the core.

**Comment by Simon-Laux** [comment]
https://github.com/deltachat/deltachat-desktop/pull/3359

**Comment by farooqkz** [comment]
Since Simon is doing a PR for this, I've assigned this issue to him.
