### ISSUE TITLE
"Toggle developer tools" menu item in webxdcs exists, but does nothing

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop#3351]
When I open a webxdc, there is always a menu item "View->Toggle Developer Tools". However, it does nothing if "Enable Webxdc Devtools" is disabled. I think it should actually be hidden, it took me a while to understand why it is not working and I have also tried to use global developer tools on .xdc unsuccessfully.

**Comment by Simon-Laux** [comment]
It is inside of this electron standard menu, so we would have to redo it ourselves.
https://github.com/deltachat/deltachat-desktop/blob/7b5032a93d824f3391dc6085bed592dcbb4ee534/src/main/deltachat/webxdc.ts#L257

this macOS only issue is be loosely related: https://github.com/deltachat/deltachat-desktop/issues/3007
