### ISSUE TITLE
fix: New email adresses should be stripped

### ISSUE THREAD

**Issue by Septias** [deltachat/deltachat-desktop#3357]
When adding an email address that has a leading whitespace, nothing happens when clicking on "New Contact". From the console, it can be taken that an invalid email address was given to the core. If this is the case, then an error message should probably be shown. For this issue to close it is enough to just strip the entered email address though.

**Comment by farooqkz** [comment]
Hello @Septias . Which version did you try? AFAIK, it was fixed in the latest version.

**Comment by Simon-Laux** [comment]
still an issue, can reproduce it in 1.40 and in master
