### ISSUE TITLE
v1.40.0 crashes during start on Android 10 / F-Droid / Fairphone 2

### ISSUE THREAD

**Issue by mgprot** [deltachat/deltachat-desktop#3358]
- Operating System: Android 10, Fairphone Open 23.02.0-rel.0 (final update for Fairphone 2)
- Delta Chat Version: v1.40.0
- Expected behavior: should be able to start (like v1.38.2 and most versions prior did)
- Actual behavior: crashes almost instantly
- Steps to reproduce the problem:
  - update / installation attempts (all from F-Droid):
    - updated from v1.38.2, previously in use - crash
    - uninstalled, installed v1.40.0 from scratch - crash
    - uninstalled, install v1.38.2, add as second device, works
      - update to v1.40.0 - crash
- workaround: ignore v1.40.0 update and continue with v1.38.2
- Screenshots:

![01-v1 40 0-suggested-2023-08-19](https://github.com/deltachat/deltachat-desktop/assets/144324/56b58a2a-2bb7-4f21-a6e3-2604b9ad482c)
![02-v1 40 0-insatlled-2023-08-19](https://github.com/deltachat/deltachat-desktop/assets/144324/5bbfecac-bca2-4560-8307-651b5a5c6cab)
![03-v1 40 0-crash-2023-08-19](https://github.com/deltachat/deltachat-desktop/assets/144324/6fbbb35a-e97e-41e8-b83e-89cd426c068f)
![04-v1 38 2-installed-2023-08-19](https://github.com/deltachat/deltachat-desktop/assets/144324/cf11f717-78d8-47fc-ade1-b89485d6e325)
![05-v1 38 2-works-2023-08-19](https://github.com/deltachat/deltachat-desktop/assets/144324/5f94aecd-3531-4e71-9dbd-8d07a42052b9)

Thanks guys & girls - DeltaChat _has been_ working like a charm - great effort! 🙇

**Comment by farooqkz** [comment]
Hello! Did you mean to open this issue in the Android repo? This is for the Desktop version(Linux/macOS/Windows).

**Comment by mgprot** [comment]
doh - not enough coffee
thanks for the heads-up, and yep, it's already been reported in the android repo.
=> closed/duplicate

**Comment by farooqkz** [comment]
I'd say not enough sleep rather ;)
