### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by psmoros** [deltachat/deltachat-desktop#3361]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@pachinko2821) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by Simon-Laux** [comment]
I added a security.md file.
`delta@merlinux.eu` is our current contact address. We may create a dedicated email address for security issues in the future.

I'm looking forward to hearing about your findings.
