### ISSUE TITLE
"float on top" may make show-full-message, webxdc and help virtually unusable

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3365]
if "Float On Top" flag is set for the main window, tapping "Show full message..." or "Start..." for an webxdc may look to the user as if nothing works or happens at all - as the opened full-message-view/webxdc is covered completely by the main window - and eg. on mac, you do not even see the webxdc window by some icon nor is the webxdc reachable by alt-tab. the help window has the issue, maybe others.

fixes may be:
- make the full-message-view/webxdc a "parent" of the main window (not sure what electron offers here, OS supports that, cmp dialogs)
- alternatively, full-message-view/webxdc windows should get the "float on top" as well. i do not think it is needed to have the menu-option for webxdc windows nor it is needed to apply it later on, it is only important that the user sees the window after hitting "start ..."
- consider, if "float on top" is needed at all; i think, this was considered at some point, so this is probably only an option if everything else fails or is too hard
EDIT: even if some system itself allows "float on top" (mac or windows do _not_ allow that by default iirc), this would be less if an issue as the mode is less likely enabled accidentally - and  it is also clear thar this mode is not maintained by us
- ...

EDIT: the issue is true not only for webxdc, i adapted title and text

**Comment by farooqkz** [comment]
I'd say remove the float on top thing if it doesn't have any use. The less code lines the better.

**Comment by Simon-Laux** [comment]
sorry for stealing your issue, finished it before checking assignment after taking with @r10s again in a call
