### ISSUE TITLE
Disable meet.jit.si as a Video Chat instance

### ISSUE THREAD

**Issue by missytake** [deltachat/deltachat-desktop#3366]
As of now, in the experimental video chat settings, we offer 3 default instances for video chats: vc.autistici.org, meet.systemli.org, and meet.jit.si.

Since August 24, meet.jit.si requires authentication for creating rooms: https://jitsi.org/blog/authentication-on-meet-jit-si/

This hurts our workflow of "just setup a call with one click" a lot. I suggest removing them as a default video chat provider.

It would be nice to offer a 3rd default option though. We could offer https://jitsi.random-redirect.de, which redirects to one of 113 jitsi servers: https://github.com/tosterkamp/random-redirect/blob/develop/res/jitsi_servers.lst
I don't know after which criteria it is curated though, e.g. meet.jit.si is still in the list. Still an improvement though.

**Comment by farooqkz** [comment]
From https://jitsi.org/blog/authentication-on-meet-jit-si/

> Starting on August 24th, we will no longer support the anonymous creation of rooms on meet.jit.si, and will require the use of an account (we will be supporting Google, GitHub and Facebook for starters but may modify the list later on).

> 8×8 will now store the account responsible for creating rooms.

These two seem really awful for a privacy oriented app like DeltaChat.

Furthermore, hardcoding list of some instances, is really against decentralization.

> It would be nice to offer a 3rd default option though. We could offer https://jitsi.random-redirect.de/, which redirects to one of 113 jitsi servers: https://github.com/tosterkamp/random-redirect/blob/develop/res/jitsi_servers.lst
I don't know after which criteria it is curated though, e.g. meet.jit.si is still in the list. Still an improvement though.

This I really like. But I wish we could check for these:

 - Availability of each instance with the connection user is using. In many countries, many Jitsi Meet instances are unfortunately blocked.
 - Connection quality of each instance(ping + speed). It might be that the instance is not blocked using some connection but with 1000ms or worse latency, I don't think we want to redirect user to such an instance.
 - If Jitsi Meet API supports this, also check if anonymous meetings are possible on instances of this list.

**Comment by Simon-Laux** [comment]
It is just links and for lazy users we provide some "sane" default options (though only jitsi based for now) from providers that agreed to be listed there after some of us asked them.
https://github.com/cracker0dks/basicwebrtc is also a good option, but there is not really public instance yet, also it has some bugs (does not reconnect automatically).
Essentially you can use all kinds of video chat software that supports joining via a link.

**Comment by Simon-Laux** [comment]
@farooqkz this is currently bugfix stage, sure your idea of ping benchmarking random jitsi instances, like a mirror check to find the fastest mirrors is interesting, but it would belong in the forum and would need to be implemented in core and not on all UI platforms, so interesting idea, but not a good place to discuss/propose it.
This "bug" will be closed and your ideas would be lost, so better to open a dedicated forum feature proposal for it.
