### ISSUE TITLE
Corrupted .desktop file in 1.40.1 .deb

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop#3389]
I have unpacked the .deb file from https://download.delta.chat/desktop/v1.40.1/deltachat-desktop_1.40.1_amd64.deb and it contains the following `.desktop` file:
```
[Desktop Entry]
Name=DeltaChat
Exec=/opt/DeltaChat/deltachat-desktop %U
Terminal=false
Type=Application
Icon=deltachat-desktop
StartupWMClass=DeltaChat
Comment=The Email messenger
With Delta Chat, you can use your existing Email account as a messenger. End-to-End Encryption with Autocrypt is supported and you can have interactive chat experiences using webxdc apps(https://webxdc.org).
Keywords=dc;chat;delta;messaging;messenger;email
MimeType=x-scheme-handler/openpgp4fpr;x-scheme-handler/dcaccount;x-scheme-handler/dclogin;x-scheme-handler/mailto;
Categories=Network;Chat;InstantMessaging;
```

The `Comment` line is broken and results in an error reported at https://support.delta.chat/t/ubuntu-23-10-beta-issue-with-delta-chat/2710

**Comment by Simon-Laux** [comment]
so the line break is the problem?

**Comment by Simon-Laux** [comment]
using  `desktop-file-validate` (from https://freedesktop.org/wiki/Software/desktop-file-utils/), I confirmed that it is the linebreak. it works when it is written out as `\n` though, so maybe we need more escaping. though the easy solution would just be putting it into one line.
