### ISSUE TITLE
some links in full-msg-html-view not working

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3408]
it happens from time to time to me, that some links are not working in the "Show full message..." view - where the same message's links work on iOS (not tested android in this case)

here is an example as an `.eml` file: https://gist.github.com/r10s/19f027782070c1688ece74621332dc73 (the 3D= is the quoted printable, core should clean this up for ui), the rendered, not working links look as follows:

<img width=320 src=https://github.com/deltachat/deltachat-desktop/assets/9800740/379fe7f2-d15c-4c02-937b-9c15b3fabab9>

thunderbird, apple-mail, delta-chat-ios all work. also, you can copy+paste the link from deltachat-deskop - but you cannot open it.

the mail is generated by https://aktion.campact.de/verkehr/49-euro-ticket/teilnehmen , maybe they're doing sth wrong, however i have seen the issue also before in other contexts, so even then, deltachat-desktop should probably be more graceful

**Comment by Simon-Laux** [comment]
what's your desktop version and what is the link?

**Comment by r10s** [comment]
> what's your desktop version and what is the link?

version is 1.40.1/mac and the link is the "Jetzt unterzeichnen und informiert bleiben" from the image above; the destination is `https://aktion.campact.de/verkehr/49-euro-ticket/teilnehmen/v/d9478a66-3c98-4476-9f0b-39bef14d6325?subscribe=1` - the linked .`eml` above shows the whole source

**Comment by Simon-Laux** [comment]
```
<a
 href="https://aktion.campact.de/verkehr/49-euro-ticket/teilnehmen/v/d9478a66-3c98-4476-9f0b-39bef14d6325?subscribe=1"
 style="display:inline-block;background:#C0000D;color:#ffffff;font-family:Open Sans, Helvetica, Arial, sans-serif;font-size:25px;font-weight:800;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:13px 20px 16px;mso-padding-alt:0px;border-radius:0;"
 target="_blank">
 Jetzt unterzeichnen und informiert bleiben
</a>
```

seems like `target="_blank"` is the issue here, because when I remove that the link works. Maybe this requires a new special event listener in electron.
