### ISSUE TITLE
webxdc title not updated in document title changes

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#3412]
if the app is opened and the document title changes, the title bar is not updated, see https://github.com/deltachat/deltachat-android/pull/2664

**Comment by r10s** [comment]
ftr, `DC_EVENT_MSGS_CHANGED` is emitted and [`dc_msg_get_webxdc_info()`](https://c.delta.chat/classdc__msg__t.html#aee526949983962ed25adf33a2f5e6878) returns the correct information

(the issue on android was that it was called on an outdated  dc_msg_t object, this does not work [in general](https://c.delta.chat/classdc__msg__t.html#details). desktop, if course may have other reasons for failure :)
