### ISSUE TITLE
"Save as" dialog appears below app window on KDE

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#3415]
when I select to "save as" a file in DC, the File manager window that appears to select where to save the file, is below the app window so no visible, this is at least happening in my GNU/Linux Kubuntu, r10s can't reproduce in mac

**Comment by Simon-Laux** [comment]
do you have always on top enabled? which version of ode are you using?

**Comment by Simon-Laux** [comment]
FTR: @adbenitez told me that always on top does not affect it this bug. it would be there in both cases: always on top enabled or disabled.

**Comment by Simon-Laux** [comment]
let's reopen when/if it happens again, we got no reports of this recently

**Comment by iequidoo** [comment]
Happens also to me, e.g. if i try to attach a file, the fs browsing window opens below the app window (i.e. it's the second window in the stack) and it's inactive. I have no such problem in other apps, e.g. in Firefox

**Comment by Simon-Laux** [comment]
is this still an issue?

**Comment by iequidoo** [comment]
I've rechecked this and now i have no problems with saving or attaching files.
