### ISSUE TITLE
pref_managekeys_import_explain string is deprecated

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#3423]
we want to remove it, use:
`pref_managekeys_import_explain_path` + "\n\n" + `pref_managekeys_import_explain_tips`

**Comment by adbenitez** [comment]
btw, pref_managekeys_import_explain (now pref_managekeys_import_explain_tips) has some bullet points that should be displayed as a list, but currently in desktop new lines are discarded in this dialog and it looks ugly all in a single paragraph

**Comment by r10s** [comment]
please wait with this issue until https://github.com/deltachat/deltachat-android/pull/2681 is merged

**Comment by adbenitez** [comment]
in the end we decided to do the same as on Desktop so no change is needed
