### ISSUE TITLE
Ask for the name when creating a broadcast list

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-desktop#3440]
Before https://github.com/deltachat/deltachat-core-rust/pull/4644, when creating a broadcast list, the UIs didn't ask for a name since the name wasn't shown to the recipients and therefore not that important.

As of https://github.com/deltachat/deltachat-core-rust/pull/4644, broadcast lists will create their own chat for the recipients, showing the broadcast lists's name, so we need to ask the user for a name when creating a broadcast list.

See https://github.com/deltachat/deltachat-android/pull/2653/files#diff-7c8940eaea1021916d97c310d04af7ebc523920d0bb7e57399e1f7655088d527 for how this is done in Android.

**Comment by farooqkz** [comment]
This needs an upgrade of jsonrpc. right?

**Comment by Hocuri** [comment]
I don't think so - you only need to call the function `set_chat_name()` right after creating the broadcast list.
