### ISSUE TITLE
show verifier name and address

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3451]
only the address is easily confusing or non-telling - only the name may be tricked :)

if possible, use the corresponding core function, contact_get_name_n_addr() this makes sure, all system display things the same way

cmp https://github.com/deltachat/deltachat-android/pull/2770 and https://github.com/deltachat/deltachat-ios/pull/1949

**Comment by Simon-Laux** [comment]
in view profile at verified by
