### ISSUE TITLE
dcaccount qr code does not work on account selection screen

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#3482]
when no account is selected it does not work with an `QR code could not be decoded` alert.

It should ask if you want to create an account there and then create and select a new account/context as it does when you invoke/click/scan it while you are in another account.

To test click on the qr code in the bottom of https://webxdc.org

This is a very niche edge case though.

**Comment by missytake** [comment]
> This is a very niche edge case though.

hm, is this not the normal case of creating a mailadm account after installing the app? :O

**Comment by Simon-Laux** [comment]
> hm, is this not the normal case of creating a mailadm account after installing the app? :O

if you scan with new account then you already have a context created and selected, this bug is only about opening the uri with the system (click on link from browser or with `xdg-open`) while inside of the account selection screen.

**Comment by Simon-Laux** [comment]
the screen in question (account selection screen) does not exist anymore since the introduction of the account sidebar in 1.44.0
