### ISSUE TITLE
Generic helper method for confirmation dialogues

### ISSUE THREAD

**Issue by adzialocha** [deltachat/deltachat-desktop#3485]
Refactor all confirmation dialoges as promises, using a  helper method like this:

```ts
const confirmed =  await confirmationDialog({message: "are you sure", confirmLabel: "Yes"});
if (confirmed){
 // ...
}
```

_Originally posted by @Simon-Laux in https://github.com/deltachat/deltachat-desktop/pull/3469#discussion_r1382039918_

**Comment by Simon-Laux** [comment]
While at it we could also add that for the Alert dialog, but there you don't need to wait for the result as there is none, so that method would not be async.

**Comment by adzialocha** [comment]
I think this can be closed now with the new refactoring
