### ISSUE TITLE
Nixos: Package ‘electron-22.3.27’ is marked as insecure, refusing to evaluate.

### ISSUE THREAD

**Issue by Septias** [deltachat/deltachat-desktop#3497]
On Nixos you can't install Deltachat-Desktop, because we still depend on 22.3.27 which is marked as insecure.

**Comment by Simon-Laux** [comment]
need to wait for the new release, which should come soon, this is solved on master.

**Comment by Septias** [comment]
@dotlambda but how do the responsible people notice that it is outdated? Or will just some random person not related to dc patch us?

**Comment by Septias** [comment]
Btw, Deltachat is _severely_ outdated on nixos with v1.36

**Comment by Simon-Laux** [comment]
@dotlambda and others told us multiple times, we updated it, but it is just not released yet.
Still I wonder why v1.36 with an even older version of electron is not also marked as unsafe?
I'm not deep into how these deprecation on nixOS work, we also harden electron a bit (disallow network connections) so I'm wondering wether the expoits in question do even affect us?
