### ISSUE TITLE
Camera keeps running when trying to scan a QR code "QR-CODE SCANNEN" and abort the scanning

### ISSUE THREAD

**Issue by dev24126** [deltachat/deltachat-desktop#3507]
Camera keeps running when trying to scan a QR code "QR-CODE SCANNEN" and abort the scanning. Camera can switched off with reboot, only.

- Operating System: Windows
- Delta Chat Version: 1.41.1
- Expected behavior: Camera switched off when closing the window (even without scan).
- Actual behavior: Camera keeps on when closing the window (without successful scan)
- Steps to reproduce the problem: open scan window, click to QR-CODE SCANNEN, close the window.
- Screenshots: none
- Logs: none

**Comment by dev24126** [comment]
Seems to be a similar bug #1730.

**Comment by Simon-Laux** [comment]
duplicate of https://github.com/deltachat/deltachat-desktop/issues/1730
