### ISSUE TITLE
common system shortcuts: ⌘W should close secondary windows

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3510]
while Ctrl+Q resp. ⌘Q works as expected and exit the app,

Ctrl+W resp. ⌘W does not close window as expected.

one can argue that the main window should not be closed that way, however, for secondary windows, this shortcut is expected to work, eg. closing the help, a html-message-view or a webxdc-editor window - just all "real" windows that are not the main window

this is a very minor issue, feel free to close it if it gets complicated - but in case it is an easy thing, it'd be good to have it

**Comment by Simon-Laux** [comment]
`⌘Q` on macOS yes, `Ctrl+Q` not on windows at least, while `Ctrl+W` works also on windows.
