### ISSUE TITLE
remove "This chat contains locally generated messages; writing is disabled." - completely hide composer in device chat

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3511]
currently, the device messages shows a bit of a noisy error line that repeats the title and does not answer questions the user has at that moment (eg. after first set up, one does not even know that there is a hidden input field)

just strike the field, it is not needed but distracts from other things and does not look nice. esp. as we aim to show device message chat directly after log in, cmp. https://github.com/deltachat/deltachat-desktop/issues/3499 - having this statement here is a not-so-good first impression

android/ios never had that line and there were never questions or ppl wondering where the input field is and why one cannot write

(iirc, it was never a loved line, but added that time as it was little more work to remove the area completely :)

![Screenshot 2023-11-14 at 13 52 24](https://github.com/deltachat/deltachat-desktop/assets/9800740/aa44c27f-6cec-4ece-b5f3-d54e889e7b91)
_"is it really a chat if i cannot say anything?"_ _"is that good or bad?"_ _"what does one have to do with the other?"_ _"it is disabled - how can i enable?"_ ... joking, of course :) but still: all questions we can avoid easily

**Comment by Simon-Laux** [comment]
Also hide the composer completely (so chat fills whole height)
