### ISSUE TITLE
"Square grid" and "Aspect Ratio Grid" must only be shown if there is a grid

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3523]
these gallery options are hard to get anyways and should only be available if there is a direct, visible effect on changes.

otherwise, the user has no idea what happens - and may later notice that the images are not rendered as usual and has no idea how to switch back - bad ux all in all.

this means, the options should only be available in "Images" and "Video" and must be hidden in "Audio", "Files", "App"

**Comment by Simon-Laux** [comment]
Problem: currently there are no other menu items in the menu, so we would need to remove the menu in these cases (gallery + not video nor image).

**Comment by r10s** [comment]
it is okay to temove the whole kebab menu then
