### ISSUE TITLE
modify group is called even when nothing was modified

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#3533]
https://github.com/deltachat/deltachat-desktop/blob/46a13ff8f0c8ac85ee462e936c9b4105ec223fa4/src/renderer/components/dialogs/ViewGroup.tsx#L117-L119

This effect fires one time initially, while nothing is changed yet. We should change the code to not do that. (react hooks are sometimes hard ;)

Even though core now ignores the core set name https://github.com/deltachat/deltachat-core-rust/issues/5011, it still makes sense to fix this.

**Comment by adzialocha** [comment]
> react hooks are sometimes hard ;)

💯
