### ISSUE TITLE
"reply" function degraded on master

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3540]
eg. for mailing lists, the "reply" function is no longer available since the attempt to fix https://github.com/deltachat/deltachat-desktop/issues/3535 in https://github.com/deltachat/deltachat-desktop/pull/3536

reason is that the menu entry is hidden because of chattype instead of checking [`dc_chat_can_send()`](https://c.delta.chat/classdc__chat__t.html#acb894b6d56253effbc886299add54872) - which is also much better in checking other states as contact-request or guaranteed-e2ee-broken

**Comment by adzialocha** [comment]
Oh! Dammit. So mailing lists are actually writable?

> > [dc_chat_can_send()](https://c.delta.chat/classdc__chat__t.html#acb894b6d56253effbc886299add54872)

Where is this method reflected in the Rust implementation, RPC and / or TypeScript wrappers? I can try a deep dive but maybe faster to ask here. @Simon-Laux @r10s

**Comment by adzialocha** [comment]
> Where is this method reflected in the Rust implementation, RPC and / or TypeScript wrappers? I can try a deep dive but maybe faster to ask here. @Simon-Laux @r10s

Okay, I assume it is `canSend` on the chat objects

**Comment by r10s** [comment]
> Oh! Dammit. 

no worries, you could not have known that, even long-term members are struggling with state of api & co here and there :)

> So mailing lists are actually writable?

yes, most times. but there are situation where this is not possible or not wantend, for whatever reason. in these cases can_send() returns false. so UI should not worry about the "why", which may also change over time by adding features or fixing bugs. UI should just use these information. in general, the whole api is meant to be very high level, and serving the UIs concrete needs
