### ISSUE TITLE
Cleanup the logs

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop#3542]
There are many debug logs like "selectedChat changed the state", "renderer/stores/Store   DEBUG   ""      "refresh"       {"state":{"messageListItems"..." etc. that take multiple lines of the screen, freeze `less` (`vim` does not freeze but still does not make it easy to read lines that take the whole terminal screen) and use disk space. If these logs are not needed, would be nice to get rid of them so it is easier to read actual core logs and more useful debug logs.

**Comment by Simon-Laux** [comment]
> use disk space.

only 10 log files are kept, others are already deleted, debug lines is not logged unless turned on with cli argument.

But sure we can comment out the message list store stuff because we don't really debug it right now anyway
