### ISSUE TITLE
fake Voice message after sending a text message

### ISSUE THREAD

**Issue by sbadux** [deltachat/deltachat-desktop#355]
Hello,
I've updated to v2.0 and I've tried to send a text message to my second email address. For every text message I send, two fake voice message appear below.

![immagine](https://user-images.githubusercontent.com/28478027/48970079-32f32400-f008-11e8-9cdd-6a71927a905a.png)

- Platform (linux/mac/windows): Ubuntu 18.10
- Delta Chat Desktop Version: 2.0
- Expected behavior: see only the text message
- Actual behavior: after each text message, 2 voice message follow
- Steps to reproduce the problem: send a text message

**Comment by r10s** [comment]
i could not reproduce this exact error, however sth. similar that is probably related:

trying to attach a file (tested with *.epub) result in an empty message being sent. the app itself shows instead of the file a voice message as above.

**Comment by Jikstra** [comment]
Thanks for reporting the issue, Is this happening for every chat or only one specific (in case you have multiple chats, if not, try deltabot@codespeak.net)

**Comment by r10s** [comment]
tried a different chat, same result. attaching eg. a *.epub or a *.pdf file results in
- a voice message displayed on the senders device
- an empty message sent (maybe [dc_msg_set_file()](https://c.delta.chat/classdc__msg__t.html#ae3d4b2a4ed4b10dbe13396ff7739160e) is not called or is failing? or dc_send_msg() is called with another message object accidentally? just some ideas :)
