### ISSUE TITLE
uncaught exception when closing full message view

### ISSUE THREAD

**Issue by Louis2747** [deltachat/deltachat-desktop#3568]
- Operating System EndeavourOS(linux) wayland with kde-unstable repo
- Delta Chat Version: Version 1.42.1 (git: v1.33.0-546-g80bf53e9) from chaotic-aur but also happens on regular aur 
- Expected behavior: full message view opens with visible text and closes without error
- Actual behavior: full message view opens with no contents and errors when closing
- Steps to reproduce the problem: clink the show full message button on a message and then close the message window
- Screenshots:
![Screenshot_20231127_124440](https://github.com/deltachat/deltachat-desktop/assets/52701949/b45c75de-c5d1-4078-9e90-da92aa4f9d73)

- Logs:
[2023-11-27-12-45-25.log](https://github.com/deltachat/deltachat-desktop/files/13473753/2023-11-27-12-45-25.log)

**Comment by Simon-Laux** [comment]
Thanks for reporting. It does not appear on macOS nor Windows. What electron version is used and what aur packages did you try specifically?

**Comment by Louis2747** [comment]
well the chaotic-aur one is [deltachat-desktop-git](https://aur.archlinux.org/packages/deltachat-desktop-git) which depends on electron25
i tried [deltachat-desktop](https://aur.archlinux.org/packages/deltachat-desktop) which depends on electron22
and [deltachat-desktop-bin](https://aur.archlinux.org/packages/deltachat-desktop-bin) which depends on electron26, but on that one it looked like this
![Screenshot_20231127_172402](https://github.com/deltachat/deltachat-desktop/assets/52701949/f0e35ada-4a5c-45ca-871c-ffdf9606c833)

**Comment by Louis2747** [comment]
it appears to be fixed
