### ISSUE TITLE
Errors when dismissing notifications on Windows

### ISSUE THREAD

**Issue by Revertron** [deltachat/deltachat-desktop#3593]
- Operating System (Linux/Mac/Windows/iOS/Android): Windows
- Delta Chat Version: 1.42.1
- Expected behavior: Notifications are dismissed silently
- Actual behavior: Big error message
- Steps to reproduce the problem: Someone sends me a message, I read it, then open notification center, click on dismiss all.
- Screenshots:
![image](https://github.com/deltachat/deltachat-desktop/assets/105154/c460e62c-e1e7-44c3-9b20-4f6e90e55421)
- Logs:

**Comment by Simon-Laux** [comment]
"click on dismiss all." - where can I find this option? are you perhaps using a newer version of windows than I do (I tested on windows 10)

**Comment by Revertron** [comment]
> "click on dismiss all." - where can I find this option? are you perhaps using a newer version of windows than I do (I tested on windows 10)

In notification center:
![image](https://github.com/deltachat/deltachat-desktop/assets/105154/e23df7c4-f115-4750-a68f-79fe37494469)
