### ISSUE TITLE
not being able to create members during group creation breaks workflows

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3594]
there is a longer standing issue that you cannot ~~add~~ create members during group creation (as on android or ios).

the the past, this was only a comparable small inconvenience as you could create the group beforehand and create and add members later - so at lease you do not have to throw aways the group.

meanwhile, we create guaranteed-e2ee groups if possible by the initial member list - and that makes it impossible to add email addresses later.

eg. this is a typical workflow for using delta chat to send a comparable "normal looking" mail to somebody, eg. some company's info@company address you did not wrote to before:

1. create a group with group name == subject
2. create and add  info@company 
3. write a message, maybe attach a pdf or so

in the past, that works like that - meanwhile, you  cannot add info@company in step 2. as in step 1. a guaranteed-e2ee groups is created.

theoretical fixes may be to not create guaranteed-e2ee in this case (as already discussed in the past) or to allow setting the subject differently, however, both would be some effort and/or may have other downsides.

pragmatic fix would be to allow adding members during group creation - which is very useful in general, independently of who subject can be set or how guaranteed-e2ee is determined.

**Comment by Simon-Laux** [comment]
do you mean creating contacts while creating a new chat?

**Comment by WofWca** [comment]
I believe it's possible, though you have to type the new contact's address in the search of the "Add Member" dialog, same as with the "New Chat" dialog.
Please verify this is what you want. In this case, it would only be a UX issue.

...Or maybe not only an UX issue, because currently, if you have a contact with the email address, `test@example.com`, you cannot add a member with an email address of `more-test@example.com` or `test@example.co`

**Comment by Simon-Laux** [comment]
isn't this possible meanwhile? @r10s can you confirm it is still an issue on `main` branch?

**Comment by r10s** [comment]
thanks for fixing! i can confirm it works as expected on `main` branch.

> ...Or maybe not only an UX issue, because currently, if you have a contact with the email address, test@example.com, you cannot add a member with an email address of more-test@example.com or test@example.co

i could not reproduce this. please open a separate issue, at best with a video, if this is still  an issue for you. closing this one
