### ISSUE TITLE
Consolidate the Chat List screen and Chat View screen

### ISSUE THREAD

**Issue by karissa** [deltachat/deltachat-desktop#36]
Chat List screen is a preview list of the chats, and Chat View is a view of a single chat. Right now, these are two separate screens. Instead, we could have (like Signal Desktop, or Facebook Messenger) have one screen with the Chat List on the left hand side and the current chat you are viewing in the rest of the window. Example:

![image](https://user-images.githubusercontent.com/633012/45445834-2ce3dd00-b680-11e8-8797-b588c68752c3.png)

**Comment by r10s** [comment]
yes, i think this makes sense.
