### ISSUE TITLE
DC-Desktop displays messages in incorrect order

### ISSUE THREAD

**Issue by raiden-social** [deltachat/deltachat-desktop#3619]
I've noticed that DC-Desktop sometimes displays messages in the wrong order. 
It seems to be based on the time received and not the time sent.
The messages number 3 and 4 are swapped.

### The chat in DC-iOS 1.42.8:

1.) Sent: 2023.12.30 17:26:00 by Ich

2.) Sent: 2023.12.30 17:26:25 by Kontakt 
      Received: 2023.12.30 17:28:22

3.) Sent: 2023.12.30 17:26:28 by Kontakt 
      Received: 2023.12.30 17:28:22

4.) Sent: 2023.12.30 17:26:37 by Ich

5.) Sent: 2023.12.30 17:27:20 by Kontakt 
      Received: 2023.12.30 17:28:22

### The same chat in DC-Desktop 1.42.2:

1.) Sent: 2023.12.30 17:26:00 by Ich

2.) Sent: 2023.12.30 17:26:25 by Kontakt 
      Received: 2023.12.30 17:26:36   (DC-iOS: 17:28:22)

4.) Sent: 2023.12.30 17:26:37 by Ich  

3.) Sent: 2023.12.30 17:26:28 by Kontakt 
      Received: 2023.12.30 17:26:46   (DC-iOS: 17:28:22)

5.) Sent: 2023.12.30 17:27:20 by Kontakt 
      Received: 2023.12.30 17:27:37   (DC-iOS: 17:28:22)

**Comment by Simon-Laux** [comment]
> It seems to be based on the time received and not the time sent.

this is intended behaviour, also if this would be an issue, then it would be a core issue.

the forum has multiple discussions about it:

- https://support.delta.chat/t/order-of-messages/698
- https://support.delta.chat/t/deltachat-almost-unusable-for-me-due-to-out-of-order-message-delivery/2241
- https://support.delta.chat/t/bug-feature-request-making-sure-the-message-are-displied-in-the-correct-order-even-if-some-take-longer-to-arrive/1843
