### ISSUE TITLE
Make setting display name mandatory when creating new account over QR Code Scan (DCACCOUNT scheme)

### ISSUE THREAD

**Issue by adzialocha** [deltachat/deltachat-desktop#3628]
Related Android issue: https://github.com/deltachat/deltachat-android/issues/2913

**Comment by Simon-Laux** [comment]
only when creating a new account over qr code scan (DCACCOUNT scheme), I assume?

**Comment by r10s** [comment]
it is reasonable to also expect a displayname when saving things on later edits

**Comment by r10s** [comment]
also change the used string from `qraccount_success_enter_name` to `set_name_and_avatar_explain` (note that the latter does not require a placeholder)

if a message is needed to remind the user to fill you the name, use `please_enter_name`.
