### ISSUE TITLE
Some dialogs slow in loading async state when opening

### ISSUE THREAD

**Issue by adzialocha** [deltachat/deltachat-desktop#3631]
Some dialogues need to load state before they can render content, which in some cases takes almost a human-noticable delay.

Affected dialogues:

* Show group members (only slow on first load) (invalid HTML `<p>` tag nesting caused React exception in debugging mode, fixed via https://github.com/deltachat/deltachat-desktop/pull/3627)
* Create new group (slow when contact list is large)

We need to find out what's going on and if its nothing we can change a spinner might make sense or some other UI indicating loading.

**Comment by Simon-Laux** [comment]
the real solution would be to not need a spinner using a virtual list for this, there is already an issue for this: https://github.com/deltachat/deltachat-desktop/issues/1830

**Comment by adzialocha** [comment]
Cool, I'll change the title then. Agree that we should look into the root of the problem first.

> the real solution would be to not need a spinner, by using a virtual list for this, there is already an issue for this: #1830

I'm looking at a 800ms loading delay for opening the `ViewGroup` dialog, rendering ca. 30 contacts, not sure if a virtual list is a solution to this problem.

I've tried hooking in the React Debugger into the [Electron Extensions](https://github.com/electron/electron/blob/main/docs/tutorial/devtools-extension.md) to do some profiling, so far I could only use the default Dev Tool profiler. It's clear that the bottleneck sits in the frontend code from looking at it, but without the React Debugger we will not easily find out why.

**Comment by adzialocha** [comment]
Ah, I think I found the issue, at least for the `ViewGroup` dialogue. Probably also this issue only pops up when doing a development build:

There's invalid HTML in `ViewGroup` which causes React to throw an error when opening the component for the first time:

> "react-dom.development.js:67 Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>."

After fixing the invalid element the dialog opens faster ✨

**Comment by adzialocha** [comment]
> After fixing the invalid element the dialog opens faster ✨

Thats btw indirectly fixed by https://github.com/deltachat/deltachat-desktop/pull/3627

**Comment by adzialocha** [comment]
I'm closing this now as the other dialog's issue is discussed in https://github.com/deltachat/deltachat-desktop/issues/1830
