### ISSUE TITLE
Loading contact list is slow

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop#3632]
Contact list is using slow getContacts JSON-RPC call which returns a list of objects rather than calling fast getContactIds and then loading contacts on demand.

This result in 150-200ms delay when clicking on "+" button in the chatlist before any contacts are displayed.

**Comment by Simon-Laux** [comment]
You forgot an `await`:

console.time("foo"); await exp.rpc.getContacts(1, 2, ''); console.timeEnd("foo")

**Comment by Simon-Laux** [comment]
merged comments into #1830 and closing this as duplicate
