### ISSUE TITLE
do not add "Changelog" device message for new accounts

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3637]
the "Changelog" device messages should be added only for real updates

on new installations or accounts, the "What's new?" messages only clutters the device messages with unimportant information (either the user is new to the app, so everyrhing is new and nothing is changed, or an existing user has created a new account, they have seen the changelog anyways)

this is esp. important _new_ as we aim to add information wrt getting in contact for chatmail users, however, it was a bit annoying all the time. 

moreover, this makes untranslated changelogs less annoying as the user is not confronted with a language mix upfront.

when reading https://c.delta.chat/classdc__context__t.html#a1a2aad98bd23c1d21ee42374e241f389 , not added changelog on updates was always the gist, however, somehow forgotten or removed on the way :)

(technically, we cannot use the pattern from the example as the "welcome" message is added by come in some threads, so we need to track if the account was just created somehow, on android we do that by passing a flag around, see https://github.com/deltachat/deltachat-android/pull/2935) (still, `label` needs to be set with `msg=null` to avoid future adding)

**Comment by Simon-Laux** [comment]
note: setting an empty / null pointer device message is not supported by jsonrpc yet
so this required core changes.
