### ISSUE TITLE
Native UX or web UX for the context menu

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#3643]
## Native Behaviour
Most native applications don't let you interact with the app while a context menu is open, you need to click outside to close it and click again to interact with a button for instance.

Examples are most (if not all) apps with a native context menu (apple mail, safari, firefox, libreoffice, usw.); also Element works this way.

Implementing this with a slight or invisible backdrop would also have other benefits, like preventing elements beneath the context menu to get a hover state and other interactions.

## "Web"/Other Behaviour

Some apps (currently including Delta Chat desktop), let the user interact with the outside while the context menu is open.
This is **inconsistent** with most desktop apps and likely comes from the custom implementation of the context menu, as you can not modify the entries of the native context menu in the web, so you need to make your own.

Examples are Signal and Discord;

Some argue there is a benefit of quicker navigation, while others argue against it because of unexpected side effects - if I clock on a picture while having the context menu open it opens the picture in fullscreen, where I might just wanted to close the context menu.

**Comment by Simon-Laux** [comment]
My Opinion: for consistency I'm for the **native behaviour**, also because it would help me with a bug I'm facing in #3621 (the alternative there would be passing functions between react components which is not the prettiest extra code we could avoid)

**Comment by adzialocha** [comment]
+1 for following the native behaviour
