### ISSUE TITLE
Data Tab: file names are not readable

### ISSUE THREAD

**Issue by g6094199** [deltachat/deltachat-desktop#3649]
- Operating System (Linux/Mac/Windows/iOS/Android): Deb 12 - Budgie
- Delta Chat Version: 1.42.2
- Expected behavior: filenames are instantly readable. currently the names overlap.
- Actual behavior: you have to hover over the filenames to read them
- Steps to reproduce the problem: open the data tab and try to read the filenames
- Screenshots:
![Snapshot_2024-01-30_14-23-47](https://github.com/deltachat/deltachat-desktop/assets/37833326/6639bff1-cc55-4aa8-bf8c-463fdabce850)

**Comment by Simon-Laux** [comment]
I guess we could set the min window width to 910px...
Though the "perfect" solution would be responsive/convergent ux design where the chatlist is hidden on small width
