### ISSUE TITLE
When the DeltaChat window is small (1/4 and smaller in 1080p) there is some layout issues

### ISSUE THREAD

**Issue by zenitogr** [deltachat/deltachat-desktop#3656]
- Operating System (Windows):
- Delta Chat Version: Version 1.42.2 (git: v1.33.0-555-g9da03dd2)
- Expected behavior: no layout issue
- Actual behavior: 
 layout issue when window is pinned in 1/4 and smaller of 1080p screen

- Steps to reproduce the problem: pin the window in the corner where its is smaller than 1/4 of 1080p screen -> layout issue as in image below
- Screenshots: 
![image](https://github.com/deltachat/deltachat-desktop/assets/109196423/2a1e1735-cdbf-46bc-8e3e-3365f1a5a3d8)

- Logs: -

edit: change the screenshot to not include personal info

**Comment by Simon-Laux** [comment]
Looks like this is caused by the sidebar, so the removal of it will solve this: #3668

**Comment by Simon-Laux** [comment]
sidebar was removed, will be solved in next release
