### ISSUE TITLE
"Save As" in avatar view not working

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3664]
when enlarging an avatar (group or contact), the context menu offers "Save As", however, on tapping it, no fileselector pops up and nothing happens.

otoh, "Copy Image" works - and "Show In Chat" does _something_, but i think it does not make sense here

![Screenshot 2024-02-07 at 22 52 52](https://github.com/deltachat/deltachat-desktop/assets/9800740/5526d6c4-6afe-4148-b5a5-32c6d10ca59e)

**Comment by Simon-Laux** [comment]
> "Show In Chat" does something, but i think it does not make sense here

The use case for that option is that you look through your photos in fullscreen but then want to jump to the chat at that time.
So I think there is a use case.

**Comment by Simon-Laux** [comment]
can not reproduce on MacOS, can you share the logs and say on which git commit you are?
