### ISSUE TITLE
chat titles are selectable, but selection results in unusual behaviour

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3688]
you can select the text of the chat title (eg. in the intention to copy an email address it to the clipboard), however, if you _release_ the mouse, selection does not finish, but the profile pops up.

by the opened profile, the focus and selection is lost, so the intention to copy anything this way does not work.

in the opened profile, you can then select the name or address and copy it as needed.

for fixing, maybe just make the two text fields as unselectable, pointing to the profile for copying addresses is anyways better as no longer all addresses are shown in the title.

https://github.com/deltachat/deltachat-desktop/assets/9800740/362db3d9-e1a4-4e03-b4aa-c706bf198f2d

(the recording is using a recent master, however, the issue is pretty old)

**Comment by Simon-Laux** [comment]
css: `user-select: none`

**Comment by adzialocha** [comment]
> css: `user-select: none`

This or checking what's going on with the JS event handlers as selecting text of a link is usually possible. Depends what we want to support I guess

**Comment by Simon-Laux** [comment]
I think `user-select: none` is fine, also because on macOS selecting there is not the easiest anymore since we declared the navbar region a drag region replacing the function of the now removed native window title bar
