### ISSUE TITLE
Message delivery notifications refinements

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#369]
notifications needs IMO:

- [ ] show single tick when message was delivered (on EVENT_MSG_DELIVERED) 
- [ ] be graphically similar/same to Android-dev, currently they use signal-style ticks with circles around

**Comment by r10s** [comment]
here are the icons used on android-dev:
https://github.com/deltachat/interface/blob/master/icons/ic_delivery_status_sent.svg
https://github.com/deltachat/interface/blob/master/icons/ic_delivery_status_read.svg

**Comment by ralphtheninja** [comment]
Also see https://github.com/deltachat/deltachat-desktop/issues/386

**Comment by ralphtheninja** [comment]
This is done.
