### ISSUE TITLE
Editting name of a contact does not change their name in the messages

### ISSUE THREAD

**Issue by farooqkz** [deltachat/deltachat-desktop#3703]
1. Rename some of your contacts by opening their profile, edit button.
2. See that their new name does not appear in the messages.
3. Select another chat and select the chat with the contact and see that the new name appears.

**Comment by r10s** [comment]
ftr, the corresponding event is [DC_EVENT_CONTACTS_CHANGED](https://c.delta.chat/group__DC__EVENT.html#ga658b9fc4315badab7afe265b7fa8c2af)

however, in general, for me, at least in the bubbles of groups and in the title bar of one-to-one chats, the change is visible at once. maybe some specific corner cases?
