### ISSUE TITLE
Popup with reaction details only shows one reaction per contact

### ISSUE THREAD

**Issue by lk108** [deltachat/deltachat-desktop#3705]
- Operating System (Linux/Mac/Windows/iOS/Android): Linux (Debian 12.5)
- Delta Chat Version: 1.43.1 (git: v1.33.0-646-g517634b34)
- Expected behavior: All reactions are shown in the popup, even if several reactions are from the same contact
- Actual behavior: Only one reaction per contact is shown
- Steps to reproduce the problem: React with more than one emoji, then click on the reactions.
- Screenshots: All reactions to the message in the screenshot are from the same user, but the popup only shows one of them.
![multi-reactions-example](https://github.com/deltachat/deltachat-desktop/assets/7987989/aa3f045b-baa3-4056-a96f-52c63104797e)

**Comment by r10s** [comment]
where do these reactions come from? 

please note, that all official delta chat clients go the way of "single reaction" after quite some discussion (multiple reactions have their UX drawbacks, are more "pro" in general, make ad-hoc polls and counters harder, and are probably avoided in many other big "mainstream" messengers for these reasons)  
for sure, one can argue the other way as well, and some devs do not like the decision, but from the two "large approaches", "single reaction" was chosen.

maybe, it would have been better to not over design core here and to let core be closer to what UI actually do (as we're doing in other places as well)

that said, it still makes send to display all reactions as long as the api is how it is, but i would also encourage all implementation to not clutter reaction UX across platforms unless there are very good reasons (eg. multiple reactions coming from bots signalling stages may still make sense)

**Comment by lk108** [comment]
The reactions come from the current dev version of DeltaTouch. In a previous discussion, I had the impression that multiple reactions will come to DC at a later point in time. When designing the reactions dialog for DeltaTouch, I did not want to implement single reactions now, just to go back to it and adapt it in some months when the official clients go for multiple reactions.

Also, I wanted to test whether multiple reactions from one user are displayed correctly in DeltaTouch, so I had to generate an example.

But sure, I can restrict DeltaTouch to single reaction if that is the consensus for DC.

**Comment by r10s** [comment]
> But sure, I can restrict DeltaTouch to single reaction if that is the consensus for DC.

that would be easier for now, and avoid tiny little problems and UX questions :)

atm, it is not clear in any way if official Delta Chat will change to "multiple reactions" as sort of natural improvement

**Comment by Simon-Laux** [comment]
> But sure, I can restrict DeltaTouch to single reaction if that is the consensus for DC.

better go for that for now.
we will further discuss this on https://support.delta.chat/t/multiple-reactions-from-one-user-on-one-message/2900, the problem with multiple reactions are the UI questions on how to make the ui to choose multiple reactions.
