### ISSUE TITLE
"Open" instead of "Save" in directory selector

### ISSUE THREAD

**Issue by raiden-social** [deltachat/deltachat-desktop#3709]
When exporting a key, the directory selector displays "_Open_" instead of "_Save_".
Version: 1.43.1
macOS 14.3.1

**Comment by iequidoo** [comment]
Not sure what is meant exactly, but at least i can say that there are "Cancel" and _"Open"_ buttons in the "Export Secret Keys" window.

**Comment by Simon-Laux** [comment]
<img width="515" alt="Bildschirmfoto 2024-03-01 um 17 19 00" src="https://github.com/deltachat/deltachat-desktop/assets/18725968/be3813f1-5cda-4827-ad13-3c8c36b2b35d">

Currently it exports 2 files so "open directory" is correct. we can replace the label of the button, though not sure if that is the perfect solution, but let's do that.

**Comment by Simon-Laux** [comment]
the dialogs purpose is to select a directory

**Comment by iequidoo** [comment]
> the dialogs purpose is to select a directory

Then probably it's better to leave it "Open". Otherwise a user could think that "Save" means "save in the current dir". But maybe a better option would be "Select".

**Comment by farooqkz** [comment]
I was about to comment the same thing as @raiden-social last comment. It should be "Select directory/folder" or something of this line IMO.
