### ISSUE TITLE
Group icon missing

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#372]
In android there's a small group icon, just before the group name, which is missing on desktop, see below:

![android-screenshot1](https://user-images.githubusercontent.com/308049/49225946-981e8f00-f3e5-11e8-9c69-fb687b45ceca.png)

@r10s Mind searching for the correct image resource and adding it here?

**Comment by ralphtheninja** [comment]
Ping @r10s

**Comment by r10s** [comment]
@ralphtheninja icon added to interface repo at https://github.com/deltachat/interface/blob/master/icons/ic_group_white_24dp.png , the icon should be colored in the same color as the text right of it. 

android-dev uses the same icon in the greenish title (currently right, but i would prefer it left of the name in the same way as in the chatlist)
