### ISSUE TITLE
DC-Desktop 1.44 for macOS, Linux and Windows does not start

### ISSUE THREAD

**Issue by raiden-social** [deltachat/deltachat-desktop#3728]
When trying to start DC-Desktop 1.44, two error messages appear.

macOS 14.4 (Apple Silicon)

First error message:

![Fatal Error](https://github.com/deltachat/deltachat-desktop/assets/108235546/cd3c3bc2-5f78-4a3d-a66a-08c44803a679)

After clicking "OK" this error message appears:

![Fatal Error during init](https://github.com/deltachat/deltachat-desktop/assets/108235546/f0b746a3-63a0-4654-b7c2-52bc71c9a8cf)

**Comment by iequidoo** [comment]
On my Debian GNU/Linux 12 it doesn't start also. But i see only the second error

**Comment by dev24126** [comment]
Similar behaviour on Windows with v1.44.0 - 2024-Mar-08 11:06.

**Comment by Simon-Laux** [comment]
the download was not announced yet, this is a problem with deltachat-node on the new build pipeline we set up, we will revert to the old pipeline for now and probably remove this version as broken.
In the future we will replace deltachat-node with stdio jsonrpc bindings, which will be a lot simpler and will not have this problem.

This issue only affects the builds on our downloads.delta.chat site.

**Comment by Simon-Laux** [comment]
the broken files were removed from the download server, I just tagged 1.44.1, which is in the process of being build now.
