### ISSUE TITLE
Deltachat-Desktop only shows a blank window

### ISSUE THREAD

**Issue by allo-** [deltachat/deltachat-desktop#373]
- Platform (linux/mac/windows): Ubuntu Linux (18.10)
- Delta Chat Desktop Version: v2.0.0 and git master
- Expected behavior: Working program
- Actual behavior: The window only shows a white area. The menus which do things outside of this area (e.g. opening the github project or pinning the window) are working.
- Steps to reproduce the problem: Clone the repo, run "npm install" and then run the project either using "npm start" or "node_modules/electron/dist/electron ."
- Logs:
```
(node:12536) Warning: N-API is an experimental feature and could change at any time.
Missing config file: Creating new one
```

**Comment by allo-** [comment]
Output of ``npm run test-integration``

```
TAP version 13
# app runs
ok 1 test dir /tmp/020bec263c5f4ac50580ab6dfcfdf511
not ok 2 Error: waitUntilTextExists Promise was rejected with the following reason: timeout
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      { [Error: waitUntilTextExists Promise was rejected with the following reason: timeout] details: undefined, message: 'waitUntilTextExists Promise was rejected with the following reason: timeout', type: 'WaitUntilTimeoutError' }
    at: <anonymous> (deltachat-desktop/test/integration/setup.js:55:7)
    stack: |-
      Error: Promise was rejected with the following reason: timeout
          at new WaitUntilTimeoutError (deltachat-desktop/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:149:12)
          at deltachat-desktop/node_modules/webdriverio/build/lib/commands/waitUntil.js:36:15
          at <anonymous>
  ...

1..2
# tests 2
# pass  1
# fail  1


```

**Comment by ralphtheninja** [comment]
@allo- Thanks for reporting!

Could you tell us _which_ commit on master you are on?

When starting the app and receiving the white window, please open up "Developer Tools". I bet there's something in the `console` there that can give us more information.

**Comment by ralphtheninja** [comment]
Ps. The failing integration tests is a result of getting the white window, just fyi.

**Comment by ralphtheninja** [comment]
I'm guessing you didn't try the released version? You need to do `npm run build` before doing `npm start` _or_ do `npm run dev`.

**Comment by ralphtheninja** [comment]
I'm going to remove `npm run dev` and just keep `npm start` (which should also build).

**Comment by allo-** [comment]
Wait, I'll test with a fresh clone of current master (c0464c9664901d99c40859ffc6dd9d207d3fbce8)

**Comment by allo-** [comment]
Ah, it seems to work, I probably did not include the build step.
Maybe you can add this to the readme, something like:

> Quickstart:
> Install packages [...]
> run
```
npm install &&
npm build &&
npm run
```

**Comment by ralphtheninja** [comment]
@allo- Nah, I'll just remove `npm run dev`. Lets just keep `npm start`, which should do the build command.

**Comment by ralphtheninja** [comment]
https://github.com/deltachat/deltachat-desktop/commit/e602cbd84f48b6a681feef44c7980e7749de7c4f

This is to remove confusing errors. I've seen two people having this problem already and that's two too many :wink:

**Comment by hpk42** [comment]
thanks @ralptheninja , makes sense to simplify this 
and unconfuse us poor node-js noobs :)
