### ISSUE TITLE
with Multi-account desktop sidebar, black screen on the pinephone

### ISSUE THREAD

**Issue by CHRISHERBET** [deltachat/deltachat-desktop#3734]
- Operating System (Linux/Mac/Windows/iOS/Android):mobian or pmos stable
- Delta Chat Version: 1.44
- Expected behavior:
- Actual behavior:
- Steps to reproduce the problem:
- Screenshots:
![Capture d’écran du 2024-03-12 22-39-14](https://github.com/deltachat/deltachat-desktop/assets/130004484/2ff5485a-2625-46eb-93f9-2398f418e0a9)

- Logs:

**Comment by Simon-Laux** [comment]
from where did you install it? this looks similar to https://github.com/deltachat/deltachat-desktop/issues/3592, maybe some electron + waylaid issue (flatpak now defaults to using waylaid when available?

**Comment by CHRISHERBET** [comment]
I installed it from flatpak on 3 pinephones with mobian (bookworm and trixie) and pmos stable. for all 3, same problem.
It does look like the https://github.com/deltachat/deltachat-desktop/issues/3592 .

**Comment by Simon-Laux** [comment]
you could try `--nosocket=wayland` or `--nosocket=fallback-x11`. Anyways the output of `flatpak run <app.id>` should give us useful information / output.

**Comment by CHRISHERBET** [comment]
with or without the options the attached log is the same:
[2024-03-15-18-06-47.log](https://github.com/deltachat/deltachat-desktop/files/14618844/2024-03-15-18-06-47.log)

**Comment by Simon-Laux** [comment]
try
```
LC_ALL=C flatpak run chat.delta.desktop
```
run it from the terminal app, the log messages we need will not appear in the deltachat log

**Comment by CHRISHERBET** [comment]
the screnn logs : 

[screnn.log](https://github.com/deltachat/deltachat-desktop/files/14627510/screnn.log)

**Comment by Simon-Laux** [comment]
```
[58:0317/141853.628950:ERROR:gl_display.cc(515)] EGL Driver message (Error) eglCreateContext: Requested GLES version (3.0) is greater than max supported (2, 0).
```

this line looks interesting, looks like somewhere the required opengl shader api version was increased and your graphics driver does not support it?
Though that would also mean that it is unrelated to https://github.com/deltachat/deltachat-desktop/issues/3592

**Comment by Simon-Laux** [comment]
Even though we don't support linux mobile phones I invested some time to try it on my linux phones.
- on the Librem5 the flatpak version of deltachat desktop works fine (the only thing that did not is the camera for the qr code scanner, and that the UI is not made for such small screens)
- my pinephone with mobian seems to be stuck in a boot loop, I don't have much motivation to figure out why.

While we (most of the active deltachat team) like linux phones in principle, we don't have enough time and resources to support those platforms at the current point in time 😢.

You currently have the following alternatives:
- use the android version with waydroid (or whatever is the state of the art android emulation layer)
- use [deltatouch](https://codeberg.org/lk108/deltatouch), a qt client original developed for ubuntu touch (with lomori ui framework)
   - it is currently available on ubuntu touch ([open store](https://open-store.io/app/deltatouch.lotharketterer)) and experimentally onmobile nixOS
   - there is an effort to make a Lomori runtime for flatpak (https://justsoup321.codeberg.page/posts/click-clack-flatpak/), this could make a flatpak version of deltatouch possible.
