### ISSUE TITLE
Green dot never disappears

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop#3735]
It seems green dot indicating recent activity of the contact in the chat list never disappears. It only goes away when I switch to another account and back.

**Comment by Simon-Laux** [comment]
#3268 would fix that, but if we want a smaller solution we could check the contact changed listeners in the chatlist and try to fix them

**Comment by Simon-Laux** [comment]
seems like it does also not disappear in the navbar automatically

**Comment by Simon-Laux** [comment]
closed with the core update to `v1.137.3`
