### ISSUE TITLE
Sending a message sometimes becomes slow on chats with many messages / sometimes draft is not removed

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#3738]
Those of you who are with me in some chat groups will have seen that i sometimes sent "double messages". 
This happens because when i hit "CTRL-return" or click the send button in a group chat with many messages, it takes 3-10 seconds until the message is sent, and then i click a second time because i wrongly think i hadn't clicked it.  Sometimes, the draft-message doesn't even go away. 
In chats with only few messages, i do not experience the problem. It's smooth/swift there. 
Sometimes it seems to be even fast in chats with many messages. 

It's all the same database, so my best guess it that something in the sending-logic (changing a draft message to a sent one) might iterate over all messages in a chat.  But whatever the guess, it would be great if someone more knowledgable of the code can take a look into what happens when the send-button is clicked. 

![image](https://github.com/deltachat/deltachat-desktop/assets/73579/2148e51f-7385-434e-96b8-993790186289)

**Comment by Simon-Laux** [comment]
> It's all the same database, so my best guess it that something in the sending-logic (changing a draft message to a sent one) might iterate over all messages in a chat.

if so its core being slow with sending as the code waits for core.

Anyways this code area is in high need of rewriting. see https://github.com/deltachat/deltachat-desktop/milestone/9

**Comment by hpk42** [comment]
On Wed, Mar 27, 2024 at 05:53 -0700, Simon Laux wrote:

> > It's all the same database, so my best guess it that something in the sending-logic (changing a draft message to a sent one) might iterate over all messages in a chat.
> if so its core being slow with sending as the code waits for core.

I find this unlikely as on Android i never have this problem. 
If i had in on both i'd file it directly on core.

**Comment by Simon-Laux** [comment]
so on android you never have delays while sending?
I have a hard time imagining that desktop ui code has delays that depend on message count in the chat as unless you scrolled to load messages only the most recent 20 or so messages are even loaded and displayed in the ui

**Comment by hpk42** [comment]
On Wed, Mar 27, 2024 at 10:04 -0700, Simon Laux wrote:
> so on android you never have delays while sending?

no, i don't have delays there. 

> I have a hard time imagining that desktop ui code has delays that depend on message count in the chat as unless you scrolled to load messages only the most recent 20 or so messages are even loaded and displayed in the ui

maybe it is something else and not the number of messages in a chat
because sometimes it's also fast in large chats
and the app is sometimes slow at other occassions eg
when clicking around in the chatlist which is usually fast
but sometimes takes 5 seconds as if something would be blocking.  
Could it be that core is generating events, 
causing re-rendering and then reacting to user-input is delayed?

**Comment by hpk42** [comment]
currently things are super-fast.   I'll close this issue and try to come back with a clearer way to reproduce as apparently no one else seems to experience the issue.

**Comment by Simon-Laux** [comment]
you already reported the delays before in https://github.com/deltachat/deltachat-desktop/issues/3586

https://github.com/deltachat/deltachat-desktop/pull/3739 might fix the double sending aspect by fixing the lock

To really make this nice we need to rewrite the composer, but we don't have time for that soon (maybe may if we are lucky with the other things). So let's test #3739 to at-least fix the double sending.
