### ISSUE TITLE
Rightclick on chat in chatlist

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#374]
I think it would be a good idea to enable a context menu when right-clicking on a chat in the chat list that has the basic chat options like delete and archive.

**Comment by Jikstra** [comment]
In case we're going to implement something like this, the conversations stuff is using a react-context-menu module which we're already using. It seems to work fine, i guess we can use it for this.

**Comment by Simon-Laux** [comment]
Ok.. this proves to be more difficult than we thought, because several actions (show encryption info, group edit) need the selectedChat object for the chat that the action is ran on. I'll leave that sections out in my pull request until we find a solution that is not too ugly of an workaround.
