### ISSUE TITLE
hide "add second device" instructions when transfer has started

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3742]
when the "add second device" transfer started, the instructions should be hidden; they are no longer helpful but confusing, looking as if there is more to do than to wait for finishing :)

![Screenshot 2024-04-01 at 18 56 34](https://github.com/deltachat/deltachat-desktop/assets/9800740/8800cafc-5bf3-4403-919b-f13ad3a37173)

**Comment by Simon-Laux** [comment]
for the one implementing it: only in transferring step, it should still be shown in the preparation step that is shown before the arcade
