### ISSUE TITLE
adapt to "reaction summaries"

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3744]
- set the stock strings [DC_STR_YOU_REACTED](https://c.delta.chat/group__DC__STR.html#ga546c9fed4e379f8ceb41a73957f4834f) and [DC_STR_REACTED_BY](https://c.delta.chat/group__DC__STR.html#gacb5d6d70133eb05aee7e9fd8425a72d0) to [`reaction_by_you` resp. `reaction_by_other`](https://github.com/deltachat/deltachat-android/pull/2985) (may require core update or using core-main, the strings are already on transifex)

- make sure, the chatlist is updated on [DC_EVENT_REACTIONS_CHANGED](https://c.delta.chat/group__DC__EVENT.html#ga613ad73fa800ebd31b66d357e2192f2a)  
([corresponding android pr](https://github.com/deltachat/deltachat-android/pull/2986))

see https://github.com/deltachat/deltachat-core-rust/pull/5387 for details, screenshot and reasoning.

**Comment by Simon-Laux** [comment]
> the strings are already on transifex
Nice

> make sure, the chatlist is updated on [DC_EVENT_REACTIONS_CHANGED](https://c.delta.chat/group__DC__EVENT.html#ga613ad73fa800ebd31b66d357e2192f2a)
(https://github.com/deltachat/deltachat-android/pull/2986)

If the chatlist events core pr is ready to be merged and contains this, this point will be addressed by https://github.com/deltachat/deltachat-desktop/pull/3268
