### ISSUE TITLE
Reaction selection dialogue closes unexpectedly when a new message comes

### ISSUE THREAD

**Issue by farooqkz** [deltachat/deltachat-desktop#3760]
- Operating System (Linux/Mac/Windows/iOS/Android): Linux
- Delta Chat Version: v1.44.1
- Expected behavior: The reaction selection dialogue shouldn't close
- Actual behavior: It closes, of course
- Steps to reproduce the problem: 1. select a message in a chat to react to and open reaction selection dialogue to find an appropriate reaction and send it. 2. wait for a new message in the same chat to arrive. 3. see that the dialogue closes immediately upon new message arrival wasting whatever search you were making among emojies.
- Screenshots: N/A
- Logs: N/A

**Comment by WofWca** [comment]
Happens on 1.44.0, so it's not because of #3751
Also FYI this isn't happening for the right-click menu, it stays open on new messages
