### ISSUE TITLE
reaction chooser does not vanish after reacting

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#3761]
Expected: the reaction chooser vanishes as soon as I react.

Actual: it stays and is not responding to additional clicks.

**Comment by WofWca** [comment]
Also can't reproduce on 24a5107d

**Comment by Simon-Laux** [comment]
I have this on `master` on 24a5107d440d9f2041d34f60f4bde16a0dba6be8 to be exact
