### ISSUE TITLE
Clicking notification doesn't bring Delta Chat to foreground on Windows

### ISSUE THREAD

**Issue by WofWca** [deltachat/deltachat-desktop#3764]
- Operating System (Linux/Mac/Windows/iOS/Android): Windows
- Delta Chat Version: 1.44.0
- Expected behavior: The main Delta Chat window is brought to foreground (focused?) when a notification is clicked
- Actual behavior: The account and the chat get switched and the icon in the task bar gets highlighted, but the window stays on the foreground
- Steps to reproduce the problem:
    1. Open Delta Chat
    2. Open another window and focus is. _DO NOT_ close the Delta Chat window (to minimize it to tray, because then it works fine)
    3. Wait for a new message to arrive (you can one yourself from a second account)
    4. Click the notification
- Screenshots:
- Logs:

The code is here, I believe

https://github.com/deltachat/deltachat-desktop/blob/631d60354ea06654d98ee976c1436dd4e048124d/src/main/notifications.ts#L63-L68

Related:
- Similar: #3609
- A bunch of workarounds: #2867

**Comment by Simon-Laux** [comment]
https://github.com/deltachat/deltachat-desktop/blob/e2c4ae006beb96e4ab84faeca2b5d8613f3fed16/src/main/notifications.ts#L40-L49

the exact code location

**Comment by WofWca** [comment]
Hmmm weird. Now I can't reproduce it.

**Comment by Simon-Laux** [comment]
I can reproduce it
