### ISSUE TITLE
portable  / Windows Desktop: ADD AS SECOND DEVICE fails

### ISSUE THREAD

**Issue by datenbank-projekt** [deltachat/deltachat-desktop#3765]
Hi,

I am using Delta (on my Android phone, but I am unable to add my desktop as a second device via QR. Simply nothing happens.

- Operating System (Linux/Mac/Windows/iOS/Android): WIndows 10 Pro
- Delta Chat Version:
Delta Chat Desktop	1.44.1 (git: v1.33.0-669-gc878fc787)
Delta Chat Core	v1.136.3
SQLite	3.39.4
electron	28.2.3
node	18.18.2

- Expected behavior: add my account to Desktop tool
- Actual behavior: nothing ... scanning is done, but there is no progress
- Steps to reproduce the problem: open QR on android mobile device, scan via webcam or import qr from file
- Logs: not sure if this contains sensitive data ...

**Comment by Simon-Laux** [comment]
> not sure if this contains sensitive data ...

read it it is a text file, you can remove sensitive information. If you want you could also sent it to the devs privately over delta@merlinux.eu

**Comment by Simon-Laux** [comment]
not enough info to reproduce, I'll close this now, we can reopen it when there is more info. also you could retry with the new delta chat version: 1.46.1

**Comment by nicodh** [comment]
Can not reproduce on WIn 10
