### ISSUE TITLE
failing to use instructions from README

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3783]
for $reasons, i did a new checkout of deltachat-desktop and trying to build the project as described in README.md with ...

```
npm install
```

... which however fails with error `Error: Command failed: npm run install:prebuilds` after some weird compilation errors à la `incompatible function pointer types passing`

[full log](https://gist.github.com/r10s/8d5f7155eb6188dd6c86fd07a10108f2) 

it did work for me before, but that was an ages old checkout, might be i tweaked sth i forgot :)

- rust is installed, and this is also not changed (and seems also be used regarding the log)
- also tried suggestions from the troubleshooting and READMEs linked there - no success
- i finally cleared `Caches/node-gyp` caches and rebooted - no success 
- an `npm install & npm run build` in deltachat-core-rust (following README there) fails in "build" with a similar error
- i checked with `master`, `1.44.1` as well as `adz/instant-onboarding` — all fail

using macos 14.4.1, node 21.7.3

however, i am also only poking around in the dark, migth be it is sth basal i've just overseen or did wrong :)

**Comment by r10s** [comment]
i also tried over with node 18 - similar issue: 

[log](https://gist.github.com/r10s/96f8677f1f852a76c72b68d2c95061e7)

**Comment by Simon-Laux** [comment]
deltachat-node has no arm/m1 build, so it is always built. the linking step somehow fails for you, it looks like a nodejs header problem. For me node `18.18.2` worked.

Anyways might be easier to figure this issue out with a local core, so:
- delete `node_modules` folder
- checkout core repo, run `npm run build` in both repo-root folder and `deltachat-jsonrpc/typescript/`
- run `npm i ../deltachat-core-rust ../deltachat-core-rust/deltachat-jsonrpc/typescript` in desktop repo (path should point to your core checkout)

https://github.com/deltachat/deltachat-desktop/blob/2ac3deb5eb0c801532cf54b43bbbe104e366236d/docs/UPDATE_CORE.md#L47-L55

**Comment by r10s** [comment]
@Simon-Laux , @link2xt , @adbenitez thanks a lot for help! i will try out the suggestions from simon to build core with the PR from link2xt. 

but please do not let that block things and go forward to merge and do whatever is needed :)

**Comment by r10s** [comment]
>  i will try out the suggestions from simon to build core with the PR from link2xt

yeah, that works out. i am in business again :) thanks a lot for help, i would have no chance to build desktop without your help 🙏
