### ISSUE TITLE
message when following an invitelink is misleading

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3790]
when following an invitelink, or when scanning a qr code, the chat shows a hint saying "To join, ask another member" - even though this was just done or one cannot know members as one followed an invitelink

i assume, the idea of the hint is when one left a group. however, with invitelines etc. nowadays it does more harm than help and i suggest to just remove it (similar to https://github.com/deltachat/deltachat-desktop/issues/3511) - it also clutters UI, so refining is not only more work, but also does not necessarily help more

we also add hints as info messages, these are more on-point; ftr android/ios were never showing such hints

![Screenshot 2024-04-24 at 22 53 25](https://github.com/deltachat/deltachat-desktop/assets/9800740/a576ce4e-f879-4970-800d-00c231ab00c9)

**Comment by Simon-Laux** [comment]
I'm against just removing it, it should be possible to detect this state and just hide the bar for this specific state.
