### ISSUE TITLE
Selected image can not be displayed when src is `file://`

### ISSUE THREAD

**Issue by adzialocha** [deltachat/deltachat-desktop#3797]
Selecting an image via `runtime.showOpenFileDialog` and then displaying the file using the selected path leads to the following error:

```
GET file:///<path_to_image>.png net::ERR_BLOCKED_BY_CLIENT
```

This seems to be related to the changes made in https://github.com/deltachat/deltachat-desktop/commit/5dfd93798889414e9a1ca84aa73740838265c1ee 

I assume we have to base64 encode the file contents and display this in the element instead to comply with the new restrictions.

**Comment by WofWca** [comment]
We don't have pass Base64 to core. We could return two things from `runtime.showOpenFileDialog`: the path (for the core) and the Base64 string (or, perhaps `File`), for the UI.
