### ISSUE TITLE
Only rebuild on npm start if something has changed?

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#380]
Can we do the `npm run build` on `npm start` only if a version has changed (for example if we pulled latest changes or node modules changed?) or we didn't build yet? Otherwise you can't start desktop via npm without rebuilding first (which slows down app start incredibly).

**Comment by ralphtheninja** [comment]
We should only do this if we can reliably do it. The reason for putting the build command there is to avoid getting reports "Oh I'm getting a white screen". Most people will (and should) download the built app where this step isn't needed. If you're using the app from source it's not that big of a deal to wait a few secs to rebuild the js stuff. In my opinion at least :)

**Comment by karissa** [comment]
I usually just use `npm run dev` along with `npm run watch`, not `npm start`. Did we take away `npm run dev`? 

I agree with @Jikstra , usually `npm start` doesn't include the build step (people should read the readme)

**Comment by Jikstra** [comment]
> How can you tell if you need to rebuild or not?

Wouldn't do something fancy, just a simple check if our build folders exist or not. 

What was the intention to put all dev related stuff also in npm start?

**Comment by hpk42** [comment]
On Thu, Dec 06, 2018 at 04:20 -0800, Jikstra wrote:

> > How can you tell if you need to rebuild or not?
> 
> Wouldn't do something fancy, just a simple check if our build folders exist or not. 
> 
> What was the intention to put all dev related stuff also in npm start?

dumb users like me and others who each independently got confused because 
they are not at home with npm but prefer to run the latest master ;) 
then magnus (IMO rightfully) thought it's better to prevent this noob-problem. 
developers can probably learn to run "npm run WHATEVER" to deal
with everyday/editable/watching hacking sessions ... 
whatever is chosen i think the README needs to reflect it ;)

**Comment by ralphtheninja** [comment]
> I agree with @Jikstra , usually `npm start` doesn't include the build step (people should read the readme)

I really don't care. I just wanted to get rid of the n00b issues. We can put back `npm run dev` etc.

**Comment by ralphtheninja** [comment]
I'll revert this back to how it used to work and update README with clear instructions.

**Comment by ralphtheninja** [comment]
https://github.com/deltachat/deltachat-desktop/commit/041e4b902ce675375a78b9d66dd8bc0f4d664621

**Comment by karissa** [comment]
thanks @ralphtheninja !
