### ISSUE TITLE
Removing member from group does not refresh member-list 

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#3807]
Removing member from group does not refresh member-list. 

going to chat and then to member list shows the member removed. 

platform: sk/ephemeral branches on cvore and desktop which i believe are rebased on master and should not influence this screen so it's basically main.

**Comment by farooqkz** [comment]
Can you please post accurate steps to reproduce this? Unfortunately, I even don't know which member list you are talking about...

**Comment by hpk42** [comment]
On Tue, May 14, 2024 at 07:19 -0700, Farooq Karimi Zadeh wrote:
> Can you please post accurate steps to reproduce this? Unfortunately, I even don't know which member list you are talking about...

1. Create a group chat with two members 
2. Tap group chat member list 
3. Remove one chat member 

expected: chat member is removed from the list

actually: chat member is still shown in the list despite 3.

**Comment by hpk42** [comment]
I think this was due to the iroh-debug branch that swallowed events. Closing.

**Comment by Simon-Laux** [comment]
Nico can reproduce this, I also ran into this recently

**Comment by nicodh** [comment]
It happens in the add member dialog. After adding a new member the list in the dialog stays the same, although the new member was added. When cloding the dialog the number of group members was updated as expected

![Before-adding-new-member](https://github.com/deltachat/deltachat-desktop/assets/1428457/34ae4e90-2537-40d5-ac21-cb1c574d764a)

Same for removing a member.
