### ISSUE TITLE
Chat messages should start above message input in chats with less messages

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#381]
![screenshot_20181205_023346](https://user-images.githubusercontent.com/34889164/49484219-83ebef00-f836-11e8-922f-0160d3ff2145.png)

**Comment by nicodh** [comment]
Can you explain why the message should be at the bottom? For me it looks totally fine as it is now...

**Comment by Jikstra** [comment]
The message list should give you the impression that new messages get appended directly above the composer.
