### ISSUE TITLE
Incorrect playing time for AAC files

### ISSUE THREAD

**Issue by Raiden-GH** [deltachat/deltachat-desktop#3814]
The displayed playing time of an AAC file is often too short. Towards the end of the displayed duration, it suddenly increases by the second until the real playing time is reached.

DC-Desktop 1.44.1
macOS 14.4.1

**Comment by Simon-Laux** [comment]
the component is the normal html5 audio player of chromium, so I suppose it is also a bug in chromium

**Comment by r10s** [comment]
AAC seems to have problems times with correct playing times in general

on android, there was a similar issue, also not actionable https://github.com/deltachat/deltachat-android/issues/2260 and closed with "won't fix" as related to upstream.

and in the iOS issue https://github.com/deltachat/deltachat-ios/issues/1923 it was reported that producing podcast with AAC some bitrates causes troubles (this is not directly related to Delta Chat, but we adapted the bitrate to the ones making fewer problems :)

**Comment by Simon-Laux** [comment]
So nothing we can do about it here.
