### ISSUE TITLE
Opening new Chat dialog does not focus input field

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#3815]
originally reported on https://support.delta.chat/t/help-testing-the-upcoming-1-37-x-release/2608/13

It is reproducible on the current `master` branch.

**Comment by farooqkz** [comment]
Didn't I once solve a problem like this? Anyway, assigned to myself.

**Comment by farooqkz** [comment]
another bug: The create group thing does not focus either. Let's consider it as part of this issue.
