### ISSUE TITLE
Clicking on the reactions button when the reactions bar shown makes the reactions bar hide and show again

### ISSUE THREAD

**Issue by farooqkz** [deltachat/deltachat-desktop#3818]
- Operating System (Linux/Mac/Windows/iOS/Android): Debian sid
- Delta Chat Version: 1.44.1
- Expected behavior: Nothing should happen when the reactions bar is shown
- Actual behavior: The reactions bar hides and shows again
- Steps to reproduce the problem:

1. Open the reactions bar by clicking on the reactions button.
2. Click on it again without closing the reactions bar.
3. You'll see reactions bar hides and shows again
- Screenshots: N/A
- Logs: N/A

**Comment by farooqkz** [comment]
After spending few hours on it, could not solve it. I might try harder in near future but unassigning myself for now in the case someone else wanted to take over.

**Comment by nicodh** [comment]
I don't consider this a bug. I think there is no obvious expected behaviour. Some may expect that nothing happens when it's already opened, others may expect that it closes, but this is not a real error...

"After spending few hours on it" - I would suggest: close this with "won't fix"

**Comment by farooqkz** [comment]
@Simon-Laux @WofWca Thoughts?

**Comment by WofWca** [comment]
I think it's too minute to care about + the current behavior is arguably the best out of the ones that were mentioned, same way as clicking on a chat in a chat list repeatedly wouldn't do anything.

**Comment by Simon-Laux** [comment]
slight backdrop (click to exit like on dialogs) could "fix" that.
Personally I would still like to have the reaction bar integrated into the context menu (open with context menu like in telegram).

**Comment by farooqkz** [comment]
Okay. closing it as won't fix.
