### ISSUE TITLE
Add support for Viewtype::Vcard

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#3829]
https://github.com/deltachat/deltachat-core-rust/pull/5536 introduces a new viewtype `Vcard` (`Viewtype::Vcard` in JsonRPC, `DC_MSG_VCARD` in the C FFI). In order to show it, call the JsonRPC function `parse_vcard(filePath)` where `filePath` is the path to the message's attachment.

`parse_vcard()` will return a JSON struct with fields `addr`, `display_name`, `profile_image`, and `color` (which you can use to create a placeholder image in case there is no profile_image). You can ignore the other returned fields. Note that `parse_vcard()` returns a list of contacts; simply ignore all except for the first contact.

Android implements viewing Vcards here: https://github.com/deltachat/deltachat-android/pull/3043

Can be done now (depends on https://github.com/deltachat/deltachat-core-rust/pull/5536):

- [x] display vcard messages in-chat
- [x] display in quotes/replies
- [ ] display in draft/staging
- [x] When a vCard is clicked, ask for confirmation and then call `import_vcard()` (depends on https://github.com/deltachat/deltachat-core-rust/pull/5582/)

These TODO-items should be postponed:
- [ ] ~~set new core stock string "Contact"~~ (looks like we won't keep this stock string)

Preview from Android:
![image](https://github.com/deltachat/deltachat-desktop/assets/24558636/48a5e91c-3e75-4d92-b55a-ddd21905be39)

**Comment by nicodh** [comment]
@adbenitez what is meant with: set new core stock string "Contact" (used in summary)?

**Comment by iequidoo** [comment]
> @adbenitez what is meant with: set new core stock string "Contact" (used in summary)?

Maybe we're going to remove this stock string at all as the contact name should be displayed instead of "Contact". And if a vCard can't be parsed, the message viewtype is changed to `File` anyway, so the file name is displayed instead.
