### ISSUE TITLE
Update UPDATE_CORE documentation

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop#3835]
It is now outdated and still talks about `deltachat-node` package which is replaced by deltachat-rpc-server:
https://github.com/deltachat/deltachat-desktop/blob/3fc3557f9de0a2f493c4dd775c3e1018222187d9/docs/UPDATE_CORE.md

At the same time it mentions `DELTA_CHAT_RPC_SERVER` environment variable.

**Comment by Simon-Laux** [comment]
closed by #3832

reopen if you disagree
