### ISSUE TITLE
Visual bug in search result list

### ISSUE THREAD

**Issue by farooqkz** [deltachat/deltachat-desktop#3848]
- Operating System (Linux/Mac/Windows/iOS/Android): Linux
- Delta Chat Version: 1.44.x
- Expected behavior: "Messages" title should not be above or under search results
- Actual behavior: It is, of course
- Steps to reproduce the problem: Search something. Then see like that in screenshot
- Screenshots: 
![a](https://github.com/deltachat/deltachat-desktop/assets/15038218/c62dcd36-8db4-4a8b-8118-109f33112b1c)

- Logs:

**Comment by Simon-Laux** [comment]
which core and what branch are you using?

**Comment by farooqkz** [comment]
alright this I can't reproduce on stable.
