### ISSUE TITLE
Map doesn't open

### ISSUE THREAD

**Issue by missytake** [deltachat/deltachat-desktop#3858]
- Operating System (Linux/Mac/Windows/iOS/Android): xubuntu 22.04
- Delta Chat Version: 1.45.0, installed via .deb
- Expected behavior: when I click on the map icon on the top right of the selected chat window, the map opens.
- Actual behavior: nothing happens.
- Steps to reproduce the problem:
  - open desktop
  - click on the map icon
- Logs:
```
Error occurred in handler for 'open-maps-webxdc': {
  code: -1,
  message: 'failed to open file /opt/DeltaChat/resources/app.asar/html-dist/xdcs/maps.xdc\n' +
    '\n' +
    'Caused by:\n' +
    '    Not a directory (os error 20)'
}
```

**Comment by missytake** [comment]
If I start deltachat-desktop with `npm run start`, it works.

**Comment by missytake** [comment]
The path doesn't work:

```
$ file /opt/DeltaChat/resources/app.asar
/opt/DeltaChat/resources/app.asar: data
```

There is `/opt/DeltaChat/resources/app.asar.unpacked/`, but it just contains:

```
.
└── node_modules
    └── @deltachat
        └── stdio-rpc-server-linux-x64
            ├── deltachat-rpc-server
            └── package.json

3 directories, 2 files
```

**Comment by r10s** [comment]
just another data point: on mac/sonoma with arm-build (thanks for that, btw!), the map shows up

**Comment by missytake** [comment]
> When I click on the gallery icon it is always highlighted along with the map icon.
> 
> ![DC Karten](https://private-user-images.githubusercontent.com/108235546/333790680-ba36e937-4ecd-4081-800a-423d2ed45789.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MzM0MTksIm5iZiI6MTcxNjYzMzExOSwicGF0aCI6Ii8xMDgyMzU1NDYvMzMzNzkwNjgwLWJhMzZlOTM3LTRlY2QtNDA4MS04MDBhLTQyM2QyZWQ0NTc4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxMDMxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzQ1MzdkMTdhYzc1NDgyZjQ4Y2E3NjllZTY5N2ZhNzJjZGJjYmJmNWYxMTUwZjQwYzNiMGY3NWE2ZGZjOWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mvKJjlWcCFZj21hMou0LVC11UWyMz9svyDqrUKgJsvU)

Same for me.

**Comment by Simon-Laux** [comment]
probably we need to instruct electron-builder to also put it into the asap.unpacked folder and probably additionally adjust the code so it finds it when it is a release, similar to what I did for the rpc server in 

https://github.com/deltachat/deltachat-desktop/blob/513bf80d7c6fa35459301da7b4ecf31edb4976c9/src/main/deltachat/controller.ts#L88-L91

**Comment by r10s** [comment]
> just another data point: on mac/sonoma with arm-build (thanks for that, btw!), the map shows up

i meanwhile have the same bug again, not sure what has changed. at least, the bug is consistent now :)
