### ISSUE TITLE
Formatting issues in Russian for scan QR code

### ISSUE THREAD

**Issue by kermoshina** [deltachat/deltachat-desktop#3864]
- Operating System: linux
- Delta Chat Version: 1.45
- Actual behavior: Problems with text formatting in Russian, when scanning the QR code. Text is too long and doesnt fit in the frame.
- Solution: replace with a shorter string, e.g. "Отсканируйте чтобы начать чат с %username%"
![deltachat-2024-05-26-114543](https://github.com/deltachat/deltachat-desktop/assets/16879492/88fae778-735d-4068-b7b1-37120892a133)

**Comment by Simon-Laux** [comment]
As far as I understood it, this is already solved on transifex.
