### ISSUE TITLE
A bug with date of audio messages in Russian

### ISSUE THREAD

**Issue by kermoshina** [deltachat/deltachat-desktop#3866]
- Operating System: Linux
- Delta Chat Version: 1.45
- Actual behavior: Month and day not properly appearing for audiofiles
![deltachat-2024-05-26-114950 (1)](https://github.com/deltachat/deltachat-desktop/assets/16879492/40ff75e8-4f05-4ca1-9703-e9c81cb595bd)

**Comment by r10s** [comment]
i think, the key `timestamp_format_m_desktop` is very questionable at all.

translators do not really know what to do with it, i just did a grep, it is seems also wrong in at least one other language. - ukranian has "MMMM" (may this exists, idk), khmer is ែ ថ្ងៃ, which seems wrong.

afaik, we're using some js-date-formatting thing anyways (i cannot really remember for what :) - maybe we can just rely on that?

**Comment by WofWca** [comment]
In the mean time I changed the Russian translation.

**Comment by r10s** [comment]
>  khmer is ែ ថ្ងៃ, which seems wrong

i fixed that to `MMM D`

> ukranian has "MMMM" (may this exists, idk)

`MMMM D` is okay according to https://momentjscom.readthedocs.io/en/latest/moment/04-displaying/01-format/ , not sure if it is the gist, however.

so, all translations should be fine for now, however, allowing translations for that strings has still the potential to break things without us noticing, as it will happen only in some language.

so, it would be good if we can get rid of the string or do some plausibility runtime check and default to `MMM D` if that fails

**Comment by Simon-Laux** [comment]
This is should be solved now by the translations update and https://github.com/deltachat/deltachat-desktop/pull/3889 would remove the usage of the translations string entirely.
