### ISSUE TITLE
Plural rules are not followed for many languages

### ISSUE THREAD

**Issue by WofWca** [deltachat/deltachat-desktop#3870]
- Operating System (Linux/Mac/Windows/iOS/Android):
- Delta Chat Version: 1.44
- Expected behavior: "2 hours" is pluralized as "2 часов"
- Actual behavior: "2 hours" is pluralized as "2 часов"
- Steps to reproduce the problem: Set language to "Russian" and look at a message that was sent 2 hours ago.
- Screenshots:
    ![image](https://github.com/deltachat/deltachat-desktop/assets/39462442/92320387-37e0-46a7-afd6-099786e9f82a)
- Logs: None

I noticed that in many places the plural rule used is in the form of `count === 1 ? 'one' : 'other'`. A few (hehe) examples:

- https://github.com/deltachat/deltachat-desktop/blob/035cfd0f38467ac7c3df6058df742e617e8280a1/src/renderer/components/conversations/formatRelativeTime.ts#L48
- https://github.com/deltachat/deltachat-desktop/blob/5dad3478b8fa7b336ffaa4f2a8141370b1ef4481/src/renderer/components/dialogs/CreateChat/index.tsx#L353
- https://github.com/deltachat/deltachat-desktop/blob/b342a1d47b505e68caaec71f79c381c3f304405a/src/shared/localize.ts#L49-L51

This might be true for German, English and many other languages, but it is not for as many other languages, such as Arabic and Russian. E.g. in Russian 1 is 'one' and 2 is 'few'. You can check the rules for all (or almost all?) languages [here](https://www.unicode.org/cldr/charts/43/supplemental/language_plural_rules.html)

The solution I believe is to use [Intl Browser API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules):

```js
const arCardinalRules = new Intl.PluralRules("ar-EG");
console.log(arCardinalRules.select(0)); // "zero"
console.log(arCardinalRules.select(1)); // "one"
console.log(arCardinalRules.select(2)); // "two"
console.log(arCardinalRules.select(6)); // "few"
console.log(arCardinalRules.select(18)); // "many"
```

I wanted to make an MR, but I wasn't sure which exact places need to be adjusted.

FYI I checked a few (heh) places in DC Android and strings seem to be pluralized alright there.

**Comment by Simon-Laux** [comment]
Yeah would make sense to replace momentjs by luton or dayjs, which use the newer browser apis. This would also make the app slightly smaller.

**Comment by WofWca** [comment]
It's not just about `moment` though. E.g. here

https://github.com/deltachat/deltachat-desktop/blob/e7fc9e2b3930f1ab8fbf525d0895ca9ac8989ee6/src/renderer/components/dialogs/ViewGroup.tsx#L239-L248

**Comment by Simon-Laux** [comment]
I think it would be the best to fix this issue by using a newer date library and to make a new issue for the other cases, I don't know a fix for those yet, maybe we need to update our translation function or introduce a new one for counts, or use some translation library instead of our own thing, but let's treat that in a dedicated issue.
