### ISSUE TITLE
Chinese shows `N_MINUTES:ONE` instead of age of message

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3886]
from the forum, https://support.delta.chat/t/help-testing-the-upcoming-v1-45-x-release/3089/7

one can easily reproduce that with any of the chinese translations, the wrong text is shown at least if the message is between one and two minutes old.

<img width="468" alt="Screenshot 2024-05-31 at 12 16 30" src="https://github.com/deltachat/deltachat-desktop/assets/9800740/b355c54a-61cb-423b-bcdf-39daac86e89e">

**Comment by WofWca** [comment]
Fixed by dce0e236263db91bed239de63e94621cb13e3921
