### ISSUE TITLE
no error shown when the app cannot be opened

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3902]
downloaded1.45.2 and 1.45.3 ARM builds from https://support.delta.chat/t/help-testing-the-upcoming-v1-45-x-release/3089/13 - on mac os 14.4.1 the main window does not open.

the app is not really crashed, however, menu and about work somehow (see video)

this is reproducible and does not work all the time. when downgrading to 1.45.0, things work again

https://github.com/deltachat/deltachat-desktop/assets/9800740/c82612ad-9447-4d17-bba7-8f1a811a4323

**Comment by Simon-Laux** [comment]
Which version version of MacOS, which cpu architecture? and what's the output when starting it from the terminal?

```
/Applications/DeltaChat.app/Contents/MacOS/DeltaChat --devmode --log-to-console
```

**Comment by r10s** [comment]
this is the output:
```
 ~ % /Applications/DeltaChat.app/Contents/MacOS/DeltaChat --devmode --log-to-console
(node:31923) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `DeltaChat --trace-warnings ...` to show where the warning was created)
Logfile: /Users/bpetersen/Library/Application Support/DeltaChat/logs/2024-06-05-15-16-57.log
0s [i]main/index: Deltachat Version 1.45.3 v1.33.0-849-g76b9e255 1717540776700
0.1s [i]main/index: cwd /Users/bpetersen/Library/Application Support/DeltaChat/accounts
0.1s [i]main/deltachat: using deltachat-rpc-server at {
  serverPath: '/Applications/DeltaChat.app/Contents/Resources/app.asar.unpacked/node_modules/@deltachat/stdio-rpc-server-darwin-arm64/deltachat-rpc-server'
}
0.1s [i]main/deltachat: HI
0.1s [i]main/deltachat: Ready, starting accounts io...
0.1s [i]main/deltachat: Started accounts io.
stderr: 2024-06-05T13:16:57.093699Z ERROR deltachat_rpc_server: Fatal error: failed to load accounts: failed to run migrations: execute_migration failed for version 114: index reactions_index1 already exists: Error code 1: SQL error or missing database.
child process exited with code 1
child process close all stdio with code 1
34.9s [w]main/index: window not set, this is normal on startup 
App.<anonymous> (file:///Applications/DeltaChat.app/Contents/Resources/app.asar/src/main/index.ts:262:9),
App.emit (node:events:518:28)
```
it is about and already existing `reactions_index`, tbh, not sure if that is only me or also a general issue. does someone else  cannot start as well?

**Comment by Simon-Laux** [comment]
I can start it just fine, it is a core error. But the desktop issue here is that the error is not shown to the user.
So let's keep the issue here and make a new one for the core migration issue.

**Comment by r10s** [comment]
yeah, i probably checked the pr or created the index during filing the original issue

**Comment by r10s** [comment]
did a `DROP INDEX reactions_index1` and things work again. the issue was very probably only on my system.

and very nice to get a better error with #3904
