### ISSUE TITLE
handle subsequent taps on profile icon

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3907]
when tapping the profile icon of the already selected profile (so, not the first tap to switch the profile), the profile should go back to sort of "default state", which is partly done also when switching to another profile:

- ~~go out of profile (already done on profile switching)~~
- end search (already done on profile switching)
- ~~scroll up(already done on profile switching)~~

~~this makes sure, the user "sees" the unread chats when they notice the profile's badge counter.~~

and, it makes taps on the profle switcher predictable, the user learns to always end up in a known, standard view.

the selected ~~account~~ chat, however, should not be changed - if that means eg. that the archive needs to stay open, then it's that.

but if the archive is entered with no selection, subsequent taps should land in the default view.

cmp. https://github.com/deltachat/deltachat-ios/issues/2125 , https://github.com/deltachat/deltachat-ios/issues/2171 , comparable apps

this is a minor one, no urgency at all :)

**Comment by Simon-Laux** [comment]
> scroll up(already done one account switching)

where? if you mean the chatlist, then I disagree, it should scroll to the selected chat, not up.

**Comment by Simon-Laux** [comment]
> the selected account, however, should not be changed - if that means eg. that the archive needs to stay open, then it's that.

do you mean the selected chat? account makes little sense to me here...

**Comment by r10s** [comment]
> > scroll up(already done one account switching)

> where? if you mean the chatlist, then I disagree, it should scroll to the selected chat, not up.

this is the current behaviour, right? 

so, yes, let's keep that as is. maybe also keep archive as is. 

i opened that issue mainly because of the not-ended-search, so maybe concentrate on that for now, that is mostly unquestionable.

we can then see how things feel in practise and if more is missing. i modified the original post accordingly
