### ISSUE TITLE
small screen layout: going to the chatlist unselects the chat

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop#3909]
Currently the following steps unselect the chat:
1. Reduce the window size.
2. Click "back" button to go from chat view to chatlist view.
3. Increase the window size back.
4. See "Select a chat or create a new chat" bubble instead of the chat.

Client should not unselect the chat, but remember separately which "screen" (chatlist or chat) is open in the small screen layout.

Also note that messages should not be immediately marked as read if we are in small screen layout and looking at the chatlist, but some chat is open in the background with new messages.

**Comment by Simon-Laux** [comment]
I disagree, if you go back you unselect the chat.
Not only do I think it is unexpected the keeping the chat open in the background is also harder to implement and prone to produce more bugs and errors.
