### ISSUE TITLE
Forward Message: Search shows many placeholders

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#3921]
it should load all visible items everytime the chat ids change.

<img width="567" alt="Bildschirmfoto 2024-06-08 um 00 28 54" src="https://github.com/deltachat/deltachat-desktop/assets/18725968/4baab9db-4537-4a34-9439-e99deed60fbb">

**Comment by farooqkz** [comment]
You mean the white gaps?

**Comment by Simon-Laux** [comment]
the skeleton items to be exact, they are shown if the chat in question is not loaded to the cache of the chatlist.
when you scroll the infinite loader (this component is responsible for only loading chats that are shown on the screen) is updated and loads the missing visible chats.

my fix forces the infinite loader to refresh (load all missing visible chats) when the count of items in the chatlist changes, which happens when you search.
