### ISSUE TITLE
message details window bugs

### ISSUE THREAD

**Issue by Raiden-GH** [deltachat/deltachat-desktop#3926]
If the message details window contains enough information to display the side scroll bar, the clickable area of ​​the x-icon is reduced and moved down. This means that a user can no longer close the window by clicking in the middle of the x-icon.

DC-Desktop 1.45.5
macOS 14.5

**Comment by Simon-Laux** [comment]
do you mean the navbar drag area makes clicking it impossible? that I can reproduce

**Comment by r10s** [comment]
the close button in the "message info" dialog was even more buggy on releases, eg. the "X" is not tappable at all for me, when the dialog is larger than main window:

![Screenshot 2024-10-15 at 18 43 55](https://github.com/user-attachments/assets/9d6fc875-55ec-4598-a99b-3dc81dc0a196)

(1.46.8 on macOS)

on current master, however,  i could not reproduce that any longer. instead, there is another bug, showing the text stacked:

![Screenshot 2024-10-15 at 18 54 38](https://github.com/user-attachments/assets/d626a96b-e835-4a27-b259-73d69f6ed89b)
