### ISSUE TITLE
wrong aspect ratio for images shown in quotes

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3931]
when quoting a message with an image, the quote gets enriched with the original image, which is great!

however, the quoted image is always force to be a square, without respecting the aspect ratio:

<img width=300 src=https://github.com/deltachat/deltachat-desktop/assets/9800740/faf1ec30-7376-46d6-ba60-6d34ce7d5aa7> &nbsp; <img width=411 src=https://github.com/deltachat/deltachat-desktop/assets/9800740/881c1e71-9b21-4062-9296-5b563b27f05e>

instead, either:

1. display the whole image - however, the height should still not be larger than the quote. the image can be wider, however. displaying the whole image is also what desktop does otherwise, maybe one can reuse some code

2. crop the image. this is done on mobile, as anyways already done for the normal image display (due to smaller screen and for $reasons). in case of desktop, however, i would show the image as its original, so go for 1.

all in all, this is a minor issue with low priority

**Comment by Simon-Laux** [comment]
probably could be solved by only setting height
