### ISSUE TITLE
Apple Store package not starting on MacOS Silicon; DMG works fine

### ISSUE THREAD

**Issue by andrewgdotcom** [deltachat/deltachat-desktop#3938]
- Operating System (Linux/Mac/Windows/iOS/Android): MacOS 13.6 on Apple Silicon
- Delta Chat Version: 1.44.1 App Store
- Expected behavior: Should start
- Actual behavior: Icon bounces for a few moments in the dock and then stops.
- Steps to reproduce the problem: Run the app
- Screenshots: None, nothing appears
- Logs: None that I can find...

Downloading the DMG and installing the old-fashioned way works without problems.

**Comment by Simon-Laux** [comment]
please try again with 1.46.0, should already be in the appstore: 
<img width="992" alt="Bildschirmfoto 2024-06-15 um 16 16 13" src="https://github.com/deltachat/deltachat-desktop/assets/18725968/f71cddb7-00d6-4043-b972-c28bb4530ce2">

**Comment by Simon-Laux** [comment]
reopen / notify us if this issue if it still happens on the current/new 1.46 version.

**Comment by andrewgdotcom** [comment]
It's even worse with 1.46, it fails immediately rather than after 20s. Again nothing particularly informative in the logs:

```
default 16:27:19.315249+0100 storekitagent [Client] (DeltaChat) Initialized with server Production bundle ID chat.delta.desktop.electron and request bundle ID chat.delta.desktop.electron]
default 16:27:19.327752+0100 storekitagent [Client] (DeltaChat) Initialized with server Production bundle ID chat.delta.desktop.electron and request bundle ID chat.delta.desktop.electron]
default 16:27:19.328353+0100 DeltaChat sf changed: <private>
default 16:27:19.331094+0100 DeltaChat Entering exit handler.
default 16:27:19.331118+0100 DeltaChat Queueing exit procedure onto XPC queue. Any further messages sent will be discarded. activeSendTransactions=0
default 16:27:19.331162+0100 DeltaChat Cancelling XPC connection. Any further reply handler invocations will not retry messages
default 16:27:19.331182+0100 DeltaChat Exiting exit handler.
default 16:27:19.331197+0100 DeltaChat XPC connection invalidated (daemon unloaded/disabled)
error 16:27:19.331207+0100 DeltaChat No error handler for XPC error: <private>
default 16:27:19.389427+0100 storekitagent [Client] (DeltaChat) Initialized with server Production bundle ID chat.delta.desktop.electron and request bundle ID chat.delta.desktop.electron]
default 16:27:19.391736+0100 storekitagent StoreKitServiceListener: Connection to DeltaChat invalidated
default 16:27:19.409693+0100 loginwindow -[PersistentAppsSupport applicationQuit:] | for app:DeltaChat, _appTrackingState = 2
default 16:27:19.409729+0100 loginwindow -[PersistentAppsSupport applicationQuit:] | App: DeltaChat, quit, updating active tracking timer
```

**Comment by Simon-Laux** [comment]
> It's even worse with 1.46, it fails immediately rather than after 20s

failing fast is way better than taking 20s to fail.

**Comment by Simon-Laux** [comment]
> Would be interesting to know if sth useful comes up if you start it from the terminal

**Comment by andrewgdotcom** [comment]
```
[46167:0617/091904.726617:ERROR:process_singleton_posix.cc(1170)] Failed to bind() /var/folders/3z/tztp1x4d1h50t062180j3qd40000gn/T/chat.delta.desktop.electron/S/SingletonSocket: Operation not permitted (1)
Only one instance allowed. Quitting.
```

**Comment by Simon-Laux** [comment]
seems to be https://github.com/electron/electron/issues/35540

solutions might be:
A. ignore single instance stuff on macOS entirely (might result in other bugs)
B. make our own implementation for a single instance lock (atleast on macOS)
C. remove com.apple.security.app-sandbox entitlement

**Comment by Simon-Laux** [comment]
For the record, it works fine on macOS Sonoma 14.3.1, just tested the version from appstore. So this only appears on some versions.

**Comment by Simon-Laux** [comment]
> C. remove com.apple.security.app-sandbox entitlement

> To distribute a macOS app through the Mac App Store, you must enable the App Sandbox capability.
> ~ https://developer.apple.com/documentation/security/app_sandbox

So option C is not possible

**Comment by Simon-Laux** [comment]
@andrewgdotcom can you try to verify that it's a sandbox issue with these steps? https://developer.apple.com/documentation/security/app_sandbox/discovering_and_diagnosing_app_sandbox_violations#4116292

**Comment by andrewgdotcom** [comment]
@Simon-Laux no results 🤷

**Comment by andrewgdotcom** [comment]
Neither subsystem:com.apple.sandbox.reporting nor category:violation produce any results, even by themselves

**Comment by Simon-Laux** [comment]
> On macOS, the system enforces single instance automatically when users try to open a second instance of your app in Finder, and the open-file and open-url events will be emitted for that. However when users start your app in command line, the system's single instance mechanism will be bypassed, and you have to use this method to ensure single instance.
> ~ electron docs https://www.electronjs.org/docs/latest/api/app#apprequestsingleinstancelockadditionaldata

so I guess we can just skip that single instance lock on macOS appstore builds, it will probably fail on the account manager lockfile in core then, but only if users try to open it via the commandline
