### ISSUE TITLE
Nicely view vCards in staging/draft

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-desktop#3940]
Right now (in 1.46.0), when attaching a vCard to a message, this looks like this:
![image](https://github.com/deltachat/deltachat-desktop/assets/18012815/fdbb098e-3d32-48d0-a2cb-6db2cfc2b157)

I think that this can lead to user confusion, so it would be nice to improve this to show the avatar, name, and email address (just as it looks in messages).

Alternatively, we could simply immediately send out the message without setting it as a draft first. This way, there would be no need to show it as a draft.

See with https://github.com/deltachat/deltachat-desktop/pull/3906; ping @nicodh @Simon-Laux

**Comment by Simon-Laux** [comment]
Sure could be nice, should also be possible before composer refactoring.
