### ISSUE TITLE
How to launch app without development mode

### ISSUE THREAD

**Issue by d47081** [deltachat/deltachat-desktop#3952]
After build from sources using this instruction
https://github.com/deltachat/deltachat-desktop?tab=readme-ov-file#from-source-

application start in development mode with additional debug window. 

how to make production build with npm? some argument like `--release` maybe missed?
thanks

**Comment by Simon-Laux** [comment]
```
npx electron .
```

For packaging into sth. you can install there are different commands for different platforms installer formats.
look inside of package.json to find all possible commands for `npm run`
