### ISSUE TITLE
Use GH Actions to send notifications about new issues and PRs to a DC group

### ISSUE THREAD

**Issue by farooqkz** [deltachat/deltachat-desktop#3967]
I think the title perfectly tell you what I've got in mind. Let me know your comments. Ping @Simon-Laux @WofWca @maxphilippov

**Comment by WofWca** [comment]
I don't mind, But for me personally, GitHub notifications are enough.

I think I saw this implemented in some DeltaChat group already for the DeltaChat forum.

Also check out Webhooks instead of GH actions

**Comment by Simon-Laux** [comment]
could be interesting to have some chat with a feed for this (maybe there is some RSS feed that we could use via an RSS bot?) but nothing for the main group, rather in an extra chat, if at all. I wouldn't use it, GitHub notifications and looking at repos manually from time to time is enough for me. email notifications were too much for me as I was too busy with checking email notifications all the time in the past.
