### ISSUE TITLE
vcard staging polishing needed

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3968]
thanks for making vcard nicer at https://github.com/deltachat/deltachat-desktop/pull/3948

there are some minors that did not make it to the PR review:

- staged vcards show the "pointing finger cursor", which does not make sense as nothing happens when tapping the vcard

- there is no padding left of the vcard's avatar, which looks bad. i'd add same padding as above the vcard's avatar

![Screenshot 2024-06-20 at 15 21 01](https://github.com/deltachat/deltachat-desktop/assets/9800740/f2746bc4-2499-4953-8a86-27959112c617)

EDIT: same is true for staged files (the missing padding does not look so bad in case of files, the cursor is wrong as well), so, in case both share the same code, that can be fixed together

**Comment by Simon-Laux** [comment]
even with those suggestions it does not look good, would be better to give it a slight background, margin, padding and rounded corners IMO

**Comment by r10s** [comment]
surely one can improve beyond fixing the most obvious design bugs.

the two points are the minimum to not consider the design buggy - the result fits somehow to the other stagings then
