### ISSUE TITLE
"Contact info" card layout continuously jumps for contact names of certain length

### ISSUE THREAD

**Issue by WofWca** [deltachat/deltachat-desktop#3971]
- Operating System (Linux/Mac/Windows/iOS/Android): Windows
- Delta Chat Version: 1.46.1
- Expected behavior: Layout stays static
- Actual behavior: Layout continuously shifting
- Steps to reproduce the problem:
    1. Create a contact e.g. with this name "aaaaaaa@example.com" so that it just wraps in the "Contact info" card
    2. Open the "Contact info" card
- Screenshots:

    https://github.com/deltachat/deltachat-desktop/assets/39462442/67b4ac8b-77a9-4ddf-8815-9f472bf3eea2
- Logs:

I suspect this is related to the `<AutoSizer>` component.

**Comment by maxphilippov** [comment]
Can't reproduce this on current master @WofWca

**Comment by WofWca** [comment]
Maybe try a different name with different length, different combinations of letters.

Otherwise, I'll try myself again.
