### ISSUE TITLE
mailto: handler asks to type a contact recipient, but never finds a match

### ISSUE THREAD

**Issue by AeliusSaionji** [deltachat/deltachat-desktop#3972]
- Operating System: Windows
- Delta Chat Version: 1.46.1 (git: v1.33.0-881-g899f196d) (winstore install)
- Expected behavior: Popup appears with recent chats, filter by typing
- Actual behavior: Popup is empty, typing into filter does not suggest matches or otherwise allow user to proceed, even when typing literal addresses
- Steps to reproduce the problem: I've been using firefox's "email image" context menu. 
![image](https://github.com/deltachat/deltachat-desktop/assets/4342746/2e95bb86-00b3-4ce7-829f-d167aeee908a)

**Comment by Simon-Laux** [comment]
I can reproduce this
