### ISSUE TITLE
More recent versions than 1.44.1 package `app-32.7z` instead of `app-64.7z`

### ISSUE THREAD

**Issue by simonsan** [deltachat/deltachat-desktop#3973]
DeltaChat 1.44.1 still packaged `app-64.7z`, from 1.45.0 on it packages `app-32.7z`. Was that renamed on purpose?

- Operating System (Linux/Mac/Windows/iOS/Android): Windows 11
- Delta Chat Version: 1.44.1 - most recent
- Expected behavior: package `app-64.7z`
- Actual behavior: packages `app-32.7z`
- Steps to reproduce the problem: Download `DeltaChat.$version.exe` and unpack.
- Screenshots: ![2024-06-24 11_40_39-0 INBOX](https://github.com/deltachat/deltachat-desktop/assets/14062932/854cf07f-22ca-49cf-a501-f800383a97b4)
- Logs: None

**Comment by Simon-Laux** [comment]
> Was that renamed on purpose?

No, maybe sth done by electron builder update or the new build script. This needs further investigation

**Comment by aliesbelik** [comment]
Any updates?
Doesn't seem to fluctuation in separate build (reproducible since 1.44.1), so I wonder whether we should fix scoop manifest to enable further updates (https://github.com/ScoopInstaller/Extras/issues/13461).

**Comment by Simon-Laux** [comment]
> Any updates?

no, haven't found the time to look into this yet. I think it makes sense to fix the scoop manifest.

I guess it is because we now also build 32bit, maybe this now means that all release are now 32bit.
I think the solution to that might be to have two variants, one 32bit and one 64bit.
