### ISSUE TITLE
show "Mark All As Read" unconditionally

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3979]
the sidebar introduced a new function "Mark All As Read", which, however, is unexpectedly not available when a _single chat is muted_  - but esp. then you want this function as one cares less about a chat anyways :)

same for muted archived chats, which also should count into "All" 

the reason for the issue be that jsonrpc-pendents of [`dc_get_fresh_msg_cnt()`](https://c.delta.chat/classdc__context__t.html#a6d47f15d87049f2afa60e059f705c1c5)/[`dc_get_fresh_msgs()`](https://c.delta.chat/classdc__context__t.html#a5dc16d0ebe4f837efb42b957948b54b0) are used to show/hide the option and to mark chats as read - however, already by its name "fresh" is not "all" :)

~~if these information are not easily available in the UI, we should consider adding dedicated core functions as   `dc_has_unnoticed_chats()` and `dc_marknoticed_all_chats()` (due to multiple meanings, we avoid the the term "read" in the api, [cmp](https://c.delta.chat/classdc__msg__t.html#a83fbf6e74d09a0b598ccefe9b48bd68c))~~

EDIT: idea is to just show the item unconditionally, above "Settings", see discussion below

<img width=320 src=https://github.com/deltachat/deltachat-desktop/assets/9800740/40daa9d6-ee08-4025-8f11-c8dfcdb580fb>

_no "Mark All As Read" here although there are unread chats_

**Comment by Simon-Laux** [comment]
made a core issue for that https://github.com/deltachat/deltachat-core-rust/issues/5825

**Comment by r10s** [comment]
i am wondering, if we shouldn't just show the menu item _unconditionally_ 

- on android, we also have that option unconditionally since some time, no one wonders so far

- it is pretty hidden anyways and available in he context menu only, so nothing that would clutter primary UI

- having that shown/hidden at the top is anyway bad, as that way, eg. "All Media" is always at a different position (surely, it can go elsewhere or being disabled, but that would be one thing less to worry about)

- showing that unconditionally would also provide a way around marking all things as read even if there are bugs in counting or thelike 

- less API to care for

this would fix the issue at hand, and if ppl really get confused (i doubt, the wording is not even wrong), we can iterate

**Comment by Simon-Laux** [comment]
ideally I'd say always show, but as somehow disabled when you can't click it.

But we can still add that later.
Also to add no new methods, we could integrate a count for all chats in `getFreshMsgCnt` by changing the chatId property type to Option, that you can provide None for all chats similar to other existing apis?https://js.jsonrpc.delta.chat/classes/RawClient.html#getFreshMsgCnt

**Comment by r10s** [comment]
then let's show the item unconditionally and call it a day :)

that disabling is a very minor thing in UI in this case, taking lots of effort :) sth. for when everything else is fine and stable :)
