### ISSUE TITLE
Clicking notification for another account doesn't open the target chat

### ISSUE THREAD

**Issue by WofWca** [deltachat/deltachat-desktop#3983]
- Operating System (Linux/Mac/Windows/iOS/Android): Windows 10
- Delta Chat Version: 1.46.1
- Expected behavior: The chat for which the notification appeared opens
- Actual behavior: The account is switched, but the chat selection remains unchanged
- Steps to reproduce the problem:
    1. Select chat with A on your first account
    2. Switch to your second account
    3. Wait for someone except A send you a message to your first account
    4. Click the notification
- Screenshots:
- Logs:

```
Uncaught (in promise) Error: accountid of ChatProvider context is not equal to nextAccountId
    at selectChat (ChatContext.tsx:70:15)
    at useMessage.ts:61:15
```

Here

https://github.com/deltachat/deltachat-desktop/blob/88e65f4b3fa014460dfca84d8c9f8246836e4c06/src/renderer/components/RuntimeAdapter.tsx#L41-L56

when `jumpToMessage` is called, `accountId` remains the current account ID and not the new one

https://github.com/deltachat/deltachat-desktop/blob/54cd76c3628e9add851ef50cf9716728a50f1964/src/renderer/contexts/ChatContext.tsx#L69-L73

This was probably introduced in #3789

**Comment by Simon-Laux** [comment]
I get the error in the console, but it works for me on macOS. so can not reproduce it on current main branch
