### ISSUE TITLE
File » Quit from an app quits all of DeltaChat

### ISSUE THREAD

**Issue by dkg** [deltachat/deltachat-desktop#3988]
- OS: Debian stable (12.5) amd64
- Delta Chat Version: 1.46.1 (installed via .deb)

If i open a webxdc app, it opens as a new window.

If, from that window, i choose "File » Quit", then all of DeltaChat closes, not just the webxdc app.  (closing the webxdc window via the window manager/compositor just closes the webxdc app, not all of DeltaChat

File » Quit in the webxdc app should just close the specific app, not the whole DeltaChat.

**Comment by iequidoo** [comment]
Btw, i'd say that `File > Settings` is not need at all in the webxdc window, moreover it opens the Delta Chat settings window behind the webxdc window for me. OS: Debian 12 as well.
