### ISSUE TITLE
'realtime channel' experimental option not persisted

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3990]
enabling experimental 'realtime webxdc channels' option is not persisted for me on mac using dc 1.46.1 - had a hard time until i realise that, i was always thinking the [ongoing iOS implementation](https://github.com/deltachat/deltachat-ios/pull/2225) is doing sth wrong 😂

is it only me? i cannot really believe this is a general issue :)

https://github.com/deltachat/deltachat-desktop/assets/9800740/9501bdcb-17b8-4b46-986b-07cd11af4e62

**Comment by hpk42** [comment]
fixed by #3992
