### ISSUE TITLE
There is a quick splash of some other screen in messageview

### ISSUE THREAD

**Issue by farooqkz** [deltachat/deltachat-desktop#3996]
- Operating System (Linux/Mac/Windows/iOS/Android): Linux, source
- Delta Chat Version: 1.46.1
- Expected behavior: It should go to list of messages directly
- Actual behavior: It shows something else then quickly the message list
- Steps to reproduce the problem: Just open some chat
- Screenshots: N/A
- Logs:

Not much important but it could be good if we could get rid of it somehow

**Comment by Simon-Laux** [comment]
you need a video or at least screenshot. without this I wouldn't agree with your "bug" classification

**Comment by Simon-Laux** [comment]
nothing actionable, so I'll close this issue now, feel free to reopen once you have a screenshot/video

**Comment by Simon-Laux** [comment]
If you mean that the background image is shortly shown (a few frames) without any messages (while those are loaded) that is not very easy to change / solve.

We could think about already loading messages before switching a chat, but that makes the code more complex and could introduce bugs (such as messages fail to load or take too long). So nothing for right now I'd say, I'll move it to resurrection.
