### ISSUE TITLE
"Mark All as Read" does not remove notifications

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#4002]
the gist of  "Mark All as Read" is to get chats out of ones way. therefore, and for consistency, also notifications should be removed when things are marked as read.

this issue may be one cause of stale notifications of https://github.com/deltachat/deltachat-desktop/issues/3991 , however, i doubt it is the only one as i was not using "Mark All as Read" until recently (i was not aware it exist :)

cmp https://github.com/deltachat/deltachat-desktop/issues/3979

**Comment by WofWca** [comment]
Might be related, or a duplicate https://github.com/deltachat/deltachat-desktop/issues/3982
#2438

**Comment by Simon-Laux** [comment]
I think we can treat it as own issue because it is reproducible, the other one is not yet.
