### ISSUE TITLE
AppImage crash at startup

### ISSUE THREAD

**Issue by sbadux** [deltachat/deltachat-desktop#401]
Hello
the appimage doesn't start on Fedora 29. The error seems similar to the #40 but that bug has been fixed and I thought it's better to post a new bug report. 

I start the AppImage, I choose "No" when asked to install and the app doesn't start. From the terminal I got the following errors
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libsasl2.so.2: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at load (/tmp/.mount_deltacoIymEh/resources/app.asar/node_modules/node-gyp-build/index.js:13:10)
    at Object.<anonymous> (/tmp/.mount_deltacoIymEh/resources/app.asar/node_modules/deltachat-node/binding.js:1:198)
```

**Comment by ralphtheninja** [comment]
Aye, you need to install `libsasl2-dev` on your system.

**Comment by sbadux** [comment]
Thanks for the quick reply. Unfortunately there is no libsasl* on fedora repositories. 

dnf search libsasl

returns 0 results.

**Comment by Jikstra** [comment]
@ralphtheninja if we're doing a AppImage release, all dependencies should be in the image somehow.

**Comment by ralphtheninja** [comment]
> @ralphtheninja if we're doing a AppImage release, all dependencies should be in the image somehow (which might be hard ^^). Maybe we can do the prebuilds with statically linked libsasl?

Yeah, maybe. This should ideally be solved in core. It doesn't feel right that the node bindings should build core in a special way to make it work.

**Comment by sbadux** [comment]
> @ralphtheninja if we're doing a AppImage release, all dependencies should be in the image somehow (which might be hard ^^). Maybe we can do the prebuilds with statically linked libsasl?
> 
> @sbadux check out if there's a `cyrus-sasl` or `cyrus-sals-lib` package otherwise compile if manually (i'm sad to give you this advice :/)

Sorry for the late reply. cyrus-sasl and cyrus-sasl-lib was already installed. I've installed cyrus-sasl-devel but the AppImage returns the sam error. Yes, I think that you should integrated the dipendecies in the AppImage in some way :)

**Comment by ralphtheninja** [comment]
@sbadux We're working on it but ran into other problems. See https://github.com/deltachat/deltachat-node/pull/207

**Comment by adbenitez** [comment]
same error for me :(
If this actually is not working out of the box, and users need to install a dependency, why we don't say so in the release page??? a normal user will download the appimage, run it (in a GUI so they will not see the console error) and get disappointed because "delta chat just don't work" 

also I agree with @Jikstra I was expecting an appimage to work out of the box

**Comment by ralphtheninja** [comment]
@adbenitez `AppImage` will be replaced by flatpak if any consolidation

**Comment by SuperJC710e** [comment]
FWIW I was able to get around the issue by adding symbolic links.
`cd /lib;sudo ln -s libsasl2.so.3.0.0 libsasl2.so.2;cd -;cd /lib64;sudo ln -s libsasl2.so.3.0.0 libsasl2.so.2`

**Comment by hpk42** [comment]
Currently we are using flatpak, and soon there'll be .deb pacakges. no immediate plan to try to provide an app image for now unless someone is willing to deep-dive into it, follow the other evolvnig build automations.

**Comment by greathappyforest** [comment]
> cd /lib;sudo ln -s libsasl2.so.3.0.0 libsasl2.so.2
> cd -
> cd /lib64;sudo ln -s libsasl2.so.3.0.0 libsasl2.so.2
> cd -

This works for me in CentOS7
