### ISSUE TITLE
Wayland + HiDPi Scaling factor leads to a tiny cursor

### ISSUE THREAD

**Issue by mityax** [deltachat/deltachat-desktop#4021]
- Operating System (Linux/Mac/Windows/iOS/Android): Linux (Fedora 40)
- Delta Chat Version: 1.46.1
- Expected behavior: Cursor has normal size
- Actual behavior: Cursor is extremely tiny, making the app feel not native at all
- Steps to reproduce the problem: Configure display scaling to e.g. 200% in gnome settings
- Screenshots: 
![Screenshot from 2024-07-09 18-26-22](https://github.com/deltachat/deltachat-desktop/assets/18172993/5fa95c89-3f02-4135-a6c5-cd7104c64b30)

Might be related to this: https://github.com/electron/electron/issues/19810, but I don't use _fractional_ scaling and have the flatpak installed, not a snap, and the cursor is still tiny.

**Comment by Simon-Laux** [comment]
This is expected. There was the tradeoff between blurry UI and small mouse cursor, I choose the latter.

https://github.com/flathub/chat.delta.desktop/pull/124#issuecomment-1962438900

**Comment by Simon-Laux** [comment]
I suspect you used the flatpak release, can you confirm that?
If so we should move the issue to https://github.com/flathub/chat.delta.desktop/pull/124

**Comment by Simon-Laux** [comment]
transferred to https://github.com/flathub/chat.delta.desktop/issues/139
