### ISSUE TITLE
DC automatically deactivates real-time channels when changing profiles

### ISSUE THREAD

**Issue by Raiden-GH** [deltachat/deltachat-desktop#4022]
DC-Desktop always disables the real-time channels in the settings when switching accounts.

Steps to reproduce the problem:

- Enable real-time channels
- Change profile
- Switch back to the first profile
- Real-time channels are deactivated

macOS 14.5
DC-Desktop 1.46.1

**Comment by hpk42** [comment]
thanks for reporting! 
this is fixed on main but not released yet -- see #3990 
TL;DR actually the option is enabled but desktop 1.46.1 shows the setting wrongly as off.

**Comment by Simon-Laux** [comment]
duplicate of #3990, will be solved in next release
