### ISSUE TITLE
Window TitleBar and Window Menu?

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#403]
1. What should be in the Window menu and where(in which order)?

2. Should we make a custom Title bar like [VS-Code](https://code.visualstudio.com/updates/v1_27#_custom-title-bar-and-menus-on-windows-and-linux)(has the menu in it) or Discord?

**Comment by Jikstra** [comment]
I think the current title bar is quite ugly, i think it's fine to just have no title bar? Don't know if we really need one, i think we don't.

**Comment by r10s** [comment]
_if_ you leave the standard-window-menu bar, we should add the menu "file" as the first menu, even if there is only the option "quit" in it. this is convention in ui since at least 30 years :)

**Comment by karissa** [comment]
I think keeping it as it is for now would be fine, but in the long term (or if someone feels inspired) I agree that looking at this UX would make things nicer.

My opinion would be to move the 'change language' and 'about' into the settings box and getting rid of the title bar completely.

**Comment by Simon-Laux** [comment]
@karissa I think you mean the menu bar and the title bar.
There are two separate things until we decide to make a custom one that contains both like in vscode. So we should specify which one we are talking about to avoid confusion. :wink: 

Titlebar:
![titlebar](https://user-images.githubusercontent.com/18725968/50048575-5de50b00-00d0-11e9-80a4-b40d29ba8ab0.png)
Menu/-bar
![menu](https://user-images.githubusercontent.com/18725968/50048576-61789200-00d0-11e9-8334-eb6e5040beed.png)
Custom Titlebar (both in one to save space) (made with borderless window I guess)
![custom](https://user-images.githubusercontent.com/18725968/50048577-63daec00-00d0-11e9-8d2f-f149e9809b77.png)

**Comment by hpk42** [comment]
the incredible issue-police determines to close this issue because it's old, not an active development item, and rather an open question ... maybe open a new one after discussion (IRC, support, direct) to directly suggest something ...
