### ISSUE TITLE
Unable to download. 

### ISSUE THREAD

**Issue by rarocompany** [deltachat/deltachat-desktop#4031]
- Operating System (Linux/Mac/Windows/iOS/Android): - Windows/iOS/Android
- Delta Chat Version: Latest
- Expected behavior: Download
- Actual behavior: Not downloading on any of the phones in Cuba.
- Steps to reproduce the problem: Attempts to download in multiple operating systems.
- Screenshots: 
- Logs:

**Comment by WofWca** [comment]
Could you clarify? Where are you trying to download from?

**Comment by Simon-Laux** [comment]
I guess they probably mean that Cuba blocks our website. this is not an issue in deltachat desktop. Use a VPN to download it or download from GitHub releases until they unblock it again.
