### ISSUE TITLE
Improve confirmation message when trying to delete a 1:1 chat

### ISSUE THREAD

**Issue by iequidoo** [deltachat/deltachat-desktop#4050]
Now it says `Are you sure you want to delete "email@address"?` One could think that the contact will be deleted, not the chat. Secondly, chatmail addresses don't tell much. Btw, for group chats the message looks good, it uses the chat name. As for DC Android, it asks `Delete 1 chat? It will no longer be shown in the chat list; its messages will remain on the server.` I.e. no contact name as well, but it's clear what will happen at least.

**Comment by iequidoo** [comment]
I think https://github.com/deltachat/deltachat-desktop/commit/ef3aa041982da27e73347a46540e096d79556ad3 fixes #4052, but not this issue. If i'm wrong please close again :)

**Comment by r10s** [comment]
closing, this seemed to be a misunderstanding; the string is anyways improved at https://github.com/deltachat/deltachat-android/pull/3219 as discussed at https://github.com/deltachat/deltachat-desktop/pull/4072
