### ISSUE TITLE
remove email address from reaction details & make details tappable

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#4066]
as at other places,
we should tune down showning email addresses
also in the primary reaction UI.

ppl will recognize name and avatar,
and if in doubt, you should be able to tap the row to go to the full profile.

this also makes the dialog easier to read, brings things to the point
and adds consistency to iOS (and now [Android](https://github.com/deltachat/deltachat-android/pull/3207))

so,  concretely:

- remove the address in the reaction details dialog (as stroked in the following image):<br><img width="320" alt="Screenshot 2024-08-05 at 15 02 57" src="https://github.com/user-attachments/assets/ffd8ff46-f749-43b0-97e6-df2beedcef05"><br>the remaining name should be centered vertically and use getDisplayName() (which will use the address if there is no name set)

- when tapping the row, open the corresponding contact's profile

**Comment by Simon-Laux** [comment]
> when tapping the row, open the corresponding contact's profile

should the reactions dialog close or stay open in the background?

**Comment by r10s** [comment]
> should the reactions dialog close or stay open in the background?

it is a _little_ nicer, if it stays open in the background. that way, one can peek at some details, close, and tap another reaction's contact. however, one need to take care of cleaning the stack then eg. on tapping "Send Message" from the contact profile, maybe on other actions.

that said, it is not a common or important flow. it is also totally fine and maybe easier if the reaction dialog is just closed. this is what eg. android is doing, and there are no plans to change it. it is good enough as well.

so, i would go for the leave-open flow only if it is really a no-brainer and not more code/complexity as if it will be closed.
