### ISSUE TITLE
QR Code Generation for Second Device

### ISSUE THREAD

**Issue by Gh0stz0x** [deltachat/deltachat-desktop#4078]
- Operating System (Linux/Mac/Windows/iOS/Android): Linux
- Delta Chat Version: 1.46.3
- Expected behavior: When I click on Add Second Device, the QR Code should be generated.
- Actual behavior: When I click on Add Second Device, the QR Code is not generated after a while and it returns to the Add Second Device screen with the explanation of what this DC function is for.
- Steps to reproduce the problem: Settings --> Add Second Device --> Continue
- Screenshots:
- Logs:

**Comment by nicodh** [comment]
Is fixed in core ( https://github.com/deltachat/deltachat-core-rust/pull/5882 ), will be fixed in next desktop release. You may try https://download.delta.chat/desktop/preview/deltachat-desktop-4082.AppImage if that works for you

**Comment by Simon-Laux** [comment]
fixed by updating core in #4082
