### ISSUE TITLE
Release Progress 1.46.5

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-desktop#4081]
- [x] git tag
- [x] DeltaChat Website (https://github.com/deltachat/deltachat-pages/pull/947)
- [x] flathub (https://github.com/flathub/chat.delta.desktop/pull/140)
- [x] GitHub release (https://github.com/deltachat/deltachat-desktop/releases/tag/v1.46.5)
- [x] downloadable files also on GitHub
- [x] MacOS store
- [x] Windows store (submitted)
- [x] homebrew
- [ ] aur
- [x] nix (https://github.com/NixOS/nixpkgs/pull/334681)
- [ ] (community) snap

**Comment by dotlambda** [comment]
https://github.com/NixOS/nixpkgs/pull/334681 for Nixpkgs
