### ISSUE TITLE
ctrl+q only minimizes to tray

### ISSUE THREAD

**Issue by missytake** [deltachat/deltachat-desktop#4084]
- Operating System (Linux/Mac/Windows/iOS/Android): xubuntu 22.04 (but @nicodh said it's also on macOS*)
- Delta Chat Version: 1.46.3
- Expected behavior: if I press ctrl+q, the process ends and the window and all sub-windows close, no future notifications appear.
- Actual behavior: the windows closes, but the tray icon stays there and I still receive notifications.
- Steps to reproduce the problem:
  - open the application
  - enable "Show Tray Icon" in Settings
  - press ctrl + q

\* see comment below

**Comment by iequidoo** [comment]
For me the process finishes as expected, Debian GNU/Linux 12, KDE Plasma 5.27.5

**Comment by nicodh** [comment]
Testing:
**Flatpak on Ubuntu**: 
Strg + Q just minimizes, but same for ending from menu, only "Exit" on tray icon really finishes the app
**deb package on Ubuntu**:
Str + Q does not (!) close the app, (for deb 1.46.1 it works) - but the Quit from menu does also not close the app!
**MacOS**: 
Cmd + Q closes the app (probably I had other processes running from development last time I tested)
**Windows**: 
Ctrl + Q closes the Window, but the background process stays alive, but same for ending from menu, there seems to be no way to "really" finish the app via UI

**Comment by nicodh** [comment]
> For me the process finishes as expected, Debian GNU/Linux 12, KDE Plasma 5.27.5

How did you install DeltaChat?

**Comment by iequidoo** [comment]
> How did you install DeltaChat?

`dpkg -i deltachat-desktop_1.46.5_amd64.deb`

**Comment by missytake** [comment]
> > How did you install DeltaChat?
> 
> `dpkg -i deltachat-desktop_1.46.5_amd64.deb`

same

**Comment by iequidoo** [comment]
I had "Show Tray Icon" disabled, if i enable it, the process doesn't quit indeed

**Comment by maxphilippov** [comment]
Should be fixed on Windows/Mac OS on current `main`, didn't get a chance to test on Linux. @missytake can you please check it on Linux?

**Comment by missytake** [comment]
> Should be fixed on Windows/Mac OS on current `main`, didn't get a chance to test on Linux. @missytake can you please check it on Linux?

fixed on linux, thanks!
