### ISSUE TITLE
Properly move out all color/styling variables

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#409]
Currently we still have some variables in the components, we should maybe also use the styled-components theme thing. https://www.styled-components.com/docs/advanced#theming

**Comment by Simon-Laux** [comment]
We could use the new css variables for theming and completely move away from any pre-processors:
https://css-tricks.com/css-custom-properties-theming/

Though that would mean we can't use the scss/sass functions anymore (such as lighten, darken and custom ones) and we only have the vanilla css functions:
https://www.w3schools.com/csSref/css_functions.asp

**Comment by Jikstra** [comment]
Wouldn't use the css variables, they are quite shitty from what i know. Weird syntax, not all the features we need. I think styled-components are fine for what we need.

**Comment by Simon-Laux** [comment]
https://ramenhog.com/blog/2017/06/07/theming-with-css-custom-properties

**Comment by Simon-Laux** [comment]
> I think styled-components are fine for what we need.

I bet that they increase the compile time and we don't get the benefit of scss/sass

**Comment by Simon-Laux** [comment]
https://github.com/danbahrami/react-custom-properties

**Comment by Jikstra** [comment]
> I bet that they increase the compile time and we don't get the benefit of scss/sass

As all js code increases the compile time, this does too. But sass/scss will increase it even further :)
The things we're using styled components for is more than just variables, it's small styled react components which are quite helpful in my opinion. 

Theming with styled components: https://www.styled-components.com/docs/advanced#theming

**Comment by Simon-Laux** [comment]
solved with #858
