### ISSUE TITLE
Release Progress 1.46.7

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-desktop#4099]
- [x] DeltaChat Website
  - [x] flathub  (https://github.com/flathub/chat.delta.desktop/pull/141)
  - [x] GitHub release  (https://github.com/deltachat/deltachat-desktop/releases/tag/v1.46.7)
       - [x] downloadable files also on GitHub
  - [x] MacOS store
  - [x] Windows store (published) 
  - [x] homebrew
  - [x] arch linux
  - [x] nix (https://github.com/NixOS/nixpkgs/pull/338211#issuecomment-2325244697)
  - [x] (community) snap

**Comment by Simon-Laux** [comment]
flatpak is not in the store yet, so it is not done yet
