### ISSUE TITLE
Do not try to start I/O before deleting account

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop#4104]
Currently if an account is imported from Android nightly or DeltaLab (now ArcaneChat) into the current Desktop with stable core 1.142.11, it fails to start I/O with a toast "Failed to start I/O: Invalid configured_imap_certificate_checks value". This is expected, user will need to update to the new core or reconfigure an account to make it usable.

The problem is that it is impossible to delete such broken account in the current Desktop 1.46.7. When user right-clicks the profile and selects "Delete Profile", desktop calls `selectAccount` here:
https://github.com/deltachat/deltachat-desktop/blob/9fdd6ea790b2027e021c6026d2c6c7e6c647b4dc/src/renderer/ScreenController.tsx#L189

`selectAccount` is this function that tries to start I/O and fails:
https://github.com/deltachat/deltachat-desktop/blob/9fdd6ea790b2027e021c6026d2c6c7e6c647b4dc/src/renderer/ScreenController.tsx#L119-L142

Desktop should not try to start I/O before deleting an account. If it fails, account cannot be deleted. Also if advanced setting "Only Synchronize Selected Profile" is enabled, I/O may have been stopped on purpose and starting I/O right before deleting an account is unnecessary.

**Comment by adbenitez** [comment]
> This is useful for some people that need more control about what accounts connect in public networks.

for this in ArcaneChat we have `ui.enabled` and allow users to enable/disable accounts individually, that is more flexible than "enable selected account only" since then you can use ex. 2-3 needed accounts concurrently while the rest are disabled

**Comment by Simon-Laux** [comment]
>  that is more flexible than "enable selected account only" since then you can use ex. 2-3 needed accounts concurrently while the rest are disabled

thats also what the core pr does. But there is still the usability question whether account should be started automatically when it is selected despite being disabled or if it should just stay disabled until the user enables it again.

**Comment by adbenitez** [comment]
it should stay disabled, and a banner could be shown at the top saying "The profile is disabled  [ENABLE]" ot so

similar to what Conversations(xmpp) does for disabled accounts
