### ISSUE TITLE
Flatpak takes a very long time to launch

### ISSUE THREAD

**Issue by niels0n** [deltachat/deltachat-desktop#4110]
- Operating System (Linux/Mac/Windows/iOS/Android): Linux (Fedora 40)
- Delta Chat Version: 1.46.5 (git: flathub)
- Expected behavior: DeltaChat should not take that long to launch
- Actual behavior: DeltaChat takes something like 30 seconds to launch
- Steps to reproduce the problem: 1. flatpak install flathub chat.delta.desktop 2. flatpak run chat.delta.desktop
- Logs: When I launch it from terminal, when the gui appears (so after the 30 seconds), these messages appear too:

```
andrea@fedora:~$ flatpak run chat.delta.desktop
[2:0907/100317.184229:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
Only one instance allowed. Quitting.
```

**Comment by Simon-Laux** [comment]
will be fixed by  #4379
more info in https://github.com/deltachat/deltachat-desktop/issues/4350, so I'll mark this as duplicate
