### ISSUE TITLE
Adding the desktop client as second device using a QR code fails - message "please login first"

### ISSUE THREAD

**Issue by frie** [deltachat/deltachat-desktop#4130]
- Operating System (Linux/Mac/Windows/iOS/Android): Linux (Manjaro)
- Delta Chat Version: 1.46.2
- Expected behavior: the client is added as 2nd device, as observed when using an Android device
- Actual behavior: when scanning the QR code a popup-window comes up showing the message "please login first"
- Steps to reproduce the problem: start client, add profile (plus-sign top left), select "add as 2nd device", scan QR code
- Screenshots:
![Bildschirmfoto vom 2024-09-13 18-53-42](https://github.com/user-attachments/assets/f52cc3c8-326a-4cd7-b441-6d8fb2080a0c)
- Logs:

**Comment by Simon-Laux** [comment]
you are on an old version, please try again with current release: https://github.com/deltachat/deltachat-desktop/releases/tag/v1.46.8

**Comment by frie** [comment]
Did not expect that this minor version number makes that difference... Works as expected now with the current release. 1.46.2 currently is the version provided by Arch / Manjaro.

**Comment by Simon-Laux** [comment]
https://archlinux.org/packages/extra/any/deltachat-desktop/

I personally recommend using arch over manjaro. Or use the flatpak of deltachat?

**Comment by frie** [comment]
> arch over manjaro

Easiest install for Arch / Manjaro ist from the github releases page (https://github.com/deltachat/deltachat-desktop/releases) - just download and install the pacman package. Arch Linux currently offers 1.46.7-1 which still is not the most recent version.
I personally never had serious problems with the Manjaro repositories. Usually this is far ahead against Ubuntu / Mint / Debian (where DeltaChat needs a separate install anyway). BTW I prefer the AppImage install, which is missing at least in the german docs (https://delta.chat/de/download)

**Comment by Simon-Laux** [comment]
> BTW I prefer the AppImage install, which is missing at least in the german docs (https://delta.chat/de/download)

It has no auto updater so it's hidden in an expandable section:
<img width="780" alt="Bildschirmfoto 2024-09-17 um 02 42 22" src="https://github.com/user-attachments/assets/20d8d8a6-bf77-4f4d-a5b6-bb7ef0471db2">
