### ISSUE TITLE
When clicking on a notification no further notification will show up

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#414]
```
      notify.on('click', () => {
        dc.selectChat(chatId)
        app.focus()
        notify.close()
      })
```

I think `notifiy.close()` should be `notifiy.emit('close')` ?

**Comment by karissa** [comment]
@Jikstra you aren't supposed to do `emit` from outside of the module, unless absolutely necessary -- instead i'm just going to do it directly by setting notify = null (i *guess* `click` already closes the notification, but doesn't emit `close`
