### ISSUE TITLE
File-Attachment-Messages are broken

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#416]
At the moment they don't even show the file name.

**Comment by karissa** [comment]
The filename is also not shown on Android, not sure if it's needed here.

**Comment by karissa** [comment]
Just kidding, it shows the filename for PDFs and probably other similar files, but not videos, audio, or images

**Comment by Simon-Laux** [comment]
https://github.com/deltachat/deltachat-desktop/blob/master/src/renderer/components/MessageWrapper.js#L219
```js
msg.attachment = {
      url: msg.file,
      contentType: convertContentType(message),
      filename: msg.text
}
```
`msg.text` is somehow empty for files.
Also the text color is white for incoming messages.

**Comment by r10s** [comment]
`msg.text` is only set if the sender added some text together with the file, eg. some words added to a photo.

this is only possible since android-dev, btw. the current f-droid version does not allow sending such "compound messages"

**Comment by Simon-Laux** [comment]
How should we handle this thing then?

**Comment by Simon-Laux** [comment]
Is the filename supposed to be that optional message?

**Comment by r10s** [comment]
not sure if i got the complete context. i am talking about a raw [dc_msg_t object](https://c.delta.chat/classdc__msg__t.html) that has some attributes, eg. `file` and `text`. it's totally fine if only one of both are set. if a mesage is _just an image file_ we should only display this one. no need to display the name or sth. like that.

the file _name_ should only be displayed if the file _content_ cannot be displayed by delta-chat directly - this is true eg. for pdf, epub and so on; a click on these file should launch the corresponding application then.

**Comment by Simon-Laux** [comment]
I'm talking about the messages that have attachments that aren't displayed in delta chat.
And currently I try to find out, how I can get the file name and file size, because ATM those properties are broken in the desktop client.

**Comment by r10s** [comment]
ahh, okay :)
