### ISSUE TITLE
"I already have a profile" > "Paste from Clipboard" only shows "Scanned QR Code text: ..." popup then does nothing

### ISSUE THREAD

**Issue by ell1e** [deltachat/deltachat-desktop#4161]
My apologies if this is somehow intended, but it does seem to be a bug: when I go to one Delta Chat instance and do "Settings" > "Add Second Device" and then use "Copy", then I go to the other device and somehow get the text into the clipboard there and do "I already have a profile" > "Paste from Clipboard" only shows "Scanned QR Code text: ..." popup then does nothing. The expected result would be that it actually allows me to somehow pair the devices at that point, or that it shows me why that's not possible.

- Operating System (Linux/Mac/Windows/iOS/Android): Linux
- Delta Chat Version: Desktop 1.46.1 flathub 1719314892000
- Expected behavior: "Paste from Clipboard" on the 2nd device of the 1st's device pairing info will somehow proceed the device pairing or tell me what the issue is, if I did something wrong
- Actual behavior: "Paste from Clipboard" on the 2nd device will show some "Scanned QR Code text: ..." popup and then when I press "OK" I'm just back at the profile creation screen with nothing new having happened.
- Steps to reproduce the problem: See in description above.
- Screenshots:
![Screenshot_20241001_232222](https://github.com/user-attachments/assets/19422dbf-b35a-43d6-8b0e-a04ac1ac20e7)

- Logs: 
[2024-10-01-23-06-14.log](https://github.com/user-attachments/files/17216635/2024-10-01-23-06-14.log)

**Comment by Simon-Laux** [comment]
please try again with version 1.46.8 should have been fixed already.

see #4075 

closing the issue for now, we can reopen it if it is a new bug

**Comment by ell1e** [comment]
I updated to 1.46.8 (core v1.142.12) but sadly the same thing happens!

**Comment by Simon-Laux** [comment]
I can not reproduce this, are you sure you have that version on both devices? if not what version of deltachat has the other device?

**Comment by ell1e** [comment]
Yes, they're both 1.46.8, I just tested it again.

The problem seems to be whitespace. I copied it via a securely transferred file via syncthing, for which I manually pasted and copied it again from that file, where I additionally copied some line breaks on the target device.

*(As a side tangent: generally, if the code is formatted wrong it would be nice if the error told me that this isn't a valid code, rather than some "Scanned QR code text:" message that doesn't really say why it tells me that QR code text or what stage of the process I am at.)*

Now that I entered the code without whitespace, I'm seeing a "Add as Second Device" progress bar in a popup that is stuck at zero percent with nothing happening. I'm not sure what I did wrong now :open_mouth: but it's still not working, even though it seems like I got one step further.

**Comment by Simon-Laux** [comment]
we could trim leading and trailing whitespaces upon pasting.

**Comment by ell1e** [comment]
I saw a person run into this today after trying two different wifis, with desktop being the "origin" and android scanning the desktop 2nd device QR and failing to do anything. Should I reopen? 🤔

**Comment by Simon-Laux** [comment]
make a new issue, sounds different - maybe even a core issue. don't forget to mention all involved app versions and check that there were no firewalls in the way.
