### ISSUE TITLE
make clear, "Setttings / Password & Account" is about "Log In"

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#4182]
the "Setttings / Password & Account" dialog lacks the framing that it is about "Log In" and it [may be unclear](https://github.com/deltachat/interface/issues/73), what the dialog is about.

<p><img width=260 src=https://github.com/user-attachments/assets/cbd5dd79-8c46-40f3-be4d-4778686b9e68>
<br><i>no hint about &quot;Log In&quot;</i></p>

on android and iOS,  these dialogs are much clearer. and also on desktop-obboarding things are fine:

<p><img width=260 src=https://github.com/user-attachments/assets/61a3c046-08be-4edc-9b2f-17ead7d56e34>
<img width=260 src=https://github.com/user-attachments/assets/0cfcde38-ad9b-4b70-8d75-843204037395>
<img width=260 src=https://github.com/user-attachments/assets/abd8d457-799b-4d64-a8bd-b1cb79f313d2>
<br><i>&quot;Log In&quot; in the title and partly in the buttons</i></p>

so, shortly
- the dialog opening at "Setttings / Password & Account" should just be roughly the same as  "Onboarding / Classic E-Mail Login"
- the buttons in "Settings" or at other places should not be changed. only the dialog

**Comment by Simon-Laux** [comment]
The iOS screenshot feels like it gives a bit more context. But I'm not sure how we would transfer that double heading ui to the desktop dialog, in a way that looks nicely.

**Comment by r10s** [comment]
no need to add two headlines, just use one as on android. and name the button "Log In". this should improve things significantly already
