### ISSUE TITLE
 use standard "Back" button for archive

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#4184]
not sure, why the "back" button in archive looks like it is, however, that is sort of non-standard. 

we're meanwhile using the standard back-button also in settings and at other places, and i see no reason to use sth. else here.

current state, looks a bit like undo/redo:

![Screenshot 2024-10-06 at 17 49 40](https://github.com/user-attachments/assets/09bd0e89-1f47-4860-be75-33cf0b6d0897)

this is what one would expect:

![Screenshot 2024-10-06 at 17 49 40 copy](https://github.com/user-attachments/assets/e660849a-a4a5-49ab-84ea-5d4231ed8aa7)

it's a minor, but as this is very much in the view also of new users, worth improving

**Comment by Simon-Laux** [comment]
Would wait until blueprint removal pr #4006 is merged to avoid causing merge conflicts.

**Comment by Simon-Laux** [comment]
closed by #4217 (there was a typo in the issue number, thats why it didn't close automatically)
