### ISSUE TITLE
"Paste" invite codes is too hidden

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#4185]
it happens several times we got reports that ppl do not find the option to "Paste" invite codes. 

the function is hidden in the "settings" icon, inside the QR code.

![Screenshot 2024-10-06 at 18 03 22](https://github.com/user-attachments/assets/a745c051-29f0-404f-ada8-4a57adbc832d)

this was refactored when we added camera-select and image-loading, it was also discussed that time, that it will be harder to discover, but we gave it a try, as it simplified code and "everyrhing" could be contained in the scanner component that way.

however, turns out, this causes troubles, and we should go for an explicit "Paste" button as before.

idea is also, that "Paste" should be at a similar position as "Paste", which would also be fullfilled by sth. like the following:

![Screenshot 2024-10-06 at 18 03 22 copy](https://github.com/user-attachments/assets/7dc4fc78-5415-4df4-96e6-a909368d1ed0)

_this is how the dialog also looked in the past_

the "settings" menu can stay as is, including its options. it seems fine, if "Paste" is duplicated.

**Comment by maxphilippov** [comment]
Possible duplicate of #3936, working on it

**Comment by r10s** [comment]
indeed, forgot, i filed the same issue some months ago 😅

closing this one, one is enough :)
