### ISSUE TITLE
Dragging links crashes electron

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#421]
Not much more to say, but it really does weird stuff to whole xorg as the link is glitchingly shown on all virtual desktops. Maybe a issue specific to my setup and not an electron/deltachat bug.

**Comment by ralphtheninja** [comment]
Dragging links?

**Comment by karissa** [comment]
Yeah this may or may not be fixed in electron 3.0...

**Comment by ralphtheninja** [comment]
@karissa Maybe we should try out electron 3 again. What was the problem @substack had?

**Comment by karissa** [comment]
Yes tested this on electron 3 and the bug seems to be gone.
