### ISSUE TITLE
Sharing a contact exposes the custom contact display name in the .vcf file name

### ISSUE THREAD

**Issue by missytake** [deltachat/deltachat-desktop#4230]
- Delta Chat Version: deltachat-desktop 1.46.8, core v1.142.12
- Expected behavior: when I set a custom name for a contact, others will not see it.
- Actual behavior: when I share a contact to a chat, I see the contact's self-chosen display name and their email address; but when recipients save the .vcf as a file, the custom name I chose for the contact is part of the .vcf file name.
- Steps to reproduce the problem:
  - edit the name of a contact to something awkward, like "<name>, secret crush"
  - share the contact to saved messages
  - right click on the message, "save as" file to your file system
  - see that the file name is VCard-namesecretcrush.vcf
- Screenshots:

![image](https://github.com/user-attachments/assets/a5f78fed-0005-49a8-9a30-d118f2b1d120)

---

![image](https://github.com/user-attachments/assets/b188a46d-8fd5-4295-9099-61fb618350fc)

---

![image](https://github.com/user-attachments/assets/71337aec-1dec-4a60-abf3-3ca8c6f9b7c5)

**Comment by Simon-Laux** [comment]
Let's fix this before composer refactoring, though we need to remember to use the new method after the composer refactoring, so adding it to that milestone as well.
