### ISSUE TITLE
Reactions are drawn below the message bubble

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop#4235]
![emoji](https://github.com/user-attachments/assets/277e52bb-14b1-4300-90f6-2619fcc5a5ef)

This is with commit 1ebcc5a62b5e6a320254eb695574c747c0253362

**Comment by WofWca** [comment]
This likely has been worsened in https://github.com/deltachat/deltachat-desktop/pull/4120 where I removed the bottom margin.

One issue here is that the metadata for an image with no captions has `position: absolute;`, thus it doesn't get included in the normal flow:

https://github.com/deltachat/deltachat-desktop/blob/a5c02433976909fe01a64f3049c96d0d101ae9d8/packages/frontend/scss/message/_metadata.scss#L10

This is how it looks on 1.46.8:

![image](https://github.com/user-attachments/assets/8c97cf2e-fdbb-475f-a17d-9e4d6e1c4f7e)
