### ISSUE TITLE
Test Release Progress 1.47.0

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#4241]
- [x] tag
- [x] builds
- [x] forum post https://support.delta.chat/t/help-testing-the-upcoming-1-47-x-release/3292
   - [x] write small list for testers what to focus on while testing
- [x] flathub beta
- [x] GitHub release
     - [x] downloadable files also on GitHub
     - [x] add section that this is a test release linking to the forum post

also make sure that these targets/platforms build:
- [ ] nix

**Comment by WofWca** [comment]
Some candidates for the list of things to test:
- Dialogs and context menus (#4006)
- #3965
- pay attention to jumpToMessage stuff and the message list in general (#4145)
