### ISSUE TITLE
Desctop version is not copying QR code when I try to register it as second device (1.40.4/Windows 7)

### ISSUE THREAD

**Issue by zratustra** [deltachat/deltachat-desktop#4258]
When I try to register desktop version as the second device, then camera started, but scanning of QR code is not performed. When I choose other options (load image file or load text from clipboard) also nothing happens.
At the same time during this process Delta Chat is eating about 20% of CPU

- Operating System (Linux/Mac/Windows/iOS/Android): Windows 7
- Delta Chat Version: 1.40.4
- Expected behavior: accepting of QR-code from first device in various form (image, text from clipboard, scan of code)
- Actual behavior: nothing happened, but great consumption of CPU
- Steps to reproduce the problem:
- Screenshots:
- Logs:

**Comment by Simon-Laux** [comment]
This is an old unsupported version of deltachat and windows.
Thanks for reporting, but unless someone sponsors work on a compatibility version that brings newer delta chat to older operating systems we can't help you. Though you can fork the repo and try downgrading electron.
