### ISSUE TITLE
progress bar layout regression

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#4263]
- the progress bar is black in light theme, this is not what the user has learned and looks as if things are already done - although not event started :)

- the progress bar dialog has an odd yellow focus border, this does not make much sense (wondering, btw, why there is no cancel button, but that is another issue)

we should go back to the layout of 1.46.x

progress bar on 1.47 - note: this is the state of 0%:

![Screenshot 2024-10-25 at 12 20 50](https://github.com/user-attachments/assets/f3068e5a-f491-418b-804a-a0fe5e5be72d)

progress bar on 1.46.x:

![Screenshot 2024-10-25 at 12 21 50](https://github.com/user-attachments/assets/12523b8f-0836-4ea4-aeb0-00028e290140)

**Comment by WofWca** [comment]
Is this `main` or the pre-release version?

**Comment by r10s** [comment]
1.47, as stated above

**Comment by WofWca** [comment]
We need to check whether this is fixed by https://github.com/deltachat/deltachat-desktop/pull/4248

**Comment by r10s** [comment]
just tested on `main` - the issue is the same, black bar. so it was not fixed by #4248

**Comment by r10s** [comment]
> Also there should be a cancel button, latest core has cancelling for backup transfer/export working

i created a separate issue for that at #4267

**Comment by WofWca** [comment]
Chromium automatically switches the color of the background based on how bright `accent-color` is. The responsible CSS:

https://github.com/deltachat/deltachat-desktop/blob/382a8060a67d00f623c905e070dd7aae2e8626bf/packages/frontend/scss/login/_login.scss#L204-L225
