### ISSUE TITLE
add "cancel" button to "backup"

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#4267]
the "export backup" progress bar dialog lacks a "cancel" button, see https://github.com/deltachat/deltachat-desktop/issues/4263 for a screenshot

in deltachat-ffi, the progress can be stopped using [`dc_stop_ongoing_process()`](https://c.delta.chat/classdc__context__t.html#a4df8b12ccbfb482a0557d027eae43cfc), not sure how that works in deltachat-jsonrpc

EDIT: "add second device" ("send backup") has a cancel button. i did not check if "add as second device" ("receive backup") or "import backup" are cancellable

**Comment by WofWca** [comment]
Here is the "export backup" code:

https://github.com/deltachat/deltachat-desktop/blob/0e0d0b80d598802ebb972c8d6c05b593bd896f24/packages/frontend/src/components/Settings/Backup.tsx#L82-L108

For reference, here is the "log in" dialog which has a "cancel" button:

https://github.com/deltachat/deltachat-desktop/blob/48e755d88bd2c3ba8f94fd9e5fe878fea84249e8/packages/frontend/src/components/LoginForm.tsx#L432-L452
