### ISSUE TITLE
Fresh messages: opening a chat only shows the first one, you need to scroll for the rest

### ISSUE THREAD

**Issue by missytake** [deltachat/deltachat-desktop#4284]
- Operating System (Linux/Mac/Windows/iOS/Android): xubuntu 22.04
- Delta Chat Version: 1.47.0
- Expected behavior: If I open a chat with multiple fresh messages, half of the chat view shows the fresh ones, half of the chat view old messages for context.
- Actual behavior: If I open a chat with multiple fresh messages, the chat view only shows the first of them, and you need to scrolls down until you see the other fresh messages, even if they would span less than half of the screen.
- Steps to reproduce the problem:
  - Alice sends to messages to Bob
  - in Bob's profile, open the chat with Alice and view the first message
  - now scrolls down to see the second message

**Comment by WofWca** [comment]
Removing it when it's out of view is another option.
