### ISSUE TITLE
For sent messages which are too long, "show full message" doesn't do anything

### ISSUE THREAD

**Issue by missytake** [deltachat/deltachat-desktop#4289]
- Operating System (Linux/Mac/Windows/iOS/Android): xubuntu 22.04
- Delta Chat Version: 1.47.0
- Expected behavior: if I send a message to someone, and it is too long to fit into one message bubble, I can click on "show full message" to view it.
- Actual behavior: If I click on "show full message", nothing happens.
- Steps to reproduce the problem:
  - send a loong message to someone, which needs to get truncated
  - click on "show full message..."

**Comment by missytake** [comment]
note that it works on incoming messages. someone mentioned a possibly related core bug yesterday, but I couldn't find it in the core's issue tracker

**Comment by iequidoo** [comment]
Already fixed in Core: 10aa308501f9f8e03955a20a703e4cdb43340eb9
