### ISSUE TITLE
Footer overlaps message if image only

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-desktop#4310]
Footer in message with image only, overlaps the image and reactions are displayed on the right

Happens for incoming and outgoing messages

![image](https://github.com/user-attachments/assets/959dee65-6e5a-4b0f-a4e7-2eeba13dad16)

![image](https://github.com/user-attachments/assets/dc8a4867-3b97-41ba-8c6a-2993ea9b853d)

**Comment by Simon-Laux** [comment]
![Bildschirmfoto 2024-11-02 um 17 15 50](https://github.com/user-attachments/assets/2f2b85dc-5312-4f57-a172-ad7590fdbb7a)

can't reproduce on main: 5eef453724cb19b7c2c136bce80a2b78bc73de71

also the overlay metadata is intended behaviour, I think on android and iOS they even overlay the name when it is not a forward message.

**Comment by iequidoo** [comment]
Thanks, then there's nothing to fix it seems. I'm using 1.46.8, waiting for 1.47.1 with fixed deb package name

**Comment by iequidoo** [comment]
Btw, i checked Telegram and Whatsapp, they don't put reactions onto image, only datetime

**Comment by WofWca** [comment]
The original post is a duplicate of https://github.com/deltachat/deltachat-desktop/issues/4235, which has been recently resolved. Please confirm that you're on 1.47.1 or `main`.

For what @link2xt there is a WIP MR: #4176

**Comment by nicodh** [comment]
Closed and moved to https://github.com/deltachat/deltachat-desktop/issues/4322
