### ISSUE TITLE
release an rpm package for opensuse / fedora

### ISSUE THREAD

**Issue by CodedIsTaken** [deltachat/deltachat-desktop#4317]
to make it more convenient for the users of openSUSE / fedora, rhel, and many more, i strongly advise you maintain a copr or opensuse, fedora package for this application, right now, have any workarounds?

**Comment by CodedIsTaken** [comment]
To make it easier to update, I also recommend uploading this to fedora’s official repositories or your own copr repo or on opensuse repos and any other repo, it can streamline updates

**Comment by Simon-Laux** [comment]
I made a forum topic for this, make sure to vote on the survey there if you want to see us maintaining an official repo: https://support.delta.chat/t/survey-additional-ways-to-get-dc-desktop-on-linux/3320

**Comment by CodedIsTaken** [comment]
> I made a forum topic for this, make sure to vote on the survey there if you want to see us maintaining an official repo: https://support.delta.chat/t/survey-additional-ways-to-get-dc-desktop-on-linux/3320

Thanks, I made an account but I do not have trust level one to vote, maybe later or you could award me a trust level.

**Comment by CodedIsTaken** [comment]
> I made a forum topic for this, make sure to vote on the survey there if you want to see us maintaining an official repo: https://support.delta.chat/t/survey-additional-ways-to-get-dc-desktop-on-linux/3320

Additionally, I highly recommend you maintain a copr repo over a standard package on the fedora repos or opensuse repos because:

copr supports both opensuse and fedora.

copr allows streamlined development at your own pace, no asking developers to release packages you upload when.

**Comment by Simon-Laux** [comment]
> Thanks, I made an account but I do not have trust level one to vote, maybe later or you could award me a trust level.

I did that.

> copr allows streamlined development at your own pace, no asking developers to release packages you upload when

you seem to be knowledgable in this area, we would assist you if you want to try getting a copr repo to work.
It's mostly that the core team currently has different priorities, but we would answer questions and help with deltachat specific problems. Like you could make a community maintained repo and when it is stable we might collaborate to turn it into the official repo.

**Comment by CodedIsTaken** [comment]
> > Thanks, I made an account but I do not have trust level one to vote, maybe later or you could award me a trust level.
> 
> I did that.
> 
> > copr allows streamlined development at your own pace, no asking developers to release packages you upload when
> 
> you seem to be knowledgable in this area, we would assist you if you want to try getting a copr repo to work. It's mostly that the core team currently has different priorities, but we would answer questions and help with deltachat specific problems. Like you could make a community maintained repo and when it is stable we might collaborate to turn it into the official repo.

Even if rpm fails, you can ask the helpful people at https://terra.fyralabs.com/ to help package delta chat and they'll provide fast updates as well as work on maintaining the package without the delta chat teams assistance, allowing for less work on your end.
