### ISSUE TITLE
Tweaks to leave group

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#432]
When you have left a group it remains in the list (which is by design), but you can still do `Leave group` again, which is a no operation. It should be removed. Also, there's no way to add yourself to the group again.

![screenshot from 2018-12-13 13-05-14](https://user-images.githubusercontent.com/308049/49937773-26137300-fed8-11e8-829e-bc9e3d73cb08.png)

**Comment by karissa** [comment]
I see the same behavior in both android-dev and the older android version, closing
