### ISSUE TITLE
Image is cropped vertically in full size view

### ISSUE THREAD

**Issue by iequidoo** [deltachat/deltachat-desktop#4320]
- Operating System (Linux/Mac/Windows/iOS/Android): Debian GNU/Linux 12.1, KDE 5
- Delta Chat Version: 1.47.1
- Actual behavior: The top and the bottom of images are a bit cropped in full size view. I can see them if i move an image up or down though.
- Steps to reproduce the problem: Click on an image in a chat to open full size view
![image](https://github.com/user-attachments/assets/505749d0-4f9f-4e5b-b6be-9ab6cf5eec00)

**Comment by nicodh** [comment]
I can confirm this. Probably related to blueprint removal

**Comment by WofWca** [comment]
Based on testing, this seems to have been fixed by https://github.com/deltachat/deltachat-desktop/pull/4385

**Comment by WofWca** [comment]
Hmmm, actually not. A few pixels still get cropped out.
