### ISSUE TITLE
Tweaks to Autocrypt setup

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#434]
* it should be under `Advanced` in settings
* the ux on desktop is slightly different compared to android, in android you have the `Send Autocrypt Setup Message` button, but on desktop it's `Initiate Key Transfer`

**Comment by hpk42** [comment]
On Thu, Dec 13, 2018 at 04:25 -0800, Lars-Magnus Skog wrote:

> * it should be under `Advanced` in settings
> * the ux is slightly different. In android you have the `Send Autocrypt Setup Message` button, but on desktop it's `Initiate Key Transfer`

"Send Autocrypt Setup Message" is much better.  In particular the word "key" should 
not appear in a primary UI (somewhere in advanced settings it's more ok).

**Comment by r10s** [comment]
i think, these sort of problems will disappear when the shared translation repo becomes more used :)
