### ISSUE TITLE
"Add s Second Device" - add an option like Text Code as QR code alternative

### ISSUE THREAD

**Issue by RooneyMcNibNug** [deltachat/deltachat-desktop#4346]
Thanks for all the work you do on this app.

I've noticed that the Delta Chat Desktop application does not allow any alternative means to adding a second device besides either scanning a QR code or uploading a screenshot of a QR code (with the second option, I am experiencing https://github.com/deltachat/deltachat-desktop/issues/4171, fwiw)

I think it would be hugely impactful to allow an alternative means to add a device besides the QR code - something like extracting the Text Code from the QR generated by the device and presenting it in the UI for the user to either copy and send to the device they are adding or even manually put it in.

I think this would benefit users - the fact that it is an additional choice you are giving them, or the fact that it would benefit in a situation where someone does not have a functioning camera to use (as an addition to the Screenshot feature for the QR code). There might also be some arguments here around offering some better accessibility.

**Comment by r10s** [comment]
thank you for your idea, however, this issue tracker is about bugs and actionable things agreed on being done soon.

please add feature proposals to the forum at https://support.delta.chat/c/features/6 - you can log in with your github account there.

there is also a better outreach as the discussion is not related to only one OS.

thanks :)
