### ISSUE TITLE
[Discussion] Advanced settings ux

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#435]
Should this be yet another dialog, or is it enough with a collapsing section in the current settings dialog, similar to what we do at the Login screen?

**Comment by Jikstra** [comment]
I think a pragmatic solution for the beginning would be a collapsing thing, but in the long run i would go for some back/forth thing as it's on android. That if you open settings you have the different categories, if you click on one, the dialog screen changes and a back button appears in the dialog header or something like that. That's at least my idea for it.

**Comment by ralphtheninja** [comment]
I'm not sure if it's worth it to make a pragmatic solution first.

**Comment by Jikstra** [comment]
A pragmatic solution would be very easy as we can just use the collapse element of blueprintjs. But we can also go for the real thing directly.

**Comment by karissa** [comment]
Are you talking about related to: https://github.com/deltachat/deltachat-desktop/issues/249 ?

I think we could do something similar to what we do for the key transfer, which is a dialog on top of a dialog. It actually seems to work pretty well in a similar manner as being able to hit 'back' and go to the settings screen.
Later we can refactor these to not be dialogs but instead panels.

**Comment by ralphtheninja** [comment]
> Are you talking about related to: #249 ?

Yes and other advanced settings.



> I think we could do something similar to what we do for the key transfer, which is a dialog on top of a dialog. It actually seems to work pretty well in a similar manner as being able to hit 'back' and go to the settings screen.
> Later we can refactor these to not be dialogs but instead panels.

Sounds good. But we're not following the android app. And to be honest I don't think we should follow it blindly either. At the moment, if you want to trigger the Autocrypt Setup Message, you have to click _four_ times in android and I think it's too much.

**Comment by karissa** [comment]
I agree
