### ISSUE TITLE
webxdc.sendUpdate(update) should work without requiring 'descr' to be passed. 

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#4359]
On Android and iOS apps don't need to pass in a `descr` argument. 
Desktop should do the same so we can eventually remove it from the spec.

**Comment by nicodh** [comment]
It shows a deprecation warning in console now and just passes an empty string to core, since in rpc.sendWebxdcStatusUpdate the parameter is still mandatory in core 1.151.2

**Comment by hpk42** [comment]
thx
