### ISSUE TITLE
cancelling profile creation with "Esc" not fully working

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#4365]
when cancelling profile creation with the "Back Arrow", the dialog is closed, the account in creation is removed, and one is back in the last profile - all as expected.

however, using the "Esc" key instead, the account in creation is not removed and one is not back in the last profile. also the dialog is only removed partly, the background images stays:

<img width="895" alt="Screenshot 2024-11-27 at 20 49 17" src="https://github.com/user-attachments/assets/76a7356d-7392-4ebf-a70e-c4c20af8d4d0">

weirdly, the dialog comes back when the window is resized

**Comment by WofWca** [comment]
I did some debugging. Looks like on first Esc press it invokes `onCancel`, which gets prevented, but the second Esc press invokes `onCancel` _and_ `onClose`. And `onClose` does close dialog.

https://github.com/deltachat/deltachat-desktop/blob/1abfd305c4a720250f8f0b84edeb1ce553e75fa4/packages/frontend/src/components/Dialog/Dialog.tsx#L61-L70

**Comment by WofWca** [comment]
I discovered that on the second `cancel` event `ev.cancelable === false`, unlike on the first one.

Another hack I can suggest is to `dialogRef.current.showModal()` immediately after such an event.

**Comment by WofWca** [comment]
Oh, and another thing: maybe we shouldn't utilize `showModal` for such un-closable dialogs at all? Looks like we only want `showModal` for the backdrop:

https://github.com/deltachat/deltachat-desktop/blob/5e07d5eb3c108e8b40a1f30ca10ce61faaf7cc4b/packages/frontend/src/components/Dialog/Dialog.tsx#L73-L75

But I guess we still want other contents to be non-interactive, so IDK...

**Comment by WofWca** [comment]
Let's reopen to track other such dialogs as suggested in https://github.com/deltachat/deltachat-desktop/pull/4396#pullrequestreview-2486926858
