### ISSUE TITLE
Pressing Ctrl+Up in read-only mailing lists sets a draft

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop#4389]
Ctrl+Up selects next message for the quote, but this should not work if the chat is read only (can send = false).

This happens in chats with github notifications.

**Comment by WofWca** [comment]
Also happens in "Device Messages"

At least it's possible to remove it with another Ctrl + Down.

**Comment by nicodh** [comment]
For me it works as expected. At least in device messages:


https://github.com/user-attachments/assets/be9068e6-8ad5-4e84-ba9c-b2402981aa5a

**Comment by WofWca** [comment]
I see the same that you see @nicodh. I wouldn't call it "expected" though. The draft is still shown in chat list, and this highlight is displayed.
