### ISSUE TITLE
webxdc selfName is set to selfAddr

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#4392]
in 1.49.0, webxdc's selfName is set to selfAddr.

for reproducing, add eg. a calendar event or use live-chat and look at the name displayed in the app.

in 1.48 it seems okay.

might be introduced by https://github.com/deltachat/deltachat-desktop/pull/4380

**Comment by nicodh** [comment]
Can't reproduce. Wehre do you see the selfAddr (which would mean the email IIRC )

![image](https://github.com/user-attachments/assets/385f5e2d-b983-40e6-a768-3ed2cd0d7b8a)

Same in LiveChat

![image](https://github.com/user-attachments/assets/51eb0d65-1f75-49c2-a397-85a21382c7ca)

**Comment by r10s** [comment]
this is how the live chat looked for me as well as for @hpk42 yesterday, same for calendar:

![Screenshot 2024-12-06 at 14 22 38](https://github.com/user-attachments/assets/30c29578-a748-4f04-940d-d59fecca77f1)



however, i also cannot reproduce that any longer. the account was the same profile, with "r10s" set as displayname "foreever".

holger and me played around with broadcast and webxdc before, however, so maybe that brought things out of control.

so, let's close this issue, if it happens again, we can reopen
