### ISSUE TITLE
Reduce size of node_modules in shipped debian/arch packages

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#441]
I looked into the app.asar file (you can do it with the asar utility, simply run `$ asar list app.asar`) and saw that there are quite some files which aren't needed in it. An incomplete list:
- /conversations/{ts|stylesheets|docs}/**/*
- /bin
- /.tx
- /.github
- /test
- /*.md

Can we somehow tell electron builder to not pull them in?

**Comment by ralphtheninja** [comment]
Yes, we already do this. Why not pull in `/*.md`?

**Comment by karissa** [comment]
these files are relatively small in whole, no?

**Comment by ralphtheninja** [comment]
> these files are relatively small in whole, no?

Yah, makes no difference size wise.

**Comment by Jikstra** [comment]
> Why not pull in /*.md?

It's not needed? And you can't really open them as they're in a weird archive.

It's not really important to remove them from the package as they aren't really making a difference size wise, we can close this issue.

**Comment by Jikstra** [comment]
Investigated this a bit more, the size of node_modules in the latest debian package is 80mb. Without electron ^^. 
The 20 biggest files are:
```
2,5M    ./intl-relativeformat/dist/intl-relativeformat-with-locales.min.js.map
2,1M    ./intl-relativeformat/dist/intl-relativeformat-with-locales.js.map
1,3M    ./deltachat-node/prebuilds/linux-x64/electron-napi.node
1,2M    ./deltachat-node/prebuilds/linux-x64/node-napi.node
1,2M    ./deltachat-node/prebuilds/linux-x64/electron-napi.node.bak
804K    ./intl-relativeformat/dist/intl-relativeformat-with-locales.js
728K    ./intl-relativeformat/lib/locales.js
712K    ./react-dom/umd/react-dom.development.js
708K    ./react-dom/cjs/react-dom.development.js
676K    ./intl-relativeformat/dist/intl-relativeformat-with-locales.min.js
540K    ./google-libphonenumber/dist/libphonenumber.js
528K    ./lodash/lodash.js
516K    ./moment/min/moment-with-locales.js
444K    ./intl-messageformat/dist/intl-messageformat-with-locales.min.js.map
388K    ./@blueprintjs/icons/dist/icons.bundle.js
376K    ./intl-relativeformat/dist/intl-relativeformat.min.js.map
376K    ./intl-messageformat/dist/intl-messageformat-with-locales.js.map
372K    ./moment/min/locales.js
348K    ./@blueprintjs/icons/src/generated/iconSvgPaths.ts
348K    ./@blueprintjs/icons/lib/esm/generated/iconSvgPaths.js
```

There are quite some redundant files, .map, .ts... i think we can reduce this a lot. Maybe even do some treeshaking. On arch we're not putting electron in the package because there's an own electron package which is quite recent. So lowering the package size is a good way to make deltachat a bit lighter.

**Comment by ralphtheninja** [comment]
We should try and automate this somehow and also set a limit. If we don't, we will keep optimizing this for all eternity without getting any bang for the buck.

**Comment by karissa** [comment]
I feel like this is nice to have but not crucial at this stage since like @ralphtheninja says we could optimize this a lot and still only get a few MB gain

**Comment by Jikstra** [comment]
Closing this in favor of https://github.com/deltachat/deltachat-desktop/issues/594 and https://github.com/deltachat/deltachat-desktop/pull/601
