### ISSUE TITLE
Dialog styling

### ISSUE THREAD

**Issue by karissa** [deltachat/deltachat-desktop#442]
Would be great to have some new styles for the dialogs, they are looking sad. Perhaps creating a `Dialog` component that wraps the dialogs rendered in the Controller class, inside `dialogs/index.js`

**Comment by nicodh** [comment]
I'm not sure if the dialogs still look as "sad" as they did when this issue was created, so maybe it's obsolete?

**Comment by Simon-Laux** [comment]
I close this because @Jikstra did restyle the dialogs https://github.com/deltachat/deltachat-desktop/pull/884
please reopen this if they still look sad.
