### ISSUE TITLE
Put in system tray on close (Background Mode)?

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#445]
An option to put it in the system tray instead of completely closing it would be cool.
Telegram and Discord (also skype, but that application is a pain to quit) do that.

- [ ] Tray icon with menu

- [ ] Don't quit on close, close only the window

- [ ] Make a setting to disable the tray icon / background mode

**Comment by Simon-Laux** [comment]
https://electronjs.org/docs/api/tray

**Comment by Simon-Laux** [comment]
Yeah lets wait on opinions on that one first.
Also Thunderbird doesn't do a tray icon.

**Comment by karissa** [comment]
+1 on the "wishlist" feature list

**Comment by Jikstra** [comment]
@Simon-Laux in case you're still bored, this could be a nice feature?

**Comment by Jikstra** [comment]
Closing as no one works on this currently

**Comment by radasbona** [comment]
The Tray Feature is needed very much. (UbuntuMate)

**Comment by r10s** [comment]
@radasbona i totally agree and i think everyone here would like to have this implemented.

however, this issue tracker is about bugs and to track things someone is currently working on. for feature requests and discussions, please use our forum at https://support.delta.chat
