### ISSUE TITLE
double checkmark is not shown on read

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#447]
Error in console is:
GET file:///home/simon/Documents/Projects/delta-chat-desktop/deltachat-desktop/images/double-check.svg

Update:
After I did the complete `npm run build` a checkmark is shown (as @ralphtheninja recomended), but not the double one.

**Comment by Simon-Laux** [comment]
@Jikstra

**Comment by ralphtheninja** [comment]
Have you rebuilt lately? This was changed to `sent.svg`.

**Comment by Simon-Laux** [comment]
Now there is one checkmark - Is that how it should behave?

**Comment by Simon-Laux** [comment]
shouldn't there be a double checkmark on seen? as read indicator?

**Comment by ralphtheninja** [comment]
> Now there is one check mark - Is that how it should behave?

No, you're right. Something is borked here for sure.

**Comment by ralphtheninja** [comment]
Hmm, it works on my machine:

![screenshot from 2018-12-16 02-44-37](https://user-images.githubusercontent.com/308049/50049104-9db1ef80-00dc-11e9-8bc4-2f453f19285a.png)

The double checkmark is the `images/read.svg` file.

**Comment by ralphtheninja** [comment]
> Error in console is:
> GET file:///home/simon/Documents/Projects/delta-chat-desktop/deltachat-desktop/images/double-check.svg

If I `git grep double-check` it's not referenced from code.

**Comment by Simon-Laux** [comment]
It's strange the css class is `...--delivered` on messages I can say for sure that they were read

**Comment by ralphtheninja** [comment]
@Simon-Laux What do you get when doing `git grep double-check`?

**Comment by Simon-Laux** [comment]
@ralphtheninja I get nothing - empty result

**Comment by ralphtheninja** [comment]
> @ralphtheninja I get nothing - empty result

So it _must_ be somewhere in your `static/bundle.js`

**Comment by Simon-Laux** [comment]
It's not about the image file anymore. The wrong class is applied, It could be anywhere, I don't found out more until now.

**Comment by Simon-Laux** [comment]
At the moment it seems to be something with the core... Is there any step I need to take to update it?

**Comment by ralphtheninja** [comment]
If `git status -s` doesn't give you a `M` on `deltachat-core` there's no need to update. If it does, then do `npm run submodule`.

**Comment by Simon-Laux** [comment]
Do I have to clone deltachat-core to do that?

**Comment by ralphtheninja** [comment]
It's a git submodule, so nope.

**Comment by ralphtheninja** [comment]
@Simon-Laux Oh damn, forget what I just said. This is desktop *bonks his head*.

**Comment by ralphtheninja** [comment]
Why would this have anything to do with core? :smile:

**Comment by Simon-Laux** [comment]
`To whom are you sending the messages?`

- To my another address of me
- Old messages that had the read state before 

`Does that account send back read receipts or not?`
Yes it should.
`Which client are you using for the recipient?`
It's the same desktop client, for the old messages I can't exactly say (the chat with @hpk42  as example)

Maybe you can give me one of your addresses for further testing?

**Comment by ralphtheninja** [comment]
> It's the same desktop client

This seems to be the problem. The desktop is not sending read receipts. I just tested it by sending a message from the android app (old version) and when I read the message on desktop, the android app doesn't get the double check mark.

**Comment by ralphtheninja** [comment]
@Simon-Laux You can chat with `ralphtheninja@deltachat.net`.

**Comment by karissa** [comment]
So we are doing `markSeen` on all the messages, https://github.com/deltachat/deltachat-desktop/blob/master/src/main/deltachat.js#L461

so this should be doing it, right? @r10s
