### ISSUE TITLE
Contact Request are broken

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#449]
Accepting does nothing and instead of the email `$1` is shown:

![cr_bug](https://user-images.githubusercontent.com/18725968/50054442-1ac38000-0142-11e9-816f-e31b3d9eafdf.png)

**Comment by Simon-Laux** [comment]
Thanks that fixed the visual bug, but the chat still doesn't show up on accept

**Comment by Simon-Laux** [comment]
```json
"chatWith": {
    "message": "Chat with $1$?"
  }
```

**Comment by ralphtheninja** [comment]
@karissa maybe broke it while refactoring *shrugs*. It has to be investigated.

**Comment by karissa** [comment]
yes it broke with the refactoring
