### ISSUE TITLE
mark read refinements

### ISSUE THREAD

**Issue by karissa** [deltachat/deltachat-desktop#458]
Messages are marked read as they are rendered, not read. This is *close* but not exact.

The issue: in theory if A sends B 20 messages in a row, it could say that B read the last 20, but only 10 showed up on the screen. This would happen if the my screen is small or the messages are large and B didn't scroll up.

Instead we could only mark messages read from the frontend, once the message comes into view using an asyncronous call.

**Comment by ralphtheninja** [comment]
So I guess this is something determined from the view back to the model? I.e. if we have _rendered_ a message and it had a certain state (not read yet), we should trigger mark seen?

**Comment by karissa** [comment]
yes that's right

**Comment by nicodh** [comment]
Moded to task list in refactor message rendering
