### ISSUE TITLE
Autocrypt Key Transfer input not showing the first two digits

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#467]
If i remember it correctly, on android the first two digits are shown, maybe @r10s can give you some insight. This is not very important.

**Comment by hpk42** [comment]
On Wed, Dec 19, 2018 at 12:15 -0800, Jikstra wrote:
> If i remember it correctly, on android the first two digits are shown, maybe @r10s can give you some insight. This is not very important.

yes, this is an UX twist that IIUC vincent and dkg introduced (it's autocrypt). 
Apparently helps with typing in the right code in case you send more than one etc.

**Comment by r10s** [comment]
@Jikstra yip, would be nice to have. you can get these two digits from a message that is identified as an ASM using [dc_msg_get_setupcodebegin()](https://c.delta.chat/classdc__msg__t.html#a677bca5655a8cc9f7a838fa588562d12)
