### ISSUE TITLE
Media view: Open download dialog directly on unknown documents

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#472]
When clicking on a document you are shown a download button. If you click on that you are shown the download dialog. Suggestion is to show the download dialog directly to minimize clicks.

![screenshot from 2018-12-21 00-06-31](https://user-images.githubusercontent.com/308049/50315829-872cdf00-04b4-11e9-98cb-8a89094f81fb.png)

**Comment by karissa** [comment]
We would just need to figure out all the kinds of documents that are viewable, or maybe just immediately download all `documents`. This could be likely handled in the `RenderMedia` dialog?
