### ISSUE TITLE
Emoji menu popup

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#475]
For sending emojis.
It would be even better when we would additionaly support the `:+1:` syntax/format in messenges.

**Comment by ralphtheninja** [comment]
@Simon-Laux I personally have no preference. I'd just try one that works :) I'm sure @Jikstra and @karissa have better input.

**Comment by Simon-Laux** [comment]
#490

**Comment by ralphtheninja** [comment]
@dignifiedquire mentioned https://www.npmjs.com/package/emoji-mart on irc (which seems we already mentioned)
