### ISSUE TITLE
Chat scrolls not to completely to bottom if pictures are present

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#477]
Probably its when pictures get loaded and grow in height after scrolling to the bottom.

A possible solution could be to use a bigger "skeleton" image placeholder that shrinks to the right size after the image is loaded.

**Comment by ralphtheninja** [comment]
I've also noticed this.

**Comment by nicodh** [comment]
Can't reproduce this. Maybe it's obsolete?

**Comment by nicodh** [comment]
@ralphtheninja @Simon-Laux 
if you also can't reproduce this anymore I will close the issue

**Comment by ralphtheninja** [comment]
I can still reproduce.
