### ISSUE TITLE
No chats, no Divider

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#482]
![no_chats_no_divider](https://user-images.githubusercontent.com/18725968/50459903-36aff880-0970-11e9-929c-900167654c40.png)

**Comment by Simon-Laux** [comment]
Ah just noticed that you don't even have a divider with chats... although the scrollbar acts like one...
Nevertheless we need a divider IMHO.

**Comment by Simon-Laux** [comment]
@Jikstra

**Comment by ralphtheninja** [comment]
Agreed. We need a divider regardless if there are chats or not.
