### ISSUE TITLE
Emojis in input field are displayed as tofu

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#483]

**Comment by Jikstra** [comment]
Adding for example https://emojipedia.org/see-no-evil-monkey/ in the ComposerInput adds a []. Sending it works though.

**Comment by ralphtheninja** [comment]
What's the problem here? Tofu what? :)

**Comment by Simon-Laux** [comment]
![e1](https://user-images.githubusercontent.com/18725968/50708029-2c25eb00-1063-11e9-8f27-d4bacdba7c70.png)
![e2](https://user-images.githubusercontent.com/18725968/50708030-2cbe8180-1063-11e9-8dc0-a99ec8d2c19d.png)

Google noto color emoji as fallback font does the trick - but its also an additional 6mb.
Also the other emojis are rendered using a different method (a function that replaces them with images)

**Comment by ralphtheninja** [comment]
Maybe we can use google noto for the other emoji stuff as well?

**Comment by ralphtheninja** [comment]
> Google noto color emoji as fallback font does the trick - but its also an additional 6mb.

I think it's fine with extra 6Mb.

**Comment by Simon-Laux** [comment]
The thing is that the emojis should look alike on each platform...  also we should test if the colored emoji font works on mac and windows (in electron)

**Comment by Simon-Laux** [comment]
Because there is a notice[ that it doesn't work on mac and windows natively](https://www.google.com/get/noto/help/emoji/) - which on the other hand is a other thing than using it as webfont in electron.
