### ISSUE TITLE
add full keyboard controll 

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#488]
Challenges:
- [ ] switch chat / navigate chatlist
- [ ] using menus
- [ ] scroll with (page up) and (page down) when selecting chat in chatview

Shortcuts:
- [ ] New Chat `Ctrl`+ `N`

If you have suggestions for this list post them below and I'll update this list.

**Comment by ralphtheninja** [comment]
> If you have suggestions for this list post them below and I'll update this list.

Or just edit your post :)

**Comment by Simon-Laux** [comment]
yeah that's also an option

**Comment by ralphtheninja** [comment]
I'd personally want:

* `ctrl + n` next chat
* `ctrl + p` previous chat

Maybe have `ctrl + shift + n` to create new chat?

**Comment by Simon-Laux** [comment]
https://reactjs.org/docs/accessibility.html#the-keyboard

**Comment by Jikstra** [comment]
Closing because currently no one works on this, but highly appreciate full keyboard control
