### ISSUE TITLE
Add github emoji syntax support via : (Git Style)

### ISSUE THREAD

**Issue by IHateMicroSoft** [deltachat/deltachat-desktop#490]
See here: https://gist.github.com/rxaviers/7360908

**Comment by Simon-Laux** [comment]
#475 #483

**Comment by Jikstra** [comment]
We try to track feature requests in the forum, if there's not such a feature request yet, please open one :)

**Comment by ralphtheninja** [comment]
@Simon-Laux This can be closes, right?

**Comment by Simon-Laux** [comment]
Technically yes, though one could argue that we only have half of it because we don't have suggestions yet.
