### ISSUE TITLE
Add markdown support

### ISSUE THREAD

**Issue by IHateMicroSoft** [deltachat/deltachat-desktop#491]
See here: https://en.wikipedia.org/wiki/Markdown

**Comment by Simon-Laux** [comment]
But we don't want full markdown -> as example links, tables and headings aren't things we need
I think you want mostly the basic stuff like lists, bold, underline, italics? also \`code\` might be useful

**Comment by muelli** [comment]
That may be more readable and easier to implement using Restructured Text.

**Comment by r10s** [comment]
i would postpone the markdown support, see https://github.com/deltachat/deltachat-desktop/issues/536#issuecomment-453566087

**Comment by Jikstra** [comment]
We try to track feature requests in the forum, if there's not such a feature request yet, please open one :)
