### ISSUE TITLE
Update electron to v3.0.0

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#50]
Release notes here https://electronjs.org/blog/electron-3-0

I don't know if we are affected by breaking changes or not.

**Comment by ralphtheninja** [comment]
Actually, I'm re-opening this. I've got some information from @flub so want to re-use this issue for that purpose ;)

From irc:

```
<@flub> so btw, for the electron v3 case the solution is to install the same openssl 
version as electron is built with onto the system (/usr/local should be fine) before 
building libdeltachat.so and *not* use --wrap-mode=forcefallback
```

**Comment by Jikstra** [comment]
What's blocking us from switchting to electron v3?

**Comment by ralphtheninja** [comment]
@Jikstra Nothing is blocking us from switching afaik.

**Comment by ralphtheninja** [comment]
Re-opening this, since it was reverted due to problems on Debian.

**Comment by ralphtheninja** [comment]
Closing again :wink:
