### ISSUE TITLE
Make initial login more helpful

### ISSUE THREAD

**Issue by obestwalter** [deltachat/deltachat-desktop#503]
- Platform (linux):
- Delta Chat Desktop Version: current master

Currently the first login screen might be a bit confusing for newcomers as it not clear what you actually need to login to (it might be some delta chat account that I am supposed to create somewhere else first).

To make it more clear a formulation like "Login with an existing mail account (use your mail credentials here)" might be better.

![scrot](https://user-images.githubusercontent.com/263007/50548046-45373200-0c46-11e9-9aa9-6d60ae966d01.png)

**Comment by Jikstra** [comment]
I think we should add an intro like we have it on android.
