### ISSUE TITLE
Improve install instructions in README

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#504]
- [ ] Mac
- [ ] Linux
  - [ ] Arch (with AUR)
  - [x] Generic linux (`.AppImage` and `.deb`)
- [x] ~~Windows?!~~
- [x] How to install from source

**Comment by ralphtheninja** [comment]
A lot of things can be done in the README. The `Troubleshooting` section should be a separate section outside `How to Contribute`.

**Comment by ralphtheninja** [comment]
I'd start by describing how to install on `Arch` and `Debian` and leave out `Mac` for now until we really do support it and the same goes for `Windows`. But we can leave this issue open to track all scenarios. Will address `Debian` from https://github.com/deltachat/deltachat-desktop/pull/552

**Comment by ralphtheninja** [comment]
I scratched ~~Windows~~ since we can't even run it there yet.

**Comment by Jikstra** [comment]
> @Jikstra Mind adding some instructions for how to run it on Arch? I can take care of Mac once we have done some testing and have a new release out.

I will do so :)

**Comment by homdx** [comment]
> I'd start by describing how to install on `Arch` and `Debian` and leave out `Mac` for now until we really do support it and the same goes for `Windows`. But we can leave this issue open to track all scenarios. Will address `Debian` and `Install from Source` in #552

Builded binary deltachat-core need testing:
[deltachat/deltachat-core#306 (comment)](https://github.com/deltachat/deltachat-core/issues/306#issuecomment-461026117)
Possible problems: Windows does not support utf-8 coding, windows uses ansi encoding. (need fix).
