### ISSUE TITLE
Implement imap folder options from android-dev

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#508]
we currently have in android and need for desktop:

- watch inbox
- watch DeltaChat folder
- watch Sent Folder
- move messages from Inbox to DeltaChat 

it's a little unclear what we do as defaults for the january releases ... but this is a separate issue.

**Comment by webratte** [comment]
I think this is fixed in current version 0.98.1-preview.

**Comment by ralphtheninja** [comment]
![screenshot from 2019-01-06 13-32-43](https://user-images.githubusercontent.com/308049/50736013-98b1fe80-11b7-11e9-8432-d735f020b04f.png)
