### ISSUE TITLE
Clean up conversations

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#509]
Wasn't `Message.tsx` converted to .js? If so, it should be removed. Very annoying to search for e.g. labels and get multiple hits.

cc @Jikstra 

TODO

- [x] Remove `Message.tsx` (already moved to js)
  - [x] Remove `MessageDetail.tsx` (move to js first, needed by custom `src/renderer/components/dialogs/MessageDetail.js`)
  - [x] Remove `LightboxGallery.tsx` (not used)
  - [x] Remove `MessageBody.tsx` (move to js first)
  - [x] Remove `Quote.tsx` (move to js first)
  - [x] Remove `EmbeddedContact.tsx` (move to js first)
  - [x] Remove `Timestamp.tsx` (move to js first)
- [x] Remove `ExpireTimer.tsx` (once `Message.tsx` is removed)
- [x] Remove `ContactName.tsx` (already moved to js)
  - [x] Remove `ConversationListItem.tsx` (not used)
  - [x] Remove `GroupNotification.tsx` (not used)
  - [x] Remove `Quote.tsx` (move to js first)
  - [x] Remove `SafetyNumberNotification.tsx` (not used)
  - [x] Remove `TimerNotification.tsx` (not used)
  - [x] Remove `VerificationNotification.tsx` (not used)

Some entries are duplicate here, since e.g. `Message` depends on `Quote` and so does `ContactName`.

**Comment by Jikstra** [comment]
Yes this should be removed. We should also think about if we want to keep the converted to js files in the conversations folder or really move them to our src.

**Comment by ralphtheninja** [comment]
> We should also think about if we want to keep the converted to js files in the conversations folder or really move them to our src.

As they are converted to js we could move them to `src/renderer/components/conversation/`? This way it's both part of our source and indicates where the code originates from.

**Comment by ralphtheninja** [comment]
So there seems to be more files than just `Message.tsx` (also, what's the difference between .tsx and .ts?)

**Comment by ralphtheninja** [comment]
Oh man this is a mess.

**Comment by ralphtheninja** [comment]
Made a quick plan. I think it makes sense to move over what we need and gradually strangle the `conversations` folder until it's no longer needed.

**Comment by Jikstra** [comment]
> Made a quick plan. I think it makes sense to move over what we need and gradually strangle the conversations folder until it's no longer needed.

I like it.
