### ISSUE TITLE
Escaped newline characters in language resources

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#510]
![screenshot from 2019-01-01 05-08-41](https://user-images.githubusercontent.com/308049/50570258-68b3c700-0d83-11e9-9bba-4dd1831ff573.png)

Wait until _after_ the translations are done and merged.

**Comment by ralphtheninja** [comment]
And

![screenshot from 2019-01-01 05-42-35](https://user-images.githubusercontent.com/308049/50570354-15904300-0d88-11e9-9ef2-96445fa7e862.png)

**Comment by Jikstra** [comment]
Does this only happen in the android-translations branch?

> It seems the newline characters are escaped in the translations. Why?

Good question. Maybe the converter does it?

**Comment by ralphtheninja** [comment]
> I'm also unsure if we need to replace the `\n` with a `<br>`.

Aye, probably not needed.

**Comment by ralphtheninja** [comment]
> Good question. Maybe the converter does it?

Aye, it's done somewhere inside `xml2js` afaict.
