### ISSUE TITLE
Copying & Pasting a message result in the message + some letters of the beginning of the message

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#514]
Original message: `Ok, I'm mostly done with the translations now, only a few tweaks left`
Pasted message: `Ok, I'm mostly done with the translations now, only a few tweaks leftOk, I'`

**Comment by Simon-Laux** [comment]
I couldn't reproduce this with your sample sentence. Do you have other examples to test?

**Comment by Jikstra** [comment]
This happens for me with every message, no matter what the text is.

**Comment by ralphtheninja** [comment]
@Jikstra Are you using ctrl+c and ctrl+v or pasting with middle button?

**Comment by Jikstra** [comment]
@ralphtheninja I use ctl+c & ctrl+v

![bug_copy_dc](https://user-images.githubusercontent.com/34889164/50726204-0acc0a00-110a-11e9-847d-5a7205089649.png)

**Comment by Jikstra** [comment]
Hmm not sure why, but currently i can't reproduce it. But @Simon-Laux said he had the same bug?

**Comment by Simon-Laux** [comment]
Yeah

**Comment by ralphtheninja** [comment]
I can't reproduce this to save my life.

**Comment by Jikstra** [comment]
I can reproduce this in groups but not in 1to1 chats. Dafuq. CSS seems to be the same for the message containers.

**Comment by ralphtheninja** [comment]
Finally managed to reproduce. It seems it's only possible when copy pasting in groups and only on messages that aren't from yourself. This is what differs a group and a 1-to-1 chat, since a message from someone else in a 1-to-1 chat doesn't contain the name at the top of the message. Now, why this would matter is another question.

**Comment by Jikstra** [comment]
But this insight clearifies this whole thing a lot, i think a good way to reproduce this is by hardcoding a message and trying to play around with the html.

**Comment by Simon-Laux** [comment]
I had it in an one 2 one chat, too while copy pasting my own messages

**Comment by ralphtheninja** [comment]
> I had it in an one 2 one chat, while copy pasting my own messages

Ok.

**Comment by Jikstra** [comment]
Interesting find: Can't reproduce it with electron4 branch. Same for you @ralphtheninja @Simon-Laux ?

Just for completion:
> try following, copy it from the right side by clicking above the text and pull it down until all is selected

**Comment by ralphtheninja** [comment]
Same here, cant' repro using electron 4. Merge?

**Comment by Jikstra** [comment]
> Same here, can't repro using electron 4. Merge?

Maybe yes. 
Pro: we can get rid of that queue hack in deltachat-node
Con: I have to bundle electron4 on arch then too, because currently only v3 is in the repos

**Comment by Jikstra** [comment]
Merged electronv4, this should be solved.
