### ISSUE TITLE
Use only the languages own language translation

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#516]
Currently we translate every language name to every other language which results in having german translated to "Deutsch, German, Allemand...". This doesn't help anyone to find the right language, as every german will recognize the "Deutsch" language string. This is also the behaviour the android version has.

**Comment by ralphtheninja** [comment]
Makes sense

**Comment by ralphtheninja** [comment]
So does this mean they shouldn't be translated at all?

**Comment by r10s** [comment]
> So does this mean they shouldn't be translated at all?

yes. i think this is not needed. for android, adding a language already requires to add the language name to https://github.com/deltachat/deltachat-android-ii/blob/master/res/values/arrays.xml#L7 - preferring the name in the locale (currently, the language names are added twice for locales in non-latin character sets, not sure if even this is needed, comes from signal) (how knows which language "Shqip" is? even if it uses latin characters :)

**Comment by ralphtheninja** [comment]
So how do we solve this practically? The strings essentially need to be hardcoded but still translated to their corresponding language.
