### ISSUE TITLE
Implement a way to have "experimental" language strings

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#517]

**Comment by ralphtheninja** [comment]
If we had a central repository for the translations, experimental strings would just be a branch in that repository.

**Comment by Jikstra** [comment]
Still i would prefer to have those experimental strings in this repository to allow creating a pr only against this repository and not against two. That's the "only" reason i want to have this.

**Comment by ralphtheninja** [comment]
> Still i would prefer to have those experimental strings in this repository to allow creating a pr only against this repository and not against two. That's the "only" reason i want to have this.

Yeah, makes sense.
