### ISSUE TITLE
desktop crashes on straight add contact

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#52]
v1.0.9. after logging, creating chat+contact (where i enter emailadr and name) there is a crash, see screenshot. 

![desktop-bug1](https://user-images.githubusercontent.com/73579/45804057-67222f80-bcbb-11e8-922b-cb042864a979.png)

**Comment by r10s** [comment]
maybe related: tried out to register delta 1.0.9 on _macOS High Sierra 10.13.4_: download and installation works like a charm, up to the setup dialog:
- a first click on the "Login" button does nothing, so i wait some ten minutes (might be the key generation took some time :)
- a second click on the "Login" button let the login window disappart without any comments.

**Comment by karissa** [comment]
@r10s key generation is being done in the main process in C so it shouldn't be any slower than a normal computer or phone.

**Comment by karissa** [comment]
should be fixed on latest master, i'll close this once we get a new version out

**Comment by hpk42** [comment]
@karissa wrt to @r10's reported issue: desktop is spearheading usage of delta-core in Apple/Laptop environment, so it's either a desktop, node or delta-core issue on this platform. Probably warrants a fresh issue, as it's unrelated to what i reported and what is fixed, i think.  I guess it's a good idea to keep usabiilty-issues open on the "ui" repos (desktop, android, ios) and reference delta-core/bindings issues if the problem needs to be fixed there.

**Comment by karissa** [comment]
this should be fixed now: https://github.com/deltachat/deltachat-desktop/commit/71e46308a7990fd09d02069c7bfb2a5dc154e7eb

**Comment by karissa** [comment]
r10s I nailed that down to incorrect credentials (or no internet connectivity) https://github.com/deltachat/deltachat-desktop/issues/61
