### ISSUE TITLE
Mark verified groups as experimental

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#523]
Verified groups is currently a experimental feature which might change in the future. We should indicate to the user that this can change in the current form.

**Comment by Jikstra** [comment]
This should be handled in the shared translations, not something for us to care about.

**Comment by ralphtheninja** [comment]
Cool. Lets leave it open until we have pulled in the updated translations.

**Comment by ralphtheninja** [comment]
So, who is making sure this happens? :)

**Comment by Jikstra** [comment]
Good question, i don't know how we can roll out a "replacement" of a already translated string. Maybe we need to introduce a new string and push it to tx? If so, we can just do that.

**Comment by r10s** [comment]
i think if we pick up the strings from the current strings.xml, it should be fine.

for desktop, i've removed the "verified" wording also from `show_qr_verify_code_desktop` and from otherwise deprecated strings.

**Comment by ralphtheninja** [comment]
When I try pulling the strings I don't get an update of `en.xml`.

**Comment by hpk42** [comment]
It's also a layout thing -- the "verified group" should be right-most and renamed to "Verified group (experimental)" or so, maybe with a little extra spacing? 
![vgroup](https://user-images.githubusercontent.com/73579/51503269-64a32400-1dda-11e9-8e84-ffe8bbde6626.png)
