### ISSUE TITLE
Implement watch deltachat folder & move to deltachat folder settings

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#526]
This needs:
- [x] ui settings
- [x] make bindings able to spawn/stop the threads on changing/loading the settings

**Comment by ralphtheninja** [comment]
Note that core doesn't have anything to do with threads, so this needs to go into the node bindings.

**Comment by ralphtheninja** [comment]
Also, lets have desktop drive the api in the node bindings, rather than the other way around.
