### ISSUE TITLE
saving credentials during desktop invocations

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#53]
Once i successfully login, i'd like my deltachat-desktop app to remember my credentials.  I am fine with storing the credentials in some default home-dir place.

**Comment by ralphtheninja** [comment]
@hpk42 It should be enough to remember last `addr` used, since that determines which folder the `deltachat-core` db is located and just open that db and configure should not be needed.

**Comment by karissa** [comment]
closing this in favor of #75
