### ISSUE TITLE
Dedicated Log View Window

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#539]
Moved out from #497 into its own issue.
The thing should become an extra electron windows/console for viewing the logs.
But not only logs - we would have tabs in it like in the chrome tools to include also other cool tools like as example an live translations editor

**Comment by Jikstra** [comment]
I don't like the idea of having an own log view window. I'm fine with having a settings -> advanced -> send log dialog which collects the current log, shows it in a editable thing and allows to cut out stuff before sending it to us or something like that but a dedicated window for logging + filtering features is too much in my opinion and not needed. Having the log levels + arguments to control those is enough in my opinion.
Keep it simple, stupid.

**Comment by ralphtheninja** [comment]
I agree. We have logging to file from both electron processes, with channel + timestamp + log level + arbitrary output. It's all we need at the moment.
