### ISSUE TITLE
Add option "Enter" send or line break

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-desktop#542]
Currently (v.0.98.1-preview), by pressing the enter key, the message will be sent.

I would like the behavior:
Enter key makes a line break.

A option for the enter key behavior would be great.

**Comment by ralphtheninja** [comment]
@webratte So you want to send the message by clicking the Send button instead?

**Comment by r10s** [comment]
afaik, `ctrl-enter` send the message on Telegram and Signal desktop clients while `enter` just adds a linebreak.
maybe we should go this way as well.

**Comment by webratte** [comment]
This sounds good to me.

**Comment by ralphtheninja** [comment]
> afaik, `ctrl-enter` sends the message on Telegram and Signal desktop clients while `enter` just adds a linebreak.> maybe we should go this way as well.

Good idea. Having configuration for every tiny detail is not ideal.

**Comment by webratte** [comment]
So there is no extra option needed and I still can click the send button 👍

**Comment by Jikstra** [comment]
> afaik, ctrl-enter sends the message on Telegram and Signal desktop clients while enter just adds a 
> linebreak.
> maybe we should go this way as well.

Telegram desktop actually allows to set this:
![screenshot_20190109_185208](https://user-images.githubusercontent.com/34889164/50918130-ab3e6900-143f-11e9-8200-bb0daa013812.png)

**Comment by ralphtheninja** [comment]
> Telegram desktop actually allows to set this:

I guess it makes sense to have this configured. Most chats have something similar and people might even expect this option.

**Comment by Jikstra** [comment]
This shouldn't be very hard, all we need to change is in Composer.js and add the option to settings (hardest part).
