### ISSUE TITLE
let input field grow up to 5 lines or more

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-desktop#543]
The input field should grow up if I enter a new line.
Maybe up to 5 lines or more if you think there is space enough (in android client it's currently 3 lines).

**Comment by ralphtheninja** [comment]
The current design is quite a mess to be honest. Before growing this thing we should consider rewriting the current page layout.

At the moment if you increase the height of the text area the whole page scrolls:

![screenshot from 2019-01-09 17-59-16](https://user-images.githubusercontent.com/308049/50915159-7975d400-1438-11e9-9105-6e7c17db2dfb.png)

I think the chat view to the right should have its own scrollbar. The entire area should never scroll. The textarea at the bottom of the chat view should just increase in size and the chat area adapts itself to whatever height the text area has.

I think `Keybase` solves this pretty nicely:

![screenshot from 2019-01-09 18-03-17](https://user-images.githubusercontent.com/308049/50915379-f86b0c80-1438-11e9-9756-c940eefe18b1.png)

![screenshot from 2019-01-09 18-03-42](https://user-images.githubusercontent.com/308049/50915384-fd2fc080-1438-11e9-975b-4d484bcbe401.png)

**Comment by Jikstra** [comment]
Currently we're extactly defining the height of the ChatView and the Composer (where you input the message). We need to change both heights to get this, which is messy. We should switch to a grid layout or something, everything else is quite hacky.

**Comment by ralphtheninja** [comment]
> We should switch to a grid layout or something, everything else is quite hacky.

Yes!
