### ISSUE TITLE
Edit verified group members, problem with non verified users

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#545]
* select verified group
* select edit group in menu
* add non verified group member
* click Save
* get error about trying to add a non bidirectionally verified member

Expected behavior: When editing a verified group you should only be allowed to see verified members _or_ you shouldn't be able to select them into the group in the first place.

**Comment by Jikstra** [comment]
I guess we only need to filter out non-verified members from the ContactList component. Shouldn't be too hard.

**Comment by r10s** [comment]
a list of verified-only contacts is available with [dc_get_contacts(DC_GCL_VERIFIED_ONLY)](https://c.delta.chat/classdc__context__t.html#a32f1458afcacf034148952305bf60abe)
