### ISSUE TITLE
Tweak css from conversations folder

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#553]
Current state:

```
$ tree conversations/
conversations/
├── build
│   └── manifest.css
└── stylesheets
    ├── _conversation.scss
    ├── _debugLog.scss
    ├── _emoji.scss
    ├── _global.scss
    ├── _index.scss
    ├── _lightbox.scss
    ├── manifest.scss
    ├── _mixins.scss
    ├── _modal.scss
    ├── _modules.scss
    ├── _options.scss
    ├── _progress.scss
    ├── _recorder.scss
    ├── _settings.scss
    └── _variables.scss
```

I propose we change it to:

```
$ tree css/
css/
├── _conversation.scss
├── _debugLog.scss
├── _emoji.scss
├── _global.scss
├── _index.scss
├── _lightbox.scss
├── manifest.scss
├── _mixins.scss
├── _modal.scss
├── _modules.scss
├── _options.scss
├── _progress.scss
├── _recorder.scss
├── _settings.scss
└── _variables.scss
```

Also, we should change the output file from `conversations/build/manifest.css` to e.g. `static/manifest.css`.

Another thing that I was wondering about, is why we load `manifest.css` using `insert-css`:

https://github.com/deltachat/deltachat-desktop/blob/f1bdc9ed43f6ed226af5f16bec59ecfb2b1a74d7/src/main/ipc.js#L58-L62

Why can't we just load it like any other css files from `main.html`?

**Comment by Simon-Laux** [comment]
We also should think about removing usused css and starting with #409 while were already at it

**Comment by Jikstra** [comment]
> We also should think about removing usused css and starting with #409 while were already at it

this might be hard as we can't really be sure if we need that css stuff or not depending on how good conversations was modularized. Maybe there are some tree shaking tools for css, but don't know much about that. 

I would propose another folder structure where we have all conversations related scss stuff in a own folder.
```
$ tree css/
css/
├── conversations
          ├── _conversation.scss
          ├── _debugLog.scss
          ├── _emoji.scss
          ├── _global.scss
          ├── _index.scss
          ├── _lightbox.scss
          ├── manifest.scss
          ├── _mixins.scss
          ├── _modal.scss
          ├── _modules.scss
          ├── _options.scss
          ├── _progress.scss
          ├── _recorder.scss
          ├── _settings.scss
          └── _variables.scss
```

This makes it clear that this is used from src/rendered/components/conversations/*
