### ISSUE TITLE
Settings -> Password/Login -> Shown password is incorrect

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#561]
The password shown in settings for the mail account is incorrect

EDIT:

Also, the dialog needs some tweaking.

- [ ] The first `Login with an existing e-mail account ..` should not be in here
- [ ] Email address is not shown
- [ ] ~~The `Login` button should not be here either~~ Nvm.

![screenshot from 2019-01-30 01-49-49](https://user-images.githubusercontent.com/308049/51950605-710a2b00-2431-11e9-9c20-06b6d0242470.png)

**Comment by ralphtheninja** [comment]
How is this `Login` button supposed to work? It's always disabled.

**Comment by ralphtheninja** [comment]
And why isn't the email shown? Why show a something disabled that doesn't display anything?

**Comment by ralphtheninja** [comment]
The password comes from here:

https://github.com/deltachat/deltachat-desktop/blob/db2764c4d1e377eeae67be232cbf7d8f390e7b41/src/renderer/components/dialogs/Settings.js#L6

Not sure what the idea was here.

cc @karissa

**Comment by karissa** [comment]
Ah yes. this is broken!

The email used to show up there. Not sure why it isn't anymore..?

This is the only case when the password is sent to the frontend and I am worried that it opens an attack vector from client-side javascript that otherwise wouldn't have access to this variable.

Perhaps if the person clicks the 'show password' box, the frontend removes the fake password so it isn't confusing to see some random password :)

**Comment by ralphtheninja** [comment]
> Perhaps if the person clicks the 'show password' box, the frontend removes the fake password so it isn't confusing to see some random password :)

Aaah, that's a good idea!

**Comment by nicodh** [comment]
I'm not sure what should be possible here. I assume:
- change SMTP/IMAP settings for an existing account
- change password for an existing account

1.  After changing the credentials, do I have to Login/Logout or will the core handle an "on-the-fly" change?

2. Should my real password be displayed here when I "unlock" the password field or should this just show something if you type a new password? If so, I suggest to show an empty field initially and once there a characters in the field show the unlock/lock button to switch both modes

**Comment by nicodh** [comment]
Added a PR for this #695 
still not sure about:
- shall we reveal account password here?
- shall we reveal IMAP/SMTP password here?
In Android app it is not possible to see the passwords...
But there are flags "showPasswordMail" & "showPasswordSend" in Login.js 
https://github.com/deltachat/deltachat-desktop/blob/master/src/renderer/components/Login.js#L20

**Comment by hpk42** [comment]
On Mon, Feb 25, 2019 at 02:58 -0800, Nico de Haen wrote:
> Added a PR for this #695 
> still not sure about:
> - shall we reveal account password here?
> - shall we reveal IMAP/SMTP password here?
> In Android app it is not possible to see the passwords...

in 0.100.0 on android it is possible to hit the "eye" icon and
see the passwords and i think it makes sense -- not sure what
is shown there for OAUTH2 support btw but that's a different issues ;)

**Comment by r10s** [comment]
> not sure what is shown there for OAUTH2 support btw but that's a different issues ;)

for oauth2 the login-token is shown (in fact, you can also do oauth2 manually by pasting it there and selecting oauth2 in the advanced options)
