### ISSUE TITLE
image message bubbles cropped on small window widths

### ISSUE THREAD

**Issue by violoncelloCH** [deltachat/deltachat-desktop#579]
- Platform (linux/mac/windows): linux
- Delta Chat Desktop Version: 0.98.1
- Expected behavior: message bubbles with images should be fully shown regardless the width of the window
- Actual behavior: message bubbles with images are cropped it the window is too small
- Steps to reproduce the problem: send an Image (on delta android) and resize the window to small widths
- Screenshots: 
![image](https://user-images.githubusercontent.com/22591354/51002748-92fc4600-1534-11e9-97c4-8b32396849d1.png)
![image](https://user-images.githubusercontent.com/22591354/51002765-a3acbc00-1534-11e9-8cf0-5d8de1a60192.png)

**Comment by violoncelloCH** [comment]
just remarked, that it get's horizontally scrollable in these cases...

**Comment by Jikstra** [comment]
Can't reproduce, i think it should be fixed.
