### ISSUE TITLE
.deb release problems on Ubuntu

### ISSUE THREAD

**Issue by sbadux** [deltachat/deltachat-desktop#58]
Hello,
I've installed the last version on Ubuntu 18.04 and found these problems:

1) The .deb file is really big (183MB). Can you try to reduce it?

2) The icon is not shown correctly on GNOME:
![schermata da 2018-09-24 21-08-42](https://user-images.githubusercontent.com/28478027/45973386-9bd91280-c03e-11e8-9728-3d9dd11de177.png)

3) The app correctly chose the system-language (italina) but the app is still in english. Can you please add the translation? In transifex all the strings are translated.

**Comment by karissa** [comment]
Thanks @sbadux ! Will get to this by the weekend.

**Comment by hpk42** [comment]
On Mon, Sep 24, 2018 at 12:16 -0700, sbadux wrote:
> Hello,
> I've installed the last version on Ubuntu 18.04 and found these problems:
> 
> 1) The .deb file is really big (183MB). Can you try to reduce it?

true, see https://github.com/deltachat/deltachat-desktop/issues/41

> 3) The app correctly chose the system-language (italina) but the app is still in english. Can you please add the translation? In transifex all the strings are translated.

there is no translation integration yet ASFAIK, and it will likely last a while
till they arrive.

**Comment by karissa** [comment]
@hpk42 there is translation integration.

**Comment by karissa** [comment]
point 3 fixed in https://github.com/deltachat/deltachat-desktop/commit/fc4dda6f274b4cfc8fbc357ac70b492cd14a68ff

**Comment by karissa** [comment]
since point 2 and 3 are fixed and point 1 is a duplicate, closing. thanks!

**Comment by sbadux** [comment]
Thanks a lot for the quick fix :)
