### ISSUE TITLE
change a (not sendet message) to draft like in android client

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-desktop#582]
- Platform (linux/mac/windows): Linux/Kubuntu
- Delta Chat Desktop Version: 0.98.2

- Expected behavior: 

If I switch to another chat,messages which not yet send, should stored as draft and the input field now should be empty, how it works in android client.

- Actual behavior: 

If I write a message to Alice and click on Bobs chat, the text will stay and can be send by accident to Bob,

- Steps to reproduce the problem:

-Open a chat to Alice. 
-Write a message e.g.: Alice, last night I never will forget. Bob should never know what happens last night.
-Don't send this message. 
-Click on Bobs chat, e.g to check his last message.
-Now (you are in hurry) click on the send button.

**Probably now you lost a friend ;-)**

**Comment by ralphtheninja** [comment]
Well, technically, Bob already lost his friend last night, but I see your point :wink:

**Comment by webratte** [comment]
Seams this is fixed in version 0.103.0-preview.
So I will close it.

Feel free to reopen if I'm wrong.
