### ISSUE TITLE
Simplify logging code

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#585]
The code for dealing with logging from the render process to the main process is a bit backwards. For instance

* the code for dealing with `LogVariants` are in two places, it should be enough with one place for this
* in each process we do `logger.setHandler()`, which is fine, but from the render side it does ipc to the `logHandler` (which writes to disk) but this in turn also does ipc back to the renderer to log to the console

I propose:

* the `logHandler` _only_ writes to file and does no ipc, it's invoked from the main process only, from two places, either directly (when logging from main process) or over ipc (when the render process logs)
* remove the ipc from the `logHandler` to the render process
* remove the ipc handler for the `'log'` event
* the log to console code is _already_ inside `src/logger.js`, which will log to either console
* remove `logDb`, not used for anything

The result would be:

* if you do e.g. `log.info()` in the main process -> it will go to log file and stdout
* if you do e.g. `log.info()` in the render process -> it will go to log file and browser console

**Comment by ralphtheninja** [comment]
Will tackle this once https://github.com/deltachat/deltachat-desktop/pull/598 has been merged

**Comment by Simon-Laux** [comment]
`logDb` was meant to be used for the dedicated log window, which we canceled for now. So its in fact an unused list and possible bad for memory usage so its good to remove it for now.
