### ISSUE TITLE
Get rid of dispatch and dispatchSync from ipc

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#591]
Currently we have a mixture of the following different ways of invoking methods in the `dc` controller:

* `ipcRender.send('foo', arg1, arg2)`
* `ipcRenderer.sendSync('foo', arg1, arg2)`
* `ipcRenderer.send('dispatch', 'foo', arg1, arg2)`
* `ipcRenderer.sendSync('dispatchSync', 'foo', arg1, arg2)`

The purpose of `'dispatch'` and `'dispatchSync'` is to have a convenient way of wrapping calls into the `dc` controller at the expense of readability.

I propose we remove them and be more explicit. it's clear then from `src/main/ipc.js` what different ipc methods we have and we restrict the render process to use that instead of opening up all methods in the `dc` context.

**Comment by ralphtheninja** [comment]
I'd say that the only downside is more boilerplate code, but I'd actually argue that it's something positive in this case.

**Comment by Jikstra** [comment]
I like this.
