### ISSUE TITLE
request things only as needed

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#6]
this is not an real issue, but more a reminder about how deltachat-core (and the deltachat-node bindings) should be used to request things.

@ralphtheninja @karissa feel free to close it :)

stumbling upon the [loadChats()](https://github.com/deltachat/deltachat-cli/blob/750c4c2470ac74fd09cb61618baed582b79e4822/state.js#L196) in IRC i have noted that this call would be an expensive call as it get the message lists for every chat. while this may be okay in an CLI program, for a desktop app, this may be too slow.

the idea is more to get the **list of all chats** via [dc_get_chatlist()](https://deltachat.github.io/api/classdc__context__t.html#a709a7b5b9b606d85f21e988e89d99fef) - without any listflags, see below - and to implement a "virtual list" or so (the count of chats is known).

only for the **items that are in view** (the list may have several hundreds chats), the UI should call [dc_chatlist_get_summary()](https://deltachat.github.io/api/classdc__chatlist__t.html#a7e155ba468613547743bf383600914d1) then. this function provides all elements needed for painting the item.

on a click of such an item, the UI should **change to the chat view** and get all messages from this view via [dc_get_chat_msgs()](https://deltachat.github.io/api/classdc__context__t.html#a51353ff6b85fa9278d2ec476c3c95eda). again, a "virtual list" is created (the count of messages is known) and for each messages that is scrolled into view, [dc_get_msg()](https://deltachat.github.io/api/classdc__context__t.html#a4fd6b4565081c558fcd6ff827f22cb01) is called then.

why no listflags? without listflags, dc_get_chatlist() adds the deaddrop and the archive "link" automatically as needed. the UI can just render these items differently then.
although the deaddrop link is currently always the first entry and only present on new messages, there is the rough idea that it can be optionally always present and sorted into the list by date. rendering the deaddrop in the described way would not add extra work in the UI then.

**Comment by r10s** [comment]
added these information also do the docs, see https://github.com/deltachat/deltachat-core/commit/1a516766a64635bacce94818de385a3a974180b6

**Comment by karissa** [comment]
The desktop app now only loads messages when you click on a chat. Could still be optimized to only fetch messages in view.

**Comment by hpk42** [comment]
indeed i have a chat with deltabot@codespeak.net with a couple hundred messages and it loads slowly (i think the dc_get_chat_msgs() is fast and only returns a list of msg-ids but then fetching each message takes time.  If only the messages in view are fetched i think it'll be super-fast as well (like other chats with only 20-30 messages).

**Comment by ralphtheninja** [comment]
What would a "get messages only in view"-algorithm look like? We might want to start thinking about this soonish for desktop.

**Comment by hpk42** [comment]
On Wed, Oct 24, 2018 at 00:32 -0700, Lars-Magnus Skog wrote:
> What would a "get messages only in view"-algorithm look like? We might want to start thinking about this soonish for desktop.

don't know the internals of desktop -- but basically it's about only asking for message content 
on demand, and not fill the whole message-list for chat up-front.
