### ISSUE TITLE
Builds for mac aren't signed

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#603]
OS X wants that the .dmg files are signed with a developer code or something. Otherwise people have to change so security settings.

**Comment by hpk42** [comment]
Maybe @dignifiedquire or @jonasreinsch can shed light on how one
can pass the OS X verification?

**Comment by dignifiedquire** [comment]
it will depend on what you are using to create the dmgs

**Comment by ralphtheninja** [comment]
We're using https://github.com/electron-userland/electron-builder

**Comment by dignifiedquire** [comment]
have you tried the things described here: https://www.electron.build/code-signing ?

**Comment by Jikstra** [comment]
I guess the main problem is that we need a apple developer account and somehow get the certificate. What's the current situation on iOS for this @dignifiedquire ? Is there a delta.chat account/certificate which we can reuse?

**Comment by hpk42** [comment]
On Mon, Jan 21, 2019 at 08:04 -0800, Jikstra wrote:
> I guess the main problem is that we need a apple developer account and somehow get the certificate. What's the current situation on iOS for this @dignifiedquire ? Is there a delta.chat account/certificate which we can reuse? 

i have an apple id but not a developer account it think.  
Not sure how one can create "organizational" apple developer accounts TBH

**Comment by jonasreinsch** [comment]
> [...] What's the current situation on iOS [...] Is there a delta.chat account/certificate which we can reuse?

@Jikstra atm, for the iOS TestFlight builds we use my personal developer account, but I think we should move that to a shared Delta Chat organization developer account.

**Comment by jonasreinsch** [comment]
> On Mon, Jan 21, 2019 at 08:04 -0800, Jikstra wrote: I guess the main problem is that we need a apple developer account and somehow get the certificate. What's the current situation on iOS for this @dignifiedquire ? Is there a delta.chat account/certificate which we can reuse?
> i have an apple id but not a developer account it think. Not sure how one can create "organizational" apple developer accounts TBH

@hpk42 here it is explained https://developer.apple.com/programs/enroll/ that is, you would sign in with your Apple ID (just tried, but I think the pw I have for the id is not current), then enter your orga data I guess and then adding a credit card to be charged the yearly amount (I think it's 80 EUR per year but didn't check)

**Comment by dignifiedquire** [comment]
https://github.com/ipfs-shipyard/ipfs-desktop/issues/66#issuecomment-456384158 has some details from someone who just walked this path

**Comment by olizilla** [comment]
👋 I've updated that issue with more details, hope it helps https://github.com/ipfs-shipyard/ipfs-desktop/issues/66#issuecomment-456384158

**Comment by dignifiedquire** [comment]
@olizilla thank you so much!

**Comment by hpk42** [comment]
Thanks to @Simon-Laux there now is a signed Mac release, built on the "bbmac" machine accessible to some devs here via ssh. You can find and try the build from here currently: https://merlinux.eu/delta/DeltaChat-0.101.0.dmg

What is missing is integrating the current script/building into the CI/Release flow somhow. Probably needs some advise, help from @ralphtheninja or others ...

**Comment by Simon-Laux** [comment]
This will also apply to windows builds, On newer windows versions(win10) the `windows defender`/`smart screen` or other antivirus programs will block the start of unsigned applications.

**Comment by Jikstra** [comment]
This is done, at least for building on the brombi mac.
