### ISSUE TITLE
Build & Start on Windows

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#606]
Blockers:
- [ ] deltachat-core doesn't build/work on windows yet https://github.com/deltachat/deltachat-core/issues/306

**Comment by homdx** [comment]
Builded binary deltachat-core need testing:
https://github.com/deltachat/deltachat-core/issues/306#issuecomment-461026117
Possible problems: Windows does not support utf-8 coding, windows uses ansi encoding. (need fix).

**Comment by homdx** [comment]
I did more more then 300+ commits for testing with travis-ci build deltachat-node under Windows
Now you can reproduce and build with some manual hands command core module under Windows
My testing repository for build under Win is:
https://github.com/homdx/test-win-build

I would continue to work build under Windows, then you can help repair the assembly with version 0.40 (lates build under win only 0.39).
Please test under Windows. Thanks)

**Comment by Jikstra** [comment]
Wow! Very awesome :+1: I will test it out tomorrow, need to get my hands on that one windows laptop :)

**Comment by kpleines** [comment]
I've tried to install the build environment using the cygwin, pyton 3, ninja, manson etc.
The build failed with:

./step1-bzip.sh: Zeile 74: patch: Kommando nicht gefunden.
./step1-bzip.sh: Zeile 79: make: Kommando nicht gefunden.

can you help to fix this problem with my development environment? Which required package is missing?

**Comment by homdx** [comment]
Hello.
All files and requirements are writed in file

https://github.com/homdx/deltachat-windows/blob/master/setup-cygwin-packages.cmd

You need install: openssl-devel, patch, dos2unix, make, cmake, libtool, automake, unzip, wget

Maybe some package, I will missing to write, but you can sea and found it at cyg-get command in this file.

**Comment by testbird** [comment]
With all the news above, how large are the remaining steps to set up an experimental deltachat-desktop windows build system and releases?

**Comment by kpleines** [comment]
I don't know how long it takes, but for me it is acual to complex. 
I would test the windows build if it where more easy to install. Sorry, it seems I missed some skills for that stage of developing.

**Comment by Jikstra** [comment]
> With all the news above, how large are the remaining steps to set up an experimental deltachat-desktop windows build system and releases?

Still hard and unknown how it works in the end. Currently the deltachat-node bindings don't work with the compiled cygwin windows library binaries. The more exact problem is that pthread on windows might work a bit different than the one for windows and is not 100% compatible. Needs more investigation.

**Comment by homdx** [comment]
@Jikstra Hello again)
You have successfully build the version 0.39 with my instruction on you notebok, under windows and cygwin.
You not started console appliction with electron.exe ?( with deltachatcmd.exe binary)?
Currently, no one else has ever compiled the application?

**Comment by sergeevabc** [comment]
Windows build is not ready, yet the issue is closed, how so?

**Comment by ralphtheninja** [comment]
Because it builds and starts on windows.

**Comment by Jikstra** [comment]
@sergeevabc with the last efforts of porting deltacht-core/libdeltachat to rust and removing most/all of the c dependencies, it's now possible to compile the rust core on windows and integrate it into deltachat-desktop. So the first people are already using it on windows.
