### ISSUE TITLE
when password incorrect, configure crashes on second time

### ISSUE THREAD

**Issue by karissa** [deltachat/deltachat-desktop#61]
from @r10s 

> maybe related: tried out to register delta 1.0.9 on macOS High Sierra 10.13.4 (grabbed my daughter's mac while she's at school :): download and installation works like a charm, up to the setup dialog:
> 
>     a first click on the "Login" button does nothing, so i wait some ten minutes (might be the key generation took some time :)
>     a second click on the "Login" button let the login window disappart without any comments.

I was able to reproduce this bug by typing in incorrect credentials, and then logging in again will cause dc_configure to crash because the sqlite database is never closed (i think). Maybe we need to use unref here?

**Comment by ralphtheninja** [comment]
I'll have a look.

**Comment by ralphtheninja** [comment]
Just realized that we never implemented `dc_is_open()`. I skipped it for some reason I forgot. But I think that if we implement that, we should be able to open the context only if it's not open, similarly to configuring when not configured. That's what I'm hoping at least.

**Comment by r10s** [comment]
just had a look at the source: in fact, the `dc_open()` may crash when called for an already opened database. i will fix this by calling `dc_is_open()` before.

however, in general, in general it is not needed to call `dc_close()` just because a configuration failed. from the view of the core, it is fine to call `dc_configure()` several times, eg. this is also done for changing the password or other settings.

**Comment by hpk42** [comment]
On Tue, Sep 25, 2018 at 10:45 -0700, björn petersen wrote:
> just had a look at the source: in fact, the `dc_open()` may crash when called for an already opened database. i will fix this by calling `dc_is_open()` before.
> 
> however, in general, in general it is not needed to call `dc_close()` just because a configuration failed. from the view of the core, it is fine to call `dc_configure()` several times, eg. this is also done for changing the password or other settings.

FWIW with the python bindings i never dc_close() -- i just make sure
that during garbage collection, when nobody holds a reference to
the "Account" object, "dc_context_unref" gets called which will
implicity call dc_close ASFAIK.

**Comment by r10s** [comment]
jipp, `dc_context_unref()` implies `dc_close()`.

also had a look at the Android part: also there `dc_close()` is never called.

**Comment by karissa** [comment]
great @r10s it does seem more elegant to fix this in core. @ralphtheninja what do you think?

**Comment by ralphtheninja** [comment]
> great @r10s it does seem more elegant to fix this in core. @ralphtheninja what do you think?

But the issue with multiple accounts still remain.

@r10s What do you recommend we do for multiple accounts? Can you use the same db? In desktop we point out different folders for different accounts.

**Comment by karissa** [comment]
@ralphtheninja I remember talking about multiple accounts in freiburg and it seemed like not on the immediate roadmap -- using a different db seemed like a nice solution. So for us we probably still want to close the old DB if one exists

**Comment by hpk42** [comment]
On Tue, Sep 25, 2018 at 13:05 -0700, Lars-Magnus Skog wrote:
> > great @r10s it does seem more elegant to fix this in core. @ralphtheninja what do you think?
> 
> But the issue with multiple accounts still remain.
> 
> @r10s What do you recommend we do for multiple accounts? Can you use the same db? In desktop we point out different folders for different accounts.

Each DB is tied to exactly one account and vice versa.  
dc_context is kind of a synonym for "dc_account". 
The way to have multiple accounts is to have multiple DBs.
in the python bindings i happily have 2 active accounts
with their respective smtp/imap threads. 

If you have a directory with different DBs and want
to show a selector of the different accounts,
say db1, db2, db3 in a particular application dir, 
you can make a for-loop over the dbs, opening each, checking if
is_configured() is true, getting the "addr" config, and closing it.

There is no need to have a db-filename that is derived from "addr". 
And this means that in "single account" mode (the one we are aiming to
get working) you can open "db1", start threads and don't ever stop the
threads or close/unref it unless you are really switching accounts. 
You can set_config(addr), set_config(mail_pw) and dc_configure() 
until success.

**Comment by r10s** [comment]
i would suggest to simply remove dc_close() from the api.
lots of troubles less.

**Comment by ralphtheninja** [comment]
> If you have a directory with different DBs and want to show a selector of the different accounts, say db1, db2, db3 in a particular application dir, you can make a for-loop over the dbs, opening each, checking if is_configured() is true, getting the "addr" config, and closing it.

That's a really cool way of enumerating the accounts. We should show a list of already configured accounts and you click on of them to "login". Would be a neat way of logging in without having to type `addr`.

**Comment by ralphtheninja** [comment]
> i would suggest to simply remove dc_close() from the api.
> lots of troubles less.

Sounds good to me!

**Comment by karissa** [comment]
@ralphtheninja @hpk42 I still think it's a good idea to be able to reverse-lookup an existing account, in case someone types in an email that is in the list

**Comment by karissa** [comment]
moving this to a new issue.
