### ISSUE TITLE
Debug logs aren't shown in renderer process

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#610]
I currently can't do a `log.debug()` call, also `console.debug()` calls are hidden in developer tools.

**Comment by ralphtheninja** [comment]
![screenshot from 2019-01-22 17-01-07](https://user-images.githubusercontent.com/308049/51548046-c8276300-1e67-11e9-8135-e5e0b41ac27b.png)
![screenshot from 2019-01-22 17-01-15](https://user-images.githubusercontent.com/308049/51548055-cc538080-1e67-11e9-919e-b2e8583e77bb.png)

**Comment by Jikstra** [comment]
That was the problem, thanks :)
