### ISSUE TITLE
Documentation for using / developing

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#612]
We should add some kind of documentation, especially for the more advanced features like logging.

Like for logging it might be:
- Logging (what gets logged / introduction sentence what it is)
- Logging parameters
- Content and Structure of the Log files

Maybe we can still fit the longing part in the README, but thats not a long term solution..
Sooner or later we should think about how we document those things ( I'm not talking about code documentation, just `use-` and `how things work-`documentation at the surface perspective)

**Comment by Simon-Laux** [comment]
Whats your perspective on this?

**Comment by Jikstra** [comment]
Hmm. Not really sure if this is worth it. I would prefer having some --help which shows the logging options.

**Comment by ralphtheninja** [comment]
We are already documenting in this fashion. If you feel there's something that's missing, just add it to the README. When it comes to documenting logging, I don't really see the need to be too detailed. Bare minimum is to document where the logs can be found.

**Comment by Simon-Laux** [comment]
> Hmm. Not really sure if this is worth it. I would prefer having some --help which shows the logging options.

Adding a man page would be cool, but the help command is better for now, cause it will work on windows.

**Comment by Jikstra** [comment]
> Adding a man page would be cool, but the help command is better for now, cause it will work on windows, too.

Normally you only document the usage of the program/the configuration in a man page, not how to start hacking on it. Besides that you can't really roll out man pages without copying them so some special "system" directory. So I think it's fine to document the logging command line options, everything else is over the top. At least outside of a DEVELOPMENT/README.md.

**Comment by Jikstra** [comment]
Is the github wiki also part of the repository files? So that if i clone the repo, i also have the docs? If not i'm against having a github wiki and prefer a docs folder with some `.md` files. But I don't think we have to document a lot besides logging? What do you want to document?

**Comment by ralphtheninja** [comment]
> Is the github wiki also part of the repository files? So that if i clone the repo, i also have the docs?

Nope.

**Comment by Simon-Laux** [comment]
I can't think of much at the moment. I'm sure we get more stuff worth documenting soon, though.

How about having a part of the documentation that acts like a help site?
That way we could add a help button to (as example) the settings page that opens a page which explains every option in detail. (only thing with that idea is that we need to think about having this site offline(no google translator and alike) or online(possibly a privacy risk))

**Comment by Simon-Laux** [comment]
I'll close this now, we can discuss this later in the forum or reopen this issue when its relevant again.
