### ISSUE TITLE
mailaddresses in messages cause doubling of message text

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#613]
current master: if you send a message with an email address, say: "email@email.org blaaaaa" then the rendering of the message on the sending side will be "email@email.org blaaaaa blaaaa".   Android shows the message correctly so this is quite definitively a desktop processing/rendering problem.

**Comment by ralphtheninja** [comment]
Mind pasting a screenshot? I don't fully understand.

**Comment by Simon-Laux** [comment]
![2019-01-24_21-04](https://user-images.githubusercontent.com/18725968/51705390-cc947d00-201b-11e9-97c5-9de61b5d66c9.png)

**Comment by Simon-Laux** [comment]
Probably it parses the email, but doesn't stop at the email and this results in a duplication of the text after the email.

**Comment by Simon-Laux** [comment]
It's somewhere in the Linkify component.
Interesting side note: As I was trying to use our logger for this debug task, the app froze and not a single entry was saved neither to the log file nor the chrome console. Console.log worked.
