### ISSUE TITLE
Read receipts not working

### ISSUE THREAD

**Issue by themchn** [deltachat/deltachat-desktop#616]
- Platform (linux/mac/windows): Linux, Debian Stretch
- Delta Chat Desktop Version: v0.99.0
- Expected behavior: Display of read receipts each message that is read by recipient.
- Actual behavior: No read receipts are displayed. Furthermore, if messaging an android client read receipts do not work on the android side either.
- Steps to reproduce the problem: Send a message to or from the desktop client to any other client.

**Comment by Simon-Laux** [comment]
I haven't seen double check marks on desktop since opening #447 
Also @ralphtheninja mentioned that he didn't see any checkmarks while chatting with me, too.

**Comment by Simon-Laux** [comment]
I would guess it's something with the core, because I get state `26` on every message that I sent successfully.
