### ISSUE TITLE
Make ChatView/ChatList resizable in x axes

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#633]
![screenshot_20190128_230306](https://user-images.githubusercontent.com/34889164/51869498-084b8180-2351-11e9-8bb6-f2ef4c2e7439.png)

**Comment by Simon-Laux** [comment]
Telegram shows only the avatars at a specific point, and you can't select a width that cuts into the text there.

**Comment by Jikstra** [comment]
Nice to have but not really needed
