### ISSUE TITLE
Add mac specifc default menu for hiding... 

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#634]
@ghoffart

**Comment by ghoffart** [comment]
<img width="319" alt="bildschirmfoto 2019-01-28 um 23 02 32" src="https://user-images.githubusercontent.com/128098/51869451-e0f4b480-2350-11e9-91ea-d3b0c6e5d439.png">

**Comment by r10s** [comment]
removed the assignment as nothing happens.
