### ISSUE TITLE
Import existing key fails (sendet via Thunderbird/Autocrypt)

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-desktop#648]
- Platform (linux/mac/windows): Linux
- Delta Chat Desktop Version: 0.100
- Expected behavior: Import existing PHP Key
- Actual behavior: Import via Autocrypt message fails

- Steps to reproduce the problem:

- create a new Account in DC for a mailadress with a already existing PGP Key
- send via Thunderbird (installed on the sam device) a Autocrypt message.
- open this message in DC
- type the shown code in the fields

- a error message (red banner) pops up "wrong code"
I'm sure the code is correct.

Maybe you also could a implement a way to import already existing PGP keys?

**Comment by violoncelloCH** [comment]
is the key in thunderbird password protected?
delta chat only supports keys without a password...

**Comment by webratte** [comment]
Yes it is.
But I thougth if I use the Autocrypt message it would work.

If there no way to import protected keys, there should pop up a clear warning.

E.g. "It's impossible to import password protected keys. You should (temporary) remove the password".

**Comment by Jikstra** [comment]
This is a core problem which we can't really solve on the desktop side of things. I would like to move/point this issue to core, and close this issue to keep the issue tracker clean @webratte.

**Comment by webratte** [comment]
Thank you.

Have I to open a issue in core?
Or will it be done by you?

Still a warning in the meantime untill it's fixed in core would be helpful.

**Comment by webratte** [comment]
If I say warning I mean a show a simple prompt window (before you open the code input window) with content  like:

DC can currently handle only keys without password protection. Please be sure you have removed the password (temporary).
Otherwise import will fail.

Or a better wording 😉

I think this can help get users not frustrated.

**Comment by Jikstra** [comment]
Found the issue in -core: https://github.com/deltachat/deltachat-core/issues/144

Adding a warning should be a good first step :)

**Comment by Jikstra** [comment]
Should be fixed? Lets reopen this in case it's still a problem
