### ISSUE TITLE
titlebar layout / UI-improvement

### ISSUE THREAD

**Issue by violoncelloCH** [deltachat/deltachat-desktop#650]
- [ ] as the tree dot menu contains general options / settings, I would place it above the chatlist (so general things are all on the left side; I think this would be much more intuitive)...
- [ ] as we would have space on the right side then, we could also move the gallery icon to the right

see screenshot/mockup:
![delta_layout_improvement](https://user-images.githubusercontent.com/22591354/52017100-a9b80c00-24e6-11e9-87ba-6a299a4778aa.jpg)

- Delta Chat Desktop Version: 0.100.0

**Comment by Jikstra** [comment]
Thanks for you ui ideas, our current idea is following:
- keep the tree dot menu as it is, but move out all general options to a menu on the left. 
- the media button will get merged in a general dialog which will be accessable over the tree dot menu on the right and by clicking on the group header (in your screen the Example thingie).

**Comment by violoncelloCH** [comment]
thank you for the explanations of your plans! these sound very good too and obviously make my suggestions obsolete, so feel free to close this issue... is there an issue for your idea?

**Comment by Jikstra** [comment]
No issue for that yet as there are a lot of other things which need to be done before.
