### ISSUE TITLE
Add setting for switching between shift+enter and enter for newline 

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#657]
We should add a setting for switching between shift+enter and enter and appart of that tell the users somehow that they have to press `Shift`+`Enter` for a new line. IMHO

**Comment by hpk42** [comment]
Just sitting next to @r10s --- on android the default is that Enter makes a new line.  On Telegram and other messengers also Enter makes a new line whereas CTRL+Enter sends the message it seems.  So it should probably be like this on Delta/Desktop.

**Comment by Simon-Laux** [comment]
@Jikstra I semi-agree, This issue also is more about **changing the default** and #542 is only the option.
