### ISSUE TITLE
Mac v0.100.0 not opening

### ISSUE THREAD

**Issue by zafai** [deltachat/deltachat-desktop#659]
- Platform (linux/mac/windows): mac mojave 10.14.2
- Delta Chat Desktop Version: v0.100.0
- Expected behavior: Open the client
- Actual behavior: error message
- Steps to reproduce the problem: install deltachat desktop
- Screenshots: 
firsttime opening error:
<img width="547" alt="deltachat_error" src="https://user-images.githubusercontent.com/10008540/52169763-04977080-273e-11e9-9cb0-46be712c737a.png">
second time opening error:
<img width="547" alt="deltachat_error2" src="https://user-images.githubusercontent.com/10008540/52169762-04977080-273e-11e9-8ea4-ff9680676050.png">

- Logs:

**Comment by ralphtheninja** [comment]
`brew install openssl`

**Comment by zafai** [comment]
@ralphtheninja yes thank you!

**Comment by nicodh** [comment]
Closed too early: same issue here (On Mac 10.12.16). I have openssl installed but with port instead of brew.
`~: openssl version` 
`~: OpenSSL 0.9.8zh 14 Jan 2016`

**Comment by zafai** [comment]
Reopend for @nicodh

**Comment by nicodh** [comment]
It seems port installs at 
`/opt/local/lib/libssl.dylib -> libssl.1.0.0.dylib`
but there is also the "default" openssl used by the system at
`/usr/lib/libssl.dylib -> libssl.0.9.8.dylib`

**Comment by ralphtheninja** [comment]
At the moment desktop assumes openssl has been installed using brew and in `/usr/local/opt`. As a workaround maybe you can symlink from there into the port location.

**Comment by nicodh** [comment]
Yes if I add a symlink manually it works, but I just wanted to report the issue...

**Comment by Jikstra** [comment]
I guess we should put this in the install instructions? What's the "standard" approach on installing openssl on mac? Bundling it into the .dmg? Installing it seperately over brew? brew is not really a tool for non techy people i think.

**Comment by nicodh** [comment]
I think we should bundle it in the .dmg if possible.
There is an openssl library which is part of the system, but that is somewhat outdated (as you see above) and you can't "overwrite" it without disabling "System Integrity Protection“  and rebooting.
Brew is not a standard tool on Mac, only for developers...

**Comment by ralphtheninja** [comment]
Again, this boils down to the node bindings. And yes, with the information we have this far, they should bundle everything that's needed for all platforms. These problems are only going to get worse :)
