### ISSUE TITLE
An Empty message shouldn't be sent

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#668]
unlike on android where you can not send "empty" messages that only contain `\n` and spaces

**Comment by Simon-Laux** [comment]
Also on android they are diplayed as if they would be completely empty - I think android trims away '\n' and space from the start and end of each message.

**Comment by Jikstra** [comment]
This should got fixed via https://github.com/deltachat/deltachat-desktop/pull/670

If not please reopen @Simon-Laux
