### ISSUE TITLE
Crash when configuring an account

### ISSUE THREAD

**Issue by sbadux** [deltachat/deltachat-desktop#67]
Hello, 
I've installed the last Desktop .deb package on Ubuntu 18.04. It starts fine, but when I put username and password DeltaChat crashes immediately. I've started it 4-5 times and always get the following errors.

The terminal returned 

```
(node:6844) Warning: N-API is an experimental feature and could change at any time.
init: 1017.107ms
undefined:0



Error: Failed to open
```
or

```
(node:7853) Warning: N-API is an experimental feature and could change at any time.
init: 1022.815ms
Not configured, cannot connect.
Not configured, cannot connect.
Bad or incomplete autoconfig: 0 0:0:0:0 0:0:0:0 0
Bad or incomplete autoconfig: 0 0:0:0:0 0:0:0:0 0
Bad or incomplete autoconfig: 0 0:0:0:0 0:0:0:0 0
undefined:0



Error: Failed to open
```
then it seemed to work. 
I've typed the email and a WRONG PASSWORD and it seemed to login. When I pressed the "Create Chat" button it asked for an account. Then I've tried to press LOG OUT but it didn't work. Now I'm stuck: it's logged in (it's a fake login since the password was wrong) and I can't logout.

Thanks for your help

**Comment by karissa** [comment]
this will be fixed in the next version! https://github.com/deltachat/deltachat-desktop/pull/63

**Comment by sbadux** [comment]
Thanks. I'll wait for the next release before posting other bug reports :)

**Comment by sbadux** [comment]
Sorry to report this again, but the problem "fake login with any password" is still here. Now I can logout but it doesn't report any error if I login with a wrong password.

1.1.0-215 amd64 :)

**Comment by karissa** [comment]
@sbadux once you login with the correct password once, it saves that configuration. Check out #53 for an update to the UI that will make this more clear

**Comment by sbadux** [comment]
Thanks. I logged with the correct password and it works. I underlined this problem because if you have the 2FA activated you could type the account password (not the app-password) and get a "fake login" which is quite confusing for a non-technical user.

Anyway, thanks for your quick reply. Now I'm ok :)
