### ISSUE TITLE
Minor issue: DeltaChat 0.100.0-PREVIEW's X-Mailer outdated

### ISSUE THREAD

**Issue by KNTRO** [deltachat/deltachat-desktop#679]
- Platform (linux/mac/windows): GNU/Linux
- Delta Chat Desktop Version: 0.100.0-PREVIEW
- Expected behavior: "x-mailer: Delta Chat 0.100.0"
- Actual behavior: "x-mailer: Delta Chat 0.39.0"
- Steps to reproduce the problem: Nothing special, simply send a message by using DeltaChat and then read the message's header in another email client.
- Screenshots: N/A
- Logs: N/A

**Comment by r10s** [comment]
just some backgrounds: 0.39 is the version of the core that actually performs the sending, so eg. Android or iOS ship similar X-Mailer header, however, at least for android the suffix "Android" is added (see [dc_context_new()](https://c.delta.chat/classdc__context__t.html#a9d0f77a01382745e59492dda8509cf83) for some information about how the string is created).

**Comment by hpk42** [comment]
On Tue, Feb 12, 2019 at 20:58 -0800, ḲṄṪṚÖ wrote:
> 
> 
> - Platform (linux/mac/windows): GNU/Linux
> - Delta Chat Desktop Version: 0.100.0-PREVIEW
> - Expected behavior: "x-mailer: Delta Chat 0.100.0"
> - Actual behavior: "x-mailer: Delta Chat 0.39.0"
> - Steps to reproduce the problem: Nothing special, simply send a message by using DeltaChat and then read the message's header in another email client.
> - Screenshots: N/A
> - Logs: N/A

hum, the x-mailer indicates the core version, not the android version. 
Maybe it should contain both like in "Delta Chat Android 0.100.0 / Core 0.39.0"? 
Or we just add "Core" to the string.

**Comment by r10s** [comment]
yip, we can change this. i think it depends a bit if x-mailer is typically exposed to the user or not.
i know of no MUAs that really show the x-mailer (only along with other headers which are typically even more technical), however, i know only few MUAs :)

**Comment by violoncelloCH** [comment]
I don't know any MUA really showing this to the user... some allow displaying the source, there it's visible obviously, but that's not a feature for regular users...
