### ISSUE TITLE
Belgian isn't a language

### ISSUE THREAD

**Issue by flub** [deltachat/deltachat-desktop#686]
In the language selection menu I noticed `Belgian` as a language.  Belgian isn't a language, languages in spoken in Belgium are either Dutch, French or German.

I noticed there is also `Dutch`, `Neederlands (Netherland)` and `French`.  Given there seems to be a preference for using english language names I'm proposing to merge the `Dutch`, `Neederlands (Netherland)`, `Belgian` and `French` into only `Dutch` and `French`.

- Platform (linux/mac/windows): linux
- Delta Chat Desktop Version: 0.101.0-preview
{
    "arch": "64",
    "compile_date": "Feb 15 2019, 08:40:41",
    "deltachat_core_version": "v0.40.0",
    "libetpan_version": "1.8",
    "openssl_version": "1.1.1a",
    "sqlite_thread_safe": "1",
    "sqlite_version": "3.26.0"
}

**Comment by Jikstra** [comment]
Related: https://github.com/deltachat/deltachat-desktop/issues/681

**Comment by Simon-Laux** [comment]
`Belgian` isn't in the language list anymore and the other points are also mentioned in #681
