### ISSUE TITLE
Log file is empty after fatal error

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#689]
I had faced issue #401, the app had shown the error trace in the stdout and pointed me to a log file, but this log file is empty.

- Platform (linux/mac/windows): GNU/Linux
- Delta Chat Desktop Version: v0.101.0

**Comment by adbenitez** [comment]
may have something to do with the fact that the app do not close after having this error (which is odd) and I had used Ctrl+C to close it

**Comment by Simon-Laux** [comment]
can you send me the stdout? (If it contains private info you can send it via deltachat otherwise posting here should be fine)

**Comment by adbenitez** [comment]
the log is not the big thing but here I attach it(also there were a line saying something like "you can see the log at ...." pointing to the log file:
[dc.log](https://github.com/deltachat/deltachat-desktop/files/2889709/dc.log)

**Comment by Simon-Laux** [comment]
ah it's likely something with deltachat-node

**Comment by Simon-Laux** [comment]
I don't really know how we can solve this, I mean we can't really catch when a require statement fails.
The expected behavior would be that it opens an error dialog which informs the user of the missing dependency I would say, but thats not so easy to implement.

**Comment by ralphtheninja** [comment]
We can't solve this. If the application can't start, we can't create a log that depends on the application running or at least starting properly.

**Comment by adbenitez** [comment]
the log file is created!!! it is just empty! the app is printing the message to stderr, maybe even to the log and the issue is that it isn't flushed

**Comment by Simon-Laux** [comment]
Still we can't fix this, the best we could do would be detecting if every dependency is there before requiring them. But I actually think solving the missing dependency has more priority.

**Comment by Simon-Laux** [comment]
The point is the logfile probably gets created before deltachat-node gets loaded up. We can't really check on whether a require fails as far as I knowso we can't add it to the log.
@ralphtheninja @Jikstra please correct me when I'm wrong here.

**Comment by Simon-Laux** [comment]
```
1. electron starts index.js
2. index.js loads in the log-handler.js
3. index.js loads in the ipc.js, which loads in deltachat.js
4. deltachat.js loads in deltachat-node
```

**Comment by Simon-Laux** [comment]
Maybe we could move the [exception handler](https://github.com/deltachat/deltachat-desktop/blob/master/src/main/index.js#L34) to before the `require('./ipc')` to catch the error in the logfile.

**Comment by ralphtheninja** [comment]
> Maybe we could move the [exception handler](https://github.com/deltachat/deltachat-desktop/blob/master/src/main/index.js#L34) to before the `require('./ipc')` to catch the error in the logfile...

Yes, that's a good idea.

> the log file is created!!! it is just empty! the app is printing the message to stderr, maybe even to the log and the issue is that it isn't flushed

Sorry @adbenitez, my bad!
