### ISSUE TITLE
Specification Needed

### ISSUE THREAD

**Issue by martindale** [deltachat/deltachat-desktop#691]
Loving this project and its direction!  I'd like to implement a client library compatible with the desktop app, so I took a look for what I expected to be a very simple specification and couldn't find one.  If one exists, can it be shared more prominently, and if not, can one be created?

**Comment by r10s** [comment]
@martindale there is https://github.com/deltachat/spec - it's not totally polished, however, it is also not really far away about how things actucally work.

if you want to implement sth. compatible to deltachat-desktop, maybe also [deltachat-core](https://github.com/deltachat/deltachat-core/) is worth a try. deltachat-core is the library used for all deltachat apps (ans some others) to do the chat-with-mail thingie and implements the spec.

**Comment by Jikstra** [comment]
I think this can get closed @martindale ?
