### ISSUE TITLE
Ship package-lock.json in release tarball

### ISSUE THREAD

**Issue by flub** [deltachat/deltachat-desktop#694]
For downstream packaging we need a the package-lock.json file which is generated by npm install --package-lock-only. I think we want to generate this file as part of the release so that different packagers end up using the same one.

**Comment by flub** [comment]
I'd rather not do this myself as my last attempt at generating this file resulted in very different things than when @muelli did so.  So my npm version does weird things or I have other things which are not setup correctly.

But afaik this just needs to be generated with `npm install --package-lock-only` and than checked in like any other normal source file.

**Comment by ralphtheninja** [comment]
We have a `package-lock.json` now.
