### ISSUE TITLE
Leaving an freshly created group

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#697]
When you leave a freshly created group nothing happens at first glance, in reality you left the group but the screen wasn't updated.

**Comment by nicodh** [comment]
The question is, what should happen here? If you leave a group it is not the same as deleting a chat.
The chat remains in the list, so all we could show is a confirmation "You have left the group". But the chat is still there (and core keeps it in the list). On the other hand - one should not be able to send a message to a group chat if one is not member of that group. We need a lot of changes in the UI if we want to support showing group chats that the current user is not member of. (Hiding the create message input, hiding the "leave group" entry in context menu, maybe a marker or special icon in chat list etc.)

**Comment by Jikstra** [comment]
I think the expected behaviour is to not be able to send a message, not receiving any new messages and not being able to leave that group again. So basically what you wrote up. Don't think we need to change that much besides hiding some stuff in the ui. Shouldn't be too hard.

**Comment by Simon-Laux** [comment]
#724

**Comment by Simon-Laux** [comment]
If I remember correctly the reason that I created this issue was, that the "Group left by [me]" message wasn't shown, only after reentering it. Let me check if it's solved and if it is I will close this in favor of #724

**Comment by Simon-Laux** [comment]
Ok the bug is still there, here is how to reproduce:
- create a new group
- don't send first message
- leave the group
-> the member count only gets updated after you reentered the group

**Comment by nicodh** [comment]
@Simon-Laux just checked this again: what happens now is, that the subtitle disappears, the message box is disabled showing "You are not in this group". I would say that's not perfect but ok for now.

**Comment by Simon-Laux** [comment]
so another bug went up to our rescue and covered up this bug

**Comment by nicodh** [comment]
Will you have a look for the subtitle issue? Since you just refactored that...
It's also the last remaining topic in #916
