### ISSUE TITLE
Disable login button (and enter key on input field) while logging in

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#70]
It's possible to click the login button multiple times and create multiple contexts. If we disable input while the login process in ongoing we can get rid of some issues. Once login succeeds we continue to next screen, if it fails we enable the login button once again, so next login attempt can be started.

**Comment by karissa** [comment]
How do we know when the login process is ongoing? How do we know when it fully fails?

**Comment by ralphtheninja** [comment]
@karissa We know when we start it, by calling `dc.configure()` and we know if it fails if `DC_EVENT_CONFIGURE_PROGRESS` reports a 0. (I think we figured this out yesterday on irc, but writing it here for completeness).

**Comment by karissa** [comment]
ok this is working now
