### ISSUE TITLE
Composer input handler is slow

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#700]
Not sure why, but something is really slow there. I think we shouldn't need to update the state every time the text changes.

We should debounce the resize methods

**Comment by nicodh** [comment]
Can't reproduce this. Performance on Mac is fine...

**Comment by Jikstra** [comment]
The problem is that the resize...() method in the Composer takes up to 30ms on my machine and because it's getting called on each change of the textarea, they can queue up for quite some time. Maybe not easily reproducable on a strong machine.
