### ISSUE TITLE
Alt+Shift combination causes menu to open

### ISSUE THREAD

**Issue by MRZA-MRZA** [deltachat/deltachat-desktop#709]
- Platform (linux/mac/windows): Linux
- Delta Chat Desktop Version: 0.101.0
- Expected behavior: Menu shouldn't open
- Actual behavior: Menu opens
- Steps to reproduce the problem: Press Alt+Shift

When I'm typing and want to switch input language I press Alt+Shift that causes menu to open. It interrupts my input.

**Comment by Jikstra** [comment]
Which menu opens? Can't reproduce on arch + kde plasma. Which desktop/window manager are you using?

**Comment by MRZA-MRZA** [comment]
Application menu. I'm using Xubuntu 18.10 with XFCE.

**Comment by Jikstra** [comment]
Can you test if this happens with other programs too? It's possible that this is a xfce specific thing, maybe a general gtk option. A keybinding to open the application menu.

**Comment by MRZA-MRZA** [comment]
I think this should clarify everything: https://github.com/vector-im/riot-web/issues/4345

**Comment by Vftdan** [comment]
I have the same problem. But I have alt+CapsLock bound as language switch: `setxkbmap -layout us,ru -option grp:alt_caps_toggle`. DeltaChat menu is triggered by alt+CapsLock, alt+Shift does nothing.
OS: Linux Mint 19 Tara
WM: bspwm

**Comment by nicodh** [comment]
Should be fixed since we had an electron upgrade and bug vector-im/riot-web#4345 is fixed. I can't reproduce it on Ubuntu 18.04
