### ISSUE TITLE
Send and request read receipts (same behaviour as in Android client)

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-desktop#711]
- Platform (linux/mac/windows): Linux
- Delta Chat Desktop Version: 0.101.0
- Expected behavior: show read state of messages
- Actual behavior: only one checkmark

Send and request read receipts (same behaviour as in Android client)

**Comment by Simon-Laux** [comment]
Duplicate of #616

**Comment by webratte** [comment]
OK, sorry.

Thank you for your hint.
