### ISSUE TITLE
Avoid content security error when loading emoji-mart image sheet

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-desktop#715]
I see an error in the console:
`Refused to load the image 'data:image/svg+xml;base64,PD94bw ...' because it violates the following Content Security Policy directive: "img-src 'self' https://unpkg.com".`
We could provide these images locally. See node_modules/emoji-mart/README.md

**Comment by Simon-Laux** [comment]
It shouldn't use any images for the emojis themselves, it should use the font, so maybe these are the icons for the tabs? :thinking:

**Comment by nicodh** [comment]
I didn't dig deeper into this so far - just saw the error message and found the domain in README

**Comment by Simon-Laux** [comment]
It's the content security policy that currently doesn't allows base64 encoded images

**Comment by Simon-Laux** [comment]
Not sure on what to do about it... the first image is some kind of half circle, doesn't seem too important..

**Comment by Simon-Laux** [comment]
Also I would disable/deny loading stuff from `https://unpkg.com` DeltaChat shouldn't load stuff at runtime from CDN servers.

**Comment by Simon-Laux** [comment]
I think this issue was resolved because I don't see that message in the console anymore also the content security policy looks updated.
