### ISSUE TITLE
Kerberos authentification support

### ISSUE THREAD

**Issue by arthurlogilab** [deltachat/deltachat-desktop#716]
- Platform (linux/mac/windows): linux
- Delta Chat Desktop Version: 0.101.0-preview
- Expected behavior: Authenticate using kerberos ticket
- Actual behavior: Only password login is available
- Steps to reproduce the problem: 
- Screenshots:
- Logs:

**Comment by Simon-Laux** [comment]
I think thats an core issue.

**Comment by Jikstra** [comment]
Yup this would need core support.

**Comment by flub** [comment]
I guess it's fine to close here?

**Comment by hpk42** [comment]
issues can be moved between repositories.
this issue here should better be reopened because of all
the meta communication though ;)
