### ISSUE TITLE
Various improvments to Media View

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#719]
Gallery navigation in Media View:
When you open it from the gallery it should present buttons to go to the previous and the next thing in line, but that could be a bit more complicated: When the user has selected to filter the gallery to only videos, only videos should appear in next and previous.

_Originally posted by @Simon-Laux in https://github.com/deltachat/deltachat-desktop/pull/710#issuecomment-469795925_

**Comment by Jikstra** [comment]
In the same step we could also imrove the general ui/ux of the fullscreen media view. The current open pr improves it already quite a bit, but i have some more ideas:
- in general do it as telegram does it:
![screenshot_20190307_203948](https://user-images.githubusercontent.com/34889164/53984256-48084480-4119-11e9-9941-8beb7e721bd7.png)
- add some padding to the X button
- same for the download button
- clicking anywhere which is not a button should close the fullscreen view
- show some image details
- hide the buttons if we didn't move the mouse for x seconds
- if possible open a new window and expand it to the full screen size (maybe hard)

**Comment by Simon-Laux** [comment]
We could use https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API then we don't need a separate window

**Comment by pabzm** [comment]
This appears to be a feature request, that no one is currently working on. We don't want to track those in our list of issues. Please close or move to project Resurrection.

**Comment by pabzm** [comment]
x
