### ISSUE TITLE
Fix linux ci/cd and flatpak

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#722]
Currently the ci/cd for linux is non existing and needs to get replaced on travis. While doing this, we can skip creating/pushing .deb releases on new version drafts but we need to tweak some stuff to make the integration with flatpak working. @flub can give us some more details on what's needed?

**Comment by flub** [comment]
- this repo needs to ship package-lock.json (issue #694 )
- the electron-builder config needs to be updated to skip the deb and AppImage

At this point the steps to go from a release here to a release at flathub/chat.delta.desktop are:
- clone chat.delta.desktop, create new branch
- run script to update generated-sources.json
- update download URL for deltachat-desktop source (.tar.gz) release (and checksums)
- create a PR which will triger a build

It would be nice if the CI in this repo could take these steps, we can script them.
- When having a draft release is there already a link to the .tar.gz URL to try?
- For each new push to the draft, do we get an updated URL and can we update the PR therefore seeing the result in the final build?
- when finally releasing the CI would have to change the URL to the release/tagged version and update the PR

Then at the end to release a user would have to:
- publish the draft release here
- wait for the PR to be updated
- merge that PR
- either wait 24h or go press a button to publish the release there immediately

I hope this is a useful overview of what this can look like.  This should allow people to start working on some of these steps.

**Comment by muelli** [comment]
the appdata file needs to be updated to contain the new release.

**Comment by flub** [comment]
@muelli yep, that's now in by #730
