### ISSUE TITLE
Improvements for displaying non-synced verified group 

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-desktop#723]
I habe been added to a verified group by scanning the QR code with my phone.  I sent an autocrypt setup message and confirmed the code in deltachat-desktop.

All messages in the verified group show only "[The sender of this message is not verified.. See "Info" for details.]"

If I try to send a message I see an error message: "End-to-end-encryption unavailable unexpectedly."

Additional issues:

- [x] "sendFailed" & "retrySend" no translation found
- [x] "The sender of this message is not verified" should be translated
- [x] it says: See "Info" for details - but infos has no more details...

**Comment by r10s** [comment]
yip, the verification state is not yet synced - as well as many other things beside [basic messages](https://github.com/deltachat/deltachat-core/issues/52) are not synced yet, eg. archived or deleted chats.

however, i think this is more a core issue. i think there is not much deltachat-desktop can do on this.

maybe we should move this issue to deltachat-core or create a more common issue to collect things that need syncing there.

**Comment by r10s** [comment]
> it says: See "Info" for details - but infos has no more details...

this, however, can be improved on desktop: the "message info" should just show the output of [dc_get_msg_info()](https://c.delta.chat/classdc__context__t.html#a9752923b64ca8288045e999a11ccf7f4) somewhere - in case of these stub message, the full text is included in the returned text - together with many other information (at some point in the future, this could be made "nicer", but to just "get" the information, it is okay for now imo)

**Comment by nicodh** [comment]
Ok I will change this issue then and another issue might be added in core...

**Comment by r10s** [comment]
@nicodh thanks! i was just searching: there is no issue wrt sync, so, in fact, this is needed (was only in our mind up to now :)
