### ISSUE TITLE
Disable message box when you left the group

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#724]
And have this property in the chat-state/-object to do other stuff like hiding the leave button and maybe replace it with a button to join the group again, though joining again a group is a feature- request matter on its own and as a feature proposal it should be discussed on the forum.

Edit: with `message box`  I mean the composer

**Comment by Jikstra** [comment]
How is this currently done on android?

**Comment by Simon-Laux** [comment]
Its not done at all on android

**Comment by Simon-Laux** [comment]
Just the error message
