### ISSUE TITLE
Offer "contact request" handling like Android

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#725]
Android and core just introduced refined contact request handling. See https://deploy-preview-146--deltachat.netlify.com/en/2019-03-14-oauth2release#streamlined-contact-requests for details. New desktop releases will thus default to the new behaviour -- i suggest to add an options to settings to configure it the same way as on android.  Note that there is no "syncing" of settings between android and desktop (or iOS) yet.  Once Desktop is reliably available on win/lin/osx this likely becomes more urgent to go for. This issue is just about the manual "contact requests setting".

**Comment by r10s** [comment]
technically, it's "just" [dc_set_config(context, "save_emails", DC_SHOW_EMAILS_OFF|ACCEPTED_CONTACTS|ALL)](https://c.delta.chat/classdc__context__t.html#aff3b894f6cfca46cab5248fdffdf083d).

the core handles the default as usual and with dc_get_config() the current state can be queried.

apart from the switch there are no ui changes necessary, the core just returns sightly different views depending on the setting.
