### ISSUE TITLE
Ship appstream metadata

### ISSUE THREAD

**Issue by flub** [deltachat/deltachat-desktop#729]
This is currently added in the flatpak repo, but is not specific to flatpak really so should probably lie here instead.

**Comment by Jikstra** [comment]
I guess it's about moving this file over to this repo?
https://github.com/flathub/chat.delta.desktop/blob/master/chat.delta.desktop.appdata.xml

**Comment by flub** [comment]
Yes, but turns out it already lives in static/!  anyway, i'm updating it and configuring travis to validate it (the latter taking up all the time).  It needs to be updated with every release sadly so i also updated the readme with instructions.  Lastly it turns out it also refers to the .desktop so that needs to moe al well.

**Comment by muelli** [comment]
and it needs to be shipped with binary releases, in case you produce any. That's what https://github.com/electron-userland/electron-builder/issues/1993 is about IIUC.

**Comment by muelli** [comment]
> I guess it's about moving this file over to this repo?

and it's about updating it to reflect a new release.
