### ISSUE TITLE
Images with huge width overflow

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#732]
![Screenshot_20190319_141432](https://user-images.githubusercontent.com/34889164/54608595-54619b00-4a51-11e9-88eb-e719f86a2e95.png)

![image-34](https://user-images.githubusercontent.com/34889164/54608565-43188e80-4a51-11e9-94d7-90c50e80c90d.png)

**Comment by Simon-Laux** [comment]
why the appimage tag?

**Comment by Simon-Laux** [comment]
is this related to #579?

**Comment by Jikstra** [comment]
Not related and no idea why the tag is there.
