### ISSUE TITLE
Drag & Dropping a file results in a picture description "Droped File"

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#733]
Not only is it a typo but also i think it's not really useful to tell people that this file got inserted via drag&drop. 
@Simon-Laux what do you think about this?
![Screenshot_20190319_185628](https://user-images.githubusercontent.com/34889164/54629848-b8e42080-4a78-11e9-8e95-d4faa4209cb0.png)

**Comment by Simon-Laux** [comment]
You can remove it, it was a reminder to add draftmode to files

**Comment by Simon-Laux** [comment]
Also I'm sorry for the typo :rofl:
