### ISSUE TITLE
Why Signal?

### ISSUE THREAD

**Issue by ShalokShalom** [deltachat/deltachat-desktop#735]
May I ask you why you use the Signal UI?

Wire would offer a lot more devices..

Or is this another code for all the different platforms there?

**Comment by ralphtheninja** [comment]
> May I ask you why you use the Signal UI?

I'm guessing mostly because peole know this type of UI and it was something that was rather easy to tap into.

> Wire would offer a lot more devices..

We use this on mobile and on desktop, which covers: iOS, android, linux, mac and windows. What are you missing?

> Or is this another code for all the different platforms there?

Not sure what you mean by this question. What do you mean by _this_?

**Comment by ShalokShalom** [comment]
Nevermind, I thought Signal covers way less platforms as it actually does, maybe I mixed it with some other application or my knowledge was outdated. Wire offers just the webapp, compared to Signal, as an advantage. Thanks a lot for your time and patience :)
