### ISSUE TITLE
Crash on OSX 10.12 (with local install)

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-desktop#743]
Current master on OSX 10.12 crashes when a new mail is received or if  new mails are in inbox when starting.
Release v0.102.0 works fine.
Error message is 
`Electron(1544,0x70001b962000) malloc: *** error for object 0x7ffdefef0048: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug`

I have libetpan 1.9.2_1 installed in /usr/local/Cellar/libetpan/1.9.2_1

I tested running the deltachat_node from command line. It works fine without crashes and could fetch mails.

Last log message on console is not the same on each crash:
`main/deltachat DEBUG [] ALL event { event: 100, data1: 0, data2: 'SENTBOX-fetch started...' }`
or
`main/deltachat DEBUG [] ALL event { event: 102,
  data1: 0,
  data2: 'IMAP-login as deltachat@ndh.me ok.' }`

Attached some crash reports (only the crashed thread)

[desktop-crashes.txt](https://github.com/deltachat/deltachat-desktop/files/3000912/desktop-crashes.txt)

**Comment by nicodh** [comment]
Not sure if that is related: when I compile deltachat-core in node-modules I see these (and more similar) warnings:

`ld: warning: object file (../deltachat-core/builddir/src/libdeltachat.a(dc_contact.c.o)) was built for newer OSX version (10.12) than being linked (10.7)
`

`ld: warning: object file (/usr/local/Cellar/libetpan/1.9.2_1/lib/libetpan.a(mailmessage_tools.o)) was built for newer OSX version (10.8) than being linked (10.7)`

`ld: warning: object file (../deltachat-core/builddir/libs/netpgp/libnetpgp.a(src_packet-parse.c.o)) was built for newer OSX version (10.12) than being linked (10.7)
`

But as said above, when running node_modules from console no crashes happen...

**Comment by Jikstra** [comment]
This error `ld: warning: object file (../deltachat-core/builddir/src/libdeltachat.a(dc_contact.c.o)) was built for newer OSX version (10.12) than being linked (10.7)` should vanish when compiling manually. So try to do a `npm install --build-from-source` and try again. I also had crashes on an older mac version which might were related to compiling on a newer mac but couldn't try it again with manually built version.

**Comment by nicodh** [comment]
Same warnings with the --build-from-source param

**Comment by nicodh** [comment]
After changing to rpgp insread of netpgp no crashes anymore!
