### ISSUE TITLE
"Random" RPC error that results in a white screen

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#745]
![error](https://user-images.githubusercontent.com/18725968/54997703-9ac47600-4fcc-11e9-9fc2-fd366595f42c.png)

After doing `npm run build && npx electron . -debug` I got a white dc window and this error in the dev console. After closing and trying the same command everything works fine.

What I know:
- This happened after a fresh boot of my system.
- I had a similar random white screen before, but I forgot to document the error.
- I'm on linux.
- I'm on master, last commit at the time: 554d0eeceeee7998d0b00dc9a7859227fdb65992

**Comment by nicodh** [comment]
Didi this ever happen again? I did never see it...

**Comment by Simon-Laux** [comment]
no it didn't, lets close it for now
