### ISSUE TITLE
Update screenshot in README.md

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#746]
The screenshot there could use an update to show the emoji support and a chat with an image in it.

**Comment by Jikstra** [comment]
How about this screenshot?

![image](https://user-images.githubusercontent.com/34889164/59110185-d372bb00-893e-11e9-8286-7347a991bc88.png)

**Comment by Simon-Laux** [comment]
Why not? you can put it in the readme in my opinion

**Comment by ralphtheninja** [comment]
It's good for now I think, but we should really spend more time on it to make sure it shows most features (everything is not possible). For example:

* group chats
* icon in a group chat
* markdown
* emojis in the chat (now only showing in the input field)

**Comment by Jikstra** [comment]
Also i'm really thinking of having a better way to generate those pictures. Can we maybe set up one config folder which has some good presettings for this? Like a set up group, one verified... so that we don't have to redo this again and again?
