### ISSUE TITLE
Attachement upload via paper-clip symbol fails - Ubuntu 18.04.2

### ISSUE THREAD

**Issue by graugelb** [deltachat/deltachat-desktop#754]
see headline

- Platform (linux--> Ubuntu 18.04.2:
Starting a message by clicking the paper-clip symbol --> targeting "home" --> "username" = nofiles (e.g. pdf) to see...?
- Delta Chat Desktop Version: 0.102.0-Preview
- Expected behavior: file (pdf/ ~ 100kB) location upload - where stored the file on the desktop -  and add text and finally send (message) both 
- Actual behavior: no files to be seen e.g. in the "home/username" location AND no drag&drop file upload possible eather
- Steps to reproduce the problem: every time
- Screenshots: see 2 attachements
- Logs:

**Comment by Simon-Laux** [comment]
How did you install deltachat?
If you used flatpack, there is currently a permission problem (https://github.com/flathub/chat.delta.desktop/issues/14)

**Comment by graugelb** [comment]
Quell: dl.flathub.org
Thanks!

**Comment by graugelb** [comment]
Quelle: dl.flathub.org
Thanks!
