### ISSUE TITLE
OSX 10.14.3 refuses to open after fresh install.

### ISSUE THREAD

**Issue by Leopere** [deltachat/deltachat-desktop#760]
- Platform (linux/mac/windows): Mac 10.14.3
- Delta Chat Desktop Version: latest as of the date of posting.
- Expected behavior: The application would open or even show up for a brief second in Activity Monitor
- Actual behavior: Does not open at all or show up in Activity Monitor
- Steps to reproduce the problem: Download .dmg file from github move the binary into the `Applications` directory and attempt to open the application.
- Screenshots: nothing to show except that Hazel notices that it's put some cruft into my filesystem when I move the application to the trash. ![screenshot](https://i.imgur.com/S6LVWIk.jpg)
- Logs: ![screenshot of console](https://i.imgur.com/Q9Uq4lW.jpg)

**Comment by End-to-End-is-the-way** [comment]
Same problem here with Mac 10.14.4

**Comment by Jikstra** [comment]
@Leopere @End-to-End-is-the-way there is a new Mac build which now includes openssl and other dependencies, can you try out that release?
https://github.com/deltachat/deltachat-desktop/releases/download/v0.103.0/DeltaChat-0.103.0.dmg

**Comment by Leopere** [comment]
@Jikstra it loads now.  ![screenshot](https://i.imgur.com/8HsFW2h.jpg)
