### ISSUE TITLE
no option to import a backup as first action after installation

### ISSUE THREAD

**Issue by haeckser** [deltachat/deltachat-desktop#763]
There were 2 bugs related to this issue, but they are closed without visible change in behaviour. That is why create the bug again ..

- Platform (linux/mac/windows): linux
- Delta Chat Desktop Version: 0.102.0 preview
- Expected behavior: after installation the first screen should have an option to load a backup (from other device) BEFORE I insert the credentials.  Loading the export would prevent user from more complex settings (my settings will fail in Desktop while Android versions worked fine ?!?!?!)
- Actual behavior: I MUST add my credentials and then I might try to load a backup which typically is rejected (see other bugs here).
- Steps to reproduce the problem: export backup, copy to desktop node, install, start DC
- Screenshots:
- Logs:

**Comment by hpk42** [comment]
agree, also just had a discussion with @nicodh about it.  Importing a backup on the first login screen certainly makes sense.  And if you try to import an account that already exists, you maybe get a choice of "replace existing account" or "abort import" -- or just an error "account exists".
