### ISSUE TITLE
flatpack: multiple instances are possible

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#764]
Was addressed here, but doesn't seem to work for the flatpack https://github.com/deltachat/deltachat-desktop/issues/495
At least on Lubuntu 64bit.

**Comment by muelli** [comment]
where is the lock file placed?
It may be that the new app simply cannot find that lock file because it does not share the filesystem with the old app.

cf. https://github.com/flathub/org.nextcloud.Nextcloud/issues/10
and https://github.com/notepadqq/notepadqq/issues/828#issuecomment-453922691
