### ISSUE TITLE
Open Map in a new window

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-desktop#771]
It would be nice to be able to move the map aside and continue working in in the chat list...

**Comment by Simon-Laux** [comment]
I could imagine something like a de-attach button...
But back to the technical stuff - we probably need:
- some webpack changes (second bundle for the map window?)
- different working with the state /  a new state object for the new map window
- think about whether we want the option to have multiple map window instances for different chats
- listen to location- & chat-contacts- change events

**Comment by ralphtheninja** [comment]
Pretty cool idea. You could have multiple map windows open if you want to follow several chats at the same time.
