### ISSUE TITLE
If a lot of messages are incoming, don't re-render all the time

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#781]
I was half day offline with my desktop, and then started desktop again.  Incidentally, there was quite some activity in one channel (also using location streaming etc.) and it took forever, and i had to ctrl-c and restart several times in order to catch up.  It seems that for each single incoming messages a re-render is triggered.  I think rendering should be disabled while messages are still streaming in -- i guess re-rendering after each message kind of delays the "all synced" state by an order of magnitude.

**Comment by nicodh** [comment]
One solution would be to add a debounce to handle incoming messages on start up. And with a refactored state handling it might be "cheaper" to update the chatlist...

It would also be nice to have events like RECEIVING_NEW_MESSAGES and NEW_MESSAGES_LOADED to be able to decide when to wait and when to rerender...
But that's something the Core has to provide...

**Comment by nicodh** [comment]
This should be solved with the chatlist refactoring. 1. we don't rerender the whole chat list for each incoming message but just update it while caching the the container of all other chats.
Can you confirm that the app doesn't freeze anymore?

**Comment by Jikstra** [comment]
Should be fixed. If core tells us to update the chatlist, we have to do that. Only way to fix this besides a smarter core is to only render what's in sight which would need a rewrite of the chatlist. I currently dont have performance issues, even when importing a new backup so i think it should be fixed.
