### ISSUE TITLE
Avoid superfluous renderings and refactor state handling

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-desktop#785]
Right now we have these event processings

1. DC_CORE_EVENT => handled by node DeltaChatController resulting in 2 possible actions:
	- emit an event which is handled by ipc main
	- call render() to recalculate a complete state wich is send to renderer
2. UI_EVENTs which are send to ipc main and passed to node DeltaChatController (like selectChat, searchChat etc.)
3. ELECTRON events (like setAspectRatio etc.) which are handled by ipc main

At the moment there are many events which trigger a complete rerendering (like each incoming message, DC_EVENT_LOCATION_CHANGED etc.)

A possible solution could be:
1. state is kept in renderer context since we often need the current state to decide how to react on events
2. handle most of the DC_CORE_EVENTs in renderer, node DeltaChatController emits directly to renderer ( new method sendToRenderer(evt))
3. introduce new event: EVENT_DC_FUNCTION_CALL which has a method name in payload to be called on node DeltaChatController (to avoid boilerplate in ipc main like on(searchChat) => dc.searchChat) (TODO: provide a list of "allowed" methods for security)
4. introduce new event type: DD_CHAT_LOADED, DD_LOCATIONS_UPDATED etc. which has the result data as payload
5. during migration we can move events step by step to be handled by renderer

In renderer we could use stores with to kinds of processing: "reducer" (which update the state) and "effects" which trigger new events and send them to ipc main

I suggest to have different stores which dispatch different events and hold different parts of the state. If we split the handling in different stores we are more flexible.
A store would listen only to events which are related to it's state.
The location store for example holds a state which is almost independent of the react component state, since its state is only related to map content

**Comment by Jikstra** [comment]
Lets close this, should be fixed.
