### ISSUE TITLE
Stop showing the emojipicker on hover

### ISSUE THREAD

**Issue by dignifiedquire** [deltachat/deltachat-desktop#793]
PLEASE make it on click only, instead of hover, it continues to pop in my face, even if I am just clicking on the send button

**Comment by ralphtheninja** [comment]
Haha yeah it's super annoying ;)

**Comment by r10s** [comment]
+1 for that

and if one is working on that part, i'd also suggest to remove the whole "☝️ pick your emoji!" area - this kind of hint does not match the rest of the app which is more unobtrusive and the skin selector does not really work as well as the shown shortcuts.

**Comment by r10s** [comment]
great!
