### ISSUE TITLE
Deleting account crashes

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#798]
- Platform (linux/mac/windows): linux
- Delta Chat Desktop Version: latest master
- Expected behavior: account deleted
- Actual behavior: desktop hangs and shows a thrown error in the log
- Steps to reproduce the problem: try to delete an account on first page

![Screenshot from 2019-05-19 14-22-36](https://user-images.githubusercontent.com/308049/57982144-956e2f80-7a41-11e9-92d1-04d1d5c53ec8.png)

**Comment by ralphtheninja** [comment]
@Jikstra Did you mess something up while splitting up into multiple files?

**Comment by Jikstra** [comment]
@ralphtheninja very possible. I think dc.getPath got renamed.
