### ISSUE TITLE
add oauth2 support

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-desktop#803]
Installed 0.102.0 on OS X.

Get the following error when trying to login. 

![DC_Desktop_Error](https://user-images.githubusercontent.com/5249565/58157782-5d513180-7c79-11e9-897b-27f767cf05e1.jpg)

In my Gmail-account I received a warning about a login attempt of an untrusted machine, but even after accepting further login-attempts fail showing the same error message from above.

I actually expected an oAuth2-login procedure but at least with my given credentials there wasn't guided into an oAuth2-process. 

- Platform (linux/mac/windows):
- Delta Chat Desktop Version:
- Expected behavior:
- Actual behavior:
- Steps to reproduce the problem:
- Screenshots:
- Logs:

**Comment by Jikstra** [comment]
oauth2 is currently not implemented in desktop yet, so this might be the reason why it fails. Also i think we're not disabling oauth2 currently, which doesn't even make it work if you enable unsecure apps.

**Comment by r10s** [comment]
i do not think, this is a blocker for an 1.0 release, esp. as this may take a _long_ time until we get the "okay" from google.

**Comment by pabzm** [comment]
I see this as a very desireable fix, but considering the amount of effort it probably requires I'd put it into "nice to have". So I suggest to keep it in the project for v1.0, but to throw it out if it blocks us from releasing.

**Comment by matobet** [comment]
@r10s what exactly is necessary from Google's side for this issue to more forward?

**Comment by Simon-Laux** [comment]
We would need to implement it and then make some videos again for google and have a back and forth with robots until the approve. Not fun enough that anyone one of us wants to do it right now. But if enough people want it we can go through that hassle again for desktop and iOS.
