### ISSUE TITLE
appdata file lacks 0.103.0 release

### ISSUE THREAD

**Issue by muelli** [deltachat/deltachat-desktop#804]
The appdata file does not include the 0.103.0 release.

https://github.com/deltachat/deltachat-desktop/blob/7ffaeb9911b280079ef57349e41cbf05d2ca13b6/static/chat.delta.desktop.appdata.xml#L36-L38

it would be good if the upstream file contains the new release.

**Comment by Jikstra** [comment]
Just (manually) added it. Not sure if there's an automated way of doing this?
Besides that appstream-util validate is unhappy, but the output is missing line numbers which makes it hard to fix those issues:
```
$ appstream-util validate static/chat.delta.desktop.appdata.xml                                                                                                                                                 
static/chat.delta.desktop.appdata.xml: FAILED:                                                                                                                                                                                                 
• tag-missing           : <translation> not specified                                                                                                                                                                                          
• tag-missing           : <update_contact> is not present                                                              
• style-invalid         : <p> does not end in '.|:|!' [Added]                                                          
• style-invalid         : <p> does not end in '.|:|!' [Changed]                                                        
• style-invalid         : <p> does not end in '.|:|!' [Fixed]                                                          
• style-invalid         : <li> is too long [Add setting for changing newline/message sending with enter/shift-enter/ctr-enter #662 @Simon-Laux @Jikstra] maximum is 100 chars
• style-invalid         : <p> does not end in '.|:|!' [Removed]                                                        
• style-invalid         : Too many <p> tags for a good description [4/3]                                               
• style-invalid         : <li> requires sentence case [change language dropdown to use the local names (@Simon-Laux)]                                                                                                                          
• style-invalid         : <li> is too long [For some reasons emoji-mart doesn't pull in a required dependency, we need to require it manually (@jikstra)] maximum is 100 chars
• style-invalid         : <li> is too long [Wrap application-config module for proper appConfig during production and testing (#598) (@ralphtheninja)] maximum is 100 chars
• style-invalid         : <li> is too long [Translations now based on xml and shared with other Delta Chat projects (@karissa, @Jikstra, @ralphtheninja)] maximum is 100 chars
Validation of files failed                                 
```

Any ideas @muelli ?

**Comment by muelli** [comment]
>  Not sure if there's an automated way of doing this?

If you have the release information somewhere (e.g. git tags) then you could probably script something.

The appdata tags are described here: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-update_contact
I wonder why that particular tag was removed. It's present here: https://github.com/flathub/chat.delta.desktop/blob/f6a65ca32533f5c857175c6cf3b9ec8ad0f36963/chat.delta.desktop.appdata.xml#L279

**Comment by Jikstra** [comment]
We can reopen this one if flatpaks work with the rust core

**Comment by muelli** [comment]
FWIW: appdata is not a flatpak or flathub thing. It's a desktop thing. And other distributions care about nice appstream data, too.

Reg. Rust: The latest release (v.0.104.0) uses a version of deltachat-node which is broken, i.e. it uses a variable that doesn't exist in core, AFAIU, cf. https://github.com/flathub/chat.delta.desktop/pull/20#issuecomment-509034471.
Once there is a new release, we can try again and the dependencies have then hopefully been worked out to actually compile.
