### ISSUE TITLE
Implement profile view

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#808]
Or the chat with that contact..
Or a menu with options like view profile/ block contact / chat with contact

**Comment by r10s** [comment]
on android, we open a profile with the tabs members|gallery|documents - more tabs as "links" and "map" are planned. afaik, on ios it is meanwhile similar (cc @nayooti)

**Comment by nayooti** [comment]
I was going to implement exactly that in iOS in my next pull request.

Outlook für iOS<https://aka.ms/o0ukef> beziehen

________________________________
Von: björn petersen <notifications@github.com>
Gesendet: Samstag, Mai 25, 2019 5:46 PM
An: deltachat/deltachat-desktop
Cc: nayooti; Mention
Betreff: Re: [deltachat/deltachat-desktop] Click on name in group chat should open a profile view of that contact. (#808)


on android, we open a profile with the tabs members|gallery|documents - more tabs as "links" and "map" are planned. afaik, on ios it is meanwhile similar (cc @nayooti<https://github.com/nayooti>)
