### ISSUE TITLE
  New login from desktop client doesn't show old messages made on mobile app

### ISSUE THREAD

**Issue by beenotung** [deltachat/deltachat-desktop#812]
New login from desktop client doesn't show old messages made on mobile app.

The messages on email server are stored in separated folder 'DeltaChat' so it should be distinguishable between delta chat messages and normal email (in fact, I setup that email account only for delta chat)

- Platform (linux/mac/windows): linux
- Delta Chat Desktop Version: 0.103.0-PREVIEW
- Expected behavior: after plenty of time, the desktop client should shows old messages made send/received as on mobile app.
- Actual behavior: the chat list is empty, when I manually create a new chat and send out a message, the desktop only show the new message; the mobile shows both old and new messages
- Steps to reproduce the problem:
1. install and login deltachat on mobile phone (android in my case)
2. chat with a friend using the mobile app deltachat
3. fresh install deltachat desktop on archlinux
4. login the same account from the deltachat desktop
5. the chat list is shown empty

- Logs:
[2019-05-27T03:20:21.784Z.log](https://github.com/deltachat/deltachat-desktop/files/3221738/2019-05-27T03.20.21.784Z.log)

**Comment by Simon-Laux** [comment]
This behavior isn't implemented yet. 
I think it's no different the other way around (when you start with desktop).
So I would say this is rather an core issue/feature request or something for the forum - In fact there is already a discussion about your problem/idea over there https://support.delta.chat/t/desktop-app-and-previous-chats-not-showing-up/174

**Comment by Jikstra** [comment]
Yup this is a core decision, would like to have that feature too!

Closing to keep issue tracker clean :)
