### ISSUE TITLE
DS 0.103.0 crashes on importing backup

### ISSUE THREAD

**Issue by g6094199** [deltachat/deltachat-desktop#815]
- Platform (linux/mac/windows): Ubuntu Budgie 19.04
- Delta Chat Desktop Version: used Jikstras rpgp build from here: https://github.com/deltachat/deltachat-desktop/issues/806#issuecomment-496122040  (non flatpak)
- Expected behavior: import backup flawlessly
- Actual behavior: DS crashes instantly on hitting "open" when selected the DS bak file.
- Steps to reproduce the problem: backuped from DS 0.102.0 (latest flatpak version)
- Screenshots:
- Logs: 
"2019-05-27T09:09:01.435Z"      "main/index"    "INFO"  []      "cwd /home/xxx/.config/DeltaChat"
"2019-05-27T09:09:01.484Z"      "main/menu"     "INFO"  []      "rebuilding menu with locale en"
"2019-05-27T09:09:04.474Z"      "main/state"    "INFO"  []      "Saving state to /home/xxx/.config/DeltaChat/config.json"
"2019-05-27T09:09:10.829Z"      "main/menu"     "INFO"  []      "rebuilding menu with locale de"
"2019-05-27T09:09:11.787Z"      "main/state"    "INFO"  []      "Saving state to /home/xxx/.config/DeltaChat/config.json"
"2019-05-27T09:09:44.201Z"      "main/deltachat/login"  "INFO"  []      "Using deltachat instance /home/xxx/.config/DeltaChat/6f647973736575735f68656c645f6465725f616e74696b65407765622e6465"
"2019-05-27T09:09:48.235Z"      "main/deltachat"        "WARNING"       [{"columnNumber":11,"lineNumber":114,"fileName":"/opt/DeltaChat/resources/app.asar/src/main/deltachat/index.js","functionName":"DeltaChat.dc$
"2019-05-27T09:09:48.236Z"      "main/deltachat"        "WARNING"       [{"columnNumber":11,"lineNumber":114,"fileName":"/opt/DeltaChat/resources/app.asar/src/main/deltachat/index.js","functionName":"DeltaChat.dc$
"2019-05-27T09:09:48.237Z"      "main/deltachat"        "WARNING"       [{"columnNumber":11,"lineNumber":114,"fileName":"/opt/DeltaChat/resources/app.asar/src/main/deltachat/index.js","functionName":"DeltaChat.dc$
"2019-05-27T09:09:48.237Z"      "main/deltachat"        "WARNING"       [{"columnNumber":11,"lineNumber":114,"fileName":"/opt/DeltaChat/resources/app.asar/src/main/deltachat/index.js","functionName":"DeltaChat.dc$
"2019-05-27T09:09:48.238Z"      "main/deltachat"        "WARNING"       [{"columnNumber":11,"lineNumber":114,"fileName":"/opt/DeltaChat/resources/app.asar/src/main/deltachat/index.js","functionName":"DeltaChat.dc$
"2019-05-27T09:09:48.239Z"      "main/deltachat"        "WARNING"       [{"columnNumber":11,"lineNumber":114,"fileName":"/opt/DeltaChat/resources/app.asar/src/main/deltachat/index.js","functionName":"DeltaChat.dc$
"2019-05-27T09:10:03.502Z"      "main/deltachat/login"  "INFO"  []      "Ready"
"2019-05-27T09:10:03.505Z"      "main/deltachat/login"  "INFO"  []      "dc_get_info"   {"deltachat_core_version":"v0.43.0","sqlite_version":"3.27.2","sqlite_thread_safe":"1","libetpan_version":"1.8","openssl_ver$
"2019-05-27T09:10:04.502Z"      "main/state"    "INFO"  []      "Saving state to /home/xxx/.config/DeltaChat/config.json"
"2019-05-27T09:10:07.714Z"      "main/state"    "INFO"  []      "Saving state to /home/xxx/.config/DeltaChat/config.json"
"2019-05-27T09:10:21.690Z"      "main/index"    "ERROR" [{"columnNumber":7,"lineNumber":27,"fileName":"/opt/DeltaChat/resources/app.asar/src/main/index.js","functionName":"process.on","source":"    at process.on $
"2019-05-27T09:10:30.439Z"	"main/index"	"INFO"	[]	"cwd /home/masterb/.config/DeltaChat"
"2019-05-27T09:10:30.447Z"	"main/deltachat/login"	"INFO"	[]	"Using deltachat instance /home/masterb/.config/DeltaChat/6f647973736575735f68656c645f6465725f616e74696b65407765622e6465"
"2019-05-27T09:10:30.481Z"	"main/menu"	"INFO"	[]	"rebuilding menu with locale de"
"2019-05-27T09:10:30.526Z"	"main/deltachat/login"	"INFO"	[]	"Ready"
"2019-05-27T09:10:30.531Z"	"main/deltachat/login"	"INFO"	[]	"dc_get_info"	{"deltachat_core_version":"v0.43.0","sqlite_version":"3.27.2","sqlite_thread_safe":"1","libetpan_version":"1.8","openssl_version":"1.1.1b","rpgp_enabled":"1","compile_date":"May 22 2019, 23:51:10","arch":"64","number_of_chats":"0","number_of_chat_messages":"0","messages_in_contact_requests":"0","number_of_contacts":"0","database_dir":"/home/masterb/.config/DeltaChat/6f647973736575735f68656c645f6465725f616e74696b65407765622e6465/db.sqlite","database_version":"55","blobdir":"/home/xxx/.config/DeltaChat/6f647973736575735f68656c645f6465725f616e74696b65407765622e6465/db.sqlite-blobs","display_name":"0","is_configured":"1","entered_account_settings":"xxxx@web.de 0:***:0:0 0:0:0:0 0","used_account_settings":"xxx@web.de xxx:***:imap.web.de:993 xxx:***:smtp.web.de:587 AUTH_NORMAL IMAP_SSL SMTP_STARTTLS","inbox_watch":"1","sentbox_watch":"1","mvbox_watch":"1","mvbox_move":"1","folders_configured":"3","configured_sentbox_folder":"Gesendet","configured_mvbox_folder":"DeltaChat","mdns_enabled":"0","e2ee_enabled":"1","private_key_count":"1","public_key_count":"0","fingerprint":"0BFA3E444E2993410AD6FFDFC2D0AB7470035656"}
"2019-05-27T09:10:32.506Z"	"main/state"	"INFO"	[]	"Saving state to /home/masterb/.config/DeltaChat/config.json"
"2019-05-27T09:10:33.522Z"	"main/state"	"INFO"	[]	"Saving state to /home/masterb/.config/DeltaChat/config.json"
"2019-05-27T09:10:45.126Z"	"main/index"	"ERROR"	[{"columnNumber":7,"lineNumber":27,"fileName":"/opt/DeltaChat/resources/app.asar/src/main/index.js","functionName":"process.on","source":"    at process.on (/opt/DeltaChat/resources/app.asar/src/main/index.js:27:7)"},{"columnNumber":15,"lineNumber":187,"fileName":"events.js","functionName":"process.emit","source":"    at process.emit (events.js:187:15)"},{"columnNumber":27,"lineNumber":488,"fileName":"internal/bootstrap/node.js","functionName":"process._fatalException","source":"    at process._fatalException (internal/bootstrap/node.js:488:27)"}]	"uncaughtError"	{"message":"dc.backupImport is not a function","stack":"TypeError: dc.backupImport is not a function\n    at EventEmitter.ipcMain.on (/opt/DeltaChat/resources/app.asar/src/main/ipc.js:168:50)\n    at EventEmitter.emit (events.js:182:13)\n    at WebContents.<anonymous> (/opt/DeltaChat/resources/electron.asar/browser/api/web-contents.js:346:13)\n    at WebContents.emit (events.js:182:13)"}

**Comment by Simon-Laux** [comment]
Its broken right now #506
