### ISSUE TITLE
Media View - Autocrypt files should not be shown together with the files

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#816]
IMHO

**Comment by Jikstra** [comment]
Seems to be the same on android the same, so probably a core bug.

**Comment by hpk42** [comment]
we discussed that UI issues that have a core correspondent issue should stay open.

**Comment by Simon-Laux** [comment]
moved discussion about this to a forum feature proposal: https://support.delta.chat/t/hide-autocrypt-html-in-gallery/1223
I'll close this for now.
