### ISSUE TITLE
contact request do not work

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#82]
contact requests are displayed in the chatlist and clicking on it shows the question "Chat with NAME - Yes - No - Never", however, clicking on yes, no chat with the contact is created.

creating the chat manually works then.

also, the question should include the email-address and not only the name, i would suggest to use [dc_get_contact_name_n_addr()](https://c.delta.chat/classdc__contact__t.html#a16056431c6926d327f5728ad3ddd4fdf) here which takes care eg. not showing the address twice if the name is unset.

**Comment by karissa** [comment]
this shoudl be fixed now
