### ISSUE TITLE
Empty list of contacts in verified group

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#821]
![Screenshot from 2019-05-27 23-59-56](https://user-images.githubusercontent.com/308049/58440625-9bb47980-80db-11e9-8799-caff3cd4d35a.png)

**Comment by nicodh** [comment]
Can't reproduce this. Is it still an issue?

<img width="804" alt="verified-group" src="https://user-images.githubusercontent.com/1428457/59550520-d2a7dd80-8f6b-11e9-8125-193a7593a2c2.png">

**Comment by ralphtheninja** [comment]
I deleted the group so can't reproduce.
