### ISSUE TITLE
blob_storage/ folder created in ~/.config/DeltaChat

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#822]
It seems desktop creates a `blob_folder/` on the wrong level during startup. (~/.config/DeltaChat is linux specific though).

**Comment by Simon-Laux** [comment]
There was a bug before (not sure if we fixed it) where a deltachat db was created at every folder in the config folder.

**Comment by Simon-Laux** [comment]
blob_storage/ is an electron specific thing, nothing to worry about. Our db blob folders are called `db.sqlite-blobs`
