### ISSUE TITLE
title in chat view

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#83]
the title in the chat view should be left-aligned and contain the name ([dc_chat_get_name()](https://c.delta.chat/classdc__chat__t.html#a0fb1b4850bcd899eaa06d23648a1efaf)) and the subtitle below ([dc_chat_get_subtitle()](https://c.delta.chat/classdc__chat__t.html#a1508279f522decd5e404e4c4fa42adf4)). the subtitle contains typically the e-mail-address or the number of members in a group.

left of that, i would display the avatar.

**Comment by karissa** [comment]
fixed, although the avatar might need some CSS love
