### ISSUE TITLE
New group not showing up directy. It's there after restart.

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#831]
- Platform (linux/mac/windows): linux
- Delta Chat Desktop Version: chatlist-refactoring branch
- Expected behavior: group is added
- Actual behavior: group is not shown until application has been restarted
- Steps to reproduce the problem: invite someone to a group and send a message to it
- Screenshots:
- Logs:

**Comment by Jikstra** [comment]
Yup this is one of the things why i haven't merged the refactoring stuff of nico yet, there's still some stuff which is not ready yet. Not sure how to proceed, as it implements quite some new stuff. We could merge it and see if we can fix it ourselves without nico?

**Comment by Jikstra** [comment]
This also happens when i'm accepting a contact request. Seems like we need to redraw the chatlist or do something there.

**Comment by ralphtheninja** [comment]
> We could merge it and see if we can fix it ourselves without nico?

Yes.

**Comment by nicodh** [comment]
I think for now it should be sufficient to call dc.updateChatList on all events that need a complete rerendering of the chat list, in this case DC_EVENT_CHAT_MODIFIED.
Later we might improve that by just adding a new created chat.
