### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#838]
Missing translations:
- [x] {tx(`a11y_delivery_status_${status}`)}
- [x] tx(key, diff.minutes() etc.

You need to check these by hand:
src/renderer/components/message/MessageMetaData.js:76:            aria-label={tx(`a11y_delivery_status_${status}`)}
src/renderer/components/conversations/formatRelativeTime.js:43:    return tx(key, diff.hours(), { quantity: diff.hours() === 1 ? 'one' : 'other' })
src/renderer/components/conversations/formatRelativeTime.js:47:    return tx(key, diff.minutes(), { quantity: diff.minutes() === 1 ? 'one' : 'other' })

**Comment by Simon-Laux** [comment]
We should make a new script to extract all missing Language strings.
@Jikstra what's your opinion on this?

**Comment by Jikstra** [comment]
@Simon-Laux  Not sure how easy this is. as long as we're always using `tx('somestring')` it maybe is, but as soon as we dynamically create those language strings it's going to get hard.

**Comment by Simon-Laux** [comment]
Missing translations:
- [ ] DC_STR_E2E_AVAILABLE
- [ ] DC_STR_ENCR_NONE
- [ ] DC_STR_ENCR_TRANSP
- [ ] DC_STR_STARREDMSGS
- [ ] id
- [ ] imageFailedToLoad
- [ ] incomingError
- [ ] retrySend
- [ ] sendAnyway
- [ ] sendFailed
- [ ] showSafetyNumber
- [ ] this.state.buttonLabel
- [ ] this.state.heading
- [ ] videoScreenshotFailedToLoad

You need to check these by hand:
src/renderer/components/conversations/formatRelativeTime.js:    return tx(key, diff.hours(), { quantity: diff.hours() === 1 ? 'one' : 'other' })
src/renderer/components/conversations/formatRelativeTime.js:    return tx(key, diff.minutes(), { quantity: diff.minutes() === 1 ? 'one' : 'other' })
src/renderer/components/GroupBase.js:              <NavbarHeading>{tx(this.state.heading)}</NavbarHeading>
src/renderer/components/GroupBase.js:                text={tx(this.state.buttonLabel)} />
src/renderer/components/Media.js:            {tx(id)}
src/renderer/components/ChatList.js:    const missingChatsMsg = tx(showArchivedChats ? 'no_archived_chats_desktop' : 'no_chats_desktop')

**Comment by nicodh** [comment]
I removed disabledReason from list, since it's a variable holding a string ('messaging_disabled_deaddrop' or 'messaging_disabled_not_in_group')

**Comment by nicodh** [comment]
the same applies for tx(id) where id is a variable holding one of these strings: 'images', 'video', 'audio' or 'documents'

**Comment by nicodh** [comment]
I can't find any usage or occurrence of these strings:
DC_STR_E2E_AVAILABLE
DC_STR_ENCR_NONE
DC_STR_ENCR_TRANSP
DC_STR_STARREDMSGS
so might be obsolete?
