### ISSUE TITLE
Desktop crashes when receiving new messages

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-desktop#839]
When I switched to an account with many new messages (since I didn't open it on desktop for a while) a lot of updates went fine, but in certain messages it crashes.

Here is the Electron crash report:

Thread 34 Crashed:
0   libsystem_c.dylib             	0x00007fffa3ca3b88 strlen + 72
1   deltachat.node                	0x00000001176bef3e std::ffi::c_str::CStr::from_ptr::h6224eb7cd72db243 + 14 (c_str.rs:965)
2   deltachat.node                	0x0000000117652ccc mmime::other::strncasecmp::he0005679c3c28014 + 28
3   deltachat.node                	0x000000011763f7d7 mmime::mailimf::mailimf_orig_date_parse::h93e4a9741561246d + 103
4   deltachat.node                	0x00000001176402bd mmime::mailimf::mailimf_envelope_field_parse::h6106b649cb9c5a09 + 221
5   deltachat.node                	0x0000000117640ed0 mmime::mailimf::mailimf_envelope_or_optional_field_parse::hd10443423c04b7c3 (.llvm.16151979463355521931) + 48
6   deltachat.node                	0x000000011763e602 mmime::mailimf::mailimf_struct_multiple_parse::h0c70b1ba8c736a79 (.llvm.16151979463355521931) + 274
7   deltachat.node                	0x0000000117640db1 mmime::mailimf::mailimf_envelope_and_optional_fields_parse::h3fea947ced0ddb23 + 65
8   deltachat.node                	0x00000001176417bf mmime::mailmime_content::mailmime_parse_with_default::hc2021c281a34f4b7 + 863
9   deltachat.node                	0x000000011764136c mmime::mailmime_content::mailmime_parse::hd91e783cef30081e + 204
10  deltachat.node                	0x0000000116e82617 deltachat::dc_mimeparser::dc_mimeparser_parse::hf4703c07e5fd9506 + 71
11  deltachat.node                	0x0000000116f01da5 deltachat::dc_receive_imf::dc_receive_imf::ha2a374909929caf1 + 309
12  deltachat.node                	0x0000000116e30f7e deltachat::imap::Imap::fetch_from_single_folder::h52c06c681f0b954c (.llvm.5819355893458355865) + 9550
13  deltachat.node                	0x0000000116e2d4ae deltachat::imap::Imap::fetch::h1b629bc184ab8ae5 + 318
14  deltachat.node                	0x0000000116e49d9f deltachat::dc_job::dc_perform_imap_fetch::hacbe2649b4cf2383 + 399
15  deltachat.node                	0x0000000116e1b8de dc_perform_imap_fetch + 14
16  deltachat.node                	0x0000000116e0eec6 imap_thread_func + 118 (module.c:165)
17  libsystem_pthread.dylib       	0x00007fffa3e8693b _pthread_body + 180
18  libsystem_pthread.dylib       	0x00007fffa3e86887 _pthread_start + 286
19  libsystem_pthread.dylib       	0x00007fffa3e8608d thread_start + 13

In all crash reports std::ffi::c_str::CStr::from_ptr:  seems to cause the crash...

**Comment by Jikstra** [comment]
Which -core version do you use?

**Comment by nicodh** [comment]
Ah - my fault - I copied an older version into node modules...
So that was probably an older bug...
