### ISSUE TITLE
Typing a message slows down ui

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#852]
I guess this is because of the setDraft thing not being async.

**Comment by nicodh** [comment]
No - since afa89564a02b it is not async any more. Can you try to debug with react debugger what happens?
Even the update of the draft in the chat list is not depending on the response from the server but is done in the reducer of chatListStore...

**Comment by Jikstra** [comment]
Hmm you're right, will close it for now and investigate it further. Can't reproduce right now.
