### ISSUE TITLE
Windows: not sending/receiving 

### ISSUE THREAD

**Issue by MIntrovrt** [deltachat/deltachat-desktop#853]
- Platform (linux/mac/windows): Windows
- Delta Chat Desktop Version: 0.104.0 Preview
- Expected behavior: pushing mails to the server / requesting mails from the server
- Actual behavior: keeps loading, but connected to the mailserver (login showed up in logfile of mailserver)
- Steps to reproduce the problem: npm run dev, it should just not work..
- Screenshots: 
- Logs:

**Comment by ralphtheninja** [comment]
32 bit windows?

**Comment by MIntrovrt** [comment]
64Bit windows 10 pro 1903

**Comment by MIntrovrt** [comment]
It is probably also worth mentioning that I can access that mailaccount with thunderbird no problem from the same devices.

**Comment by ralphtheninja** [comment]
Maybe you can bring your computer to bb33 and @Jikstra or someone else could help you debug this. Impossible to know what's wrong given this report.

**Comment by Jikstra** [comment]
@MIntrovrt can you provide any logs?

**Comment by ralphtheninja** [comment]
Might be worth it to try that account on linux or mac as well, just to rule out it's not related to windows only.

**Comment by MIntrovrt** [comment]
yeah i will try that account on linux. somehow i just found this "SMTP failed to send message: connection refused" in the output of npm. i suspect the restrictiveness of my mailserver might be messing with it. It only allows StartTLS and encryped passwords, so that might be why my mailserver is refusing to work. ill try it with another server just to make sure.

**Comment by MIntrovrt** [comment]
okay that problem just solved itself. its the policy on my mailserver.

**Comment by ralphtheninja** [comment]
@MIntrovrt Aaah ok. All good then, for now :wink:

**Comment by Jikstra** [comment]
@MIntrovrt try out the advanced settings and enforce starttls for imap/smtp, than you should be able to make it work.

**Comment by ralphtheninja** [comment]
@Jikstra I'm wondering if we somehow can detect these sort of problems and make a suggestion?

**Comment by Jikstra** [comment]
@ralphtheninja i think the problem is that we currently don't show a good error in the ui if something weird happend. Not sure.

**Comment by MIntrovrt** [comment]
Yeah, just showing an error would be helpful. I mean, it detected it couldnt send even though it knew the server worked.
