### ISSUE TITLE
all "watch" checkboxes disabled after fresh installation on mac

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#875]
first of all, great work to have a mac version with the rust core!

to the issue:
I setup a new account on mac, login and sending works as expected, however, I did not manage to _receive_ any messages.

looking around in the app, I noticed that non if the "watch inbox/sendbox/mvbox" flags were enabled. enabling at least inbox fixes the problem completely for me :)

EDIT: 0.105.0-pre1-PREVIEW has the problem,
0.104 is fine at lest on Mac

**Comment by r10s** [comment]
just teste to create a fresh account with the most recent rust-cli-tool, there the flags are set as expected. so this issue is probably related to the desktop code and not the the rust-core.

**Comment by nicodh** [comment]
seems to be introduced with https://github.com/deltachat/deltachat-node/commit/929d64da2ece8c16055f3e65d8bd2d80d5a9c24f - if I uncomment this.setConfig('inbox_watch', String(opts.inbox_watch ? 1 : 0)) etc. it loads correct defaults

**Comment by ralphtheninja** [comment]
So we pass incorrect settings that override defaults? Wondering where to fix this.
