### ISSUE TITLE
Issue about Turkish

### ISSUE THREAD

**Issue by OzancanKaratas** [deltachat/deltachat-desktop#877]
Hi,

I have installed Windows version of DeltaChat. It does not contain a language setting, and did not recognized my system language.
Now I cannot test my localized content. What is the resource of this problem?

Thanks.

**Comment by Simon-Laux** [comment]
Isn't it in the top toolbar under `Preferences` -> `choose language`?
![2019-06-29_15-28](https://user-images.githubusercontent.com/18725968/60384792-876cef00-9a82-11e9-98c1-9ce661bd5c49.png)

**Comment by OzancanKaratas** [comment]
Unfortunetely I didn't found a setting about language. I think DeltaChat should recognize the system language automatically.

**Comment by Simon-Laux** [comment]
You didn't found anything related to language, even after looking at the screenshot I sent?

We can talk about auto detection but please in a dedicated issue, because auto-detection isn't implemented for any language yet.

**Comment by OzancanKaratas** [comment]
No option about language selection. Also I am blind. I cannot see the screenshots.

**Comment by ralphtheninja** [comment]
@OzancanKaratas Thanks for your report. What would be the best case for you if you could have it your way? I agree that delta chat should use the system language, if not already set.

**Comment by ralphtheninja** [comment]
There is a getLocale() api in electron https://electronjs.org/docs/api/locales which we also use in desktop. It might also be a bug that never makes it pick the system locale.

**Comment by Simon-Laux** [comment]
@OzancanKaratas can you tell us what you would expect from an deltachat client for blind people?
I think that would be easier to develop than making deltachat desktop electron accessible.

**Comment by OzancanKaratas** [comment]
I think the problem occurs in Windows build only. Because the settings menu sometimes appears, and sometimes doesn't appears. I have using 1920x1080 resolution, program interface is very small. I will review the code for Windows. So this is not just a language problem.

**Comment by Simon-Laux** [comment]
It's not in the settings menue - its in the top bar that contains File, Edit, View, Preferences, Help.
Under Preferences you can select choose language and then you get a list of available languages

**Comment by Simon-Laux** [comment]
> I will review the code for Windows

You don't need to review any code it's the same code for all desktop platforms - thats the power of electron.

**Comment by OzancanKaratas** [comment]
I will refer another computers and some Linux distributions. If this problem continues, it means due to my fault.

**Comment by Jikstra** [comment]
@OzancanKaratas thanks for investigating this further :)

**Comment by OzancanKaratas** [comment]
Menu bar was not displaying. However it is now showing in new version. This issue was closed after the problem was fixed.

Thank you for your interest.
