### ISSUE TITLE
invitation didn't appear until interacting with the interface

### ISSUE THREAD

**Issue by rawrrawrfox** [deltachat/deltachat-desktop#880]
- OS: arch linux

- Delta Chat Desktop Version: 0.105.0-pre1-PREVIEW

- Expected behavior: 
receive an invitation from a user

- Actual behavior: 
didn't receive invitation until i pressed the menu button on the top right and clicked "new chat" then after like a second the invitation appeared

- Steps to reproduce the problem:
make new email account, never used delta chat before either
log in
ask someone to invite you
wait until they tell you they've invited you
press top right menu button (the one with the 3 dots vertically aligned)
press the "New Chat" button
the notification should now appear

- Screenshots:
sorry i didn't take any, but i dont think there's much to see anyway

- Logs:
"2019-06-30T12:56:44.078Z"	"main/index"	"INFO"	[]	"cwd /home/rawr/.config/DeltaChat"
"2019-06-30T12:56:44.110Z"	"main/menu"	"INFO"	[]	"rebuilding menu with locale en"
"2019-06-30T12:56:46.935Z"	"main/state"	"INFO"	[]	"Saving state to /home/rawr/.config/DeltaChat/config.json"
"2019-06-30T12:56:52.559Z"	"main/mainWindow"	"INFO"	[]	"toggleDevTools"
"2019-06-30T12:57:16.227Z"	"main/state"	"INFO"	[]	"Saving state to /home/rawr/.config/DeltaChat/config.json"
"2019-06-30T12:57:44.020Z"	"main/deltachat/login"	"INFO"	[]	"Using deltachat instance /home/rawr/.config/DeltaChat/7261777272617772666f78407269736575702e6e6574"
"2019-06-30T12:57:44.763Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":145,"fileName":"/opt/DeltaChat/rawrtron_app/src/main/deltachat/index.js","functionName":"DeltaChat.dc.on","source":"    at DeltaChat.dc.on (/opt/DeltaChat/rawrtron_app/src/main/deltachat/index.js:145:11)"},{"columnNumber":13,"lineNumber":182,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:182:13)"},{"columnNumber":12,"lineNumber":739,"fileName":"/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"handleEvent","source":"    at handleEvent (/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js:739:12)"},{"columnNumber":7,"lineNumber":35,"fileName":"/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"DeltaChat.binding.dcn_set_event_handler","source":"    at DeltaChat.binding.dcn_set_event_handler (/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js:35:7)"}]	"Not configured, cannot connect."
"2019-06-30T12:57:44.764Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":145,"fileName":"/opt/DeltaChat/rawrtron_app/src/main/deltachat/index.js","functionName":"DeltaChat.dc.on","source":"    at DeltaChat.dc.on (/opt/DeltaChat/rawrtron_app/src/main/deltachat/index.js:145:11)"},{"columnNumber":13,"lineNumber":182,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:182:13)"},{"columnNumber":12,"lineNumber":739,"fileName":"/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"handleEvent","source":"    at handleEvent (/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js:739:12)"},{"columnNumber":7,"lineNumber":35,"fileName":"/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"DeltaChat.binding.dcn_set_event_handler","source":"    at DeltaChat.binding.dcn_set_event_handler (/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js:35:7)"}]	"Not configured, cannot connect."
"2019-06-30T12:57:44.765Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":145,"fileName":"/opt/DeltaChat/rawrtron_app/src/main/deltachat/index.js","functionName":"DeltaChat.dc.on","source":"    at DeltaChat.dc.on (/opt/DeltaChat/rawrtron_app/src/main/deltachat/index.js:145:11)"},{"columnNumber":13,"lineNumber":182,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:182:13)"},{"columnNumber":12,"lineNumber":739,"fileName":"/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"handleEvent","source":"    at handleEvent (/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js:739:12)"},{"columnNumber":7,"lineNumber":35,"fileName":"/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"DeltaChat.binding.dcn_set_event_handler","source":"    at DeltaChat.binding.dcn_set_event_handler (/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js:35:7)"}]	"Not configured, cannot connect."
"2019-06-30T12:57:44.765Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":145,"fileName":"/opt/DeltaChat/rawrtron_app/src/main/deltachat/index.js","functionName":"DeltaChat.dc.on","source":"    at DeltaChat.dc.on (/opt/DeltaChat/rawrtron_app/src/main/deltachat/index.js:145:11)"},{"columnNumber":13,"lineNumber":182,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:182:13)"},{"columnNumber":12,"lineNumber":739,"fileName":"/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"handleEvent","source":"    at handleEvent (/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js:739:12)"},{"columnNumber":7,"lineNumber":35,"fileName":"/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"DeltaChat.binding.dcn_set_event_handler","source":"    at DeltaChat.binding.dcn_set_event_handler (/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js:35:7)"}]	"Not configured, cannot connect."
"2019-06-30T12:57:44.765Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":145,"fileName":"/opt/DeltaChat/rawrtron_app/src/main/deltachat/index.js","functionName":"DeltaChat.dc.on","source":"    at DeltaChat.dc.on (/opt/DeltaChat/rawrtron_app/src/main/deltachat/index.js:145:11)"},{"columnNumber":13,"lineNumber":182,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:182:13)"},{"columnNumber":12,"lineNumber":739,"fileName":"/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"handleEvent","source":"    at handleEvent (/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js:739:12)"},{"columnNumber":7,"lineNumber":35,"fileName":"/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"DeltaChat.binding.dcn_set_event_handler","source":"    at DeltaChat.binding.dcn_set_event_handler (/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js:35:7)"}]	"Not configured, cannot connect."
"2019-06-30T12:57:44.766Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":145,"fileName":"/opt/DeltaChat/rawrtron_app/src/main/deltachat/index.js","functionName":"DeltaChat.dc.on","source":"    at DeltaChat.dc.on (/opt/DeltaChat/rawrtron_app/src/main/deltachat/index.js:145:11)"},{"columnNumber":13,"lineNumber":182,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:182:13)"},{"columnNumber":12,"lineNumber":739,"fileName":"/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"handleEvent","source":"    at handleEvent (/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js:739:12)"},{"columnNumber":7,"lineNumber":35,"fileName":"/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"DeltaChat.binding.dcn_set_event_handler","source":"    at DeltaChat.binding.dcn_set_event_handler (/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js:35:7)"}]	"Not configured, cannot connect."
"2019-06-30T12:57:44.766Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":145,"fileName":"/opt/DeltaChat/rawrtron_app/src/main/deltachat/index.js","functionName":"DeltaChat.dc.on","source":"    at DeltaChat.dc.on (/opt/DeltaChat/rawrtron_app/src/main/deltachat/index.js:145:11)"},{"columnNumber":13,"lineNumber":182,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:182:13)"},{"columnNumber":12,"lineNumber":739,"fileName":"/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"handleEvent","source":"    at handleEvent (/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js:739:12)"},{"columnNumber":7,"lineNumber":35,"fileName":"/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"DeltaChat.binding.dcn_set_event_handler","source":"    at DeltaChat.binding.dcn_set_event_handler (/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js:35:7)"}]	"Not configured, cannot connect."
"2019-06-30T12:57:44.766Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":145,"fileName":"/opt/DeltaChat/rawrtron_app/src/main/deltachat/index.js","functionName":"DeltaChat.dc.on","source":"    at DeltaChat.dc.on (/opt/DeltaChat/rawrtron_app/src/main/deltachat/index.js:145:11)"},{"columnNumber":13,"lineNumber":182,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:182:13)"},{"columnNumber":12,"lineNumber":739,"fileName":"/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"handleEvent","source":"    at handleEvent (/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js:739:12)"},{"columnNumber":7,"lineNumber":35,"fileName":"/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"DeltaChat.binding.dcn_set_event_handler","source":"    at DeltaChat.binding.dcn_set_event_handler (/opt/DeltaChat/rawrtron_app/node_modules/deltachat-node/lib/deltachat.js:35:7)"}]	"Not configured, cannot connect."
"2019-06-30T12:57:48.815Z"	"main/deltachat/login"	"INFO"	[]	"Ready"
"2019-06-30T12:57:48.820Z"	"main/deltachat/login"	"INFO"	[]	"dc_get_info"	{"deltachat_core_version":"v1.0.0-alpha.0","sqlite_version":"3.27.2","sqlite_thread_safe":"1","compile_date":"Apr 26 2019, 00:51:50","arch":"64","number_of_chats":"0","number_of_chat_messages":"0","messages_in_contact_requests":"0","number_of_contacts":"0","database_dir":"/home/rawr/.config/DeltaChat/7261777272617772666f78407269736575702e6e6574/db.sqlite","database_version":"55","blobdir":"/home/rawr/.config/DeltaChat/7261777272617772666f78407269736575702e6e6574/db.sqlite-blobs","display_name":"0","is_configured":"1","entered_account_settings":"rawrrawrfox@riseup.net 0:***:0:0 0:0:0:0 0","used_account_settings":"rawrrawrfox@riseup.net rawrrawrfox:***:imap.riseup.net:993 rawrrawrfox:***:mail.riseup.net:465 AUTH_NORMAL IMAP_SSL SMTP_SSL","inbox_watch":"0","sentbox_watch":"0","mvbox_watch":"0","mvbox_move":"0","folders_configured":"3","configured_sentbox_folder":"<unset>","configured_mvbox_folder":"<unset>","mdns_enabled":"0","e2ee_enabled":"1","private_key_count":"1","public_key_count":"0","fingerprint":"7620234E26139EDE27DD7E147473470B4FA2CC23","level":"awesome"}
"2019-06-30T12:57:49.817Z"	"main/state"	"INFO"	[]	"Saving state to /home/rawr/.config/DeltaChat/config.json"
"2019-06-30T12:57:53.104Z"	"main/state"	"INFO"	[]	"Saving state to /home/rawr/.config/DeltaChat/config.json"
"2019-06-30T12:58:44.941Z"	"main/deltachat/settings"	"INFO"	[]	"Setting config inbox_watch:1"
"2019-06-30T12:58:49.811Z"	"main/deltachat/settings"	"INFO"	[]	"Setting config sentbox_watch:1"
"2019-06-30T12:58:50.993Z"	"main/deltachat/settings"	"INFO"	[]	"Setting config mvbox_watch:1"
"2019-06-30T12:58:56.078Z"	"main/deltachat/settings"	"INFO"	[]	"Setting config mvbox_move:1"
"2019-06-30T12:59:45.938Z"	"main/state"	"INFO"	[]	"Saving state to /home/rawr/.config/DeltaChat/config.json"
"2019-06-30T13:18:07.325Z"	"main/state"	"INFO"	[]	"Saving state to /home/rawr/.config/DeltaChat/config.json"
"2019-06-30T13:20:14.028Z"	"main/deltachat/chatmethods"	"INFO"	[]	"chat with dead drop [object Object]"
"2019-06-30T13:20:14.118Z"	"main/deltachat/chatmethods"	"INFO"	[]	"Added contact mela_sapiens (mela_sapiens@riseup.net)"
"2019-06-30T13:20:50.389Z"	"main/state"	"INFO"	[]	"Saving state to /home/rawr/.config/DeltaChat/config.json"
"2019-06-30T13:21:02.807Z"	"main/state"	"INFO"	[]	"Saving state to /home/rawr/.config/DeltaChat/config.json"
"2019-06-30T14:09:42.820Z"	"main/state"	"INFO"	[]	"Saving state to /home/rawr/.config/DeltaChat/config.json"
"2019-06-30T14:12:19.184Z"	"main/state"	"INFO"	[]	"Saving state to /home/rawr/.config/DeltaChat/config.json"
"2019-06-30T14:12:33.730Z"	"main/state"	"INFO"	[]	"Saving state to /home/rawr/.config/DeltaChat/config.json"
"2019-06-30T14:12:38.378Z"	"main/state"	"INFO"	[]	"Saving state to /home/rawr/.config/DeltaChat/config.json"

**Comment by ralphtheninja** [comment]
I've seen this as well. There might be some problem with rendering because I got a message from someone that I have never chatted with before, clicked around a bit and then it showed up.
