### ISSUE TITLE
delta chat messages aren't moved to the DeltaChat folder, despite settings

### ISSUE THREAD

**Issue by rawrrawrfox** [deltachat/deltachat-desktop#881]
- Platform (linux/mac/windows): Arch linux

- Delta Chat Desktop Version: 0.105.0-pre1-PREVIEW

- Expected behavior: 
Move chat related emais to DeltaChat folder on the email server, in accordance with the settings

- Actual behavior: 
messages go to inbox and aren't moved

- Steps to reproduce the problem:
make new email account (mine is on riseup.net) and install deltachat
log in
go to settings and enable "Watch Inbox folder", "Watch Sent folder" and "Watch DeltaChat folder" (the "Automatic Moves to DeltaChat folder" i think was enabled already)
add users, receive messages
login via the webmail interface and all messages are in inbox

- Screenshots:
[https://imgur.com/NwKuyIs](https://imgur.com/NwKuyIs)
[https://imgur.com/JEx3aeR](https://imgur.com/JEx3aeR)

- Logs:
"2019-06-30T12:56:44.078Z"	"main/index"	"INFO"	[]	"cwd /home/[redacted]/.config/DeltaChat"
"2019-06-30T12:56:44.110Z"	"main/menu"	"INFO"	[]	"rebuilding menu with locale en"
"2019-06-30T12:56:46.935Z"	"main/state"	"INFO"	[]	"Saving state to /home/[redacted]/.config/DeltaChat/config.json"
"2019-06-30T12:56:52.559Z"	"main/mainWindow"	"INFO"	[]	"toggleDevTools"
"2019-06-30T12:57:16.227Z"	"main/state"	"INFO"	[]	"Saving state to /home/[redacted]/.config/DeltaChat/config.json"
"2019-06-30T12:57:44.020Z"	"main/deltachat/login"	"INFO"	[]	"Using deltachat instance /home/[redacted]/.config/DeltaChat/7261777272617772666f78407269736575702e6e6574"
"2019-06-30T12:57:44.763Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":145,"fileName":"/opt/DeltaChat/electron_app/src/main/deltachat/index.js","functionName":"DeltaChat.dc.on","source":"    at DeltaChat.dc.on (/opt/DeltaChat/electron_app/src/main/deltachat/index.js:145:11)"},{"columnNumber":13,"lineNumber":182,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:182:13)"},{"columnNumber":12,"lineNumber":739,"fileName":"/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"handleEvent","source":"    at handleEvent (/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js:739:12)"},{"columnNumber":7,"lineNumber":35,"fileName":"/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"DeltaChat.binding.dcn_set_event_handler","source":"    at DeltaChat.binding.dcn_set_event_handler (/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js:35:7)"}]	"Not configured, cannot connect."
"2019-06-30T12:57:44.764Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":145,"fileName":"/opt/DeltaChat/electron_app/src/main/deltachat/index.js","functionName":"DeltaChat.dc.on","source":"    at DeltaChat.dc.on (/opt/DeltaChat/electron_app/src/main/deltachat/index.js:145:11)"},{"columnNumber":13,"lineNumber":182,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:182:13)"},{"columnNumber":12,"lineNumber":739,"fileName":"/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"handleEvent","source":"    at handleEvent (/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js:739:12)"},{"columnNumber":7,"lineNumber":35,"fileName":"/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"DeltaChat.binding.dcn_set_event_handler","source":"    at DeltaChat.binding.dcn_set_event_handler (/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js:35:7)"}]	"Not configured, cannot connect."
"2019-06-30T12:57:44.765Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":145,"fileName":"/opt/DeltaChat/electron_app/src/main/deltachat/index.js","functionName":"DeltaChat.dc.on","source":"    at DeltaChat.dc.on (/opt/DeltaChat/electron_app/src/main/deltachat/index.js:145:11)"},{"columnNumber":13,"lineNumber":182,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:182:13)"},{"columnNumber":12,"lineNumber":739,"fileName":"/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"handleEvent","source":"    at handleEvent (/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js:739:12)"},{"columnNumber":7,"lineNumber":35,"fileName":"/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"DeltaChat.binding.dcn_set_event_handler","source":"    at DeltaChat.binding.dcn_set_event_handler (/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js:35:7)"}]	"Not configured, cannot connect."
"2019-06-30T12:57:44.765Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":145,"fileName":"/opt/DeltaChat/electron_app/src/main/deltachat/index.js","functionName":"DeltaChat.dc.on","source":"    at DeltaChat.dc.on (/opt/DeltaChat/electron_app/src/main/deltachat/index.js:145:11)"},{"columnNumber":13,"lineNumber":182,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:182:13)"},{"columnNumber":12,"lineNumber":739,"fileName":"/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"handleEvent","source":"    at handleEvent (/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js:739:12)"},{"columnNumber":7,"lineNumber":35,"fileName":"/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"DeltaChat.binding.dcn_set_event_handler","source":"    at DeltaChat.binding.dcn_set_event_handler (/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js:35:7)"}]	"Not configured, cannot connect."
"2019-06-30T12:57:44.765Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":145,"fileName":"/opt/DeltaChat/electron_app/src/main/deltachat/index.js","functionName":"DeltaChat.dc.on","source":"    at DeltaChat.dc.on (/opt/DeltaChat/electron_app/src/main/deltachat/index.js:145:11)"},{"columnNumber":13,"lineNumber":182,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:182:13)"},{"columnNumber":12,"lineNumber":739,"fileName":"/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"handleEvent","source":"    at handleEvent (/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js:739:12)"},{"columnNumber":7,"lineNumber":35,"fileName":"/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"DeltaChat.binding.dcn_set_event_handler","source":"    at DeltaChat.binding.dcn_set_event_handler (/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js:35:7)"}]	"Not configured, cannot connect."
"2019-06-30T12:57:44.766Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":145,"fileName":"/opt/DeltaChat/electron_app/src/main/deltachat/index.js","functionName":"DeltaChat.dc.on","source":"    at DeltaChat.dc.on (/opt/DeltaChat/electron_app/src/main/deltachat/index.js:145:11)"},{"columnNumber":13,"lineNumber":182,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:182:13)"},{"columnNumber":12,"lineNumber":739,"fileName":"/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"handleEvent","source":"    at handleEvent (/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js:739:12)"},{"columnNumber":7,"lineNumber":35,"fileName":"/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"DeltaChat.binding.dcn_set_event_handler","source":"    at DeltaChat.binding.dcn_set_event_handler (/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js:35:7)"}]	"Not configured, cannot connect."
"2019-06-30T12:57:44.766Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":145,"fileName":"/opt/DeltaChat/electron_app/src/main/deltachat/index.js","functionName":"DeltaChat.dc.on","source":"    at DeltaChat.dc.on (/opt/DeltaChat/electron_app/src/main/deltachat/index.js:145:11)"},{"columnNumber":13,"lineNumber":182,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:182:13)"},{"columnNumber":12,"lineNumber":739,"fileName":"/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"handleEvent","source":"    at handleEvent (/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js:739:12)"},{"columnNumber":7,"lineNumber":35,"fileName":"/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"DeltaChat.binding.dcn_set_event_handler","source":"    at DeltaChat.binding.dcn_set_event_handler (/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js:35:7)"}]	"Not configured, cannot connect."
"2019-06-30T12:57:44.766Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":145,"fileName":"/opt/DeltaChat/electron_app/src/main/deltachat/index.js","functionName":"DeltaChat.dc.on","source":"    at DeltaChat.dc.on (/opt/DeltaChat/electron_app/src/main/deltachat/index.js:145:11)"},{"columnNumber":13,"lineNumber":182,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:182:13)"},{"columnNumber":12,"lineNumber":739,"fileName":"/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"handleEvent","source":"    at handleEvent (/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js:739:12)"},{"columnNumber":7,"lineNumber":35,"fileName":"/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js","functionName":"DeltaChat.binding.dcn_set_event_handler","source":"    at DeltaChat.binding.dcn_set_event_handler (/opt/DeltaChat/electron_app/node_modules/deltachat-node/lib/deltachat.js:35:7)"}]	"Not configured, cannot connect."
"2019-06-30T12:57:48.815Z"	"main/deltachat/login"	"INFO"	[]	"Ready"
"2019-06-30T12:57:48.820Z"	"main/deltachat/login"	"INFO"	[]	"dc_get_info"	{"deltachat_core_version":"v1.0.0-alpha.0","sqlite_version":"3.27.2","sqlite_thread_safe":"1","compile_date":"Apr 26 2019, 00:51:50","arch":"64","number_of_chats":"0","number_of_chat_messages":"0","messages_in_contact_requests":"0","number_of_contacts":"0","database_dir":"/home/[redacted]/.config/DeltaChat/7261777272617772666f78407269736575702e6e6574/db.sqlite","database_version":"55","blobdir":"/home/[redacted]/.config/DeltaChat/7261777272617772666f78407269736575702e6e6574/db.sqlite-blobs","display_name":"0","is_configured":"1","entered_account_settings":"[redacted]@riseup.net 0:***:0:0 0:0:0:0 0","used_account_settings":"[redacted]@riseup.net [redacted]:***:imap.riseup.net:993 [redacted]:***:mail.riseup.net:465 AUTH_NORMAL IMAP_SSL SMTP_SSL","inbox_watch":"0","sentbox_watch":"0","mvbox_watch":"0","mvbox_move":"0","folders_configured":"3","configured_sentbox_folder":"<unset>","configured_mvbox_folder":"<unset>","mdns_enabled":"0","e2ee_enabled":"1","private_key_count":"1","public_key_count":"0","fingerprint":"7620234E26139EDE27DD7E147473470B4FA2CC23","level":"awesome"}
"2019-06-30T12:57:49.817Z"	"main/state"	"INFO"	[]	"Saving state to /home/[redacted]/.config/DeltaChat/config.json"
"2019-06-30T12:57:53.104Z"	"main/state"	"INFO"	[]	"Saving state to /home/[redacted]/.config/DeltaChat/config.json"
"2019-06-30T12:58:44.941Z"	"main/deltachat/settings"	"INFO"	[]	"Setting config inbox_watch:1"
"2019-06-30T12:58:49.811Z"	"main/deltachat/settings"	"INFO"	[]	"Setting config sentbox_watch:1"
"2019-06-30T12:58:50.993Z"	"main/deltachat/settings"	"INFO"	[]	"Setting config mvbox_watch:1"
"2019-06-30T12:58:56.078Z"	"main/deltachat/settings"	"INFO"	[]	"Setting config mvbox_move:1"
"2019-06-30T12:59:45.938Z"	"main/state"	"INFO"	[]	"Saving state to /home/[redacted]/.config/DeltaChat/config.json"
"2019-06-30T13:18:07.325Z"	"main/state"	"INFO"	[]	"Saving state to /home/[redacted]/.config/DeltaChat/config.json"
"2019-06-30T13:20:14.028Z"	"main/deltachat/chatmethods"	"INFO"	[]	"chat with dead drop [object Object]"
"2019-06-30T13:20:14.118Z"	"main/deltachat/chatmethods"	"INFO"	[]	"Added contact [redacted] ([redacted]@riseup.net)"
"2019-06-30T13:20:50.389Z"	"main/state"	"INFO"	[]	"Saving state to /home/[redacted]/.config/DeltaChat/config.json"
"2019-06-30T13:21:02.807Z"	"main/state"	"INFO"	[]	"Saving state to /home/[redacted]/.config/DeltaChat/config.json"
"2019-06-30T14:09:42.820Z"	"main/state"	"INFO"	[]	"Saving state to /home/[redacted]/.config/DeltaChat/config.json"
"2019-06-30T14:12:19.184Z"	"main/state"	"INFO"	[]	"Saving state to /home/[redacted]/.config/DeltaChat/config.json"
"2019-06-30T14:12:33.730Z"	"main/state"	"INFO"	[]	"Saving state to /home/[redacted]/.config/DeltaChat/config.json"
"2019-06-30T14:12:38.378Z"	"main/state"	"INFO"	[]	"Saving state to /home/[redacted]/.config/DeltaChat/config.json"

**Comment by Jikstra** [comment]
Does it move newer mails or nothing? I think deltachat will only start moving messages that get into your inbox after you enabled that setting. @r10s any ideas?

**Comment by rawrrawrfox** [comment]
no it doesn't move anything, i've had the setting enabled since the start
should it be attempting to create a DeltaChat folder automatically? if not could it be due to no DeltaChat folder existing in the email server?

**Comment by Jikstra** [comment]
It normally creates the folder automatically, not sure what's wrong here. This seems more like a core problem to me, the desktop app isn't doing any logic on that moving stuff besides enabling/disabling. What e-mail provider/server are you using?

**Comment by Jikstra** [comment]
@rawrrawrfox can you test the new pre2 preview release? It's possible that this was a bug in the new deltachat rust core.

**Comment by Jikstra** [comment]
Should be fixed by https://github.com/deltachat/deltachat-desktop/pull/939 everything else is a core bug.
