### ISSUE TITLE
Rethink MessageList and fix problems with current implementation

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-desktop#885]
Somehow the scroll position is calculated wrong when new a new set of messages is loaded...

**Comment by nicodh** [comment]
After diving into the code, I wonder when this did break or if it ever worked as expected. It seems fetching messages is triggered up to 3 times depending on how fast I scroll, which results in 3 fast updates (3 times adding 20 messages) which causes jumps. It also happens quite often, that setting this.doc.scrollTop does not result in the expected scroll position (scroll bar still sticks to the top although scrollTop was a value > 1000)

I think we should consider using a ready made library for that like https://github.com/bvaughn/react-window together with https://github.com/bvaughn/react-window-infinite-loader

**Comment by Jikstra** [comment]
Yes. But probably it's fine to first fix the bug that it's getting loaded three times and jumps as besides this it works quite well.

**Comment by nicodh** [comment]
It seems to happen only on Mac. Maybe because of Macs "slide" scroll feature (which I really miss on Linux so far). It means if you scroll fast the scrolling on the element (page) continues even after stopping it on the touch pad. So probably it continuously  fires scroll event although there is nothing more to scroll (because the limit is reached). The jumps only occur from time to time - seems to be related to images since it seems to work if only text messages are loaded. I would suggest to close this and see if people have problems with it
