### ISSUE TITLE
Crash by choose "new chat"

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-desktop#886]
- Platform (linux/mac/windows): Kubuntu 18.04
- Delta Chat Desktop Version: 0.104.0 Preview
- Expected behavior: Start a new Chat by click the Menu item "New Chat"
- Actual behavior: The window freezes
- Steps to reproduce the problem:
1. Open the desktop client
2. Open the "three dot" menu
3. Click "New Chat"
4. The window freezes

**Comment by Simon-Laux** [comment]
do you have logs?

**Comment by webratte** [comment]
I've just seen there is a new preview out.

I will test this version later and if it's still not work I will offer a log

**Comment by webratte** [comment]
The new version Version 0.105.0-pre2-PREVIEW fixed it for me :+1: 

I will close this issue
