### ISSUE TITLE
"normal" e-Mails are shown that are not DeltaChat messages

### ISSUE THREAD

**Issue by silberzwiebel** [deltachat/deltachat-desktop#887]
- Platform (linux/mac/windows): Fedora Linux 30
- Delta Chat Desktop Version: 0.102.0 - PREVIEW
- Expected behavior: I only see chats I started with DeltaChat on my Android-Phone
- Actual behavior: I see random other e-mails, preferably with more than one recipient, popping up in the DeltaChat desktop program.
- Steps to reproduce the problem: just login and see e-mails (not DeltaChat-Emails) popping up.

My e-Mail Provider is posteo.de, if that matters.

**Comment by hpk42** [comment]
please install the recent version (0.104) and check out the new "e-mail interaction" settings. If problem persists please re-open/open a new issue.

**Comment by silberzwiebel** [comment]
Oh, sorry for the noise. My deltachat upgraded some days ago, so I thought I'm on the current version. I'll need to wait for https://github.com/flathub/chat.delta.desktop/pull/20 and will report back if the problem persists. Thanks for your work!
