### ISSUE TITLE
Security Alerts

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#901]
![Screenshot from 2019-07-23 00-38-43](https://user-images.githubusercontent.com/308049/61669977-4b742500-ace2-11e9-8eba-1aeff3a63831.png)

https://github.com/deltachat/deltachat-desktop/network/alerts

**Comment by nicodh** [comment]
This should be obsolete soon, when we have the hallmark update in a new deltachat-node npm release.
The outdated lodash dependencies should be removed with deltachat/deltachat-node#647cde00a

**Comment by Jikstra** [comment]
It's fixed
