### ISSUE TITLE
rust-master attachments weirdly becomes Autocrypt Setup Messages

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#903]
Using rust-master, when sending an attachment, the message is displayed as an ASM in the chat-view, and correctly as file-attach in the chatlist view.  If someone could kindly identify precisely which core-api sequence is used for getting the wrong type in the chat view, we could probably quickly test and fix it in core.

**Comment by Simon-Laux** [comment]
still happening? Which filetype did you sent?

**Comment by Jikstra** [comment]
Didn't see this in a while

**Comment by Simon-Laux** [comment]
Try with html files

Am 8. September 2019 23:31:13 MESZ schrieb Jikstra <notifications@github.com>:
>Didn't see this in a while
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/deltachat/deltachat-desktop/issues/903#issuecomment-529243592

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Jikstra** [comment]
Shows as a .html but sent it to myself. Don't have a 2 account setup currently so cant test that.
