### ISSUE TITLE
Automate Readme Screenshot generation

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#907]
It's good for now I think, but we should really spend more time on it to make sure it shows most features (everything is not possible). For example:

* group chats
* icon in a group chat
* markdown
* emojis in the chat (now only showing in the input field)

_Originally posted by @ralphtheninja in https://github.com/deltachat/deltachat-desktop/issues/746#issuecomment-499928729_

Also i'm really thinking of having a better way to generate those pictures. Can we maybe set up one config folder which has some good presettings for this? Like a set up group, one verified... so that we don't have to redo this again and again?

_Originally posted by @Jikstra in https://github.com/deltachat/deltachat-desktop/issues/746#issuecomment-500222869_

**Comment by Jikstra** [comment]
Maybe we can also create a dummy state which we inject into the renderer? Shouldn't be too hard, maybe some extra maintenance.

**Comment by Jikstra** [comment]
Lets just use backups for this
