### ISSUE TITLE
"Login" button isn't disabled inmediately after click

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#910]
When I click the "Login" button nothing happens, there are not immediate feedback, the button remains clickable some seconds enough to wonder if it worked and try to click it one or two more times ;) then finally a progress bar  appears and it is disabled.

- Platform (linux/mac/windows): GNU/Linux
- Delta Chat Desktop Version: 0.105.0-pre2-PREVIEW
- Steps to reproduce the problem: Maybe this delay is only perceptible in slow networks?

**Comment by Jikstra** [comment]
Looks like we're doing this with line of code which looks a bit weird:
https://github.com/deltachat/deltachat-desktop/blob/master/src/renderer/components/Login.js#L246

Not sure why we're mapping over the childrens and looking for the submit button. Weird code.

**Comment by pabzm** [comment]
This appears to be a cosmetic problem, not an actual bug, and has not seen activity since a while, thus closing.
