### ISSUE TITLE
Various interface Update Bugs

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#916]
- ~~Creating a new group doesn't change the screen.~~
- ~~Deleting currently active chat doesn't update selected chat~~
- leaving a group doesn't change the member count

**Comment by Simon-Laux** [comment]
leave group should not unselect the chat, also the media buttons in the nav bar are still visible in this case and in the also in the other cases:
![2019-08-05_20-23](https://user-images.githubusercontent.com/18725968/62486208-e975ee00-b7be-11e9-8c4b-0725b010a668.png)

**Comment by r10s** [comment]
@Simon-Laux why is this a blocker :) cmp #992

**Comment by Simon-Laux** [comment]
missing/lacking visual feedback on actions is bad

**Comment by Simon-Laux** [comment]
having #697 is enough so I close this now
