### ISSUE TITLE
Delta Chat para windows 32bit

### ISSUE THREAD

**Issue by hegosoft** [deltachat/deltachat-desktop#920]
- Platform (linux/mac/windows): windows 32bit
- Delta Chat Desktop Version: 0.105.0
- Expected behavior:
- Actual behavior:
- Steps to reproduce the problem: There is no compiled version for 32 bit
- Screenshots:
- Logs:

**Comment by ralphtheninja** [comment]
Are we really doing this? Are there many out there using 32 bit windows?

**Comment by 0xC4N1** [comment]
Currently 85.928% of Firefox users are using a 64-bit Windows according to the Firefox Public Data Report.

[![firefox-windows-architecture-metrics](https://user-images.githubusercontent.com/7902457/63193330-7b0e1700-c06d-11e9-9948-3c0af684522f.png)](https://data.firefox.com/dashboard/hardware)

**Comment by hegosoft** [comment]
It is true that 80% use 64-bit operating systems but why not support that 20% it is also true that some of us have old PCs and we want to make use of this software I think it would not be so difficult.
20% is a somewhat small percentage but if 100 million users use windows windows then 20 million use windows 32 bit are not few, it is worth the effort

**Comment by Jikstra** [comment]
Sadly electron is not really suited for old pcs as it wastes too many resources. I would accept a pr to deltachat-node to build prebuilts for 32bit on ci and same for desktop. But I myself don't see a point in implementing this. Sorry :/
