### ISSUE TITLE
Theming prs broke some styling

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#924]
The interface got a bit uglier with the theming pr, guess there are some bugs.

**Comment by Simon-Laux** [comment]
you mean the lightgreen background?

**Comment by nicodh** [comment]
the background of the chat view (messages) - it's not light green but "poison green" ;-)
Why did that change? The background looked not bad and was/should be the same as in the app (as default)

**Comment by Simon-Laux** [comment]
for testing and I forgot to change it back to `#e6dcd4` from `lime`

**Comment by Jikstra** [comment]
There's more broken:
- scrollbarcolor/hover in chat list
- color of checkboxes in settings
- the menu on the three dots
- color of callouts
- probably more

**Comment by Simon-Laux** [comment]
I mention the todo section in the `THEMES.md` doc file which contains more things that need to be included into theming.
Also can you be more specific than saying broken here? what do you mean by broken? I would rather use words like missing in the theme system and looking bad / needs adjustment.

**Comment by Jikstra** [comment]
Looks bad because of wrong colors ^^
