### ISSUE TITLE
Chat list showing chats with "Me" instead of names

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#926]
- Platform (linux/mac/windows): linux
- Delta Chat Desktop Version: commit f00ec6532c6be58fd093984c57bf66cc1e624349
- Expected behavior: 
- Actual behavior:
- Steps to reproduce the problem:
- Screenshots:
- Logs:

Below shows chats where I'm chatting with another person (two different chats and persons)

![testing](https://user-images.githubusercontent.com/308049/62425190-9c1f5100-b6d8-11e9-839c-7246b7b7e344.png)

**Comment by Jikstra** [comment]
Yup, having that too but i think it's a core bug.

**Comment by Jikstra** [comment]
I think it got fixed in core.
