### ISSUE TITLE
Theming bugs

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#938]
- [ ] Background color of emoji selctor is not white
- [ ] toggles in settings are weird
- [ ] in settings we get some weird `:active` `:focus` borders on some elements. We should remove them.

**Comment by Simon-Laux** [comment]
whats with the rest from `docs/theming`?

>  in settings we get some weird :active :focus borders on some elements. We should remove them.

I'm 90% sure that was already there before the whole theming thing.

> Background color of emoji selctor is not white

should it be white? not the dialog color?

**Comment by Jikstra** [comment]
The dialogBackgroundColor is not really the background color (only for the css/html/layering) but actually it's only the color of the stuff between the callout. We should give it a better name.
