### ISSUE TITLE
Change from Android usage to Windows AND Android

### ISSUE THREAD

**Issue by aheidemann** [deltachat/deltachat-desktop#967]
- Platform (linux/mac/windows):
Windows 10, Android
- Delta Chat Desktop Version:
Version 0.105.0-pre1-PREVIEW , Android client 0.510.1
- Expected behavior:
When login with an existing account used on android phone and import the secret key from these android phone, I expect the old messages, contacts and groups to appear as in android, because the information is saved in delta.chat folder of the email account
- Actual behavior:
After login and importing the secret key from android into windows client, no content is shown in the windows client
- Steps to reproduce the problem:
1. Install and use android client
2. export secret key there 
3. install windows client
4. Import secrect key there
5. Observe windows client content, (with none available)
- Screenshots:
- Logs:

**Comment by Simon-Laux** [comment]
You need to use a backup for this, keytransfer only transfers the key.
There is a feature request on the forum about downloading the history from the email server:
https://support.delta.chat/t/workaround-make-new-delta-chat-installation-import-old-messages-from-imap-directory/262/27
