### ISSUE TITLE
How to fix a wrong language name

### ISSUE THREAD

**Issue by OzancanKaratas** [deltachat/deltachat-desktop#973]
@Simon-Laux I found a wrong language name. “language_be” is Belgian at the moment, should be Belarusian. I don't know which project I must edit.

**Comment by flub** [comment]
Belgian shouldn't exist afaik. It should be nl or fr for Belgium. So be can
be turned into Belarusian

**Comment by Jikstra** [comment]
@OzancanKaratas in this file you can change it, but, it's somehow auto generated https://github.com/deltachat/deltachat-desktop/blob/master/_locales/_languages.json. 

This script does that, not sure why it comes up with Belgian for Belarusian.
https://github.com/deltachat/deltachat-desktop/blob/master/bin/convert-translations-from-xml-to-json.js

**Comment by Simon-Laux** [comment]
No `_locales/_languages.json` Isn't autogenerated anymore. you need to edit language names in directly `_locales/_languages.json`

**Comment by OzancanKaratas** [comment]
Can you do it for me? I couldn't find.
