### ISSUE TITLE
The chat list jumps more around than ever

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#975]
with chats on the top that don't have any new messages

**Comment by Jikstra** [comment]
Seems like this happens as soon as we have incoming messages?

**Comment by Simon-Laux** [comment]
yeah

**Comment by nicodh** [comment]
Should be fixed with 7865d438
Can you check again?

**Comment by nicodh** [comment]
In my test after importing an old backup the chat list was very smooth while loading hundreds of messages...

**Comment by Simon-Laux** [comment]
now it doesn't update anymore until I click on something

**Comment by Simon-Laux** [comment]
Also after importing an backup to give it a second chance the rust core crashes on me as soon as I open the account. I'm looking more into that crash tomorrow as I was already in the process of going to bed.

**Comment by nicodh** [comment]
> now it doesn't update anymore until I click on something
that can't be related to the last commit, it only changes the properties in the sort function...??

**Comment by Simon-Laux** [comment]
I close this as it doesn't jump around anymore
