### ISSUE TITLE
CI build is broken

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-desktop#977]
It seems with cc7914a02c the CI build is broken, complaining "Could not find cargo"

**Comment by Jikstra** [comment]
I think ci can't handle deltachat-node directly from git repo

**Comment by nicodh** [comment]
any ideas how to fix this? Otherwise I would prefer to bind to dc-node release again

**Comment by nicodh** [comment]
Fixed with e4bae836f60a0
