### ISSUE TITLE
What does "Enter key sents" switch does?

### ISSUE THREAD

**Issue by KAction** [deltachat/deltachat-desktop#982]
Here are two screenshots of settings with "Enter key sends" toggle. Whether it is on or off, text is same, so I am confused. Probably, it is about Enter vs Ctrl-Enter, like in Telegram. Please, make text describe what is currently configured state.

git:  [c568ff]

![foo1](https://user-images.githubusercontent.com/44864956/64742284-37cb8a80-d4eb-11e9-8ab6-5f58c1b80ac1.png)
![foo2](https://user-images.githubusercontent.com/44864956/64742288-3b5f1180-d4eb-11e9-90df-73eb79614673.png)

**Comment by nicodh** [comment]
I would say that's common behavior. The text remains the same but the button can be on or off. That's how all the settings buttons in Android or Iphone look like...

**Comment by pabzm** [comment]
All our boolean settings have a fixed text-label that doesn't change when toggled. We can't change that just for one setting.
If we'd have many issues in which people report problems with the toggle buttons we could discuss how to improve the UI, but currently that apparently isn't the case.
