### ISSUE TITLE
License is incompatible to deltachat-node

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop#987]
Deltachat-node is `GPL-3.0`, but deltachat-desktop is `GPL-3.0-or-later`.

That probably needs to be resolved in deltachat-node, which does not specify the license clearly enough (no source code headers etc.).

**Comment by Jikstra** [comment]
I don't know much about licensing, but does 3.0-or-later not include 3.0?

**Comment by link2xt** [comment]
Deltachat-node is licensed as GPL-3.0 *only*. Deltachat-desktop is licensed GPL-3.0 or later, which means user is allowed to use it under GPL-4.0 if/when FSF publishes it. But it is not allowed by the deltachat-node license.

**Comment by ralphtheninja** [comment]
@link2xt Where does it say that `deltachat-desktop` is licensed `GPL-3.0-or-later`? The `LICENSE` file and `README.md` says the same as `deltachat-node` afaict.

**Comment by ralphtheninja** [comment]
Oh nvm, it's in `package.json`. So it seems we're sending off mixed signals in desktop if the `LICENSE` file and `README.md` says otherwise than the `license` field in `package.json`.

Should we fix `package.json` or `LICENSE` / `README.md` files?

**Comment by ralphtheninja** [comment]
Seems the contents of the `LICENSE` file is correct, so we're left with

* update `README.md` in `deltachat-desktop`
* update `README.md`, `LICENSE` and `package.json` in `deltachat-node`
