### ISSUE TITLE
Block contact needs some ui/ux love

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-desktop#992]
works but looks bad...

**Comment by nicodh** [comment]
works but looks bad...

**Comment by r10s** [comment]
> works but looks bad

@Simon-Laux so this should not be blocker then?

**Comment by Simon-Laux** [comment]
It is also unresponsive - like I unblock a contact an get no visual feedback whatsoever

**Comment by pabzm** [comment]
Unblocking a contact removes it from the list, that is visual feedback, isn't it?

To me and @r10s the feature feels ok, thus I'm closing it. If someone thinks this does need more love, please concretely describe what is lacking.
