### ISSUE TITLE
Archived chat shouldn't call getDraft

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#996]
As this triggers an ugly red error:
```
main/deltachat DEBUG [] Core Event DC_EVENT_ERROR  Failed to get draft for chat #6: "Invalid chat ID"
```
Also maybe we could also bring back the old design from that pseudo-chatlist-item.

**Comment by ralphtheninja** [comment]
I also have this issue.

**Comment by Jikstra** [comment]
Will be fixed by https://github.com/deltachat/deltachat-core-rust/pull/590
