### ISSUE TITLE
CI: Add AppVeyor script for Windows builds

### ISSUE THREAD

**Issue by OzancanKaratas** [deltachat/deltachat-desktop#998]
Hi,

AppVeyor creates builds for Windows. I think we should open a branch and allow AppVeyor to create Delta Chat builds. Also we can test the builds using a beta branch. Final versions can be built by AppVeyor on master.

**Comment by Simon-Laux** [comment]
I think getting the prebuild for node / building node is the challenge we need to tackle first, besides that cross compiling / packaging the electron app works fine.

**Comment by Jikstra** [comment]
> I think getting the prebuild for node / building node is the challenge we need to tackle first, besides that part cross compiling / packaging the electron app would work fine.

I already fixed them some time ago, so this should be quite easy now. I think we should be able to copy most of this file https://github.com/deltachat/deltachat-node/blob/master/appveyor.yml

**Comment by Jikstra** [comment]
We don't need this anymore as we can build releases for any os on almost any os (except dmg on a non mac). Thanks to electron-builder :)
